import {createRetrievalQuery} from './retrieval-bridge.browser.mjs';
import {createAuthorizedTransport} from './authorized-transport.mjs';
import {connectionConfig,sealedLibrary} from './mount-config.mjs';
const TEXT={es:{subtitle:'Asistente de Iris Green',unavailable:'Consultas no disponibles todavía',available:'Consulta de fuentes disponible',hide:'Ocultar',show:'Mostrar',welcome:'Estoy aquí si quieres ayuda.',explanation:'La consulta de fuentes aún no está disponible. Puedes usar el buscador y las secciones de Iris Green.',connected:'Busca información en las fuentes de Iris Green. No hace diagnósticos.',label:'¿Qué necesitas?',help:'Hasta 300 caracteres. Enter añade una línea; Ctrl+Enter envía.',send:'Enviar',cancel:'Cancelar consulta',low:'Bajar intensidad',reset:'Empezar de nuevo',motion:'Movimiento de Sabik',normal:'Normal',reduced:'Reducido',still:'Sin movimiento',motionHelp:'Movimiento breve solo cuando hace falta.',memory:'No guarda historial entre sesiones.',limits:'Comprueba la información importante en las fuentes. Sabik no hace diagnósticos.',browse:'Explorar los recursos',placeholder:'Por ejemplo: el ruido me agota',cleared:'La consulta y los resultados se han borrado.',busy:'Buscando en las fuentes de Iris Green.',error:'No se pudo conectar. Puedes intentarlo de nuevo o usar el buscador de Iris Green.',empty:'Escribe qué necesitas.',spanish:'Las citas originales están en español.'},en:{subtitle:'Iris Green assistant',unavailable:'Queries are not available yet',available:'Source search available',hide:'Hide',show:'Show',welcome:'I am here if you need help.',explanation:'Source search is not available yet. You can use the Iris Green search and sections.',connected:'Search information from Iris Green sources. It does not make diagnoses.',label:'What do you need?',help:'Up to 300 characters. Enter adds a new line; Ctrl+Enter sends.',send:'Send',cancel:'Cancel query',low:'Lower intensity',reset:'Start again',motion:'Sabik motion',normal:'Normal',reduced:'Reduced',still:'No motion',motionHelp:'Brief motion only when needed.',memory:'No history is saved between sessions.',limits:'Check important information against the sources. Sabik does not make diagnoses.',browse:'Explore resources',placeholder:'For example: noise drains me',cleared:'Your query and results have been cleared.',busy:'Searching Iris Green sources.',error:'Could not connect. Try again or use the Iris Green search.',empty:'Write what you need.',spanish:'Original quotations are in Spanish.'}};
function mount(){
 const aside=document.querySelector('.sabik-panel');if(!aside)return;
 const $=s=>aside.querySelector(s),input=$('#sabik-input'),announcement=$('#sabik-announcement'),root=$('#sabik-results');
 const connection=connectionConfig.enabled?createAuthorizedTransport({cloudOrigin:connectionConfig.cloudOrigin}):null;
 const query=createRetrievalQuery({transport:connection?.transport||(()=>Promise.reject(new Error('LIBRARY_UNAVAILABLE'))),library:sealedLibrary});
 let lang=document.documentElement.lang.startsWith('en')?'en':'es',serial=0,busy=false,low=false;
 const strings=()=>TEXT[lang],say=text=>{announcement.textContent=text;},visual=(state,options)=>window.SabikWebPresentation?.setSabikState(state,options);
 let panel=window.SabikRetrievalPanel.createRetrievalPanel({root,query,announcement,language:lang});
 function controls(){ $('#sabik-submit').disabled=!connection||!input.value.trim();$('#sabik-cancel').hidden=!busy; }
 function translate(){const next=document.documentElement.lang.startsWith('en')?'en':'es';lang=next;aside.lang=lang;announcement.lang=lang;aside.querySelectorAll('[data-sabik-text]').forEach(el=>el.textContent=strings()[el.dataset.sabikText]);$('#sabik-toggle').textContent=$('#sabik-widget-body').hidden?strings().show:strings().hide;input.placeholder=strings().placeholder;$('#sabik-browse').href=lang==='en'?'/en/resources/':'/es/recursos/';if(connection){aside.querySelector('.sabik-state').textContent=strings().available;$('#sabik-availability').textContent=strings().connected+(lang==='en'?' '+strings().spanish:'');}panel.setLanguage(lang);controls();}
 async function submit(event){event.preventDefault();if(!connection){say(strings().explanation);return;}if(!input.value.trim()){say(strings().empty);input.focus();return;}const ticket=++serial;panel.cancel();busy=true;controls();say(strings().busy);try{await connection.connect(lang);if(ticket!==serial)return;await panel.run({query:input.value.trim(),limit:10});}catch{if(ticket===serial)say(strings().error);}finally{if(ticket===serial){busy=false;controls();}}}
 $('#sabik-form').addEventListener('submit',submit);input.addEventListener('input',controls);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();$('#sabik-form').requestSubmit();}});
 $('#sabik-cancel').addEventListener('click',()=>{serial++;panel.cancel();connection?.disconnect();busy=false;controls();input.focus();});
 $('#sabik-toggle').addEventListener('click',()=>{const body=$('#sabik-widget-body');body.hidden=!body.hidden;$('#sabik-toggle').setAttribute('aria-expanded',String(!body.hidden));$('#sabik-toggle').textContent=body.hidden?strings().show:strings().hide;if(!body.hidden)visual('transicion');});
 $('#sabik-low').addEventListener('click',()=>{low=!low;aside.dataset.low=String(low);$('#sabik-low').setAttribute('aria-pressed',String(low));window.SabikWebPresentation?.render({interaction:'espera',lowIntensity:low,protection:'normal'});});
 $('#sabik-reset').addEventListener('click',()=>{serial++;panel.cancel();connection?.disconnect();input.value='';root.replaceChildren();panel=window.SabikRetrievalPanel.createRetrievalPanel({root,query,announcement,language:lang});busy=false;controls();say(strings().cleared);visual('transicion');input.focus();});
 window.addEventListener('pagehide',()=>{serial++;panel.cancel();connection?.disconnect();});
 new MutationObserver(translate).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});translate();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
