import {createRetrievalQuery} from './retrieval-bridge.browser.mjs';
import {createAuthorizedTransport} from './authorized-transport.mjs';
import {connectionConfig,sealedLibrary} from './mount-config.mjs';
import {createSabikVoice} from './sabik-voice-r01.mjs';
const TEXT={es:{subtitle:'Asistente de Iris Green',unavailable:'La búsqueda en fuentes todavía no está disponible.',available:'La búsqueda en fuentes está disponible.',hide:'Ocultar',show:'Mostrar',welcome:'Puedo ayudarte a buscar información.',explanation:'La búsqueda en las fuentes todavía no está disponible. Puedes usar el buscador y las secciones de Iris Green.',connected:'Puedo buscar información en las fuentes de Iris Green. No hago diagnósticos.',label:'¿Qué necesitas?',help:'Hasta 300 caracteres. Enter añade una línea; Ctrl+Enter envía.',send:'Enviar',cancel:'Cancelar consulta',low:'Desactivar movimiento',reset:'Empezar de nuevo',motion:'Movimiento de Sabik',normal:'Normal',reduced:'Reducido',still:'Sin movimiento',motionHelp:'Movimiento breve cuando cambia el estado.',memory:'No se guarda el historial entre sesiones.',limits:'Comprueba la información importante en las fuentes. Sabik no realiza diagnósticos.',browse:'Explorar los recursos',placeholder:'Por ejemplo: el ruido me agota',cleared:'La consulta y los resultados se han borrado.',busy:'Buscando en las fuentes de Iris Green.',error:'No se pudo conectar. Puedes intentarlo de nuevo o usar el buscador de Iris Green.',empty:'Escribe qué necesitas.',spanish:'Las citas originales están en español.',voice:'Voz de Sabik',voiceOn:'Activada',voiceOff:'Desactivada',voiceHelp:'Solo reproduce mensajes fijos cuando la activas.',resultsOne:'1 resultado disponible.',resultsMany:n=>`${n} resultados disponibles.`},en:{subtitle:'Iris Green assistant',unavailable:'Source search is not available yet.',available:'Source search is available.',hide:'Hide',show:'Show',welcome:'I can help you find information.',explanation:"Source search is not available yet. You can use Iris Green's search and sections.",connected:"I can search Iris Green's sources for information. I don't make diagnoses.",label:'What do you need?',help:'Up to 300 characters. Enter adds a new line; Ctrl+Enter sends.',send:'Send',cancel:'Cancel query',low:'Turn off motion',reset:'Start again',motion:'Sabik motion',normal:'Normal',reduced:'Reduced',still:'No motion',motionHelp:'Brief motion when the state changes.',memory:'No history is saved between sessions.',limits:'Check important information against the sources. Sabik does not make diagnoses.',browse:'Explore resources',placeholder:'For example: noise drains me',cleared:'Your query and results have been cleared.',busy:'Searching Iris Green sources.',error:"Could not connect. You can try again or use Iris Green's search.",empty:'Write what you need.',spanish:'The original quotations are in Spanish.',voice:'Sabik voice',voiceOn:'On',voiceOff:'Off',voiceHelp:'Only plays fixed messages when you turn it on.',resultsOne:'1 result available.',resultsMany:n=>`${n} results available.`}};
function mount(){
 const aside=document.querySelector('.sabik-panel');if(!aside)return;
 const $=s=>aside.querySelector(s),input=$('#sabik-input'),announcement=$('#sabik-announcement'),root=$('#sabik-results'),voiceButton=$('#sabik-voice'),voiceState=$('#sabik-voice-state');
 const connection=connectionConfig.enabled?createAuthorizedTransport({cloudOrigin:connectionConfig.cloudOrigin}):null;
 const query=createRetrievalQuery({transport:connection?.transport||(()=>Promise.reject(new Error('LIBRARY_UNAVAILABLE'))),library:sealedLibrary});
 let lang=document.documentElement.lang.startsWith('en')?'en':'es',serial=0,busy=false;
 const strings=()=>TEXT[lang],visual=(state,options)=>window.SabikWebPresentation?.setSabikState(state,options);
 const voice=createSabikVoice({getLanguage:()=>lang,onEnabledChange:syncVoice});
 let panel=window.SabikRetrievalPanel.createRetrievalPanel({root,query,announcement,language:lang});
 function syncVoice(){const on=voice.enabled();voiceButton.setAttribute('aria-pressed',String(on));voiceState.textContent=on?strings().voiceOn:strings().voiceOff;voiceButton.setAttribute('aria-label',`${strings().voice}: ${on?strings().voiceOn:strings().voiceOff}`);announcement.dataset.sabikVoice=String(on);announcement.setAttribute('aria-live',on?'off':'polite');}
 function say(text,{voiceId=null,allowOptional=false}={}){if(voiceId&&voice.enabled()){announcement.textContent=text;void voice.speak(voiceId,text,{allowOptional});}else{announcement.setAttribute('aria-live','polite');announcement.textContent=text;}}
 function controls(){ $('#sabik-submit').disabled=!connection||!input.value.trim();$('#sabik-cancel').hidden=!busy; }
 function translate(){const next=document.documentElement.lang.startsWith('en')?'en':'es',changed=next!==lang;if(changed)voice.stop();lang=next;aside.lang=lang;announcement.lang=lang;aside.querySelectorAll('[data-sabik-text]').forEach(el=>el.textContent=strings()[el.dataset.sabikText]);$('#sabik-toggle').textContent=$('#sabik-widget-body').hidden?strings().show:strings().hide;input.placeholder=strings().placeholder;$('#sabik-browse').href=lang==='en'?'/en/resources/':'/es/recursos/';if(connection){aside.querySelector('.sabik-state').textContent=strings().available;$('#sabik-availability').textContent=strings().connected+(lang==='en'?' '+strings().spanish:'');}panel.setLanguage(lang);syncVoice();controls();}
 async function submit(event){event.preventDefault();if(!connection){say(strings().explanation,{voiceId:'sabik.capability.offline'});return;}if(!input.value.trim()){say(strings().empty,{voiceId:'sabik.input.empty'});input.focus();return;}const ticket=++serial;panel.cancel();busy=true;controls();say(strings().busy,{voiceId:'sabik.search.busy'});try{await connection.connect(lang);if(ticket!==serial)return;await panel.run({query:input.value.trim(),limit:10});}catch{if(ticket===serial)say(strings().error,{voiceId:'sabik.connection.error'});}finally{if(ticket===serial){busy=false;controls();}}}
 function resultVoice(){const state=root.dataset.retrievalState;if(state==='results'){voice.stop();if(voice.enabled()){const count=root.querySelectorAll('.sabik-retrieval-result').length;announcement.setAttribute('aria-live','polite');announcement.textContent=count===1?strings().resultsOne:strings().resultsMany(count);queueMicrotask(()=>{if(voice.enabled())announcement.setAttribute('aria-live','off');});}return;}const ids={empty:'sabik.results.empty',error:'sabik.results.error',cancelled:'sabik.results.cancelled'};const id=ids[state],text=root.querySelector('.sabik-notice')?.textContent;if(id&&text&&voice.enabled())void voice.speak(id,text);}
 new MutationObserver(resultVoice).observe(root,{attributes:true,attributeFilter:['data-retrieval-state']});
 $('#sabik-form').addEventListener('submit',submit);input.addEventListener('input',controls);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();$('#sabik-form').requestSubmit();}});
 $('#sabik-cancel').addEventListener('click',()=>{serial++;panel.cancel();connection?.disconnect();busy=false;controls();input.focus();});
 $('#sabik-toggle').addEventListener('click',()=>{const body=$('#sabik-widget-body');body.hidden=!body.hidden;$('#sabik-toggle').setAttribute('aria-expanded',String(!body.hidden));$('#sabik-toggle').textContent=body.hidden?strings().show:strings().hide;if(!body.hidden)visual('transicion');});
 voiceButton.addEventListener('click',()=>{const on=voice.toggle();syncVoice();if(on)void voice.speak('sabik.welcome',strings().welcome);});
 $('#sabik-low').addEventListener('click',()=>{const motion=$('#sabik-motion-level');motion.value='SIN_MOVIMIENTO';$('#sabik-low').setAttribute('aria-pressed','true');motion.dispatchEvent(new Event('change',{bubbles:true}));});
 $('#sabik-motion-level').addEventListener('change',()=>{$('#sabik-low').setAttribute('aria-pressed',String($('#sabik-motion-level').value==='SIN_MOVIMIENTO'));});
 $('#sabik-reset').addEventListener('click',()=>{serial++;panel.cancel();connection?.disconnect();voice.stop();input.value='';root.replaceChildren();panel=window.SabikRetrievalPanel.createRetrievalPanel({root,query,announcement,language:lang});busy=false;controls();say(strings().cleared,{voiceId:'sabik.reset.confirmation'});visual('transicion');input.focus();});
 window.addEventListener('pagehide',()=>{serial++;panel.cancel();connection?.disconnect();voice.dispose();});
 new MutationObserver(translate).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});translate();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
