"""Traducciones al español de los textos de Blockly 13 que vienen sin traducir
(sobre todo accesibilidad: anuncios, etiquetas ARIA, atajos de teclado).
Genera assets/vendor/taller/blockly-msg-extra.js. Traducción hecha en este carril."""
from pathlib import Path
import json, re

ES = {
    'ANNOUNCE_CANT_SCROLL_FURTHER': 'No se puede desplazar más.',
    'ANNOUNCE_MOVE_AFTER': 'Moviendo %1 detrás de %2.',
    'ANNOUNCE_MOVE_AROUND': 'Moviendo %1 alrededor de %2.',
    'ANNOUNCE_MOVE_BEFORE': 'Moviendo %1 delante de %2.',
    'ANNOUNCE_MOVE_CANCELED': 'Movimiento cancelado.',
    'ANNOUNCE_MOVE_INSIDE': 'Moviendo %1 dentro de %2.',
    'ANNOUNCE_MOVE_OF': '%1 de %2',
    'ANNOUNCE_MOVE_TO': 'Moviendo %1 a %2.',
    'ANNOUNCE_MOVE_WORKSPACE': 'Moviendo %1 por el área de trabajo.',
    'ANNOUNCE_SCROLLED_DOWN': 'Desplazado hacia abajo.',
    'ANNOUNCE_SCROLLED_LEFT': 'Desplazado hacia la izquierda.',
    'ANNOUNCE_SCROLLED_RIGHT': 'Desplazado hacia la derecha.',
    'ANNOUNCE_SCROLLED_UP': 'Desplazado hacia arriba.',
    'ARIA_LABEL_ADD_ELSE_IF': 'Añadir «si no, si»',
    'ARIA_LABEL_ADD_INPUT': 'Añadir entrada',
    'ARIA_LABEL_ADD_LIST_ITEM': 'Añadir elemento a la lista',
    'ARIA_LABEL_ADD_TEXT': 'Añadir texto',
    'ARIA_LABEL_BUTTON': 'botón',
    'ARIA_LABEL_COMMENT': 'Comentario',
    'ARIA_LABEL_COMMENT_COLLAPSE': 'Contraer el comentario',
    'ARIA_LABEL_COMMENT_EXPAND': 'Expandir el comentario',
    'ARIA_LABEL_FIELD_ANGLE': '%1 grados',
    'ARIA_LABEL_HEADING': 'encabezado',
    'ARIA_LABEL_REMOVE_ELSE_IF': 'Quitar «si no, si»',
    'ARIA_LABEL_REMOVE_INPUT': 'Quitar entrada',
    'ARIA_LABEL_REMOVE_LIST_ITEM': 'Quitar elemento de la lista',
    'ARIA_LABEL_REMOVE_TEXT': 'Quitar texto',
    'ARIA_LABEL_TRASH_EMPTY': 'Papelera, vacía',
    'ARIA_TYPE_FIELD_ANGLE': 'ángulo',
    'ARIA_TYPE_FIELD_BITMAP': 'imagen de píxeles',
    'ARIA_TYPE_FIELD_CHECKBOX': 'casilla',
    'ARIA_TYPE_FIELD_COLOUR': 'color',
    'ARIA_TYPE_FIELD_DATE': 'fecha',
    'ARIA_TYPE_FIELD_DROPDOWN': 'desplegable',
    'ARIA_TYPE_FIELD_GRID': 'desplegable en cuadrícula',
    'ARIA_TYPE_FIELD_IMAGE': 'imagen',
    'ARIA_TYPE_FIELD_INPUT': 'campo',
    'ARIA_TYPE_FIELD_NUMBER': 'número',
    'ARIA_TYPE_FIELD_TEXT_INPUT': 'texto',
    'ARIA_TYPE_FIELD_TEXT_INPUT_ARGUMENT': 'nombre de la entrada',
    'ARIA_TYPE_FIELD_TEXT_INPUT_PROCEDURE': 'nombre de la función',
    'BACKSPACE_KEY': 'Retroceso',
    'BLOCK_LABEL_BEGIN_PREFIX': 'Inicio de %1',
    'BLOCK_LABEL_BEGIN_STACK': 'Inicio de la pila',
    'BLOCK_LABEL_COLLAPSED': 'contraído',
    'BLOCK_LABEL_CONTAINER': 'contenedor',
    'BLOCK_LABEL_DISABLED': 'desactivado',
    'BLOCK_LABEL_HAS_BRANCHES': 'tiene %1 ramas',
    'BLOCK_LABEL_HAS_INPUT': 'tiene una entrada',
    'BLOCK_LABEL_HAS_INPUTS': 'tiene entradas',
    'BLOCK_LABEL_REPLACEABLE': 'reemplazable',
    'BLOCK_LABEL_STACK_BLOCKS': '%1 bloques en la pila',
    'BLOCK_LABEL_STATEMENT': 'instrucción',
    'BLOCK_LABEL_TOOLBOX_CATEGORY': 'categoría %1',
    'BLOCK_LABEL_VALUE': 'valor',
    'BUBBLE_LABEL_COMMENT': 'Comentario: %1',
    'BUBBLE_LABEL_DEFAULT': 'Burbuja',
    'BUBBLE_LABEL_WARNING': 'Aviso: %1',
    'CAPS_LOCK_KEY': 'Bloq Mayús',
    'CLOSE_BACKPACK': 'Cerrar la mochila',
    'CONTEXT_MENU_KEY': '≣ Menú',
    'COPY_ALL_TO_BACKPACK': 'Copiar todos los bloques a la mochila',
    'COPY_TO_BACKPACK': 'Copiar a la mochila',
    'CURRENT_BLOCK_ANNOUNCEMENT': 'Bloque actual: %1',
    'DELETE_KEY': 'Supr',
    'EMPTY_BACKPACK': 'Vaciar la mochila',
    'END_KEY': 'Fin',
    'ENTER_KEY': 'Intro',
    'ESCAPE': 'Esc',
    'FIELD_BITMAP_ARIA_VALUE': '%1 por %2, %3 píxeles encendidos',
    'FIELD_BITMAP_BUTTON_LABEL_CLEAR': 'Borrar',
    'FIELD_BITMAP_BUTTON_LABEL_RANDOMIZE': 'Al azar',
    'FIELD_BITMAP_PIXEL_LABEL': '%1, fila %2, columna %3',
    'FIELD_BITMAP_PIXEL_OFF': 'apagado',
    'FIELD_BITMAP_PIXEL_ON': 'encendido',
    'FIELD_LABEL_CHECKBOX_CHECKED': 'Marcada',
    'FIELD_LABEL_CHECKBOX_UNCHECKED': 'Sin marcar',
    'FIELD_LABEL_EDIT_PREFIX': 'Editar %1',
    'FIELD_LABEL_EMPTY': 'vacío',
    'FIELD_LABEL_OPTION_INDEX': 'Opción %1',
    'FIELD_LABEL_VARIABLE': 'Variable «%1»',
    'FIELD_MULTILINEINPUT_FINISH_EDITING': 'Terminar de editar',
    'FIELD_MULTILINEINPUT_NEW_LINE': 'Nueva línea',
    'HOME_KEY': 'Inicio',
    'ICON_LABEL_COMMENT_CLOSED': 'Abrir comentario',
    'ICON_LABEL_COMMENT_OPEN': 'Cerrar comentario',
    'ICON_LABEL_DEFAULT': 'Icono',
    'ICON_LABEL_MUTATOR_CLOSED': 'Editar este bloque',
    'ICON_LABEL_MUTATOR_OPEN': 'Cerrar el editor del bloque',
    'ICON_LABEL_WARNING_CLOSED': 'Abrir aviso',
    'ICON_LABEL_WARNING_OPEN': 'Cerrar aviso',
    'INPUT_LABEL_CONDITION': 'condición',
    'INPUT_LABEL_CONDITION_A': 'primera condición',
    'INPUT_LABEL_CONDITION_B': 'segunda condición',
    'INPUT_LABEL_EMPTY': 'Vacía',
    'INPUT_LABEL_END_STATEMENT': 'Fin de %1',
    'INPUT_LABEL_INDEX': 'entrada %1',
    'INPUT_LABEL_LISTS_CREATE_WITH_ITEM': 'valor %1',
    'INPUT_LABEL_LISTS_DELIMITER': 'separador',
    'INPUT_LABEL_LISTS_END_POSITION': 'posición final',
    'INPUT_LABEL_LISTS_LIST_FROM_TEXT': 'texto que se divide',
    'INPUT_LABEL_LISTS_POSITION': 'posición en la lista',
    'INPUT_LABEL_LISTS_REPEAT_ITEM': 'valor que se repite',
    'INPUT_LABEL_LISTS_REPEAT_NUM': 'número de repeticiones',
    'INPUT_LABEL_LISTS_START_POSITION': 'posición inicial',
    'INPUT_LABEL_LISTS_TEXT_FROM_LIST': 'lista que se une',
    'INPUT_LABEL_LISTS_TO_CHANGE': 'lista que se cambia',
    'INPUT_LABEL_LISTS_TO_CHECK': 'lista que se comprueba',
    'INPUT_LABEL_LISTS_VALUE_TO_SET': 'valor que se pone',
    'INPUT_LABEL_LOOP_BY': 'incremento',
    'INPUT_LABEL_LOOP_FROM': 'número inicial',
    'INPUT_LABEL_LOOP_LIST': 'lista que se recorre',
    'INPUT_LABEL_LOOP_TIMES': 'número de repeticiones',
    'INPUT_LABEL_LOOP_TO': 'número final',
    'INPUT_LABEL_MATH_CHANGE_BY': 'cantidad del cambio',
    'INPUT_LABEL_MATH_CONSTRAIN_VALUE': 'número que se limita',
    'INPUT_LABEL_MATH_DIVIDEND': 'dividendo',
    'INPUT_LABEL_MATH_DIVISOR': 'divisor',
    'INPUT_LABEL_NUMBER': 'número',
    'INPUT_LABEL_NUMBER_A': 'primer número',
    'INPUT_LABEL_NUMBER_ATAN2_X': 'coordenada x',
    'INPUT_LABEL_NUMBER_ATAN2_Y': 'coordenada y',
    'INPUT_LABEL_NUMBER_B': 'segundo número',
    'INPUT_LABEL_NUMBER_LIST': 'lista de números',
    'INPUT_LABEL_NUMBER_MAX': 'máximo',
    'INPUT_LABEL_NUMBER_MIN': 'mínimo',
    'INPUT_LABEL_NUMBER_TO_CHECK': 'número que se comprueba',
    'INPUT_LABEL_STATEMENT': 'posición de instrucción',
    'INPUT_LABEL_TEXT_APPEND': 'valor que se añade',
    'INPUT_LABEL_TEXT_END_POSITION': 'posición final',
    'INPUT_LABEL_TEXT_JOIN_ITEM': 'valor %1',
    'INPUT_LABEL_TEXT_POSITION': 'posición de la letra',
    'INPUT_LABEL_TEXT_PROMPT_MESSAGE': 'mensaje',
    'INPUT_LABEL_TEXT_START_POSITION': 'posición inicial',
    'INPUT_LABEL_TEXT_TO_CHANGE': 'texto que se cambia',
    'INPUT_LABEL_TEXT_TO_CHECK': 'texto que se comprueba',
    'INPUT_LABEL_TEXT_TO_FIND': 'texto que se busca',
    'INPUT_LABEL_TEXT_TO_REPLACE': 'texto que se sustituye',
    'INPUT_LABEL_VALUE': 'posición de valor',
    'INPUT_LABEL_VALUE_A': 'primer valor',
    'INPUT_LABEL_VALUE_B': 'segundo valor',
    'INPUT_LABEL_VARIABLES_SET': 'valor que se pone',
    'INSERT_KEY': 'Insert',
    'KEYBOARD_NAV_BLOCK_NAVIGATION_HINT': 'Usa %1 para moverte dentro de los bloques.',
    'KEYBOARD_NAV_FLYOUT_LABEL_HINT': 'Usa las flechas para ir a un bloque, o pulsa %1 para ir al siguiente encabezado.',
    'KEYBOARD_NAV_WORKSPACE_NAVIGATION_HINT': 'Usa las flechas para moverte.',
    'LOGIC_COMPARE_EQ_ARIA': 'igual a',
    'LOGIC_COMPARE_GTE_ARIA': 'mayor o igual que',
    'LOGIC_COMPARE_GT_ARIA': 'mayor que',
    'LOGIC_COMPARE_LTE_ARIA': 'menor o igual que',
    'LOGIC_COMPARE_LT_ARIA': 'menor que',
    'LOGIC_COMPARE_NEQ_ARIA': 'distinto de',
    'MATH_ADDITION_SYMBOL_ARIA': 'más',
    'MATH_CONSTANT_E_ARIA': 'e',
    'MATH_CONSTANT_GOLDEN_RATIO_ARIA': 'número áureo',
    'MATH_CONSTANT_INFINITY_ARIA': 'infinito',
    'MATH_CONSTANT_PI_ARIA': 'pi',
    'MATH_CONSTANT_SQRT1_2_ARIA': 'raíz cuadrada de un medio',
    'MATH_CONSTANT_SQRT2_ARIA': 'raíz cuadrada de 2',
    'MATH_DIVISION_SYMBOL_ARIA': 'dividido entre',
    'MATH_MULTIPLICATION_SYMBOL_ARIA': 'por',
    'MATH_ONLIST_OPERATOR_MAX_ARIA': 'máximo',
    'MATH_ONLIST_OPERATOR_MIN_ARIA': 'mínimo',
    'MATH_POWER_SYMBOL_ARIA': 'elevado a',
    'MATH_SINGLE_OP_ABSOLUTE_ARIA': 'valor absoluto',
    'MATH_SINGLE_OP_EXP_ARIA': 'e elevado a',
    'MATH_SINGLE_OP_LN_ARIA': 'logaritmo natural',
    'MATH_SINGLE_OP_LOG10_ARIA': 'logaritmo en base 10',
    'MATH_SINGLE_OP_NEG_ARIA': 'negativo',
    'MATH_SINGLE_OP_POW10_ARIA': '10 elevado a',
    'MATH_SUBTRACTION_SYMBOL_ARIA': 'menos',
    'MATH_TRIG_ACOS_ARIA': 'arcocoseno',
    'MATH_TRIG_ASIN_ARIA': 'arcoseno',
    'MATH_TRIG_ATAN_ARIA': 'arcotangente',
    'MATH_TRIG_COS_ARIA': 'coseno',
    'MATH_TRIG_SIN_ARIA': 'seno',
    'MATH_TRIG_TAN_ARIA': 'tangente',
    'MINIMAP_ARIA_LABEL': 'Minimapa del área de trabajo. Usa las flechas para desplazar el área.',
    'NO_PARENT_ANNOUNCEMENT': 'El bloque actual no está dentro de otro',
    'OPEN_BACKPACK': 'Abrir la mochila',
    'OPEN_TRASH': 'Abrir la papelera',
    'PAGE_DOWN_KEY': 'Av Pág',
    'PAGE_UP_KEY': 'Re Pág',
    'PARENT_BLOCKS_ANNOUNCEMENT': 'Dentro de: %1',
    'PASTE_ALL_FROM_BACKPACK': 'Pegar todos los bloques de la mochila',
    'PAUSE_KEY': 'Pausa',
    'REMOVE_FROM_BACKPACK': 'Quitar de la mochila',
    'RESET_ZOOM': 'Restablecer el zoom',
    'SCREENREADER_HINT': 'Usa las flechas para moverte. Pulsa %1 para activar o desactivar el modo para lector de pantalla.',
    'SCREENREADER_MODE_DISABLED': 'El modo para lector de pantalla está desactivado; pulsa %1 para activarlo',
    'SCREENREADER_MODE_ENABLED': 'El modo para lector de pantalla está activado; pulsa %1 para desactivarlo',
    'SHIFT_KEY': 'Mayús',
    'SHORTCUTS_ABORT_MOVE': 'Cancelar el movimiento',
    'SHORTCUTS_CLEANUP': 'Ordenar el área de trabajo',
    'SHORTCUTS_DELETE': 'Borrar',
    'SHORTCUTS_DISCONNECT': 'Separar el bloque',
    'SHORTCUTS_DUPLICATE': 'Duplicar',
    'SHORTCUTS_ESCAPE': 'Salir',
    'SHORTCUTS_EXTENDED_INFORMATION': 'Leer información detallada',
    'SHORTCUTS_FINISH_MOVE': 'Terminar el movimiento',
    'SHORTCUTS_FOCUS_TOOLBOX': 'Ir a la caja de bloques',
    'SHORTCUTS_FOCUS_WORKSPACE': 'Ir al área de trabajo',
    'SHORTCUTS_INFORMATION': 'Leer información',
    'SHORTCUTS_JUMP_BLOCK_END': 'Ir al final del bloque',
    'SHORTCUTS_JUMP_BLOCK_START': 'Ir al principio del bloque',
    'SHORTCUTS_JUMP_BOTTOM_STACK': 'Ir al final de la pila',
    'SHORTCUTS_JUMP_FIRST_BLOCK': 'Ir al primer bloque',
    'SHORTCUTS_JUMP_LAST_BLOCK': 'Ir al último bloque',
    'SHORTCUTS_JUMP_NEXT_PAGE': 'Ir a la página siguiente',
    'SHORTCUTS_JUMP_PREVIOUS_PAGE': 'Ir a la página anterior',
    'SHORTCUTS_JUMP_TOP_STACK': 'Ir al principio de la pila',
    'SHORTCUTS_MOVE_DOWN': 'Mover abajo',
    'SHORTCUTS_MOVE_LEFT': 'Mover a la izquierda',
    'SHORTCUTS_MOVE_RIGHT': 'Mover a la derecha',
    'SHORTCUTS_MOVE_UP': 'Mover arriba',
    'SHORTCUTS_NEXT_HEADING': 'Encabezado siguiente',
    'SHORTCUTS_NEXT_STACK': 'Pila siguiente',
    'SHORTCUTS_PERFORM_ACTION': 'Editar o confirmar',
    'SHORTCUTS_PREVIOUS_HEADING': 'Encabezado anterior',
    'SHORTCUTS_PREVIOUS_STACK': 'Pila anterior',
    'SHORTCUTS_SCROLL_DOWN': 'Desplazar abajo',
    'SHORTCUTS_SCROLL_LEFT': 'Desplazar a la izquierda',
    'SHORTCUTS_SCROLL_RIGHT': 'Desplazar a la derecha',
    'SHORTCUTS_SCROLL_UP': 'Desplazar arriba',
    'SHORTCUTS_SHOW_CONTEXT_MENU': 'Mostrar el menú',
    'SHORTCUTS_SHOW_TOOLTIP': 'Mostrar la ayuda del bloque',
    'SHORTCUTS_START_MOVE': 'Empezar a mover',
    'SHORTCUTS_START_MOVE_STACK': 'Empezar a mover la pila',
    'SHORTCUTS_TOGGLE_SCREENREADER_MODE': 'Activar o desactivar el modo para lector de pantalla',
    'SPACE_KEY': 'Espacio',
    'TAB_KEY': 'Tabulador',
    'TEXT_FROM_END_ARIA': 'número de letra desde el final',
    'TEXT_FROM_START_ARIA': 'número de letra',
    'WORKSPACE_CONTENTS_BLOCKS_MANY': '%1 pilas de bloques%2 en el área de trabajo.',
    'WORKSPACE_CONTENTS_BLOCKS_ONE': 'Una pila de bloques%2 en el área de trabajo.',
    'WORKSPACE_CONTENTS_BLOCKS_ZERO': 'No hay bloques%2 en el área de trabajo.',
    'WORKSPACE_CONTENTS_COMMENTS_MANY': ' y %1 comentarios',
    'WORKSPACE_CONTENTS_COMMENTS_ONE': ' y un comentario',
    'WORKSPACE_LABEL_1_STACK': '1 pila de bloques',
    'WORKSPACE_LABEL_FLYOUT_WORKSPACE': '%1 bloques',
    'WORKSPACE_LABEL_MANY_STACKS': '%1 pilas de bloques',
    'WORKSPACE_LABEL_MUTATOR_WORKSPACE': 'Área del editor del bloque',
    'WORKSPACE_LABEL_PLAIN': 'Área de trabajo de bloques.',
    'WORKSPACE_ROLEDESCRIPTION': 'área de trabajo',
    'WORKSPACE_SEARCH_CLOSE': 'Cerrar la barra de búsqueda',
    'WORKSPACE_SEARCH_FIND_NEXT': 'Buscar siguiente',
    'WORKSPACE_SEARCH_FIND_PREVIOUS': 'Buscar anterior',
    'WORKSPACE_SEARCH_INPUT_LABEL': 'Buscar en el área de trabajo. Pulsa Intro para ir a la coincidencia siguiente y Mayús + Intro para la anterior. Pulsa Esc para cerrar la búsqueda y volver a la coincidencia actual.',
    'WORKSPACE_SEARCH_MATCH': 'Coincidencia %1 de %2: %3',
    'WORKSPACE_SEARCH_NO_MATCHES': 'No hay bloques que coincidan',
    'WORKSPACE_SEARCH_PLACEHOLDER': 'Buscar',
    'ZOOM_IN': 'Acercar',
    'ZOOM_OUT': 'Alejar',
    'ZOOM_TO_FIT_ARIA_LABEL': 'Ajustar el zoom para verlo todo',
}

# Claves que no necesitan traducción (símbolos, cadenas vacías, direcciones de ayuda, nombres de tecla iguales).
SAME = {'MATH_ADDITION_SYMBOL', 'MATH_DIVISION_SYMBOL', 'MATH_MULTIPLICATION_SYMBOL', 'MATH_POWER_SYMBOL', 'MATH_SUBTRACTION_SYMBOL',
        'LISTS_GET_INDEX_TAIL', 'LISTS_GET_SUBLIST_TAIL', 'ORDINAL_NUMBER_SUFFIX', 'PROCEDURES_DEFNORETURN_DO', 'TEXT_CHARAT_TAIL', 'TEXT_GET_SUBSTRING_TAIL', 'ALT_KEY', 'CTRL_KEY', 'COMMAND_KEY', 'OPTION_KEY', 'META_KEY', 'WINDOWS_KEY'}


def main():
    src = Path('/home/claude/vend/node_modules/blockly/msg/es.js')
    if src.exists():
        keys = re.findall(r'Blockly\.Msg\["([A-Z_0-9]+)"\] = .*;  // untranslated', src.read_text(encoding='utf-8'))
        missing = [k for k in keys if k not in ES and k not in SAME and not k.endswith('HELPURL')]
        assert not missing, missing
    out = Path(__file__).resolve().parents[2] / 'assets/vendor/taller/blockly-msg-extra.js'
    body = json.dumps(ES, ensure_ascii=False, indent=0)
    out.write_text('/* Iris Green · traducción al español de los textos de accesibilidad de Blockly 13 que llegan sin traducir.\n'
                   '   Generado por scripts/taller_suite/blockly_es_extra.py. */\n'
                   '(function(){if(!window.Blockly||String(document.documentElement.lang).slice(0,2)!=="es")return;var M=' + body + ';'
                   'Object.keys(M).forEach(function(k){Blockly.Msg[k]=M[k];});})();\n', encoding='utf-8')
    print(out, len(ES))


if __name__ == '__main__':
    main()
