"""Textos del editor bloques ↔ código ↔ resultado, comunes a Programación y Robótica (ES/EN)."""

STRINGS = {
    'es': {
        'evStart': 'al pulsar Ejecutar', 'evKey': 'al pulsar la tecla', 'evClick': 'al tocar este personaje', 'evMessage': 'al recibir el mensaje', 'evBump': 'al chocar',
        'evTip': 'Los bloques que cuelgan de aquí se ejecutan cuando ocurre este suceso.', 'defaultMessage': 'mensaje',
        'blkWait': 'esperar %1 segundos', 'blkForever': 'repetir siempre', 'blkBroadcast': 'enviar el mensaje %1', 'blkRandom': 'número al azar entre %1 y %2',
        'catEvents': 'Sucesos', 'catControl': 'Control', 'catOperators': 'Operadores', 'catVariables': 'Variables', 'catFunctions': 'Funciones',
        'codeArea': 'Programa', 'codeViews': 'Vistas del programa', 'tabBlocks': 'Bloques',
        'blockTitle': 'Bloque elegido', 'blockChanged': 'Bloque cambiado',
        'blockHelp': 'Los datos del bloque que elijas se pueden cambiar aquí, con campos grandes, sin tocarlos dentro del bloque.',
        'applyCode': 'Pasar el código a bloques', 'codeHint': 'Puedes escribir aquí. Al volver a Bloques, el código se convierte.',
        'pyNote': 'El mismo programa en Python, para leerlo y compararlo. Esta vista no se edita.',
        'jsLabel': 'Programa en JavaScript', 'pyLabel': 'Programa en Python, solo lectura',
        'codeEdited': 'Has cambiado el código. Pulsa «Pasar el código a bloques» o vuelve a Bloques para aplicarlo.', 'codeApplied': 'Código aplicado: los bloques ya son iguales que el código.',
        'errLine': 'Línea {n}:', 'errSyntax': 'Hay un error de escritura en el código (falta o sobra algún signo). Revisa paréntesis, llaves y comillas.',
        'errExpr': 'no sé convertir «{code}» en un bloque.', 'errArgs': '«{name}» necesita {n} datos entre paréntesis.',
        'errKey': 'esa tecla no existe en el taller. Usa: espacio, arriba, abajo, izquierda, derecha, a, d, s, w o intro.',
        'errColor': 'el color va entre comillas, por ejemplo \'azul\'.', 'errChoice': 'ese valor no está en la lista del bloque.',
        'errMessage': 'el mensaje va entre comillas, por ejemplo \'empezar\'.', 'errNotStmt': '«{name}» da un valor: úsalo dentro de otra instrucción, por ejemplo en un «if».',
        'errUnknownFn': 'no hay ninguna instrucción ni función llamada «{name}».', 'errUnknownVar': 'la variable «{name}» no está creada. Créala arriba con «let {name} = 0;».',
        'errFor': 'este bucle «for» no tiene una forma conocida. Usa «for (let i = 0; i < 10; i++)» o «for (x = 1; x <= 10; x += 1)».',
        'errBlock': 'aquí sobran unas llaves { }.', 'errLocalVar': 'las variables se crean arriba del todo, fuera de las funciones.',
        'errStmt': 'no sé convertir «{code}» en un bloque.', 'errReserved': '«{name}» ya es el nombre de una instrucción del taller. Elige otro nombre.',
        'errVarInit': 'las variables empiezan en 0. Dales otro valor dentro de «alEmpezar».', 'errParam': 'los datos de una función deben ser nombres sencillos.',
        'errEventFn': 'los sucesos se escriben así: alEmpezar(() => { … });', 'errTop': 'arriba del todo solo pueden ir variables, funciones y sucesos como alEmpezar(…).',
        'errRuntime': 'Algo ha fallado al ejecutar este guion.', 'errTooLong': 'Un bucle hace demasiadas cosas sin pausa. Añade «esperar» dentro o reduce las repeticiones.',
        'errUnknownVarRun': 'La variable «{name}» no existe.', 'errRecursion': 'Una función se llama a sí misma demasiadas veces.',
    },
    'en': {
        'evStart': 'when Run is pressed', 'evKey': 'when key pressed:', 'evClick': 'when this sprite is tapped', 'evMessage': 'when I receive the message', 'evBump': 'when it bumps into something',
        'evTip': 'The blocks hanging from here run when this happens.', 'defaultMessage': 'message',
        'blkWait': 'wait %1 seconds', 'blkForever': 'repeat forever', 'blkBroadcast': 'broadcast the message %1', 'blkRandom': 'random number from %1 to %2',
        'catEvents': 'Events', 'catControl': 'Control', 'catOperators': 'Operators', 'catVariables': 'Variables', 'catFunctions': 'Functions',
        'codeArea': 'Program', 'codeViews': 'Program views', 'tabBlocks': 'Blocks',
        'blockTitle': 'Selected block', 'blockChanged': 'Block changed',
        'blockHelp': 'The values of the block you select can be changed here, in larger fields, without editing them inside the block.',
        'applyCode': 'Turn the code into blocks', 'codeHint': 'You can type here. When you go back to Blocks, the code is converted.',
        'pyNote': 'The same program in Python, to read and compare. This view cannot be edited.',
        'jsLabel': 'Program in JavaScript', 'pyLabel': 'Program in Python, read only',
        'codeEdited': 'You have changed the code. Press “Turn the code into blocks” or go back to Blocks to apply it.', 'codeApplied': 'Code applied: the blocks now match the code.',
        'errLine': 'Line {n}:', 'errSyntax': 'There is a typing error in the code (a sign is missing or extra). Check brackets, braces and quotes.',
        'errExpr': 'I cannot turn “{code}” into a block.', 'errArgs': '“{name}” needs {n} values in brackets.',
        'errKey': 'that key does not exist in the workshop. Use: space, up, down, left, right, a, d, s, w or enter.',
        'errColor': 'the colour goes in quotes, for example \'blue\'.', 'errChoice': 'that value is not in the block’s list.',
        'errMessage': 'the message goes in quotes, for example \'start\'.', 'errNotStmt': '“{name}” gives a value: use it inside another instruction, for example in an “if”.',
        'errUnknownFn': 'there is no instruction or function called “{name}”.', 'errUnknownVar': 'the variable “{name}” has not been created. Create it at the top with “let {name} = 0;”.',
        'errFor': 'this “for” loop does not have a known shape. Use “for (let i = 0; i < 10; i++)” or “for (x = 1; x <= 10; x += 1)”.',
        'errBlock': 'there is an extra pair of braces { } here.', 'errLocalVar': 'variables are created at the very top, outside functions.',
        'errStmt': 'I cannot turn “{code}” into a block.', 'errReserved': '“{name}” is already the name of a workshop instruction. Choose another name.',
        'errVarInit': 'variables start at 0. Give them another value inside “onStart”.', 'errParam': 'a function’s inputs must be simple names.',
        'errEventFn': 'events are written like this: onStart(() => { … });', 'errTop': 'only variables, functions and events such as onStart(…) can go at the very top.',
        'errRuntime': 'Something went wrong while running this script.', 'errTooLong': 'A loop does too much without a pause. Add “wait” inside it or repeat fewer times.',
        'errUnknownVarRun': 'The variable “{name}” does not exist.', 'errRecursion': 'A function calls itself too many times.',
    },
}

assert set(STRINGS['es']) == set(STRINGS['en'])
