"""Estudio de color (R43): paletas, rueda OKLCH, armonías, mezclas de luz y de pintura, contraste WCAG 2.2,
visión del color y una escena de día y de noche. Textos ES/EN.

Fuentes comprobadas:
- W3C. Web Content Accessibility Guidelines (WCAG) 2.2, 2023: definiciones de «relative luminance» y «contrast ratio»;
  criterios 1.4.3, 1.4.6 y 1.4.11. https://www.w3.org/TR/WCAG22/
- Machado, G. M., Oliveira, M. M. y Fernandes, L. A. F. (2009). A Physiologically-based Model for Simulation of Color
  Vision Deficiency. IEEE Transactions on Visualization and Computer Graphics, 15(6), 1291-1298. Matrices de gravedad 1,0
  publicadas por los autores en https://www.inf.ufrgs.br/~oliveira/pubs_files/CVD_Simulation/CVD_Simulation.html
- Ottosson, B. (2020). A perceptual color space for image processing. https://bottosson.github.io/posts/oklab/
- Gossett, N. y Chen, B. (2004). Paint Inspired Color Mixing and Compositing for Visualization. IEEE Symposium on
  Information Visualization (InfoVis 2004), 113-118.
"""

ENGINE = 'color'
SLUG = {'es': 'color', 'en': 'colour'}
SCRIPTS = ['ig-suite-color.js']
STYLES = ['ig-suite-color.css']
LIBRARIES = 'Ninguna biblioteca externa: cálculos de color, Canvas 2D y SVG propios de Iris Green'
LIBRARIES_EN = 'No outside libraries: Iris Green’s own colour maths, Canvas 2D and SVG'

NAMES_ES = {
    'black': 'Negro', 'white': 'Blanco', 'grey': 'Gris', 'lightgrey': 'Gris claro', 'darkgrey': 'Gris oscuro', 'charcoal': 'Carbón', 'slate': 'Pizarra',
    'bluegrey': 'Gris azulado', 'red': 'Rojo', 'crimson': 'Carmesí', 'maroon': 'Granate', 'wine': 'Burdeos', 'pink': 'Rosa', 'hotpink': 'Rosa intenso',
    'fuchsia': 'Fucsia', 'magenta': 'Magenta', 'coral': 'Coral', 'salmon': 'Salmón', 'peach': 'Melocotón', 'orange': 'Naranja', 'terracotta': 'Terracota',
    'rust': 'Óxido', 'brown': 'Marrón', 'chocolate': 'Chocolate', 'caramel': 'Caramelo', 'beige': 'Beis', 'cream': 'Crema', 'ivory': 'Marfil', 'sand': 'Arena',
    'ochre': 'Ocre', 'mustard': 'Mostaza', 'gold': 'Dorado', 'yellow': 'Amarillo', 'lemon': 'Amarillo limón', 'olive': 'Verde oliva', 'khaki': 'Caqui',
    'lime': 'Verde lima', 'green': 'Verde', 'forest': 'Verde bosque', 'mint': 'Verde menta', 'emerald': 'Esmeralda', 'sage': 'Verde salvia', 'teal': 'Verde azulado',
    'turquoise': 'Turquesa', 'cyan': 'Cian', 'skyblue': 'Azul cielo', 'lightblue': 'Azul claro', 'blue': 'Azul', 'cobalt': 'Azul cobalto', 'navy': 'Azul marino',
    'midnight': 'Azul noche', 'indigo': 'Añil', 'violet': 'Violeta', 'purple': 'Morado', 'lavender': 'Lavanda', 'lilac': 'Lila', 'plum': 'Ciruela', 'mauve': 'Malva',
}
NAMES_EN = {
    'black': 'Black', 'white': 'White', 'grey': 'Grey', 'lightgrey': 'Light grey', 'darkgrey': 'Dark grey', 'charcoal': 'Charcoal', 'slate': 'Slate',
    'bluegrey': 'Blue grey', 'red': 'Red', 'crimson': 'Crimson', 'maroon': 'Maroon', 'wine': 'Burgundy', 'pink': 'Pink', 'hotpink': 'Hot pink',
    'fuchsia': 'Fuchsia', 'magenta': 'Magenta', 'coral': 'Coral', 'salmon': 'Salmon', 'peach': 'Peach', 'orange': 'Orange', 'terracotta': 'Terracotta',
    'rust': 'Rust', 'brown': 'Brown', 'chocolate': 'Chocolate', 'caramel': 'Caramel', 'beige': 'Beige', 'cream': 'Cream', 'ivory': 'Ivory', 'sand': 'Sand',
    'ochre': 'Ochre', 'mustard': 'Mustard', 'gold': 'Gold', 'yellow': 'Yellow', 'lemon': 'Lemon yellow', 'olive': 'Olive green', 'khaki': 'Khaki',
    'lime': 'Lime green', 'green': 'Green', 'forest': 'Forest green', 'mint': 'Mint green', 'emerald': 'Emerald', 'sage': 'Sage green', 'teal': 'Teal',
    'turquoise': 'Turquoise', 'cyan': 'Cyan', 'skyblue': 'Sky blue', 'lightblue': 'Light blue', 'blue': 'Blue', 'cobalt': 'Cobalt blue', 'navy': 'Navy blue',
    'midnight': 'Midnight blue', 'indigo': 'Indigo', 'violet': 'Violet', 'purple': 'Purple', 'lavender': 'Lavender', 'lilac': 'Lilac', 'plum': 'Plum', 'mauve': 'Mauve',
}

PAGE = {
    'es': {
        'title': 'Color',
        'description': 'Crea paletas con la rueda OKLCH, prueba armonías, mezcla luces y pinturas, comprueba el contraste WCAG 2.2 y cómo ven tus colores otras personas, y pinta una escena de día y de noche.',
        'lede': 'Elige colores, mira cómo combinan y comprueba que se leen bien. La escena de la calle se pinta con tu paleta.',
        'make': ['Una paleta de 5 colores que se lea bien', 'La misma escena de día y de noche', 'Mezclas de pinturas y de luces', 'La paleta de un videojuego, una app o una marca', 'Tarjeta PNG, SVG, variables CSS, paleta de GIMP y JSON'],
        'steps': [
            'Elige un color en Estructura. En Rueda, toca otro punto o usa las flechas para cambiar el tono y el croma.',
            'En Contraste, toca una casilla para ver si el par se lee bien. Propiedades te propone el ajuste mínimo.',
            'Mira Visión para saber si dos colores se confunden, y Escena para verlos en una calle.',
            'Descarga la paleta o la escena desde Archivo.',
        ],
        'sections': [
            {'h': 'Palabras del color', 'p': 'El tono es el nombre del color en la rueda (rojo, verde, azul…). El croma es su fuerza: poco croma es grisáceo; mucho croma es vivo. La luminosidad dice si es claro u oscuro.\n\nLa rueda usa OKLCH, un modelo de color hecho para que los pasos iguales se vean iguales. Algunas combinaciones no caben en una pantalla normal (la gama sRGB): en la rueda aparecen como cuadros grises y el estudio baja el croma lo justo.'},
            {'h': 'Contraste que se lee', 'p': 'El contraste compara la luz de dos colores, de 1:1 (iguales) a 21:1 (negro y blanco). Las pautas WCAG 2.2 piden al menos 4,5:1 para texto normal (nivel AA), 3:1 para texto grande y para gráficos o controles, y 7:1 para el nivel AAA.'},
            {'h': 'Luz y pintura', 'p': 'Las luces se suman: rojo y verde dan amarillo. Las pinturas absorben luz: amarillo y azul dan verde. Para la pintura, el estudio usa el modelo rojo-amarillo-azul (RYB) de Gossett y Chen: es una aproximación, no la química real de los pigmentos. En este modelo el blanco es el papel, así que no aclara.'},
            {'h': 'Visión del color', 'p': 'Alrededor de una de cada doce personas que nacen con cromosomas XY ve algunos colores de otra forma. La simulación muestra tres tipos (protanopía, deuteranopía y tritanopía) y la escala de grises. Si dos colores se confunden, cambia su luminosidad o añade texto o formas.'},
            {'h': 'Fuentes', 'p': 'W3C (2023). Web Content Accessibility Guidelines (WCAG) 2.2: definiciones de luminancia relativa y relación de contraste; criterios 1.4.3, 1.4.6 y 1.4.11. https://www.w3.org/TR/WCAG22/\n\nMachado, G. M., Oliveira, M. M. y Fernandes, L. A. F. (2009). A Physiologically-based Model for Simulation of Color Vision Deficiency. IEEE Transactions on Visualization and Computer Graphics, 15(6), 1291-1298.\n\nOttosson, B. (2020). A perceptual color space for image processing. https://bottosson.github.io/posts/oklab/\n\nGossett, N. y Chen, B. (2004). Paint Inspired Color Mixing and Compositing for Visualization. IEEE Symposium on Information Visualization (InfoVis 2004), 113-118.'},
        ],
        'links': [('Todo el taller', '/es/taller/'), ('Diseño gráfico', '/es/taller/diseno-grafico/'), ('Pixel art', '/es/taller/pixel-art/')],
    },
    'en': {
        'title': 'Colour',
        'description': 'Build palettes on the OKLCH colour wheel, try harmonies, mix lights and paints, check WCAG 2.2 contrast and how other people see your colours, and paint a scene by day and by night.',
        'lede': 'Choose colours, see how they go together and check they are easy to read. The street scene is painted with your palette.',
        'make': ['A five-colour palette that is easy to read', 'The same scene by day and by night', 'Paint mixes and light mixes', 'A palette for a video game, an app or a brand', 'PNG card, SVG, CSS variables, GIMP palette and JSON'],
        'steps': [
            'Choose a colour in Structure. In Wheel, tap another point or use the arrow keys to change hue and chroma.',
            'In Contrast, tap a square to see whether the pair is easy to read. Properties suggests the smallest change.',
            'Look at Vision to see whether two colours get mixed up, and at Scene to see them in a street.',
            'Download the palette or the scene from File.',
        ],
        'sections': [
            {'h': 'Colour words', 'p': 'Hue is the colour’s name on the wheel (red, green, blue…). Chroma is its strength: low chroma looks greyish; high chroma looks vivid. Lightness tells you whether it is light or dark.\n\nThe wheel uses OKLCH, a colour model made so that equal steps look equal. Some combinations do not fit on a normal screen (the sRGB gamut): on the wheel they show as grey squares, and the studio lowers the chroma just enough.'},
            {'h': 'Contrast you can read', 'p': 'Contrast compares the light of two colours, from 1:1 (the same) to 21:1 (black and white). The WCAG 2.2 guidelines ask for at least 4.5:1 for normal text (level AA), 3:1 for large text and for graphics or controls, and 7:1 for level AAA.'},
            {'h': 'Light and paint', 'p': 'Lights add up: red and green make yellow. Paints absorb light: yellow and blue make green. For paint, the studio uses the red-yellow-blue (RYB) model by Gossett and Chen: it is an approximation, not the real chemistry of pigments. In this model white is the paper, so it does not make colours lighter.'},
            {'h': 'Colour vision', 'p': 'About one in twelve people born with XY chromosomes sees some colours differently. The simulation shows three types (protanopia, deuteranopia and tritanopia) and greyscale. If two colours get mixed up, change their lightness or add text or shapes.'},
            {'h': 'Sources', 'p': 'W3C (2023). Web Content Accessibility Guidelines (WCAG) 2.2: definitions of relative luminance and contrast ratio; success criteria 1.4.3, 1.4.6 and 1.4.11. https://www.w3.org/TR/WCAG22/\n\nMachado, G. M., Oliveira, M. M. and Fernandes, L. A. F. (2009). A Physiologically-based Model for Simulation of Color Vision Deficiency. IEEE Transactions on Visualization and Computer Graphics, 15(6), 1291-1298.\n\nOttosson, B. (2020). A perceptual color space for image processing. https://bottosson.github.io/posts/oklab/\n\nGossett, N. and Chen, B. (2004). Paint Inspired Color Mixing and Compositing for Visualization. IEEE Symposium on Information Visualization (InfoVis 2004), 113-118.'},
        ],
        'links': [('The whole workshop', '/en/workshop/'), ('Graphic design', '/en/workshop/graphic-design/'), ('Pixel art', '/en/workshop/pixel-art/')],
    },
}

STRINGS = {
    'es': {
        'canvasLabel': 'Espacio de color',
        'canvasHelp': 'En la rueda, flechas izquierda y derecha cambian el tono; arriba y abajo, el croma; Re Pág y Av Pág, la luminosidad. Con Mayús, el paso es largo. Corchetes [ y ] eligen el color anterior o el siguiente. Supr borra el color y Esc suelta la selección. En Contraste, cada casilla es un botón.',
        'kColWheel': 'En la rueda: flechas izquierda y derecha, tono; arriba y abajo, croma (Mayús: paso largo)',
        'kColLight': 'Re Pág y Av Pág: luminosidad',
        'kColPick': '[ y ]: color anterior o siguiente de la paleta',
        'stFive': 'Paleta de 5 colores con contraste accesible', 'stFiveD': 'Reto: cinco colores con texto legible (4,5:1) y gráficos visibles (3:1). Uno todavía no cumple.',
        'stDayNight': 'Misma escena de día y de noche', 'stDayNightD': 'Reto: pinta la calle de día y crea su versión de noche que también se lea bien.',
        'stRainbow': 'Colores del arcoíris y mezclas', 'stRainbowD': 'Los siete colores del arcoíris y un laboratorio para mezclar pinturas y luces.',
        'stGame': 'Paleta para un videojuego o una app', 'stGameD': 'Fondo oscuro, texto claro y un acento que destaca.',
        'stBrand': 'Paleta de marca accesible', 'stBrandD': 'Un color de marca que sirva también para texto (4,5:1) y texto de nivel AAA (7:1).',
        'v_wheel': 'Rueda', 'v_harmony': 'Armonías', 'v_mix': 'Mezclas', 'v_contrast': 'Contraste', 'v_vision': 'Visión', 'v_scene': 'Escena', 'viewCmd': 'Cambiar de vista', 'viewRegion': 'Vista {v}',
        'paletteN': 'Paleta {n}', 'palettes': 'Paletas', 'coloursN': 'Colores ({n})', 'newPalette': 'Nueva paleta', 'addColour': 'Añadir color',
        'timeDay': 'Día', 'timeNight': 'Noche', 'timeLabel': 'Momento de la escena', 'timeChanged': 'Escena de {t}',
        'role_sky': 'cielo', 'role_background': 'fondo', 'role_main': 'principal', 'role_accent': 'acento', 'role_text': 'texto', 'role_free': 'sin rol',
        'wheelPick': 'Elige un color en Estructura o toca un punto de la rueda.', 'noColours': 'Esta paleta no tiene colores todavía. Añade uno.',
        'gamutEdge': 'Estás en el borde de la gama sRGB: una pantalla normal no puede mostrar más croma con este tono y esta luminosidad.',
        'nudgeGroup': 'Cambiar el color con botones', 'nudge_hue': 'Tono', 'nudge_chroma': 'Croma', 'nudge_light': 'Luz',
        'wheelNote': 'Los puntos muestran el tono (ángulo) y el croma (distancia al centro). La rueda se pinta con la luminosidad del color elegido; la barra de al lado cambia la luminosidad.',
        'colourChanged': 'Color cambiado', 'harmBase': 'Color base:', 'harmHow': 'Las armonías giran el tono en la rueda OKLCH y mantienen la luminosidad y el croma.',
        'harm_complementary': 'Complementaria', 'harm_complementaryD': 'El tono opuesto (180°). Mucho contraste de tono.',
        'harm_analogous': 'Análogos', 'harm_analogousD': 'Vecinos en la rueda (±30°). Tranquila y natural.',
        'harm_triad': 'Tríada', 'harm_triadD': 'Tres tonos repartidos (120°). Viva y equilibrada.',
        'harm_split': 'Complementaria dividida', 'harm_splitD': 'Los dos vecinos del opuesto (150° y 210°). Contraste más suave.',
        'harm_tetrad': 'Tétrada', 'harm_tetradD': 'Cuatro tonos en cuadrado (90°). Muy variada: elige uno que mande.',
        'harm_mono': 'Monocromática', 'harm_monoD': 'Un solo tono con varias luminosidades.',
        'harmAdd': 'Añadir a la paleta', 'harmReplace': 'Usar como paleta', 'nothingNew': 'Esos colores ya están en la paleta.', 'tooMany': 'Una paleta tiene como mucho {n} colores.',
        'addedN': 'Añadidos {n} colores: {what}', 'replacedWith': 'Paleta nueva: {what}. Roles repartidos por luminosidad.',
        'mixPaintTitle': 'Mezclar pinturas (rojo, amarillo y azul)', 'mixPaintHelp': 'Escribe cuánta pintura de cada color pones, de 0 a 1. El resultado es una aproximación del modelo RYB.',
        'paint_red': 'Rojo', 'paint_yellow': 'Amarillo', 'paint_blue': 'Azul', 'quick_ry': 'Rojo + amarillo', 'quick_yb': 'Amarillo + azul', 'quick_br': 'Azul + rojo', 'quick_all': 'Los tres',
        'paintResult': 'Pintura resultante: {name} {hex}', 'paintResultLabel': 'Pintura resultante', 'rybAmounts': 'Rojo {r} · amarillo {y} · azul {b}', 'addToPalette': 'Añadir a la paleta',
        'addedMix': 'Añadido a la paleta: {what} {hex}', 'mixTwoTitle': 'Mezclar dos colores de la paleta', 'needTwo': 'Hacen falta al menos dos colores.',
        'colourA': 'Color A', 'colourB': 'Color B', 'mixLight': 'Como luces (se suman)', 'mixLightNote': 'Suma de la luz de cada canal RGB.', 'mixLightScaled': 'La suma pasaba del máximo: se ha bajado la intensidad sin cambiar el tono.',
        'mixPaint': 'Como pinturas (se restan)', 'mixPaintNote': 'Modelo RYB de Gossett y Chen (2004).',
        'gradTitle': 'Degradado de A a B', 'gradOklab': 'Mezcla en Oklab (paso a paso, igualado a la vista)', 'gradSrgb': 'Mezcla directa en sRGB',
        'gradNote': 'La mezcla en sRGB suele pasar por tonos más oscuros o grisáceos a mitad de camino.',
        'mixLightsTitle': 'Luces primarias', 'lightsAlt': 'Tres círculos de luz roja, verde y azul que se cruzan: donde se juntan dos salen amarillo, cian y magenta, y en el centro blanco.',
        'lightsRG': 'Rojo + verde = amarillo', 'lightsGB': 'Verde + azul = cian', 'lightsBR': 'Azul + rojo = magenta', 'lightsAll': 'Las tres juntas = blanco',
        'matrixCaption': 'Relación de contraste de cada par: filas, color del texto; columnas, color del fondo', 'textOn': 'Texto ↓ · fondo →', 'samePair': 'mismo color',
        'cellLabel': 'Texto {fg} sobre {bg}: {r}. {g}', 'grade_AAA': 'Cumple AAA para texto normal (7:1)', 'grade_AA': 'Cumple AA para texto normal (4,5:1)',
        'grade_large': 'Solo texto grande y gráficos (3:1)', 'grade_fail': 'No llega a 3:1',
        'gradeShort_AAA': 'AAA', 'gradeShort_AA': 'AA', 'gradeShort_large': 'grande', 'gradeShort_fail': 'no',
        'matrixCount': 'Pares que sirven para texto normal (4,5:1 o más): {n} de {total}.',
        'legend_AAA': 'AAA: 7:1 o más, texto normal', 'legend_AA': 'AA: 4,5:1 o más, texto normal', 'legend_large': 'Grande: 3:1 o más, texto grande (24 px, o 18,5 px en negrita) y gráficos', 'legend_fail': 'No: menos de 3:1',
        'visionHelp': 'Así verían tu paleta y la escena personas con cada tipo de visión del color (simulación de Machado, Oliveira y Fernandes, 2009).',
        'sim_normal': 'Visión típica', 'sim_normalD': 'Tres tipos de conos que funcionan.', 'sim_protan': 'Protanopía', 'sim_protanD': 'Sin conos de rojo: el rojo se ve oscuro y se confunde con verdes.',
        'sim_deutan': 'Deuteranopía', 'sim_deutanD': 'Sin conos de verde: rojos y verdes se parecen.', 'sim_tritan': 'Tritanopía', 'sim_tritanD': 'Sin conos de azul: azules y verdes, amarillos y rosas se parecen.',
        'sim_grey': 'Escala de grises', 'sim_greyD': 'Solo la luminosidad: como una fotocopia en blanco y negro.',
        'confTitle': 'Colores que se confunden', 'confNone': 'Ningún par de colores se confunde.',
        'confItem': 'Con {sim}, «{a}» y «{b}» se confunden (diferencia {d}).', 'confNormal': '«{a}» y «{b}» se parecen mucho incluso con visión típica (diferencia {d}).',
        'confNote': 'Se avisa cuando la diferencia en Oklab baja de 0,05. Para separar dos colores, cambia su luminosidad.',
        'sceneTitle': 'Escena de calle con la paleta «{name}»', 'signText': 'Calle del Color', 'sceneAll': 'Ver todas las paletas', 'makeNight': 'Crear versión de noche',
        'sceneDay': 'Calle de día. Cielo {sky} con sol de color {acc} y nubes. Colinas y suelo {bg}; dos casas {main} con ventanas claras; un árbol; una carretera. Un cartel dice «{sign}» en {txt} sobre {bg}, con contraste {r}.',
        'sceneNight': 'Calle de noche. Cielo {sky} con estrellas y luna de color {acc}. Colinas y suelo {bg}; dos casas {main} con las ventanas encendidas en {acc}; un árbol; una carretera. Un cartel dice «{sign}» en {txt} sobre {bg}, con contraste {r}.',
        'paletteNow': 'Paleta {name}, {n} colores', 'hexLabel': 'Código hexadecimal', 'badHex': 'Ese código no vale. Escribe algo como #1f63d6.', 'pickerLabel': 'Selector del sistema',
        'roleLabel': 'Rol en la escena', 'roleChanged': '{name}: rol {role}', 'ownName': 'Nombre propio (opcional)', 'renamed': 'Nombre cambiado', 'approxName': 'Nombre aproximado',
        'oklchGroup': 'OKLCH (luminosidad, croma y tono)', 'okL': 'Luminosidad L', 'okC': 'Croma C', 'okH': 'Tono H', 'exactValue': 'valor exacto',
        'hslGroup': 'HSL (tono, saturación y luminosidad)', 'hslH': 'Tono', 'hslS': 'Saturación', 'hslL': 'Luminosidad HSL',
        'contrastGroup': 'Contraste de este color', 'onWhite': 'Sobre blanco', 'onBlack': 'Sobre negro', 'onBackground': 'Sobre el fondo ({name})',
        'moveUp': 'Subir', 'moveDown': 'Bajar', 'duplicate': 'Duplicar', 'deleteBtn': 'Borrar', 'reordered': 'Orden cambiado', 'duplicated': 'Color duplicado',
        'pairTitle': '{fg} sobre {bg}', 'sampleNormal': 'Texto normal de ejemplo para leer.', 'sampleLarge': 'Texto grande',
        'ratioIs': 'Contraste {r}', 'critAA': 'Texto normal, nivel AA (4,5:1)', 'critAAA': 'Texto normal, nivel AAA (7:1)', 'critLarge': 'Texto grande, nivel AA (3:1)',
        'critLargeAAA': 'Texto grande, nivel AAA (4,5:1)', 'critGraphics': 'Gráficos y controles, criterio 1.4.11 (3:1)',
        'suggestTitle': 'Para llegar a {need}:1', 'suggestFg': 'Texto: luminosidad de {from} a {to} ({hex})', 'suggestBg': 'Fondo: luminosidad de {from} a {to} ({hex})',
        'applyFg': 'Cambiar el texto', 'applyBg': 'Cambiar el fondo', 'noFix': 'No hay un ajuste de luminosidad que llegue. Prueba con otro color.',
        'suggestNote': 'El ajuste mantiene el tono y el croma y cambia solo la luminosidad, lo mínimo posible.', 'closePair': 'Volver a la paleta',
        'fixed': '{name} ajustado a {hex}', 'paletteProps': 'Paleta', 'paletteName': 'Nombre de la paleta',
        'challengeTitle': 'Reto', 'challengeDone': '¡Reto conseguido!', 'reviewTitle': 'Revisión', 'reviewOk': 'La paleta se lee bien', 'reviewBad': 'Puntos que revisar: {n}',
        'okWord': 'Cumple', 'checkWord': 'Revisar', 'fixBtn': 'Ajustar',
        'ch_five': 'Paleta de 5 colores con contraste accesible', 'ch_fiveD': 'Cinco colores. El texto sobre el fondo debe llegar a 4,5:1 y el principal y el acento, a 3:1. Que nadie los confunda.',
        'ch_daynight': 'Misma escena de día y de noche', 'ch_daynightD': 'Crea una paleta de noche con los mismos roles. En las dos, el cartel tiene que leerse (4,5:1).',
        'ch_rainbow': 'Colores del arcoíris y mezclas', 'ch_rainbowD': 'Ten al menos seis colores y añade uno que hayas mezclado en Mezclas.',
        'ch_game': 'Paleta para un videojuego o una app', 'ch_gameD': 'Fondo oscuro, texto que se lea (4,5:1) y un acento visible (3:1).',
        'ch_brand': 'Paleta de marca accesible', 'ch_brandD': 'El texto llega a 7:1 (AAA) y el color principal a 4,5:1 para poder usarlo en enlaces y títulos.',
        'chkTextOk': 'Texto sobre fondo: {r} (se pide {need}:1).', 'chkTextBad': 'Texto sobre fondo: {r}; se pide {need}:1.',
        'chkMainOk': 'Principal sobre fondo: {r} (se pide {need}:1).', 'chkMainBad': 'Principal sobre fondo: {r}; se pide {need}:1.',
        'chkAccOk': 'Acento sobre fondo: {r} (gráficos, 3:1).', 'chkAccBad': 'Acento sobre fondo: {r}; para gráficos se pide 3:1.',
        'chkConfOk': 'Ningún par se confunde con protanopía, deuteranopía ni tritanopía.', 'chkConfBad': 'Hay {n} pares que se confunden. Míralo en Visión.',
        'chkFive': 'La paleta tiene {n} colores (se piden 5).', 'chkRainbow': 'La paleta tiene {n} colores (se piden 6 o más).', 'chkMixed': 'Hay un color hecho en Mezclas.',
        'chkDark': 'El fondo es oscuro.', 'chkDayNight': 'Hay una paleta de día y otra de noche.', 'chkOther': 'En «{name}», texto sobre fondo: {r}.',
        'needRoles': 'Asigna los roles de fondo y de ese color primero.',
        'sortLight': 'Ordenar de claro a oscuro', 'sorted': 'Colores ordenados por luminosidad', 'autoRoles': 'Repartir roles', 'rolesAssigned': 'Roles repartidos por luminosidad',
        'dupPalette': 'Duplicar paleta', 'delPalette': 'Borrar paleta', 'rolesHelp': 'Los roles dicen qué parte de la escena pinta cada color: cielo, fondo (suelo y cartel), principal (casas), acento (sol, luna y luces) y texto (cartel).',
        'summary': 'Paleta «{name}», de {time}, con {n} colores. Vista: {view}.', 'selNow': 'Elegido: {name}, {v}.', 'sumContrast': 'Texto sobre fondo: {r}.', 'sumMix': 'Pintura RYB actual: {name} {hex}.',
        'selected': 'Elegido: {name}', 'deselected': 'Nada elegido.', 'colourAdded': 'Color añadido: {name} {hex}', 'deleted': 'Borrado: {name}',
        'paletteAdded': 'Paleta nueva', 'paletteDup': 'Paleta duplicada', 'nightOf': '{name} de noche', 'copyOf': 'Copia de {name}', 'nightMade': 'Creada la paleta «{name}». Mírala en Escena.',
        'lastPalette': 'Tiene que quedar al menos una paleta.', 'paletteDeleted': 'Paleta borrada: {name}', 'tooManyPal': 'Puedes tener como mucho {n} paletas.',
        'exportCard': 'Tarjeta de la paleta (PNG)', 'exportSvg': 'Paleta (SVG)', 'exportCss': 'Variables CSS', 'exportGpl': 'Paleta de GIMP (.gpl)', 'exportJson': 'Paleta (JSON)',
        'exportScenePng': 'Escena (PNG)', 'exportSceneSvg': 'Escena (SVG)', 'exportError': 'No se ha podido exportar. Inténtalo de nuevo.', 'fileWord': 'Archivo',
        'cardSub': '{n} colores · {time} · nombres aproximados', 'cardSample': 'Texto sobre fondo · {r}', 'cssHeader': 'Paleta «{name}»',
        'exFive': 'Cinco colores', 'exRainbow': 'Arcoíris', 'exGame': 'Videojuego nocturno', 'exBrand': 'Marca', 'exDay': 'Calle de día',
    },
    'en': {
        'canvasLabel': 'Colour space',
        'canvasHelp': 'On the wheel, the left and right arrow keys change hue; up and down change chroma; Page Up and Page Down change lightness. With Shift, the step is bigger. The [ and ] keys choose the previous or next colour. Delete removes the colour and Esc clears the selection. In Contrast, every square is a button.',
        'kColWheel': 'On the wheel: left and right arrows, hue; up and down, chroma (Shift: bigger step)',
        'kColLight': 'Page Up and Page Down: lightness',
        'kColPick': '[ and ]: previous or next colour in the palette',
        'stFive': 'Five-colour palette with accessible contrast', 'stFiveD': 'Challenge: five colours with readable text (4.5:1) and visible graphics (3:1). One does not pass yet.',
        'stDayNight': 'The same scene by day and by night', 'stDayNightD': 'Challenge: paint the street by day and make a night version that is also easy to read.',
        'stRainbow': 'Rainbow colours and mixing', 'stRainbowD': 'The seven colours of the rainbow and a lab for mixing paints and lights.',
        'stGame': 'Palette for a video game or an app', 'stGameD': 'Dark background, light text and an accent that stands out.',
        'stBrand': 'Accessible brand palette', 'stBrandD': 'A brand colour that also works for text (4.5:1) and AAA-level text (7:1).',
        'v_wheel': 'Wheel', 'v_harmony': 'Harmonies', 'v_mix': 'Mixing', 'v_contrast': 'Contrast', 'v_vision': 'Vision', 'v_scene': 'Scene', 'viewCmd': 'Change view', 'viewRegion': '{v} view',
        'paletteN': 'Palette {n}', 'palettes': 'Palettes', 'coloursN': 'Colours ({n})', 'newPalette': 'New palette', 'addColour': 'Add colour',
        'timeDay': 'Day', 'timeNight': 'Night', 'timeLabel': 'Time of the scene', 'timeChanged': '{t} scene',
        'role_sky': 'sky', 'role_background': 'background', 'role_main': 'main', 'role_accent': 'accent', 'role_text': 'text', 'role_free': 'no role',
        'wheelPick': 'Choose a colour in Structure or tap a point on the wheel.', 'noColours': 'This palette has no colours yet. Add one.',
        'gamutEdge': 'You are at the edge of the sRGB gamut: a normal screen cannot show more chroma with this hue and lightness.',
        'nudgeGroup': 'Change the colour with buttons', 'nudge_hue': 'Hue', 'nudge_chroma': 'Chroma', 'nudge_light': 'Light',
        'wheelNote': 'The points show hue (angle) and chroma (distance from the centre). The wheel is painted at the lightness of the chosen colour; the bar beside it changes lightness.',
        'colourChanged': 'Colour changed', 'harmBase': 'Base colour:', 'harmHow': 'Harmonies turn the hue on the OKLCH wheel and keep lightness and chroma.',
        'harm_complementary': 'Complementary', 'harm_complementaryD': 'The opposite hue (180°). Strong hue contrast.',
        'harm_analogous': 'Analogous', 'harm_analogousD': 'Neighbours on the wheel (±30°). Calm and natural.',
        'harm_triad': 'Triad', 'harm_triadD': 'Three evenly spaced hues (120°). Lively and balanced.',
        'harm_split': 'Split complementary', 'harm_splitD': 'The two neighbours of the opposite (150° and 210°). Gentler contrast.',
        'harm_tetrad': 'Tetrad', 'harm_tetradD': 'Four hues in a square (90°). Very varied: let one lead.',
        'harm_mono': 'Monochromatic', 'harm_monoD': 'One hue in several lightnesses.',
        'harmAdd': 'Add to the palette', 'harmReplace': 'Use as palette', 'nothingNew': 'Those colours are already in the palette.', 'tooMany': 'A palette has {n} colours at most.',
        'addedN': '{n} colours added: {what}', 'replacedWith': 'New palette: {what}. Roles shared out by lightness.',
        'mixPaintTitle': 'Mix paints (red, yellow and blue)', 'mixPaintHelp': 'Type how much of each paint you use, from 0 to 1. The result is an approximation from the RYB model.',
        'paint_red': 'Red', 'paint_yellow': 'Yellow', 'paint_blue': 'Blue', 'quick_ry': 'Red + yellow', 'quick_yb': 'Yellow + blue', 'quick_br': 'Blue + red', 'quick_all': 'All three',
        'paintResult': 'Resulting paint: {name} {hex}', 'paintResultLabel': 'Resulting paint', 'rybAmounts': 'Red {r} · yellow {y} · blue {b}', 'addToPalette': 'Add to the palette',
        'addedMix': 'Added to the palette: {what} {hex}', 'mixTwoTitle': 'Mix two colours from the palette', 'needTwo': 'You need at least two colours.',
        'colourA': 'Colour A', 'colourB': 'Colour B', 'mixLight': 'As lights (they add up)', 'mixLightNote': 'The light of each RGB channel added together.', 'mixLightScaled': 'The sum went over the maximum: the brightness was lowered without changing the hue.',
        'mixPaint': 'As paints (they take away)', 'mixPaintNote': 'RYB model by Gossett and Chen (2004).',
        'gradTitle': 'Gradient from A to B', 'gradOklab': 'Mixed in Oklab (even steps to the eye)', 'gradSrgb': 'Mixed directly in sRGB',
        'gradNote': 'Mixing in sRGB often passes through darker or greyer colours halfway.',
        'mixLightsTitle': 'Primary lights', 'lightsAlt': 'Three overlapping circles of red, green and blue light: where two meet you get yellow, cyan and magenta, and white in the centre.',
        'lightsRG': 'Red + green = yellow', 'lightsGB': 'Green + blue = cyan', 'lightsBR': 'Blue + red = magenta', 'lightsAll': 'All three together = white',
        'matrixCaption': 'Contrast ratio of every pair: rows, text colour; columns, background colour', 'textOn': 'Text ↓ · background →', 'samePair': 'same colour',
        'cellLabel': '{fg} text on {bg}: {r}. {g}', 'grade_AAA': 'Passes AAA for normal text (7:1)', 'grade_AA': 'Passes AA for normal text (4.5:1)',
        'grade_large': 'Only large text and graphics (3:1)', 'grade_fail': 'Below 3:1',
        'gradeShort_AAA': 'AAA', 'gradeShort_AA': 'AA', 'gradeShort_large': 'large', 'gradeShort_fail': 'no',
        'matrixCount': 'Pairs that work for normal text (4.5:1 or more): {n} of {total}.',
        'legend_AAA': 'AAA: 7:1 or more, normal text', 'legend_AA': 'AA: 4.5:1 or more, normal text', 'legend_large': 'Large: 3:1 or more, large text (24 px, or 18.5 px bold) and graphics', 'legend_fail': 'No: under 3:1',
        'visionHelp': 'This is how your palette and the scene would look to people with each type of colour vision (simulation by Machado, Oliveira and Fernandes, 2009).',
        'sim_normal': 'Typical vision', 'sim_normalD': 'Three working types of cone.', 'sim_protan': 'Protanopia', 'sim_protanD': 'No red cones: red looks dark and gets mixed up with greens.',
        'sim_deutan': 'Deuteranopia', 'sim_deutanD': 'No green cones: reds and greens look alike.', 'sim_tritan': 'Tritanopia', 'sim_tritanD': 'No blue cones: blues and greens, yellows and pinks look alike.',
        'sim_grey': 'Greyscale', 'sim_greyD': 'Lightness only: like a black-and-white photocopy.',
        'confTitle': 'Colours that get mixed up', 'confNone': 'No pair of colours gets mixed up.',
        'confItem': 'With {sim}, “{a}” and “{b}” get mixed up (difference {d}).', 'confNormal': '“{a}” and “{b}” look very alike even with typical vision (difference {d}).',
        'confNote': 'You get a warning when the difference in Oklab is under 0.05. To tell two colours apart, change their lightness.',
        'sceneTitle': 'Street scene with the palette “{name}”', 'signText': 'Colour Street', 'sceneAll': 'Show every palette', 'makeNight': 'Make night version',
        'sceneDay': 'Street by day. {sky} sky with a {acc} sun and clouds. Hills and ground in {bg}; two {main} houses with pale windows; a tree; a road. A sign says “{sign}” in {txt} on {bg}, with contrast {r}.',
        'sceneNight': 'Street at night. {sky} sky with stars and a {acc} moon. Hills and ground in {bg}; two {main} houses with windows lit in {acc}; a tree; a road. A sign says “{sign}” in {txt} on {bg}, with contrast {r}.',
        'paletteNow': 'Palette {name}, {n} colours', 'hexLabel': 'Hex code', 'badHex': 'That code does not work. Type something like #1f63d6.', 'pickerLabel': 'System picker',
        'roleLabel': 'Role in the scene', 'roleChanged': '{name}: role {role}', 'ownName': 'Your own name (optional)', 'renamed': 'Name changed', 'approxName': 'Approximate name',
        'oklchGroup': 'OKLCH (lightness, chroma and hue)', 'okL': 'Lightness L', 'okC': 'Chroma C', 'okH': 'Hue H', 'exactValue': 'exact value',
        'hslGroup': 'HSL (hue, saturation and lightness)', 'hslH': 'Hue', 'hslS': 'Saturation', 'hslL': 'HSL lightness',
        'contrastGroup': 'Contrast of this colour', 'onWhite': 'On white', 'onBlack': 'On black', 'onBackground': 'On the background ({name})',
        'moveUp': 'Move up', 'moveDown': 'Move down', 'duplicate': 'Duplicate', 'deleteBtn': 'Delete', 'reordered': 'Order changed', 'duplicated': 'Colour duplicated',
        'pairTitle': '{fg} on {bg}', 'sampleNormal': 'Normal sample text to read.', 'sampleLarge': 'Large text',
        'ratioIs': 'Contrast {r}', 'critAA': 'Normal text, level AA (4.5:1)', 'critAAA': 'Normal text, level AAA (7:1)', 'critLarge': 'Large text, level AA (3:1)',
        'critLargeAAA': 'Large text, level AAA (4.5:1)', 'critGraphics': 'Graphics and controls, criterion 1.4.11 (3:1)',
        'suggestTitle': 'To reach {need}:1', 'suggestFg': 'Text: lightness from {from} to {to} ({hex})', 'suggestBg': 'Background: lightness from {from} to {to} ({hex})',
        'applyFg': 'Change the text', 'applyBg': 'Change the background', 'noFix': 'No lightness change gets there. Try another colour.',
        'suggestNote': 'The change keeps hue and chroma and only changes lightness, as little as possible.', 'closePair': 'Back to the palette',
        'fixed': '{name} changed to {hex}', 'paletteProps': 'Palette', 'paletteName': 'Palette name',
        'challengeTitle': 'Challenge', 'challengeDone': 'Challenge complete!', 'reviewTitle': 'Check', 'reviewOk': 'The palette is easy to read', 'reviewBad': 'Points to look at: {n}',
        'okWord': 'Passes', 'checkWord': 'Look at', 'fixBtn': 'Fix',
        'ch_five': 'Five-colour palette with accessible contrast', 'ch_fiveD': 'Five colours. Text on the background must reach 4.5:1, and main and accent 3:1. Nobody should mix them up.',
        'ch_daynight': 'The same scene by day and by night', 'ch_daynightD': 'Make a night palette with the same roles. In both, the sign has to be readable (4.5:1).',
        'ch_rainbow': 'Rainbow colours and mixing', 'ch_rainbowD': 'Have at least six colours and add one you mixed in Mixing.',
        'ch_game': 'Palette for a video game or an app', 'ch_gameD': 'Dark background, readable text (4.5:1) and a visible accent (3:1).',
        'ch_brand': 'Accessible brand palette', 'ch_brandD': 'Text reaches 7:1 (AAA) and the main colour 4.5:1 so you can use it for links and headings.',
        'chkTextOk': 'Text on background: {r} ({need}:1 needed).', 'chkTextBad': 'Text on background: {r}; {need}:1 is needed.',
        'chkMainOk': 'Main on background: {r} ({need}:1 needed).', 'chkMainBad': 'Main on background: {r}; {need}:1 is needed.',
        'chkAccOk': 'Accent on background: {r} (graphics, 3:1).', 'chkAccBad': 'Accent on background: {r}; graphics need 3:1.',
        'chkConfOk': 'No pair gets mixed up with protanopia, deuteranopia or tritanopia.', 'chkConfBad': '{n} pairs get mixed up. Look at Vision.',
        'chkFive': 'The palette has {n} colours (5 needed).', 'chkRainbow': 'The palette has {n} colours (6 or more needed).', 'chkMixed': 'There is a colour made in Mixing.',
        'chkDark': 'The background is dark.', 'chkDayNight': 'There is a day palette and a night palette.', 'chkOther': 'In “{name}”, text on background: {r}.',
        'needRoles': 'Give the background and that colour their roles first.',
        'sortLight': 'Sort from light to dark', 'sorted': 'Colours sorted by lightness', 'autoRoles': 'Share out roles', 'rolesAssigned': 'Roles shared out by lightness',
        'dupPalette': 'Duplicate palette', 'delPalette': 'Delete palette', 'rolesHelp': 'Roles say which part of the scene each colour paints: sky, background (ground and sign), main (houses), accent (sun, moon and lights) and text (sign).',
        'summary': 'Palette “{name}”, {time}, with {n} colours. View: {view}.', 'selNow': 'Selected: {name}, {v}.', 'sumContrast': 'Text on background: {r}.', 'sumMix': 'Current RYB paint: {name} {hex}.',
        'selected': 'Selected: {name}', 'deselected': 'Nothing selected.', 'colourAdded': 'Colour added: {name} {hex}', 'deleted': 'Deleted: {name}',
        'paletteAdded': 'New palette', 'paletteDup': 'Palette duplicated', 'nightOf': '{name} at night', 'copyOf': 'Copy of {name}', 'nightMade': 'Palette “{name}” created. Look at it in Scene.',
        'lastPalette': 'At least one palette must remain.', 'paletteDeleted': 'Palette deleted: {name}', 'tooManyPal': 'You can have {n} palettes at most.',
        'exportCard': 'Palette card (PNG)', 'exportSvg': 'Palette (SVG)', 'exportCss': 'CSS variables', 'exportGpl': 'GIMP palette (.gpl)', 'exportJson': 'Palette (JSON)',
        'exportScenePng': 'Scene (PNG)', 'exportSceneSvg': 'Scene (SVG)', 'exportError': 'Could not export. Please try again.', 'fileWord': 'File',
        'cardSub': '{n} colours · {time} · approximate names', 'cardSample': 'Text on background · {r}', 'cssHeader': 'Palette “{name}”',
        'exFive': 'Five colours', 'exRainbow': 'Rainbow', 'exGame': 'Night-time game', 'exBrand': 'Brand', 'exDay': 'Street by day',
    },
}
for _k, _v in NAMES_ES.items():
    STRINGS['es']['cn_' + _k] = _v
    STRINGS['en']['cn_' + _k] = NAMES_EN[_k]
assert set(NAMES_ES) == set(NAMES_EN)
assert set(STRINGS['es']) == set(STRINGS['en'])
assert set(PAGE['es']) == set(PAGE['en'])
