"""Estudio de dibujo (R43): lienzo por capas en PixiJS, pinceles con presión, simetría,
perspectiva de 1, 2 y 3 puntos, series y retos por niveles. Textos ES/EN."""

ENGINE = 'dibujo'
SLUG = {'es': 'dibujo', 'en': 'drawing'}
SCRIPTS = ['ig-suite-dibujo.js']
STYLES = ['ig-suite-dibujo.css']
LIBRARIES = 'PixiJS (MIT)'
LIBRARIES_EN = 'PixiJS (MIT)'

PAGE = {
    'es': {
        'title': 'Estudio de dibujo',
        'description': 'Lienzo con capas de verdad, pinceles con presión del lápiz, goma, simetría, guías de perspectiva de 1, 2 y 3 puntos, series y 15 retos por niveles.',
        'lede': 'Dibujas en el lienzo del centro. A la izquierda, Estructura: los dibujos de la serie y las capas. A la derecha, Propiedades: el pincel, el color, la simetría, las guías y el reto.',
        'make': [
            'Dibujos por capas, con pinceles que responden a la presión del lápiz',
            'Mandalas y caleidoscopios con simetría radial',
            'Escenas en perspectiva de uno, dos o tres puntos de fuga',
            'Estudios de luz con tres tonos: claro, medio y sombra',
            'Series de varios dibujos con reglas que escribes tú',
        ],
        'steps': [
            'Elige una herramienta en la barra de abajo y dibuja con el ratón, el dedo, un lápiz digital o el teclado.',
            'Con el teclado: entra en el lienzo con el tabulador, mueve el cursor con las flechas e Intro baja y sube la pluma. Con las formas, el primer Intro marca el inicio y el segundo el final.',
            'En Propiedades cambias tamaño, opacidad, dureza, flujo y estabilización, y activas simetría o una guía de perspectiva.',
            'En Estructura añades capas y dibujos de la serie. Cada capa tiene nombre, opacidad y modo de fusión.',
            'En Archivo: «Nuevo…» trae los 15 retos por niveles; «Guardar proyecto» descarga tu archivo; «Exportar» da PNG, capas en ZIP y SVG.',
        ],
        'sections': [
            {'h': 'Capas, simetría y perspectiva',
             'p': 'Las capas son hojas transparentes una encima de otra: lo que borras en una no toca las demás. Puedes ocultarlas, cambiar su opacidad, su modo de fusión y su orden, y fusionar dos en una.\n\nLa simetría repite cada trazo en espejo o alrededor del centro, de 2 a 16 partes. Las guías de perspectiva llevan las líneas que se alejan hacia uno, dos o tres puntos de fuga; puedes moverlos con los campos numéricos de Propiedades o con las flechas.'},
            {'h': 'Presión, inclinación y trazo suave',
             'p': 'Si dibujas con un lápiz digital, el estudio usa la presión para el grosor y la inclinación para la forma del trazo. Con ratón o con el dedo funciona igual, con un grosor constante: nunca hace falta un lápiz.\n\nEl estudio lee todos los puntos intermedios del movimiento, así que las curvas rápidas salen suaves. La estabilización suaviza el pulso: súbela si te tiembla la mano, bájala si quieres trazo nervioso.'},
            {'h': 'Luz con tres tonos',
             'p': 'Un objeto con luz se entiende con tres valores: el tono claro donde da la luz, el tono medio y la sombra. En Propiedades, «Luz en tres tonos» calcula los tres a partir de un color base: el claro se va hacia el color de la luz y la sombra hacia el azul del cielo, que es lo que ocurre a la intemperie.\n\nJames Gurney explica esta relación entre la luz directa y la luz ambiente del cielo en «Color and Light» (2010).'},
            {'h': 'Series con reglas propias',
             'p': 'Un proyecto puede tener varios dibujos. Sirven para hacer series: el mismo objeto con cuatro luces, una historia en viñetas o diez variaciones de una idea.\n\nEscribe tus reglas en «Mis reglas», una por línea. El contador te dice cuántas reglas llevas y cuántos dibujos de la serie tienen trazos.'},
            {'h': 'Fuentes',
             'p': 'Andrew Loomis, «Successful Drawing», Viking Press, 1951: perspectiva de uno, dos y tres puntos de fuga y altura del horizonte.\n\nJames Gurney, «Color and Light: A Guide for the Realist Painter», Andrews McMeel Publishing, 2010 (ISBN 978-0-7407-9771-2): luz, sombra y valores tonales.\n\nW3C, «Pointer Events Level 3», Recomendación del W3C de 30 de junio de 2026: https://www.w3.org/TR/pointerevents3/ — presión, inclinación y eventos agrupados del lápiz.'},
        ],
        'links': [('Todo el taller', '/es/taller/'), ('Pixel art', '/es/taller/pixel-art/'), ('Color', '/es/taller/color/'), ('Cómic', '/es/taller/comic/')],
    },
    'en': {
        'title': 'Drawing studio',
        'description': 'A canvas with real layers, brushes that follow stylus pressure, an eraser, symmetry, one-, two- and three-point perspective guides, series and 15 challenges by level.',
        'lede': 'You draw on the canvas in the middle. Structure, on the left, holds the drawings in your series and the layers. Properties, on the right, holds the brush, the colour, symmetry, guides and the challenge.',
        'make': [
            'Layered drawings with brushes that follow stylus pressure',
            'Mandalas and kaleidoscopes with radial symmetry',
            'Scenes in one-, two- or three-point perspective',
            'Light studies in three values: light, mid and shadow',
            'Series of several drawings following rules you write yourself',
        ],
        'steps': [
            'Pick a tool in the bar below and draw with a mouse, a finger, a stylus or the keyboard.',
            'With a keyboard: tab into the canvas, move the cursor with the arrow keys, and Enter puts the pen down and lifts it. With shapes, the first Enter marks the start and the second the end.',
            'Properties is where you change size, opacity, hardness, flow and stabilisation, and turn on symmetry or a perspective guide.',
            'Structure is where you add layers and drawings to the series. Every layer has a name, an opacity and a blend mode.',
            'In File: “New…” offers the 15 challenges by level; “Save project” downloads your file; “Export” gives you a PNG, the layers in a ZIP and an SVG.',
        ],
        'sections': [
            {'h': 'Layers, symmetry and perspective',
             'p': 'Layers are transparent sheets stacked on top of each other: what you erase on one does not touch the others. You can hide them, change their opacity, their blend mode and their order, and merge two into one.\n\nSymmetry repeats every stroke as a mirror image or around the centre, in 2 to 16 parts. The perspective guides take lines that go into the distance towards one, two or three vanishing points; you can move the points with the number fields in Properties or with the arrow keys.'},
            {'h': 'Pressure, tilt and a steady line',
             'p': 'If you draw with a stylus, the studio uses pressure for the width and tilt for the shape of the mark. With a mouse or a finger it works just the same, at a constant width: you never need a stylus.\n\nThe studio reads every in-between point of the movement, so fast curves come out smooth. Stabilisation smooths out your hand: turn it up if your hand shakes, turn it down if you want a nervous line.'},
            {'h': 'Light in three values',
             'p': 'An object with light on it reads in three values: the light tone where the light falls, the mid tone, and the shadow. In Properties, “Light in three values” works the three out from one base colour: the light tone moves towards the colour of the light and the shadow towards the blue of the sky, which is what happens outdoors.\n\nJames Gurney explains this relationship between direct light and ambient skylight in “Color and Light” (2010).'},
            {'h': 'Series with your own rules',
             'p': 'One project can hold several drawings. They are for making series: the same object in four different lights, a story in panels, or ten variations on one idea.\n\nWrite your rules in “My rules”, one per line. The counter tells you how many rules you have written and how many drawings in the series have marks on them.'},
            {'h': 'Sources',
             'p': 'Andrew Loomis, “Successful Drawing”, Viking Press, 1951: one-, two- and three-point perspective and horizon height.\n\nJames Gurney, “Color and Light: A Guide for the Realist Painter”, Andrews McMeel Publishing, 2010 (ISBN 978-0-7407-9771-2): light, shadow and tonal values.\n\nW3C, “Pointer Events Level 3”, W3C Recommendation of 30 June 2026: https://www.w3.org/TR/pointerevents3/ — stylus pressure, tilt and coalesced events.'},
        ],
        'links': [('The whole workshop', '/en/workshop/'), ('Pixel art', '/en/workshop/pixel-art/'), ('Colour', '/en/workshop/colour/'), ('Comics', '/en/workshop/comics-storyboarding/')],
    },
}

STRINGS = {
    'es': {
        # --- lienzo y teclado ---
        'canvasLabel': 'Lienzo de dibujo',
        'canvasHelp': 'Las flechas mueven el cursor por el lienzo (paso corto con Mayús). Intro o Espacio bajan y suben la pluma; con las formas, el primer Intro marca el inicio y el segundo el final. Esc cancela el trazo. [ y ] cambian el tamaño. Con la herramienta Puntos de fuga, las flechas mueven el punto elegido.',
        'kDibCursor': 'En el lienzo: flechas para el cursor; Intro o Espacio para dibujar',
        'kDibSize': '[ y ] cambian el tamaño del pincel; Esc cancela el trazo',
        'kDibVp': 'Con Puntos de fuga: flechas para mover el punto; V para cambiar de punto',
        'cursorAt': 'Cursor en x {x}, y {y} · {pen}',
        'penDown': 'pluma bajada', 'penUp': 'pluma subida', 'penUpSaved': 'Pluma subida, trazo guardado',
        'shapeStart': 'Primer punto marcado. Mueve el cursor y pulsa Intro para terminar.',
        'shapeDone': 'Forma guardada', 'cancelled': 'Trazo cancelado', 'drawn': 'Trazo',
        'hiddenLayer': 'La capa elegida está oculta. Hazla visible o elige otra para dibujar.',
        'lockedByChallenge': 'El reto no permite esta herramienta.',
        # --- herramientas ---
        'tool_pencil': 'Lápiz', 'tool_soft': 'Pincel blando', 'tool_marker': 'Rotulador', 'tool_water': 'Acuarela',
        'tool_chalk': 'Tiza y carboncillo', 'tool_air': 'Aerógrafo', 'tool_eraser': 'Goma', 'tool_picker': 'Cuentagotas',
        'tool_line': 'Línea', 'tool_rect': 'Rectángulo', 'tool_ellipse': 'Elipse', 'tool_fill': 'Relleno',
        'tool_text': 'Texto', 'tool_select': 'Seleccionar', 'tool_vp': 'Puntos de fuga', 'tool_pan': 'Mover la vista',
        'fitView': 'Ver todo', 'toolPicked': 'Herramienta: {t}',
        # --- pincel ---
        'brushTitle': 'Herramienta', 'size': 'Tamaño', 'px': 'px', 'opacity': 'Opacidad', 'hardness': 'Dureza',
        'flow': 'Flujo', 'stabilise': 'Estabilización del trazo', 'pct': '%',
        'fillShapes': 'Rellenar las formas', 'usePressure': 'Usar la presión del lápiz', 'useTilt': 'Usar la inclinación del lápiz',
        'brushNote': 'La presión y la inclinación solo cambian algo si dibujas con un lápiz digital. Con ratón o con el dedo el trazo tiene un grosor constante.',
        'inputPen': 'Lápiz: presión {p} %', 'inputPenTilt': 'Lápiz: presión {p} %, inclinación {a}°', 'inputMouse': 'Ratón o dedo: grosor constante',
        'sizeSet': 'Tamaño: {n} px',
        # --- color ---
        'colourTitle': 'Color', 'palette': 'Paleta', 'customColour': 'Otro color', 'colourNow': 'Color: {c}', 'picked': 'Color tomado: {c}',
        'colourNames': 'negro|gris|gris claro|blanco|granate|rojo|naranja|amarillo|verde oliva|verde|verde azulado|azul|azul marino|violeta|rosa oscuro|marrón',
        'hueNames': 'rojo|naranja|verde amarillento|verde|turquesa|azul|violeta|rosa|blanco|negro|gris',
        'light': 'claro', 'dark': 'oscuro', 'hueOrder': '{h} {q}',
        'mixTitle': 'Mezclar dos colores', 'mixA': 'Color A', 'mixB': 'Color B', 'mixAmount': 'Cantidad de B',
        'mixUse': 'Pintar con la mezcla', 'mixResult': 'Mezcla: {c}',
        'valuesTitle': 'Luz en tres tonos', 'valuesBase': 'Color base', 'valuesLightDir': 'Color de la luz',
        'valLight': 'Claro', 'valMid': 'Medio', 'valShadow': 'Sombra', 'valuesUse': 'Pintar con el tono {name}',
        'valuesNote': 'El tono claro se acerca al color de la luz; la sombra se va hacia el azul del cielo y pierde fuerza. Es la relación que describe James Gurney en «Color and Light» (2010).',
        'coloursUsed': 'Colores usados en este dibujo: {n}',
        # --- capas ---
        'layers': 'Capas', 'layerN': 'Capa {n}', 'layerBg': 'Fondo', 'layerTitle': 'Capa: {name}',
        'layerName': 'Nombre de la capa', 'visible': 'Visible', 'layerOpacity': 'Opacidad de la capa', 'blend': 'Modo de fusión',
        'blend_normal': 'Normal', 'blend_multiply': 'Multiplicar', 'blend_screen': 'Trama', 'blend_overlay': 'Superponer',
        'blend_darken': 'Oscurecer', 'blend_lighten': 'Aclarar', 'blend_add': 'Sumar luz',
        'addLayer': 'Añadir capa', 'dupLayer': 'Duplicar capa', 'mergeLayer': 'Fusionar con la de abajo', 'delLayer': 'Borrar capa',
        'layerUp': 'Subir la capa', 'layerDown': 'Bajar la capa',
        'layerAdded': 'Capa añadida', 'layerDuplicated': 'Capa duplicada', 'layerMerged': 'Capas fusionadas',
        'layerDeleted': 'Capa borrada', 'layerMoved': 'Capa movida', 'layerNow': 'Dibujas en la capa {name}',
        'lastLayer': 'Cada dibujo necesita al menos una capa.', 'maxLayers': 'Máximo {n} capas por dibujo.',
        'noMergeBelow': 'Esta capa ya es la de más abajo.', 'marksN': '{n} marcas',
        # --- serie ---
        'series': 'Serie', 'sheetOf': 'Dibujo {n} de {m}', 'sheetN': 'Dibujo {n}',
        'addSheet': 'Dibujo nuevo', 'dupSheet': 'Duplicar el dibujo', 'delSheet': 'Borrar el dibujo',
        'sheetAdded': 'Dibujo añadido', 'sheetDeleted': 'Dibujo borrado', 'maxSheets': 'Máximo {n} dibujos por proyecto.',
        'lastSheet': 'El proyecto necesita al menos un dibujo.',
        'rulesLabel': 'Mis reglas (una por línea)',
        'rulesCount': 'Reglas escritas: {r}. Dibujos con trazos: {d} de {m}.',
        'altLabel': 'Descripción de este dibujo',
        'altHelp': 'Cuenta en una o dos frases qué se ve. Sirve a quien no puede ver la imagen y acompaña al dibujo al imprimir.',
        'docTitle': 'Título del proyecto', 'docSection': 'Proyecto', 'untitled': 'Sin título',
        'format': 'Formato', 'format_h': 'Horizontal (3:2)', 'format_v': 'Vertical (2:3)', 'format_sq': 'Cuadrado',
        'formatChanged': 'Formato cambiado. Los trazos se quedan donde estaban.',
        # --- simetría y guías ---
        'symTitle': 'Simetría y guías', 'sym': 'Simetría', 'symN': 'Partes (2 a 16)',
        'sym_no': 'Sin simetría', 'sym_v': 'Espejo vertical', 'sym_h': 'Espejo horizontal', 'sym_vh': 'Cuatro espejos',
        'sym_radial': 'Radial', 'sym_kaleido': 'Caleidoscopio',
        'guide': 'Guía', 'guide_no': 'Sin guía', 'guide_grid': 'Cuadrícula',
        'guide_p1': 'Perspectiva de un punto', 'guide_p2': 'Perspectiva de dos puntos', 'guide_p3': 'Perspectiva de tres puntos',
        'gridSize': 'Tamaño de la cuadrícula', 'horizon': 'Altura del horizonte', 'snap': 'Ajustar líneas a la guía',
        'ruler': 'Regla en los bordes', 'showGuides': 'Ver las guías',
        'vpN': 'Punto de fuga {n}', 'vpX': 'X del punto {n}', 'vpY': 'Y del punto {n}',
        'vpMoved': 'Punto de fuga {n} en x {x}, y {y}', 'vpChosen': 'Punto de fuga {n} elegido',
        'guideNote': 'Las guías no salen en las exportaciones de imagen. Con «Ajustar», la línea recta va sola hacia el punto de fuga, o en horizontal o en vertical. La perspectiva de tres puntos añade un punto arriba o abajo para las verticales, como explica Andrew Loomis en «Successful Drawing» (1951).',
        'symChanged': 'Simetría: {s}', 'guideChanged': 'Guía: {g}',
        # --- selección ---
        'selTitle': 'Selección', 'selX': 'X', 'selY': 'Y', 'selW': 'Ancho', 'selH': 'Alto',
        'selFlipH': 'Voltear en horizontal', 'selFlipV': 'Voltear en vertical',
        'selApply': 'Aplicar la selección', 'selCancel': 'Quitar la selección', 'selDelete': 'Borrar lo seleccionado',
        'selMade': 'Selección de {w} × {h} px en x {x}, y {y}', 'selApplied': 'Selección aplicada', 'selCleared': 'Selección quitada',
        'selHelp': 'Marca dos esquinas con Intro o arrastra. Después mueve y cambia el tamaño con las flechas o con los campos, y pulsa «Aplicar la selección».',
        'selEmpty': 'Marca antes una selección en el lienzo.',
        # --- texto ---
        'textTitle': 'Texto', 'textContent': 'Texto', 'textSize': 'Tamaño de la letra', 'textAdd': 'Poner el texto',
        'textPlaced': 'Texto puesto', 'textHelp': 'Escribe el texto, elige el tamaño y pulsa en el lienzo (o Intro con el teclado) para ponerlo.',
        'textDefault': 'Escribe aquí',
        # --- retos ---
        'chTitle': 'Reto', 'chFree': 'Modo libre', 'chFreeDesc': 'Sin reto: usa el estudio como quieras.',
        'chLevel': 'Nivel {n} · {name}', 'chGoal': 'Objetivo', 'chLimits': 'Límites', 'chTip': 'Pista',
        'chCheck': 'Comprobar el reto', 'chClear': 'Quitar el reto', 'chPicked': 'Reto: {t}',
        'chAllOk': 'Reto cumplido. Puedes seguir, exportar o pasar a otro.',
        'chSome': 'Así va el reto. Sigue cuando quieras: no hay prisa.',
        'lvl1': 'Primeros trazos', 'lvl2': 'Luz y volumen', 'lvl3': 'Simetría y patrón',
        'lvl4': 'Perspectiva', 'lvl5': 'Series con reglas propias', 'lvl6': 'Sin techo',
        'ch1T': 'Una sola línea', 'ch1G': 'Dibuja una cara, un animal o un objeto con un único trazo, sin levantar el lápiz.',
        'ch1L': 'Un solo trazo|Sin goma', 'ch1H': 'Ve despacio. Si la línea tiene que volver atrás, que vuelva por encima de sí misma.',
        'ch2T': 'Solo formas', 'ch2G': 'Dibuja un objeto de tu mesa usando solo líneas rectas, rectángulos y elipses. Al menos seis formas.',
        'ch2L': 'Solo línea, rectángulo y elipse|Mínimo 6 formas', 'ch2H': 'Primero la forma más grande; luego las pequeñas encima.',
        'ch3T': 'Tres colores', 'ch3G': 'Un paisaje con solo tres colores. Elige bien cuáles antes de empezar.',
        'ch3L': 'Máximo 3 colores|Mínimo 10 trazos', 'ch3H': 'Un color claro, uno medio y uno oscuro dan mucho juego.',
        'ch4T': 'Luz con tres tonos', 'ch4G': 'Una esfera o una taza con luz: un tono claro, uno medio y uno oscuro del mismo color.',
        'ch4L': 'Exactamente 3 colores|Los tres del mismo tono, de claro a oscuro', 'ch4H': 'Decide de dónde viene la luz. El lado contrario va con el tono oscuro. «Luz en tres tonos» te calcula los tres.',
        'ch5T': 'Tres planos', 'ch5G': 'Una escena con fondo, plano medio y primer plano, cada uno en su propia capa.',
        'ch5L': 'Al menos 3 capas con dibujo', 'ch5H': 'Lo lejano, más claro y con menos detalle.',
        'ch6T': 'Sombra proyectada', 'ch6G': 'Un objeto y la sombra que deja en el suelo con la luz a un lado. Escribe en la descripción de dónde viene la luz.',
        'ch6L': 'Mínimo 15 trazos|Descripción escrita', 'ch6H': 'La sombra sale del objeto hacia el lado contrario a la luz.',
        'ch7T': 'Mariposa simétrica', 'ch7G': 'Una mariposa, una máscara o un escarabajo con simetría de espejo.',
        'ch7L': 'Al menos 6 trazos con simetría vertical', 'ch7H': 'Dibuja solo un lado: el otro sale solo.',
        'ch8T': 'Mandala de ocho', 'ch8G': 'Un mandala con simetría radial de 8 partes, de dentro hacia fuera.',
        'ch8L': 'Simetría radial de 8|Al menos 10 trazos', 'ch8H': 'Anillos: cada vuelta un poco más lejos del centro.',
        'ch9T': 'Caleidoscopio', 'ch9G': 'Un caleidoscopio de 6 espejos con cuatro colores como máximo.',
        'ch9L': 'Caleidoscopio de 6|Máximo 4 colores|Mínimo 10 trazos', 'ch9H': 'Los trazos cortos cerca del centro dan estrellas.',
        'ch10T': 'Un punto de fuga', 'ch10G': 'Un pasillo, una carretera o una vía de tren que se aleja hacia un único punto.',
        'ch10L': 'Al menos 6 líneas ajustadas al punto de fuga', 'ch10H': 'Todas las líneas que se alejan van al punto rosa. Las verticales siguen verticales.',
        'ch11T': 'Dos puntos de fuga', 'ch11G': 'Una caja o la esquina de un edificio vista de frente a la arista, con dos puntos de fuga.',
        'ch11L': 'Al menos 10 líneas ajustadas|Usa los dos puntos de fuga', 'ch11H': 'Empieza por la arista vertical más cercana y lleva sus extremos a cada punto.',
        'ch12T': 'Tres edificios', 'ch12G': 'Una calle con tres edificios en perspectiva de dos puntos y el horizonte bajo, como vista desde el suelo.',
        'ch12L': 'Al menos 24 líneas ajustadas|Dos puntos de fuga|Al menos 2 capas', 'ch12H': 'Baja el horizonte en «Altura del horizonte»: los edificios parecerán más altos.',
        'ch13T': 'La misma cosa, cuatro luces', 'ch13G': 'El mismo objeto en cuatro dibujos de la serie: luz de la mañana, del mediodía, de la tarde y de la noche.',
        'ch13L': '4 dibujos con trazos', 'ch13H': 'Usa «Duplicar el dibujo» para partir del mismo contorno.',
        'ch14T': 'Serie de diez con reglas propias', 'ch14G': 'Escribe tres reglas tuyas en «Mis reglas» y haz una serie de diez dibujos que las cumpla.',
        'ch14L': '3 reglas escritas|10 dibujos con trazos', 'ch14H': 'Reglas que funcionan: un color por dibujo, siempre el mismo encuadre, cada dibujo un trazo más.',
        'ch15T': 'Reto combinado', 'ch15G': 'Un tema, un límite y una técnica al azar. Pulsa «Otro reto» cuantas veces quieras: no se acaban.',
        'ch15L': '', 'ch15H': 'Si una combinación no te dice nada, pide otra.',
        'limShapes': 'Este reto es solo con línea recta, rectángulo y elipse.',
        'limNoErase': 'Este reto es sin goma.',
        'limStrokes': 'Este reto permite {n} trazo. Deshaz el último si quieres repetirlo.',
        'limColors': 'Este reto permite {n} colores y ya los has usado. Elige uno de los que ya están en el dibujo.',
        'chkMinStrokes': 'Trazos: {n} (mínimo {m})', 'chkMaxStrokes': 'Trazos: {n} (máximo {m})',
        'chkColors': 'Colores: {n} (máximo {m})', 'chkExactColors': 'Colores: {n} (hacen falta {m})',
        'chkHue': 'Los colores son del mismo tono y van de claro a oscuro (diferencia de luz: {spread} %; hace falta 25 % o más)',
        'chkShapes': 'Solo líneas rectas, rectángulos y elipses',
        'chkLayers': 'Capas con dibujo: {n} (mínimo {m})',
        'chkSym': 'Trazos con {sym}: {n} (mínimo {m})',
        'chkVp': 'Líneas ajustadas a los puntos de fuga: {n} (mínimo {m})',
        'chkVps': 'Puntos de fuga usados: {n} de {m}',
        'chkSheets': 'Dibujos con trazos: {n} (mínimo {m})',
        'chkRules': 'Reglas escritas: {n} (mínimo {m})',
        'chkAlt': 'Descripción escrita',
        'genBtn': 'Otro reto', 'genOut': 'Dibuja {a}, {b}, {c}.',
        'genPools': 'un faro|tu calle de noche|una planta de interior|un tren que llega|una ciudad bajo el agua|tu mochila por dentro|un mercado|un robot jardinero|una tormenta vista desde la ventana|el esqueleto de un pez|una estación espacial|un árbol en cuatro estaciones||solo con tres colores|con una sola línea|sin goma|con simetría radial|en tres capas|solo con formas|con el horizonte muy bajo|con dos puntos de fuga|con la mano que no usas (con ratón o dedo)|sin usar el negro||con luz de un solo lado|con mucho detalle en un rincón y nada en el resto|como un plano visto desde arriba|como un cartel|en una tira de cuatro dibujos|como si fuera de noche|con trazos muy cortos|en tamaño enorme, que se salga del lienzo',
        # --- puntos de partida ---
        'stLandscape': 'Paisaje en tres planos', 'stLandscapeD': 'Fondo, plano medio y primer plano, cada uno en su capa.',
        'stMandala': 'Mandala empezado', 'stMandalaD': 'Simetría radial de 8 partes, con los primeros anillos puestos.',
        'stStreet': 'Calle en dos puntos', 'stStreetD': 'Guía de dos puntos de fuga y las primeras líneas de la calle.',
        'stSphere': 'Esfera con luz', 'stSphereD': 'Una esfera en tres tonos: claro, medio y sombra.',
        # --- exportar ---
        'exportPng': 'Exportar el dibujo (PNG)', 'exportLayers': 'Exportar las capas (ZIP de PNG)',
        'exportSvg': 'Exportar en vectorial (SVG)', 'exportPrint': 'Imprimir o guardar en PDF',
        'layerFile': 'capa-{n}-{name}', 'zipDone': '{n} capas en el ZIP.',
        'svgDone': 'SVG con {n} elementos vectoriales.', 'svgEmpty': 'Este dibujo no tiene nada vectorial todavía: dibuja formas o texto.',
        'svgNote': 'El SVG lleva las formas, el texto y los trazos como líneas vectoriales, sin la textura del pincel.',
        'printTitle': '{title} · dibujo {n} de {m}',
        # --- resumen y órdenes ---
        'summary': 'Dibujo {n} de {m}, {w} × {h} píxeles. {marks} marcas en {used} de {layers} capas. Capa activa: {layer}. Colores: {colours}. Simetría: {sym}. Guía: {guide}. Reto: {challenge}.',
        'cmdCheck': 'Comprobar el reto', 'cmdNewSheet': 'Dibujo nuevo en la serie', 'cmdAddLayer': 'Añadir capa',
        'cmdFit': 'Ver todo el lienzo', 'cmdValues': 'Calcular la luz en tres tonos',
        'undoStroke': 'Trazo', 'undoShape': 'Forma', 'undoFill': 'Relleno', 'undoText': 'Texto', 'undoSel': 'Selección',
        'undoLayer': 'Capa', 'undoSheet': 'Dibujo', 'undoGuide': 'Guías', 'undoDoc': 'Proyecto',
    },
    'en': {
        'canvasLabel': 'Drawing canvas',
        'canvasHelp': 'The arrow keys move the cursor around the canvas (a short step with Shift). Enter or Space put the pen down and lift it; with shapes, the first Enter marks the start and the second the end. Esc cancels the stroke. [ and ] change the size. With the Vanishing points tool, the arrow keys move the chosen point.',
        'kDibCursor': 'On the canvas: arrow keys for the cursor; Enter or Space to draw',
        'kDibSize': '[ and ] change the brush size; Esc cancels the stroke',
        'kDibVp': 'With Vanishing points: arrow keys move the point; V changes point',
        'cursorAt': 'Cursor at x {x}, y {y} · {pen}',
        'penDown': 'pen down', 'penUp': 'pen up', 'penUpSaved': 'Pen up, stroke saved',
        'shapeStart': 'First point marked. Move the cursor and press Enter to finish.',
        'shapeDone': 'Shape saved', 'cancelled': 'Stroke cancelled', 'drawn': 'Stroke',
        'hiddenLayer': 'The chosen layer is hidden. Make it visible or pick another one to draw on.',
        'lockedByChallenge': 'The challenge does not allow this tool.',
        'tool_pencil': 'Pencil', 'tool_soft': 'Soft brush', 'tool_marker': 'Marker', 'tool_water': 'Watercolour',
        'tool_chalk': 'Chalk and charcoal', 'tool_air': 'Airbrush', 'tool_eraser': 'Eraser', 'tool_picker': 'Colour picker',
        'tool_line': 'Line', 'tool_rect': 'Rectangle', 'tool_ellipse': 'Ellipse', 'tool_fill': 'Fill',
        'tool_text': 'Text', 'tool_select': 'Select', 'tool_vp': 'Vanishing points', 'tool_pan': 'Move the view',
        'fitView': 'Fit to view', 'toolPicked': 'Tool: {t}',
        'brushTitle': 'Tool', 'size': 'Size', 'px': 'px', 'opacity': 'Opacity', 'hardness': 'Hardness',
        'flow': 'Flow', 'stabilise': 'Stroke stabilisation', 'pct': '%',
        'fillShapes': 'Fill the shapes', 'usePressure': 'Use stylus pressure', 'useTilt': 'Use stylus tilt',
        'brushNote': 'Pressure and tilt only change anything if you draw with a stylus. With a mouse or a finger the stroke keeps a constant width.',
        'inputPen': 'Stylus: pressure {p}%', 'inputPenTilt': 'Stylus: pressure {p}%, tilt {a}°', 'inputMouse': 'Mouse or finger: constant width',
        'sizeSet': 'Size: {n} px',
        'colourTitle': 'Colour', 'palette': 'Palette', 'customColour': 'Another colour', 'colourNow': 'Colour: {c}', 'picked': 'Colour picked: {c}',
        'colourNames': 'black|grey|light grey|white|maroon|red|orange|yellow|olive green|green|teal|blue|navy|violet|dark pink|brown',
        'hueNames': 'red|orange|yellow-green|green|turquoise|blue|violet|pink|white|black|grey',
        'light': 'light', 'dark': 'dark', 'hueOrder': '{q} {h}',
        'mixTitle': 'Mix two colours', 'mixA': 'Colour A', 'mixB': 'Colour B', 'mixAmount': 'Amount of B',
        'mixUse': 'Paint with the mix', 'mixResult': 'Mix: {c}',
        'valuesTitle': 'Light in three values', 'valuesBase': 'Base colour', 'valuesLightDir': 'Colour of the light',
        'valLight': 'Light', 'valMid': 'Mid', 'valShadow': 'Shadow', 'valuesUse': 'Paint with the {name} value',
        'valuesNote': 'The light value moves towards the colour of the light; the shadow moves towards the blue of the sky and loses strength. This is the relationship James Gurney describes in “Color and Light” (2010).',
        'coloursUsed': 'Colours used in this drawing: {n}',
        'layers': 'Layers', 'layerN': 'Layer {n}', 'layerBg': 'Background', 'layerTitle': 'Layer: {name}',
        'layerName': 'Layer name', 'visible': 'Visible', 'layerOpacity': 'Layer opacity', 'blend': 'Blend mode',
        'blend_normal': 'Normal', 'blend_multiply': 'Multiply', 'blend_screen': 'Screen', 'blend_overlay': 'Overlay',
        'blend_darken': 'Darken', 'blend_lighten': 'Lighten', 'blend_add': 'Add light',
        'addLayer': 'Add layer', 'dupLayer': 'Duplicate layer', 'mergeLayer': 'Merge with the one below', 'delLayer': 'Delete layer',
        'layerUp': 'Move the layer up', 'layerDown': 'Move the layer down',
        'layerAdded': 'Layer added', 'layerDuplicated': 'Layer duplicated', 'layerMerged': 'Layers merged',
        'layerDeleted': 'Layer deleted', 'layerMoved': 'Layer moved', 'layerNow': 'You are drawing on layer {name}',
        'lastLayer': 'Each drawing needs at least one layer.', 'maxLayers': '{n} layers per drawing at most.',
        'noMergeBelow': 'This layer is already the bottom one.', 'marksN': '{n} marks',
        'series': 'Series', 'sheetOf': 'Drawing {n} of {m}', 'sheetN': 'Drawing {n}',
        'addSheet': 'New drawing', 'dupSheet': 'Duplicate the drawing', 'delSheet': 'Delete the drawing',
        'sheetAdded': 'Drawing added', 'sheetDeleted': 'Drawing deleted', 'maxSheets': '{n} drawings per project at most.',
        'lastSheet': 'The project needs at least one drawing.',
        'rulesLabel': 'My rules (one per line)',
        'rulesCount': 'Rules written: {r}. Drawings with marks: {d} of {m}.',
        'altLabel': 'Description of this drawing',
        'altHelp': 'Say in one or two sentences what can be seen. It helps anyone who cannot see the image and goes with the drawing when you print.',
        'docTitle': 'Project title', 'docSection': 'Project', 'untitled': 'Untitled',
        'format': 'Format', 'format_h': 'Landscape (3:2)', 'format_v': 'Portrait (2:3)', 'format_sq': 'Square',
        'formatChanged': 'Format changed. The marks stay where they were.',
        'symTitle': 'Symmetry and guides', 'sym': 'Symmetry', 'symN': 'Parts (2 to 16)',
        'sym_no': 'No symmetry', 'sym_v': 'Vertical mirror', 'sym_h': 'Horizontal mirror', 'sym_vh': 'Four mirrors',
        'sym_radial': 'Radial', 'sym_kaleido': 'Kaleidoscope',
        'guide': 'Guide', 'guide_no': 'No guide', 'guide_grid': 'Grid',
        'guide_p1': 'One-point perspective', 'guide_p2': 'Two-point perspective', 'guide_p3': 'Three-point perspective',
        'gridSize': 'Grid size', 'horizon': 'Horizon height', 'snap': 'Snap lines to the guide',
        'ruler': 'Ruler along the edges', 'showGuides': 'Show the guides',
        'vpN': 'Vanishing point {n}', 'vpX': 'X of point {n}', 'vpY': 'Y of point {n}',
        'vpMoved': 'Vanishing point {n} at x {x}, y {y}', 'vpChosen': 'Vanishing point {n} chosen',
        'guideNote': 'Guides never appear in the image exports. With “Snap”, the straight line heads for the vanishing point on its own, or runs horizontally or vertically. Three-point perspective adds a point above or below for the verticals, as Andrew Loomis explains in “Successful Drawing” (1951).',
        'symChanged': 'Symmetry: {s}', 'guideChanged': 'Guide: {g}',
        'selTitle': 'Selection', 'selX': 'X', 'selY': 'Y', 'selW': 'Width', 'selH': 'Height',
        'selFlipH': 'Flip horizontally', 'selFlipV': 'Flip vertically',
        'selApply': 'Apply the selection', 'selCancel': 'Clear the selection', 'selDelete': 'Delete what is selected',
        'selMade': 'Selection of {w} × {h} px at x {x}, y {y}', 'selApplied': 'Selection applied', 'selCleared': 'Selection cleared',
        'selHelp': 'Mark two corners with Enter or drag. Then move it and change its size with the arrow keys or the fields, and press “Apply the selection”.',
        'selEmpty': 'Mark a selection on the canvas first.',
        'textTitle': 'Text', 'textContent': 'Text', 'textSize': 'Letter size', 'textAdd': 'Place the text',
        'textPlaced': 'Text placed', 'textHelp': 'Write the text, choose the size and click on the canvas (or press Enter with the keyboard) to place it.',
        'textDefault': 'Write here',
        'chTitle': 'Challenge', 'chFree': 'Free mode', 'chFreeDesc': 'No challenge: use the studio however you like.',
        'chLevel': 'Level {n} · {name}', 'chGoal': 'Goal', 'chLimits': 'Limits', 'chTip': 'Hint',
        'chCheck': 'Check the challenge', 'chClear': 'Drop the challenge', 'chPicked': 'Challenge: {t}',
        'chAllOk': 'Challenge done. You can carry on, export it or move to another one.',
        'chSome': 'Here is how the challenge is going. Carry on whenever you like: there is no rush.',
        'lvl1': 'First marks', 'lvl2': 'Light and volume', 'lvl3': 'Symmetry and pattern',
        'lvl4': 'Perspective', 'lvl5': 'Series with your own rules', 'lvl6': 'No ceiling',
        'ch1T': 'One single line', 'ch1G': 'Draw a face, an animal or an object in one stroke, without lifting the pencil.',
        'ch1L': 'One stroke only|No eraser', 'ch1H': 'Go slowly. If the line needs to go back, let it run over itself.',
        'ch2T': 'Shapes only', 'ch2G': 'Draw an object from your desk using only straight lines, rectangles and ellipses. At least six shapes.',
        'ch2L': 'Line, rectangle and ellipse only|At least 6 shapes', 'ch2H': 'Start with the biggest shape, then add the small ones on top.',
        'ch3T': 'Three colours', 'ch3G': 'A landscape using only three colours. Choose them carefully before you start.',
        'ch3L': '3 colours at most|At least 10 strokes', 'ch3H': 'A light, a middle and a dark colour go a long way.',
        'ch4T': 'Light in three values', 'ch4G': 'A sphere or a mug with light on it: one light, one middle and one dark value of the same colour.',
        'ch4L': 'Exactly 3 colours|All three the same hue, from light to dark', 'ch4H': 'Decide where the light comes from. The opposite side takes the dark value. “Light in three values” works the three out for you.',
        'ch5T': 'Three planes', 'ch5G': 'A scene with background, middle ground and foreground, each on its own layer.',
        'ch5L': 'At least 3 layers with drawing', 'ch5H': 'Things far away are lighter and less detailed.',
        'ch6T': 'Cast shadow', 'ch6G': 'An object and the shadow it casts on the floor, with the light to one side. Write in the description where the light comes from.',
        'ch6L': 'At least 15 strokes|Description written', 'ch6H': 'The shadow stretches away from the light.',
        'ch7T': 'Symmetrical butterfly', 'ch7G': 'A butterfly, a mask or a beetle with mirror symmetry.',
        'ch7L': 'At least 6 strokes with vertical symmetry', 'ch7H': 'Draw one side only: the other appears by itself.',
        'ch8T': 'Eight-fold mandala', 'ch8G': 'A mandala with 8-part radial symmetry, from the centre outwards.',
        'ch8L': '8-part radial symmetry|At least 10 strokes', 'ch8H': 'Rings: each round a little further from the centre.',
        'ch9T': 'Kaleidoscope', 'ch9G': 'A 6-mirror kaleidoscope with four colours at most.',
        'ch9L': '6-mirror kaleidoscope|4 colours at most|At least 10 strokes', 'ch9H': 'Short strokes near the centre make stars.',
        'ch10T': 'One vanishing point', 'ch10G': 'A corridor, a road or a railway track heading away towards a single point.',
        'ch10L': 'At least 6 lines snapped to the vanishing point', 'ch10H': 'Every line going into the distance heads for the pink point. Verticals stay vertical.',
        'ch11T': 'Two vanishing points', 'ch11G': 'A box or the corner of a building seen edge-on, with two vanishing points.',
        'ch11L': 'At least 10 snapped lines|Use both vanishing points', 'ch11H': 'Start with the nearest vertical edge and take its ends to each point.',
        'ch12T': 'Three buildings', 'ch12G': 'A street with three buildings in two-point perspective and a low horizon, as if seen from the ground.',
        'ch12L': 'At least 24 snapped lines|Two vanishing points|At least 2 layers', 'ch12H': 'Lower the horizon with “Horizon height”: the buildings will look taller.',
        'ch13T': 'The same thing, four lights', 'ch13G': 'The same object across four drawings in the series: morning, midday, evening and night light.',
        'ch13L': '4 drawings with marks', 'ch13H': 'Use “Duplicate the drawing” to start from the same outline.',
        'ch14T': 'A series of ten with your own rules', 'ch14G': 'Write three rules of your own in “My rules” and make a series of ten drawings that follows them.',
        'ch14L': '3 rules written|10 drawings with marks', 'ch14H': 'Rules that work: one colour per drawing, always the same framing, one more stroke on each drawing.',
        'ch15T': 'Combined challenge', 'ch15G': 'A random subject, limit and technique. Press “Another challenge” as often as you like: they never run out.',
        'ch15L': '', 'ch15H': 'If a combination does nothing for you, ask for another.',
        'limShapes': 'This challenge uses the straight line, rectangle and ellipse only.',
        'limNoErase': 'This challenge has no eraser.',
        'limStrokes': 'This challenge allows {n} stroke. Undo the last one if you want another go.',
        'limColors': 'This challenge allows {n} colours and you have used them all. Pick one that is already in the drawing.',
        'chkMinStrokes': 'Strokes: {n} (at least {m})', 'chkMaxStrokes': 'Strokes: {n} (at most {m})',
        'chkColors': 'Colours: {n} (at most {m})', 'chkExactColors': 'Colours: {n} ({m} needed)',
        'chkHue': 'The colours share one hue and go from light to dark (difference in lightness: {spread}%; 25% or more needed)',
        'chkShapes': 'Straight lines, rectangles and ellipses only',
        'chkLayers': 'Layers with drawing: {n} (at least {m})',
        'chkSym': 'Strokes with {sym}: {n} (at least {m})',
        'chkVp': 'Lines snapped to vanishing points: {n} (at least {m})',
        'chkVps': 'Vanishing points used: {n} of {m}',
        'chkSheets': 'Drawings with marks: {n} (at least {m})',
        'chkRules': 'Rules written: {n} (at least {m})',
        'chkAlt': 'Description written',
        'genBtn': 'Another challenge', 'genOut': 'Draw {a}, {b}, {c}.',
        'genPools': 'a lighthouse|your street at night|a house plant|a train pulling in|a city under water|the inside of your bag|a market|a gardening robot|a storm seen from the window|a fish skeleton|a space station|a tree in four seasons||with only three colours|with one single line|with no eraser|with radial symmetry|on three layers|with shapes only|with a very low horizon|with two vanishing points|with your other hand (mouse or finger)|without using black||with light from one side only|with lots of detail in one corner and none elsewhere|as a plan seen from above|as a poster|as a strip of four drawings|as if it were night|with very short strokes|huge, spilling off the canvas',
        'stLandscape': 'Landscape in three planes', 'stLandscapeD': 'Background, middle ground and foreground, each on its own layer.',
        'stMandala': 'Mandala started', 'stMandalaD': '8-part radial symmetry, with the first rings already drawn.',
        'stStreet': 'Street in two points', 'stStreetD': 'A two-point perspective guide and the first lines of the street.',
        'stSphere': 'Sphere with light', 'stSphereD': 'A sphere in three values: light, mid and shadow.',
        'exportPng': 'Export the drawing (PNG)', 'exportLayers': 'Export the layers (ZIP of PNGs)',
        'exportSvg': 'Export as vectors (SVG)', 'exportPrint': 'Print or save as PDF',
        'layerFile': 'layer-{n}-{name}', 'zipDone': '{n} layers in the ZIP.',
        'svgDone': 'SVG with {n} vector items.', 'svgEmpty': 'This drawing has nothing vector yet: draw shapes or text.',
        'svgNote': 'The SVG carries the shapes, the text and the strokes as vector lines, without the brush texture.',
        'printTitle': '{title} · drawing {n} of {m}',
        'summary': 'Drawing {n} of {m}, {w} × {h} pixels. {marks} marks on {used} of {layers} layers. Active layer: {layer}. Colours: {colours}. Symmetry: {sym}. Guide: {guide}. Challenge: {challenge}.',
        'cmdCheck': 'Check the challenge', 'cmdNewSheet': 'New drawing in the series', 'cmdAddLayer': 'Add layer',
        'cmdFit': 'Fit the whole canvas', 'cmdValues': 'Work out the light in three values',
        'undoStroke': 'Stroke', 'undoShape': 'Shape', 'undoFill': 'Fill', 'undoText': 'Text', 'undoSel': 'Selection',
        'undoLayer': 'Layer', 'undoSheet': 'Drawing', 'undoGuide': 'Guides', 'undoDoc': 'Project',
    },
}

assert set(STRINGS['es']) == set(STRINGS['en']), sorted(set(STRINGS['es']) ^ set(STRINGS['en']))
assert set(PAGE['es']) == set(PAGE['en'])
