"""Estudio de escritura con restricciones (R43). Textos ES/EN.
Sustituye al estudio genérico r40 (kind 'writing') y conserva sus retos: microrrelato de 50 palabras,
texto sin la letra e y cuento con estructura fija (antes, «tres párrafos»).
Fuentes verificadas: Perec, «La Disparition» (Denoël, 1969); Queneau, «Exercices de style» (Gallimard, 1947);
RAE y ASALE, «Ortografía de la lengua española» (Espasa, 2010), capítulo sobre la sílaba (rae.es/ortografía);
Kenn Adams, «How to Improvise a Full-Length Play: The Art of Spontaneous Theater» (Allworth Press, 2007)."""

ENGINE = 'escritura'
SLUG = {'es': 'escritura-restricciones', 'en': 'constraint-writing'}
SCRIPTS = ['ig-suite-escritura.js']
STYLES = ['ig-suite-escritura.css']
LIBRARIES = 'código propio de Iris Green, sin bibliotecas externas; letras Atkinson Hyperlegible, Newsreader y JetBrains Mono (SIL OFL)'
LIBRARIES_EN = 'Iris Green’s own code, with no outside libraries; typefaces Atkinson Hyperlegible, Newsreader and JetBrains Mono (SIL OFL)'

PAGE = {
    'es': {
        'title': 'Escritura con restricciones',
        'description': 'Escribe con reglas que se comprueban mientras tecleas: sin una letra, número exacto de palabras, acróstico, palíndromo, haiku, soneto con contador de sílabas métricas y cuentos con estructura fija.',
        'lede': 'Una regla difícil despierta ideas. Elige una o varias, escribe y mira al momento qué cumples y qué no. Cada aviso tiene un botón «Ir» que te lleva a esa parte del texto.',
        'make': ['Un microrrelato de 50 palabras justas', 'Un texto sin la letra e (un lipograma)', 'Un acróstico con el nombre de tu animal favorito', 'Un haiku 5-7-5 o un soneto de 14 endecasílabos', 'Un cuento con la espina narrativa u otra estructura fija', 'Tu texto en .txt, .md, HTML accesible o PDF'],
        'steps': [
            'Escribe en el editor del centro. Arriba ves si tu texto cumple las reglas.',
            'En Propiedades, activa las reglas que quieras: se pueden combinar.',
            'Pulsa «Ir» junto a un aviso, o «Siguiente aviso» (tecla F8), para ir a esa parte del texto.',
            'En Estructura tienes tus borradores y las partes del texto: versos o párrafos. Elige una parte para ver sus sílabas o sus palabras.',
            'Guarda el proyecto o exporta tu texto desde Archivo.',
        ],
        'sections': [
            {'h': 'Escribir con reglas', 'p': 'Una restricción es una regla que te pones al escribir. El grupo Oulipo (Francia, 1960) la convirtió en juego literario: Georges Perec escribió una novela entera sin la letra e.\n\nAquí puedes combinar lipograma (sin una letra), número de palabras, límite de caracteres, número de párrafos, acróstico, tautograma, univocalismo, palíndromo, haiku, soneto y estructura fija de cuento.'},
            {'h': 'Sílabas métricas', 'p': 'En un poema, la sinalefa une la vocal final de una palabra con la vocal inicial de la siguiente. Además, el verso suma una sílaba si acaba en palabra aguda y resta una si acaba en esdrújula.\n\nEl contador separa sílabas con las reglas de la Ortografía de la RAE y la ASALE (diptongos, hiatos, grupos como pr o bl). Puedes quitar la sinalefa o el ajuste final en Propiedades. La métrica admite licencias: si tu oído dice otra cosa, fíate de tu oído.'},
            {'h': 'Textos en inglés', 'p': 'Si eliges inglés como idioma del borrador, el contador de sílabas es aproximado: cuenta grupos de vocales y descuenta la e muda final y las terminaciones -es y -ed que no suenan. El soneto inglés se comprueba con 14 versos de 10 sílabas.'},
            {'h': 'Estructuras de cuento', 'p': 'La espina narrativa (story spine) es de Kenn Adams: «Había una vez…», «Todos los días…», «Pero un día…», «Por eso…», «Por eso…», «Hasta que finalmente…», «Y desde entonces…». Cada frase de arranque abre un párrafo. También hay plantillas propias del taller: tres párrafos, carta a tu yo del pasado y diario de un objeto.'},
            {'h': 'Lenguaje claro', 'p': 'Las estadísticas ayudan a escribir textos fáciles de leer: palabras, frases, longitud media de frase, palabras largas y tiempo de lectura (unas 200 palabras por minuto). Las frases de más de 25 palabras llevan su botón «Ir». Son orientaciones, no notas: un poema puede romperlas a propósito.'},
            {'h': 'Fuentes', 'p': 'Georges Perec, «La Disparition», París: Denoël, 1969.\n\nRaymond Queneau, «Exercices de style», París: Gallimard, 1947.\n\nReal Academia Española y Asociación de Academias de la Lengua Española, «Ortografía de la lengua española», Madrid: Espasa, 2010 (estructura de la sílaba, diptongos, triptongos e hiatos).\n\nKenn Adams, «How to Improvise a Full-Length Play: The Art of Spontaneous Theater», Nueva York: Allworth Press, 2007 (la espina narrativa).'},
        ],
        'links': [('Todo el taller', '/es/taller/'), ('Cómic y guion gráfico', '/es/taller/comic/'), ('Lenguas inventadas', '/es/taller/lenguas-inventadas/')],
    },
    'en': {
        'title': 'Constraint writing',
        'description': 'Write with rules that are checked as you type: a missing letter, an exact word count, acrostics, palindromes, haiku, sonnets with a syllable counter and stories with a fixed structure.',
        'lede': 'A tricky rule sparks ideas. Choose one or several, write, and see straight away what you meet and what you do not. Every warning has a “Go” button that takes you to that part of the text.',
        'make': ['A micro-story of exactly 50 words', 'A text without the letter e (a lipogram)', 'An acrostic with the name of your favourite animal', 'A 5-7-5 haiku or a 14-line sonnet', 'A story built on the story spine or another fixed structure', 'Your text as .txt, .md, accessible HTML or PDF'],
        'steps': [
            'Write in the editor in the centre. Above it you can see whether your text meets the rules.',
            'In Properties, switch on the rules you want: you can combine them.',
            'Press “Go” next to a warning, or “Next warning” (F8 key), to jump to that part of the text.',
            'Structure lists your drafts and the parts of the text: lines or paragraphs. Choose a part to see its syllables or its words.',
            'Save the project or export your text from File.',
        ],
        'sections': [
            {'h': 'Writing with rules', 'p': 'A constraint is a rule you set yourself when you write. The Oulipo group (France, 1960) turned it into a literary game: Georges Perec wrote a whole novel without the letter e.\n\nHere you can combine the lipogram (a missing letter), word count, character limit, number of paragraphs, acrostic, tautogram, univocalism, palindrome, haiku, sonnet and fixed story structure.'},
            {'h': 'Syllables in English', 'p': 'For drafts in English, the syllable counter is approximate: it counts groups of vowels and leaves out a silent final e and the -es and -ed endings that are not pronounced. English sonnets are checked as 14 lines of 10 syllables. Trust your ear when it disagrees.'},
            {'h': 'Spanish metre', 'p': 'For drafts in Spanish, syllables are split with the rules in the Spanish Royal Academy’s Orthography (diphthongs, hiatus, clusters such as pr or bl). Synalepha joins a final vowel to the first vowel of the next word, and the count changes by one when the line ends on a stressed final syllable (+1) or three syllables from the end (−1). Both can be switched off in Properties.'},
            {'h': 'Story structures', 'p': 'The story spine comes from Kenn Adams: “Once upon a time…”, “Every day…”, “But one day…”, “Because of that…”, “Because of that…”, “Until finally…”, “And ever since then…”. Each opening phrase starts a paragraph. There are also templates made for the workshop: three paragraphs, a letter to your past self and the diary of an object.'},
            {'h': 'Plain language', 'p': 'The statistics help you write text that is easy to read: words, sentences, average sentence length, long words and reading time (about 200 words a minute). Sentences of more than 25 words get their own “Go” button. They are guidance, not marks: a poem can break them on purpose.'},
            {'h': 'Sources', 'p': 'Georges Perec, “La Disparition”, Paris: Denoël, 1969.\n\nRaymond Queneau, “Exercices de style”, Paris: Gallimard, 1947.\n\nReal Academia Española and Asociación de Academias de la Lengua Española, “Ortografía de la lengua española”, Madrid: Espasa, 2010 (syllable structure, diphthongs, triphthongs and hiatus).\n\nKenn Adams, “How to Improvise a Full-Length Play: The Art of Spontaneous Theater”, New York: Allworth Press, 2007 (the story spine).'},
        ],
        'links': [('The whole workshop', '/en/workshop/'), ('Comics and storyboards', '/en/workshop/comics-storyboarding/'), ('Invented languages', '/en/workshop/invented-languages/')],
    },
}

_TPL_CUES = {
    'es': {
        'spine': 'Había una vez|Todos los días|Pero un día|Por eso|Por eso|Hasta que finalmente|Y desde entonces',
        'three': 'Al principio|Pero entonces|Al final',
        'letter': 'Querido yo del pasado|Te escribo desde|Lo que más ha cambiado es|Lo que no ha cambiado es|Mi consejo es|Un abrazo',
        'object': 'Me desperté cuando|Lo primero que vi fue|Lo más raro del día fue|Por la noche',
    },
    'en': {
        'spine': 'Once upon a time|Every day|But one day|Because of that|Because of that|Until finally|And ever since then',
        'three': 'At first|But then|In the end',
        'letter': 'Dear past me|I am writing to you from|What has changed most is|What has not changed is|My advice is|Lots of love',
        'object': 'I woke up when|The first thing I saw was|The strangest thing today was|At night',
    },
}

STRINGS = {
    'es': {
        'canvasLabel': 'Editor de texto', 'canvasHelp': 'Escribe en el cuadro de texto. F8 va al siguiente aviso. Ctrl/Cmd + Z deshace.',
        'kWriteNext': 'F8: ir al siguiente aviso de las reglas (también dentro del editor)',
        'kWriteUndo': 'Dentro del editor, Ctrl/Cmd + Z y Ctrl/Cmd + Mayús + Z deshacen y rehacen como el resto del estudio',
        'editorLabel': 'Texto del borrador', 'editorHelp': 'Escribe libremente. Las reglas se comprueban mientras escribes; los avisos están en Propiedades, cada uno con su botón Ir. F8 lleva al siguiente aviso.',
        'untitled': 'Sin título', 'draftN': 'Borrador {n}', 'copyOf': 'Copia de {name}',
        'badgeNone': 'Sin reglas activas: escribe libremente o activa una regla en Propiedades.', 'badgeAll': 'Cumples todas las reglas ({n}).', 'badgeSome': 'Reglas cumplidas: {ok} de {n} · {i}.', 'issue1': '1 aviso', 'quoted': '«{s}»',
        'footCounts': '{w} palabras · {c} caracteres · {l} líneas', 'lineN': 'Línea {n}', 'syllMetric': '{n} sílabas métricas', 'syllApprox': '{n} sílabas (aprox.)', 'wordsN': '{n} palabras',
        'wordsShort': '{n} pal.', 'syllShort': '{n} síl.', 'typed': 'Escritura',
        'drafts': 'Borradores', 'newDraft': 'Nuevo borrador', 'dupDraft': 'Duplicar borrador', 'renameDraft': 'Renombrar', 'delDraft': 'Borrar borrador',
        'draftName': 'Nombre del borrador', 'renameOk': 'Cambiar nombre', 'renamed': 'Nombre cambiado', 'renamedTo': 'Ahora se llama «{name}»',
        'draftOpened': 'Borrador abierto: {name}', 'draftCreated': 'Borrador nuevo: {name}. Las reglas son las mismas que en el anterior.', 'draftDuplicated': 'Duplicado: {name}',
        'draftDeleted': 'Borrador borrado: {name}. Puedes deshacerlo.', 'lastDraft': 'Tiene que quedar al menos un borrador.', 'tooManyDocs': 'Como máximo, {n} borradores por proyecto.',
        'versesTitle': 'Versos', 'parasTitle': 'Párrafos', 'partsTitle': 'Partes del cuento', 'noParts': 'Todavía no hay texto.',
        'verseN': 'Verso {n}', 'paraN': 'Párrafo {n}', 'partN': 'Parte {n}',
        'checksTitle': 'Comprobación', 'noRules': 'No hay reglas activas.', 'allOk': 'Cumples todas las reglas', 'allOkD': '¡Bien hecho!',
        'someBad': 'Reglas cumplidas: {ok} de {n}', 'issuesTotal': 'Hay {i}. Pulsa «Ir» para ver cada uno en el texto.', 'issuesN': '{n} avisos',
        'nextIssue': 'Siguiente aviso', 'noIssues': 'No hay avisos: el texto cumple las reglas.', 'issueN': 'Aviso {i} de {n}',
        'go': 'Ir', 'goTo': 'Ir al texto: {what}', 'selectedText': 'seleccionado «{s}»', 'moreIssues': 'Y {n} avisos más. Corrige estos primero.',
        'okWord': 'Bien', 'checkWord': 'Revisar', 'ruleMet': 'Se cumple.',
        'rulesTitle': 'Reglas', 'rulesHelp': 'Activa las que quieras. Se pueden combinar y cada borrador tiene las suyas.',
        'ruleOn': 'Regla activada: {r}', 'ruleOff': 'Regla desactivada: {r}', 'ruleChanged': 'Regla cambiada',
        'rule_words': 'Número de palabras', 'rule_chars': 'Límite de caracteres', 'rule_paras': 'Número de párrafos', 'rule_lipo': 'Lipograma: sin una letra',
        'rule_acro': 'Acróstico', 'rule_tauto': 'Tautograma', 'rule_univ': 'Univocalismo: una sola vocal', 'rule_pali': 'Palíndromo',
        'rule_haiku': 'Haiku 5-7-5', 'rule_sonnet': 'Soneto', 'rule_story': 'Estructura fija de cuento',
        'ruleHelp_words': 'Cuenta las palabras, también las cortas como «y» o «a».', 'ruleHelp_chars': 'Como en un mensaje corto: un máximo de letras, signos y espacios.',
        'ruleHelp_paras': 'Un párrafo termina con una línea en blanco.', 'ruleHelp_lipo': 'Un lipograma es un texto sin una letra (o sin varias).',
        'ruleHelp_acro': 'Las primeras letras de los versos, de arriba abajo, forman una palabra.', 'ruleHelp_tauto': 'Todas las palabras empiezan por la misma letra.',
        'ruleHelp_univ': 'Todas las palabras usan la misma vocal y ninguna otra.', 'ruleHelp_pali': 'Se lee igual del derecho y del revés (sin contar espacios, signos ni tildes).',
        'ruleHelp_haiku': 'Tres versos de 5, 7 y 5 sílabas. Un verso es una línea.', 'ruleHelp_sonnet': 'Catorce versos de 11 sílabas métricas (endecasílabos). En inglés, de 10. Separa las estrofas con una línea en blanco.',
        'ruleHelp_story': 'Cada párrafo es una parte del cuento, en orden, y empieza con su frase de arranque.',
        'wordsMode': 'Cómo contar', 'mode_exact': 'exactamente', 'mode_max': 'como máximo', 'mode_min': 'como mínimo', 'wordsN2': 'Palabras',
        'charsN': 'Caracteres como máximo', 'countSpaces': 'Contar también los espacios', 'withSpaces': 'con espacios', 'withoutSpaces': 'sin espacios',
        'parasN': 'Párrafos', 'lipoLetters': 'Letras prohibidas', 'lipoAccents': 'Las vocales con tilde o diéresis cuentan como la misma letra (é es e)',
        'acroWord': 'Palabra del acróstico', 'tautoLetter': 'Letra (vacío: la de la primera palabra)', 'tautoShort': 'Permitir palabras de 1 a 3 letras (y, de, la…)',
        'univVowel': 'Vocal', 'paliUnit': 'Qué se lee al revés', 'paliLetters': 'Letra a letra', 'paliWords': 'Palabra a palabra',
        'storyTpl': 'Plantilla', 'storyCues': 'Cada parte empieza con su frase de arranque', 'storyMin': 'Palabras propias como mínimo en cada parte', 'insertCues': 'Añadir las frases de arranque al final',
        'meterTitle': 'Cómo se cuentan las sílabas', 'meterSyn': 'Sinalefa: unir vocal final y vocal inicial', 'meterAcc': 'Ajuste por acento final (aguda +1, esdrújula −1)',
        'meterHelpEs': 'Silabeo según la Ortografía de la RAE y la ASALE (2010). La h no impide la sinalefa. Los signos fuertes (. ; : ? !) la cortan.',
        'meterHelpEn': 'En inglés el recuento es aproximado: grupos de vocales, sin la e muda final ni -es y -ed cuando no suenan.',
        'rWordsT': 'Palabras: {mode} {n}', 'rCharsT': 'Caracteres: como máximo {n} ({sp})', 'rParasT': 'Párrafos: exactamente {n}', 'rLipoT': 'Sin la letra: {l}',
        'rAcroT': 'Acróstico: {w}', 'rTautoT': 'Tautograma con la letra {l}', 'rUnivT': 'Solo la vocal {v}', 'rPaliT': 'Palíndromo (letra a letra)', 'rPaliWT': 'Palíndromo (palabra a palabra)',
        'rHaikuT': 'Haiku 5-7-5', 'rSonnetT': 'Soneto: 14 endecasílabos', 'rSonnetEnT': 'Soneto: 14 versos de 10 sílabas', 'rStoryT': 'Estructura: {tpl} ({n} partes)',
        'countWords': 'Llevas {n} palabras.', 'countChars': 'Llevas {n} caracteres.', 'countParas': 'Llevas {n} párrafos.',
        'iTooMany': 'Sobran {n} palabras, desde «{w}».', 'iTooFew': 'Faltan {n} palabras.', 'iCharsOver': 'Te pasas en {n} caracteres.',
        'iParasOver': 'Sobran {n} párrafos.', 'iParasUnder': 'Faltan {n} párrafos.', 'iLipo': '«{w}» lleva {l}.',
        'iAcroMissing': 'Falta el verso {n}, que empieza por {l}.', 'iAcroWrong': 'El verso {n} empieza por {got}; tiene que empezar por {l}.', 'iAcroExtra': 'El verso {n} sobra: la palabra ya está completa.',
        'iTauto': '«{w}» no empieza por {l}.', 'iUniv': '«{w}» lleva otra vocal: {v}.',
        'iPali': 'La letra {n} («{a}») no coincide con su pareja del final («{b}»).', 'iPali2': 'Pareja del final: «{a}» debería ser «{b}».', 'iPaliShort': 'Escribe al menos dos letras.',
        'iPaliW': '«{a}» no coincide con su pareja del final, «{b}».', 'iPaliW2': 'Pareja del final: «{a}» debería ser «{b}».',
        'iDigits': 'Hay números en cifras: escríbelos con letras para contar bien las sílabas.', 'iVerseExtra': 'El verso {n} sobra.',
        'iVerseCount': 'El verso {n} tiene {c} sílabas; deberían ser {want}.', 'iVersesMissing': 'Faltan {n} versos.',
        'rhymeScheme': 'Rima detectada (versos con el mismo final llevan la misma letra): {s}.', 'stanzas': 'Estrofas: {s} versos.',
        'iPartMissing': 'Falta la parte {n}: «{cue}…».', 'iPartCue': 'La parte {n} tiene que empezar con «{cue}».', 'iPartShort': 'La parte {n} necesita al menos {min} palabras tuyas.', 'iPartExtra': 'El párrafo {n} sobra en esta estructura.',
        'challengesTitle': 'Retos del taller', 'challengesHelp': 'Aplican las reglas del reto a este borrador sin borrar tu texto.',
        'chMicro': 'Microrrelato de 50 palabras', 'chLipo': 'Texto sin la letra e', 'chStory': 'Cuento con estructura fija', 'challengeApplied': 'Reto aplicado: {c}',
        'plainTitle': 'Lenguaje claro', 'statsCaption': 'Estadísticas del borrador', 'stWords': 'Palabras', 'stChars': 'Caracteres', 'noSpaces': '{n} sin espacios',
        'stSentences': 'Frases', 'stParas': 'Párrafos', 'stLines': 'Líneas con texto', 'stAvg': 'Longitud media de frase', 'wordsUnit': 'palabras',
        'stLong': 'Palabras largas (4 sílabas o más)', 'stTime': 'Tiempo de lectura', 'lessMinute': 'menos de 1 minuto', 'minutes': 'unos {n} min',
        'plainAvgOk': 'Frases de {n} palabras de media: se leen con facilidad.', 'plainAvgHigh': 'Frases de {n} palabras de media: prueba a partir alguna.',
        'plainLongSentence': 'Frase larga ({n} palabras): «{s}».',
        'plainNoteEs': 'Orientaciones de lenguaje claro (ISO 24495-1). En español, palabra larga = 4 sílabas o más. Lectura a unas 200 palabras por minuto.',
        'plainNoteEn': 'Orientaciones de lenguaje claro (ISO 24495-1). En inglés, palabra larga = 3 sílabas o más (recuento aproximado). Lectura a unas 200 palabras por minuto.',
        'docTitle': 'Borrador', 'docLang': 'Idioma del texto', 'langEs': 'Español', 'langEn': 'Inglés', 'langChanged': 'Idioma cambiado',
        'docLangHelp': 'El idioma decide cómo se cuentan las sílabas y las frases de arranque de las plantillas.',
        'mGram': 'Sílabas gramaticales', 'mSyn': 'Sinalefas', 'mEnd': 'Final del verso', 'mMetric': 'Sílabas métricas', 'mAlt': 'Con sinalefa triple', 'mRhyme': 'Rima', 'mApprox': 'Sílabas (aprox.)',
        'kind_aguda': 'agudo', 'kind_llana': 'llano', 'kind_esdrujula': 'esdrújulo',
        'syllDivision': 'División en sílabas', 'syllLegend': 'Los guiones separan sílabas; el signo ‿ marca una sinalefa.',
        'selectInText': 'Seleccionar en el texto', 'selectedPart': 'Parte seleccionada', 'backToDoc': 'Ver todo el borrador',
        'marksBtn': 'Marcas en el texto', 'marksOn': 'Marcas visibles: las palabras con aviso llevan un subrayado ondulado.', 'marksOff': 'Marcas ocultas.',
        'templateBtn': 'Plantilla de cuento…', 'templateTitle': 'Plantillas de cuento', 'templateHelp': 'Se añaden las frases de arranque al final del texto y se activa la regla de estructura.',
        'templateInserted': 'Plantilla añadida: {tpl}. Escribe después de cada frase de arranque.',
        'tpl_spine': 'Espina narrativa (Kenn Adams)', 'tpl_three': 'Planteamiento, nudo y desenlace', 'tpl_letter': 'Carta a tu yo del pasado', 'tpl_object': 'Diario de un objeto',
        'tplDesc_spine': 'Siete frases que sostienen cualquier historia.', 'tplDesc_three': 'El cuento clásico en tres párrafos.', 'tplDesc_letter': 'Seis partes para escribirte desde el futuro.', 'tplDesc_object': 'Un día contado por una cosa.',
        'tplCues_spine': _TPL_CUES['es']['spine'], 'tplCues_three': _TPL_CUES['es']['three'], 'tplCues_letter': _TPL_CUES['es']['letter'], 'tplCues_object': _TPL_CUES['es']['object'],
        'tplCuesOther_spine': _TPL_CUES['en']['spine'], 'tplCuesOther_three': _TPL_CUES['en']['three'], 'tplCuesOther_letter': _TPL_CUES['en']['letter'], 'tplCuesOther_object': _TPL_CUES['en']['object'],
        'fontBigger': 'Letra más grande', 'fontSmaller': 'Letra más pequeña', 'fontSizeNow': 'Tamaño de letra: {n} px',
        'editorFont': 'Letra', 'font_atkinson': 'Atkinson (muy legible)', 'font_serif': 'Newsreader (de libro)', 'font_mono': 'Monoespaciada',
        'focusEditor': 'Ir al editor de texto',
        'exportTxt': 'Exportar texto (.txt)', 'exportMd': 'Exportar Markdown (.md)', 'exportHtml': 'Exportar página HTML accesible', 'exportPrint': 'Imprimir o guardar como PDF',
        'exportAllMd': 'Exportar todos los borradores (.md)', 'printing': 'Se abre el diálogo de impresión. Para un PDF, elige «Guardar como PDF».',
        'summary': 'Borrador «{name}» ({n} de {total}): {w} palabras, {s} frases, {l} líneas con texto.', 'summaryRules': 'Reglas: {list}.', 'summaryStart': 'Empieza así: «{s}»', 'emptyDoc': 'El borrador está vacío.',
        'stAcro': 'Acróstico de tu animal favorito', 'stAcroD': 'Las iniciales de los versos forman GATO. Cambia la palabra por tu animal.',
        'stMicro': 'Microrrelato de 50 palabras', 'stMicroD': 'Un cuento de 50 palabras justas. Mira cuántas llevas.',
        'stSonnet': 'Soneto', 'stSonnetD': 'Un primer cuarteto de endecasílabos para seguir hasta 14 versos.',
        'stLipo': 'Texto sin la letra e', 'stLipoD': 'Un lipograma como el de Perec: la e no puede aparecer.',
        'stSpine': 'Cuento con estructura fija', 'stSpineD': 'La espina narrativa de Kenn Adams, con el principio ya escrito.',
        'stThree': 'Cuento en tres párrafos', 'stThreeD': 'Planteamiento, nudo y desenlace: el reto del estudio anterior.',
        'stHaiku': 'Haiku 5-7-5', 'stHaikuD': 'Tres versos cortos con el contador de sílabas.',
        'stTauto': 'Tautograma', 'stTautoD': 'Todas las palabras empiezan por la misma letra.',
        'stUniv': 'Una sola vocal', 'stUnivD': 'Un texto que solo usa la vocal a.',
        'stPali': 'Palíndromo', 'stPaliD': 'Una frase que se lee igual al revés.',
        'ex_acro_name': 'Acróstico', 'ex_acro_word': 'gato',
        'ex_acro': 'Gira y salta por el sofá,\nAraña la alfombra al pasar,\nTumbado al sol se queda ya,\nOjos verdes que brillan al mirar.',
        'ex_micro50_name': 'El faro', 'ex_micro50': 'Cada noche, el faro de la isla contaba barcos para no dormirse. Una noche no pasó ninguno. Preocupado, giró su luz hacia el pueblo y descubrió a todos los vecinos en la playa, mirándolo a él. Era su cumpleaños. Aquella noche, por primera vez, el faro no se sintió solo.',
        'ex_sonnet_name': 'Soneto de la tarde', 'ex_sonnet': 'La tarde se deshace en la ventana\ny el viento borra el nombre de la calle,\nla luz se queda quieta sobre el valle\ny guarda su color para mañana.',
        'ex_lipo_name': 'Paseo sin e', 'ex_lipo': 'Hoy salí a caminar con mi amiga Lucía. Vimos un río claro, hojas rojas y un pato gordo nadando sin prisa. Lucía contó una broma malísima y nos partimos a carcajadas. Ya a oscuras, cada una volvió a su casa.',
        'ex_spine_name': 'La tortuga y la piedra', 'ex_spine': 'Había una vez una tortuga que coleccionaba piedras redondas.\n\nTodos los días recorría la playa y elegía una nueva.\n\nPero un día encontró una piedra completamente cuadrada.\n\nPor eso…\n\nPor eso…\n\nHasta que finalmente…\n\nY desde entonces…',
        'ex_three_name': 'Cuento en tres párrafos', 'ex_three': 'Al principio…\n\nPero entonces…\n\nAl final…',
        'ex_haiku_name': 'Lluvia', 'ex_haiku': 'Cae la lluvia\nsobre el tejado viejo;\ncanta la casa.',
        'ex_tauto_name': 'Pablo', 'ex_tauto': 'Pablo pinta pájaros pequeños por placer.',
        'ex_univ_name': 'Ana', 'ex_univ': 'Ana nada al alba. Hay sal, hay mar, hay calma.',
        'ex_pali_name': 'Ojo rojo', 'ex_pali': 'Ojo rojo.',
    },
    'en': {
        'canvasLabel': 'Text editor', 'canvasHelp': 'Type in the text box. F8 goes to the next warning. Ctrl/Cmd + Z undoes.',
        'kWriteNext': 'F8: go to the next rule warning (also inside the editor)',
        'kWriteUndo': 'Inside the editor, Ctrl/Cmd + Z and Ctrl/Cmd + Shift + Z undo and redo like the rest of the studio',
        'editorLabel': 'Draft text', 'editorHelp': 'Write freely. The rules are checked as you type; the warnings are in Properties, each with its Go button. F8 goes to the next warning.',
        'untitled': 'Untitled', 'draftN': 'Draft {n}', 'copyOf': 'Copy of {name}',
        'badgeNone': 'No rules switched on: write freely or switch a rule on in Properties.', 'badgeAll': 'You meet every rule ({n}).', 'badgeSome': 'Rules met: {ok} of {n} · {i}.', 'issue1': '1 warning', 'quoted': '“{s}”',
        'footCounts': '{w} words · {c} characters · {l} lines', 'lineN': 'Line {n}', 'syllMetric': '{n} metrical syllables', 'syllApprox': '{n} syllables (approx.)', 'wordsN': '{n} words',
        'wordsShort': '{n} w.', 'syllShort': '{n} syl.', 'typed': 'Typing',
        'drafts': 'Drafts', 'newDraft': 'New draft', 'dupDraft': 'Duplicate draft', 'renameDraft': 'Rename', 'delDraft': 'Delete draft',
        'draftName': 'Draft name', 'renameOk': 'Change name', 'renamed': 'Name changed', 'renamedTo': 'It is now called “{name}”',
        'draftOpened': 'Draft opened: {name}', 'draftCreated': 'New draft: {name}. It keeps the rules of the previous one.', 'draftDuplicated': 'Duplicated: {name}',
        'draftDeleted': 'Draft deleted: {name}. You can undo this.', 'lastDraft': 'At least one draft must remain.', 'tooManyDocs': 'A project can have up to {n} drafts.',
        'versesTitle': 'Lines', 'parasTitle': 'Paragraphs', 'partsTitle': 'Parts of the story', 'noParts': 'There is no text yet.',
        'verseN': 'Line {n}', 'paraN': 'Paragraph {n}', 'partN': 'Part {n}',
        'checksTitle': 'Check', 'noRules': 'No rules are switched on.', 'allOk': 'You meet every rule', 'allOkD': 'Well done!',
        'someBad': 'Rules met: {ok} of {n}', 'issuesTotal': 'Warnings: {i}. Press “Go” to see each one in the text.', 'issuesN': '{n} warnings',
        'nextIssue': 'Next warning', 'noIssues': 'No warnings: the text meets the rules.', 'issueN': 'Warning {i} of {n}',
        'go': 'Go', 'goTo': 'Go to the text: {what}', 'selectedText': '“{s}” selected', 'moreIssues': 'And {n} more warnings. Fix these first.',
        'okWord': 'Fine', 'checkWord': 'Look at', 'ruleMet': 'Met.',
        'rulesTitle': 'Rules', 'rulesHelp': 'Switch on the ones you want. You can combine them and each draft has its own.',
        'ruleOn': 'Rule on: {r}', 'ruleOff': 'Rule off: {r}', 'ruleChanged': 'Rule changed',
        'rule_words': 'Word count', 'rule_chars': 'Character limit', 'rule_paras': 'Number of paragraphs', 'rule_lipo': 'Lipogram: a missing letter',
        'rule_acro': 'Acrostic', 'rule_tauto': 'Tautogram', 'rule_univ': 'Univocalism: a single vowel', 'rule_pali': 'Palindrome',
        'rule_haiku': '5-7-5 haiku', 'rule_sonnet': 'Sonnet', 'rule_story': 'Fixed story structure',
        'ruleHelp_words': 'Every word counts, short ones like “a” or “I” too.', 'ruleHelp_chars': 'Like a short message: a maximum number of letters, marks and spaces.',
        'ruleHelp_paras': 'A paragraph ends with a blank line.', 'ruleHelp_lipo': 'A lipogram is a text without one letter (or several).',
        'ruleHelp_acro': 'The first letters of the lines, from top to bottom, spell a word.', 'ruleHelp_tauto': 'Every word starts with the same letter.',
        'ruleHelp_univ': 'Every word uses the same vowel and no other.', 'ruleHelp_pali': 'It reads the same forwards and backwards (ignoring spaces, punctuation and accents).',
        'ruleHelp_haiku': 'Three lines of 5, 7 and 5 syllables.', 'ruleHelp_sonnet': 'Fourteen lines of 10 syllables in English, or 11 metrical syllables in Spanish. Separate the stanzas with a blank line.',
        'ruleHelp_story': 'Each paragraph is one part of the story, in order, and starts with its opening phrase.',
        'wordsMode': 'How to count', 'mode_exact': 'exactly', 'mode_max': 'at most', 'mode_min': 'at least', 'wordsN2': 'Words',
        'charsN': 'Maximum characters', 'countSpaces': 'Count spaces as well', 'withSpaces': 'with spaces', 'withoutSpaces': 'without spaces',
        'parasN': 'Paragraphs', 'lipoLetters': 'Banned letters', 'lipoAccents': 'Vowels with accents or diaeresis count as the same letter (é is e)',
        'acroWord': 'Acrostic word', 'tautoLetter': 'Letter (empty: the first word’s letter)', 'tautoShort': 'Allow words of 1 to 3 letters (a, of, the…)',
        'univVowel': 'Vowel', 'paliUnit': 'What reads backwards', 'paliLetters': 'Letter by letter', 'paliWords': 'Word by word',
        'storyTpl': 'Template', 'storyCues': 'Each part starts with its opening phrase', 'storyMin': 'Minimum words of your own in each part', 'insertCues': 'Add the opening phrases at the end',
        'meterTitle': 'How syllables are counted', 'meterSyn': 'Synalepha: join a final vowel to the next initial vowel', 'meterAcc': 'Final stress adjustment (stressed last syllable +1, third from last −1)',
        'meterHelpEs': 'Syllables are split with the Spanish Royal Academy’s Orthography (2010). A silent h does not stop synalepha. Strong punctuation (. ; : ? !) does.',
        'meterHelpEn': 'In English the count is approximate: groups of vowels, leaving out a silent final e and -es or -ed when they are not pronounced.',
        'rWordsT': 'Words: {mode} {n}', 'rCharsT': 'Characters: at most {n} ({sp})', 'rParasT': 'Paragraphs: exactly {n}', 'rLipoT': 'Without the letter: {l}',
        'rAcroT': 'Acrostic: {w}', 'rTautoT': 'Tautogram with the letter {l}', 'rUnivT': 'Only the vowel {v}', 'rPaliT': 'Palindrome (letter by letter)', 'rPaliWT': 'Palindrome (word by word)',
        'rHaikuT': '5-7-5 haiku', 'rSonnetT': 'Sonnet: 14 hendecasyllables', 'rSonnetEnT': 'Sonnet: 14 lines of 10 syllables', 'rStoryT': 'Structure: {tpl} ({n} parts)',
        'countWords': 'You have {n} words.', 'countChars': 'You have {n} characters.', 'countParas': 'You have {n} paragraphs.',
        'iTooMany': '{n} words too many, from “{w}”.', 'iTooFew': '{n} words short.', 'iCharsOver': '{n} characters over the limit.',
        'iParasOver': '{n} paragraphs too many.', 'iParasUnder': '{n} paragraphs short.', 'iLipo': '“{w}” has {l}.',
        'iAcroMissing': 'Line {n} is missing; it starts with {l}.', 'iAcroWrong': 'Line {n} starts with {got}; it has to start with {l}.', 'iAcroExtra': 'Line {n} is extra: the word is already complete.',
        'iTauto': '“{w}” does not start with {l}.', 'iUniv': '“{w}” has another vowel: {v}.',
        'iPali': 'Letter {n} (“{a}”) does not match its partner at the end (“{b}”).', 'iPali2': 'Partner at the end: “{a}” should be “{b}”.', 'iPaliShort': 'Write at least two letters.',
        'iPaliW': '“{a}” does not match its partner at the end, “{b}”.', 'iPaliW2': 'Partner at the end: “{a}” should be “{b}”.',
        'iDigits': 'There are numbers written as figures: write them as words so the syllables count properly.', 'iVerseExtra': 'Line {n} is extra.',
        'iVerseCount': 'Line {n} has {c} syllables; it should have {want}.', 'iVersesMissing': '{n} lines missing.',
        'rhymeScheme': 'Rhyme found (lines with the same ending get the same letter): {s}.', 'stanzas': 'Stanzas: {s} lines.',
        'iPartMissing': 'Part {n} is missing: “{cue}…”.', 'iPartCue': 'Part {n} has to start with “{cue}”.', 'iPartShort': 'Part {n} needs at least {min} words of your own.', 'iPartExtra': 'Paragraph {n} is extra in this structure.',
        'challengesTitle': 'Workshop challenges', 'challengesHelp': 'They apply the challenge’s rules to this draft without deleting your text.',
        'chMicro': '50-word micro-story', 'chLipo': 'Text without the letter e', 'chStory': 'Story with a fixed structure', 'challengeApplied': 'Challenge applied: {c}',
        'plainTitle': 'Plain language', 'statsCaption': 'Draft statistics', 'stWords': 'Words', 'stChars': 'Characters', 'noSpaces': '{n} without spaces',
        'stSentences': 'Sentences', 'stParas': 'Paragraphs', 'stLines': 'Lines with text', 'stAvg': 'Average sentence length', 'wordsUnit': 'words',
        'stLong': 'Long words (3 syllables or more)', 'stTime': 'Reading time', 'lessMinute': 'under 1 minute', 'minutes': 'about {n} min',
        'plainAvgOk': 'Sentences average {n} words: they are easy to read.', 'plainAvgHigh': 'Sentences average {n} words: try splitting some.',
        'plainLongSentence': 'Long sentence ({n} words): “{s}”.',
        'plainNoteEs': 'Plain-language guidance (ISO 24495-1). In Spanish, a long word has 4 syllables or more. Reading at about 200 words a minute.',
        'plainNoteEn': 'Plain-language guidance (ISO 24495-1). In English, a long word has 3 syllables or more (approximate count). Reading at about 200 words a minute.',
        'docTitle': 'Draft', 'docLang': 'Language of the text', 'langEs': 'Spanish', 'langEn': 'English', 'langChanged': 'Language changed',
        'docLangHelp': 'The language decides how syllables are counted and which opening phrases the templates use.',
        'mGram': 'Dictionary syllables', 'mSyn': 'Synalephas', 'mEnd': 'Line ending', 'mMetric': 'Metrical syllables', 'mAlt': 'With triple synalepha', 'mRhyme': 'Rhyme', 'mApprox': 'Syllables (approx.)',
        'kind_aguda': 'stressed last syllable', 'kind_llana': 'stressed second to last', 'kind_esdrujula': 'stressed third from last',
        'syllDivision': 'Syllable division', 'syllLegend': 'Hyphens split syllables; the ‿ sign marks a synalepha.',
        'selectInText': 'Select in the text', 'selectedPart': 'Part selected', 'backToDoc': 'Show the whole draft',
        'marksBtn': 'Marks in the text', 'marksOn': 'Marks shown: words with a warning have a wavy underline.', 'marksOff': 'Marks hidden.',
        'templateBtn': 'Story template…', 'templateTitle': 'Story templates', 'templateHelp': 'The opening phrases are added at the end of the text and the structure rule is switched on.',
        'templateInserted': 'Template added: {tpl}. Write after each opening phrase.',
        'tpl_spine': 'Story spine (Kenn Adams)', 'tpl_three': 'Beginning, middle and end', 'tpl_letter': 'Letter to your past self', 'tpl_object': 'Diary of an object',
        'tplDesc_spine': 'Seven phrases that hold up any story.', 'tplDesc_three': 'The classic story in three paragraphs.', 'tplDesc_letter': 'Six parts to write to yourself from the future.', 'tplDesc_object': 'A day told by a thing.',
        'tplCues_spine': _TPL_CUES['en']['spine'], 'tplCues_three': _TPL_CUES['en']['three'], 'tplCues_letter': _TPL_CUES['en']['letter'], 'tplCues_object': _TPL_CUES['en']['object'],
        'tplCuesOther_spine': _TPL_CUES['es']['spine'], 'tplCuesOther_three': _TPL_CUES['es']['three'], 'tplCuesOther_letter': _TPL_CUES['es']['letter'], 'tplCuesOther_object': _TPL_CUES['es']['object'],
        'fontBigger': 'Bigger text', 'fontSmaller': 'Smaller text', 'fontSizeNow': 'Text size: {n} px',
        'editorFont': 'Typeface', 'font_atkinson': 'Atkinson (very legible)', 'font_serif': 'Newsreader (bookish)', 'font_mono': 'Monospace',
        'focusEditor': 'Go to the text editor',
        'exportTxt': 'Export text (.txt)', 'exportMd': 'Export Markdown (.md)', 'exportHtml': 'Export accessible HTML page', 'exportPrint': 'Print or save as PDF',
        'exportAllMd': 'Export every draft (.md)', 'printing': 'The print dialogue opens. For a PDF, choose “Save as PDF”.',
        'summary': 'Draft “{name}” ({n} of {total}): {w} words, {s} sentences, {l} lines with text.', 'summaryRules': 'Rules: {list}.', 'summaryStart': 'It starts: “{s}”', 'emptyDoc': 'The draft is empty.',
        'stAcro': 'Acrostic of your favourite animal', 'stAcroD': 'The first letters of the lines spell CAT. Change the word to your animal.',
        'stMicro': '50-word micro-story', 'stMicroD': 'A story of exactly 50 words. See how many you have.',
        'stSonnet': 'Sonnet', 'stSonnetD': 'A first quatrain of ten-syllable lines to continue up to 14 lines.',
        'stLipo': 'Text without the letter e', 'stLipoD': 'A lipogram like Perec’s: the e cannot appear.',
        'stSpine': 'Story with a fixed structure', 'stSpineD': 'Kenn Adams’s story spine, with the beginning already written.',
        'stThree': 'Story in three paragraphs', 'stThreeD': 'Beginning, middle and end: the previous studio’s challenge.',
        'stHaiku': '5-7-5 haiku', 'stHaikuD': 'Three short lines with the syllable counter.',
        'stTauto': 'Tautogram', 'stTautoD': 'Every word starts with the same letter.',
        'stUniv': 'A single vowel', 'stUnivD': 'A text that only uses the vowel a.',
        'stPali': 'Palindrome', 'stPaliD': 'A phrase that reads the same backwards.',
        'ex_acro_name': 'Acrostic', 'ex_acro_word': 'cat',
        'ex_acro': 'Curls up warm beside the fire,\nAlways chasing balls of string,\nTail held high just like a king.',
        'ex_micro50_name': 'The lighthouse', 'ex_micro50': 'Every night, the lighthouse on the island counted boats so it would not fall asleep. One night, none came by. Worried, it turned its light towards the village and found everyone on the beach, looking up at it. It was its birthday. That night, the lighthouse did not feel alone.',
        'ex_sonnet_name': 'Evening sonnet', 'ex_sonnet': 'The light goes slowly from the garden wall,\nthe wind forgets the name of our old street,\nthe stones keep still beneath the passing feet\nand save the colours for tomorrow’s call.',
        'ex_lipo_name': 'A walk without e', 'ex_lipo': 'Today I took a walk with my pal Lucy. On our way, a fat duck was swimming slowly in a still pond, and a cold wind was blowing through old oaks. Lucy told a pun so awful that both of us burst out laughing. At dusk, I found my way back to my own flat.',
        'ex_spine_name': 'The tortoise and the stone', 'ex_spine': 'Once upon a time there was a tortoise who collected round stones.\n\nEvery day she walked along the beach and chose a new one.\n\nBut one day she found a stone that was perfectly square.\n\nBecause of that…\n\nBecause of that…\n\nUntil finally…\n\nAnd ever since then…',
        'ex_three_name': 'Story in three paragraphs', 'ex_three': 'At first…\n\nBut then…\n\nIn the end…',
        'ex_haiku_name': 'Rain', 'ex_haiku': 'Rain on the old roof;\nthe gutter hums a small song,\nthe whole house listens.',
        'ex_tauto_name': 'Peter', 'ex_tauto': 'Peter paints pretty purple parrots.',
        'ex_univ_name': 'A black cat', 'ex_univ': 'A black cat sat and sang and ran.',
        'ex_pali_name': 'Top spot', 'ex_pali': 'Top spot.',
    },
}

assert set(STRINGS['es']) == set(STRINGS['en'])
assert set(PAGE['es']) == set(PAGE['en'])
