"""Estudio de estructuras (R43): construir ↔ probar con física real. Textos ES/EN."""

ENGINE = 'estructuras'
SLUG = {'es': 'estructuras', 'en': 'structures'}
SCRIPTS = ['ig-taller-estructuras-calc.js', 'ig-suite-physics.js', 'ig-suite-estructuras.js']
LIBRARIES = 'PixiJS (MIT), Rapier (Apache 2.0) o Planck.js (MIT)'
LIBRARIES_EN = 'PixiJS (MIT), Rapier (Apache 2.0) or Planck.js (MIT)'

PAGE = {
    'es': {
        'title': 'Estructuras y puentes',
        'description': 'Construye puentes, grúas y estructuras arrastrando piezas y apoyos. Pruébalos con un coche, un tren o pesos: el cálculo da las fuerzas y la física muestra qué pasa.',
        'lede': 'Coloca vigas y apoyos directamente, aplica una carga y pulsa Probar. El cálculo de barras dice cuánto trabaja cada pieza; un motor físico real enseña qué pasa si algo se rompe.',
        'make': ['Un puente de maqueta que aguante un peso', 'Un puente de carretera que cruce un río', 'Una grúa o un voladizo', 'Una tabla de fuerzas (CSV) y una imagen (PNG)'],
        'steps': [
            'Elige la herramienta Pieza y arrastra de un punto a otro. También puedes tocar el inicio y después el final.',
            'Los puntos que tocan el terreno son apoyos (triángulo oscuro). Con la herramienta Apoyo puedes poner o quitar más.',
            'Con Peso cuelgas cargas de un nudo. En un río, en el panel de propiedades eliges qué cruza: una persona, un coche, un camión o un tren.',
            'Pulsa Probar. Verás cuánto trabaja cada pieza y, si algo se rompe, cómo cae la estructura.',
            'Cambia material, sección o forma y vuelve a probar. Guarda el proyecto o exporta la imagen y la tabla.',
        ],
        'sections': [
            {'h': 'Qué pasa al probar', 'p': 'Primero se calcula la estructura como un conjunto de barras unidas por bisagras (método de rigidez). Cada pieza trabaja tirando (tracción) o empujando (compresión). Si una pieza supera lo que aguanta, se rompe; si una pieza larga empuja mucho, se dobla de lado (pandeo).\n\nDespués, un motor físico mueve las piezas de verdad: sin las rotas, la estructura cae como caería. El motor físico enseña el movimiento; las cifras salen del cálculo.'},
            {'h': 'Triángulos', 'p': 'Un cuadrado de barras con bisagras se deforma aunque las barras no se rompan. Un triángulo no: sus tres lados fijan la forma. Por eso casi todos los puentes de barras están hechos de triángulos.'},
            {'h': 'Límites del modelo', 'p': 'Los materiales y las cifras están simplificados para aprender. No sirven para diseñar ni construir una estructura real.'},
        ],
        'links': [('Todo el taller', '/es/taller/'), ('Estudio de máquinas', '/es/taller/maquinas/'), ('Programación y robótica', '/es/taller/robotica/')],
    },
    'en': {
        'title': 'Structures and bridges',
        'description': 'Build bridges, cranes and structures by dragging pieces and supports. Test them with a car, a train or weights: the calculation gives the forces and physics shows what happens.',
        'lede': 'Place beams and supports directly, add a load and press Test. The truss calculation tells you how hard each piece works; a real physics engine shows what happens if something breaks.',
        'make': ['A model bridge that holds a weight', 'A road bridge over a river', 'A crane or a cantilever', 'A table of forces (CSV) and an image (PNG)'],
        'steps': [
            'Choose the Piece tool and drag from one point to another. You can also tap the start and then the end.',
            'Points that touch the ground are supports (dark triangle). With the Support tool you can add or remove more.',
            'With Weight you hang loads from a joint. Over a river, you choose in the properties panel what crosses: a person, a car, a lorry or a train.',
            'Press Test. You will see how hard each piece works and, if something breaks, how the structure falls.',
            'Change the material, section or shape and test again. Save the project or export the image and the table.',
        ],
        'sections': [
            {'h': 'What happens when you test', 'p': 'First the structure is calculated as a set of bars joined by hinges (the stiffness method). Each piece is either pulled (tension) or pushed (compression). If a piece goes beyond what it can take, it breaks; if a long piece is pushed hard, it bends sideways (buckling).\n\nThen a physics engine really moves the pieces: without the broken ones, the structure falls the way it would. The physics engine shows the movement; the numbers come from the calculation.'},
            {'h': 'Triangles', 'p': 'A square of hinged bars changes shape even if no bar breaks. A triangle does not: its three sides fix its shape. That is why almost every bar bridge is made of triangles.'},
            {'h': 'Limits of the model', 'p': 'The materials and numbers are simplified for learning. They are not suitable for designing or building a real structure.'},
        ],
        'links': [('The whole workshop', '/en/workshop/'), ('Machines studio', '/en/workshop/machines/'), ('Coding and robotics', '/en/workshop/robotics/')],
    },
}

STRINGS = {
    'es': {
        'canvasLabel': 'Editor de estructuras', 'canvasHelp': 'Con el teclado: flechas para mover el cursor por la rejilla, Intro para actuar con la herramienta elegida, T para probar. Todo lo que hay en el lienzo aparece también en la lista Estructura.',
        'kEnter': 'Intro o Espacio: actuar en el cursor con la herramienta elegida (marcar inicio y final de una pieza, poner apoyo, colgar peso…)',
        'kTest': 'T: probar · Esc durante la prueba: volver a editar',
        'startGap': 'Hueco entre dos mesas', 'startGapDesc': 'Maqueta de 50 cm con 2 kg colgados en el centro. Empieza sin piezas.',
        'startKids': 'Arregla este puente de palitos', 'startKidsDesc': 'Un puente sencillo que se rompe. Pruébalo, mira qué falla y mejóralo.',
        'startRiver': 'Un coche sobre el río', 'startRiverDesc': 'Río de 12 m y un coche de 1,5 toneladas. Empieza sin piezas.',
        'startTruss': 'Celosía de madera', 'startTrussDesc': 'Un puente de triángulos de 12 m que aguanta un coche y un camión. ¿Y un tren?',
        'startFoot': 'Pasarela peatonal ligera', 'startFootDesc': '18 m para un grupo de personas, en madera. Busca la menor masa con un uso por debajo del 80 %.',
        'startArch': 'Arco sobre un barranco', 'startArchDesc': '30 m para un camión, con apoyos permitidos en las paredes.',
        'startCrane': 'Grúa', 'startCraneDesc': 'Una torre con brazo que sostiene 800 kg. Prueba a alargar el brazo.',
        'table': 'mesa',
        'sceneShort_gap': 'Maqueta · hueco de {span}', 'sceneShort_river': 'Río · {span}', 'sceneShort_free': 'Terreno libre',
        'testingBadge': 'Probando…', 'testDoneBadge': 'Prueba terminada',
        'tool_member': 'Pieza', 'tool_select': 'Mover', 'tool_support': 'Apoyo', 'tool_weight': 'Peso', 'tool_erase': 'Borrar', 'tool_pan': 'Mano',
        'help_member': 'Arrastra de un punto a otro, o toca el inicio y después el final.', 'help_select': 'Toca para elegir; arrastra un nudo para moverlo.',
        'help_support': 'Toca un punto del terreno para poner o quitar un apoyo.', 'help_weight': 'Toca un nudo para colgarle un peso.',
        'help_erase': 'Toca una pieza, un nudo o un peso para quitarlo.', 'help_pan': 'Arrastra para mover la vista.', 'help_test': 'Calcula las fuerzas y muestra qué pasa.',
        'badgeOk': 'Aguanta · máx. {u} %', 'badgeFail': 'No aguanta', 'mirrorOn': 'Simetría activada', 'mirrorOff': 'Simetría desactivada',
        'cantPlace': 'Ahí no se puede poner: está dentro del terreno o fuera de la zona de trabajo.', 'tooMany': 'Demasiadas piezas para el editor.',
        'exists': 'Ya hay una pieza entre esos dos nudos.', 'nodeName': 'Nudo en {pos}', 'support': 'apoyo', 'node': 'Nudo',
        'pieceName': 'Pieza {n} · {mat} · {len}',
        'supportAdded': 'Apoyo añadido.', 'supportRemoved': 'Apoyo quitado.', 'supportOnlyGround': 'Los apoyos solo pueden ir sobre el terreno.',
        'weightNeedsNode': 'Los pesos se cuelgan de un nudo. Toca un nudo o crea uno con una pieza.', 'weightAdded': 'Peso colgado.', 'weightRemoved': 'Peso quitado.',
        'startMarked': 'Inicio marcado. Elige el punto final.', 'added': 'Añadida: {name}',
        'atNode': 'nudo con {n} piezas', 'atGround': 'dentro del terreno', 'atSurface': 'borde del terreno', 'atEmpty': 'punto libre',
        'cursorAt': 'Cursor en {pos}: {what}', 'pendingFrom': 'pieza empezada en {pos}', 'nodeMoveHint': 'Nudo elegido. Muévelo con las flechas.',
        'cancelled': 'Cancelado.', 'cantMove': 'No se puede mover ahí.',
        'weightName': 'Peso de {kg} kg', 'pieces': 'Piezas', 'joints': 'Nudos', 'weights': 'Pesos',
        'material': 'Material', 'section': 'Sección', 'section_1': 'Sencilla', 'section_2': 'Doble', 'section_3': 'Triple',
        'mat_palito': 'Palito', 'mat_liston': 'Listón', 'mat_hilo': 'Hilo', 'mat_madera': 'Madera', 'mat_acero': 'Acero', 'mat_cable': 'Cable',
        'matInfo_palito': 'Palito de manualidades de 10 × 2 mm. Ligero; si es largo y empuja, se dobla pronto.',
        'matInfo_liston': 'Listón de pino de 5 × 5 mm. Más rígido que el palito.',
        'matInfo_hilo': 'Cordel de algodón. Solo aguanta tirando (tracción) y se monta tenso.',
        'matInfo_madera': 'Viga de madera laminada de 20 × 20 cm.', 'matInfo_acero': 'Perfil de acero IPE 300.',
        'matInfo_cable': 'Cable de acero de 50 mm. Solo aguanta tirando y se monta tenso.',
        'materialSet': 'Material: {m}', 'sectionSet': 'Sección cambiada.', 'deletePiece': 'Borrar pieza',
        'posX': 'Distancia desde el borde izquierdo', 'posY': 'Altura sobre el tablero', 'isSupport': 'Es un apoyo',
        'editWeight': 'Ver el peso', 'addWeight': 'Colgar un peso', 'deleteJoint': 'Borrar nudo', 'weightKg': 'Masa', 'weightSet': 'Peso: {kg} kg', 'removeWeight': 'Quitar peso',
        'scene': 'Escena', 'span': 'Hueco', 'crossing': 'Qué cruza el puente', 'crossingSet': 'Cruza: {v}',
        'veh_persona': 'Una persona (80 kg)', 'veh_grupo': 'Un grupo de personas (960 kg)', 'veh_coche': 'Un coche (1,5 t)', 'veh_camion': 'Un camión (26 t)', 'veh_tren': 'Un tren (140 t)',
        'wallSupports': 'Permitir apoyos en las paredes', 'newPieces': 'Piezas nuevas', 'mirror': 'Simetría: cada pieza nueva se copia al otro lado',
        'showNumbers': 'Mostrar número y uso de cada pieza',
        'capInfo': 'Con este largo aguanta {t} tirando y {c} empujando. Pesa {w}.', 'nothing': 'nada',
        'spanSet': 'Hueco: {v}', 'noWeights': 'sin pesos',
        'sceneInfo_gap': 'Maqueta de mesa. Hueco de {span}. Carga: {cross}.', 'sceneInfo_river': 'Tamaño real. Río de {span}. Cruza: {cross}. La carretera va por la línea discontinua, de borde a borde.',
        'sceneInfo_free': 'Terreno libre, tamaño real. Carga: {cross}.',
        'whyTension': 'se parte de tanto tirar', 'whyBuckle': 'se dobla de lado al empujar (pandeo)', 'whyCrush': 'se aplasta al empujar',
        'lastTest': 'En la última prueba', 'memberResult': 'Trabaja {kind}: {f}. Uso: {u} % de lo que aguanta.',
        'kTension': 'tirando', 'kCompression': 'empujando', 'kNone': 'casi nada',
        'noTestYet': 'Construye y pulsa Probar. La prueba incluye el peso de las propias piezas.',
        'empty': 'Todavía no hay piezas.', 'roadGap': 'Falta carretera entre {gaps}. Pon piezas por la línea discontinua, de borde a borde.',
        'holds': 'Aguanta. La pieza que más trabaja llega al {peak} % de lo que resiste.',
        'breaks': 'Se rompe la pieza {n}: {why}{pos}.', 'when': ' cuando la carga está a {x}',
        'thenFalls': 'Sin ella, la estructura se viene abajo.', 'standsDamaged': 'Se rompen {n} piezas, pero lo demás sigue en pie.',
        'mechanism': 'La estructura se mueve sin romperse: le falta algún triángulo. El nudo con círculo rojo no está sujeto.',
        'resultOk': 'Aguanta', 'resultBad': 'No aguanta', 'massInfo': 'Masa de la estructura: {m}',
        'legend': 'Azul: la pieza tira (tracción). Naranja con línea blanca: empuja (compresión). Más gruesa y oscura: más cerca de su límite. Roja discontinua con aspa: rota. La tabla da los valores exactos.',
        'tableCap': 'Fuerzas máximas en cada pieza', 'thN': 'Pieza', 'thKind': 'Trabaja', 'thForce': 'Fuerza', 'thUse': 'Uso', 'thLen': 'Largo',
        'simBreaks': 'Se rompe.', 'simHolds': 'La prueba ha terminado: aguanta.', 'simDone': 'La prueba ha terminado.',
        'backToEdit': 'De vuelta a la edición.', 'backToEditBtn': 'Volver a editar', 'test': 'Probar',
        'exportPng': 'Exportar imagen (PNG)', 'exportCsv': 'Exportar tabla de fuerzas (CSV)',
        'summaryCounts': '{m} piezas, {n} nudos, {a} apoyos.',
    },
    'en': {
        'canvasLabel': 'Structure editor', 'canvasHelp': 'With a keyboard: arrow keys move the cursor around the grid, Enter acts with the chosen tool, T tests. Everything on the canvas is also listed under Structure.',
        'kEnter': 'Enter or Space: act at the cursor with the chosen tool (mark the start and end of a piece, add a support, hang a weight…)',
        'kTest': 'T: test · Esc during a test: back to editing',
        'startGap': 'A gap between two tables', 'startGapDesc': 'A 50 cm model with 2 kg hanging in the middle. Starts with no pieces.',
        'startKids': 'Fix this craft-stick bridge', 'startKidsDesc': 'A simple bridge that breaks. Test it, see what fails and improve it.',
        'startRiver': 'A car over the river', 'startRiverDesc': 'A 12 m river and a 1.5-tonne car. Starts with no pieces.',
        'startTruss': 'Timber truss', 'startTrussDesc': 'A 12 m bridge made of triangles that holds a car and a lorry. What about a train?',
        'startFoot': 'Light footbridge', 'startFootDesc': '18 m for a group of people, in timber. Aim for the lowest mass with use under 80%.',
        'startArch': 'Arch over a canyon', 'startArchDesc': '30 m for a lorry, with supports allowed on the walls.',
        'startCrane': 'Crane', 'startCraneDesc': 'A tower with an arm holding 800 kg. Try making the arm longer.',
        'table': 'table',
        'sceneShort_gap': 'Model · {span} gap', 'sceneShort_river': 'River · {span}', 'sceneShort_free': 'Open ground',
        'testingBadge': 'Testing…', 'testDoneBadge': 'Test finished',
        'tool_member': 'Piece', 'tool_select': 'Move', 'tool_support': 'Support', 'tool_weight': 'Weight', 'tool_erase': 'Delete', 'tool_pan': 'Hand',
        'help_member': 'Drag from one point to another, or tap the start and then the end.', 'help_select': 'Tap to choose; drag a joint to move it.',
        'help_support': 'Tap a point on the ground to add or remove a support.', 'help_weight': 'Tap a joint to hang a weight from it.',
        'help_erase': 'Tap a piece, a joint or a weight to remove it.', 'help_pan': 'Drag to move the view.', 'help_test': 'Works out the forces and shows what happens.',
        'badgeOk': 'Holds · max {u}%', 'badgeFail': 'Does not hold', 'mirrorOn': 'Mirror on', 'mirrorOff': 'Mirror off',
        'cantPlace': 'That point is not allowed: it is inside the ground or outside the work area.', 'tooMany': 'Too many pieces for the editor.',
        'exists': 'There is already a piece between those two joints.', 'nodeName': 'Joint at {pos}', 'support': 'support', 'node': 'Joint',
        'pieceName': 'Piece {n} · {mat} · {len}',
        'supportAdded': 'Support added.', 'supportRemoved': 'Support removed.', 'supportOnlyGround': 'Supports can only go on the ground.',
        'weightNeedsNode': 'Weights hang from a joint. Tap a joint, or make one with a piece.', 'weightAdded': 'Weight hung.', 'weightRemoved': 'Weight removed.',
        'startMarked': 'Start marked. Choose the end point.', 'added': 'Added: {name}',
        'atNode': 'joint with {n} pieces', 'atGround': 'inside the ground', 'atSurface': 'edge of the ground', 'atEmpty': 'free point',
        'cursorAt': 'Cursor at {pos}: {what}', 'pendingFrom': 'piece started at {pos}', 'nodeMoveHint': 'Joint chosen. Move it with the arrow keys.',
        'cancelled': 'Cancelled.', 'cantMove': 'It cannot move there.',
        'weightName': '{kg} kg weight', 'pieces': 'Pieces', 'joints': 'Joints', 'weights': 'Weights',
        'material': 'Material', 'section': 'Section', 'section_1': 'Single', 'section_2': 'Double', 'section_3': 'Triple',
        'mat_palito': 'Craft stick', 'mat_liston': 'Batten', 'mat_hilo': 'String', 'mat_madera': 'Timber', 'mat_acero': 'Steel', 'mat_cable': 'Cable',
        'matInfo_palito': 'A 10 × 2 mm craft stick. Light; when it is long and pushed, it bends early.',
        'matInfo_liston': 'A 5 × 5 mm pine batten. Stiffer than a craft stick.',
        'matInfo_hilo': 'Cotton string. It only holds when pulled (tension) and is fitted taut.',
        'matInfo_madera': 'A 20 × 20 cm glued-laminated timber beam.', 'matInfo_acero': 'An IPE 300 steel section.',
        'matInfo_cable': 'A 50 mm steel cable. It only holds when pulled and is fitted taut.',
        'materialSet': 'Material: {m}', 'sectionSet': 'Section changed.', 'deletePiece': 'Delete piece',
        'posX': 'Distance from the left edge', 'posY': 'Height above the deck', 'isSupport': 'It is a support',
        'editWeight': 'Show the weight', 'addWeight': 'Hang a weight', 'deleteJoint': 'Delete joint', 'weightKg': 'Mass', 'weightSet': 'Weight: {kg} kg', 'removeWeight': 'Remove weight',
        'scene': 'Scene', 'span': 'Gap', 'crossing': 'What crosses the bridge', 'crossingSet': 'Crossing: {v}',
        'veh_persona': 'One person (80 kg)', 'veh_grupo': 'A group of people (960 kg)', 'veh_coche': 'A car (1.5 t)', 'veh_camion': 'A lorry (26 t)', 'veh_tren': 'A train (140 t)',
        'wallSupports': 'Allow supports on the walls', 'newPieces': 'New pieces', 'mirror': 'Mirror: each new piece is copied to the other side',
        'showNumbers': 'Show the number and use of each piece',
        'capInfo': 'At this length it holds {t} pulling and {c} pushing. It weighs {w}.', 'nothing': 'nothing',
        'spanSet': 'Gap: {v}', 'noWeights': 'no weights',
        'sceneInfo_gap': 'Table-top model. Gap of {span}. Load: {cross}.', 'sceneInfo_river': 'Full size. River of {span}. Crossing: {cross}. The road runs along the dashed line, from edge to edge.',
        'sceneInfo_free': 'Open ground, full size. Load: {cross}.',
        'whyTension': 'it snaps from being pulled too hard', 'whyBuckle': 'it bends sideways when pushed (buckling)', 'whyCrush': 'it is crushed when pushed',
        'lastTest': 'In the last test', 'memberResult': 'It is being {kind}: {f}. Use: {u}% of what it can take.',
        'kTension': 'pulled', 'kCompression': 'pushed', 'kNone': 'hardly at all',
        'noTestYet': 'Build, then press Test. The test includes the weight of the pieces themselves.',
        'empty': 'There are no pieces yet.', 'roadGap': 'Road missing between {gaps}. Put pieces along the dashed line, from edge to edge.',
        'holds': 'It holds. The hardest-working piece reaches {peak}% of what it can take.',
        'breaks': 'Piece {n} breaks: {why}{pos}.', 'when': ' when the load is at {x}',
        'thenFalls': 'Without it, the structure comes down.', 'standsDamaged': '{n} pieces break, but the rest stays up.',
        'mechanism': 'The structure moves without breaking: a triangle is missing somewhere. The joint circled in red is not held in place.',
        'resultOk': 'It holds', 'resultBad': 'It does not hold', 'massInfo': 'Mass of the structure: {m}',
        'legend': 'Blue: the piece is pulled (tension). Orange with a white line: it is pushed (compression). Thicker and darker: closer to its limit. Red dashed with a cross: broken. The table gives the exact values.',
        'tableCap': 'Maximum force in each piece', 'thN': 'Piece', 'thKind': 'Being', 'thForce': 'Force', 'thUse': 'Use', 'thLen': 'Length',
        'simBreaks': 'It breaks.', 'simHolds': 'The test has finished: it holds.', 'simDone': 'The test has finished.',
        'backToEdit': 'Back to editing.', 'backToEditBtn': 'Back to editing', 'test': 'Test',
        'exportPng': 'Export image (PNG)', 'exportCsv': 'Export table of forces (CSV)',
        'summaryCounts': '{m} pieces, {n} joints, {a} supports.',
    },
}

assert set(STRINGS['es']) == set(STRINGS['en']), set(STRINGS['es']) ^ set(STRINGS['en'])
