"""Estudio de ideas e inventos (R43): tablero, seis mesas, técnicas guiadas, evaluación y ficha. Textos ES/EN."""

ENGINE = 'ideas'
SLUG = {'es': 'ideas', 'en': 'ideas'}
SCRIPTS = ['ig-suite-ideas.js']
STYLES = ['ig-suite-ideas.css']
LIBRARIES = 'Canvas 2D y SVG del navegador, sin bibliotecas externas'
LIBRARIES_EN = 'The browser’s 2D canvas and SVG, with no outside libraries'

PAGE = {
    'es': {
        'title': 'Ideas e inventos',
        'description': 'De la idea suelta al invento que se puede construir: tablero de ideas y mapa mental, las seis mesas, SCAMPER, 8 ideas en 8 minutos, matrices para decidir y ficha de invento con coste, medidas y peso.',
        'lede': 'Suelta ideas, ordénalas en un tablero, elige con criterios y conviértelas en una ficha de invento con límites reales de dinero, tamaño y peso.',
        'make': [
            'Un tablero de notas y un mapa mental con conexiones',
            'Ideas con SCAMPER, usos alternativos o combinando dos objetos',
            'Ocho ideas en ocho minutos para un problema concreto',
            'Una decisión razonada con matriz de impacto/esfuerzo y matriz ponderada',
            'Una ficha de invento imprimible con piezas, coste, medidas y peso',
        ],
        'steps': [
            'Empieza donde quieras: el tablero, una de las seis mesas o una técnica. Se cambia de vista en la barra o en Estructura.',
            'En el tablero, añade notas y nodos con la herramienta o con el teclado, y únelos desde Propiedades o con la herramienta Unir.',
            'Las mesas y las técnicas tienen un botón para guardar lo que escribes como nota del tablero.',
            'Cuando tengas opciones, pásalas a Evaluar: coloca cada una por impacto y esfuerzo, y añade criterios con peso.',
            'Termina en la ficha de invento: piezas con precio y peso, boceto y comprobaciones. Imprime la ficha o expórtalo todo en Archivo.',
        ],
        'sections': [
            {'h': 'Los ocho retos', 'p': 'Están en Propiedades, en cuatro niveles. Nivel 1, mirar distinto: pasar una pinza por SCAMPER, o tres ideas en cada letra. Nivel 2, encargos pequeños: un soporte para el móvil, algo para no olvidar las llaves. Nivel 3, encargos reales: leer en la cama, una planta sin ti una semana, cables en orden. Nivel 4, sin techo: encargos al azar que no se acaban. Cada encargo trae presupuesto, medidas y peso máximos, y la ficha comprueba sola si se cumplen.'},
            {'h': 'Las seis mesas', 'p': 'Seis actividades cortas para calentar: laboratorio de historias, ¿y si…?, inventa algo nuevo, transforma la forma, muchos usos y cambia el punto de vista. Puedes cambiar el tema de las piezas y pedir más piezas. Nada se puntúa y todo se puede deshacer.'},
            {'h': 'Por qué con límites', 'p': 'Los límites bien puestos ayudan a inventar: obligan a buscar caminos que no se buscarían con dinero y espacio sin fin. Por eso cada encargo tiene un presupuesto, unas medidas y un peso máximos. Los límites nunca llevan puntuación ni tiempo.'},
            {'h': 'De dónde vienen las técnicas', 'p': 'SCAMPER son siete preguntas para transformar algo que ya existe; las recopiló Bob Eberle (1971) a partir de las preguntas de Alex Osborn (1953), que también propuso separar el momento de soltar ideas del de juzgarlas. En «muchos usos» se cuentan dos cosas distintas: cuántas ideas escribes (fluidez) y en cuántas categorías diferentes caen (flexibilidad); esa distinción es de J. P. Guilford (1967).'},
            {'h': 'El tiempo lo llevas tú', 'p': 'El temporizador de «8 ideas en 8 minutos» no se pone en marcha solo: lo inicias, lo pausas, lo alargas un minuto o lo reinicias cuando quieras. Puedes cambiar los minutos y el número de ideas antes o durante.'},
            {'h': 'Fuentes', 'p': 'Osborn, A. F. (1953). Applied Imagination: Principles and Procedures of Creative Problem Solving. Nueva York: Charles Scribner’s Sons.\n\nEberle, R. F. (1971). Scamper: Games for Imagination Development. Buffalo (Nueva York): D.O.K. Publishers.\n\nGuilford, J. P. (1967). The Nature of Human Intelligence. Nueva York: McGraw-Hill.'},
        ],
        'links': [('Todo el taller', '/es/taller/'), ('Dibujo', '/es/taller/dibujo/'), ('Estructuras y puentes', '/es/taller/estructuras/')],
    },
    'en': {
        'title': 'Ideas and inventions',
        'description': 'From a loose idea to something you can build: an idea board and mind map, the six tables, SCAMPER, 8 ideas in 8 minutes, matrices for deciding and an invention sheet with cost, size and weight.',
        'lede': 'Let ideas out, arrange them on a board, choose with criteria and turn them into an invention sheet with real limits of money, size and weight.',
        'make': [
            'A board of notes and a mind map with connections',
            'Ideas from SCAMPER, alternative uses or combining two objects',
            'Eight ideas in eight minutes for one specific problem',
            'A reasoned decision with an impact/effort matrix and a weighted matrix',
            'A printable invention sheet with parts, cost, size and weight',
        ],
        'steps': [
            'Start wherever you like: the board, one of the six tables or a technique. You change view in the toolbar or under Structure.',
            'On the board, add notes and nodes with the tool or the keyboard, and join them from Properties or with the Join tool.',
            'The tables and techniques have a button to keep what you write as a note on the board.',
            'Once you have options, take them to Evaluate: place each one by impact and effort, and add criteria with weights.',
            'Finish on the invention sheet: parts with price and weight, a sketch and the checks. Print the sheet or export everything from File.',
        ],
        'sections': [
            {'h': 'The eight challenges', 'p': 'They are under Properties, in four levels. Level 1, looking differently: take a clothes peg through SCAMPER, or write three ideas for each letter. Level 2, small commissions: a phone stand, something so you never forget your keys. Level 3, real commissions: reading in bed, a plant left alone for a week, tidy cables. Level 4, no ceiling: random commissions that never run out. Each commission comes with a maximum budget, size and weight, and the sheet checks them for you.'},
            {'h': 'The six tables', 'p': 'Six short warm-up activities: story lab, what if…?, invent something new, transform the shape, many uses and change the point of view. You can change the theme of the pieces and ask for more pieces. Nothing is scored and everything can be undone.'},
            {'h': 'Why limits help', 'p': 'Well-chosen limits help you invent: they push you towards paths you would not look for with endless money and space. That is why each commission has a maximum budget, size and weight. Limits never come with scores or countdowns.'},
            {'h': 'Where the techniques come from', 'p': 'SCAMPER is seven questions for transforming something that already exists; Bob Eberle (1971) put them together from Alex Osborn’s questions (1953), who also suggested separating the moment of producing ideas from the moment of judging them. In “many uses” two different things are counted: how many ideas you write (fluency) and how many different categories they fall into (flexibility); that distinction comes from J. P. Guilford (1967).'},
            {'h': 'You are in charge of the time', 'p': 'The “8 ideas in 8 minutes” timer never starts by itself: you start it, pause it, add a minute or reset it whenever you like. You can change the minutes and the number of ideas before or during.'},
            {'h': 'Sources', 'p': 'Osborn, A. F. (1953). Applied Imagination: Principles and Procedures of Creative Problem Solving. New York: Charles Scribner’s Sons.\n\nEberle, R. F. (1971). Scamper: Games for Imagination Development. Buffalo (New York): D.O.K. Publishers.\n\nGuilford, J. P. (1967). The Nature of Human Intelligence. New York: McGraw-Hill.'},
        ],
        'links': [('The whole workshop', '/en/workshop/'), ('Drawing', '/en/workshop/drawing/'), ('Structures and bridges', '/en/workshop/structures/')],
    },
}

_UI = {
    'es': {
        'canvasLabel': 'Tablero de ideas',
        'canvasHelp': 'En el tablero: las flechas mueven la nota elegida o el cursor (paso largo con Mayús); Intro o Espacio actúan con la herramienta; Supr borra la nota; Esc suelta la selección. En «Transforma la forma», las flechas mueven la pieza elegida, R la gira y + y − cambian su tamaño.',
        'kIdeasBoard': 'En el tablero: flechas para mover; Intro o Espacio para actuar; Supr para borrar',
        'kIdeasViews': 'Números 1 a 5: herramientas del tablero (elegir, nota, nodo, unir, borrar)',
        'stToy': 'Inventar un juguete con SCAMPER', 'stToyD': 'Las siete preguntas aplicadas a un juguete que ya tienes.',
        'stSprint': '8 ideas en 8 minutos', 'stSprintD': 'Un problema del instituto y un temporizador que llevas tú.',
        'stBrief': 'Invento con límites de coste y tamaño', 'stBriefD': 'Encargo real: leer en la cama, con presupuesto, medidas y peso.',
        'stTables': 'Las seis mesas', 'stTablesD': 'Seis actividades cortas para soltar ideas sin objetivo fijo.',
        'stMap': 'Mapa mental de ejemplo', 'stMapD': 'Un nodo central y tres ramas para seguir tirando del hilo.',
        'stDecide': 'Decidir entre tres opciones', 'stDecideD': 'Matriz de impacto/esfuerzo y matriz ponderada ya montadas.',
        'grpBoard': 'Tablero', 'grpTables': 'Las seis mesas', 'grpTechniques': 'Técnicas guiadas', 'grpEvaluate': 'Evaluar', 'grpInvention': 'Invento',
        'view_board': 'Tablero de ideas', 'viewInfo_board': 'Notas y nodos que puedes unir. Todo se crea y se mueve con el teclado o con clics.',
        'view_scamper': 'Método SCAMPER', 'viewInfo_scamper': 'Siete preguntas para transformar un objeto que ya existe. Escribe una idea por línea.',
        'view_sprint': '8 ideas en 8 minutos', 'viewInfo_sprint': 'Un problema, un temporizador que llevas tú y una lista de ideas.',
        'view_matrix': 'Evaluar y decidir', 'viewInfo_matrix': 'Coloca cada opción por impacto y esfuerzo, y compárala con criterios con peso.',
        'view_sheet': 'Ficha de invento', 'viewInfo_sheet': 'Qué problema resuelve, para quién, cómo se usa, con qué piezas, cuánto cuesta, mide y pesa.',
        'tableN': 'mesa {n}', 'viewLabel': 'Vista', 'viewShort': 'Vista', 'viewSet': 'Vista: {v}',
        'boardEmpty': 'El tablero está vacío.', 'boardEmptyHow': 'Añade una nota con la herramienta Nota o desde Estructura.',
        'emptyNote': 'nota vacía', 'kindNote': 'Nota', 'kindNode': 'Nodo', 'notesAndNodes': 'Notas y nodos',
        'newNote': 'Nueva nota', 'newNode': 'Nuevo nodo', 'noteAdded': 'Nota añadida', 'nodeAdded': 'Nodo añadido', 'noteDeleted': 'Nota borrada',
        'noteWritten': 'Texto de la nota cambiado', 'noteText': 'Texto', 'colour': 'Color', 'colourSet': 'Color cambiado',
        'colYellow': 'Amarillo', 'colBlue': 'Azul', 'colGreen': 'Verde', 'colPink': 'Rosa', 'colViolet': 'Violeta', 'colGrey': 'Gris',
        'posX': 'Posición horizontal', 'posY': 'Posición vertical', 'moved': 'Movido', 'notePos': 'Nota en {x}, {y}',
        'connectWith': 'Unir con', 'connectToggle': 'Unir o separar', 'connected': 'Unidas', 'disconnected': 'Separadas',
        'connections': 'Uniones', 'noConnections': 'Sin uniones todavía.', 'removeConnection': 'Quitar la unión {n}', 'deleteNote': 'Borrar la nota',
        'selected': 'Elegido: {name}', 'deselected': 'Selección vacía.', 'cursorAt': 'Cursor en {x}, {y}', 'nothingHere': 'Ahí no hay nada.',
        'linkNeedsNote': 'Para unir, elige primero una nota o un nodo.', 'linkStart': 'Primera nota marcada. Elige la segunda para unirlas.', 'cancelled': 'Cancelado.',
        'saveToBoard': 'Guardar en el tablero', 'saveAllToBoard': 'Guardar todas en el tablero', 'savedToBoard': 'Guardado en el tablero.', 'savedNIdeas': '{n} ideas guardadas en el tablero.',
        'toolSelect': 'Elegir', 'toolNote': 'Nota', 'toolNode': 'Nodo', 'toolLink': 'Unir', 'toolErase': 'Borrar',
        'docTitle': 'Documento', 'themeLabel': 'Tema de las piezas', 'themeSet': 'Tema: {v}',
        'modeLabel': 'Cantidad de piezas', 'modeSimple': 'Sencillo', 'modeMore': 'Más piezas', 'modeSet': 'Cantidad de piezas cambiada',
        'seed': 'Semilla del azar', 'seedSet': 'Semilla: {s}', 'seedNote': 'La semilla decide el orden de las piezas al azar. Con la misma semilla salen las mismas.',
        'challenges': 'Retos', 'chooseChallenge': 'Elegir reto', 'noChallenge': 'Sin reto (modo libre)',
        'challengeNote': 'Sin reto puedes usar el estudio como quieras. Los retos solo añaden un encargo y unas comprobaciones.',
        'challengeSet': 'Reto elegido: {c}', 'challengeDropped': 'Reto quitado. Sigues con tu trabajo.', 'challenge': 'Reto',
        'lvl1': 'Nivel 1 · Mirar distinto', 'lvl2': 'Nivel 2 · Encargos pequeños', 'lvl3': 'Nivel 3 · Encargos reales', 'lvl4': 'Nivel 4 · Sin techo',
        'tipWord': 'Pista', 'limScamper': 'Al menos {n} idea(s) en cada letra de SCAMPER', 'limRandom': 'Los límites cambian en cada encargo',
        'goToSheet': 'Ir al reto', 'dropChallenge': 'Quitar el reto',
        'chScamperStatus': 'Letras con {m} idea(s) o más: {n} de 7.', 'chSheetStatus': 'La ficha cumple {n} de {m} comprobaciones.',
        'chTitle_i1': 'Una pinza de la ropa', 'chGoal_i1': 'Pasa una pinza de la ropa por las siete preguntas del método SCAMPER. Una idea en cada letra.', 'chTip_i1': 'Las ideas raras también cuentan. Luego se eligen.', 'chObj_i1': 'una pinza de la ropa',
        'chTitle_i2': 'Tres ideas por letra', 'chGoal_i2': 'Elige un objeto y escribe tres ideas en cada letra de SCAMPER: veintiuna ideas. Una por línea.', 'chTip_i2': 'Cuando se acaban las ideas fáciles empiezan las buenas.',
        'chTitle_i3': 'Soporte para el móvil', 'chGoal_i3': 'Un soporte que sujete el móvil de pie para ver una receta mientras cocinas.', 'chTip_i3': 'Mira qué hay en casa: lo que ya tienes cuesta 0 €.',
        'chTitle_i4': 'No olvidar las llaves', 'chGoal_i4': 'Algo junto a la puerta que haga difícil salir de casa sin las llaves.', 'chTip_i4': 'Piensa en el momento exacto en que se olvidan: ¿qué haces justo antes de abrir la puerta?', 'chExtra_i4': 'Sin pilas ni enchufe',
        'chTitle_i5': 'Leer en la cama', 'chGoal_i5': 'Leer tumbado un rato largo sin que se cansen los brazos ni el cuello.', 'chTip_i5': 'Pregunta a alguien que lea en la cama qué le molesta. Anótalo en «Para quién es».',
        'chTitle_i6': 'Una planta sin ti una semana', 'chGoal_i6': 'Que una planta de maceta tenga agua durante siete días sin que nadie la riegue.', 'chTip_i6': 'En «Cómo compruebo que funciona», escribe cómo lo probarías antes de irte.', 'chExtra_i6': 'Sin electricidad',
        'chTitle_i7': 'Cables en orden', 'chGoal_i7': 'Que los cables de un escritorio no se enreden ni caigan al suelo, y que se pueda desenchufar uno sin mover los demás.', 'chTip_i7': 'Cuenta primero cuántos cables hay y de qué grosor.',
        'chTitle_i8': 'Encargo al azar', 'chGoal_i8': 'Un problema, una persona, un lugar y unos límites al azar. Pide otro encargo cuando quieras: no se acaban.', 'chTip_i8': 'Si el encargo no te dice nada, pide otro.',
        'cat_personaje': 'Personaje', 'cat_lugar': 'Lugar', 'cat_objeto': 'Objeto', 'cat_situacion': 'Situación',
        'another': 'Otra', 'keep': 'Fijar', 'kept': 'fijada', 'keptMsg': '{c}: fijada.', 'released': '{c}: suelta.', 'pieceChanged': '{c}: nueva pieza.',
        'shuffle': 'Barajar lo que no está fijado', 'shuffled': 'Piezas no fijadas cambiadas.', 'allKept': 'Todas las piezas están fijadas. Suelta alguna para barajar.',
        'yourStory': 'Tu historia (escribirla es opcional)', 'storyWritten': 'Historia escrita',
        'question': 'Pregunta', 'yourQuestion': 'Tu pregunta', 'anotherQuestion': 'Otra pregunta', 'newQuestion': 'Nueva pregunta', 'thinkAbout': 'Piensa en…',
        'ownQuestion': 'O escribe tu propia pregunta «¿Y si…?»', 'ownQuestionSaved': 'Pregunta propia guardada',
        'anAnswer': 'Una respuesta', 'add': 'Añadir', 'writeFirst': 'Escribe algo antes de añadirlo.',
        'answerAdded': 'Respuesta añadida. Van {n}.', 'answersN': 'Tienes {n} respuestas.', 'noAnswers': 'Aún no hay respuestas. No hay una correcta: vale cualquiera.',
        'answerRemoved': 'Respuesta quitada.', 'removeN': 'Quitar {n}',
        'changeA': 'Cambiar A', 'changeB': 'Cambiar B', 'changedA': 'Cambiado A.', 'changedB': 'Cambiado B.', 'otherPair': 'Otra combinación', 'otherPairDone': 'Otra combinación.',
        'inventName': 'Nombre del invento', 'nameWritten': 'Nombre escrito', 'whatFor': 'Para qué sirve', 'howWorks': 'Cómo funciona', 'written': 'Escrito',
        'improveIt': 'Mejóralo', 'improvePrompt': 'Pregunta para mejorar', 'needName': 'Ponle un nombre al invento antes de guardarlo.', 'toSheet': 'Llevar a la ficha',
        'addPiece': 'Añadir pieza', 'pieces': 'Piezas', 'pieceAdded': '{s} añadida en el centro.', 'pieceChosen': 'Pieza {n} elegida.',
        'pieceMoved': 'Pieza movida.', 'pieceTurned': 'Pieza girada.', 'pieceResized': 'Tamaño cambiado.', 'pieceRemoved': 'Pieza quitada.', 'pieceMirrored': 'Pieza reflejada.',
        'removePiece': 'Quitar la pieza', 'noPieceChosen': 'Elige una pieza en la lista Estructura para cambiarla.', 'noPieces': 'Añade al menos una pieza.', 'maxPieces': 'Máximo 12 piezas.',
        'shapeTitle': '¿Qué ves? Ponle un título', 'titleWritten': 'Título escrito', 'otherChallenge': 'Otro reto', 'otherChallengeDone': 'Otro reto.',
        'turn': 'Giro', 'size': 'Tamaño', 'mirrorPiece': 'Reflejar la pieza',
        'rowN': 'fila {n}', 'colN': 'columna {n}', 'turnedN': 'girada {n}°', 'sizeN': 'tamaño {n} %', 'mirrored': 'reflejada',
        'object': 'Objeto', 'anotherObject': 'Otro objeto', 'otherObjectDone': 'Otro objeto. La lista empieza de nuevo; puedes deshacerlo.',
        'otherDirection': 'Prueba otra dirección', 'directionPrompt': 'Otra dirección', 'aUse': 'Un uso', 'group': 'Grupo',
        'useAdded': 'Uso añadido.', 'useStats': '{n} usos en {g} grupos distintos.', 'noUses': 'Sin usos todavía. Empieza por el más obvio y luego aléjate de él.', 'useRemoved': 'Uso quitado.',
        'fluencyNote': 'Se cuentan dos cosas: cuántos usos escribes (fluidez) y en cuántos grupos distintos caen (flexibilidad).',
        'scene': 'Escena', 'otherScene': 'Otra escena', 'otherSceneDone': 'Otra escena. Tus textos de la anterior se conservan.',
        'viewpoints': 'Miradas', 'hasText': 'con texto', 'emptyText': 'vacía', 'povWrite': 'Escribe desde esta mirada', 'povWritten': 'Texto escrito',
        'compareViews': 'Comparar miradas', 'noViewsYet': 'Escribe en alguna mirada para compararlas aquí.',
        'scObject': 'Objeto', 'scSuggest': 'Otro objeto', 'scThis': 'este objeto', 'scObjectSet': 'Objeto cambiado',
        'scObjects': 'una pinza de la ropa|un paraguas|una silla|una botella de agua|una mochila|un cepillo de dientes|una cuchara|un despertador|una bicicleta|una caja de zapatos|un lápiz|una lámpara|un calcetín|un cubo',
        'sc_S': 'Sustituir', 'sc_C': 'Combinar', 'sc_A': 'Adaptar', 'sc_M': 'Modificar', 'sc_P': 'Poner otro uso', 'sc_E': 'Eliminar', 'sc_R': 'Reordenar',
        'scQ_S': '¿Qué parte o material de {o} podrías cambiar por otro?',
        'scQ_C': '¿Con qué otra cosa podrías juntar {o}?',
        'scQ_A': '¿Qué idea de otro objeto, animal o lugar podrías copiar para {o}?',
        'scQ_M': '¿Qué pasa si {o} es mucho más grande, más pequeño, más blando o de otra forma?',
        'scQ_P': '¿Para qué más podría servir {o}? ¿Y en otro sitio, o para otra persona?',
        'scQ_E': '¿Qué le puedes quitar a {o} y que siga funcionando?',
        'scQ_R': '¿Qué pasa si cambias el orden, le das la vuelta o lo usas al revés?',
        'scCount': 'Ideas escritas: {n}', 'scWritten': 'Idea escrita',
        'sprintProblem': 'El problema, en una frase', 'problemWritten': 'Problema escrito',
        'timerStart': 'Empezar el tiempo', 'timerPause': 'Pausa', 'timerResume': 'Seguir',
        'timerStarted': 'Tiempo en marcha: quedan {time}.', 'timerPaused': 'Tiempo en pausa: quedan {time}.',
        'timerDone': 'Se acabó el tiempo. Has escrito {n} ideas.', 'timerOneMinute': 'Queda un minuto.',
        'timerPlusMinute': 'Un minuto más', 'timerExtended': 'Un minuto más: quedan {time}.', 'timerReset': 'Reiniciar el tiempo',
        'timerNote': 'El tiempo no empieza solo. Puedes pausarlo, alargarlo o reiniciarlo cuando quieras; la lista de ideas no se borra.',
        'sprintSet': 'Tiempo o meta cambiados', 'sprintMinutes': 'Minutos', 'minutesUnit': 'min', 'sprintTarget': 'Ideas que buscas', 'ideasUnit': 'ideas',
        'anIdea': 'Una idea', 'ideaAdded': 'Idea añadida. Van {n}.', 'ideaRemoved': 'Idea quitada.', 'sprintProgress': '{n} ideas de {m}.',
        'noIdeasYet': 'Escribe alguna idea antes de guardarlas.', 'toMatrix': 'Llevar a Evaluar',
        'anOption': 'Una opción', 'optionAdded': 'Opción añadida.', 'optionRemoved': 'Opción quitada.', 'removeOption': 'Quitar la opción {n}',
        'importIdeas': 'Traer ideas', 'matrixImported': '{n} opciones traídas del tablero y de las ideas.', 'matrixNothingNew': 'No hay ideas nuevas que traer.',
        'noOptions': 'Añade opciones para compararlas.', 'impactEffort': 'Matriz de impacto y esfuerzo',
        'impactEffortNote': 'Pon a cada opción cuánto cambia las cosas (impacto) y cuánto cuesta hacerla (esfuerzo), del 1 al 5. No hay que arrastrar nada.',
        'impact': 'Impacto', 'effort': 'Esfuerzo', 'quadrant': 'Dónde cae',
        'quad_win': 'Hazlo ya', 'quad_big': 'Proyecto grande', 'quad_maybe': 'Si sobra tiempo', 'quad_no': 'Mejor no',
        'quadMapCaption': 'Opciones colocadas por impacto (filas) y esfuerzo (columnas)', 'impactN': 'Impacto {n}', 'effortN': 'Esfuerzo {n}',
        'option': 'Opción', 'remove': 'Quitar', 'decisionMatrix': 'Matriz de decisión ponderada',
        'aCriterion': 'Un criterio', 'criterionAdded': 'Criterio añadido.', 'criterionRemoved': 'Criterio quitado.', 'removeCriterion': 'Quitar el criterio {n}',
        'noCriteria': 'Añade criterios (por ejemplo: coste, tiempo, a quién ayuda) y ponles peso.',
        'weightOf': 'Peso de {c}', 'weightSet': 'Peso cambiado.', 'scoreSet': 'Nota cambiada.', 'total': 'Total', 'best': 'la más alta',
        'decisionNote': 'El total es la media de las notas, dando a cada criterio el peso que le has puesto. Sirve para comparar, no para decidir por ti.',
        'matrixSet': 'Matriz cambiada.', 'criteria': 'Criterios',
        'f_name': 'Nombre del invento', 'f_who': 'Para quién es', 'f_problem': 'Qué problema resuelve', 'f_how': 'Cómo se usa, paso a paso',
        'f_test': 'Cómo compruebo que funciona', 'f_better': 'Qué mejoraría en la versión 2',
        'sizeLegend': 'Medidas del invento montado', 'size_0': 'Largo', 'size_1': 'Ancho', 'size_2': 'Alto', 'sizeSet': 'Medidas cambiadas', 'sheetWritten': 'Ficha cambiada',
        'partsTitle': 'Piezas y materiales', 'partsNote': 'Una fila por pieza. El precio y el peso son por unidad. Lo que ya tienes en casa puede costar 0 €.',
        'partsCap': 'Piezas del invento', 'thPart': 'Pieza o material', 'thQty': 'Cantidad', 'thPrice': 'Precio por unidad (€)', 'thWeight': 'Peso por unidad (g)',
        'ariaPart': 'Pieza {n}: nombre', 'ariaQty': 'Pieza {n}: cantidad', 'ariaPrice': 'Pieza {n}: precio por unidad en euros', 'ariaWeight': 'Pieza {n}: peso por unidad en gramos',
        'delPart': 'Quitar la pieza {n}', 'partDeleted': 'Pieza quitada', 'partAdded': 'Pieza añadida', 'partChanged': 'Pieza cambiada', 'addPart': 'Añadir pieza', 'noParts': 'Todavía no hay piezas.',
        'totals': 'Coste total: {c} € · Peso total: {w} g · Piezas con nombre: {n} · Medidas: {s} cm', 'totalsShort': 'Totales',
        'checksTitle': 'Cómo va la ficha', 'chkField': '{f}: escrito', 'chkBudget': 'Coste: {c} € (hasta {m} €)',
        'chkSize': 'Medidas: {s} cm (hasta {m} cm, en cualquier orientación)', 'chkWeight': 'Peso: {w} g (hasta {m} g)',
        'chkParts': 'Piezas: {n} (al menos {m})', 'chkScamper': 'Al menos {m} idea(s) en cada letra de SCAMPER',
        'allOk': 'La ficha está completa y cumple el encargo.', 'someOk': 'Así va. Completa lo que falta cuando quieras.',
        'doneWord': 'hecho', 'pendingWord': 'falta',
        'briefWord': 'Encargo', 'noBrief': 'Sin encargo', 'noBriefText': 'Elige un reto en Propiedades o rellena la ficha con tu propio invento.',
        'anotherBrief': 'Otro encargo', 'newBrief': 'Encargo nuevo', 'limits': 'Límites del encargo',
        'limBudget': 'Coste total: hasta {v} €', 'limSize': 'Medidas del invento montado: hasta {v} cm', 'limWeight': 'Peso total: hasta {v} g', 'limParts': 'Piezas distintas: al menos {v}',
        'randText': '{p}, para {who}, {where}.',
        'printSheet': 'Imprimir la ficha', 'printing': 'Preparando la ficha para imprimir.',
        'sketchTitle': 'Boceto', 'sketchHelp': 'Dibuja con el ratón, con el dedo o con el lápiz (si tiene presión, el trazo cambia de grosor). Con el teclado: flechas para mover el punto, Intro para empezar y terminar un trazo, Esc para cancelarlo.',
        'sketchLabel': 'Boceto del invento', 'sketchStart': 'Trazo empezado.', 'sketchEnd': 'Trazo terminado.', 'sketchDrawing': 'dibujando',
        'sketchDrawn': 'Boceto cambiado', 'sketchAt': 'Punto en {x}, {y}', 'sketchCancelled': 'Trazo cancelado.',
        'sketchUndo': 'Quitar el último trazo', 'sketchUndone': 'Último trazo quitado.', 'sketchClear': 'Vaciar el boceto', 'sketchCleared': 'Boceto vacío.', 'sketchEmpty': 'El boceto ya está vacío.',
        'exportMd': 'Exportar texto (Markdown)', 'exportBoardPng': 'Exportar tablero (PNG)', 'exportBoardSvg': 'Exportar tablero (SVG)',
        'sumBoard': '{n} notas y nodos, {l} uniones. La primera dice: {first}', 'sumBoardEmpty': 'El tablero está vacío.',
        'sumShapes': '{n} piezas en la rejilla. Título: {title}', 'sumScamper': 'Objeto: {o}. Ideas escritas: {n}.',
        'sumSprint': '{n} ideas de {m}. Tiempo restante: {time}.', 'sumUses': '{n} usos en {g} grupos distintos.',
        'sumMatrix': '{n} opciones y {c} criterios.', 'sumSheet': 'Invento: {name}. {p} piezas, {c} €, {w} g. Comprobaciones cumplidas: {ok} de {n}.',
        'sumWhatIf': '{n} respuestas escritas.', 'sumStories': 'Historia de {n} líneas.', 'sumCombine': 'Invento combinado: {name}.', 'sumPov': '{n} miradas escritas.',
        'toyObject': 'un juguete que ya tienes', 'teenProblem': 'Algo del instituto que se podría hacer mejor',
        'mapCentre': 'Mi idea', 'mapBranch1': 'Para quién', 'mapBranch2': 'Qué problema resuelve', 'mapBranch3': 'Con qué se hace',
        'decideA': 'Opción A', 'decideB': 'Opción B', 'decideC': 'Opción C', 'crit1': 'Coste', 'crit2': 'A cuánta gente ayuda',
    },
    'en': {
        'canvasLabel': 'Idea board',
        'canvasHelp': 'On the board: the arrow keys move the chosen note or the cursor (bigger step with Shift); Enter or Space act with the tool; Delete removes the note; Esc clears the selection. In “Transform the shape”, the arrow keys move the chosen piece, R turns it and + and − change its size.',
        'kIdeasBoard': 'On the board: arrow keys to move; Enter or Space to act; Delete to remove',
        'kIdeasViews': 'Numbers 1 to 5: board tools (choose, note, node, join, delete)',
        'stToy': 'Invent a toy with SCAMPER', 'stToyD': 'The seven questions applied to a toy you already have.',
        'stSprint': '8 ideas in 8 minutes', 'stSprintD': 'A problem from school and a timer you are in charge of.',
        'stBrief': 'Invention with cost and size limits', 'stBriefD': 'A real commission: reading in bed, with budget, size and weight.',
        'stTables': 'The six tables', 'stTablesD': 'Six short activities to get ideas flowing with no fixed goal.',
        'stMap': 'Example mind map', 'stMapD': 'A central node and three branches to keep pulling the thread.',
        'stDecide': 'Choosing between three options', 'stDecideD': 'An impact/effort matrix and a weighted matrix, ready to use.',
        'grpBoard': 'Board', 'grpTables': 'The six tables', 'grpTechniques': 'Guided techniques', 'grpEvaluate': 'Evaluate', 'grpInvention': 'Invention',
        'view_board': 'Idea board', 'viewInfo_board': 'Notes and nodes you can join. Everything is created and moved with the keyboard or with clicks.',
        'view_scamper': 'The SCAMPER method', 'viewInfo_scamper': 'Seven questions to transform an object that already exists. Write one idea per line.',
        'view_sprint': '8 ideas in 8 minutes', 'viewInfo_sprint': 'One problem, a timer you are in charge of and a list of ideas.',
        'view_matrix': 'Evaluate and decide', 'viewInfo_matrix': 'Place each option by impact and effort, and compare it against weighted criteria.',
        'view_sheet': 'Invention sheet', 'viewInfo_sheet': 'What problem it solves, who for, how it is used, with which parts, how much it costs, measures and weighs.',
        'tableN': 'table {n}', 'viewLabel': 'View', 'viewShort': 'View', 'viewSet': 'View: {v}',
        'boardEmpty': 'The board is empty.', 'boardEmptyHow': 'Add a note with the Note tool or from Structure.',
        'emptyNote': 'empty note', 'kindNote': 'Note', 'kindNode': 'Node', 'notesAndNodes': 'Notes and nodes',
        'newNote': 'New note', 'newNode': 'New node', 'noteAdded': 'Note added', 'nodeAdded': 'Node added', 'noteDeleted': 'Note deleted',
        'noteWritten': 'Note text changed', 'noteText': 'Text', 'colour': 'Colour', 'colourSet': 'Colour changed',
        'colYellow': 'Yellow', 'colBlue': 'Blue', 'colGreen': 'Green', 'colPink': 'Pink', 'colViolet': 'Violet', 'colGrey': 'Grey',
        'posX': 'Horizontal position', 'posY': 'Vertical position', 'moved': 'Moved', 'notePos': 'Note at {x}, {y}',
        'connectWith': 'Join with', 'connectToggle': 'Join or separate', 'connected': 'Joined', 'disconnected': 'Separated',
        'connections': 'Joins', 'noConnections': 'No joins yet.', 'removeConnection': 'Remove join {n}', 'deleteNote': 'Delete the note',
        'selected': 'Chosen: {name}', 'deselected': 'Nothing selected.', 'cursorAt': 'Cursor at {x}, {y}', 'nothingHere': 'There is nothing there.',
        'linkNeedsNote': 'To join, first choose a note or a node.', 'linkStart': 'First note marked. Choose the second one to join them.', 'cancelled': 'Cancelled.',
        'saveToBoard': 'Keep on the board', 'saveAllToBoard': 'Keep them all on the board', 'savedToBoard': 'Kept on the board.', 'savedNIdeas': '{n} ideas kept on the board.',
        'toolSelect': 'Choose', 'toolNote': 'Note', 'toolNode': 'Node', 'toolLink': 'Join', 'toolErase': 'Delete',
        'docTitle': 'Document', 'themeLabel': 'Theme of the pieces', 'themeSet': 'Theme: {v}',
        'modeLabel': 'Number of pieces', 'modeSimple': 'Simple', 'modeMore': 'More pieces', 'modeSet': 'Number of pieces changed',
        'seed': 'Random seed', 'seedSet': 'Seed: {s}', 'seedNote': 'The seed decides the order of the random pieces. The same seed gives the same ones.',
        'challenges': 'Challenges', 'chooseChallenge': 'Choose a challenge', 'noChallenge': 'No challenge (free mode)',
        'challengeNote': 'With no challenge you can use the studio however you like. Challenges only add a commission and some checks.',
        'challengeSet': 'Challenge chosen: {c}', 'challengeDropped': 'Challenge dropped. Your work stays as it is.', 'challenge': 'Challenge',
        'lvl1': 'Level 1 · Looking differently', 'lvl2': 'Level 2 · Small commissions', 'lvl3': 'Level 3 · Real commissions', 'lvl4': 'Level 4 · No ceiling',
        'tipWord': 'Tip', 'limScamper': 'At least {n} idea(s) for each SCAMPER letter', 'limRandom': 'The limits change with each commission',
        'goToSheet': 'Go to the challenge', 'dropChallenge': 'Drop the challenge',
        'chScamperStatus': 'Letters with {m} idea(s) or more: {n} of 7.', 'chSheetStatus': 'The sheet meets {n} of {m} checks.',
        'chTitle_i1': 'A clothes peg', 'chGoal_i1': 'Take a clothes peg through the seven questions of the SCAMPER method. One idea for each letter.', 'chTip_i1': 'Odd ideas count too. You choose later.', 'chObj_i1': 'a clothes peg',
        'chTitle_i2': 'Three ideas per letter', 'chGoal_i2': 'Choose an object and write three ideas for each SCAMPER letter: twenty-one ideas. One per line.', 'chTip_i2': 'The good ideas start once the easy ones run out.',
        'chTitle_i3': 'Phone stand', 'chGoal_i3': 'A stand that holds a phone upright so you can follow a recipe while cooking.', 'chTip_i3': 'Look at what is at home: what you already have costs €0.',
        'chTitle_i4': 'Never forget the keys', 'chGoal_i4': 'Something by the door that makes it hard to leave home without your keys.', 'chTip_i4': 'Think about the exact moment they get forgotten: what do you do just before opening the door?', 'chExtra_i4': 'No batteries or plug',
        'chTitle_i5': 'Reading in bed', 'chGoal_i5': 'Read lying down for a long time without tiring your arms or neck.', 'chTip_i5': 'Ask someone who reads in bed what bothers them. Note it under “Who it is for”.',
        'chTitle_i6': 'A plant without you for a week', 'chGoal_i6': 'Keep a potted plant watered for seven days without anyone watering it.', 'chTip_i6': 'Under “How I check it works”, write how you would test it before leaving.', 'chExtra_i6': 'No electricity',
        'chTitle_i7': 'Tidy cables', 'chGoal_i7': 'Stop the cables on a desk from tangling or falling on the floor, so you can unplug one without moving the rest.', 'chTip_i7': 'First count how many cables there are and how thick they are.',
        'chTitle_i8': 'Random commission', 'chGoal_i8': 'A random problem, person, place and set of limits. Ask for another commission whenever you like: they never run out.', 'chTip_i8': 'If a commission does nothing for you, ask for another.',
        'cat_personaje': 'Character', 'cat_lugar': 'Place', 'cat_objeto': 'Object', 'cat_situacion': 'Situation',
        'another': 'Another', 'keep': 'Keep', 'kept': 'kept', 'keptMsg': '{c}: kept.', 'released': '{c}: released.', 'pieceChanged': '{c}: new piece.',
        'shuffle': 'Shuffle what is not kept', 'shuffled': 'Unkept pieces changed.', 'allKept': 'All the pieces are kept. Release one to shuffle.',
        'yourStory': 'Your story (writing it is optional)', 'storyWritten': 'Story written',
        'question': 'Question', 'yourQuestion': 'Your question', 'anotherQuestion': 'Another question', 'newQuestion': 'New question', 'thinkAbout': 'Think about…',
        'ownQuestion': 'Or write your own “What if…?” question', 'ownQuestionSaved': 'Own question saved',
        'anAnswer': 'An answer', 'add': 'Add', 'writeFirst': 'Write something before adding it.',
        'answerAdded': 'Answer added. That makes {n}.', 'answersN': 'You have {n} answers.', 'noAnswers': 'No answers yet. There is no right one: any answer is fine.',
        'answerRemoved': 'Answer removed.', 'removeN': 'Remove {n}',
        'changeA': 'Change A', 'changeB': 'Change B', 'changedA': 'A changed.', 'changedB': 'B changed.', 'otherPair': 'Another combination', 'otherPairDone': 'Another combination.',
        'inventName': 'Name of the invention', 'nameWritten': 'Name written', 'whatFor': 'What it is for', 'howWorks': 'How it works', 'written': 'Written',
        'improveIt': 'Improve it', 'improvePrompt': 'A question to improve it', 'needName': 'Give the invention a name before keeping it.', 'toSheet': 'Take it to the sheet',
        'addPiece': 'Add a piece', 'pieces': 'Pieces', 'pieceAdded': '{s} added in the centre.', 'pieceChosen': 'Piece {n} chosen.',
        'pieceMoved': 'Piece moved.', 'pieceTurned': 'Piece turned.', 'pieceResized': 'Size changed.', 'pieceRemoved': 'Piece removed.', 'pieceMirrored': 'Piece mirrored.',
        'removePiece': 'Remove the piece', 'noPieceChosen': 'Choose a piece in the Structure list to change it.', 'noPieces': 'Add at least one piece.', 'maxPieces': 'Twelve pieces maximum.',
        'shapeTitle': 'What do you see? Give it a title', 'titleWritten': 'Title written', 'otherChallenge': 'Another challenge', 'otherChallengeDone': 'Another challenge.',
        'turn': 'Rotation', 'size': 'Size', 'mirrorPiece': 'Mirror the piece',
        'rowN': 'row {n}', 'colN': 'column {n}', 'turnedN': 'turned {n}°', 'sizeN': 'size {n}%', 'mirrored': 'mirrored',
        'object': 'Object', 'anotherObject': 'Another object', 'otherObjectDone': 'Another object. The list starts again; you can undo it.',
        'otherDirection': 'Try another direction', 'directionPrompt': 'Another direction', 'aUse': 'A use', 'group': 'Group',
        'useAdded': 'Use added.', 'useStats': '{n} uses in {g} different groups.', 'noUses': 'No uses yet. Start with the obvious one, then move away from it.', 'useRemoved': 'Use removed.',
        'fluencyNote': 'Two things are counted: how many uses you write (fluency) and how many different groups they fall into (flexibility).',
        'scene': 'Scene', 'otherScene': 'Another scene', 'otherSceneDone': 'Another scene. Your texts from the previous one are kept.',
        'viewpoints': 'Viewpoints', 'hasText': 'has text', 'emptyText': 'empty', 'povWrite': 'Write from this viewpoint', 'povWritten': 'Text written',
        'compareViews': 'Compare viewpoints', 'noViewsYet': 'Write in a viewpoint to compare them here.',
        'scObject': 'Object', 'scSuggest': 'Another object', 'scThis': 'this object', 'scObjectSet': 'Object changed',
        'scObjects': 'a clothes peg|an umbrella|a chair|a water bottle|a backpack|a toothbrush|a spoon|an alarm clock|a bicycle|a shoebox|a pencil|a lamp|a sock|a bucket',
        'sc_S': 'Substitute', 'sc_C': 'Combine', 'sc_A': 'Adapt', 'sc_M': 'Modify', 'sc_P': 'Put to another use', 'sc_E': 'Eliminate', 'sc_R': 'Rearrange',
        'scQ_S': 'Which part or material of {o} could you swap for another?',
        'scQ_C': 'What else could you join {o} with?',
        'scQ_A': 'What idea from another object, animal or place could you borrow for {o}?',
        'scQ_M': 'What happens if {o} is much bigger, smaller, softer or a different shape?',
        'scQ_P': 'What else could {o} be used for? Somewhere else, or by someone else?',
        'scQ_E': 'What can you take away from {o} so that it still works?',
        'scQ_R': 'What happens if you change the order, turn it over or use it the other way round?',
        'scCount': 'Ideas written: {n}', 'scWritten': 'Idea written',
        'sprintProblem': 'The problem, in one sentence', 'problemWritten': 'Problem written',
        'timerStart': 'Start the time', 'timerPause': 'Pause', 'timerResume': 'Carry on',
        'timerStarted': 'Time running: {time} left.', 'timerPaused': 'Time paused: {time} left.',
        'timerDone': 'Time is up. You have written {n} ideas.', 'timerOneMinute': 'One minute left.',
        'timerPlusMinute': 'One more minute', 'timerExtended': 'One more minute: {time} left.', 'timerReset': 'Reset the time',
        'timerNote': 'The time never starts by itself. You can pause it, extend it or reset it whenever you like; the list of ideas stays.',
        'sprintSet': 'Time or target changed', 'sprintMinutes': 'Minutes', 'minutesUnit': 'min', 'sprintTarget': 'Ideas you are aiming for', 'ideasUnit': 'ideas',
        'anIdea': 'An idea', 'ideaAdded': 'Idea added. That makes {n}.', 'ideaRemoved': 'Idea removed.', 'sprintProgress': '{n} ideas of {m}.',
        'noIdeasYet': 'Write some ideas before keeping them.', 'toMatrix': 'Take them to Evaluate',
        'anOption': 'An option', 'optionAdded': 'Option added.', 'optionRemoved': 'Option removed.', 'removeOption': 'Remove option {n}',
        'importIdeas': 'Bring ideas in', 'matrixImported': '{n} options brought in from the board and the ideas.', 'matrixNothingNew': 'There are no new ideas to bring in.',
        'noOptions': 'Add options to compare them.', 'impactEffort': 'Impact and effort matrix',
        'impactEffortNote': 'Give each option how much it changes things (impact) and how much work it takes (effort), from 1 to 5. Nothing has to be dragged.',
        'impact': 'Impact', 'effort': 'Effort', 'quadrant': 'Where it falls',
        'quad_win': 'Do it now', 'quad_big': 'Big project', 'quad_maybe': 'If there is time', 'quad_no': 'Better not',
        'quadMapCaption': 'Options placed by impact (rows) and effort (columns)', 'impactN': 'Impact {n}', 'effortN': 'Effort {n}',
        'option': 'Option', 'remove': 'Remove', 'decisionMatrix': 'Weighted decision matrix',
        'aCriterion': 'A criterion', 'criterionAdded': 'Criterion added.', 'criterionRemoved': 'Criterion removed.', 'removeCriterion': 'Remove criterion {n}',
        'noCriteria': 'Add criteria (for example: cost, time, who it helps) and give them weights.',
        'weightOf': 'Weight of {c}', 'weightSet': 'Weight changed.', 'scoreSet': 'Score changed.', 'total': 'Total', 'best': 'the highest',
        'decisionNote': 'The total is the average of the scores, giving each criterion the weight you set. It is there to compare, not to decide for you.',
        'matrixSet': 'Matrix changed.', 'criteria': 'Criteria',
        'f_name': 'Name of the invention', 'f_who': 'Who it is for', 'f_problem': 'What problem it solves', 'f_how': 'How it is used, step by step',
        'f_test': 'How I check it works', 'f_better': 'What I would improve in version 2',
        'sizeLegend': 'Size of the finished invention', 'size_0': 'Length', 'size_1': 'Width', 'size_2': 'Height', 'sizeSet': 'Size changed', 'sheetWritten': 'Sheet changed',
        'partsTitle': 'Parts and materials', 'partsNote': 'One row per part. Price and weight are per unit. What you already have at home can cost €0.',
        'partsCap': 'Parts of the invention', 'thPart': 'Part or material', 'thQty': 'Quantity', 'thPrice': 'Price per unit (€)', 'thWeight': 'Weight per unit (g)',
        'ariaPart': 'Part {n}: name', 'ariaQty': 'Part {n}: quantity', 'ariaPrice': 'Part {n}: price per unit in euros', 'ariaWeight': 'Part {n}: weight per unit in grams',
        'delPart': 'Remove part {n}', 'partDeleted': 'Part removed', 'partAdded': 'Part added', 'partChanged': 'Part changed', 'addPart': 'Add part', 'noParts': 'There are no parts yet.',
        'totals': 'Total cost: €{c} · Total weight: {w} g · Named parts: {n} · Size: {s} cm', 'totalsShort': 'Totals',
        'checksTitle': 'How the sheet is going', 'chkField': '{f}: written', 'chkBudget': 'Cost: €{c} (up to €{m})',
        'chkSize': 'Size: {s} cm (up to {m} cm, in any orientation)', 'chkWeight': 'Weight: {w} g (up to {m} g)',
        'chkParts': 'Parts: {n} (at least {m})', 'chkScamper': 'At least {m} idea(s) for each SCAMPER letter',
        'allOk': 'The sheet is complete and meets the commission.', 'someOk': 'Here is how it is going. Fill in what is missing whenever you like.',
        'doneWord': 'done', 'pendingWord': 'to do',
        'briefWord': 'Commission', 'noBrief': 'No commission', 'noBriefText': 'Choose a challenge under Properties, or fill in the sheet with your own invention.',
        'anotherBrief': 'Another commission', 'newBrief': 'New commission', 'limits': 'Limits of the commission',
        'limBudget': 'Total cost: up to €{v}', 'limSize': 'Size of the finished invention: up to {v} cm', 'limWeight': 'Total weight: up to {v} g', 'limParts': 'Different parts: at least {v}',
        'randText': '{p}, for {who}, {where}.',
        'printSheet': 'Print the sheet', 'printing': 'Getting the sheet ready to print.',
        'sketchTitle': 'Sketch', 'sketchHelp': 'Draw with the mouse, your finger or a pen (if it senses pressure, the line changes thickness). With a keyboard: arrow keys move the point, Enter starts and finishes a line, Esc cancels it.',
        'sketchLabel': 'Sketch of the invention', 'sketchStart': 'Line started.', 'sketchEnd': 'Line finished.', 'sketchDrawing': 'drawing',
        'sketchDrawn': 'Sketch changed', 'sketchAt': 'Point at {x}, {y}', 'sketchCancelled': 'Line cancelled.',
        'sketchUndo': 'Remove the last line', 'sketchUndone': 'Last line removed.', 'sketchClear': 'Clear the sketch', 'sketchCleared': 'Sketch cleared.', 'sketchEmpty': 'The sketch is already empty.',
        'exportMd': 'Export text (Markdown)', 'exportBoardPng': 'Export board (PNG)', 'exportBoardSvg': 'Export board (SVG)',
        'sumBoard': '{n} notes and nodes, {l} joins. The first one says: {first}', 'sumBoardEmpty': 'The board is empty.',
        'sumShapes': '{n} pieces on the grid. Title: {title}', 'sumScamper': 'Object: {o}. Ideas written: {n}.',
        'sumSprint': '{n} ideas of {m}. Time left: {time}.', 'sumUses': '{n} uses in {g} different groups.',
        'sumMatrix': '{n} options and {c} criteria.', 'sumSheet': 'Invention: {name}. {p} parts, €{c}, {w} g. Checks met: {ok} of {n}.',
        'sumWhatIf': '{n} answers written.', 'sumStories': 'A story of {n} lines.', 'sumCombine': 'Combined invention: {name}.', 'sumPov': '{n} viewpoints written.',
        'toyObject': 'a toy you already have', 'teenProblem': 'Something at school that could be done better',
        'mapCentre': 'My idea', 'mapBranch1': 'Who it is for', 'mapBranch2': 'What problem it solves', 'mapBranch3': 'What it is made with',
        'decideA': 'Option A', 'decideB': 'Option B', 'decideC': 'Option C', 'crit1': 'Cost', 'crit2': 'How many people it helps',
    },
}

STRINGS = {'es': dict(_UI['es']), 'en': dict(_UI['en'])}

# Listas curadas y textos de las seis mesas, heredados del estudio anterior (ES/EN).
_BANKS_ES = {
    'fillNames': 'azul tinta|lila|rosa|turquesa|azul',
    'randPools': 'Llevar la compra sin que se rompan los huevos|Saber qué toca hacer mañana sin mirar el móvil|Secar las zapatillas mojadas más rápido|Encontrar el mando a distancia siempre|Que el perro beba agua cuando no hay nadie|Que una puerta no dé portazos con el viento|Tapar la luz de los aparatos por la noche|Colgar la bici en poco sitio|Llevar un paraguas sin tener que sujetarlo|Que la mochila pese menos en la espalda|Guardar las gafas donde no se pisen|Avisar de que el agua de la pasta va a salirse||una persona mayor|alguien que va en silla de ruedas|una familia con un bebé|un estudiante que vive en un piso compartido|alguien que trabaja por la noche|una persona que no oye bien|alguien a quien le molestan los ruidos fuertes|una persona con poca fuerza en las manos|alguien que viaja mucho||en una cocina pequeña|en la entrada de casa|en un balcón|en una clase|en una habitación compartida|en el coche|en un parque|en una tienda pequeña|en una biblioteca||Sin pilas ni enchufe|Que se pueda lavar|Que se monte en menos de dos minutos|Que se pueda usar con una sola mano|Sin herramientas para montarlo|Que no haga ruido|Todo reutilizado menos una pieza',
    'shapeNames': 'Círculo|Triángulo|Cuadrado|Arco|Gota',
    't1Char': 'una farera jubilada|un cartero que se pierde en su barrio|una niña que colecciona sonidos|un robot que hace pan|dos hermanos que no se hablan|una bibliotecaria de noche|un gigante muy tímido|una jardinera que habla con las piedras||una astrónoma aficionada|un satélite perdido|la estrella más tímida del cielo|un búho que cuenta estrellas||un pulpo relojero|una garza impaciente|un perro guía jubilado|una colonia de hormigas arquitectas||una conductora de tren nocturno|un barco de papel|un tranvía que ya no se usa|un piloto de globo',
    't1Obj': 'una llave que no abre nada|un paraguas con agujeros|una caja de música sin música|un mapa en blanco|un reloj que va hacia atrás|una carta sin remitente|una linterna gastada|un botón dorado||un telescopio de cartón|un mapa del cielo antiguo|una brújula|un farol||una pluma azul|una concha enorme|un collar sin nombre|una lupa||un billete de ida|una maleta que pesa demasiado|un silbato|una rueda de repuesto',
    't1Place': 'un mercado de noche|una estación sin trenes|el tejado de una biblioteca|un invernadero abandonado|una isla del tamaño de una mesa|un ascensor muy lento|un bosque de antenas|la cocina de un barco||un observatorio en la montaña|una azotea en una noche clara|una playa sin luces|un campo lejos de la ciudad||un arrecife|un nido en un campanario|una madriguera con muchas salidas|un estanque helado||un andén vacío|un puerto al amanecer|un aeropuerto de juguete|un túnel de montaña',
    't1Sit': 'se va la luz|llega una carta equivocada|todo el mundo se queda sin voz|empieza a nevar en verano|algo desaparece|alguien pide ayuda|se abre una puerta que nunca se abría|hay que elegir entre dos caminos||una estrella deja de verse|aparece una luz que nadie conoce|las nubes no se van en toda la noche|se ve un eclipse||los animales dejan de hacer ruido|llega una tormenta|una cría se separa de su grupo|el agua sube||el tren se detiene en mitad del campo|se pierde el equipaje|el viaje cambia de destino|se acaba el combustible',
    't2Hints': '¿Quién lo notaría primero?|¿Qué problemas aparecerían?|¿Qué cosas buenas pasarían?|¿Qué cambiaría en tu casa?',
    't2Q': '¿Y si los árboles pudieran hablar?|¿Y si una casa no tuviera puertas?|¿Y si la lluvia fuera de colores?|¿Y si los objetos recordaran quién los usó?|¿Y si el día durara 30 horas?|¿Y si las sombras se movieran solas?|¿Y si todo pesara la mitad?|¿Y si las ciudades flotaran?||¿Y si la Luna se viera de día y de noche siempre igual?|¿Y si pudiéramos oír las estrellas?|¿Y si el cielo nocturno fuera verde?|¿Y si hubiera dos soles?||¿Y si los peces pudieran caminar?|¿Y si los pájaros hablaran nuestro idioma?|¿Y si las hormigas fueran del tamaño de un perro?|¿Y si los animales votaran?||¿Y si los trenes pudieran ir por el agua?|¿Y si las bicicletas volaran un poco?|¿Y si no existieran las ruedas?|¿Y si los autobuses decidieran la ruta?',
    't3Improve': '¿Y si fuera más pequeño?|¿Qué le quitarías?|¿Con qué otra cosa lo juntarías?|¿Cómo lo usaría otra persona?|¿Y si funcionara al revés?|¿Qué material cambiarías?|¿Para qué más podría servir?',
    't3Obj': 'paraguas|mochila|lámpara|cuchara|zapato|almohada|reloj|maceta|bufanda|escalera||telescopio|farol|mapa del cielo|brújula||comedero|caseta|pluma|lupa||bicicleta|maleta|billete|vela de barco',
    't4Challenges': 'Convierte las piezas en un animal.|Haz un vehículo que no exista.|Construye una cara con tres piezas.|Dibuja un edificio raro.|Haz algo que viva en el cielo.',
    't5Dirs': '¿Y como instrumento de música?|¿Y si fuera gigante?|¿Y para un animal?|¿Y en el espacio?|¿Y para guardar algo?|¿Y para jugar con otra persona?',
    't5Groups': 'Herramienta|Juego|Arte|Ciencia|Casa|Otro',
    't5Obj': 'un clip|una cuchara de madera|una pinza de la ropa|un cartón de huevos|un calcetín desparejado|una goma elástica||una linterna|un trozo de papel de aluminio||una pluma|una piña de pino||un billete usado|una cámara de bicicleta',
    't6Q': '¿Qué ve? ¿Qué le importa? ¿Qué no sabe?',
    't6Scenes': 'Una parada de autobús un día de lluvia. Hay un banco, un paraguas olvidado y una conductora que espera la hora de salir. >> El paraguas olvidado|La conductora|Dentro de 100 años|Una hormiga en el banco||Una cocina a primera hora. Hay una tostadora, una ventana con vaho y alguien que busca las llaves. >> La tostadora|Las llaves|El gato de al lado|Dentro de un minuto|||Una azotea de noche. Hay un telescopio, una manta y una persona que intenta encontrar una constelación. >> El telescopio|Una estrella lejana|La vecina que mira por la ventana|Dentro de mil años|||Un estanque al amanecer. Hay una garza quieta, peces bajo el agua y un perro que se acerca. >> La garza|Un pez|El perro|El agua|||Un andén de tren a mediodía. Hay una maleta sola, un reloj grande y un tren que llega tarde. >> La maleta|El reloj|El tren|Una paloma del andén',
    'themeNames': 'Libre|Cielo nocturno|Animales|Transporte',
    'viewInfo_combine': 'Junta dos cosas y haz un invento. Ponle nombre.',
    'viewInfo_pov': 'La misma escena contada desde otro lugar: otra persona, un objeto, otro momento u otra escala.',
    'viewInfo_shapes': 'Formas sencillas. Añade, mueve y gira piezas hasta que sean otra cosa.',
    'viewInfo_stories': 'Tres piezas (cuatro en «Más piezas») y una historia. Cambia una pieza y mira qué pasa.',
    'viewInfo_uses': 'Un objeto de casa. ¿Para qué más podría servir?',
    'viewInfo_whatif': 'Una pregunta imposible. Escribe todas las respuestas que se te ocurran.',
    'view_combine': 'Inventa algo nuevo',
    'view_pov': 'Cambia el punto de vista',
    'view_shapes': 'Transforma la forma',
    'view_stories': 'Laboratorio de historias',
    'view_uses': 'Muchos usos',
    'view_whatif': '¿Y si…?',
}
_BANKS_EN = {
    'fillNames': 'ink blue|lilac|pink|teal|blue',
    'randPools': 'Carrying the shopping without breaking the eggs|Knowing what is on tomorrow without looking at your phone|Drying wet trainers faster|Always finding the remote control|Making sure the dog drinks when nobody is home|Stopping a door slamming in the wind|Covering the lights on devices at night|Hanging a bike up in a small space|Carrying an umbrella without holding it|Making a backpack feel lighter on your back|Keeping glasses where nobody steps on them|Warning that the pasta water is about to boil over||an older person|someone who uses a wheelchair|a family with a baby|a student living in a shared flat|someone who works nights|someone who is hard of hearing|someone bothered by loud noises|someone with little strength in their hands|someone who travels a lot||in a small kitchen|in the hallway at home|on a balcony|in a classroom|in a shared bedroom|in the car|in a park|in a small shop|in a library||No batteries or plug|It can be washed|It goes together in under two minutes|It can be used with one hand|No tools needed to build it|It makes no noise|All reused except one part',
    'shapeNames': 'Circle|Triangle|Square|Arch|Drop',
    't1Char': "a retired lighthouse keeper|a postman who gets lost in his own street|a girl who collects sounds|a robot that bakes bread|two siblings who don't talk|a night-shift librarian|a very shy giant|a gardener who talks to stones||an amateur astronomer|a lost satellite|the shyest star in the sky|an owl who counts stars||an octopus watchmaker|an impatient heron|a retired guide dog|a colony of architect ants||a night-train driver|a paper boat|a tram nobody uses any more|a balloon pilot",
    't1Obj': 'a key that opens nothing|an umbrella full of holes|a music box with no music|a blank map|a clock that runs backwards|a letter with no sender|a worn-out torch|a golden button||a cardboard telescope|an old sky map|a compass|a lantern||a blue feather|a huge shell|a collar with no name|a magnifying glass||a one-way ticket|a suitcase that is far too heavy|a whistle|a spare wheel',
    't1Place': "a night market|a station with no trains|the roof of a library|an abandoned greenhouse|an island the size of a table|a very slow lift|a forest of antennas|a ship's kitchen||a mountain observatory|a rooftop on a clear night|a beach with no lights|a field far from the city||a reef|a nest in a bell tower|a burrow with many exits|a frozen pond||an empty platform|a harbour at dawn|a toy airport|a mountain tunnel",
    't1Sit': 'the power goes out|the wrong letter arrives|everyone loses their voice|it starts snowing in summer|something disappears|someone asks for help|a door that never opened opens|there are two paths to choose from||a star can no longer be seen|a light nobody knows appears|the clouds stay all night|there is an eclipse||the animals go quiet|a storm arrives|a young animal gets separated from its group|the water rises||the train stops in the middle of the countryside|the luggage gets lost|the trip changes destination|the fuel runs out',
    't2Hints': 'Who would notice first?|What problems would appear?|What good things would happen?|What would change at home?',
    't2Q': "What if trees could talk?|What if a house had no doors?|What if rain came in colours?|What if objects remembered who used them?|What if a day lasted 30 hours?|What if shadows moved on their own?|What if everything weighed half as much?|What if cities floated?||What if the Moon looked the same day and night?|What if we could hear the stars?|What if the night sky were green?|What if there were two suns?||What if fish could walk?|What if birds spoke our language?|What if ants were the size of a dog?|What if animals could vote?||What if trains could travel on water?|What if bikes could fly a little?|What if wheels didn't exist?|What if buses chose their own route?",
    't3Improve': 'What if it were smaller?|What would you take away?|What else would you combine it with?|How would someone else use it?|What if it worked the other way round?|Which material would you change?|What else could it be used for?',
    't3Obj': 'umbrella|backpack|lamp|spoon|shoe|pillow|clock|flowerpot|scarf|ladder||telescope|lantern|sky map|compass||feeder|kennel|feather|magnifying glass||bicycle|suitcase|ticket|boat sail',
    't4Challenges': "Turn the pieces into an animal.|Make a vehicle that doesn't exist.|Build a face with three pieces.|Make a strange building.|Make something that lives in the sky.",
    't5Dirs': 'What about as a musical instrument?|What if it were giant?|What about for an animal?|What about in space?|What about for storing something?|What about for playing with someone else?',
    't5Groups': 'Tool|Game|Art|Science|Home|Other',
    't5Obj': 'a paper clip|a wooden spoon|a clothes peg|an egg carton|an odd sock|a rubber band||a torch|a piece of kitchen foil||a feather|a pine cone||a used ticket|a bicycle inner tube',
    't6Q': "What does it see? What matters to it? What doesn't it know?",
    't6Scenes': "A bus stop on a rainy day. There is a bench, a forgotten umbrella and a driver waiting for departure time. >> The forgotten umbrella|The driver|In 100 years|An ant on the bench||A kitchen early in the morning. There is a toaster, a steamed-up window and someone looking for their keys. >> The toaster|The keys|The neighbour's cat|One minute later|||A rooftop at night. There is a telescope, a blanket and a person trying to find a constellation. >> The telescope|A distant star|The neighbour looking out of the window|In a thousand years|||A pond at dawn. There is a still heron, fish under the water and a dog coming closer. >> The heron|A fish|The dog|The water|||A train platform at midday. There is a lone suitcase, a big clock and a train running late. >> The suitcase|The clock|The train|A pigeon on the platform",
    'themeNames': 'Free|Night sky|Animals|Transport',
    'viewInfo_combine': 'Put two things together and make an invention. Give it a name.',
    'viewInfo_pov': 'The same scene told from somewhere else: another person, an object, another time or another scale.',
    'viewInfo_shapes': 'Simple shapes. Add, move and turn pieces until they become something else.',
    'viewInfo_stories': 'Three pieces (four in "More pieces") and a story. Change one piece and see what happens.',
    'viewInfo_uses': 'An everyday object. What else could it be used for?',
    'viewInfo_whatif': 'An impossible question. Write every answer you can think of.',
    'view_combine': 'Invent something new',
    'view_pov': 'Change the point of view',
    'view_shapes': 'Transform the shape',
    'view_stories': 'Story lab',
    'view_uses': 'Many uses',
    'view_whatif': 'What if…?',
}

STRINGS['es'].update(_BANKS_ES)
STRINGS['en'].update(_BANKS_EN)

assert set(STRINGS['es']) == set(STRINGS['en']), set(STRINGS['es']) ^ set(STRINGS['en'])
assert set(PAGE['es']) == set(PAGE['en'])
