"""Estudio de juegos de mesa (R43): tablero, cartas, dados, reglas y pruebas de equilibrio. Textos ES/EN.

Fuentes citadas en la página:
- Selinker, Mike (ed.) (2011). The Kobold Guide to Board Game Design. Kirkland (Washington): Open Design.
- Grinstead, Charles M. y Snell, J. Laurie (1997). Introduction to Probability (2.ª edición revisada).
  Providence (Rhode Island): American Mathematical Society.
"""

ENGINE = 'juegosmesa'
SLUG = {'es': 'juegos-de-mesa', 'en': 'board-games'}
SCRIPTS = ['ig-suite-juegosmesa.js']
STYLES = ['ig-suite-juegosmesa.css']
LIBRARIES = 'ninguna biblioteca externa: tablero SVG, cartas, dados y simulación propios de Iris Green'
LIBRARIES_EN = 'no outside libraries: Iris Green’s own SVG board, cards, dice and simulation'

PAGE = {
    'es': {
        'title': 'Juegos de mesa',
        'description': 'Diseña un juego de mesa completo: tablero, cartas, dados, fichas y reglas. Pruébalo en el navegador, mira si está equilibrado e imprímelo a tamaño real.',
        'lede': 'Haz un juego y juégalo el mismo día. Dibuja el tablero, diseña las cartas, escribe las reglas, prueba una partida y comprueba con números si es justo.',
        'make': ['Una carrera de dados con casillas especiales', 'Un mazo de cartas equilibrado', 'Un juego de estrategia en hexágonos', 'Las reglas en HTML o Markdown', 'El juego entero listo para imprimir en hojas A4'],
        'steps': [
            'Elige el tipo de tablero (recorrido, rejilla o hexágonos) y pinta las casillas: salida, meta, avanza, retrocede, pierde turno o roba carta.',
            'Añade cartas en Estructura y dales título, texto, valor, icono y color. Las copias se imprimen repetidas.',
            'Escribe las reglas con la plantilla: objetivo, preparación, turno, final y variantes. El estudio cuenta las reglas y revisa el lenguaje claro.',
            'Pulsa «Jugar» para probar la partida: tira los dados, mueve las fichas, roba cartas y pasa el turno.',
            'Abre «Equilibrio» para ver la probabilidad de cada suma de dados y simular miles de partidas. Luego imprime el juego desde Archivo.',
        ],
        'sections': [
            {'h': 'Tres tipos de tablero', 'p': 'El recorrido es una fila de casillas numeradas en zigzag, de la salida a la meta: la ficha avanza lo que marcan los dados. La rejilla y los hexágonos son mapas por los que te mueves casilla a casilla, y los hexágonos tienen seis vecinos en vez de cuatro.\n\nCada tipo de casilla tiene color y dibujo propios, para reconocerla aunque no se vean bien los colores. Con el teclado, las flechas mueven el cursor, Intro pinta y los corchetes cambian de tipo de casilla.'},
            {'h': 'Cartas para imprimir', 'p': 'Las cartas miden 63 × 88 mm, la medida más usada en los juegos de mesa. La hoja de impresión pone nueve cartas en un A4 con marcas de corte en las esquinas. Al imprimir, elige «tamaño real» o «100 %» para que midan lo que deben.'},
            {'h': 'Probar y equilibrar', 'p': 'En el modo partida el azar solo ocurre cuando pulsas «Tirar dados», y el resultado se anuncia en palabras. Las fichas se mueven con el teclado o tocando la casilla.\n\nEn Equilibrio verás la probabilidad exacta de cada suma de los dados y una simulación de Montecarlo: el estudio juega miles de partidas rápidas y cuenta cuántos turnos duran y cuántas veces gana cada jugador. Así se ve si el primer jugador tiene ventaja y qué cambian las casillas especiales. La probabilidad exacta se calcula combinando las caras de cada dado (Grinstead y Snell, 1997).'},
            {'h': 'Reglas claras', 'p': 'La plantilla separa objetivo, preparación, turno, final y variantes, que es el orden habitual en los manuales de juego (Selinker, 2011). La revisión avisa de frases de más de veinte palabras y de pasos sin verbo, siguiendo la idea del lenguaje claro: frases cortas y decir quién hace qué. El contador te dice cuántas reglas llevas, para el reto de las cinco reglas.'},
            {'h': 'Fuentes', 'p': 'Selinker, Mike (ed.) (2011). The Kobold Guide to Board Game Design. Kirkland (Washington): Open Design.\n\nGrinstead, Charles M. y Snell, J. Laurie (1997). Introduction to Probability (2.ª edición revisada). Providence (Rhode Island): American Mathematical Society.'},
        ],
        'links': [('Todo el taller', '/es/taller/'), ('Mundos', '/es/taller/mundos/'), ('Videojuegos', '/es/taller/videojuegos/')],
    },
    'en': {
        'title': 'Board games',
        'description': 'Design a complete board game: board, cards, dice, pieces and rules. Try it in the browser, check whether it is balanced and print it at actual size.',
        'lede': 'Make a game and play it the same day. Draw the board, design the cards, write the rules, try a game and use numbers to check whether it is fair.',
        'make': ['A dice race with special squares', 'A balanced deck of cards', 'A strategy game on hexagons', 'The rules as HTML or Markdown', 'The whole game ready to print on A4 sheets'],
        'steps': [
            'Choose the kind of board (track, grid or hexagons) and paint the squares: start, finish, go forward, go back, miss a turn or draw a card.',
            'Add cards in Structure and give them a title, text, value, icon and colour. Copies are printed repeatedly.',
            'Write the rules with the template: objective, setup, turn, ending and variants. The studio counts the rules and checks them for plain language.',
            'Press “Play” to try a game: roll the dice, move the pieces, draw cards and pass the turn.',
            'Open “Balance” to see the probability of each dice total and to simulate thousands of games. Then print the game from File.',
        ],
        'sections': [
            {'h': 'Three kinds of board', 'p': 'The track is a row of numbered squares in a zigzag, from start to finish: your piece moves as far as the dice say. The grid and the hexagons are maps you move across square by square, and hexagons have six neighbours instead of four.\n\nEach kind of square has its own colour and drawing, so you can recognise it even if you cannot see the colours well. With the keyboard, the arrow keys move the cursor, Enter paints and the square brackets change the kind of square.'},
            {'h': 'Cards to print', 'p': 'Cards are 63 × 88 mm, the size most board games use. The print sheet puts nine cards on an A4 with cut marks at the corners. When printing, choose “actual size” or “100%” so they come out the right size.'},
            {'h': 'Playing and balancing', 'p': 'In play mode randomness only happens when you press “Roll dice”, and the result is announced in words. Pieces move with the keyboard or by tapping a square.\n\nIn Balance you see the exact probability of each dice total and a Monte Carlo simulation: the studio plays thousands of quick games and counts how many turns they take and how often each player wins. That shows whether the first player has an advantage and what the special squares change. The exact probability comes from combining the faces of each die (Grinstead and Snell, 1997).'},
            {'h': 'Clear rules', 'p': 'The template separates objective, setup, turn, ending and variants, the usual order in game rulebooks (Selinker, 2011). The check warns about sentences longer than twenty words and steps with no verb, following the plain-language idea: short sentences that say who does what. The counter tells you how many rules you have, for the five-rule challenge.'},
            {'h': 'Sources', 'p': 'Selinker, Mike (ed.) (2011). The Kobold Guide to Board Game Design. Kirkland (Washington): Open Design.\n\nGrinstead, Charles M. and Snell, J. Laurie (1997). Introduction to Probability (2nd revised edition). Providence (Rhode Island): American Mathematical Society.'},
        ],
        'links': [('The whole workshop', '/en/workshop/'), ('Worlds', '/en/workshop/worlds/'), ('Video game design', '/en/workshop/video-game-design/')],
    },
}

ICONS_ES = {'star': 'estrella', 'moon': 'luna', 'sun': 'sol', 'leaf': 'hoja', 'drop': 'gota', 'flame': 'llama', 'peak': 'montaña',
            'eye': 'ojo', 'key': 'llave', 'shield': 'escudo', 'clock': 'reloj', 'bolt': 'rayo', 'anchor': 'ancla', 'seed': 'semilla'}
ICONS_EN = {'star': 'star', 'moon': 'moon', 'sun': 'sun', 'leaf': 'leaf', 'drop': 'drop', 'flame': 'flame', 'peak': 'mountain',
            'eye': 'eye', 'key': 'key', 'shield': 'shield', 'clock': 'clock', 'bolt': 'lightning', 'anchor': 'anchor', 'seed': 'seed'}
COLOURS_ES = ['azul', 'verde', 'granate', 'violeta', 'marrón', 'turquesa', 'gris azulado', 'ocre']
COLOURS_EN = ['blue', 'green', 'maroon', 'violet', 'brown', 'teal', 'blue grey', 'ochre']

STRINGS = {
    'es': {
        'canvasLabel': 'Tablero del juego',
        'canvasHelp': 'En el tablero, las flechas mueven el cursor una casilla e Intro usa la herramienta: con Pintar cambia el tipo de casilla, con Ficha coloca o elige una ficha y con Elegir abre sus propiedades. [ y ] cambian el tipo de casilla que pintas. Con una ficha elegida, las flechas la mueven. En el modo partida: R tira los dados, C roba carta, N pasa el turno, las flechas llevan el cursor, Intro mueve la ficha a esa casilla y Esc sale.',
        'kGameCursor': 'En el tablero: flechas para el cursor; Intro para usar la herramienta; [ y ] cambian el tipo de casilla',
        'kGamePlay': 'En la partida: R tira los dados, C roba carta, N pasa el turno, Esc sale',
        'kGameViews': 'En Cartas: flechas para pasar de una carta a otra',
        'stRace': 'Carrera con dados y 5 reglas', 'stRaceD': 'Recorrido de 40 casillas con avanza, retrocede, pierde turno y roba carta.',
        'stCards': 'Juego de cartas equilibrado', 'stCardsD': 'Mazo de 14 cartas con cinco valores y una zona de juego en rejilla.',
        'stHex': 'Estrategia en hexágonos', 'stHexD': 'Tablero de hexágonos con obstáculos, dos dados y cartas de acción.',
        'stTwo': 'Juego para 2 con 5 reglas', 'stTwoD': 'Un recorrido corto, dos fichas, un dado y cinco reglas escritas.',
        'newGameName': 'Juego sin nombre',
        'toolSelect': 'Elegir', 'toolPaint': 'Pintar', 'toolPiece': 'Ficha', 'toolPan': 'Mover la vista',
        'cellTypeLabel': 'Tipo de casilla', 'viewLabel': 'Vista', 'playBtn': 'Jugar',
        'view_board': 'Tablero', 'view_cards': 'Cartas', 'view_rules': 'Reglas', 'view_balance': 'Equilibrio',
        'viewNow': 'Vista: {v}', 'viewCmd': 'Ver {v}',
        'type_normal': 'Normal', 'type_start': 'Salida', 'type_goal': 'Meta', 'type_advance': 'Avanza', 'type_back': 'Retrocede',
        'type_skip': 'Pierde turno', 'type_card': 'Roba carta', 'type_blocked': 'Bloqueada',
        'bk_track': 'Recorrido', 'bk_grid': 'Rejilla', 'bk_hex': 'Hexágonos',
        'kind_game': 'Juego', 'kind_card': 'Carta', 'kind_die': 'Dado', 'kind_piece': 'Ficha', 'kind_rules': 'Reglas', 'kind_cell': 'Casilla',
        'rs_objective': 'Objetivo', 'rs_setup': 'Preparación', 'rs_turn': 'Tu turno', 'rs_end': 'Final de la partida', 'rs_variants': 'Variantes',
        'gameTitle': 'Juego', 'gameName': 'Nombre del juego', 'playersLabel': 'Número de jugadores', 'challenges': 'Retos', 'done': 'Hecho', 'pending': 'Pendiente',
        'ch1': 'Juego para 2 con 5 reglas', 'ch1D': 'Jugadores: {players}. Reglas escritas: {n} de 5.',
        'ch2': 'Juego equilibrado con cartas',
        'g2Cards': 'Cartas en el mazo: {n} de 10', 'g2Values': 'Valores distintos: {n} de 3', 'g2Sim': 'Simulación hecha',
        'g2Lead': 'Ventaja del primer jugador menor de 10 puntos (ahora: {n})',
        'ch3': 'Reglas claras y completas', 'ch3D': 'Avisos de lenguaje claro: {n}.', 'ch3Ok': 'Sin avisos: frases cortas y pasos con verbo.',
        'boardTitle': 'Tablero', 'boardKind': 'Tipo de tablero', 'colsLabel': 'Columnas', 'rowsLabel': 'Filas',
        'boardInfo': '{kind} de {n} casillas.', 'numbering': 'Numerar las casillas', 'boardResized': 'Tablero de {n} casillas',
        'kindChanged': 'Tablero cambiado a {kind}', 'paintTitle': 'Casilla para pintar', 'stepsLabel': 'Casillas que mueve',
        'typeNow': 'Casilla: {t}', 'painted': 'Pintado: {t}', 'alreadyThat': 'Esa casilla ya es así.',
        'cellAt': 'Casilla {n}: {t}', 'cellChanged': 'Casilla {n}: {t}', 'stepsN': 'mueve {n}',
        'cellHelp': 'Cambia el tipo aquí o pinta varias casillas seguidas con la herramienta Pintar.',
        'piecesHere': 'Fichas aquí: {list}.', 'noPiecesHere': 'No hay fichas en esta casilla.',
        'cardsTitle': 'Cartas', 'addCard': 'Añadir carta', 'dupCard': 'Duplicar', 'cardDefault': 'Carta {n}',
        'cardTitle': 'Título', 'cardText': 'Texto de la carta', 'cardValue': 'Valor', 'cardCopies': 'Copias', 'cardIcon': 'Icono', 'cardColour': 'Color',
        'cardLabel': 'Carta {title}, valor {v}', 'copiesN': '{n} copias', 'deckEmpty': 'Todavía no hay cartas en el mazo.',
        'cardsNote': 'Al imprimir, las cartas miden 63 × 88 mm y salen nueve por hoja A4 con marcas de corte.',
        'printCards': 'Imprimir las cartas', 'printBoard': 'Imprimir el tablero', 'printRules': 'Imprimir las reglas',
        'diceTitle': 'Dados', 'addDie': 'Añadir dado', 'dieFacesLabel': 'Caras del dado', 'dieCustomOpt': 'Caras propias',
        'dieCustom': 'dado de {n} caras propias', 'dieCustomFaces': 'Caras (separadas por comas)', 'faceBlank': 'nada',
        'dieCustomHelp': 'Escribe lo que pone cada cara. Si son números, cuentan para la suma; si son palabras, valen cero.',
        'dieNeedFaces': 'Escribe al menos dos caras.', 'facesN': '{n} caras', 'maxDice': 'Como mucho seis dados.', 'minDice': 'Tiene que quedar un dado.',
        'diceLede': 'Con {dice} la suma va de {min} a {max} y la media es {mean}.',
        'piecesTitle': 'Fichas', 'addPiece': 'Añadir ficha', 'pieceColour': 'Color de la ficha', 'cellLabel': 'Casilla', 'cellN': 'casilla {n}',
        'pieceMoveHelp': 'Con la ficha elegida, las flechas la mueven por el tablero. También puedes escribir el número de casilla.',
        'maxPieces': 'Como mucho seis fichas.', 'playerN': 'Jugador {n}',
        'rulesN': '{n} reglas', 'rulesOf': 'Reglas de {name}', 'rulesMeta': 'Para {players} jugadores · {n} reglas escritas.',
        'ruleN': '{sec}, regla {n}', 'removeRule': 'Quitar la regla {n} de {sec}', 'addRule': 'Añadir regla', 'rulesChanged': 'Reglas cambiadas',
        'editRules': 'Escribir las reglas', 'seeRules': 'Ver las reglas',
        'revTitle': 'Revisión de lenguaje claro', 'revOk': 'Las reglas se entienden bien: frases cortas y pasos con verbo.',
        'revBad': 'Avisos: {n}', 'revLong': '{sec}: frase de {n} palabras. Pártela en dos. «{s}…»',
        'revNoVerb': '{sec}: este paso no dice qué hay que hacer. Empieza por un verbo. «{s}…»',
        'revNoObjective': 'Escribe el objetivo: en una frase, cómo se gana.', 'revNoTurn': 'Escribe al menos un paso de «Tu turno».',
        'revNote': 'La revisión es orientativa: avisa de frases de más de veinte palabras y de pasos sin verbo (lenguaje claro, ISO 24495-1).',
        'playTitle': 'Partida', 'playOn': 'Empieza la partida. Turno de {name}. Pulsa Tirar dados.', 'playOff': 'Fin de la partida. Vuelves a editar el juego.',
        'exitPlay': 'Salir de la partida', 'rollBtn': 'Tirar dados', 'drawBtn': 'Robar carta', 'shuffleBtn': 'Barajar', 'nextBtn': 'Turno siguiente',
        'turnOf': 'Turno de {name}.', 'rolled': 'Has sacado {r}.', 'rollPrompt': 'Pulsa «Tirar dados» para empezar el turno.',
        'rollAnnounce': 'Dados: {r}. Total: {total}.', 'stepsLeft': 'Te quedan {n} pasos.',
        'moveAnnounce': '{name} sale {r} y va de la casilla {from} a la {to}.',
        'moveHelp': 'Lleva el cursor con las flechas y pulsa Intro, o toca una casilla marcada.',
        'trackHelp': 'En el recorrido, la ficha avanza sola lo que marcan los dados.', 'trackAuto': 'En el recorrido la ficha avanza sola al tirar los dados.',
        'rollFirst': 'Tira los dados antes de mover.', 'tooFar': 'Esa casilla está demasiado lejos para los pasos que te quedan.',
        'pieceAt': '{name} en la casilla {n}: {t}.', 'cardDrawn': 'carta: {title}',
        'sqAdvance': 'Avanza {n} casillas más.', 'sqBack': 'Retrocede {n} casillas.', 'sqSkip': 'Pierdes el turno siguiente.', 'sqCard': 'Robas una carta.',
        'winAnnounce': '¡{name} llega a la meta y gana!', 'skipTurn': '{name} pierde este turno.',
        'drewCard': 'Carta robada: {title}, valor {v}. {text}', 'drewCardShort': 'Carta robada: {title}, valor {v}.',
        'deckShuffled': 'Mazo barajado: {n} cartas.', 'deckReshuffled': 'Se acabó el mazo: se baraja otra vez.', 'deckEmptyPlay': 'No hay cartas en el mazo.',
        'playNote': 'El azar solo ocurre cuando pulsas Tirar dados o Robar carta. Nada se mueve solo.',
        'simTitle': 'Simulación del recorrido', 'simLede': 'El estudio juega muchas partidas rápidas con tus dados y tus casillas, y cuenta lo que pasa. Todas las fichas salen de la casilla de salida y corren hacia la meta.',
        'simRun': 'Simular {n} partidas', 'simRunFast': 'Probar con {n}', 'simNone': 'Todavía no has simulado ninguna partida.',
        'simNeedGoal': 'Para simular hace falta una casilla de salida y una de meta unidas por un camino.',
        'simDone': 'Simuladas {n} partidas: {turns} turnos de media y {lead} puntos de ventaja para el primer jugador.',
        'simBalanced': 'El juego parece equilibrado. ', 'simUnbalanced': 'El primer jugador tiene ventaja. ',
        'simSummary': 'Duración media: {turns} turnos por jugador. Ventaja del primer jugador: {lead} puntos. La partida más corta duró {short} turnos y la más larga, {long}.',
        'simCap': 'Resultado de {n} partidas simuladas, con y sin casillas especiales',
        'colWho': 'Quién', 'colWinsWith': 'Victorias con especiales', 'colWinsNo': 'Victorias sin especiales',
        'rowTurns': 'Turnos por jugador (media)', 'rowSpecials': 'Casillas especiales usadas por partida',
        'simNote': 'La simulación juega sola y solo cuando la pides. Cada vez sale un poco distinta, porque los dados son al azar.',
        'distCap': 'Probabilidad de cada suma con {dice}', 'sumWord': 'Suma', 'probWord': 'Probabilidad', 'outOfWord': 'Una vez de cada',
        'oneIn': '{n}', 'chartAlt': 'Gráfico de barras con la probabilidad de cada suma, de {min} a {max}. Los mismos datos están en la tabla siguiente.',
        'deckTitle': 'Mazo', 'deckLede': '{total} cartas de {kinds} tipos. Valores: de {min} a {max}, media {mean} y mediana {median}.',
        'deckCap': 'Cuántas cartas hay de cada valor', 'deckCapList': 'Lista de cartas del mazo', 'colValue': 'Valor', 'colCards': 'Cartas',
        'componentsTitle': 'Qué hace falta', 'compBoard': 'Un tablero de {kind} con {n} casillas.', 'compCards': '{n} cartas.',
        'compDice': 'Dados: {dice}.', 'compPieces': '{n} fichas.',
        'name': 'Nombre', 'deleteBtn': 'Borrar', 'noneYet': 'Todavía no hay nada aquí.', 'noneWord': 'ninguna',
        'added': '{kind} añadido: {name}', 'deletedItem': 'Borrado: {name}', 'selectedItem': '{kind}: {name}',
        'renamed': 'Nombre cambiado', 'changedWord': 'Cambiado', 'movedWord': 'Movido', 'deselected': 'Nada elegido.',
        'printGame': 'Imprimir el juego entero (tablero, cartas y reglas)', 'printing': 'Preparadas {n} hojas para imprimir.',
        'exportPng': 'Exportar tablero (PNG)', 'exportRulesHtml': 'Exportar reglas (HTML)', 'exportRulesMd': 'Exportar reglas (Markdown)',
        'exportError': 'No se ha podido exportar. Inténtalo de nuevo.',
        'boardOf': 'Tablero de {name}', 'boardSheet': '{name} · tablero, hoja {n} de {total}', 'cardSheet': '{name} · cartas, hoja {n} de {total}',
        'filesNote': 'Este archivo no tiene programas ni enlaces externos.',
        'summary': '{name}: tablero de {kind} de {w} × {h} ({n} casillas). Casillas especiales: {specials}. Cartas: {cards}. Dados: {dice}. Fichas: {pieces}. Reglas: {rules}.',
        'cursorSum': 'Cursor en la casilla {n} ({t}).',
        'exRaceName': 'La carrera del río', 'exTwoName': 'Duelo de seis casillas',
        'exRaceObj': 'Gana quien llega antes a la meta con su ficha.',
        'exRaceSetup1': 'Poned las dos fichas en la casilla de salida.', 'exRaceSetup2': 'Barajad las cartas y dejadlas boca abajo al lado del tablero.',
        'exRaceTurn1': 'Tira el dado y avanza esas casillas.', 'exRaceTurn2': 'Haz lo que diga la casilla donde caes.', 'exRaceTurn3': 'Pasa el turno a la otra persona.',
        'exRaceEnd1': 'La partida acaba cuando una ficha llega a la meta.', 'exRaceVar1': 'Para una partida más corta, empezad en la casilla diez.',
        'exCardWind': 'Viento a favor', 'exCardWindT': 'Avanza tres casillas.', 'exCardRest': 'Alto en el camino', 'exCardRestT': 'Quédate donde estás y pasa el turno.',
        'exCardShort': 'Atajo', 'exCardShortT': 'Avanza dos casillas.',
        'exDeckName': 'Cinco valores',
        'exDeckObj': 'Gana quien llega antes a la meta jugando cartas de valor alto.',
        'exDeckSetup1': 'Repartid tres cartas a cada jugador.', 'exDeckSetup2': 'Poned las fichas en la salida.',
        'exDeckTurn1': 'Juega una carta y avanza tantas casillas como su valor.', 'exDeckTurn2': 'Roba una carta nueva del mazo.', 'exDeckTurn3': 'Pasa el turno.',
        'exDeckEnd1': 'Gana quien llega antes a la meta.', 'exDeckVar1': 'Variante: con dos cartas del mismo valor, avanza el doble.',
        'exC1': 'Paso corto', 'exC1T': 'Avanza una casilla.', 'exC2': 'Paso doble', 'exC2T': 'Avanza dos casillas.',
        'exC3': 'Carrera', 'exC3T': 'Avanza tres casillas.', 'exC4': 'Salto', 'exC4T': 'Avanza cuatro casillas.',
        'exC5': 'Impulso', 'exC5T': 'Avanza cinco casillas, pero pierdes el turno siguiente.',
        'exHexName': 'El paso de la montaña', 'exHexObj': 'Gana quien llega antes a la casilla de meta del otro lado.',
        'exHexSetup1': 'Cada jugador coloca su ficha en una esquina del tablero.', 'exHexSetup2': 'Barajad las cartas de acción.',
        'exHexTurn1': 'Tira los dos dados y suma: esos son tus pasos.', 'exHexTurn2': 'Mueve tu ficha de hexágono en hexágono, sin pasar por las casillas bloqueadas.',
        'exHexTurn3': 'Si acabas en una casilla de carta, roba una.',
        'exHexEnd1': 'La partida acaba cuando una ficha llega a la meta contraria.',
        'exHexVar1': 'Variante: usa un solo dado para que la partida dure más.', 'exHexVar2': 'Variante: quien saca doble repite turno.',
        'exH1': 'Refugio', 'exH1T': 'Este turno no te afectan las casillas de retroceso.', 'exH2': 'Atajo de montaña', 'exH2T': 'Avanza dos hexágonos más.',
        'exH3': 'Llave del paso', 'exH3T': 'Cruza una casilla bloqueada.',
    },
    'en': {
        'canvasLabel': 'Game board',
        'canvasHelp': 'On the board, the arrow keys move the cursor one square and Enter uses the tool: Paint changes the kind of square, Piece places or selects a piece, and Select opens its properties. [ and ] change the kind of square you paint. With a piece selected, the arrow keys move it. In play mode: R rolls the dice, C draws a card, N passes the turn, the arrow keys move the cursor, Enter moves the piece to that square and Esc leaves.',
        'kGameCursor': 'On the board: arrow keys for the cursor; Enter to use the tool; [ and ] change the kind of square',
        'kGamePlay': 'In play mode: R rolls the dice, C draws a card, N passes the turn, Esc leaves',
        'kGameViews': 'In Cards: arrow keys to go from one card to the next',
        'stRace': 'Dice race with five rules', 'stRaceD': 'A 40-square track with go forward, go back, miss a turn and draw a card.',
        'stCards': 'Balanced card game', 'stCardsD': 'A 14-card deck with five values and a grid play area.',
        'stHex': 'Strategy on hexagons', 'stHexD': 'A hexagon board with obstacles, two dice and action cards.',
        'stTwo': 'Two-player game with five rules', 'stTwoD': 'A short track, two pieces, one die and five written rules.',
        'newGameName': 'Untitled game',
        'toolSelect': 'Select', 'toolPaint': 'Paint', 'toolPiece': 'Piece', 'toolPan': 'Move the view',
        'cellTypeLabel': 'Kind of square', 'viewLabel': 'View', 'playBtn': 'Play',
        'view_board': 'Board', 'view_cards': 'Cards', 'view_rules': 'Rules', 'view_balance': 'Balance',
        'viewNow': 'View: {v}', 'viewCmd': 'Show {v}',
        'type_normal': 'Plain', 'type_start': 'Start', 'type_goal': 'Finish', 'type_advance': 'Go forward', 'type_back': 'Go back',
        'type_skip': 'Miss a turn', 'type_card': 'Draw a card', 'type_blocked': 'Blocked',
        'bk_track': 'Track', 'bk_grid': 'Grid', 'bk_hex': 'Hexagons',
        'kind_game': 'Game', 'kind_card': 'Card', 'kind_die': 'Die', 'kind_piece': 'Piece', 'kind_rules': 'Rules', 'kind_cell': 'Square',
        'rs_objective': 'Objective', 'rs_setup': 'Setup', 'rs_turn': 'Your turn', 'rs_end': 'End of the game', 'rs_variants': 'Variants',
        'gameTitle': 'Game', 'gameName': 'Name of the game', 'playersLabel': 'Number of players', 'challenges': 'Challenges', 'done': 'Done', 'pending': 'To do',
        'ch1': 'Two-player game with five rules', 'ch1D': 'Players: {players}. Rules written: {n} of 5.',
        'ch2': 'Balanced card game',
        'g2Cards': 'Cards in the deck: {n} of 10', 'g2Values': 'Different values: {n} of 3', 'g2Sim': 'Simulation done',
        'g2Lead': 'First-player advantage under 10 points (now: {n})',
        'ch3': 'Clear, complete rules', 'ch3D': 'Plain-language warnings: {n}.', 'ch3Ok': 'No warnings: short sentences and steps with a verb.',
        'boardTitle': 'Board', 'boardKind': 'Kind of board', 'colsLabel': 'Columns', 'rowsLabel': 'Rows',
        'boardInfo': '{kind} with {n} squares.', 'numbering': 'Number the squares', 'boardResized': 'Board with {n} squares',
        'kindChanged': 'Board changed to {kind}', 'paintTitle': 'Square to paint', 'stepsLabel': 'Squares it moves',
        'typeNow': 'Square: {t}', 'painted': 'Painted: {t}', 'alreadyThat': 'That square is already like that.',
        'cellAt': 'Square {n}: {t}', 'cellChanged': 'Square {n}: {t}', 'stepsN': 'moves {n}',
        'cellHelp': 'Change the kind here, or paint several squares in a row with the Paint tool.',
        'piecesHere': 'Pieces here: {list}.', 'noPiecesHere': 'There are no pieces on this square.',
        'cardsTitle': 'Cards', 'addCard': 'Add card', 'dupCard': 'Duplicate', 'cardDefault': 'Card {n}',
        'cardTitle': 'Title', 'cardText': 'Card text', 'cardValue': 'Value', 'cardCopies': 'Copies', 'cardIcon': 'Icon', 'cardColour': 'Colour',
        'cardLabel': 'Card {title}, value {v}', 'copiesN': '{n} copies', 'deckEmpty': 'There are no cards in the deck yet.',
        'cardsNote': 'When printed, cards are 63 × 88 mm and come nine to an A4 sheet with cut marks.',
        'printCards': 'Print the cards', 'printBoard': 'Print the board', 'printRules': 'Print the rules',
        'diceTitle': 'Dice', 'addDie': 'Add die', 'dieFacesLabel': 'Faces of the die', 'dieCustomOpt': 'Faces of your own',
        'dieCustom': 'die with {n} faces of your own', 'dieCustomFaces': 'Faces (separated by commas)', 'faceBlank': 'nothing',
        'dieCustomHelp': 'Write what each face says. Numbers count towards the total; words count as zero.',
        'dieNeedFaces': 'Write at least two faces.', 'facesN': '{n} faces', 'maxDice': 'Six dice at most.', 'minDice': 'One die must remain.',
        'diceLede': 'With {dice} the total goes from {min} to {max} and the average is {mean}.',
        'piecesTitle': 'Pieces', 'addPiece': 'Add piece', 'pieceColour': 'Colour of the piece', 'cellLabel': 'Square', 'cellN': 'square {n}',
        'pieceMoveHelp': 'With the piece selected, the arrow keys move it around the board. You can also type the square number.',
        'maxPieces': 'Six pieces at most.', 'playerN': 'Player {n}',
        'rulesN': '{n} rules', 'rulesOf': 'Rules of {name}', 'rulesMeta': 'For {players} players · {n} rules written.',
        'ruleN': '{sec}, rule {n}', 'removeRule': 'Remove rule {n} of {sec}', 'addRule': 'Add rule', 'rulesChanged': 'Rules changed',
        'editRules': 'Write the rules', 'seeRules': 'Read the rules',
        'revTitle': 'Plain-language check', 'revOk': 'The rules read well: short sentences and steps with a verb.',
        'revBad': 'Warnings: {n}', 'revLong': '{sec}: a sentence of {n} words. Split it in two. “{s}…”',
        'revNoVerb': '{sec}: this step does not say what to do. Start with a verb. “{s}…”',
        'revNoObjective': 'Write the objective: in one sentence, how you win.', 'revNoTurn': 'Write at least one step for “Your turn”.',
        'revNote': 'The check is a guide: it warns about sentences longer than twenty words and steps with no verb (plain language, ISO 24495-1).',
        'playTitle': 'Play mode', 'playOn': 'The game starts. It is {name}’s turn. Press Roll dice.', 'playOff': 'Game over. You are editing the game again.',
        'exitPlay': 'Leave play mode', 'rollBtn': 'Roll dice', 'drawBtn': 'Draw a card', 'shuffleBtn': 'Shuffle', 'nextBtn': 'Next turn',
        'turnOf': '{name}’s turn.', 'rolled': 'You rolled {r}.', 'rollPrompt': 'Press “Roll dice” to start the turn.',
        'rollAnnounce': 'Dice: {r}. Total: {total}.', 'stepsLeft': 'You have {n} steps left.',
        'moveAnnounce': '{name} rolls {r} and goes from square {from} to square {to}.',
        'moveHelp': 'Take the cursor there with the arrow keys and press Enter, or tap a marked square.',
        'trackHelp': 'On a track, the piece moves by itself as far as the dice say.', 'trackAuto': 'On a track the piece moves by itself when you roll.',
        'rollFirst': 'Roll the dice before moving.', 'tooFar': 'That square is too far for the steps you have left.',
        'pieceAt': '{name} on square {n}: {t}.', 'cardDrawn': 'card: {title}',
        'sqAdvance': 'Go forward {n} more squares.', 'sqBack': 'Go back {n} squares.', 'sqSkip': 'You miss your next turn.', 'sqCard': 'You draw a card.',
        'winAnnounce': '{name} reaches the finish and wins!', 'skipTurn': '{name} misses this turn.',
        'drewCard': 'Card drawn: {title}, value {v}. {text}', 'drewCardShort': 'Card drawn: {title}, value {v}.',
        'deckShuffled': 'Deck shuffled: {n} cards.', 'deckReshuffled': 'The deck ran out: it is shuffled again.', 'deckEmptyPlay': 'There are no cards in the deck.',
        'playNote': 'Randomness only happens when you press Roll dice or Draw a card. Nothing moves by itself.',
        'simTitle': 'Track simulation', 'simLede': 'The studio plays many quick games with your dice and your squares, and counts what happens. Every piece starts on the start square and races to the finish.',
        'simRun': 'Simulate {n} games', 'simRunFast': 'Try {n}', 'simNone': 'You have not simulated any games yet.',
        'simNeedGoal': 'To simulate you need a start square and a finish square joined by a path.',
        'simDone': '{n} games simulated: {turns} turns on average and {lead} points of advantage for the first player.',
        'simBalanced': 'The game looks balanced. ', 'simUnbalanced': 'The first player has an advantage. ',
        'simSummary': 'Average length: {turns} turns per player. First-player advantage: {lead} points. The shortest game took {short} turns and the longest {long}.',
        'simCap': 'Result of {n} simulated games, with and without special squares',
        'colWho': 'Who', 'colWinsWith': 'Wins with special squares', 'colWinsNo': 'Wins without special squares',
        'rowTurns': 'Turns per player (average)', 'rowSpecials': 'Special squares used per game',
        'simNote': 'The simulation runs only when you ask for it. Each run comes out a little different, because dice are random.',
        'distCap': 'Probability of each total with {dice}', 'sumWord': 'Total', 'probWord': 'Probability', 'outOfWord': 'Once in every',
        'oneIn': '{n}', 'chartAlt': 'Bar chart of the probability of each total, from {min} to {max}. The same data is in the table below.',
        'deckTitle': 'Deck', 'deckLede': '{total} cards of {kinds} kinds. Values: from {min} to {max}, mean {mean} and median {median}.',
        'deckCap': 'How many cards there are of each value', 'deckCapList': 'List of cards in the deck', 'colValue': 'Value', 'colCards': 'Cards',
        'componentsTitle': 'What you need', 'compBoard': 'A {kind} board with {n} squares.', 'compCards': '{n} cards.',
        'compDice': 'Dice: {dice}.', 'compPieces': '{n} pieces.',
        'name': 'Name', 'deleteBtn': 'Delete', 'noneYet': 'There is nothing here yet.', 'noneWord': 'none',
        'added': '{kind} added: {name}', 'deletedItem': 'Deleted: {name}', 'selectedItem': '{kind}: {name}',
        'renamed': 'Name changed', 'changedWord': 'Changed', 'movedWord': 'Moved', 'deselected': 'Nothing selected.',
        'printGame': 'Print the whole game (board, cards and rules)', 'printing': '{n} sheets ready to print.',
        'exportPng': 'Export board (PNG)', 'exportRulesHtml': 'Export rules (HTML)', 'exportRulesMd': 'Export rules (Markdown)',
        'exportError': 'Could not export. Please try again.',
        'boardOf': 'Board of {name}', 'boardSheet': '{name} · board, sheet {n} of {total}', 'cardSheet': '{name} · cards, sheet {n} of {total}',
        'filesNote': 'This file has no programs and no outside links.',
        'summary': '{name}: {kind} board of {w} × {h} ({n} squares). Special squares: {specials}. Cards: {cards}. Dice: {dice}. Pieces: {pieces}. Rules: {rules}.',
        'cursorSum': 'Cursor on square {n} ({t}).',
        'exRaceName': 'The river race', 'exTwoName': 'Six-square duel',
        'exRaceObj': 'The first piece to reach the finish wins.',
        'exRaceSetup1': 'Put both pieces on the start square.', 'exRaceSetup2': 'Shuffle the cards and leave them face down beside the board.',
        'exRaceTurn1': 'Roll the die and move that many squares.', 'exRaceTurn2': 'Do what the square you land on says.', 'exRaceTurn3': 'Pass the turn to the other player.',
        'exRaceEnd1': 'The game ends when a piece reaches the finish.', 'exRaceVar1': 'For a shorter game, start on square ten.',
        'exCardWind': 'Following wind', 'exCardWindT': 'Go forward three squares.', 'exCardRest': 'A rest on the way', 'exCardRestT': 'Stay where you are and pass the turn.',
        'exCardShort': 'Short cut', 'exCardShortT': 'Go forward two squares.',
        'exDeckName': 'Five values',
        'exDeckObj': 'The first player to reach the finish by playing high cards wins.',
        'exDeckSetup1': 'Deal three cards to each player.', 'exDeckSetup2': 'Put the pieces on the start square.',
        'exDeckTurn1': 'Play a card and move as many squares as its value.', 'exDeckTurn2': 'Draw a new card from the deck.', 'exDeckTurn3': 'Pass the turn.',
        'exDeckEnd1': 'The first player to reach the finish wins.', 'exDeckVar1': 'Variant: if you play two cards of the same value, you move twice as far.',
        'exC1': 'Short step', 'exC1T': 'Go forward one square.', 'exC2': 'Double step', 'exC2T': 'Go forward two squares.',
        'exC3': 'Run', 'exC3T': 'Go forward three squares.', 'exC4': 'Leap', 'exC4T': 'Go forward four squares.',
        'exC5': 'Sprint', 'exC5T': 'Go forward five squares, but you miss your next turn.',
        'exHexName': 'The mountain pass', 'exHexObj': 'The first piece to reach the finish on the far side wins.',
        'exHexSetup1': 'Each player puts their piece in one corner of the board.', 'exHexSetup2': 'Shuffle the action cards.',
        'exHexTurn1': 'Roll both dice and add them up: those are your steps.', 'exHexTurn2': 'Move your piece from hexagon to hexagon, never through blocked squares.',
        'exHexTurn3': 'If you end on a card square, draw a card.',
        'exHexEnd1': 'The game ends when a piece reaches the opposite finish.',
        'exHexVar1': 'Variant: use only one die to make the game last longer.', 'exHexVar2': 'Variant: whoever rolls a double takes another turn.',
        'exH1': 'Shelter', 'exH1T': 'This turn, go-back squares do not affect you.', 'exH2': 'Mountain short cut', 'exH2T': 'Go forward two more hexagons.',
        'exH3': 'Key to the pass', 'exH3T': 'Cross one blocked square.',
    },
}
for _k, _v in ICONS_ES.items():
    STRINGS['es']['icon_' + _k] = _v
    STRINGS['en']['icon_' + _k] = ICONS_EN[_k]
for _i, _v in enumerate(COLOURS_ES):
    STRINGS['es']['colour_' + str(_i)] = _v
    STRINGS['en']['colour_' + str(_i)] = COLOURS_EN[_i]
assert set(STRINGS['es']) == set(STRINGS['en'])
assert set(PAGE['es']) == set(PAGE['en'])
