"""Estudio de lenguas inventadas (R43). Textos ES/EN.
Sustituye al estudio genérico r40 (kind 'conlang') y conserva sus retos: alfabeto de 20 signos,
100 palabras y texto traducido.
Fuentes verificadas: International Phonetic Association, «IPA Chart» (revisión de 2020, CC BY-SA 3.0);
Leipzig Glossing Rules (Comrie, Haspelmath y Bickel; Max Planck Institute for Evolutionary Anthropology
y Universidad de Leipzig, última revisión de 2015); Morris Swadesh, «Towards Greater Accuracy in
Lexicostatistic Dating», International Journal of American Linguistics 21 (1955), pp. 121-137;
Mark Rosenfelder, «The Language Construction Kit» (Yonagu Books, 2010)."""

ENGINE = 'lenguas'
SLUG = {'es': 'lenguas-inventadas', 'en': 'invented-languages'}
SCRIPTS = ['ig-suite-lenguas-datos.js', 'ig-suite-lenguas.js']
STYLES = ['ig-suite-lenguas.css']
LIBRARIES = 'código propio de Iris Green, sin bibliotecas externas; letras Atkinson Hyperlegible y JetBrains Mono (SIL OFL)'
LIBRARIES_EN = 'Iris Green’s own code, with no outside libraries; typefaces Atkinson Hyperlegible and JetBrains Mono (SIL OFL)'

PAGE = {
    'es': {
        'title': 'Lenguas inventadas',
        'description': 'Crea una lengua: elige sonidos en las tablas del AFI, inventa sílabas y palabras, diseña tus signos, decide la gramática, llena el diccionario y traduce frases con glosa interlineal.',
        'lede': 'Construye una lengua paso a paso. Eliges los sonidos, el generador propone palabras con tus reglas, diseñas un signo para cada sonido y traduces frases con su glosa.',
        'make': ['Un alfabeto propio de 20 signos', 'Un diccionario de 100 palabras', 'Una frase traducida con glosa interlineal', 'Cambios de sonido aplicados a todo el léxico', 'El diccionario en CSV, el alfabeto en SVG o PNG y la gramática en PDF'],
        'steps': [
            'En Estructura eliges la parte en la que trabajas: Sonidos, Sílabas, Escritura, Gramática, Diccionario, Texto o Cambios de sonido.',
            'En Sonidos, toca los símbolos de las tablas del AFI para añadirlos o quitarlos. Cada uno explica cómo se pronuncia.',
            'En Sílabas, ajusta los patrones (CV, CVC…) y pulsa «Generar palabras»: salen con tu semilla y respetan tus reglas.',
            'En Escritura diseñas cada signo uniendo puntos, y en Diccionario y Texto das significado a las palabras y traduces frases.',
            'En Propiedades ves las comprobaciones y los tres retos. Exporta desde Archivo.',
        ],
        'sections': [
            {'h': 'Sonidos y AFI', 'p': 'El Alfabeto Fonético Internacional (AFI) da un símbolo a cada sonido de las lenguas del mundo. Las tablas colocan las consonantes por lugar (dónde se toca la boca) y modo (cómo sale el aire), y las vocales por altura y posición de la lengua. Al elegir un símbolo, el estudio te dice en lenguaje claro cómo se hace ese sonido. No hay audio: se describe con palabras.'},
            {'h': 'Sílabas y palabras', 'p': 'Los patrones dicen cómo se arman las sílabas: C es consonante y V es vocal, así que CV es «ta» y CVC es «tan». Cada patrón tiene un peso: cuanto mayor, más veces sale. El generador usa una semilla, así que la misma semilla da siempre las mismas palabras. Descarta las que suenan a palabras malsonantes reales en español o en inglés.'},
            {'h': 'Escritura', 'p': 'Cada sonido puede tener su signo. Lo dibujas uniendo dos puntos de la rejilla: tocas el primero y luego el segundo, y ese trazo se añade o se quita. Se hace también con el teclado, sin arrastrar. La romanización es cómo escribes ese sonido con letras latinas, y es la que se usa en el diccionario y en la glosa.'},
            {'h': 'Gramática y glosa', 'p': 'Eliges el orden de las palabras (SVO como en español, SOV como en japonés, VSO como en irlandés…), si el adjetivo va antes o después, y los afijos de plural y de tiempo verbal. La glosa interlineal sigue las Leipzig Glossing Rules: una línea con las palabras, otra con el significado de cada trozo (los afijos, separados por guion, con etiquetas como PL, PST o FUT) y una tercera con la traducción libre entre comillas simples.'},
            {'h': 'Cambios de sonido', 'p': 'Las lenguas cambian con el tiempo. Una regla como «a > e / _i» dice: la a se convierte en e cuando va delante de una i. Puedes ver antes de aplicarla a qué palabras afecta, y luego aplicarla a todo el diccionario de una vez. Es lo que hace que una lengua tenga aire de familia.'},
            {'h': 'Fuentes', 'p': 'International Phonetic Association, «IPA Chart» (revisión de 2020), licencia Creative Commons BY-SA 3.0: internationalphoneticassociation.org.\n\nLeipzig Glossing Rules, de Bernard Comrie, Martin Haspelmath y Balthasar Bickel (Max Planck Institute for Evolutionary Anthropology y Universidad de Leipzig; última revisión, 2015).\n\nMorris Swadesh, «Towards Greater Accuracy in Lexicostatistic Dating», International Journal of American Linguistics 21 (1955), pp. 121-137: de ahí viene la idea de una lista de conceptos básicos.\n\nMark Rosenfelder, «The Language Construction Kit», Chicago: Yonagu Books, 2010.'},
        ],
        'links': [('Todo el taller', '/es/taller/'), ('Escritura con restricciones', '/es/taller/escritura-restricciones/'), ('Mundos', '/es/taller/mundos/')],
    },
    'en': {
        'title': 'Invented languages',
        'description': 'Build a language: choose sounds from the IPA charts, invent syllables and words, design your own signs, set the grammar, fill the dictionary and translate sentences with interlinear glossing.',
        'lede': 'Build a language step by step. You choose the sounds, the generator proposes words that follow your rules, you design a sign for each sound and you translate sentences with their gloss.',
        'make': ['Your own 20-sign alphabet', 'A dictionary of 100 words', 'A translated sentence with interlinear glossing', 'Sound changes applied to the whole lexicon', 'The dictionary as CSV, the alphabet as SVG or PNG and the grammar as PDF'],
        'steps': [
            'Structure is where you choose the part you are working on: Sounds, Syllables, Writing, Grammar, Dictionary, Text or Sound changes.',
            'In Sounds, tap symbols in the IPA charts to add or remove them. Each one explains how it is pronounced.',
            'In Syllables, set the patterns (CV, CVC…) and press “Generate words”: they follow your seed and your rules.',
            'In Writing you design each sign by joining dots, and in Dictionary and Text you give words meanings and translate sentences.',
            'Properties shows the checks and the three challenges. Export from File.',
        ],
        'sections': [
            {'h': 'Sounds and the IPA', 'p': 'The International Phonetic Alphabet (IPA) gives one symbol to each sound in the world’s languages. The charts set consonants out by place (where the mouth touches) and manner (how the air comes out), and vowels by tongue height and position. When you choose a symbol, the studio tells you in plain language how that sound is made. There is no audio: it is described in words.'},
            {'h': 'Syllables and words', 'p': 'Patterns say how syllables are built: C is a consonant and V is a vowel, so CV is “ta” and CVC is “tan”. Each pattern has a weight: the higher it is, the more often it comes up. The generator uses a seed, so the same seed always gives the same words. It throws away anything that sounds like a real rude word in Spanish or English.'},
            {'h': 'Writing', 'p': 'Each sound can have its own sign. You draw it by joining two dots on the grid: tap the first, then the second, and that stroke is added or removed. It works with the keyboard too, with no dragging. The romanisation is how you write that sound with Latin letters, and it is what the dictionary and the gloss use.'},
            {'h': 'Grammar and glossing', 'p': 'You choose the word order (SVO as in English, SOV as in Japanese, VSO as in Irish…), whether the adjective comes before or after, and the plural and tense affixes. The interlinear gloss follows the Leipzig Glossing Rules: one line with the words, one with the meaning of each piece (affixes separated by a hyphen, with labels such as PL, PST or FUT) and a third with the free translation in single quotes.'},
            {'h': 'Sound changes', 'p': 'Languages change over time. A rule such as “a > e / _i” says: a becomes e when it comes before an i. You can see which words it affects before you apply it, and then apply it to the whole dictionary at once. This is what gives a language its family resemblance.'},
            {'h': 'Sources', 'p': 'International Phonetic Association, “IPA Chart” (2020 revision), Creative Commons BY-SA 3.0: internationalphoneticassociation.org.\n\nLeipzig Glossing Rules, by Bernard Comrie, Martin Haspelmath and Balthasar Bickel (Max Planck Institute for Evolutionary Anthropology and University of Leipzig; last revised 2015).\n\nMorris Swadesh, “Towards Greater Accuracy in Lexicostatistic Dating”, International Journal of American Linguistics 21 (1955), pp. 121-137: the idea of a basic concept list comes from here.\n\nMark Rosenfelder, “The Language Construction Kit”, Chicago: Yonagu Books, 2010.'},
        ],
        'links': [('The whole workshop', '/en/workshop/'), ('Constraint writing', '/en/workshop/constraint-writing/'), ('Worlds', '/en/workshop/worlds/')],
    },
}

# Ejemplos en lenguaje claro para los sonidos más corrientes (clave ASCII = DATA.key del símbolo).
_EX = {
    'p': ('Como la p de «pato».', 'Like the p in “pat”.'),
    'b': ('Como la b de «bota».', 'Like the b in “boat”.'),
    't': ('Como la t de «taza».', 'Like the t in “top”.'),
    'd': ('Como la d de «dedo».', 'Like the d in “dog”.'),
    'k': ('Como la c de «casa» o la k de «kilo».', 'Like the c in “cat”.'),
    'g': ('Como la g de «gato».', 'Like the g in “goat”.'),
    'm': ('Como la m de «mano».', 'Like the m in “man”.'),
    'n': ('Como la n de «nube».', 'Like the n in “now”.'),
    'ny': ('Como la ñ de «niño».', 'Like the ny sound in “canyon”.'),
    'ng': ('Como la n de «banco», al final de «cantando».', 'Like the ng in “sing”.'),
    'f': ('Como la f de «foca».', 'Like the f in “fish”.'),
    'v': ('Como la v inglesa de «very»; en español no se usa.', 'Like the v in “very”.'),
    'th': ('Como la z de «zapato» en el centro y el norte de España.', 'Like the th in “think”.'),
    'dh': ('Como la d suave de «nada».', 'Like the th in “this”.'),
    's': ('Como la s de «sol».', 'Like the s in “sun”.'),
    'z': ('Como la s de «mismo» o la z inglesa de «zoo».', 'Like the z in “zoo”.'),
    'sh': ('Como la sh inglesa de «ship»; en español no se usa.', 'Like the sh in “ship”.'),
    'ch': ('Como la ch de «chico».', 'Like the ch in “chip”.'),
    'dj': ('Como la j inglesa de «jam».', 'Like the j in “jam”.'),
    'x': ('Como la j de «jarra».', 'Like the ch in the Scottish “loch”.'),
    'h': ('Como la h inglesa de «hat»; en español la h no suena.', 'Like the h in “hat”.'),
    'r': ('Como la rr de «perro».', 'Like a rolled Spanish rr.'),
    'rt': ('Como la r de «pera».', 'Like the quick r in the Spanish “pera”.'),
    'ra': ('Como la r inglesa de «red».', 'Like the r in “red”.'),
    'l': ('Como la l de «luna».', 'Like the l in “love”.'),
    'll': ('Como la ll de «llave» en quien distingue ll de y.', 'Like the lli in “million”.'),
    'j': ('Como la i de «piano» o la y de «yo».', 'Like the y in “yes”.'),
    'w': ('Como la u de «hueso» o la w inglesa de «water».', 'Like the w in “water”.'),
    'q7': ('El cortito de «ah-ah»: cierras la garganta un instante.', 'The catch in the middle of “uh-oh”.'),
    'a': ('Como la a de «casa».', 'Like the a in “father”.'),
    'e': ('Como la e de «mesa».', 'Like the e in “bed”, but tenser.'),
    'i': ('Como la i de «vino».', 'Like the ee in “see”.'),
    'o': ('Como la o de «boca».', 'Like the o in “more”.'),
    'u': ('Como la u de «luna».', 'Like the oo in “moon”.'),
    'eh': ('Como la e abierta de «perro».', 'Like the e in “bed”.'),
    'oh': ('Como la o abierta inglesa de «thought».', 'Like the aw in “thought”.'),
    'ae': ('Como la a inglesa de «cat».', 'Like the a in “cat”.'),
    'sw': ('La vocal floja del final de «sofá» en inglés («sofa»).', 'Like the a in “about”.'),
    'ii': ('Como la i inglesa de «sit».', 'Like the i in “sit”.'),
    'uu': ('Como la u inglesa de «put».', 'Like the u in “put”.'),
    'uh': ('Como la u inglesa de «cup».', 'Like the u in “cup”.'),
    'o2': ('Como la eu francesa de «peu».', 'Like the eu in the French “peu”.'),
    'yy': ('Como la u francesa de «tu».', 'Like the u in the French “tu”.'),
}

_PLACES_ES = {'bilabial': 'bilabial', 'labiodental': 'labiodental', 'dental': 'dental', 'alveolar': 'alveolar', 'postalveolar': 'postalveolar',
              'retroflex': 'retrofleja', 'palatal': 'palatal', 'velar': 'velar', 'uvular': 'uvular', 'pharyngeal': 'faríngea', 'glottal': 'glotal', 'labialvelar': 'labiovelar'}
_PLACES_EN = {'bilabial': 'bilabial', 'labiodental': 'labiodental', 'dental': 'dental', 'alveolar': 'alveolar', 'postalveolar': 'post-alveolar',
              'retroflex': 'retroflex', 'palatal': 'palatal', 'velar': 'velar', 'uvular': 'uvular', 'pharyngeal': 'pharyngeal', 'glottal': 'glottal', 'labialvelar': 'labial-velar'}
_WHERE_ES = {'bilabial': 'Juntas los dos labios.', 'labiodental': 'Los dientes de arriba tocan el labio de abajo.', 'dental': 'La lengua toca los dientes de arriba.',
             'alveolar': 'La punta de la lengua toca detrás de los dientes de arriba.', 'postalveolar': 'La lengua se coloca un poco más atrás, cerca del paladar.',
             'retroflex': 'La punta de la lengua se dobla hacia atrás.', 'palatal': 'El centro de la lengua sube hacia el paladar.',
             'velar': 'La parte de atrás de la lengua toca el velo del paladar.', 'uvular': 'La lengua llega hasta la campanilla.',
             'pharyngeal': 'El sonido se hace muy atrás, en la garganta.', 'glottal': 'El sonido se hace en las cuerdas vocales.',
             'labialvelar': 'Redondeas los labios y a la vez subes la parte de atrás de la lengua.'}
_WHERE_EN = {'bilabial': 'You put both lips together.', 'labiodental': 'Your top teeth touch your bottom lip.', 'dental': 'Your tongue touches your top teeth.',
             'alveolar': 'The tip of your tongue touches just behind your top teeth.', 'postalveolar': 'Your tongue sits a little further back, near the roof of the mouth.',
             'retroflex': 'The tip of your tongue curls backwards.', 'palatal': 'The middle of your tongue rises to the roof of your mouth.',
             'velar': 'The back of your tongue touches the soft palate.', 'uvular': 'Your tongue reaches right back to the uvula.',
             'pharyngeal': 'The sound is made far back, in the throat.', 'glottal': 'The sound is made at the vocal folds.',
             'labialvelar': 'You round your lips and raise the back of your tongue at the same time.'}
_MANNER_ES = {'plosive': 'oclusiva', 'nasal': 'nasal', 'trill': 'vibrante múltiple', 'tap': 'vibrante simple', 'fricative': 'fricativa',
              'latfric': 'fricativa lateral', 'approx': 'aproximante', 'latapprox': 'aproximante lateral', 'affricate': 'africada'}
_MANNER_EN = {'plosive': 'plosive', 'nasal': 'nasal', 'trill': 'trill', 'tap': 'tap', 'fricative': 'fricative',
              'latfric': 'lateral fricative', 'approx': 'approximant', 'latapprox': 'lateral approximant', 'affricate': 'affricate'}
_HOW_ES = {'plosive': 'Cortas el aire del todo y lo sueltas de golpe.', 'nasal': 'El aire sale por la nariz.', 'trill': 'La lengua o los labios vibran varias veces.',
           'tap': 'La lengua da un golpecito rápido.', 'fricative': 'El aire pasa por un hueco estrecho y hace ruido.',
           'latfric': 'El aire sale rozando por los lados de la lengua.', 'approx': 'La lengua se acerca sin llegar a rozar.',
           'latapprox': 'El aire sale por los lados de la lengua, sin ruido.', 'affricate': 'Cortas el aire y lo sueltas rozando, como una t y una s pegadas.'}
_HOW_EN = {'plosive': 'You stop the air completely and let it go all at once.', 'nasal': 'The air comes out through your nose.', 'trill': 'Your tongue or lips vibrate several times.',
           'tap': 'Your tongue gives one quick flick.', 'fricative': 'The air squeezes through a narrow gap and makes a hiss.',
           'latfric': 'The air rubs out along the sides of your tongue.', 'approx': 'Your tongue comes close without touching.',
           'latapprox': 'The air flows out along the sides of your tongue, with no hiss.', 'affricate': 'You stop the air and release it with a hiss, like a t and an s together.'}
_HEIGHT_ES = {'close': 'cerrada', 'nearclose': 'casi cerrada', 'closemid': 'semicerrada', 'mid': 'media', 'openmid': 'semiabierta', 'nearopen': 'casi abierta', 'open': 'abierta'}
_HEIGHT_EN = {'close': 'close', 'nearclose': 'near-close', 'closemid': 'close-mid', 'mid': 'mid', 'openmid': 'open-mid', 'nearopen': 'near-open', 'open': 'open'}
_BACK_ES = {'front': 'anterior', 'central': 'central', 'back': 'posterior'}
_BACK_EN = {'front': 'front', 'central': 'central', 'back': 'back'}


def _sound_keys(lang):
    d = {}
    src_p, src_w, src_m, src_h, src_hh, src_b = ((_PLACES_ES, _WHERE_ES, _MANNER_ES, _HOW_ES, _HEIGHT_ES, _BACK_ES) if lang == 'es'
                                                 else (_PLACES_EN, _WHERE_EN, _MANNER_EN, _HOW_EN, _HEIGHT_EN, _BACK_EN))
    for k, v in src_p.items():
        d['p_' + k] = v
    for k, v in src_w.items():
        d['where_' + k] = v
    for k, v in src_m.items():
        d['m_' + k] = v
    for k, v in src_h.items():
        d['how_' + k] = v
    for k, v in src_hh.items():
        d['h_' + k] = v
    for k, v in src_b.items():
        d['b_' + k] = v
    for k, v in _EX.items():
        d['ex_' + k] = v[0] if lang == 'es' else v[1]
    return d


STRINGS = {
    'es': {
        'canvasLabel': 'Documento de tu lengua', 'canvasHelp': 'Elige la parte en Estructura o con la lista «Ir a». Re Pág y Av Pág cambian de parte. En las tablas de sonidos, las flechas mueven el foco y Intro añade o quita el sonido.',
        'kLangTable': 'En las tablas de sonidos: flechas para moverte, Intro o Espacio para añadir o quitar',
        'kLangParts': 'Av Pág y Re Pág: parte siguiente y anterior del documento',
        'newLangName': 'Mi lengua', 'langTitle': 'Tu lengua', 'langName': 'Nombre de la lengua', 'nameChanged': 'La lengua se llama «{n}»',
        'nSoundsLabel': 'Sonidos', 'nWordsLabel': 'Palabras', 'nSignsLabel': 'Signos dibujados', 'nSentencesLabel': 'Frases',
        'partsTitle': 'Partes', 'partsHelp': 'Cada parte se trabaja por separado. El orden es una sugerencia.', 'goToPart': 'Ir a',
        'sec_sounds': 'Sonidos', 'sec_syllables': 'Sílabas y palabras', 'sec_writing': 'Escritura', 'sec_grammar': 'Gramática',
        'sec_dict': 'Diccionario', 'sec_text': 'Texto y glosa', 'sec_changes': 'Cambios de sonido',
        'sectionNow': 'Ahora estás en {s}. {meta}', 'deselected': 'Nada elegido.',
        'nSounds': '{n} sonidos', 'nPatterns': '{n} patrones', 'nSigns': '{n} de {goal} signos', 'nWords': '{n} de {goal} palabras',
        'nSentences': '{n} frases', 'nRules': '{n} reglas',
        'nSounds1': '1 sonido', 'nPatterns1': '1 patrón', 'nSentences1': '1 frase', 'nRules1': '1 regla',
        'soundsLede': 'Elige los sonidos de tu lengua en las tablas. Con 10 o 15 ya se puede hablar.',
        'yourSounds': 'Sonidos elegidos', 'noSounds': 'Todavía no has elegido ningún sonido. Toca un símbolo de las tablas.',
        'chipSound': 'Ver {s}', 'consTable': 'Consonantes: el lugar en las columnas y el modo en las filas',
        'vowTable': 'Vocales: la altura de la lengua en las filas y la posición en las columnas',
        'otherSounds': 'Otros sonidos', 'mannerCol': 'Modo', 'heightCol': 'Altura',
        'ipaSource': 'Tablas basadas en el Alfabeto Fonético Internacional (IPA Chart, revisión de 2020). Sin audio: cada sonido se explica con palabras.',
        'cDesc': '{m} {p} {v}', 'vDesc': 'vocal {h} {b} {r}', 'voiced': 'sonora', 'voiceless': 'sorda', 'rounded': 'redondeada', 'unrounded': 'no redondeada',
        'howV': 'La lengua va en posición {h} y {b}.',
        'soundTitle': 'Sonido {s}', 'romanLabel': 'Cómo se escribe (romanización)', 'romanChanged': 'El sonido {s} se escribe «{r}»',
        'romanHelp': 'Con letras latinas. Se usa en el diccionario, en la glosa y en las exportaciones.',
        'soundOn': 'Sonido añadido: {s}', 'soundOff': 'Sonido quitado: {s}', 'soundUsed': 'Algunas palabras lo usaban: revísalas.',
        'addSound': 'Añadir a mi lengua', 'removeSound': 'Quitar de mi lengua', 'strokesN': '{n} trazos', 'example': 'Ejemplo',
        'syllLede': 'Los patrones dicen cómo son tus sílabas. C es consonante y V es vocal: CV es «ta» y CVC es «tan».',
        'patternsTitle': 'Patrones de sílaba', 'patternN': 'Patrón {n}', 'patternWeight': 'Peso', 'removePattern': 'Quitar', 'addPattern': 'Añadir patrón',
        'patternHelp': 'Solo letras C y V, hasta cinco. Cuanto mayor es el peso, más veces sale ese patrón.',
        'patternBad': 'Un patrón solo puede llevar C y V.', 'patternChanged': 'Patrón: {p}', 'patternAdded': 'Patrón añadido', 'patternRemoved': 'Patrón quitado',
        'lastPattern': 'Tiene que quedar al menos un patrón.', 'maxPatterns': 'Como máximo, ocho patrones.',
        'genTitle': 'Generador de palabras', 'genHelp': 'La semilla hace que el azar sea repetible: con la misma semilla salen las mismas palabras.',
        'seed': 'Semilla', 'seedChanged': 'Semilla cambiada', 'genBtn': 'Generar palabras', 'genMore': 'Generar más',
        'genResults': '{n} palabras nuevas (semilla «{seed}»)', 'genEmpty': 'Pulsa «Generar palabras» para ver propuestas.',
        'genDone': '{n} palabras propuestas', 'genNone': 'No han salido palabras nuevas. Prueba otra semilla.',
        'addToDict': 'Añadir al diccionario', 'needSounds': 'Elige antes al menos una consonante y una vocal en Sonidos.',
        'writeLede': 'Dibuja un signo para cada sonido. Toca un punto y luego otro: el trazo se añade o se quita.',
        'signsGoal': 'Reto: alfabeto de 20 signos.', 'progressN': '{n} de {goal}', 'progressPct': '{n} por ciento',
        'designFor': 'Signo de {s}', 'alphabetTitle': 'Tu alfabeto', 'signOf': 'Signo de {s} · {n} trazos',
        'gridLabel': 'Rejilla de puntos del signo', 'pointN': 'Punto columna {c}, fila {r}',
        'pointPicked': 'Punto de inicio en columna {c}, fila {r}. Elige el segundo punto.', 'pointCancel': 'Punto de inicio cancelado.',
        'strokeAdded': 'Trazo añadido', 'strokeRemoved': 'Trazo quitado', 'noStrokes': 'Este signo no tiene trazos.',
        'undoStroke': 'Quitar el último trazo', 'clearGlyph': 'Vaciar el signo', 'presetGlyph': 'Propuesta automática',
        'glyphCleared': 'Signo vacío', 'glyphPreset': 'Signo propuesto', 'designBtn': 'Diseñar el signo',
        'designHelp': 'Sin arrastrar: dos toques por trazo. Con el teclado, Tab lleva a los puntos e Intro los elige.',
        'gramLede': 'Decide cómo se ordenan las palabras y qué afijos marcan el plural y el tiempo.',
        'wordOrder': 'Orden de las palabras', 'order_SVO': 'SVO · sujeto, verbo, objeto', 'order_SOV': 'SOV · sujeto, objeto, verbo',
        'order_VSO': 'VSO · verbo, sujeto, objeto', 'order_VOS': 'VOS · verbo, objeto, sujeto', 'order_OSV': 'OSV · objeto, sujeto, verbo', 'order_OVS': 'OVS · objeto, verbo, sujeto',
        'orderChanged': 'Orden: {o}', 'adjPos': 'Posición del adjetivo', 'adjBefore': 'antes del nombre', 'adjAfter': 'después del nombre', 'adjChanged': 'Posición del adjetivo cambiada',
        'affixTitle': 'Afijos', 'affixHelp': 'Escribe el afijo con tus letras. Si lo dejas vacío, esa marca no se escribe (∅).',
        'affix_plural': 'Plural', 'affix_past': 'Pasado', 'affix_present': 'Presente', 'affix_future': 'Futuro',
        'affixForm': 'Forma', 'affixType': 'Dónde va', 'prefix': 'delante (prefijo)', 'suffix': 'detrás (sufijo)',
        'affixChanged': '{a}: {f}', 'affixBad': 'Estas letras no están en tu lengua: {l}',
        'dictLede': 'Da significado a tus palabras. La lista de conceptos básicos te da ideas para empezar.',
        'wordsGoal': 'Reto: 100 palabras.', 'searchLabel': 'Buscar en el diccionario', 'addWordBtn': 'Palabra nueva', 'fillConcept': 'Palabra para el siguiente concepto',
        'dictCaption': 'Diccionario: {n} de {total} palabras', 'dictEmpty': 'El diccionario está vacío. Pulsa «Palabra nueva» o genera palabras en Sílabas.',
        'noMatches': 'Ninguna palabra contiene «{q}».', 'tooManyRows': 'Se muestran las 300 primeras. Usa la búsqueda para ver el resto.',
        'colWord': 'Palabra', 'colIpa': 'AFI', 'colEs': 'Significado en español', 'colEn': 'Significado en inglés', 'colCat': 'Categoría', 'colConcept': 'Concepto',
        'cat_n': 'nombre', 'cat_v': 'verbo', 'cat_adj': 'adjetivo', 'cat_pron': 'pronombre', 'cat_num': 'número', 'cat_part': 'partícula',
        'conceptsTitle': 'Conceptos básicos', 'conceptsHelp': 'Lista inspirada en la de Swadesh (1955). Pulsa uno y el generador crea su palabra.',
        'conceptsDone': 'Ya tienes una palabra para cada concepto de la lista.', 'makeWordFor': 'Crear la palabra para «{m}»',
        'wordTitle': 'Palabra', 'wordForm': 'Palabra (con tus letras)', 'wordChanged': 'Palabra: {w}', 'wordEmpty': 'Escribe la palabra con letras de tu lengua.',
        'wordAdded': 'Palabra añadida: {w}', 'wordDeleted': 'Palabra borrada: {w}', 'wordSelected': '{w}: {m}', 'meaningChanged': 'Significado cambiado', 'catChanged': 'Categoría cambiada',
        'deleteWord': 'Borrar la palabra', 'useInSentence': 'Usar en la frase', 'withChanges': 'Con los cambios de sonido: ', 'maxWords': 'Como máximo, {n} palabras.',
        'textLede': 'Arma una frase con tus palabras: el estudio la ordena, le pone los afijos y la glosa.',
        'addSentence': 'Frase nueva', 'delSentence': 'Borrar la frase', 'sentenceAdded': 'Frase nueva', 'sentenceDeleted': 'Frase borrada',
        'lastSentence': 'Tiene que quedar al menos una frase.', 'maxSentences': 'Como máximo, 40 frases.',
        'freeLabel': 'Qué quieres decir (traducción libre)', 'freeChanged': 'Traducción libre cambiada',
        'wordsOfSentence': 'Palabras de la frase', 'needWords': 'Añade antes palabras al diccionario.',
        'slotWord': 'Palabra {n}', 'slotRole': 'Función', 'slotPlural': 'En plural', 'slotTense': 'Tiempo',
        'role_S': 'sujeto', 'role_V': 'verbo', 'role_O': 'objeto', 'role_ADJ': 'adjetivo', 'role_X': 'otra',
        'tense_none': 'sin marcar', 'tense_past': 'pasado', 'tense_present': 'presente', 'tense_future': 'futuro',
        'addSlot': 'Añadir palabra a la frase', 'slotAdded': 'Palabra añadida a la frase', 'slotRemoved': 'Palabra quitada de la frase',
        'slotChanged': 'Frase cambiada', 'slotUp': 'Subir', 'slotDown': 'Bajar', 'slotRemove': 'Quitar', 'slotMoved': 'Orden cambiado',
        'firstSlot': 'Ya es la primera.', 'lastSlot': 'Ya es la última.', 'maxSlots': 'Como máximo, 20 palabras por frase.',
        'glossTitle': 'Glosa interlineal', 'glossEmpty': 'Añade palabras a la frase para ver la glosa.',
        'glossNote': 'Glosa según las Leipzig Glossing Rules: una línea con las palabras, otra con el significado de cada trozo y la traducción libre entre comillas simples.',
        'noFree': 'escribe aquí qué quiere decir', 'inYourAlphabet': 'En tu alfabeto', 'scriptAlt': 'Texto en tu alfabeto: {s}',
        'abbr_PL': 'plural', 'abbr_PST': 'pasado', 'abbr_PRS': 'presente', 'abbr_FUT': 'futuro',
        'changeLede': 'Una regla como «a > e / _i» cambia un sonido según lo que tenga al lado. Mira la vista previa antes de aplicarla.',
        'ruleN': 'Regla {n}', 'ruleFrom': 'Sonido que cambia', 'ruleTo': 'Se convierte en', 'ruleLeft': 'Cuando antes hay', 'ruleRight': 'Cuando después hay',
        'anySound': 'cualquier sonido', 'wordEdge': 'el principio o el final de la palabra', 'deleteSound': 'nada (el sonido desaparece)',
        'ruleOn': 'Regla activa', 'ruleOff': 'inactiva', 'ruleEnabled': 'Regla activada', 'ruleDisabled': 'Regla desactivada',
        'ruleAdded': 'Regla añadida', 'ruleRemoved': 'Regla quitada', 'ruleRemove': 'Quitar la regla', 'ruleChanged': 'Regla cambiada',
        'addRule': 'Añadir regla', 'maxRules': 'Como máximo, doce reglas.', 'noRules': 'Todavía no hay reglas.',
        'applyChanges': 'Aplicar al diccionario', 'changesApplied': 'Cambios aplicados a {n} palabras. Las reglas quedan desactivadas.',
        'previewTitle': 'Vista previa', 'previewNoRules': 'Activa alguna regla para ver la vista previa.', 'previewNone': 'Ninguna palabra cambia con estas reglas.',
        'previewCaption': 'Palabras que cambian: {n}', 'colBefore': 'Antes', 'colAfter': 'Después', 'colMeaning': 'Significado',
        'challengesTitle': 'Retos', 'doneWord': 'Conseguido', 'pendingWord': 'Pendiente',
        'chSigns': 'Alfabeto de 20 signos: llevas {n} de {goal}.', 'chWords': '100 palabras: llevas {n} de {goal}.', 'chText': 'Texto traducido: {n} frases completas.', 'chText1': 'Texto traducido: 1 frase completa.',
        'checksTitle': 'Comprobación', 'okWord': 'Bien', 'checkWord': 'Revisar',
        'ckNoCons': 'No hay consonantes: elige alguna en Sonidos.', 'ckNoVowels': 'No hay vocales: elige alguna en Sonidos.',
        'ckInventory': 'Inventario: {c} consonantes y {v} vocales.', 'ckNoGlyph': 'Faltan signos para {n} sonidos ({l}).', 'ckGlyphs': 'Todos tus sonidos tienen signo.',
        'ckDupes': 'Hay {n} palabras repetidas.', 'ckNoMeaning': 'Hay {n} palabras sin significado.', 'ckBadPattern': 'Algún patrón no es válido: solo C y V.',
        'ckAllGood': 'Todo en orden por ahora.',
        'exportCsv': 'Exportar diccionario (CSV)', 'exportGrammar': 'Imprimir la gramática o guardarla en PDF',
        'exportAlphaSvg': 'Exportar alfabeto (SVG)', 'exportAlphaPng': 'Exportar alfabeto (PNG)',
        'exportTextSvg': 'Exportar texto en tu alfabeto (SVG)', 'exportTextPng': 'Exportar texto en tu alfabeto (PNG)',
        'nothingToExport': 'Todavía no hay nada que exportar aquí.', 'pngError': 'No se ha podido crear la imagen.',
        'printing': 'Se abre el diálogo de impresión. Para un PDF, elige «Guardar como PDF».',
        'alphaTitle': 'Alfabeto de {name}', 'alphaDesc': 'Alfabeto con {n} signos: {list}.',
        'textSvgTitle': 'Texto en {name}', 'textSvgDesc': 'Texto «{s}», que quiere decir «{free}».',
        'printSub': '{c} consonantes, {v} vocales, {s} signos y {w} palabras.', 'printPatterns': 'Patrones de sílaba: {p}.',
        'sumHead': 'Lengua «{name}». Parte: {sec}.', 'sumSounds': 'Sonidos: {c} consonantes y {v} vocales ({list}).',
        'sumSigns': 'Signos dibujados: {n} de {goal}.', 'sumWords': 'Diccionario: {n} de {goal} palabras.',
        'sumGrammar': 'Orden {o}; adjetivo {a}.', 'sumText': 'Frase: «{s}», que quiere decir «{free}».',
        'stSecret': 'Idioma secreto con 20 signos', 'stSecretD': 'Sonidos sencillos y un signo para cada uno. Llega a 20.',
        'stFantasy': 'Lengua de un mundo de fantasía', 'stFantasyD': 'Muchos sonidos, palabras generadas y orden VSO. Llega a 100 palabras.',
        'stFull': 'Sistema completo con cambios de sonido', 'stFullD': 'Inventario grande, orden SOV y dos reglas de cambio listas.',
        'stTranslate': 'Traducir un texto corto', 'stTranslateD': 'Un léxico pequeño y una frase de ejemplo con su glosa.',
        'nameSecret': 'Lengua secreta', 'nameFantasy': 'Lengua del bosque', 'nameFull': 'Lengua antigua', 'nameTranslate': 'Primera lengua',
        'exFree': 'La niña ve el agua',
    },
    'en': {
        'canvasLabel': 'Your language document', 'canvasHelp': 'Choose a part in Structure or with the “Go to” list. Page Down and Page Up move between parts. In the sound charts, the arrow keys move the focus and Enter adds or removes the sound.',
        'kLangTable': 'In the sound charts: arrow keys to move, Enter or Space to add or remove',
        'kLangParts': 'Page Down and Page Up: next and previous part of the document',
        'newLangName': 'My language', 'langTitle': 'Your language', 'langName': 'Language name', 'nameChanged': 'The language is called “{n}”',
        'nSoundsLabel': 'Sounds', 'nWordsLabel': 'Words', 'nSignsLabel': 'Signs drawn', 'nSentencesLabel': 'Sentences',
        'partsTitle': 'Parts', 'partsHelp': 'Each part is worked on separately. The order is only a suggestion.', 'goToPart': 'Go to',
        'sec_sounds': 'Sounds', 'sec_syllables': 'Syllables and words', 'sec_writing': 'Writing', 'sec_grammar': 'Grammar',
        'sec_dict': 'Dictionary', 'sec_text': 'Text and gloss', 'sec_changes': 'Sound changes',
        'sectionNow': 'You are now in {s}. {meta}', 'deselected': 'Nothing selected.',
        'nSounds': '{n} sounds', 'nPatterns': '{n} patterns', 'nSigns': '{n} of {goal} signs', 'nWords': '{n} of {goal} words',
        'nSentences': '{n} sentences', 'nRules': '{n} rules',
        'nSounds1': '1 sound', 'nPatterns1': '1 pattern', 'nSentences1': '1 sentence', 'nRules1': '1 rule',
        'soundsLede': 'Choose the sounds of your language in the charts. Ten or fifteen are already enough to speak.',
        'yourSounds': 'Sounds chosen', 'noSounds': 'You have not chosen any sounds yet. Tap a symbol in the charts.',
        'chipSound': 'Show {s}', 'consTable': 'Consonants: place across the columns, manner down the rows',
        'vowTable': 'Vowels: tongue height down the rows, position across the columns',
        'otherSounds': 'Other sounds', 'mannerCol': 'Manner', 'heightCol': 'Height',
        'ipaSource': 'Charts based on the International Phonetic Alphabet (IPA Chart, 2020 revision). No audio: every sound is explained in words.',
        'cDesc': '{v} {p} {m}', 'vDesc': '{h} {b} {r} vowel', 'voiced': 'voiced', 'voiceless': 'voiceless', 'rounded': 'rounded', 'unrounded': 'unrounded',
        'howV': 'Your tongue sits in a {h} and {b} position.',
        'soundTitle': 'Sound {s}', 'romanLabel': 'How it is written (romanisation)', 'romanChanged': 'The sound {s} is written “{r}”',
        'romanHelp': 'With Latin letters. It is used in the dictionary, in the gloss and in exports.',
        'soundOn': 'Sound added: {s}', 'soundOff': 'Sound removed: {s}', 'soundUsed': 'Some words were using it: check them.',
        'addSound': 'Add to my language', 'removeSound': 'Remove from my language', 'strokesN': '{n} strokes', 'example': 'Example',
        'syllLede': 'Patterns say what your syllables look like. C is a consonant and V is a vowel: CV is “ta” and CVC is “tan”.',
        'patternsTitle': 'Syllable patterns', 'patternN': 'Pattern {n}', 'patternWeight': 'Weight', 'removePattern': 'Remove', 'addPattern': 'Add pattern',
        'patternHelp': 'Only the letters C and V, up to five. The higher the weight, the more often that pattern comes up.',
        'patternBad': 'A pattern can only use C and V.', 'patternChanged': 'Pattern: {p}', 'patternAdded': 'Pattern added', 'patternRemoved': 'Pattern removed',
        'lastPattern': 'At least one pattern must remain.', 'maxPatterns': 'Eight patterns at most.',
        'genTitle': 'Word generator', 'genHelp': 'The seed makes the randomness repeatable: the same seed gives the same words.',
        'seed': 'Seed', 'seedChanged': 'Seed changed', 'genBtn': 'Generate words', 'genMore': 'Generate more',
        'genResults': '{n} new words (seed “{seed}”)', 'genEmpty': 'Press “Generate words” to see suggestions.',
        'genDone': '{n} words suggested', 'genNone': 'No new words came up. Try another seed.',
        'addToDict': 'Add to the dictionary', 'needSounds': 'First choose at least one consonant and one vowel in Sounds.',
        'writeLede': 'Draw a sign for each sound. Tap one dot and then another: the stroke is added or removed.',
        'signsGoal': 'Challenge: a 20-sign alphabet.', 'progressN': '{n} of {goal}', 'progressPct': '{n} per cent',
        'designFor': 'Sign for {s}', 'alphabetTitle': 'Your alphabet', 'signOf': 'Sign for {s} · {n} strokes',
        'gridLabel': 'Dot grid for the sign', 'pointN': 'Dot column {c}, row {r}',
        'pointPicked': 'Start dot at column {c}, row {r}. Choose the second dot.', 'pointCancel': 'Start dot cancelled.',
        'strokeAdded': 'Stroke added', 'strokeRemoved': 'Stroke removed', 'noStrokes': 'This sign has no strokes.',
        'undoStroke': 'Remove the last stroke', 'clearGlyph': 'Empty the sign', 'presetGlyph': 'Suggest a sign',
        'glyphCleared': 'Sign emptied', 'glyphPreset': 'Sign suggested', 'designBtn': 'Design the sign',
        'designHelp': 'No dragging: two taps per stroke. With the keyboard, Tab reaches the dots and Enter chooses them.',
        'gramLede': 'Decide how words are ordered and which affixes mark plural and tense.',
        'wordOrder': 'Word order', 'order_SVO': 'SVO · subject, verb, object', 'order_SOV': 'SOV · subject, object, verb',
        'order_VSO': 'VSO · verb, subject, object', 'order_VOS': 'VOS · verb, object, subject', 'order_OSV': 'OSV · object, subject, verb', 'order_OVS': 'OVS · object, verb, subject',
        'orderChanged': 'Order: {o}', 'adjPos': 'Adjective position', 'adjBefore': 'before the noun', 'adjAfter': 'after the noun', 'adjChanged': 'Adjective position changed',
        'affixTitle': 'Affixes', 'affixHelp': 'Write the affix with your own letters. If you leave it empty, that marking is not written (∅).',
        'affix_plural': 'Plural', 'affix_past': 'Past', 'affix_present': 'Present', 'affix_future': 'Future',
        'affixForm': 'Form', 'affixType': 'Where it goes', 'prefix': 'in front (prefix)', 'suffix': 'behind (suffix)',
        'affixChanged': '{a}: {f}', 'affixBad': 'These letters are not in your language: {l}',
        'dictLede': 'Give your words their meanings. The list of basic concepts gives you ideas to start with.',
        'wordsGoal': 'Challenge: 100 words.', 'searchLabel': 'Search the dictionary', 'addWordBtn': 'New word', 'fillConcept': 'Word for the next concept',
        'dictCaption': 'Dictionary: {n} of {total} words', 'dictEmpty': 'The dictionary is empty. Press “New word” or generate words in Syllables.',
        'noMatches': 'No word contains “{q}”.', 'tooManyRows': 'The first 300 are shown. Use the search to see the rest.',
        'colWord': 'Word', 'colIpa': 'IPA', 'colEs': 'Meaning in Spanish', 'colEn': 'Meaning in English', 'colCat': 'Category', 'colConcept': 'Concept',
        'cat_n': 'noun', 'cat_v': 'verb', 'cat_adj': 'adjective', 'cat_pron': 'pronoun', 'cat_num': 'number', 'cat_part': 'particle',
        'conceptsTitle': 'Basic concepts', 'conceptsHelp': 'A list inspired by Swadesh (1955). Press one and the generator makes its word.',
        'conceptsDone': 'You already have a word for every concept on the list.', 'makeWordFor': 'Make the word for “{m}”',
        'wordTitle': 'Word', 'wordForm': 'Word (with your letters)', 'wordChanged': 'Word: {w}', 'wordEmpty': 'Write the word with letters from your language.',
        'wordAdded': 'Word added: {w}', 'wordDeleted': 'Word deleted: {w}', 'wordSelected': '{w}: {m}', 'meaningChanged': 'Meaning changed', 'catChanged': 'Category changed',
        'deleteWord': 'Delete the word', 'useInSentence': 'Use in the sentence', 'withChanges': 'With the sound changes: ', 'maxWords': '{n} words at most.',
        'textLede': 'Build a sentence with your words: the studio orders it, adds the affixes and glosses it.',
        'addSentence': 'New sentence', 'delSentence': 'Delete the sentence', 'sentenceAdded': 'New sentence', 'sentenceDeleted': 'Sentence deleted',
        'lastSentence': 'At least one sentence must remain.', 'maxSentences': 'Forty sentences at most.',
        'freeLabel': 'What you want to say (free translation)', 'freeChanged': 'Free translation changed',
        'wordsOfSentence': 'Words in the sentence', 'needWords': 'First add words to the dictionary.',
        'slotWord': 'Word {n}', 'slotRole': 'Role', 'slotPlural': 'Plural', 'slotTense': 'Tense',
        'role_S': 'subject', 'role_V': 'verb', 'role_O': 'object', 'role_ADJ': 'adjective', 'role_X': 'other',
        'tense_none': 'unmarked', 'tense_past': 'past', 'tense_present': 'present', 'tense_future': 'future',
        'addSlot': 'Add a word to the sentence', 'slotAdded': 'Word added to the sentence', 'slotRemoved': 'Word removed from the sentence',
        'slotChanged': 'Sentence changed', 'slotUp': 'Move up', 'slotDown': 'Move down', 'slotRemove': 'Remove', 'slotMoved': 'Order changed',
        'firstSlot': 'It is already the first one.', 'lastSlot': 'It is already the last one.', 'maxSlots': 'Twenty words per sentence at most.',
        'glossTitle': 'Interlinear gloss', 'glossEmpty': 'Add words to the sentence to see the gloss.',
        'glossNote': 'Glossing follows the Leipzig Glossing Rules: one line with the words, one with the meaning of each piece, and the free translation in single quotes.',
        'noFree': 'write here what it means', 'inYourAlphabet': 'In your alphabet', 'scriptAlt': 'Text in your alphabet: {s}',
        'abbr_PL': 'plural', 'abbr_PST': 'past', 'abbr_PRS': 'present', 'abbr_FUT': 'future',
        'changeLede': 'A rule such as “a > e / _i” changes a sound depending on what is next to it. Look at the preview before you apply it.',
        'ruleN': 'Rule {n}', 'ruleFrom': 'Sound that changes', 'ruleTo': 'Becomes', 'ruleLeft': 'When before it there is', 'ruleRight': 'When after it there is',
        'anySound': 'any sound', 'wordEdge': 'the start or the end of the word', 'deleteSound': 'nothing (the sound disappears)',
        'ruleOn': 'Rule on', 'ruleOff': 'off', 'ruleEnabled': 'Rule switched on', 'ruleDisabled': 'Rule switched off',
        'ruleAdded': 'Rule added', 'ruleRemoved': 'Rule removed', 'ruleRemove': 'Remove the rule', 'ruleChanged': 'Rule changed',
        'addRule': 'Add rule', 'maxRules': 'Twelve rules at most.', 'noRules': 'There are no rules yet.',
        'applyChanges': 'Apply to the dictionary', 'changesApplied': 'Changes applied to {n} words. The rules are switched off.',
        'previewTitle': 'Preview', 'previewNoRules': 'Switch a rule on to see the preview.', 'previewNone': 'No word changes with these rules.',
        'previewCaption': 'Words that change: {n}', 'colBefore': 'Before', 'colAfter': 'After', 'colMeaning': 'Meaning',
        'challengesTitle': 'Challenges', 'doneWord': 'Done', 'pendingWord': 'Still to do',
        'chSigns': '20-sign alphabet: you have {n} of {goal}.', 'chWords': '100 words: you have {n} of {goal}.', 'chText': 'Translated text: {n} complete sentences.', 'chText1': 'Translated text: 1 complete sentence.',
        'checksTitle': 'Check', 'okWord': 'Fine', 'checkWord': 'Look at',
        'ckNoCons': 'There are no consonants: choose some in Sounds.', 'ckNoVowels': 'There are no vowels: choose some in Sounds.',
        'ckInventory': 'Inventory: {c} consonants and {v} vowels.', 'ckNoGlyph': '{n} sounds still have no sign ({l}).', 'ckGlyphs': 'Every sound of yours has a sign.',
        'ckDupes': 'There are {n} repeated words.', 'ckNoMeaning': 'There are {n} words with no meaning.', 'ckBadPattern': 'A pattern is not valid: only C and V.',
        'ckAllGood': 'All fine so far.',
        'exportCsv': 'Export dictionary (CSV)', 'exportGrammar': 'Print the grammar or save it as PDF',
        'exportAlphaSvg': 'Export alphabet (SVG)', 'exportAlphaPng': 'Export alphabet (PNG)',
        'exportTextSvg': 'Export text in your alphabet (SVG)', 'exportTextPng': 'Export text in your alphabet (PNG)',
        'nothingToExport': 'There is nothing to export here yet.', 'pngError': 'The image could not be created.',
        'printing': 'The print dialogue opens. For a PDF, choose “Save as PDF”.',
        'alphaTitle': 'Alphabet of {name}', 'alphaDesc': 'Alphabet with {n} signs: {list}.',
        'textSvgTitle': 'Text in {name}', 'textSvgDesc': 'Text “{s}”, which means “{free}”.',
        'printSub': '{c} consonants, {v} vowels, {s} signs and {w} words.', 'printPatterns': 'Syllable patterns: {p}.',
        'sumHead': 'Language “{name}”. Part: {sec}.', 'sumSounds': 'Sounds: {c} consonants and {v} vowels ({list}).',
        'sumSigns': 'Signs drawn: {n} of {goal}.', 'sumWords': 'Dictionary: {n} of {goal} words.',
        'sumGrammar': 'Order {o}; adjective {a}.', 'sumText': 'Sentence: “{s}”, which means “{free}”.',
        'stSecret': 'Secret language with 20 signs', 'stSecretD': 'Simple sounds and one sign for each. Get to 20.',
        'stFantasy': 'Language of a fantasy world', 'stFantasyD': 'Plenty of sounds, generated words and VSO order. Get to 100 words.',
        'stFull': 'Complete system with sound changes', 'stFullD': 'A big inventory, SOV order and two change rules ready to try.',
        'stTranslate': 'Translate a short text', 'stTranslateD': 'A small lexicon and an example sentence with its gloss.',
        'nameSecret': 'Secret tongue', 'nameFantasy': 'Forest tongue', 'nameFull': 'Old tongue', 'nameTranslate': 'First tongue',
        'exFree': 'The child sees the water',
    },
}

for _l in ('es', 'en'):
    STRINGS[_l].update(_sound_keys(_l))

assert set(STRINGS['es']) == set(STRINGS['en'])
assert set(PAGE['es']) == set(PAGE['en'])
