"""Textos comunes del lienzo vectorial (Cómic y Diseño gráfico), ES/EN."""

STRINGS = {
    'es': {
        'canvasLabel': 'Lienzo de la página',
        'canvasHelp': 'Las flechas mueven un cursor 10 px (50 con Mayús) y dicen qué hay debajo. Con Elegir, Intro elige el objeto bajo el cursor; con otra herramienta, Intro lo crea ahí. Con un objeto elegido, las flechas lo mueven, R lo gira 15°, Ctrl + D lo duplica, Supr lo borra y Esc lo suelta. Tab lleva a las asas de tamaño y de la cola del bocadillo.',
        'kLienzoCursor': 'En el lienzo: flechas para el cursor; Intro para elegir o crear',
        'kLienzoObj': 'Con un objeto elegido: flechas para moverlo, R para girarlo, Ctrl/Cmd + D para duplicarlo',
        'toolSelect': 'Elegir', 'toolPan': 'Mover la vista', 'fitView': 'Ver la página entera',
        'tool_text': 'Texto', 'tool_rect': 'Rectángulo', 'tool_ellipse': 'Elipse', 'tool_line': 'Línea', 'tool_pen': 'Lápiz', 'tool_panel': 'Viñeta', 'tool_balloon': 'Bocadillo', 'tool_image': 'Imagen…',
        'type_text': 'Texto', 'type_rect': 'Rectángulo', 'type_ellipse': 'Elipse', 'type_line': 'Línea', 'type_pen': 'Trazo', 'type_image': 'Imagen', 'type_panel': 'Viñeta', 'type_balloon': 'Bocadillo',
        'kind_speech': 'habla', 'kind_thought': 'pensamiento', 'kind_shout': 'grito', 'kind_caption': 'cartela',
        'font_atkinson': 'Atkinson Hyperlegible (muy legible)', 'font_bricolage': 'Bricolage Grotesque (títulos)', 'font_newsreader': 'Newsreader (con remates)', 'font_mono': 'JetBrains Mono (monoespaciada)',
        'handle_nw': 'Asa superior izquierda', 'handle_ne': 'Asa superior derecha', 'handle_se': 'Asa inferior derecha', 'handle_sw': 'Asa inferior izquierda',
        'handle_start': 'Inicio de la línea', 'handle_end': 'Final de la línea', 'handle_tail': 'Punta de la cola del bocadillo', 'handleHelp': 'Flechas para moverla; Mayús, más rápido',
        'newText': 'Escribe aquí', 'newBalloon': '¡Hola!',
        'added': 'Añadido: {what}', 'deleted': 'Borrado: {what}', 'duplicated': 'Duplicado', 'moved': 'Movido', 'resized': 'Tamaño cambiado', 'rotated': 'Girado',
        'reordered': 'Orden cambiado', 'changed': 'Cambiado', 'textChanged': 'Texto cambiado', 'colourChanged': 'Color cambiado',
        'selected': 'Elegido: {what}', 'deselected': 'Nada elegido.', 'nothingHere': 'Aquí no hay nada.', 'cursorAt': 'Cursor en x {x}, y {y}',
        'posSize': 'en x {x}, y {y}, de {w} × {h} px',
        'layers': 'Capas', 'layersHelp': 'La de arriba de la lista se ve por encima de las demás.', 'pages': 'Páginas', 'pageN': 'Página {n}', 'nObjects': '{n} objetos',
        'addPage': 'Nueva página', 'dupPage': 'Duplicar página', 'delPage': 'Borrar página', 'pageAdded': 'Página añadida', 'pageDeleted': 'Página borrada', 'lastPage': 'Tiene que quedar al menos una página.',
        'textLabel': 'Texto', 'balloonKind': 'Tipo de bocadillo', 'font': 'Letra', 'size': 'Tamaño de letra', 'bold': 'Negrita',
        'align': 'Alineación', 'alignLeft': 'Izquierda', 'alignCenter': 'Centro', 'alignRight': 'Derecha',
        'textColour': 'Color del texto', 'boxColour': 'Fondo del texto', 'fillColour': 'Relleno', 'strokeColour': 'Borde', 'strokeWidth': 'Grosor del borde', 'radius': 'Esquinas redondeadas',
        'arrow': 'Con flecha', 'tailPos': 'Punta de la cola', 'noColour': 'Sin color', 'colourHex': 'Color {hex}', 'customColour': 'Otro color',
        'contrastLabel': 'Contraste {cr}:1.', 'contrastOk': 'Se lee bien (mínimo {need}:1).', 'contrastBad': 'Poco contraste: hace falta al menos {need}:1.',
        'altText': 'Descripción de la imagen', 'altHelp': 'Escribe qué muestra la imagen, para quien no la ve. Va dentro del SVG.',
        'fit': 'Ajuste', 'fitCover': 'Llenar el recuadro', 'fitContain': 'Imagen entera',
        'imageTooBig': 'La imagen pesa más de 20 MB.', 'imageError': 'No se ha podido abrir esa imagen.',
        'position': 'Posición y tamaño', 'width': 'Ancho', 'height': 'Alto', 'rotation': 'Giro', 'opacity': 'Opacidad',
        'centerH': 'Centrar', 'toFront': 'Al frente', 'toBack': 'Al fondo', 'duplicate': 'Duplicar', 'deleteBtn': 'Borrar',
        'pageSettings': 'Página', 'format': 'Formato', 'formatChanged': 'Formato cambiado', 'pageColour': 'Color de la página',
        'penSettings': 'Lápiz', 'penColour': 'Color del lápiz', 'penWidth': 'Grosor del lápiz',
        'reviewTitle': 'Revisión de lectura', 'reviewEmpty': 'Añade textos para revisar su lectura.', 'reviewOk': 'Todos los textos se leen bien', 'reviewBad': 'Puntos que revisar: {n}',
        'okWord': 'Bien', 'checkWord': 'Revisar',
        'revContrastOk': '{name}: contraste {cr}:1 (mínimo {need}:1).', 'revContrastBad': '{name}: contraste {cr}:1; hace falta al menos {need}:1.',
        'revOverImage': '{name}: está sobre una imagen; comprueba a ojo que se lee bien o ponle un fondo.',
        'revSmall': '{name}: letra de {size} px; para este formato conviene al menos {min} px.',
        'revLong': '{name}: una frase tiene {n} palabras. Las frases cortas se entienden mejor.', 'revAlt': 'Hay una imagen sin descripción.',
        'reviewNote': 'Basado en WCAG 2.2 (contraste 1.4.3: 4,5:1, o 3:1 para letra grande) y en pautas de lenguaje claro (ISO 24495-1).',
        'summary': 'Página {page} de {pages}, de {w} × {h} px, con {n} objetos.',
        'exportPng': 'Exportar imagen (PNG)', 'exportPngPrint': 'Exportar para imprimir (PNG a 3×)', 'exportSvg': 'Exportar vectorial (SVG)', 'exportZip': 'Exportar todas las páginas (ZIP de PNG)',
        'pageFile': 'pagina-{n}', 'zipDone': '{n} páginas en el archivo ZIP',
    },
    'en': {
        'canvasLabel': 'Page canvas',
        'canvasHelp': 'The arrow keys move a cursor 10 px (50 with Shift) and say what is underneath. With Select, Enter selects the object under the cursor; with another tool, Enter creates it there. With an object selected, the arrow keys move it, R rotates it 15°, Ctrl + D duplicates it, Delete removes it and Esc lets go. Tab takes you to the size handles and the balloon tail.',
        'kLienzoCursor': 'On the canvas: arrow keys for the cursor; Enter to select or create',
        'kLienzoObj': 'With an object selected: arrow keys to move it, R to rotate it, Ctrl/Cmd + D to duplicate it',
        'toolSelect': 'Select', 'toolPan': 'Move the view', 'fitView': 'Show whole page',
        'tool_text': 'Text', 'tool_rect': 'Rectangle', 'tool_ellipse': 'Ellipse', 'tool_line': 'Line', 'tool_pen': 'Pencil', 'tool_panel': 'Panel', 'tool_balloon': 'Balloon', 'tool_image': 'Image…',
        'type_text': 'Text', 'type_rect': 'Rectangle', 'type_ellipse': 'Ellipse', 'type_line': 'Line', 'type_pen': 'Stroke', 'type_image': 'Image', 'type_panel': 'Panel', 'type_balloon': 'Balloon',
        'kind_speech': 'speech', 'kind_thought': 'thought', 'kind_shout': 'shout', 'kind_caption': 'caption',
        'font_atkinson': 'Atkinson Hyperlegible (very legible)', 'font_bricolage': 'Bricolage Grotesque (headings)', 'font_newsreader': 'Newsreader (serif)', 'font_mono': 'JetBrains Mono (monospace)',
        'handle_nw': 'Top left handle', 'handle_ne': 'Top right handle', 'handle_se': 'Bottom right handle', 'handle_sw': 'Bottom left handle',
        'handle_start': 'Start of the line', 'handle_end': 'End of the line', 'handle_tail': 'Tip of the balloon tail', 'handleHelp': 'Arrow keys to move it; Shift, faster',
        'newText': 'Type here', 'newBalloon': 'Hello!',
        'added': 'Added: {what}', 'deleted': 'Deleted: {what}', 'duplicated': 'Duplicated', 'moved': 'Moved', 'resized': 'Size changed', 'rotated': 'Rotated',
        'reordered': 'Order changed', 'changed': 'Changed', 'textChanged': 'Text changed', 'colourChanged': 'Colour changed',
        'selected': 'Selected: {what}', 'deselected': 'Nothing selected.', 'nothingHere': 'There is nothing here.', 'cursorAt': 'Cursor at x {x}, y {y}',
        'posSize': 'at x {x}, y {y}, {w} × {h} px',
        'layers': 'Layers', 'layersHelp': 'The one at the top of the list is shown above the others.', 'pages': 'Pages', 'pageN': 'Page {n}', 'nObjects': '{n} objects',
        'addPage': 'New page', 'dupPage': 'Duplicate page', 'delPage': 'Delete page', 'pageAdded': 'Page added', 'pageDeleted': 'Page deleted', 'lastPage': 'At least one page must remain.',
        'textLabel': 'Text', 'balloonKind': 'Balloon type', 'font': 'Typeface', 'size': 'Text size', 'bold': 'Bold',
        'align': 'Alignment', 'alignLeft': 'Left', 'alignCenter': 'Centre', 'alignRight': 'Right',
        'textColour': 'Text colour', 'boxColour': 'Text background', 'fillColour': 'Fill', 'strokeColour': 'Outline', 'strokeWidth': 'Outline width', 'radius': 'Rounded corners',
        'arrow': 'With arrow', 'tailPos': 'Tail tip', 'noColour': 'No colour', 'colourHex': 'Colour {hex}', 'customColour': 'Other colour',
        'contrastLabel': 'Contrast {cr}:1.', 'contrastOk': 'Easy to read (minimum {need}:1).', 'contrastBad': 'Low contrast: at least {need}:1 is needed.',
        'altText': 'Image description', 'altHelp': 'Write what the image shows, for people who cannot see it. It goes inside the SVG.',
        'fit': 'Fit', 'fitCover': 'Fill the box', 'fitContain': 'Whole image',
        'imageTooBig': 'The image is larger than 20 MB.', 'imageError': 'That image could not be opened.',
        'position': 'Position and size', 'width': 'Width', 'height': 'Height', 'rotation': 'Rotation', 'opacity': 'Opacity',
        'centerH': 'Centre', 'toFront': 'To front', 'toBack': 'To back', 'duplicate': 'Duplicate', 'deleteBtn': 'Delete',
        'pageSettings': 'Page', 'format': 'Format', 'formatChanged': 'Format changed', 'pageColour': 'Page colour',
        'penSettings': 'Pencil', 'penColour': 'Pencil colour', 'penWidth': 'Pencil width',
        'reviewTitle': 'Readability check', 'reviewEmpty': 'Add text to check how it reads.', 'reviewOk': 'All text is easy to read', 'reviewBad': 'Points to look at: {n}',
        'okWord': 'Fine', 'checkWord': 'Look at',
        'revContrastOk': '{name}: contrast {cr}:1 (minimum {need}:1).', 'revContrastBad': '{name}: contrast {cr}:1; at least {need}:1 is needed.',
        'revOverImage': '{name}: it is on top of an image; check by eye that it reads well, or give it a background.',
        'revSmall': '{name}: {size} px text; for this format at least {min} px is advisable.',
        'revLong': '{name}: one sentence has {n} words. Short sentences are easier to understand.', 'revAlt': 'There is an image with no description.',
        'reviewNote': 'Based on WCAG 2.2 (contrast 1.4.3: 4.5:1, or 3:1 for large text) and plain-language guidance (ISO 24495-1).',
        'summary': 'Page {page} of {pages}, {w} × {h} px, with {n} objects.',
        'exportPng': 'Export image (PNG)', 'exportPngPrint': 'Export for print (PNG at 3×)', 'exportSvg': 'Export vector (SVG)', 'exportZip': 'Export all pages (ZIP of PNGs)',
        'pageFile': 'page-{n}', 'zipDone': '{n} pages in the ZIP file',
    },
}
assert set(STRINGS['es']) == set(STRINGS['en'])
