# -*- coding: utf-8 -*-
"""Texto editorial de la matriz visual 27/27 (R54).

ANTES: qué había en R47, tal y como lo describió la auditoría de Astra.
ELEMENTOS: qué tiene la escena nueva.
PORQUE: por qué esa escena representa a ese estudio y no a otro.
"""

ANTES = {
    'dibujo': 'Un trazo, un lápiz y un círculo: icono ampliado',
    'diseno-grafico': 'Rectángulo con un círculo y dos barras de texto',
    'pixel-art': 'Una rejilla con un corazón de píxeles',
    'comic': 'Tres rectángulos vacíos con dos caras y una estrella',
    'color': 'Una rueda de seis sectores, sola',
    'patrones': 'Triángulos repetidos sobre fondo liso',
    'fotografia': 'Silueta de cámara con un círculo',
    'moda-textil': 'Una camiseta plana con rayas',
    'estructuras': 'Un puente reducido a pocas líneas',
    'arquitectura': 'Un rectángulo dividido con dos manchas de color',
    'modelado-3d': 'Un cubo aislado en perspectiva',
    'maquinas': 'Dos engranajes dentados, sin contexto',
    'circuitos': 'Un rectángulo con una pila y una bombilla',
    'papiroflexia': 'Seis cuadrados en cruz y un romboide',
    'simulaciones': 'Ocho puntos con una raya cada uno',
    'ritmo': 'Cuadrícula de celdas y una línea roja',
    'composicion': 'Un teclado de ocho teclas y seis barras',
    'sintesis-sonido': 'Una onda y una señal cuadrada',
    'videomapping': 'Un trapecio de luz y tres rombos',
    'programacion': 'Cuatro bloques rectangulares apilados',
    'robotica': 'Una caja con dos ojos sobre una curva',
    'videojuegos': 'Suelo verde, dos barras y tres círculos',
    'escritura-restricciones': 'Cinco rayas y una letra tachada',
    'mundos': 'Una mancha verde con dos triángulos',
    'lenguas-inventadas': 'Un bocadillo con cuatro garabatos',
    'juegos-de-mesa': 'Cuadrado con doce casillas y un dado',
    'ideas': 'Una bombilla con rayos',
}

ELEMENTOS = {
    'dibujo': 'Mesa y ventana; lámina con un pájaro a medio dibujar sobre su línea de construcción; bote de lápices; lápiz apoyado en el trazo que sigue, con su contorno punteado',
    'diseno-grafico': 'Cartel a medio maquetar con rejilla de columnas, titular, foto interior y guías; abanico de fichas de color; regla; un bloque de titular bajando a su hueco',
    'pixel-art': 'Pantalla de trabajo con un gato dibujado celda a celda sobre hierba y una esquina sin pintar; tira de tres fotogramas; paleta limitada; estilete sobre el píxel activo',
    'comic': 'Página con cuatro viñetas de marco grueso y tamaños distintos, con paisaje, primer plano y bocadillos; la última viñeta vacía y punteada; guion gráfico al lado; rotulador',
    'color': 'Rueda de doce sectores con el selector marcado; paleta en formación con sus etiquetas de contraste; escena de ejemplo pintada con esos colores; gota de color en camino',
    'patrones': 'Mosaico de doce celdas con el motivo girado; celda fundamental marcada con escuadras; una celda a medio hacer; el motivo suelto grande que lo genera todo',
    'fotografia': 'Copia fotográfica con paisaje; rectángulo de recorte con asas y rejilla de tercios; encuadre anterior punteado; histograma; cámara apoyada',
    'moda-textil': 'Muestras de color tendidas; camiseta colgada con su estampado; rollo de tela con el mismo motivo; patrón recortado con su costura punteada; carrete e hilo enhebrado',
    'estructuras': 'Río, pilares y tablero; celosía triangulada; camión cruzando; flechas de carga; una barra todavía en el aire bajando a su hueco punteado',
    'arquitectura': 'Papel de plano con la planta (muros, puertas con su arco, cotas y muebles); tabique que falta en punteado; escalímetro; la misma casa levantada en volumen, unida al plano',
    'modelado-3d': 'Visor con rejilla en perspectiva; una taza con volumen real y tres caras de luz; vértices seleccionados; asa sin aplicar en punteado; ejes de manipulación; cubo de vista',
    'maquinas': 'Tren de tres engranajes engranados con sus sentidos de giro; hueco del cuarto y el engranaje entrando; polea con cuerda y peso; palanca con su apoyo',
    'circuitos': 'Placa con rejilla; circuito cerrado con pila, interruptor, resistencia y bombilla encendida; chip soldado; componente bajando a su hueco; puerta lógica',
    'papiroflexia': 'Icosaedro con caras de color y sombra; su red desplegada con pliegues de valle y monte y pestañas; triángulo a medio plegar; leyenda de pliegues; pila de papeles',
    'simulaciones': 'Panel del autómata con un planeador y un oscilador vivos; célula cayendo a su casilla; gráfico de dos poblaciones que se cruzan; mandos de parámetros',
    'ritmo': 'Secuenciador de ocho por cuatro con doce casillas encendidas; línea de reproducción con su cabezal; batería al lado (bombo, caja y platillo) con marcas de que acaba de sonar',
    'composicion': 'Teclado vertical con teclas pulsadas y sus ondas; melodía de siete notas que sube y baja; dos acordes enmarcados; el hueco de la nota siguiente',
    'sintesis-sonido': 'Osciloscopio con la onda grande; envolvente con sus tiradores y su versión anterior en punteado; pantalla del filtro; tres mandos y un fader',
    'videomapping': 'Sala en penumbra; proyector con su cono de luz; tres cajas apiladas con dibujo geométrico encajado en las caras; cuadrilátero de ajuste con una esquina descolocada',
    'programacion': 'Pantalla con el escenario, el camino y un robot avanzando hacia la meta; pila de bloques encajados; el bloque siguiente bajando a su hueco punteado',
    'robotica': 'Suelo de taller con la línea pintada; robot de dos ruedas con sensores y sus conos; obstáculo por delante; traza punteada del recorrido ya hecho',
    'videojuegos': 'Nivel completo: cielo, colinas, suelo de baldosas, dos plataformas, personaje en pleno salto con su arco, monedas, bandera de meta y un enemigo',
    'escritura-restricciones': 'Cuaderno de anillas con el texto a medio escribir, huecos de palabra y marcas de revisión; pluma parada donde se corta; ficha de la letra prohibida; contador',
    'mundos': 'Mapa de un continente inventado con costa, cordillera, bosque y río; marcadores con nombres; rosa de los vientos; fichas de criatura, cultura y calendario unidas por hilos',
    'lenguas-inventadas': 'Hoja con doce signos inventados y la casilla que falta; pluma trazando el siguiente; frase escrita con esos signos y su glosa; tabla de sonidos a medio rellenar',
    'juegos-de-mesa': 'Tablero de recorrido en S con casillas especiales; fichas de dos colores repartidas; una ficha levantada sobre su casilla; mazo con dos cartas; dado recién tirado',
    'ideas': 'Tablero con cuatro notas unidas por hilos y flechas; una nota con el boceto del invento; hueco esperando y una nota entrando; ficha del invento con sus casillas',
}

PORQUE = {
    'dibujo': 'Se ve el gesto de dibujar: una obra empezada, la línea de construcción debajo y la herramienta donde sigue el trazo',
    'diseno-grafico': 'Lo propio del estudio es colocar: hay rejilla, jerarquía y un elemento buscando su sitio',
    'pixel-art': 'Solo el pixel art se hace celda a celda con pocos colores y se anima por fotogramas: están las tres cosas',
    'comic': 'La página con viñetas de distinto tamaño y bocadillos es exclusiva del cómic, y la viñeta vacía muestra que la historia continúa',
    'color': 'No es una rueda decorativa: se ve elegir un color, llevarlo a una paleta y comprobar que funciona en una escena',
    'patrones': 'Enseña la relación entre una pieza y su repetición, que es justo lo que se aprende aquí',
    'fotografia': 'El estudio no hace fotos: encuadra y corrige luz, y eso es lo que se ve (recorte, tercios e histograma)',
    'moda-textil': 'El motivo aparece creado una vez y repetido dos, en prenda y en tela, más el patrón que lleva al objeto real',
    'estructuras': 'La triangulación, la carga y la pieza que falta cuentan que aquí se construye y se pone a prueba',
    'arquitectura': 'Plano y volumen en la misma imagen: el estudio es exactamente ese ida y vuelta',
    'modelado-3d': 'Un objeto con volumen, caras de luz distintas y ejes de manipulación: se modela, no se ve un cubo',
    'maquinas': 'El movimiento se sigue de pieza en pieza: engranajes, polea y palanca, los tres mecanismos del estudio',
    'circuitos': 'La bombilla encendida prueba que el circuito está cerrado; la puerta lógica anuncia la otra mitad del estudio',
    'papiroflexia': 'El paso de plano a cuerpo es la idea entera: el sólido, su red y un triángulo a medio plegar',
    'simulaciones': 'Un sistema corriendo y sus datos al lado: reglas que producen comportamiento',
    'ritmo': 'La rejilla sola sería un icono; con los instrumentos y el cabezal se ve que eso suena y cuándo',
    'composicion': 'Manda la altura de las notas y el teclado, no la rejilla de tiempo: por eso no se confunde con Ritmo',
    'sintesis-sonido': 'Aquí el sonido se esculpe: onda, envolvente, filtro y mandos, no un instrumento que se toca',
    'videomapping': 'La luz encajando en las caras reales de unas cajas es lo único que distingue al videomapping',
    'programacion': 'Muestra la relación causa y efecto: los bloques a la izquierda, lo que hacen a la derecha',
    'robotica': 'Sensores mirando la línea, obstáculo y traza recorrida: el bucle de sensor, decisión y motor',
    'videojuegos': 'Un nivel se entiende de un vistazo: personaje, obstáculo, recompensa y meta',
    'escritura-restricciones': 'No es escribir: es escribir bajo una regla, y la regla está a la vista con su contador',
    'mundos': 'Mapa, criatura, cultura y calendario enlazados: un universo propio, no solo un mapa',
    'lenguas-inventadas': 'Inventar un sistema de escritura y usarlo: los signos, la frase escrita con ellos y su glosa',
    'juegos-de-mesa': 'Una partida ya empezada, con recorrido, cartas y azar: el juego existe, no es una plantilla',
    'ideas': 'Pensar en voz alta y quedarse con una: notas conectadas y una que ya ha pasado a ficha',
}

assert set(ANTES) == set(ELEMENTOS) == set(PORQUE), 'las tres tablas deben cubrir los mismos estudios'
