"""Estudio de modelado 3D (R43): formas sólidas y huecos, CSG, exportación STL/GLB/OBJ. Textos ES/EN."""

ENGINE = 'modelado3d'
SLUG = {'es': 'modelado-3d', 'en': '3d-modelling'}
SCRIPTS = ['ig-suite-3d.js', 'ig-suite-modelado3d.js']
LIBRARIES = 'Three.js (MIT) con WebGPU o WebGL 2 y three-bvh-csg (MIT)'
LIBRARIES_EN = 'Three.js (MIT) with WebGPU or WebGL 2 and three-bvh-csg (MIT)'

PAGE = {
    'es': {
        'title': 'Modelado 3D',
        'description': 'Diseña objetos en 3D con formas sólidas y huecos, en milímetros, sobre una cama de impresión. Exporta STL para imprimir, GLB para la web u OBJ.',
        'lede': 'Construye objetos juntando formas: cubos, esferas, cilindros, conos, pirámides, anillos y cuñas. Una forma puede ser sólida o un hueco que perfora a las demás. Todo se mide en milímetros, listo para imprimir en 3D.',
        'make': ['Un llavero con tu inicial o un dibujo', 'Un soporte para el móvil', 'Una caja con tapa que encaja', 'Piezas de repuesto, maquetas y prototipos', 'Archivos STL para imprimir, GLB para la web y OBJ para otros programas'],
        'steps': [
            'Elige una forma en la barra y pulsa «Añadir sólido». Aparece sobre la cama de impresión.',
            'Toca una forma para elegirla. Con las flechas de colores del modelo la mueves; con «Girar» y «Escalar» cambias su giro y su tamaño. También puedes escribir las medidas en Propiedades.',
            'Para hacer un agujero, añade un hueco y colócalo donde quieras quitar material.',
            'Elige varias formas (Mayús + toque, o Mayús + clic en la lista) y pulsa «Agrupar»: los sólidos se unen y los huecos perforan.',
            'Revisa el apartado «Antes de imprimir» y exporta en Archivo: STL para la impresora, GLB para la web u OBJ.',
        ],
        'sections': [
            {'h': 'Sólidos y huecos', 'p': 'Un sólido añade material. Un hueco lo quita. Al agrupar, el estudio une todos los sólidos y resta los huecos: así se hace el agujero de un llavero o el interior de una caja. El grupo se puede desagrupar para volver a cambiar las piezas.'},
            {'h': 'Medidas y cama de impresión', 'p': 'La cuadrícula es una cama de impresión de 200 × 200 mm con líneas cada 10 mm. Las flechas del teclado mueven 1 mm (10 mm con Mayús). «Apoyar en la cama» baja la forma hasta que toca la base: lo que flota en el aire no se puede imprimir sin soportes.'},
            {'h': 'Qué archivo elegir', 'p': 'STL es el formato de las impresoras 3D: solo guarda la forma, sin color, y aquí se exporta con el eje Z hacia arriba, como esperan los programas de impresión. GLB guarda forma y color y se abre en visores web y en programas 3D. OBJ es un formato de texto que casi cualquier programa entiende. Los huecos sueltos no se exportan.'},
            {'h': 'Cómo funciona por dentro', 'p': 'El dibujo usa WebGPU cuando el navegador lo ofrece y, si no, WebGL 2, sin que tengas que hacer nada. Las uniones y restas de formas se calculan con geometría sólida constructiva (CSG). Solo se dibuja cuando algo cambia, para gastar menos batería.'},
        ],
        'links': [('Todo el taller', '/es/taller/'), ('Estructuras', '/es/taller/estructuras/'), ('Diseño gráfico', '/es/taller/diseno-grafico/')],
    },
    'en': {
        'title': '3D modelling',
        'description': 'Design 3D objects from solid shapes and holes, in millimetres, on a print bed. Export STL to print, GLB for the web or OBJ.',
        'lede': 'Build objects by putting shapes together: cubes, spheres, cylinders, cones, pyramids, rings and wedges. A shape can be solid or a hole that cuts through the others. Everything is measured in millimetres, ready for 3D printing.',
        'make': ['A keyring with your initial or a drawing', 'A phone stand', 'A box with a lid that fits', 'Spare parts, scale models and prototypes', 'STL files to print, GLB for the web and OBJ for other programs'],
        'steps': [
            'Choose a shape in the toolbar and press “Add solid”. It appears on the print bed.',
            'Tap a shape to select it. The coloured arrows on the model move it; “Rotate” and “Scale” change its angle and size. You can also type the measurements in Properties.',
            'To make a hole, add a hole shape and place it where you want to remove material.',
            'Select several shapes (Shift + tap, or Shift + click in the list) and press “Group”: solids join together and holes cut through.',
            'Check the “Before printing” section and export from File: STL for the printer, GLB for the web or OBJ.',
        ],
        'sections': [
            {'h': 'Solids and holes', 'p': 'A solid adds material. A hole takes it away. When you group, the studio joins all the solids and subtracts the holes: that is how you make the hole in a keyring or the inside of a box. You can ungroup a group to change the pieces again.'},
            {'h': 'Measurements and print bed', 'p': 'The grid is a 200 × 200 mm print bed with lines every 10 mm. The arrow keys move 1 mm (10 mm with Shift). “Drop to bed” lowers the shape until it touches the base: anything floating in the air cannot be printed without supports.'},
            {'h': 'Which file to choose', 'p': 'STL is the format for 3D printers: it only stores the shape, not the colour, and here it is exported with the Z axis pointing up, as slicing programs expect. GLB stores shape and colour and opens in web viewers and 3D programs. OBJ is a text format that almost any program understands. Loose holes are not exported.'},
            {'h': 'How it works inside', 'p': 'Drawing uses WebGPU when the browser offers it and WebGL 2 otherwise, without you having to do anything. Joining and subtracting shapes is calculated with constructive solid geometry (CSG). It only redraws when something changes, to use less battery.'},
        ],
        'links': [('The whole workshop', '/en/workshop/'), ('Structures', '/en/workshop/structures/'), ('Graphic design', '/en/workshop/graphic-design/')],
    },
}

STRINGS = {
    'es': {
        'canvasLabel': 'Vista 3D del modelo',
        'canvasHelp': 'Sin nada elegido, las flechas giran la cámara, + y − acercan y alejan, y 0 vuelve a la vista inicial. Con una forma elegida, las flechas la mueven 1 mm (10 con Mayús), Re Pág y Av Pág la suben y bajan, R la gira 15°, Ctrl + D la duplica, Supr la borra y Esc deja de elegirla.',
        'k3dMove': 'Con una forma elegida: flechas y Re Pág/Av Pág para moverla; R para girarla; Ctrl/Cmd + D para duplicarla',
        'k3dView': 'Sin nada elegido: flechas para girar la cámara; + y − para acercar; 0 para la vista inicial',
        'stKey': 'Llavero', 'stKeyD': 'Una placa redondeada con un agujero para la anilla. Agrúpala para perforarla.',
        'stRocket': 'Cohete', 'stRocketD': 'Cuerpo, punta, aletas y una ventana. Cambia colores y medidas.',
        'stStand': 'Soporte para el móvil', 'stStandD': 'Base, respaldo inclinado, tope y un hueco para el cable.',
        'stBox': 'Caja con tapa', 'stBoxD': 'Una caja hueca hecha con un grupo y una tapa con reborde que encaja.',
        'kind_box': 'Cubo', 'kind_roundbox': 'Cubo redondeado', 'kind_sphere': 'Esfera', 'kind_cylinder': 'Cilindro', 'kind_cone': 'Cono',
        'kind_pyramid': 'Pirámide', 'kind_torus': 'Anillo', 'kind_wedge': 'Cuña', 'kind_group': 'Grupo',
        'shapeLabel': 'Forma', 'addSolid': 'Añadir sólido', 'addHole': 'Añadir hueco',
        'toolMove': 'Mover', 'toolRotate': 'Girar', 'toolScale': 'Escalar',
        'groupBtn': 'Agrupar', 'ungroupBtn': 'Desagrupar', 'dropToBed': 'Apoyar en la cama', 'duplicateBtn': 'Duplicar', 'deleteBtn': 'Borrar',
        'view_top': 'Vista desde arriba', 'view_front': 'Vista de frente', 'view_iso': 'Vista inicial',
        'holeWord': 'hueco', 'solidWord': 'Sólido', 'groupWord': 'Grupo', 'copyWord': 'copia',
        'selected': 'Elegido: {name}', 'deselected': 'Nada elegido.',
        'describe': '{name}: {w} × {h} × {d} mm, en x {x}, y {y}, z {z}.', 'isHole': 'Es un hueco.',
        'posAnnounce': 'Posición: x {x}, y {y}, z {z} mm',
        'added': 'Añadido: {name}', 'deleted': 'Borrado: {name}', 'duplicated': 'Duplicado', 'renamed': 'Nombre cambiado',
        'transformed': 'Forma cambiada', 'moved3d': 'Forma movida', 'rotated': 'Forma girada', 'resized3d': 'Tamaño cambiado',
        'grouped': 'Agrupadas {n} formas: los sólidos se unen y los huecos perforan.', 'ungrouped': 'Grupo deshecho',
        'needTwo': 'Elige al menos dos formas para agrupar (Mayús + toque).', 'needSolid': 'Un grupo necesita al menos un sólido.',
        'groupError': 'No se ha podido calcular este grupo. Prueba a mover un poco las formas.',
        'dropped': 'Apoyado en la cama', 'nowHole': 'Ahora es un hueco', 'nowSolid': 'Ahora es un sólido', 'colourSet': 'Color cambiado',
        'objects': 'Formas', 'multiHelp': 'Mayús + clic para elegir varias.',
        'name': 'Nombre', 'solidOrHole': 'Tipo', 'colour': 'Color',
        'sizeMm': 'Tamaño (mm)', 'size_x': 'Ancho', 'size_y': 'Alto', 'size_z': 'Fondo',
        'positionMm': 'Posición (mm)', 'pos_x': 'Izquierda – derecha', 'pos_y': 'Altura', 'pos_z': 'Delante – detrás',
        'rotationDeg': 'Giro (grados)', 'rot_x': 'Giro hacia delante', 'rot_y': 'Giro sobre sí', 'rot_z': 'Giro de lado',
        'groupHelp': 'Este grupo tiene {n} piezas. Para cambiarlas, pulsa Desagrupar.',
        'nSelected': '{n} formas elegidas', 'groupExplain': 'Al agrupar, los sólidos se unen en una sola pieza y los huecos perforan.',
        'printCheck': 'Antes de imprimir', 'printOk': 'Listo para imprimir', 'printOkText': 'Todo está sobre la cama y nada flota.',
        'printWarn': 'Revisa esto',
        'offBed': 'Se sale de la cama: {names}.', 'floating': 'Flota en el aire (usa «Apoyar en la cama» o agrúpalo con algo apoyado): {names}.',
        'offBedShort': '{n} fuera de la cama', 'bedLabel': 'Cama 200 × 200 mm',
        'emptyModel': 'El modelo está vacío. Elige una forma y pulsa Añadir sólido.',
        'exportStl': 'Exportar para imprimir (STL)', 'exportGlb': 'Exportar para la web (GLB)', 'exportObj': 'Exportar para otros programas (OBJ)', 'exportPng': 'Exportar imagen (PNG)',
        'nothingToExport': 'No hay ningún sólido que exportar.', 'exportError': 'No se ha podido exportar. Inténtalo de nuevo.',
        'exBase': 'Placa', 'exRing': 'Agujero de la anilla', 'exDome': 'Botón', 'exBase2': 'Base', 'exBack': 'Respaldo', 'exLip': 'Tope',
        'exCable': 'Paso del cable', 'exHollow': 'Caja', 'exOuter': 'Exterior', 'exInner': 'Interior', 'exLid': 'Tapa', 'exLidLip': 'Reborde de la tapa',
        'exBody': 'Cuerpo', 'exNose': 'Punta', 'exFin': 'Aleta', 'exWindow': 'Ventana',
    },
    'en': {
        'canvasLabel': '3D view of the model',
        'canvasHelp': 'With nothing selected, the arrow keys orbit the camera, + and − zoom in and out, and 0 returns to the starting view. With a shape selected, the arrow keys move it 1 mm (10 with Shift), Page Up and Page Down raise and lower it, R rotates it 15°, Ctrl + D duplicates it, Delete removes it and Esc deselects it.',
        'k3dMove': 'With a shape selected: arrows and Page Up/Page Down to move it; R to rotate it; Ctrl/Cmd + D to duplicate it',
        'k3dView': 'With nothing selected: arrows to orbit the camera; + and − to zoom; 0 for the starting view',
        'stKey': 'Keyring', 'stKeyD': 'A rounded plate with a hole for the ring. Group it to cut the hole.',
        'stRocket': 'Rocket', 'stRocketD': 'Body, nose, fins and a window. Change colours and sizes.',
        'stStand': 'Phone stand', 'stStandD': 'Base, sloping back, lip and a gap for the cable.',
        'stBox': 'Box with lid', 'stBoxD': 'A hollow box made with a group and a lid with a rim that fits.',
        'kind_box': 'Cube', 'kind_roundbox': 'Rounded cube', 'kind_sphere': 'Sphere', 'kind_cylinder': 'Cylinder', 'kind_cone': 'Cone',
        'kind_pyramid': 'Pyramid', 'kind_torus': 'Ring', 'kind_wedge': 'Wedge', 'kind_group': 'Group',
        'shapeLabel': 'Shape', 'addSolid': 'Add solid', 'addHole': 'Add hole',
        'toolMove': 'Move', 'toolRotate': 'Rotate', 'toolScale': 'Scale',
        'groupBtn': 'Group', 'ungroupBtn': 'Ungroup', 'dropToBed': 'Drop to bed', 'duplicateBtn': 'Duplicate', 'deleteBtn': 'Delete',
        'view_top': 'View from above', 'view_front': 'Front view', 'view_iso': 'Starting view',
        'holeWord': 'hole', 'solidWord': 'Solid', 'groupWord': 'Group', 'copyWord': 'copy',
        'selected': 'Selected: {name}', 'deselected': 'Nothing selected.',
        'describe': '{name}: {w} × {h} × {d} mm, at x {x}, y {y}, z {z}.', 'isHole': 'It is a hole.',
        'posAnnounce': 'Position: x {x}, y {y}, z {z} mm',
        'added': 'Added: {name}', 'deleted': 'Deleted: {name}', 'duplicated': 'Duplicated', 'renamed': 'Name changed',
        'transformed': 'Shape changed', 'moved3d': 'Shape moved', 'rotated': 'Shape rotated', 'resized3d': 'Size changed',
        'grouped': 'Grouped {n} shapes: solids join together and holes cut through.', 'ungrouped': 'Group undone',
        'needTwo': 'Select at least two shapes to group (Shift + tap).', 'needSolid': 'A group needs at least one solid.',
        'groupError': 'This group could not be calculated. Try moving the shapes a little.',
        'dropped': 'Dropped to the bed', 'nowHole': 'It is now a hole', 'nowSolid': 'It is now a solid', 'colourSet': 'Colour changed',
        'objects': 'Shapes', 'multiHelp': 'Shift + click to select several.',
        'name': 'Name', 'solidOrHole': 'Type', 'colour': 'Colour',
        'sizeMm': 'Size (mm)', 'size_x': 'Width', 'size_y': 'Height', 'size_z': 'Depth',
        'positionMm': 'Position (mm)', 'pos_x': 'Left – right', 'pos_y': 'Height above bed', 'pos_z': 'Front – back',
        'rotationDeg': 'Rotation (degrees)', 'rot_x': 'Tilt forward', 'rot_y': 'Spin', 'rot_z': 'Tilt sideways',
        'groupHelp': 'This group has {n} pieces. To change them, press Ungroup.',
        'nSelected': '{n} shapes selected', 'groupExplain': 'When you group, solids join into a single piece and holes cut through.',
        'printCheck': 'Before printing', 'printOk': 'Ready to print', 'printOkText': 'Everything is on the bed and nothing floats.',
        'printWarn': 'Check this',
        'offBed': 'Goes off the bed: {names}.', 'floating': 'Floating in the air (use “Drop to bed” or group it with something resting on the bed): {names}.',
        'offBedShort': '{n} off the bed', 'bedLabel': 'Bed 200 × 200 mm',
        'emptyModel': 'The model is empty. Choose a shape and press Add solid.',
        'exportStl': 'Export to print (STL)', 'exportGlb': 'Export for the web (GLB)', 'exportObj': 'Export for other programs (OBJ)', 'exportPng': 'Export image (PNG)',
        'nothingToExport': 'There is no solid to export.', 'exportError': 'Could not export. Please try again.',
        'exBase': 'Plate', 'exRing': 'Ring hole', 'exDome': 'Button', 'exBase2': 'Base', 'exBack': 'Back', 'exLip': 'Lip',
        'exCable': 'Cable gap', 'exHollow': 'Box', 'exOuter': 'Outside', 'exInner': 'Inside', 'exLid': 'Lid', 'exLidLip': 'Lid rim',
        'exBody': 'Body', 'exNose': 'Nose', 'exFin': 'Fin', 'exWindow': 'Window',
    },
}
assert set(STRINGS['es']) == set(STRINGS['en'])
