"""Estudio de mundos (R43): mapa de terrenos, especies, culturas con lengua y calendario propio,
historia, personajes y atlas. Textos ES/EN.
Fuente de la explicación de biomas: Whittaker, R. H. (1975). Communities and Ecosystems (2.ª ed.). Nueva York: Macmillan
(diagrama de biomas según temperatura media y precipitación anual)."""

ENGINE = 'mundos'
SLUG = {'es': 'mundos', 'en': 'worlds'}
SCRIPTS = ['ig-suite-mundos.js']
STYLES = ['ig-suite-mundos.css']
LIBRARIES = 'ninguna biblioteca externa: mapa SVG, generador de ruido y atlas propios de Iris Green'
LIBRARIES_EN = 'no outside libraries: Iris Green’s own SVG map, noise generator and atlas'

PAGE = {
    'es': {
        'title': 'Mundos',
        'description': 'Inventa un mundo: dibuja o genera su mapa con semilla y enlaza especies, culturas con calendario propio, historia y personajes. Exporta un atlas accesible.',
        'lede': 'Dibuja un mapa, llénalo de seres vivos, pueblos, fiestas e historias, y comprueba que todo encaja. Al final, tu mundo cabe en un atlas que puedes descargar o imprimir.',
        'make': ['Una isla con sus especies', 'Una cultura con su lengua y su calendario', 'La historia de un reino con sus fechas', 'Personajes y sus relaciones', 'Un atlas en HTML, el mapa en PNG o SVG y una versión para imprimir'],
        'steps': [
            'Pinta terrenos con el Pincel o el Relleno, o pulsa «Generar mapa» para crear una isla, un archipiélago o un continente con una semilla.',
            'Añade ríos con la herramienta Río (toca varias casillas y repite la última para terminar) y lugares con la herramienta Lugar.',
            'En Estructura añade especies, culturas, hechos y personajes. Cada ficha se edita en Propiedades.',
            'Enlaza las fichas: el hábitat son terrenos del mapa, cada cultura tiene calendario y cada hecho lleva fecha de ese calendario.',
            'Cambia de vista (Mapa, Calendario, Historia, Relaciones), mira los retos en Propiedades y exporta el atlas desde Archivo.',
        ],
        'sections': [
            {'h': 'El mapa y sus terrenos', 'p': 'El mapa es una rejilla de casillas hexagonales o cuadradas con ocho terrenos: agua, costa, llanura, bosque, montaña, desierto, hielo y pantano. Cada uno tiene color y textura propias, para distinguirlos aunque no se vean bien los colores. Con el teclado, las flechas mueven el cursor, Intro usa la herramienta y los corchetes cambian de terreno.'},
            {'h': 'Generar con semilla', 'p': 'El generador usa ruido: números al azar suavizados que imitan la forma irregular de costas y montañas. La semilla es el punto de partida de ese azar, así que con la misma semilla sale siempre el mismo mapa.\n\nPara elegir el terreno de cada casilla mira la altura, la temperatura (más fría hacia los bordes, que hacen de polos, y en lo alto) y la humedad. Es la idea con la que los ecólogos ordenan los grandes biomas según la temperatura media y la lluvia anual (Whittaker, 1975). Aquí es una simplificación para inventar, no un modelo del clima.'},
            {'h': 'Fichas enlazadas', 'p': 'Al elegir una especie, el mapa destaca las casillas de su hábitat; si vive en un terreno que no existe en el mapa, la revisión te avisa. Las fechas de la historia usan el calendario de una cultura: sus meses, sus días de la semana y sus fiestas. Las relaciones entre personajes se ven como gráfico y como tabla.'},
            {'h': 'Nombres y retos', 'p': 'El generador de nombres junta sílabas de listas escogidas a mano o de la lengua de cada cultura, con un filtro de palabras malsonantes en español y en inglés. El azar solo actúa cuando pulsas el botón.\n\nLos tres retos están en Propiedades cuando no hay nada elegido: isla con tres especies, cultura con calendario propio y mundo completo con atlas.'},
            {'h': 'Fuentes', 'p': 'Whittaker, R. H. (1975). Communities and Ecosystems (2.ª edición). Nueva York: Macmillan. Incluye el diagrama que relaciona los biomas con la temperatura media y la precipitación anual.'},
        ],
        'links': [('Todo el taller', '/es/taller/'), ('Lenguas inventadas', '/es/taller/lenguas-inventadas/'), ('Juegos de mesa', '/es/taller/juegos-de-mesa/')],
    },
    'en': {
        'title': 'Worlds',
        'description': 'Invent a world: draw or generate its map from a seed and link species, cultures with their own calendar, history and characters. Export an accessible atlas.',
        'lede': 'Draw a map, fill it with living things, peoples, festivals and stories, and check that everything fits together. In the end your world fits into an atlas you can download or print.',
        'make': ['An island with its species', 'A culture with its own language and calendar', 'The history of a kingdom with its dates', 'Characters and how they are related', 'An atlas in HTML, the map as PNG or SVG and a printable version'],
        'steps': [
            'Paint terrain with the Brush or Fill, or press “Generate map” to create an island, an archipelago or a continent from a seed.',
            'Add rivers with the River tool (tap several cells and repeat the last one to finish) and places with the Place tool.',
            'In Structure add species, cultures, events and characters. You edit each entry in Properties.',
            'Link the entries: a habitat is made of map terrain, each culture has a calendar and each event is dated with it.',
            'Switch views (Map, Calendar, History, Relationships), look at the challenges in Properties and export the atlas from File.',
        ],
        'sections': [
            {'h': 'The map and its terrain', 'p': 'The map is a grid of hexagonal or square cells with eight kinds of terrain: water, coast, plain, forest, mountain, desert, ice and marsh. Each has its own colour and texture, so you can tell them apart even if you cannot see the colours well. With the keyboard, the arrow keys move the cursor, Enter uses the tool and the square brackets change terrain.'},
            {'h': 'Generating from a seed', 'p': 'The generator uses noise: smoothed random numbers that imitate the ragged shape of coastlines and mountains. The seed is the starting point for that randomness, so the same seed always gives the same map.\n\nTo choose each cell’s terrain it looks at height, temperature (colder towards the edges, which act as poles, and on high ground) and moisture. It is the idea ecologists use to arrange the major biomes by average temperature and yearly rainfall (Whittaker, 1975). Here it is a simplification for inventing, not a climate model.'},
            {'h': 'Linked entries', 'p': 'When you select a species the map highlights the cells of its habitat; if it lives in terrain that is not on the map, the check tells you. Events in history use a culture’s calendar: its months, its days of the week and its festivals. Relationships between characters are shown as a diagram and as a table.'},
            {'h': 'Names and challenges', 'p': 'The name generator puts together syllables from hand-picked lists or from each culture’s language, with a filter of offensive words in Spanish and English. Randomness only acts when you press the button.\n\nThe three challenges sit in Properties when nothing is selected: an island with three species, a culture with its own calendar, and a complete world with an atlas.'},
            {'h': 'Sources', 'p': 'Whittaker, R. H. (1975). Communities and Ecosystems (2nd edition). New York: Macmillan. It includes the diagram that relates biomes to average temperature and yearly rainfall.'},
        ],
        'links': [('The whole workshop', '/en/workshop/'), ('Invented languages', '/en/workshop/invented-languages/'), ('Board games', '/en/workshop/board-games/')],
    },
}

STRINGS = {
    'es': {
        'canvasLabel': 'Mapa del mundo',
        'canvasHelp': 'En el mapa, las flechas mueven el cursor una casilla (cuatro con Mayús) y leen su terreno. Intro o Espacio usan la herramienta elegida: el Pincel pinta, el Relleno llena la zona, el Río añade un punto (vuelve a pulsar Intro en el último punto para terminar) y Lugar crea un lugar. Con Elegir, Intro elige el lugar del cursor y las flechas lo mueven. [ y ] cambian de terreno; Supr borra; Esc cancela. En las vistas Calendario, Historia y Relaciones, las flechas pasan de una ficha a otra.',
        'kWorldCursor': 'En el mapa: flechas para el cursor; Intro o Espacio para usar la herramienta',
        'kWorldTerrain': '[ y ] para cambiar de terreno; Esc termina un río o suelta la selección',
        'kWorldViews': 'En Calendario, Historia y Relaciones: flechas para pasar de una ficha a otra',
        'stIsland': 'Isla con 3 especies', 'stIslandD': 'Una isla generada con semilla y tres especies con su hábitat en el mapa.',
        'stCalendar': 'Cultura con calendario propio', 'stCalendarD': 'Un pueblo marinero con lengua, ocho meses, semana de seis días, fiestas e historia.',
        'stAtlas': 'Mundo completo con atlas', 'stAtlasD': 'Un continente con lugares, especies, dos culturas, historia y personajes enlazados.',
        'stContinent': 'Continente con semilla', 'stContinentD': 'Un continente generado con ríos y lugares. Cambia la semilla para ver otro.',
        'newWorldName': 'Mundo sin nombre',
        'toolSelect': 'Elegir', 'toolBrush': 'Pincel', 'toolFill': 'Relleno', 'toolRiver': 'Río', 'toolPlace': 'Lugar', 'toolUnriver': 'Quitar río', 'toolPan': 'Mover la vista',
        'terrainLabel': 'Terreno', 'viewLabel': 'Vista', 'generateBtn': 'Generar mapa', 'namesBtn': 'Nombres',
        'view_map': 'Mapa', 'view_calendar': 'Calendario', 'view_timeline': 'Historia', 'view_relations': 'Relaciones',
        'viewNow': 'Vista: {v}', 'viewCmd': 'Ver {v}',
        'terr_water': 'Agua', 'terr_coast': 'Costa', 'terr_plain': 'Llanura', 'terr_forest': 'Bosque', 'terr_mountain': 'Montaña', 'terr_desert': 'Desierto', 'terr_ice': 'Hielo', 'terr_swamp': 'Pantano',
        'legendTex_water': 'azul con olas', 'legendTex_coast': 'arena con puntos', 'legendTex_plain': 'verde claro con matas de hierba', 'legendTex_forest': 'verde con árboles',
        'legendTex_mountain': 'marrón grisáceo con picos', 'legendTex_desert': 'amarillo con rayas diagonales', 'legendTex_ice': 'blanco con cruces', 'legendTex_swamp': 'verde grisáceo con juncos',
        'legendMarkers': 'Lugares: cuadrado, ciudad; círculo, pueblo; círculo con ancla, puerto; triángulo hueco, ruinas; estrella, maravilla.',
        'legend': 'Leyenda',
        'pk_city': 'Ciudad', 'pk_village': 'Pueblo', 'pk_port': 'Puerto', 'pk_ruin': 'Ruinas', 'pk_landmark': 'Maravilla',
        'diet_plants': 'Come plantas', 'diet_meat': 'Come otros animales', 'diet_both': 'Come de todo', 'diet_sun': 'Vive de la luz del sol', 'diet_filter': 'Filtra el agua',
        'size_tiny': 'Diminuto (menos que una mano)', 'size_small': 'Pequeño (como un gato)', 'size_medium': 'Mediano (como una persona)', 'size_large': 'Grande (como un caballo)', 'size_huge': 'Enorme (como una casa)',
        'rel_family': 'familia', 'rel_friend': 'amistad', 'rel_rival': 'rivalidad', 'rel_mentor': 'enseña a', 'rel_ally': 'alianza',
        'shape_hex': 'Hexágonos', 'shape_square': 'Cuadrados',
        'syl_soft': 'Suave', 'syl_stone': 'Pétrea', 'syl_sea': 'Marina', 'syl_bright': 'Luminosa',
        'gen_island': 'Isla', 'gen_archipelago': 'Archipiélago', 'gen_continent': 'Continente',
        'kind_world': 'Mundo', 'kind_place': 'Lugar', 'kind_species': 'Especie', 'kind_culture': 'Cultura', 'kind_event': 'Hecho', 'kind_character': 'Personaje',
        'places': 'Lugares', 'speciesPl': 'Especies', 'cultures': 'Culturas', 'events': 'Historia', 'characters': 'Personajes',
        'add_place': 'Añadir lugar', 'add_species': 'Añadir especie', 'add_culture': 'Añadir cultura', 'add_event': 'Añadir hecho', 'add_character': 'Añadir personaje',
        'addCulture': 'Añadir cultura', 'addEvent': 'Añadir hecho', 'addCharacter': 'Añadir personaje',
        'added': '{kind} añadido: {name}', 'deletedItem': 'Borrado: {name}', 'selectedItem': '{kind}: {name}',
        'renamed': 'Nombre cambiado', 'changedWord': 'Cambiado', 'movedWord': 'Movido', 'newNameIs': 'Nombre nuevo: {name}',
        'monthsN': '{n} meses', 'yearN': 'año {y}',
        'worldTitle': 'Mundo', 'worldName': 'Nombre del mundo', 'challenges': 'Retos', 'done': 'Hecho', 'pending': 'Pendiente', 'yes': 'sí', 'no': 'no',
        'ch1': 'Isla con 3 especies', 'ch1D': 'Tierra rodeada de agua: {island}. Especies con hábitat en el mapa: {n} de 3.',
        'ch2': 'Cultura con calendario propio', 'ch2D': 'Al menos 3 meses, 3 días de la semana y 1 fiesta en una fecha que exista.',
        'ch3': 'Mundo completo con atlas',
        'gPlaces': 'Lugares: {n} de 3', 'gSpecies': 'Especies con hábitat en el mapa: {n} de 3', 'gCalendar': 'Una cultura con calendario completo',
        'gEvents': 'Hechos de la historia: {n} de 3', 'gChars': 'Personajes: {n} de 3', 'gRels': 'Relaciones: {n} de 2', 'gAtlas': 'Atlas exportado o impreso',
        'terrainTitle': 'Terreno para pintar', 'brushSize': 'Tamaño del pincel', 'brush1': '1 casilla', 'brush2': '7 casillas', 'brush3': '19 casillas', 'brushNow': 'Pincel de {n}',
        'terrainNow': 'Terreno: {t}',
        'mapTitle': 'Mapa', 'mapInfo': '{shape}, {w} × {h} casillas. Semilla: {seed}.', 'shapeLabel': 'Forma de las casillas', 'sizeLabel': 'Tamaño del mapa (columnas × filas)',
        'shapeChanged': 'Forma de las casillas cambiada', 'resized': 'Tamaño del mapa cambiado',
        'showTex': 'Texturas en los terrenos', 'showGrid': 'Bordes de las casillas', 'showNames': 'Nombres de los lugares',
        'surfaceCap': 'Superficie de cada terreno', 'colTerrain': 'Terreno', 'colCells': 'Casillas',
        'checksTitle': 'Revisión', 'checksOk': 'Todo encaja: no hay avisos.', 'checksBad': 'Avisos: {n}',
        'chkNoHabitat': '{name}: elige al menos un terreno de hábitat.', 'chkHabitatMissing': '{name} vive en {terr}, pero en el mapa no hay {terr}.',
        'chkNoMonths': '{name}: el calendario necesita al menos un mes.', 'chkMonthName': '{name}: el mes {n} no tiene nombre.', 'chkNoWeek': '{name}: escribe al menos un día de la semana.',
        'chkFeastDay': '{name}: la fiesta «{feast}» cae en un día que no existe en ese mes.', 'chkEventDate': '«{name}»: la fecha no existe en ese calendario.',
        'chkPlaceWater': '{name} está en el agua. ¿Quieres que sea un puerto o moverlo a tierra?',
        'name': 'Nombre', 'otherName': 'Otro nombre', 'description': 'Descripción', 'deleteBtn': 'Borrar', 'noneOpt': '(ninguno)', 'noCalendar': '(sin calendario)',
        'placeKind': 'Tipo de lugar', 'colLabel': 'Columna', 'rowLabel': 'Fila', 'moveTap': 'Mover con un toque', 'moveCancel': 'Cancelar el movimiento',
        'moveTapHelp': 'Toca una casilla del mapa o lleva el cursor con las flechas y pulsa Intro para mover el lugar allí.',
        'placeMoved': '{name} en columna {c}, fila {r}', 'placeTerrain': 'Está en: {terr}.', 'speciesHere': 'Especies que pueden vivir aquí: {list}.', 'speciesHereNone': 'Ninguna especie tiene este terreno en su hábitat.',
        'habitat': 'Hábitat (terrenos donde vive)', 'cellsN': '{n} casillas', 'habitatChanged': 'Hábitat cambiado', 'habitatInfo': 'Puede vivir en {n} casillas del mapa ({p} %).',
        'diet': 'Alimentación', 'sizeWord': 'Tamaño', 'traits': 'Rasgos',
        'homeland': 'Tierra de origen', 'languageTitle': 'Lengua', 'langName': 'Nombre de la lengua', 'syllables': 'Sílabas de la lengua',
        'sylHelp': 'Escribe sílabas separadas por espacios. El generador de nombres las combina para los nombres de esta cultura.', 'sylTooFew': 'Escribe al menos dos sílabas.', 'sampleNames': 'Ejemplos:',
        'calendarTitle': 'Calendario', 'calSum': 'Año de {days} días en {months} meses; semana de {week} días.', 'curYear': 'Año actual', 'eraName': 'Nombre de la era',
        'monthsTitle': 'Meses', 'monthName': 'Nombre del mes {n}', 'monthDays': 'Días del mes {n}', 'removeMonth': 'Quitar el mes {name}', 'addMonth': 'Añadir mes', 'oneMonthMin': 'El calendario necesita al menos un mes.',
        'weekDays': 'Días de la semana (separados por comas)', 'firstDay': 'Día de la semana con el que empieza el año 1',
        'feastsTitle': 'Fiestas', 'feastName': 'Nombre de la fiesta {n}', 'feastMonth': 'Mes de {name}', 'feastDay': 'Día de {name}', 'removeFeast': 'Quitar la fiesta {name}', 'addFeast': 'Añadir fiesta', 'feastDefault': 'Fiesta {n}',
        'calChanged': 'Calendario cambiado', 'calOkMsg': 'El calendario es coherente.', 'seeCalendar': 'Ver el calendario', 'feastWord': 'fiesta',
        'calTitle': 'Calendario de {name}', 'calLede': 'Un año tiene {days} días repartidos en {months} meses, y la semana tiene {week} días. Año actual: {y} {era}.',
        'monthCap': '{m} ({n} días)', 'dateShort': 'día {d} de {m}', 'noFeasts': 'Todavía no hay fiestas.', 'daysWord': 'Días',
        'calEmpty': 'Todavía no hay culturas. Añade una para inventar su calendario.',
        'titleLabel': 'Título', 'calendarUsed': 'Calendario de la fecha', 'yearLabel': 'Año', 'monthLabel': 'Mes', 'dayLabel': 'Día', 'dateIs': 'Fecha: {date}.', 'whereLabel': 'Lugar',
        'seeTimeline': 'Ver la historia', 'eventDefault': 'Hecho {n}', 'calendarOf': 'calendario de {name}',
        'dateFmt': '{d} de {m} del año {y} {era}', 'dateYearOnly': 'Año {y}',
        'tlEmpty': 'Todavía no hay hechos en la historia.',
        'roleLabel': 'Papel en la historia', 'placeLabel': 'Lugar donde vive', 'relationsTitle': 'Relaciones', 'relKind': 'Tipo de la relación {n}', 'relWith': 'Con quién (relación {n})',
        'removeRel': 'Quitar la relación {n}', 'addRel': 'Añadir relación', 'relChanged': 'Relaciones cambiadas', 'relNeedTwo': 'Añade otro personaje para crear relaciones.', 'seeRelations': 'Ver las relaciones',
        'relEmpty': 'Todavía no hay personajes.', 'relNone': 'Todavía no hay relaciones. Elige un personaje y añade una en Propiedades.',
        'relTitle': 'Gráfico de relaciones entre personajes', 'relTableCap': 'Relaciones (la misma información que el gráfico)', 'relKey': 'Tipos de línea',
        'colChar': 'Personaje', 'colRel': 'Relación', 'colWith': 'Con',
        'cellAt': 'Columna {c}, fila {r}: {t}', 'riverWord': 'río', 'cursorSum': 'Cursor en columna {c}, fila {r} ({t}).',
        'painted': 'Pintado: {t}', 'filled': 'Relleno: {n} casillas de {t}', 'alreadyThat': 'Esa zona ya es de ese terreno.',
        'riverStart': 'Río empezado. Añade más puntos y vuelve a elegir el último para terminar.', 'riverPoint': 'Punto {n} del río', 'riverPending': 'río con {n} puntos',
        'riverAdded': 'Río añadido', 'riverRemoved': 'Río quitado', 'noRiverHere': 'Aquí no hay ningún río.', 'cancelled': 'Cancelado',
        'summary': '{name}. Mapa de {shape} de {w} × {h} casillas: {terr}. Ríos: {rivers}. Lugares: {places}. Especies: {species}. Culturas: {cultures}. Hechos: {events}. Personajes: {chars}.',
        'placesList': 'Lugares: {list}.',
        'genTitle': 'Generar un mapa', 'genWarn': 'El mapa nuevo sustituye al actual. Las fichas se conservan. Puedes deshacerlo.',
        'genType': 'Tipo de mapa', 'seedLabel': 'Semilla', 'newSeed': 'Semilla nueva', 'seedIs': 'Semilla: {s}',
        'seedHelp': 'La semilla puede ser un número o una palabra. Con la misma semilla y las mismas opciones sale siempre el mismo mapa.',
        'landLabel': 'Tierra firme', 'riversLabel': 'Número de ríos', 'genPlaces': 'Crear lugares nuevos (sustituye los actuales)', 'generateGo': 'Generar',
        'generated': 'Mapa generado: {t} con la semilla {seed}',
        'namesTitle': 'Generador de nombres', 'namesHelp': 'Elige un juego de sílabas o la lengua de una cultura y pide nombres. Puedes copiar los que te gusten.',
        'sylSet': 'Sílabas', 'langOf': 'Lengua de {name}', 'moreNames': 'Otros nombres', 'namesFilter': 'Los nombres salen de listas escogidas a mano y pasan por un filtro de palabras malsonantes en español y en inglés.',
        'exportAtlas': 'Exportar atlas (HTML)', 'exportPng': 'Exportar mapa (PNG)', 'exportSvg': 'Exportar mapa (SVG)', 'printAtlas': 'Imprimir atlas o guardarlo como PDF',
        'exportError': 'No se ha podido exportar. Inténtalo de nuevo.',
        'mapOf': 'Mapa de {name}', 'atlasOf': 'Atlas de {name}', 'tocTitle': 'Índice', 'noneYet': 'Todavía no hay nada aquí.', 'colRow': 'columna {c}, fila {r}',
        'atlasIntro': 'Un mundo inventado en El taller de Iris Green: su mapa, sus lugares, sus especies, sus culturas y calendarios, su historia y sus personajes.',
        'atlasFooter': 'IRIS GREEN · irisgreen.eu · Hecho en El taller. Este archivo no tiene programas ni enlaces externos.',
        'exIslandName': 'Isla de Marela', 'exTideName': 'Isla de las Mareas', 'exAtlasName': 'Continente de Dorkal', 'exContName': 'Tierra de Lindra',
        'exSp1': 'Tortuga de musgo', 'exSp1T': 'Lleva musgo en el caparazón y duerme al sol sobre la arena. Pone los huevos en el barro del pantano.',
        'exSp2': 'Cabra saltarrocas', 'exSp2T': 'Salta entre las rocas con pezuñas blandas. Baja a la llanura en invierno.',
        'exSp3': 'Pez farol', 'exSp3T': 'Brilla de noche para encontrar a su grupo. Come gambas diminutas.',
        'exSp4': 'Ratón de duna', 'exSp4T': 'Guarda agua en la cola y solo sale cuando se pone el sol.',
        'exSp5': 'Árbol caminante', 'exSp5T': 'Mueve sus raíces muy despacio para buscar claros con luz. Tarda un año en cruzar un bosque.',
        'exCul1': 'Gente de las Mareas', 'exCul1T': 'Pescan con redes de algas y leen la marea en la luna.', 'exLang1': 'Olamar', 'exEra1': 'desde la Llegada',
        'exFeast1': 'Fiesta de las Redes', 'exFeast2': 'Noche de los Faroles', 'exFeast3': 'Día de la Marea Alta',
        'exEv1': 'Llegada a la isla', 'exEv1T': 'Las primeras barcas llegan a la costa y fundan la ciudad.',
        'exEv2': 'Se enciende el faro', 'exEv2T': 'Desde entonces, la Noche de los Faroles recuerda esa fecha.',
        'exEv3': 'La gran tormenta', 'exEv3T': 'Una tormenta cambia la forma de la costa. Nadie sale al mar en siete días.',
        'exCul2': 'Pueblo de la Piedra', 'exCul2T': 'Viven junto a las montañas y tallan sus casas en la roca.', 'exLang2': 'Kardunio', 'exEra2': 'de la Primera Forja',
        'exCul3': 'Gente del Alba', 'exCul3T': 'Viajan con las estaciones y cuentan el tiempo por la luz.', 'exLang3': 'Aeliano', 'exEra3': 'del Nuevo Sol',
        'exFeast4': 'Fuego de Año Nuevo', 'exFeast5': 'Día del Pacto', 'exFeast6': 'Fiesta de la Luz Larga', 'exFeast7': 'Noche Quieta',
        'exEv4': 'Se funda la primera ciudad', 'exEv4T': 'Los canteros abren la primera calle en la montaña.',
        'exEv5': 'El Pacto del Río', 'exEv5T': 'Los dos pueblos acuerdan compartir el agua del río.',
        'exEv6': 'La gran marcha del Alba', 'exEv6T': 'La Gente del Alba cruza el continente siguiendo la luz.',
        'exEv7': 'El año sin cosecha', 'exEv7T': 'Una sequía obliga a las ciudades a ayudarse.',
        'exRole1': 'Guardiana del Pacto', 'exRole2': 'Cartógrafo viajero', 'exRole3': 'Maestro cantero', 'exRole4': 'Aprendiz de cartógrafa',
    },
    'en': {
        'canvasLabel': 'World map',
        'canvasHelp': 'On the map, the arrow keys move the cursor one cell (four with Shift) and read its terrain. Enter or Space use the chosen tool: the Brush paints, Fill fills the area, River adds a point (press Enter again on the last point to finish) and Place creates a place. With Select, Enter selects the place under the cursor and the arrow keys move it. [ and ] change terrain; Delete removes; Esc cancels. In the Calendar, History and Relationships views, the arrow keys go from one entry to the next.',
        'kWorldCursor': 'On the map: arrow keys for the cursor; Enter or Space to use the tool',
        'kWorldTerrain': '[ and ] to change terrain; Esc finishes a river or clears the selection',
        'kWorldViews': 'In Calendar, History and Relationships: arrow keys to go from one entry to the next',
        'stIsland': 'Island with three species', 'stIslandD': 'An island generated from a seed and three species with their habitat on the map.',
        'stCalendar': 'Culture with its own calendar', 'stCalendarD': 'A seafaring people with a language, eight months, a six-day week, festivals and history.',
        'stAtlas': 'Complete world with an atlas', 'stAtlasD': 'A continent with linked places, species, two cultures, history and characters.',
        'stContinent': 'Continent from a seed', 'stContinentD': 'A generated continent with rivers and places. Change the seed to see another.',
        'newWorldName': 'Untitled world',
        'toolSelect': 'Select', 'toolBrush': 'Brush', 'toolFill': 'Fill', 'toolRiver': 'River', 'toolPlace': 'Place', 'toolUnriver': 'Remove river', 'toolPan': 'Move the view',
        'terrainLabel': 'Terrain', 'viewLabel': 'View', 'generateBtn': 'Generate map', 'namesBtn': 'Names',
        'view_map': 'Map', 'view_calendar': 'Calendar', 'view_timeline': 'History', 'view_relations': 'Relationships',
        'viewNow': 'View: {v}', 'viewCmd': 'Show {v}',
        'terr_water': 'Water', 'terr_coast': 'Coast', 'terr_plain': 'Plain', 'terr_forest': 'Forest', 'terr_mountain': 'Mountain', 'terr_desert': 'Desert', 'terr_ice': 'Ice', 'terr_swamp': 'Marsh',
        'legendTex_water': 'blue with waves', 'legendTex_coast': 'sand with dots', 'legendTex_plain': 'light green with tufts of grass', 'legendTex_forest': 'green with trees',
        'legendTex_mountain': 'greyish brown with peaks', 'legendTex_desert': 'yellow with diagonal stripes', 'legendTex_ice': 'white with crosses', 'legendTex_swamp': 'greyish green with reeds',
        'legendMarkers': 'Places: square, city; circle, village; circle with an anchor, port; hollow triangle, ruins; star, landmark.',
        'legend': 'Key',
        'pk_city': 'City', 'pk_village': 'Village', 'pk_port': 'Port', 'pk_ruin': 'Ruins', 'pk_landmark': 'Landmark',
        'diet_plants': 'Eats plants', 'diet_meat': 'Eats other animals', 'diet_both': 'Eats anything', 'diet_sun': 'Lives on sunlight', 'diet_filter': 'Filters the water',
        'size_tiny': 'Tiny (smaller than a hand)', 'size_small': 'Small (like a cat)', 'size_medium': 'Medium (like a person)', 'size_large': 'Large (like a horse)', 'size_huge': 'Huge (like a house)',
        'rel_family': 'family', 'rel_friend': 'friendship', 'rel_rival': 'rivalry', 'rel_mentor': 'teaches', 'rel_ally': 'alliance',
        'shape_hex': 'Hexagons', 'shape_square': 'Squares',
        'syl_soft': 'Soft', 'syl_stone': 'Stony', 'syl_sea': 'Seaside', 'syl_bright': 'Bright',
        'gen_island': 'Island', 'gen_archipelago': 'Archipelago', 'gen_continent': 'Continent',
        'kind_world': 'World', 'kind_place': 'Place', 'kind_species': 'Species', 'kind_culture': 'Culture', 'kind_event': 'Event', 'kind_character': 'Character',
        'places': 'Places', 'speciesPl': 'Species', 'cultures': 'Cultures', 'events': 'History', 'characters': 'Characters',
        'add_place': 'Add place', 'add_species': 'Add species', 'add_culture': 'Add culture', 'add_event': 'Add event', 'add_character': 'Add character',
        'addCulture': 'Add culture', 'addEvent': 'Add event', 'addCharacter': 'Add character',
        'added': '{kind} added: {name}', 'deletedItem': 'Deleted: {name}', 'selectedItem': '{kind}: {name}',
        'renamed': 'Name changed', 'changedWord': 'Changed', 'movedWord': 'Moved', 'newNameIs': 'New name: {name}',
        'monthsN': '{n} months', 'yearN': 'year {y}',
        'worldTitle': 'World', 'worldName': 'Name of the world', 'challenges': 'Challenges', 'done': 'Done', 'pending': 'To do', 'yes': 'yes', 'no': 'no',
        'ch1': 'Island with three species', 'ch1D': 'Land surrounded by water: {island}. Species with a habitat on the map: {n} of 3.',
        'ch2': 'Culture with its own calendar', 'ch2D': 'At least 3 months, 3 days of the week and 1 festival on a date that exists.',
        'ch3': 'Complete world with an atlas',
        'gPlaces': 'Places: {n} of 3', 'gSpecies': 'Species with a habitat on the map: {n} of 3', 'gCalendar': 'A culture with a complete calendar',
        'gEvents': 'Events in history: {n} of 3', 'gChars': 'Characters: {n} of 3', 'gRels': 'Relationships: {n} of 2', 'gAtlas': 'Atlas exported or printed',
        'terrainTitle': 'Terrain to paint', 'brushSize': 'Brush size', 'brush1': '1 cell', 'brush2': '7 cells', 'brush3': '19 cells', 'brushNow': 'Brush of {n}',
        'terrainNow': 'Terrain: {t}',
        'mapTitle': 'Map', 'mapInfo': '{shape}, {w} × {h} cells. Seed: {seed}.', 'shapeLabel': 'Cell shape', 'sizeLabel': 'Map size (columns × rows)',
        'shapeChanged': 'Cell shape changed', 'resized': 'Map size changed',
        'showTex': 'Terrain textures', 'showGrid': 'Cell borders', 'showNames': 'Place names',
        'surfaceCap': 'Area of each terrain', 'colTerrain': 'Terrain', 'colCells': 'Cells',
        'checksTitle': 'Check', 'checksOk': 'Everything fits: no warnings.', 'checksBad': 'Warnings: {n}',
        'chkNoHabitat': '{name}: choose at least one habitat terrain.', 'chkHabitatMissing': '{name} lives in {terr}, but there is no {terr} on the map.',
        'chkNoMonths': '{name}: the calendar needs at least one month.', 'chkMonthName': '{name}: month {n} has no name.', 'chkNoWeek': '{name}: write at least one day of the week.',
        'chkFeastDay': '{name}: the festival “{feast}” falls on a day that does not exist in that month.', 'chkEventDate': '“{name}”: the date does not exist in that calendar.',
        'chkPlaceWater': '{name} is in the water. Should it be a port, or would you like to move it onto land?',
        'name': 'Name', 'otherName': 'Another name', 'description': 'Description', 'deleteBtn': 'Delete', 'noneOpt': '(none)', 'noCalendar': '(no calendar)',
        'placeKind': 'Kind of place', 'colLabel': 'Column', 'rowLabel': 'Row', 'moveTap': 'Move with one tap', 'moveCancel': 'Cancel the move',
        'moveTapHelp': 'Tap a cell on the map, or take the cursor there with the arrow keys and press Enter, to move the place there.',
        'placeMoved': '{name} at column {c}, row {r}', 'placeTerrain': 'It is on: {terr}.', 'speciesHere': 'Species that can live here: {list}.', 'speciesHereNone': 'No species has this terrain in its habitat.',
        'habitat': 'Habitat (terrain it lives in)', 'cellsN': '{n} cells', 'habitatChanged': 'Habitat changed', 'habitatInfo': 'It can live in {n} cells of the map ({p}%).',
        'diet': 'Diet', 'sizeWord': 'Size', 'traits': 'Features',
        'homeland': 'Homeland', 'languageTitle': 'Language', 'langName': 'Name of the language', 'syllables': 'Syllables of the language',
        'sylHelp': 'Write syllables separated by spaces. The name generator combines them to make names for this culture.', 'sylTooFew': 'Write at least two syllables.', 'sampleNames': 'Examples:',
        'calendarTitle': 'Calendar', 'calSum': 'A year of {days} days in {months} months; a week of {week} days.', 'curYear': 'Current year', 'eraName': 'Name of the era',
        'monthsTitle': 'Months', 'monthName': 'Name of month {n}', 'monthDays': 'Days in month {n}', 'removeMonth': 'Remove the month {name}', 'addMonth': 'Add month', 'oneMonthMin': 'The calendar needs at least one month.',
        'weekDays': 'Days of the week (separated by commas)', 'firstDay': 'Day of the week that year 1 starts on',
        'feastsTitle': 'Festivals', 'feastName': 'Name of festival {n}', 'feastMonth': 'Month of {name}', 'feastDay': 'Day of {name}', 'removeFeast': 'Remove the festival {name}', 'addFeast': 'Add festival', 'feastDefault': 'Festival {n}',
        'calChanged': 'Calendar changed', 'calOkMsg': 'The calendar is consistent.', 'seeCalendar': 'Show the calendar', 'feastWord': 'festival',
        'calTitle': 'Calendar of {name}', 'calLede': 'A year has {days} days in {months} months, and the week has {week} days. Current year: {y} {era}.',
        'monthCap': '{m} ({n} days)', 'dateShort': 'day {d} of {m}', 'noFeasts': 'There are no festivals yet.', 'daysWord': 'Days',
        'calEmpty': 'There are no cultures yet. Add one to invent its calendar.',
        'titleLabel': 'Title', 'calendarUsed': 'Calendar for the date', 'yearLabel': 'Year', 'monthLabel': 'Month', 'dayLabel': 'Day', 'dateIs': 'Date: {date}.', 'whereLabel': 'Place',
        'seeTimeline': 'Show the history', 'eventDefault': 'Event {n}', 'calendarOf': 'calendar of {name}',
        'dateFmt': '{d} {m}, year {y} {era}', 'dateYearOnly': 'Year {y}',
        'tlEmpty': 'There are no events in the history yet.',
        'roleLabel': 'Role in the story', 'placeLabel': 'Place where they live', 'relationsTitle': 'Relationships', 'relKind': 'Kind of relationship {n}', 'relWith': 'With whom (relationship {n})',
        'removeRel': 'Remove relationship {n}', 'addRel': 'Add relationship', 'relChanged': 'Relationships changed', 'relNeedTwo': 'Add another character to create relationships.', 'seeRelations': 'Show the relationships',
        'relEmpty': 'There are no characters yet.', 'relNone': 'There are no relationships yet. Select a character and add one in Properties.',
        'relTitle': 'Diagram of relationships between characters', 'relTableCap': 'Relationships (the same information as the diagram)', 'relKey': 'Kinds of line',
        'colChar': 'Character', 'colRel': 'Relationship', 'colWith': 'With',
        'cellAt': 'Column {c}, row {r}: {t}', 'riverWord': 'river', 'cursorSum': 'Cursor at column {c}, row {r} ({t}).',
        'painted': 'Painted: {t}', 'filled': 'Filled: {n} cells of {t}', 'alreadyThat': 'That area is already that terrain.',
        'riverStart': 'River started. Add more points and choose the last one again to finish.', 'riverPoint': 'River point {n}', 'riverPending': 'river with {n} points',
        'riverAdded': 'River added', 'riverRemoved': 'River removed', 'noRiverHere': 'There is no river here.', 'cancelled': 'Cancelled',
        'summary': '{name}. Map of {shape}, {w} × {h} cells: {terr}. Rivers: {rivers}. Places: {places}. Species: {species}. Cultures: {cultures}. Events: {events}. Characters: {chars}.',
        'placesList': 'Places: {list}.',
        'genTitle': 'Generate a map', 'genWarn': 'The new map replaces the current one. Your entries are kept. You can undo it.',
        'genType': 'Kind of map', 'seedLabel': 'Seed', 'newSeed': 'New seed', 'seedIs': 'Seed: {s}',
        'seedHelp': 'The seed can be a number or a word. The same seed with the same options always gives the same map.',
        'landLabel': 'Dry land', 'riversLabel': 'Number of rivers', 'genPlaces': 'Create new places (replaces the current ones)', 'generateGo': 'Generate',
        'generated': 'Map generated: {t} with the seed {seed}',
        'namesTitle': 'Name generator', 'namesHelp': 'Choose a set of syllables or a culture’s language and ask for names. You can copy the ones you like.',
        'sylSet': 'Syllables', 'langOf': 'Language of {name}', 'moreNames': 'More names', 'namesFilter': 'Names come from hand-picked lists and go through a filter of offensive words in Spanish and English.',
        'exportAtlas': 'Export atlas (HTML)', 'exportPng': 'Export map (PNG)', 'exportSvg': 'Export map (SVG)', 'printAtlas': 'Print the atlas or save it as PDF',
        'exportError': 'Could not export. Please try again.',
        'mapOf': 'Map of {name}', 'atlasOf': 'Atlas of {name}', 'tocTitle': 'Contents', 'noneYet': 'There is nothing here yet.', 'colRow': 'column {c}, row {r}',
        'atlasIntro': 'An invented world from the Iris Green workshop: its map, places, species, cultures and calendars, its history and its characters.',
        'atlasFooter': 'IRIS GREEN · irisgreen.eu · Made in the workshop. This file has no programs and no outside links.',
        'exIslandName': 'Isle of Marela', 'exTideName': 'Isle of Tides', 'exAtlasName': 'The Continent of Dorkal', 'exContName': 'Land of Lindra',
        'exSp1': 'Moss turtle', 'exSp1T': 'It carries moss on its shell and sleeps in the sun on the sand. It lays its eggs in the marsh mud.',
        'exSp2': 'Rock-hopper goat', 'exSp2T': 'It jumps between rocks on soft hooves. In winter it comes down to the plain.',
        'exSp3': 'Lantern fish', 'exSp3T': 'It glows at night to find its shoal. It eats tiny shrimp.',
        'exSp4': 'Dune mouse', 'exSp4T': 'It stores water in its tail and only comes out when the sun goes down.',
        'exSp5': 'Walking tree', 'exSp5T': 'It moves its roots very slowly to find sunny clearings. It takes a year to cross a forest.',
        'exCul1': 'Tide Folk', 'exCul1T': 'They fish with seaweed nets and read the tides in the moon.', 'exLang1': 'Olamar', 'exEra1': 'since the Landing',
        'exFeast1': 'Festival of Nets', 'exFeast2': 'Night of Lanterns', 'exFeast3': 'High Tide Day',
        'exEv1': 'Landing on the island', 'exEv1T': 'The first boats reach the coast and found the city.',
        'exEv2': 'The lighthouse is lit', 'exEv2T': 'Since then, the Night of Lanterns remembers that date.',
        'exEv3': 'The great storm', 'exEv3T': 'A storm changes the shape of the coast. Nobody goes to sea for seven days.',
        'exCul2': 'Stone People', 'exCul2T': 'They live by the mountains and carve their homes in the rock.', 'exLang2': 'Kardunian', 'exEra2': 'of the First Forge',
        'exCul3': 'Dawn Folk', 'exCul3T': 'They travel with the seasons and count time by the light.', 'exLang3': 'Aelian', 'exEra3': 'of the New Sun',
        'exFeast4': 'New Year Fire', 'exFeast5': 'Pact Day', 'exFeast6': 'Festival of the Long Light', 'exFeast7': 'Still Night',
        'exEv4': 'The first city is founded', 'exEv4T': 'The stonemasons open the first street in the mountain.',
        'exEv5': 'The River Pact', 'exEv5T': 'The two peoples agree to share the river water.',
        'exEv6': 'The great Dawn march', 'exEv6T': 'The Dawn Folk cross the continent following the light.',
        'exEv7': 'The year without a harvest', 'exEv7T': 'A drought makes the cities help each other.',
        'exRole1': 'Keeper of the Pact', 'exRole2': 'Travelling mapmaker', 'exRole3': 'Master stonemason', 'exRole4': 'Apprentice mapmaker',
    },
}
assert set(STRINGS['es']) == set(STRINGS['en'])
assert set(PAGE['es']) == set(PAGE['en'])
