"""Textos del estudio de música (R43), comunes a Ritmo, Composición y Síntesis (ES/EN)."""

LIBRARIES = 'Tone.js (MIT) y PixiJS (MIT); medidor propio en AudioWorklet'
LIBRARIES_EN = 'Tone.js (MIT) and PixiJS (MIT); our own AudioWorklet level meter'
SCRIPTS = ['ig-suite-musica.js']

STRINGS = {
    'es': {
        'noteStartF': 'Empieza en el tiempo', 'noteLenF': 'Duración', 'notePitchF': 'Altura', 'beatsUnitF': 'tiempos',
        'canvasLabel': 'Línea de tiempo y editor de notas',
        'canvasHelp': 'Arriba, las pistas con sus clips; abajo, las notas del clip elegido. Con el teclado: flechas para mover el cursor, Intro para poner o quitar una nota, Ctrl + flechas para mover las notas elegidas, Mayús + flechas para alargarlas, Espacio para reproducir o parar.',
        'kPlay': 'Espacio: reproducir o parar', 'kEditor': 'En el editor: flechas mueven el cursor; Intro pone o quita la nota; Ctrl/Cmd + flechas mueven las notas elegidas; Mayús + flechas cambian su duración; Supr las borra',
        'kTyping': 'Con «Tocar con el teclado» activado: teclas A W S E D F T G Y H U J K O L P tocan notas',
        'stBeatFirst': 'Mi primer ritmo', 'stBeatFirstD': 'Bombo, palmadas y charles. Añade o quita golpes tocando las casillas.',
        'stBeatRock': 'Ritmo de rock', 'stBeatRockD': 'Batería clásica con bajo. Cambia el tempo y escucha la diferencia.',
        'stBeatDembow': 'Dembow', 'stBeatDembowD': 'El patrón del reguetón con un bajo sencillo. Pruébalo más rápido o más lento.',
        'stBeatPoly': 'Polirritmo 3 contra 4', 'stBeatPolyD': 'Dos pulsos distintos a la vez. Escucha cómo se cruzan y se vuelven a encontrar.',
        'stSongBells': 'Canción de campanas', 'stSongBellsD': 'Una melodía tradicional con campanas y un pulso suave.',
        'stSongPop': 'Canción pop', 'stSongPopD': 'Acordes, bajo, melodía y batería: cuatro pistas para mezclar y cambiar.',
        'stSongAmbient': 'Música ambiental', 'stSongAmbientD': 'Acordes largos y campanas lejanas. Juega con la reverberación y el espacio.',
        'stSynthBells': 'Diseña campanas', 'stSynthBellsD': 'Síntesis FM: cambia el índice y la armonicidad y escucha cómo cambia el metal.',
        'stSynthBass': 'Diseña un bajo', 'stSynthBassD': 'Onda de sierra con filtro. Baja el corte y sube la resonancia.',
        'stSynthPad': 'Diseña un colchón sonoro', 'stSynthPadD': 'Ataque lento y cola larga. Dibuja la envolvente arrastrando sus puntos.',
        'stSynthWind': 'Paisaje de viento', 'stSynthWindD': 'Ruido filtrado que sube y baja, con acordes de fondo.',
        'trDrums': 'Batería', 'trBass': 'Bajo', 'trMelody': 'Melodía', 'trPad': 'Colchón', 'trBells': 'Campanas', 'trWind': 'Viento', 'trChords': 'Acordes',
        'audioWaiting': 'se activa al pulsar Reproducir o tocar una nota', 'meterWord': 'medidor de nivel', 'noWorklet': 'sin AudioWorklet en este navegador',
        'playing': 'Reproduciendo.', 'stoppedAudio': 'Parado.', 'kindDrums': 'Batería',
        'preset_piano': 'Piano eléctrico', 'preset_bass': 'Bajo', 'preset_pad': 'Colchón', 'preset_lead': 'Solista', 'preset_bell': 'Campana', 'preset_strings': 'Cuerdas', 'preset_noise': 'Ruido (viento, mar)',
        'bpmShort': '{n} BPM', 'noClip': 'Elige un clip arriba o crea uno con el lápiz en una pista.',
        'editing': '{track} · compás {start} · {len} compases', 'playheadAt': 'Cabezal en el compás {bar}, tiempo {beat}',
        'clipDeleted': 'Clip borrado.', 'clipAdded': 'Clip nuevo de un compás.', 'noteDeleted': 'Nota borrada.', 'noteAdded': 'Nota añadida: {name}', 'loopSet': 'Bucle del compás {a} al {b}.',
        'clipMoved': 'Clip movido.', 'clipResized': 'Clip alargado o acortado.', 'noteMoved': 'Notas movidas.', 'noteResized': 'Duración cambiada.',
        'cursorMusic': '{what}, compás {bar}, tiempo {beat}, parte {sub}', 'hasNote': 'hay nota',
        'tracks': 'Pistas', 'trackChosen': 'Pista elegida: {name}', 'muteTrack': 'Silenciar {name}', 'soloTrack': 'Escuchar solo {name}',
        'muted': '{name} silenciada.', 'unmuted': '{name} vuelve a sonar.', 'soloOn': 'Solo: {name}.', 'soloOff': '{name} ya no está en solo.',
        'newTrackKind': 'Instrumento', 'addTrack': 'Añadir pista', 'clipsOf': 'Clips de {name}', 'clipName': 'Compás {bar} · {len} comp.', 'notesN': '{n} notas',
        'song': 'Canción', 'tempo': 'Tempo', 'tempoSet': 'Tempo: {n} BPM', 'lengthBars': 'Duración', 'barsUnit': 'compases', 'lengthSet': 'Duración cambiada.',
        'gridLabel': 'Cuadrícula', 'grid1': 'Negras (1/4)', 'grid2': 'Corcheas (1/8)', 'grid4': 'Semicorcheas (1/16)', 'grid8': 'Fusas (1/32)',
        'trackTitle': 'Pista: {name}', 'name': 'Nombre', 'renamed': 'Nombre cambiado.', 'volume': 'Volumen', 'volumeSet': 'Volumen cambiado.', 'pan': 'Panorama',
        'centre': 'centro', 'leftN': 'izquierda {n} %', 'rightN': 'derecha {n} %', 'panSet': 'Panorama cambiado.',
        'clipTitle': 'Clip elegido', 'clipStart': 'Empieza en el compás', 'barWord': 'compás', 'clipLen': 'Duración del clip', 'duplicateClip': 'Duplicar detrás', 'clipDuplicated': 'Clip duplicado.', 'deleteClip': 'Borrar clip',
        'noteTitle': 'Nota elegida: {name}', 'velocity': 'Intensidad', 'velocitySet': 'Intensidad cambiada.', 'deleteTrack': 'Borrar pista', 'trackDeleted': 'Pista borrada.',
        'summary': 'Canción a {bpm} BPM, {bars} compases, {n} pistas: {tracks}.',
        'notesTable': 'Notas del clip ({n})', 'thWhen': 'Cuándo (compás.tiempo)', 'thSound': 'Sonido', 'thNote': 'Nota', 'thLength': 'Duración (tiempos)',
        'instrument': 'Instrumento', 'presetLabel': 'Sonido base', 'presetSet': 'Sonido: {name}', 'waveform': 'Forma de onda', 'wSine': 'Senoidal', 'wTriangle': 'Triangular', 'wSquare': 'Cuadrada', 'wSaw': 'Sierra',
        'noiseColour': 'Tipo de ruido', 'nWhite': 'Blanco', 'nPink': 'Rosa', 'nBrown': 'Marrón',
        'cutoff': 'Filtro: frecuencia de corte', 'resonance': 'Filtro: resonancia', 'fmIndex': 'Índice de modulación', 'harmonicity': 'Armonicidad', 'reverb': 'Reverberación', 'echo': 'Eco',
        'envelope': 'Envolvente (arrastra los puntos)', 'envDesc': 'Envolvente: ataque {a} s, caída {d} s, sostenido {s} %, final {r} s',
        'attack': 'Ataque', 'decay': 'Caída', 'sustain': 'Sostenido', 'release': 'Final',
        'trackAdded': 'Pista añadida: {name}', 'rendering': 'Preparando el WAV…', 'renderError': 'No se ha podido crear el archivo de sonido.',
        'exportWav': 'Exportar sonido (WAV)', 'exportMidi': 'Exportar partitura (MIDI)', 'stopBtn': 'Parar', 'play': 'Reproducir',
        'toolDraw': 'Lápiz', 'toolSelect': 'Mover', 'toolErase': 'Borrar', 'metronome': 'Metrónomo', 'metroOn': 'Metrónomo activado.', 'metroOff': 'Metrónomo desactivado.',
        'typing': 'Tocar con el teclado', 'typingOn': 'Teclado musical activado: A W S E D F T G Y H U J K O L P.', 'typingOff': 'Teclado musical desactivado.',
    },
    'en': {
        'noteStartF': 'Starts on beat', 'noteLenF': 'Length', 'notePitchF': 'Pitch', 'beatsUnitF': 'beats',
        'canvasLabel': 'Timeline and note editor',
        'canvasHelp': 'At the top, the tracks and their clips; below, the notes of the chosen clip. With a keyboard: arrow keys move the cursor, Enter adds or removes a note, Ctrl + arrows move the chosen notes, Shift + arrows lengthen them, Space plays or stops.',
        'kPlay': 'Space: play or stop', 'kEditor': 'In the editor: arrow keys move the cursor; Enter adds or removes the note; Ctrl/Cmd + arrows move the chosen notes; Shift + arrows change their length; Delete removes them',
        'kTyping': 'With “Play with the keyboard” on: keys A W S E D F T G Y H U J K O L P play notes',
        'stBeatFirst': 'My first beat', 'stBeatFirstD': 'Kick, claps and hi-hat. Add or remove hits by tapping the cells.',
        'stBeatRock': 'Rock beat', 'stBeatRockD': 'A classic drum kit with bass. Change the tempo and hear the difference.',
        'stBeatDembow': 'Dembow', 'stBeatDembowD': 'The reggaeton pattern with a simple bass. Try it faster or slower.',
        'stBeatPoly': 'Polyrhythm 3 against 4', 'stBeatPolyD': 'Two different pulses at once. Hear them cross and meet again.',
        'stSongBells': 'Bell song', 'stSongBellsD': 'A traditional tune on bells with a gentle beat.',
        'stSongPop': 'Pop song', 'stSongPopD': 'Chords, bass, melody and drums: four tracks to mix and change.',
        'stSongAmbient': 'Ambient music', 'stSongAmbientD': 'Long chords and distant bells. Play with reverb and space.',
        'stSynthBells': 'Design bells', 'stSynthBellsD': 'FM synthesis: change the index and harmonicity and hear the metal change.',
        'stSynthBass': 'Design a bass', 'stSynthBassD': 'A sawtooth wave with a filter. Lower the cutoff and raise the resonance.',
        'stSynthPad': 'Design a pad', 'stSynthPadD': 'Slow attack and long tail. Shape the envelope by dragging its points.',
        'stSynthWind': 'Wind soundscape', 'stSynthWindD': 'Filtered noise that rises and falls, with chords behind it.',
        'trDrums': 'Drums', 'trBass': 'Bass', 'trMelody': 'Melody', 'trPad': 'Pad', 'trBells': 'Bells', 'trWind': 'Wind', 'trChords': 'Chords',
        'audioWaiting': 'starts when you press Play or play a note', 'meterWord': 'level meter', 'noWorklet': 'no AudioWorklet in this browser',
        'playing': 'Playing.', 'stoppedAudio': 'Stopped.', 'kindDrums': 'Drums',
        'preset_piano': 'Electric piano', 'preset_bass': 'Bass', 'preset_pad': 'Pad', 'preset_lead': 'Lead', 'preset_bell': 'Bell', 'preset_strings': 'Strings', 'preset_noise': 'Noise (wind, sea)',
        'bpmShort': '{n} BPM', 'noClip': 'Choose a clip above or create one with the pencil on a track.',
        'editing': '{track} · bar {start} · {len} bars', 'playheadAt': 'Playhead at bar {bar}, beat {beat}',
        'clipDeleted': 'Clip deleted.', 'clipAdded': 'New one-bar clip.', 'noteDeleted': 'Note deleted.', 'noteAdded': 'Note added: {name}', 'loopSet': 'Loop from bar {a} to {b}.',
        'clipMoved': 'Clip moved.', 'clipResized': 'Clip lengthened or shortened.', 'noteMoved': 'Notes moved.', 'noteResized': 'Length changed.',
        'cursorMusic': '{what}, bar {bar}, beat {beat}, part {sub}', 'hasNote': 'note here',
        'tracks': 'Tracks', 'trackChosen': 'Track chosen: {name}', 'muteTrack': 'Mute {name}', 'soloTrack': 'Solo {name}',
        'muted': '{name} muted.', 'unmuted': '{name} playing again.', 'soloOn': 'Solo: {name}.', 'soloOff': '{name} is no longer solo.',
        'newTrackKind': 'Instrument', 'addTrack': 'Add track', 'clipsOf': 'Clips in {name}', 'clipName': 'Bar {bar} · {len} bars', 'notesN': '{n} notes',
        'song': 'Song', 'tempo': 'Tempo', 'tempoSet': 'Tempo: {n} BPM', 'lengthBars': 'Length', 'barsUnit': 'bars', 'lengthSet': 'Length changed.',
        'gridLabel': 'Grid', 'grid1': 'Quarter notes (1/4)', 'grid2': 'Eighth notes (1/8)', 'grid4': 'Sixteenth notes (1/16)', 'grid8': 'Thirty-second notes (1/32)',
        'trackTitle': 'Track: {name}', 'name': 'Name', 'renamed': 'Name changed.', 'volume': 'Volume', 'volumeSet': 'Volume changed.', 'pan': 'Pan',
        'centre': 'centre', 'leftN': 'left {n}%', 'rightN': 'right {n}%', 'panSet': 'Pan changed.',
        'clipTitle': 'Chosen clip', 'clipStart': 'Starts at bar', 'barWord': 'bar', 'clipLen': 'Clip length', 'duplicateClip': 'Duplicate after', 'clipDuplicated': 'Clip duplicated.', 'deleteClip': 'Delete clip',
        'noteTitle': 'Chosen note: {name}', 'velocity': 'Velocity', 'velocitySet': 'Velocity changed.', 'deleteTrack': 'Delete track', 'trackDeleted': 'Track deleted.',
        'summary': 'Song at {bpm} BPM, {bars} bars, {n} tracks: {tracks}.',
        'notesTable': 'Notes in the clip ({n})', 'thWhen': 'When (bar.beat)', 'thSound': 'Sound', 'thNote': 'Note', 'thLength': 'Length (beats)',
        'instrument': 'Instrument', 'presetLabel': 'Base sound', 'presetSet': 'Sound: {name}', 'waveform': 'Waveform', 'wSine': 'Sine', 'wTriangle': 'Triangle', 'wSquare': 'Square', 'wSaw': 'Sawtooth',
        'noiseColour': 'Noise type', 'nWhite': 'White', 'nPink': 'Pink', 'nBrown': 'Brown',
        'cutoff': 'Filter: cutoff frequency', 'resonance': 'Filter: resonance', 'fmIndex': 'Modulation index', 'harmonicity': 'Harmonicity', 'reverb': 'Reverb', 'echo': 'Echo',
        'envelope': 'Envelope (drag the points)', 'envDesc': 'Envelope: attack {a} s, decay {d} s, sustain {s}%, release {r} s',
        'attack': 'Attack', 'decay': 'Decay', 'sustain': 'Sustain', 'release': 'Release',
        'trackAdded': 'Track added: {name}', 'rendering': 'Preparing the WAV…', 'renderError': 'The sound file could not be created.',
        'exportWav': 'Export sound (WAV)', 'exportMidi': 'Export score (MIDI)', 'stopBtn': 'Stop', 'play': 'Play',
        'toolDraw': 'Pencil', 'toolSelect': 'Move', 'toolErase': 'Delete', 'metronome': 'Metronome', 'metroOn': 'Metronome on.', 'metroOff': 'Metronome off.',
        'typing': 'Play with the keyboard', 'typingOn': 'Musical keyboard on: A W S E D F T G Y H U J K O L P.', 'typingOff': 'Musical keyboard off.',
    },
}
assert set(STRINGS['es']) == set(STRINGS['en']), set(STRINGS['es']) ^ set(STRINGS['en'])


def section_common(lang):
    if lang == 'es':
        return [
            {'h': 'Tiempo real, reloj de audio', 'p': 'El cabezal y las notas siguen al reloj de la tarjeta de sonido, no a los temporizadores de la página. Por eso el ritmo no se descuadra aunque el ordenador vaya cargado.'},
            {'h': 'Qué te llevas', 'p': 'WAV es el sonido ya mezclado, listo para escuchar o subir. MIDI es la partitura: las notas de cada pista, que puedes abrir en otro programa de música para cambiar los instrumentos.'},
        ]
    return [
        {'h': 'Real time, audio clock', 'p': 'The playhead and the notes follow the sound card’s clock, not the page’s timers. That is why the rhythm stays tight even when the computer is busy.'},
        {'h': 'What you take away', 'p': 'WAV is the mixed sound, ready to listen to or upload. MIDI is the score: the notes of every track, which you can open in another music program to change the instruments.'},
    ]
