"""Estudio de papiroflexia y poliedros (R43): sólidos que se despliegan (Three.js), redes para imprimir
con pestañas, simulador de pliegues con hoja de diagramas, vértice plano (Maekawa y Kawasaki),
grulla y cubo Sonobe. Textos ES/EN."""

ENGINE = 'papiroflexia'
SLUG = {'es': 'papiroflexia', 'en': 'origami-polyhedra'}
SCRIPTS = ['ig-suite-3d.js', 'ig-suite-papiroflexia-geo.js', 'ig-suite-papiroflexia-diagramas.js', 'ig-suite-papiroflexia.js']
STYLES = ['ig-suite-papiroflexia.css']
LIBRARIES = 'Three.js (MIT) con WebGPU o WebGL 2; geometría de poliedros, pliegues y diagramas propia de Iris Green'
LIBRARIES_EN = 'Three.js (MIT) with WebGPU or WebGL 2; Iris Green’s own geometry for polyhedra, folds and diagrams'

PAGE = {
    'es': {
        'title': 'Papiroflexia y poliedros',
        'description': 'Despliega poliedros en 3D, imprime su red con pestañas a escala real, pliega papel paso a paso con hoja de diagramas, comprueba vértices planos y aprende la grulla y el cubo Sonobe.',
        'lede': 'Seis vistas en un mismo estudio: arriba eliges Sólido 3D, Red para imprimir, Pliegues, Vértice plano, Grulla o Cubo Sonobe. Todo se hace con clics, dedo o teclado.',
        'make': ['Un poliedro desplegado a su red plana', 'La red de tu poliedro, con pestañas, colores y números de pegado, a escala real', 'Un avión, un vaso, un gorro o un sobre, con su hoja de diagramas', 'Tus propios pliegues y su patrón', 'Una grulla y un cubo de 6 piezas Sonobe'],
        'steps': [
            'Sólido 3D: elige un sólido y mueve «Plegado %» para desplegarlo. Gira la vista con el ratón, el dedo o las flechas.',
            'Red para imprimir: pon la arista en mm, colorea las caras (tócalas o elígelas en Estructura) y pulsa «Imprimir a escala real».',
            'Pliegues: toca dos puntos marcados del papel. Elige Valle o Monte y pulsa «Plegar». Cada pliegue es un paso de la hoja de diagramas.',
            'Vértice plano: añade pliegues alrededor del punto central y mira si cumplen Maekawa y Kawasaki.',
            'Grulla y Cubo Sonobe: avanza paso a paso con «Siguiente» o con las flechas, e imprime los diagramas.',
        ],
        'sections': [
            {'h': 'Caras, aristas y vértices', 'p': 'Una cara es cada polígono plano del sólido; una arista, el segmento donde se juntan dos caras; un vértice, cada esquina. En todo poliedro convexo se cumple la fórmula de Euler: vértices − aristas + caras = 2. El ángulo diedro es el que forman dos caras vecinas. La suma de lo que le falta a cada vértice para llegar a 360° (el defecto angular) siempre da 720°.'},
            {'h': 'Redes y pestañas', 'p': 'La red es el sólido abierto en un solo trozo plano. Hay una pestaña por cada par de aristas que se pegan, y el mismo número aparece en la pestaña y en el borde donde va. Línea continua: corta. Raya y dos puntos: pliegue en monte (la arista queda hacia ti). Rayas: pliegue en valle. Si la red no cabe en un A4, el estudio la reparte en varias hojas con una franja de solape o te dice qué arista cabe en una sola hoja. Comprueba la regla de 50 mm al imprimir: debe medir eso exacto (escala 100 %).'},
            {'h': 'Pliegues en valle y en monte', 'p': 'En un pliegue en valle el papel se dobla hacia ti y forma una V. En un monte se dobla hacia atrás y forma una cresta. El simulador refleja de verdad las capas: cada pieza de papel se voltea sobre la línea y queda encima (valle) o debajo (monte). «Solo la capa de arriba» pliega la solapa superior, como en el ala de un avión.'},
            {'h': 'Vértices que se aplanan', 'p': 'Teorema de Maekawa: en un vértice plegado en plano, el número de montes y el de valles se diferencian en 2. Teorema de Kawasaki: sumando un ángulo sí y otro no alrededor del vértice se obtienen 180°. El estudio comprueba también la regla del ángulo pequeño entre dos grandes (sus dos pliegues deben ser distintos) y reduce el patrón con pliegues en zigzag para decir si se puede aplanar.'},
            {'h': 'Grulla y módulo Sonobe', 'p': 'La grulla es un modelo tradicional que parte de la base pájaro. Sus pasos con pliegue de pétalo e invertido van en diagramas dibujados para este estudio. El módulo Sonobe se atribuye a Mitsunobu Sonobe (Japón); con 6 piezas iguales se monta un cubo: cada pieza es una cara y sus dos puntas entran en los bolsillos de las vecinas.'},
            {'h': 'Fuentes', 'p': 'David S. Richeson, «Euler’s Gem: The Polyhedron Formula and the Birth of Topology», Princeton University Press, 2008. Peter R. Cromwell, «Polyhedra», Cambridge University Press, 1997. Thomas C. Hull, «Origametry: Mathematical Methods in Paper Folding», Cambridge University Press, 2020 (teoremas de Maekawa y Kawasaki). Erik D. Demaine y Joseph O’Rourke, «Geometric Folding Algorithms: Linkages, Origami, Polyhedra», Cambridge University Press, 2007 (pliegues en zigzag y redes de poliedros). Robert J. Lang, «Origami Design Secrets: Mathematical Methods for an Ancient Art», A K Peters, 2003 (base pájaro y notación de diagramas). David Lister, «The Sonobe Module», Lister List, British Origami Society, britishorigami.org (origen del módulo, documentado desde 1968).'},
        ],
        'links': [('Todo el taller', '/es/taller/'), ('Modelado 3D', '/es/taller/modelado-3d/'), ('Arquitectura y planos', '/es/taller/arquitectura/')],
    },
    'en': {
        'title': 'Origami and polyhedra',
        'description': 'Unfold polyhedra in 3D, print their nets with glue tabs at true scale, fold paper step by step with a diagram sheet, check flat vertices and learn the crane and the Sonobe cube.',
        'lede': 'Six views in one studio: at the top choose 3D solid, Printable net, Folding, Flat vertex, Crane or Sonobe cube. Everything works with a mouse, a finger or the keyboard.',
        'make': ['A polyhedron unfolded into its flat net', 'Your polyhedron’s net with tabs, colours and glue numbers, at true scale', 'A plane, a cup, a hat or an envelope, with its diagram sheet', 'Your own folds and their crease pattern', 'A crane and a 6-piece Sonobe cube'],
        'steps': [
            '3D solid: choose a solid and move “Folded %” to unfold it. Turn the view with the mouse, a finger or the arrow keys.',
            'Printable net: set the edge in mm, colour the faces (tap them or choose them in Structure) and press “Print at true scale”.',
            'Folding: tap two marked points on the paper. Choose Valley or Mountain and press “Fold”. Each fold becomes a step on the diagram sheet.',
            'Flat vertex: add creases around the centre point and see whether they meet Maekawa and Kawasaki.',
            'Crane and Sonobe cube: go step by step with “Next” or the arrow keys, and print the diagrams.',
        ],
        'sections': [
            {'h': 'Faces, edges and vertices', 'p': 'A face is each flat polygon of the solid; an edge is the segment where two faces meet; a vertex is each corner. Every convex polyhedron follows Euler’s formula: vertices − edges + faces = 2. The dihedral angle is the angle between two neighbouring faces. What each vertex is missing to reach 360° (the angular defect) always adds up to 720°.'},
            {'h': 'Nets and tabs', 'p': 'The net is the solid opened out into one flat piece. There is one tab for each pair of edges that are glued, and the same number is printed on the tab and on the edge it goes to. Solid line: cut. Dash and two dots: mountain fold (the edge points towards you). Dashes: valley fold. If the net does not fit on A4, the studio spreads it over several sheets with an overlap strip, or tells you which edge fits on one sheet. Check the 50 mm ruler when printing: it must measure exactly that (100 % scale).'},
            {'h': 'Valley and mountain folds', 'p': 'In a valley fold the paper bends towards you and makes a V. In a mountain fold it bends away and makes a ridge. The simulator really reflects the layers: each piece of paper flips over the line and ends up on top (valley) or underneath (mountain). “Top layer only” folds just the top flap, as with a plane’s wing.'},
            {'h': 'Vertices that fold flat', 'p': 'Maekawa’s theorem: at a flat-folded vertex, the numbers of mountains and valleys differ by 2. Kawasaki’s theorem: adding every other angle around the vertex gives 180°. The studio also checks the small-angle-between-two-big-ones rule (its two creases must be different) and reduces the pattern with zigzag folds (crimps) to tell you whether it can be flattened.'},
            {'h': 'Crane and Sonobe unit', 'p': 'The crane is a traditional model that starts from the bird base. Its steps with petal and reverse folds are in diagrams drawn for this studio. The Sonobe unit is credited to Mitsunobu Sonobe (Japan); 6 identical pieces make a cube: each piece is one face and its two points slide into the pockets of its neighbours.'},
            {'h': 'Sources', 'p': 'David S. Richeson, “Euler’s Gem: The Polyhedron Formula and the Birth of Topology”, Princeton University Press, 2008. Peter R. Cromwell, “Polyhedra”, Cambridge University Press, 1997. Thomas C. Hull, “Origametry: Mathematical Methods in Paper Folding”, Cambridge University Press, 2020 (Maekawa’s and Kawasaki’s theorems). Erik D. Demaine and Joseph O’Rourke, “Geometric Folding Algorithms: Linkages, Origami, Polyhedra”, Cambridge University Press, 2007 (crimps and polyhedron nets). Robert J. Lang, “Origami Design Secrets: Mathematical Methods for an Ancient Art”, A K Peters, 2003 (bird base and diagram notation). David Lister, “The Sonobe Module”, Lister List, British Origami Society, britishorigami.org (origin of the unit, documented from 1968).'},
        ],
        'links': [('The whole workshop', '/en/workshop/'), ('3D modelling', '/en/workshop/3d-modelling/'), ('Architecture and plans', '/en/workshop/architecture-plans/')],
    },
}

STRINGS = {
    'es': {
        'canvasLabel': 'Escenario del estudio de papiroflexia',
        'canvasHelp': 'Teclas 1 a 6: cambiar de vista. Sólido 3D: flechas para girar, + y − para acercar, [ y ] para plegar o desplegar, Re Pág y Av Pág para elegir caras. Pliegues: flechas para ir de un punto marcado a otro, Intro para elegirlo y, con dos puntos, Intro otra vez para plegar; V valle, M monte, S cambiar el lado, T solo la capa de arriba, F dar la vuelta, G paso guiado, Esc cancelar. Vértice plano: flechas para girar el cursor, Intro para añadir un pliegue, Supr para borrarlo. Grulla y Sonobe: flechas para pasar de paso.',
        'kModes': 'Teclas 1 a 6 (con el foco en el escenario): Sólido 3D, Red, Pliegues, Vértice, Grulla, Sonobe',
        'kPoly': 'Sólido 3D: [ y ] pliegan y despliegan 10 %; Inicio y Fin: 0 % y 100 %; Re Pág y Av Pág: cara anterior y siguiente',
        'kFold': 'Pliegues: flechas entre puntos; Intro elige; V valle; M monte; S cambia el lado; T solo capa de arriba; F dar la vuelta; G paso guiado',
        'kVertex': 'Vértice plano: flechas giran el cursor (Mayús: 15°); Intro añade o elige un pliegue; V o M cambian su tipo; Supr lo borra',
        'kSteps': 'Grulla y Sonobe: flecha derecha o Av Pág, paso siguiente; flecha izquierda o Re Pág, paso anterior',
        'modesLabel': 'Vistas del estudio',
        'mode_poly': 'Sólido 3D', 'mode_net': 'Red para imprimir', 'mode_fold': 'Pliegues', 'mode_vertex': 'Vértice plano', 'mode_crane': 'Grulla', 'mode_sonobe': 'Cubo Sonobe',
        'modeHelp_poly': 'Mueve «Plegado %» para desplegar el sólido.',
        'modeHelp_net': 'Colorea las caras e imprime la red a escala real.',
        'modeHelp_fold': 'Elige dos puntos marcados del papel y pliega.',
        'modeHelp_vertex': 'Añade pliegues alrededor del punto y comprueba si se aplanan.',
        'modeHelp_crane': 'Diagramas de la grulla paso a paso.',
        'modeHelp_sonobe': 'Pliega el módulo y monta el cubo pieza a pieza.',
        'modeNow': 'Vista: {name}.', 'goMode': 'Ir a {name}',
        'stIcosa': 'Desplegar un icosaedro', 'stIcosaD': 'Un sólido de 20 triángulos a medio desplegar. Mueve «Plegado %».',
        'stPlane': 'Avión de papel', 'stPlaneD': 'Modelo guiado con 8 pliegues simples en una hoja A4.',
        'stCup': 'Vaso de papel', 'stCupD': 'Modelo guiado con un cuadrado: 6 pasos.',
        'stCubeNet': 'Cubo para recortar', 'stCubeNetD': 'La red de un cubo con pestañas, lista para imprimir.',
        'stCrane': 'Reto: grulla', 'stCraneD': 'La grulla tradicional en 13 pasos con diagramas.',
        'stSonobe': 'Reto: cubo de piezas', 'stSonobeD': 'Módulo Sonobe: pliega 6 piezas y monta el cubo en 3D.',
        'stVertex': '¿Se aplana este vértice?', 'stVertexD': 'Un patrón de 4 pliegues para comprobar Maekawa y Kawasaki.',
        'stPrintable': 'Reto: poliedro propio para imprimir', 'stPrintableD': 'Octaedro truncado con colores y pestañas. Cambia el sólido, la arista y los colores.',
        'stHat': 'Gorro de papel', 'stHatD': 'Modelo guiado con una hoja A4: 6 pasos.',
        'stEnvelope': 'Sobre', 'stEnvelopeD': 'Modelo guiado con un cuadrado en rombo: 4 pasos.',
        'kind_tetra': 'Tetraedro', 'kind_cube': 'Cubo', 'kind_octa': 'Octaedro', 'kind_dodeca': 'Dodecaedro', 'kind_icosa': 'Icosaedro',
        'kind_ttetra': 'Tetraedro truncado', 'kind_cubocta': 'Cuboctaedro', 'kind_tocta': 'Octaedro truncado', 'kind_tcube': 'Cubo truncado', 'kind_icosidodeca': 'Icosidodecaedro',
        'kind_prism': 'Prisma', 'kind_antiprism': 'Antiprisma', 'kind_pyramid': 'Pirámide', 'kind_bipyramid': 'Bipirámide',
        'fam_platonic': 'Platónico', 'fam_archimedean': 'Arquimediano', 'fam_prism': 'Prismas', 'fam_pyramid': 'Pirámides',
        'nSides': 'base de {n} lados',
        'shape_3': 'triángulo', 'shape_4': 'cuadrilátero', 'shape_5': 'pentágono', 'shape_6': 'hexágono', 'shape_7': 'heptágono', 'shape_8': 'octógono',
        'shape_9': 'eneágono', 'shape_10': 'decágono', 'shape_11': 'endecágono', 'shape_12': 'dodecágono', 'shape_13': 'polígono',
        'solidLabel': 'Sólido', 'solidShort': 'Sólido', 'nLabel': 'Lados de la base (n)', 'hrLabel': 'Altura',
        'hrHelp': 'La altura se mide en veces la arista de la base. Con 1, las caras de los lados son cuadradas o triángulos iguales cuando se puede.',
        'hrHelpAnti': 'Con 1, todas las caras laterales son triángulos equiláteros.',
        'foldLabel': 'Plegado', 'foldValue': 'Plegado al {n} %', 'unfoldBtn': 'Desplegar', 'foldBtn': 'Plegar', 'toNet': 'Ver la red', 'to3d': 'Ver en 3D',
        'otherNet': 'Otra red', 'viewReset': 'Vista inicial', 'viewTop': 'Vista desde arriba', 'fitView': 'Ver todo',
        'foldHelp': 'Plegado al {n} %. Con 0 % ves la red plana; con 100 %, el sólido cerrado. Nada se mueve solo: tú mueves el control.',
        'recolour': 'Colores por tipo de cara', 'recoloured': 'Colores por tipo de cara',
        'factsTitle': 'Datos del sólido',
        'eulerLine': 'V − A + C = {v} − {e} + {f} = {r}',
        'eulerText': 'Vértices menos aristas más caras da 2: se cumple la fórmula de Euler.',
        'faceTable': 'Caras por tipo', 'colFace': 'Cara', 'colCount': 'Cuántas', 'colAngles': 'Ángulos interiores',
        'dihTable': 'Ángulos diedros (entre caras vecinas)', 'colBetween': 'Entre', 'colDihedral': 'Ángulo', 'colEdges': 'Aristas',
        'edgesMm': 'Aristas en la red impresa: {list} mm.',
        'defectText': 'Suma de los defectos angulares de todos los vértices: {d}°. En cualquier poliedro convexo da 720° (teorema de Descartes).',
        'facesTitle': 'Caras ({n})', 'faceN': 'Cara {n}', 'faceColour': 'Color de la cara', 'sameColourType': 'Mismo color en las caras iguales',
        'faceAngles': 'Ángulos interiores: {list}. Suman {sum}°.', 'faceNeighbours': 'Vecinas y ángulo diedro: {list}.',
        'faceSelected': 'Cara {n} elegida: {shape}.', 'deselect': 'Soltar la selección', 'deselected': 'Nada elegido.', 'selected': 'Elegido: {name}.',
        'colourSet': 'Color cambiado', 'colourAll': 'Color aplicado a las caras iguales', 'solidSet': 'Sólido: {name}', 'netChanged': 'Red {k} de {n}',
        'netSettings': 'Red para imprimir', 'edgeLabel': 'Arista', 'edgeSet': 'Arista de {mm} mm', 'edgeIs': 'arista de {mm} mm',
        'tabsLabel': 'Pestañas de pegado', 'tabsOn': 'Con pestañas', 'tabsOff': 'Sin pestañas', 'tabLabel': 'Ancho de las pestañas', 'tabSet': 'Ancho de pestañas cambiado',
        'numbersLabel': 'Números de pegado', 'fillLabel': 'Rellenar las caras de color', 'changedWord': 'Cambiado',
        'sideLabel': 'Cara impresa', 'sideOut': 'Por fuera', 'sideIn': 'Por dentro',
        'sideOutHelp': 'Lo impreso queda por fuera del sólido: todos los pliegues son en monte (raya y dos puntos).',
        'sideInHelp': 'Lo impreso queda por dentro: todos los pliegues son en valle (rayas).',
        'netOf': 'Red {k} de {n} sin solapes.',
        'printTitle': 'Impresión a escala real', 'fitsOne': 'Cabe en una hoja A4.', 'needsPages': 'Se reparte en {n} hojas A4.',
        'netSize': 'La red mide {w} × {h} mm.', 'reduceTo': 'Para que quepa en una sola hoja, pon una arista de {mm} mm o menos.',
        'fitOnePage': 'Ajustar a una hoja', 'printNet': 'Imprimir a escala real', 'downloadNet': 'Descargar la red (SVG)', 'downloadNetShort': 'Red en SVG',
        'printHelp': 'En el diálogo de impresión elige escala 100 % (tamaño real) y sin ajustar a la página. Mide la regla de 50 mm para comprobarlo.',
        'netTitle': 'Red de {name} con arista de {mm} mm', 'legCut': 'Cortar', 'legMountain': 'Pliegue en monte', 'legValley': 'Pliegue en valle', 'legTab': 'Pestaña: pégala en el borde con su número',
        'legCrease': 'Pliegue ya marcado',
        'scaleCheck': 'Esta línea mide 50 mm', 'sheetOf': 'hoja {i} de {n} (fila {r}, columna {c})',
        'tileHelp': 'Recorta cada hoja por la línea morada y superpón la franja de 10 mm con la hoja vecina antes de pegarla.',
        'hudPoly': '{name} · plegado {n} %', 'hudNet': 'Arista {mm} mm · {n} hoja(s) A4',
        'sumPoly': '{name}: {f} caras, {e} aristas y {v} vértices. Plegado al {fold} %.',
        'sumNet': 'Red de {name} con arista de {mm} mm: mide {w} × {h} mm, ocupa {pages} hoja(s) A4 y lleva {tabs} pestañas.',
        'no3d': 'Este navegador no puede mostrar 3D. La red, los pliegues y los diagramas funcionan igual.',
        'valleyWord': 'Valle', 'mountainWord': 'Monte', 'vShort': 'V', 'mShort': 'M',
        'doFold': 'Plegar', 'swapSide': 'Cambiar el lado', 'topOnly': 'Solo la capa de arriba', 'flipBtn': 'Dar la vuelta', 'rotateBtn': 'Girar 90°', 'cancelPick': 'Cancelar puntos',
        'doGuideStep': 'Hacer el paso guiado', 'printSheet': 'Imprimir la hoja de diagramas', 'downloadSheet': 'Descargar la hoja (SVG)',
        'topOnlyOn': 'Plegarás solo la capa de arriba.', 'topOnlyOff': 'Plegarás todas las capas.', 'sideSwapped': 'Ahora se mueve el otro lado.',
        'typeNow': 'Tipo de pliegue: {type}.', 'typeSet': 'Pliegue en {type}', 'cancelled': 'Cancelado.',
        'pickFirst': 'Toca un punto marcado para empezar la línea', 'pickSecond': 'Toca el segundo punto de la línea', 'pickTarget': 'Toca el punto al que quieres llevarlo',
        'readyToFold': 'Pulsa Plegar (o Intro)', 'needTwo': 'Primero elige dos puntos.', 'samePoint': 'Elige un punto distinto.',
        'pointPicked': 'Punto {n} en {x}, {y}.', 'pickedN': 'Puntos elegidos: {n}.', 'tapAMark': 'Toca uno de los puntos marcados del papel.',
        'cursorAt': 'Punto en {x}, {y}: {kind}.', 'markCorner': 'esquina', 'markMid': 'punto medio de un borde',
        'folded': 'Paso {n}: pliegue en {type}', 'flipped': 'Papel dado la vuelta', 'rotatedPaper': 'Papel girado 90°',
        'foldErr_line': 'Los dos puntos están demasiado juntos.', 'foldErr_nothing': 'La línea no cruza el papel: no hay nada que plegar.',
        'foldErr_topMountain': 'La capa de arriba solo se pliega en valle. Para plegarla hacia atrás, da la vuelta al papel.',
        'foldErr_tear': 'Esa solapa está unida a otras capas por otro borde: se rompería. Pliega todas las capas.',
        'paperStart': 'Papel sin plegar', 'paperSquare': 'Cuadrado', 'paperA4': 'A4', 'flipShort': 'Vuelta', 'rotateShort': 'Giro',
        'stepsTitle': 'Pasos ({n})', 'stepN': 'Paso {n}.', 'stepOf': 'Paso {k} de {n}.', 'stepNote': 'Texto del paso para la hoja de diagramas',
        'noteSet': 'Texto del paso cambiado', 'deleteFrom': 'Borrar este paso y los siguientes', 'deletedFrom': 'Borrado desde el paso {n}',
        'descFlip': 'Da la vuelta al papel.', 'descRotate': 'Gira el papel 90°.', 'descValley': 'Pliegue en valle', 'descMountain': 'Pliegue en monte',
        'descAll': 'de todas las capas.', 'descTop': 'solo de la capa de arriba.', 'finalResult': 'Resultado.',
        'paperTitle': 'Papel', 'guideLabel': 'Modelo guiado', 'guideNone': 'Ninguno: pliego a mi manera', 'guideLoaded': 'Modelo guiado: {name}', 'guideCleared': 'Sin modelo guiado',
        'guideTitle': 'Guía: {name}', 'guideDone': 'Modelo terminado.', 'guideOffTitle': 'Te has salido de la guía.',
        'guideOff': 'Deshaz tus últimos pliegues para volver a la guía, o sigue a tu manera.',
        'guideHint': 'La línea morada muestra dónde va el pliegue. Puedes hacerlo tú eligiendo los puntos o pulsar el botón.',
        'guideStepDone': 'Paso guiado {k} de {n} hecho', 'hudGuide': 'Guía: paso {k} de {n}',
        'guideName_plane': 'Avión de papel', 'guideName_cup': 'Vaso de papel', 'guideName_hat': 'Gorro de papel', 'guideName_envelope': 'Sobre',
        'guide_plane_1': 'Pliega la esquina de arriba a la izquierda hasta la línea del centro.',
        'guide_plane_2': 'Pliega la esquina de arriba a la derecha hasta la línea del centro.',
        'guide_plane_3': 'Pliega el nuevo borde inclinado de la izquierda hasta el centro.',
        'guide_plane_4': 'Haz lo mismo con el borde de la derecha. Queda una punta afilada.',
        'guide_plane_5': 'Pliega el avión por la mitad en monte: la mitad izquierda pasa por detrás.',
        'guide_plane_6': 'Pliega el ala de delante hacia abajo (solo la capa de arriba).',
        'guide_plane_7': 'Da la vuelta al avión.',
        'guide_plane_8': 'Pliega la otra ala igual.',
        'guideEnd_plane': 'Avión terminado. Abre las alas para que queden planas y lánzalo suave, hacia delante.',
        'guide_cup_1': 'Con el papel en rombo, pliega la punta de abajo hasta la de arriba: queda un triángulo.',
        'guide_cup_2': 'Lleva la esquina izquierda al borde derecho, de forma que su borde de arriba quede horizontal.',
        'guide_cup_3': 'Lleva la esquina derecha al borde izquierdo, igual que antes.',
        'guide_cup_4': 'Pliega hacia abajo la punta de delante (solo la capa de arriba).',
        'guide_cup_5': 'Da la vuelta.',
        'guide_cup_6': 'Pliega hacia abajo la otra punta.',
        'guideEnd_cup': 'Vaso terminado. Aprieta un poco los lados para abrir la boca.',
        'guide_hat_1': 'Con la hoja A4 en vertical, pliega el borde de arriba hasta el de abajo.',
        'guide_hat_2': 'Pliega la esquina de arriba a la izquierda hasta la línea del centro.',
        'guide_hat_3': 'Haz lo mismo con la esquina de la derecha.',
        'guide_hat_4': 'Pliega la tira de abajo hacia arriba (solo la capa de arriba).',
        'guide_hat_5': 'Da la vuelta.',
        'guide_hat_6': 'Pliega la otra tira hacia arriba.',
        'guideEnd_hat': 'Gorro terminado. Abre la parte de abajo para ponértelo. Con una hoja grande de papel de periódico cabe en la cabeza.',
        'guide_envelope_1': 'Con el papel en rombo, pliega la esquina izquierda hasta el centro.',
        'guide_envelope_2': 'Pliega la esquina derecha hasta el centro.',
        'guide_envelope_3': 'Pliega la esquina de abajo hacia arriba hasta el centro.',
        'guide_envelope_4': 'Pliega la esquina de arriba hacia abajo: es la solapa que cierra el sobre.',
        'guideEnd_envelope': 'Sobre terminado. Mete una nota dentro y cierra la solapa.',
        'paperShape': 'Forma del papel', 'paperOrient': 'Colocación', 'orientSquare': 'Recto', 'orientDiamond': 'En rombo',
        'paperChanged': 'Papel nuevo', 'paperChangeWarn': 'Cambiar la forma o la colocación empieza de nuevo (puedes deshacerlo).',
        'frontColour': 'Color de la cara', 'backColour': 'Color del dorso', 'paperColour': 'Color del papel',
        'pickMode': 'Cómo marcas el pliegue', 'pickLine': 'Línea por dos puntos', 'pickP2P': 'Llevar un punto sobre otro',
        'pickLineHelp': 'El pliegue pasa por los dos puntos que eliges. Se mueve el lado con menos papel; «Cambiar el lado» mueve el otro.',
        'pickP2PHelp': 'El primer punto se lleva encima del segundo, como en «lleva la esquina al centro».',
        'patternTitle': 'Patrón de pliegues', 'patternHelp': 'El papel desplegado con todas las marcas: rayas azules para valle y raya con dos puntos rojos para monte, vistas desde la cara de color.',
        'patternAlt': 'Patrón de pliegues del papel desplegado: {v} valles y {m} montes.',
        'replayErrors': '{n} paso(s) no se han podido repetir y se han saltado.',
        'sumFold': 'Papel con {steps} pasos, {layers} trozos de capa y {creases} pliegues marcados.',
        'mySheet': 'Mis pliegues · hoja de diagramas', 'sheetWord': 'hoja de diagramas', 'noSteps': 'Todavía no hay pasos: pliega algo primero.',
        'printing': 'Abriendo la impresión: {n} hoja(s).', 'pageN': 'Hoja {i} de {n}',
        'vertexTitle': 'Vértice plano', 'vertexHelp': 'Toca alrededor del punto central para añadir pliegues, o gira el cursor y pulsa «Añadir pliegue». Toca un pliegue para elegirlo.',
        'presetLabel': 'Ejemplos', 'presetChoose': 'Elige un ejemplo…', 'presetLoaded': 'Ejemplo: {name}',
        'preset_cross': 'Cruz: 4 pliegues a 90°', 'preset_kite': 'Cometa: 4 pliegues', 'preset_six': 'Seis pliegues', 'preset_bad': 'Un vértice que no se aplana',
        'cursorLabel': 'Ángulo del cursor', 'cursorAngle': 'Cursor a {a}°', 'addCrease': 'Añadir pliegue', 'deleteCrease': 'Borrar pliegue', 'clearCreases': 'Borrar todos',
        'creasesCleared': 'Pliegues borrados', 'creasesTitle': 'Pliegues ({n})', 'creaseN': 'Pliegue {n}',
        'creaseAdded': 'Pliegue en {type} a {a}°', 'creaseDeleted': 'Pliegue de {a}° borrado', 'creaseMoved': 'Pliegue movido a {a}°',
        'creaseSel': 'Pliegue {n}: {a}°, {type}.', 'tooManyCreases': 'Como máximo 16 pliegues.', 'noCreaseSel': 'Primero elige un pliegue.',
        'angleLabel': 'Ángulo', 'angleTaken': 'Ya hay un pliegue en ese ángulo.', 'typeLabel': 'Tipo',
        'turnLeft': 'Girar cursor a la izquierda', 'turnRight': 'Girar cursor a la derecha',
        'checkTitle': 'Comprobación', 'checkNeedTwo': 'Añade al menos dos pliegues.',
        'flatYes': 'Se puede aplanar.', 'flatNo': 'No se puede aplanar así.',
        'flatYesText': 'Cumple todas las condiciones y la reducción en zigzag termina bien.',
        'flatNoText': 'Mira qué condición falla y cambia un ángulo o el tipo de un pliegue.',
        'okWord': 'Cumple', 'failWord': 'No cumple',
        'chkEven': 'Número de pliegues par ({n}).',
        'chkMaekawa': 'Maekawa: {m} montes y {v} valles; se diferencian en {d} (debe ser 2).',
        'chkKawasaki': 'Kawasaki: ángulos alternos {a}° y {b}° (los dos deben ser 180°).',
        'chkBlbOk': 'Ángulo pequeño entre dos grandes: sus pliegues son distintos.',
        'chkBlbBad': 'Ángulo pequeño entre dos grandes con dos pliegues iguales: {list}.',
        'sectorTable': 'Ángulos entre pliegues', 'colSector': 'Sector', 'colAngle': 'Ángulo',
        'theoremsNote': 'Maekawa y Kawasaki son condiciones necesarias. La reducción en zigzag (quitar dos pliegues seguidos distintos alrededor de un ángulo que no es mayor que sus vecinos) decide el caso completo de un solo vértice.',
        'sumVertex': 'Vértice con {n} pliegues: {list}.',
        'craneSteps': 'Pasos de la grulla', 'sonobeSteps': 'Pasos del cubo Sonobe', 'sonUnitStep': 'Pieza · paso {n}', 'sonPiece': 'Montaje · pieza {n}',
        'prevStep': 'Paso anterior', 'nextStep': 'Paso siguiente', 'firstStepBtn': 'Primer paso', 'lastStep': 'Ya estás en el último paso.', 'firstStep': 'Ya estás en el primer paso.',
        'craneTitle': 'Grulla tradicional · diagramas', 'sonobeTitle': 'Cubo de 6 módulos Sonobe · diagramas',
        'craneHelp': 'Usa un cuadrado de 15 cm o más, fino. Marca bien cada pliegue con la uña.',
        'printCrane': 'Imprimir la grulla', 'downloadCrane': 'Descargar la grulla (SVG)', 'printSonobe': 'Imprimir el Sonobe', 'downloadSonobe': 'Descargar el Sonobe (SVG)',
        'sonColour': 'Color {n}', 'sonobeHelp': 'Haz 2 piezas de cada color: los colores iguales quedan en caras opuestas. Usa cuadrados de 7,5 cm.',
        'crane1': 'Empieza con el lado de color hacia arriba. Pliega en valle por las dos diagonales y desdobla.',
        'crane2': 'Da la vuelta al papel. Pliega por la mitad en los dos sentidos, de borde a borde, y desdobla.',
        'crane3': 'Junta las esquinas de la izquierda, la derecha y arriba con la de abajo, siguiendo los pliegues. Aplana: es la base preliminar, con la parte abierta abajo.',
        'crane4': 'Pliega los bordes de abajo de la capa de arriba hasta la línea del centro.',
        'crane5': 'Pliega el triángulo de arriba hacia abajo, por encima de las solapas. Marca bien.',
        'crane6': 'Desdobla los tres últimos pliegues. Quedan marcados.',
        'crane7': 'Pliegue de pétalo: levanta la punta de abajo de la capa de arriba por la línea horizontal. Los lados se meten hacia el centro por los pliegues marcados. Aplana.',
        'crane8': 'Da la vuelta y repite los pasos 4 a 7 por detrás.',
        'crane9': 'Esta es la base pájaro. Pliega los bordes de abajo de la capa de arriba hasta el centro para estrechar las patas. Repite por detrás.',
        'crane10': 'Pliegue invertido: mete cada pata hacia arriba entre las capas, por la línea marcada. Serán el cuello y la cola.',
        'crane11': 'Haz otro pliegue invertido en la punta del cuello para formar la cabeza.',
        'crane12': 'Pliega el ala de delante hacia abajo por la línea horizontal. Repite con el ala de detrás.',
        'crane13': 'Grulla terminada. Separa un poco las alas y aprieta con suavidad el centro para que el cuerpo se abra.',
        'son1': 'Usa un cuadrado con el lado blanco hacia arriba. Pliega por la mitad en valle y desdobla.',
        'son2': 'Pliega los bordes de la izquierda y la derecha hasta la línea del centro.',
        'son3': 'Pliega la esquina de abajo a la izquierda hacia arriba hasta el borde derecho, y la de arriba a la derecha hacia abajo hasta el borde izquierdo.',
        'son4': 'Desdobla las dos esquinas. Vuelve a plegarlas por la misma línea, pero mete cada triángulo por debajo de la solapa del otro lado.',
        'son5': 'Queda un paralelogramo. Dale la vuelta.',
        'son6': 'Pliega cada punta hasta la esquina de enfrente: queda un cuadrado.',
        'son7': 'Desdobla las dos puntas.',
        'son8': 'Pieza terminada. El cuadrado es una cara del cubo, las puntas rayadas son las pestañas y las líneas gruesas, los bolsillos. Dobla las puntas a 90°. Haz 6 piezas: 2 de cada color.',
        'sonA1': 'Pieza 1, abajo: déjala con las dos pestañas hacia arriba.',
        'sonA2': 'Pieza 2, a la derecha: mete en su bolsillo una pestaña de la pieza 1.',
        'sonA3': 'Pieza 3, delante: encaja sus pestañas con las piezas 1 y 2.',
        'sonA4': 'Pieza 4, a la izquierda: igual que la pieza 2, al otro lado.',
        'sonA5': 'Pieza 5, detrás: cierra los lados.',
        'sonA6': 'Pieza 6, arriba: mete sus dos pestañas en los bolsillos libres. Cubo terminado: todas las pestañas quedan dentro de un bolsillo.',
        'sonAssemblyPrint': 'Montaje: une las 6 piezas metiendo cada pestaña en el bolsillo de una vecina. Cada color va en dos caras opuestas.',
        'exportNetSvg': 'Red del poliedro (SVG en mm)', 'exportNetPrint': 'Imprimir la red a escala real…',
        'exportSheetSvg': 'Hoja de diagramas de tus pliegues (SVG)', 'exportSheetPrint': 'Imprimir la hoja de diagramas…',
        'exportCraneSvg': 'Diagramas de la grulla (SVG)', 'exportCranePrint': 'Imprimir la grulla…',
        'exportSonobeSvg': 'Diagramas del cubo Sonobe (SVG)', 'exportSonobePrint': 'Imprimir el cubo Sonobe…',
        'exportPng': 'Imagen de la vista 3D (PNG)',
    },
    'en': {
        'canvasLabel': 'Origami studio stage',
        'canvasHelp': 'Keys 1 to 6: change view. 3D solid: arrows to turn, + and − to zoom, [ and ] to fold or unfold, Page Up and Page Down to choose faces. Folding: arrows to move between marked points, Enter to choose one and, with two points, Enter again to fold; V valley, M mountain, S swap side, T top layer only, F flip over, G guided step, Esc cancel. Flat vertex: arrows to turn the cursor, Enter to add a crease, Delete to remove it. Crane and Sonobe: arrows to change step.',
        'kModes': 'Keys 1 to 6 (with focus on the stage): 3D solid, Net, Folding, Vertex, Crane, Sonobe',
        'kPoly': '3D solid: [ and ] fold and unfold by 10 %; Home and End: 0 % and 100 %; Page Up and Page Down: previous and next face',
        'kFold': 'Folding: arrows between points; Enter chooses; V valley; M mountain; S swaps side; T top layer only; F flip over; G guided step',
        'kVertex': 'Flat vertex: arrows turn the cursor (Shift: 15°); Enter adds or picks a crease; V or M change its type; Delete removes it',
        'kSteps': 'Crane and Sonobe: right arrow or Page Down, next step; left arrow or Page Up, previous step',
        'modesLabel': 'Studio views',
        'mode_poly': '3D solid', 'mode_net': 'Printable net', 'mode_fold': 'Folding', 'mode_vertex': 'Flat vertex', 'mode_crane': 'Crane', 'mode_sonobe': 'Sonobe cube',
        'modeHelp_poly': 'Move “Folded %” to unfold the solid.',
        'modeHelp_net': 'Colour the faces and print the net at true scale.',
        'modeHelp_fold': 'Choose two marked points on the paper and fold.',
        'modeHelp_vertex': 'Add creases around the point and check whether they fold flat.',
        'modeHelp_crane': 'Step-by-step crane diagrams.',
        'modeHelp_sonobe': 'Fold the unit and build the cube piece by piece.',
        'modeNow': 'View: {name}.', 'goMode': 'Go to {name}',
        'stIcosa': 'Unfold an icosahedron', 'stIcosaD': 'A solid of 20 triangles, half unfolded. Move “Folded %”.',
        'stPlane': 'Paper plane', 'stPlaneD': 'Guided model with 8 simple folds on an A4 sheet.',
        'stCup': 'Paper cup', 'stCupD': 'Guided model from a square: 6 steps.',
        'stCubeNet': 'Cut-out cube', 'stCubeNetD': 'A cube net with tabs, ready to print.',
        'stCrane': 'Challenge: crane', 'stCraneD': 'The traditional crane in 13 diagram steps.',
        'stSonobe': 'Challenge: modular cube', 'stSonobeD': 'Sonobe unit: fold 6 pieces and build the cube in 3D.',
        'stVertex': 'Does this vertex fold flat?', 'stVertexD': 'A 4-crease pattern to check Maekawa and Kawasaki.',
        'stPrintable': 'Challenge: your own printable polyhedron', 'stPrintableD': 'Truncated octahedron with colours and tabs. Change the solid, the edge and the colours.',
        'stHat': 'Paper hat', 'stHatD': 'Guided model from an A4 sheet: 6 steps.',
        'stEnvelope': 'Envelope', 'stEnvelopeD': 'Guided model from a square turned like a diamond: 4 steps.',
        'kind_tetra': 'Tetrahedron', 'kind_cube': 'Cube', 'kind_octa': 'Octahedron', 'kind_dodeca': 'Dodecahedron', 'kind_icosa': 'Icosahedron',
        'kind_ttetra': 'Truncated tetrahedron', 'kind_cubocta': 'Cuboctahedron', 'kind_tocta': 'Truncated octahedron', 'kind_tcube': 'Truncated cube', 'kind_icosidodeca': 'Icosidodecahedron',
        'kind_prism': 'Prism', 'kind_antiprism': 'Antiprism', 'kind_pyramid': 'Pyramid', 'kind_bipyramid': 'Bipyramid',
        'fam_platonic': 'Platonic', 'fam_archimedean': 'Archimedean', 'fam_prism': 'Prisms', 'fam_pyramid': 'Pyramids',
        'nSides': '{n}-sided base',
        'shape_3': 'triangle', 'shape_4': 'quadrilateral', 'shape_5': 'pentagon', 'shape_6': 'hexagon', 'shape_7': 'heptagon', 'shape_8': 'octagon',
        'shape_9': 'nonagon', 'shape_10': 'decagon', 'shape_11': 'hendecagon', 'shape_12': 'dodecagon', 'shape_13': 'polygon',
        'solidLabel': 'Solid', 'solidShort': 'Solid', 'nLabel': 'Sides of the base (n)', 'hrLabel': 'Height',
        'hrHelp': 'Height is measured in base edges. At 1, the side faces are squares, or equal triangles where possible.',
        'hrHelpAnti': 'At 1, every side face is an equilateral triangle.',
        'foldLabel': 'Folded', 'foldValue': '{n} % folded', 'unfoldBtn': 'Unfold', 'foldBtn': 'Fold', 'toNet': 'See the net', 'to3d': 'See in 3D',
        'otherNet': 'Another net', 'viewReset': 'Starting view', 'viewTop': 'View from above', 'fitView': 'Fit to view',
        'foldHelp': '{n} % folded. At 0 % you see the flat net; at 100 %, the closed solid. Nothing moves on its own: you move the control.',
        'recolour': 'Colours by face type', 'recoloured': 'Colours by face type',
        'factsTitle': 'About this solid',
        'eulerLine': 'V − E + F = {v} − {e} + {f} = {r}',
        'eulerText': 'Vertices minus edges plus faces gives 2: Euler’s formula holds.',
        'faceTable': 'Faces by type', 'colFace': 'Face', 'colCount': 'How many', 'colAngles': 'Interior angles',
        'dihTable': 'Dihedral angles (between neighbouring faces)', 'colBetween': 'Between', 'colDihedral': 'Angle', 'colEdges': 'Edges',
        'edgesMm': 'Edges on the printed net: {list} mm.',
        'defectText': 'Sum of the angular defects of all vertices: {d}°. For any convex polyhedron it is 720° (Descartes’ theorem).',
        'facesTitle': 'Faces ({n})', 'faceN': 'Face {n}', 'faceColour': 'Face colour', 'sameColourType': 'Same colour on matching faces',
        'faceAngles': 'Interior angles: {list}. They add up to {sum}°.', 'faceNeighbours': 'Neighbours and dihedral angle: {list}.',
        'faceSelected': 'Face {n} selected: {shape}.', 'deselect': 'Clear selection', 'deselected': 'Nothing selected.', 'selected': 'Selected: {name}.',
        'colourSet': 'Colour changed', 'colourAll': 'Colour applied to matching faces', 'solidSet': 'Solid: {name}', 'netChanged': 'Net {k} of {n}',
        'netSettings': 'Printable net', 'edgeLabel': 'Edge', 'edgeSet': '{mm} mm edge', 'edgeIs': '{mm} mm edge',
        'tabsLabel': 'Glue tabs', 'tabsOn': 'With tabs', 'tabsOff': 'Without tabs', 'tabLabel': 'Tab width', 'tabSet': 'Tab width changed',
        'numbersLabel': 'Glue numbers', 'fillLabel': 'Fill faces with colour', 'changedWord': 'Changed',
        'sideLabel': 'Printed side', 'sideOut': 'Outside', 'sideIn': 'Inside',
        'sideOutHelp': 'The print ends up on the outside of the solid: every fold is a mountain fold (dash and two dots).',
        'sideInHelp': 'The print ends up inside: every fold is a valley fold (dashes).',
        'netOf': 'Net {k} of {n} with no overlaps.',
        'printTitle': 'True-scale printing', 'fitsOne': 'Fits on one A4 sheet.', 'needsPages': 'Spread over {n} A4 sheets.',
        'netSize': 'The net measures {w} × {h} mm.', 'reduceTo': 'To fit it on one sheet, use an edge of {mm} mm or less.',
        'fitOnePage': 'Fit to one sheet', 'printNet': 'Print at true scale', 'downloadNet': 'Download the net (SVG)', 'downloadNetShort': 'Net as SVG',
        'printHelp': 'In the print dialogue choose 100 % scale (actual size), not “fit to page”. Measure the 50 mm ruler to check.',
        'netTitle': 'Net of {name} with a {mm} mm edge', 'legCut': 'Cut', 'legMountain': 'Mountain fold', 'legValley': 'Valley fold', 'legTab': 'Tab: glue it to the edge with its number',
        'legCrease': 'Existing crease',
        'scaleCheck': 'This line is 50 mm long', 'sheetOf': 'sheet {i} of {n} (row {r}, column {c})',
        'tileHelp': 'Trim each sheet along the purple line and overlap the 10 mm strip with the next sheet before gluing.',
        'hudPoly': '{name} · {n} % folded', 'hudNet': '{mm} mm edge · {n} A4 sheet(s)',
        'sumPoly': '{name}: {f} faces, {e} edges and {v} vertices. {fold} % folded.',
        'sumNet': 'Net of {name} with a {mm} mm edge: {w} × {h} mm, on {pages} A4 sheet(s), with {tabs} tabs.',
        'no3d': 'This browser cannot show 3D. The net, the folding and the diagrams still work.',
        'valleyWord': 'Valley', 'mountainWord': 'Mountain', 'vShort': 'V', 'mShort': 'M',
        'doFold': 'Fold', 'swapSide': 'Swap side', 'topOnly': 'Top layer only', 'flipBtn': 'Flip over', 'rotateBtn': 'Turn 90°', 'cancelPick': 'Cancel points',
        'doGuideStep': 'Do the guided step', 'printSheet': 'Print the diagram sheet', 'downloadSheet': 'Download the sheet (SVG)',
        'topOnlyOn': 'You will fold the top layer only.', 'topOnlyOff': 'You will fold every layer.', 'sideSwapped': 'The other side moves now.',
        'typeNow': 'Fold type: {type}.', 'typeSet': '{type} fold', 'cancelled': 'Cancelled.',
        'pickFirst': 'Tap a marked point to start the line', 'pickSecond': 'Tap the second point of the line', 'pickTarget': 'Tap the point you want to bring it to',
        'readyToFold': 'Press Fold (or Enter)', 'needTwo': 'Choose two points first.', 'samePoint': 'Choose a different point.',
        'pointPicked': 'Point {n} at {x}, {y}.', 'pickedN': 'Points chosen: {n}.', 'tapAMark': 'Tap one of the marked points on the paper.',
        'cursorAt': 'Point at {x}, {y}: {kind}.', 'markCorner': 'corner', 'markMid': 'middle of an edge',
        'folded': 'Step {n}: {type} fold', 'flipped': 'Paper flipped over', 'rotatedPaper': 'Paper turned 90°',
        'foldErr_line': 'The two points are too close together.', 'foldErr_nothing': 'The line does not cross the paper: there is nothing to fold.',
        'foldErr_topMountain': 'The top layer can only be valley-folded. To fold it backwards, flip the paper over.',
        'foldErr_tear': 'That flap is joined to other layers along another edge: it would tear. Fold every layer.',
        'paperStart': 'Unfolded paper', 'paperSquare': 'Square', 'paperA4': 'A4', 'flipShort': 'Flip', 'rotateShort': 'Turn',
        'stepsTitle': 'Steps ({n})', 'stepN': 'Step {n}.', 'stepOf': 'Step {k} of {n}.', 'stepNote': 'Step text for the diagram sheet',
        'noteSet': 'Step text changed', 'deleteFrom': 'Delete this step and the ones after it', 'deletedFrom': 'Deleted from step {n}',
        'descFlip': 'Flip the paper over.', 'descRotate': 'Turn the paper 90°.', 'descValley': 'Valley fold', 'descMountain': 'Mountain fold',
        'descAll': 'through every layer.', 'descTop': 'of the top layer only.', 'finalResult': 'Result.',
        'paperTitle': 'Paper', 'guideLabel': 'Guided model', 'guideNone': 'None: I will fold my own way', 'guideLoaded': 'Guided model: {name}', 'guideCleared': 'No guided model',
        'guideTitle': 'Guide: {name}', 'guideDone': 'Model finished.', 'guideOffTitle': 'You have left the guide.',
        'guideOff': 'Undo your last folds to go back to the guide, or carry on your own way.',
        'guideHint': 'The purple line shows where the fold goes. You can make it yourself by choosing the points, or press the button.',
        'guideStepDone': 'Guided step {k} of {n} done', 'hudGuide': 'Guide: step {k} of {n}',
        'guideName_plane': 'Paper plane', 'guideName_cup': 'Paper cup', 'guideName_hat': 'Paper hat', 'guideName_envelope': 'Envelope',
        'guide_plane_1': 'Fold the top left corner to the centre line.',
        'guide_plane_2': 'Fold the top right corner to the centre line.',
        'guide_plane_3': 'Fold the new sloping edge on the left to the centre.',
        'guide_plane_4': 'Do the same with the edge on the right. You get a sharp point.',
        'guide_plane_5': 'Mountain-fold the plane in half: the left half goes behind.',
        'guide_plane_6': 'Fold the front wing down (top layer only).',
        'guide_plane_7': 'Flip the plane over.',
        'guide_plane_8': 'Fold the other wing the same way.',
        'guideEnd_plane': 'Plane finished. Open the wings so they are flat and throw it gently forwards.',
        'guide_cup_1': 'With the paper as a diamond, fold the bottom point up to the top one: you get a triangle.',
        'guide_cup_2': 'Bring the left corner to the right edge so that its top edge is level.',
        'guide_cup_3': 'Bring the right corner to the left edge in the same way.',
        'guide_cup_4': 'Fold the front point down (top layer only).',
        'guide_cup_5': 'Flip it over.',
        'guide_cup_6': 'Fold the other point down.',
        'guideEnd_cup': 'Cup finished. Squeeze the sides a little to open it.',
        'guide_hat_1': 'With the A4 sheet upright, fold the top edge down to the bottom edge.',
        'guide_hat_2': 'Fold the top left corner to the centre line.',
        'guide_hat_3': 'Do the same with the right corner.',
        'guide_hat_4': 'Fold the bottom strip up (top layer only).',
        'guide_hat_5': 'Flip it over.',
        'guide_hat_6': 'Fold the other strip up.',
        'guideEnd_hat': 'Hat finished. Open the bottom to put it on. Made from a large sheet of newspaper, it fits a head.',
        'guide_envelope_1': 'With the paper as a diamond, fold the left corner to the centre.',
        'guide_envelope_2': 'Fold the right corner to the centre.',
        'guide_envelope_3': 'Fold the bottom corner up to the centre.',
        'guide_envelope_4': 'Fold the top corner down: this is the flap that closes the envelope.',
        'guideEnd_envelope': 'Envelope finished. Put a note inside and close the flap.',
        'paperShape': 'Paper shape', 'paperOrient': 'Position', 'orientSquare': 'Straight', 'orientDiamond': 'As a diamond',
        'paperChanged': 'New paper', 'paperChangeWarn': 'Changing the shape or position starts again (you can undo it).',
        'frontColour': 'Front colour', 'backColour': 'Back colour', 'paperColour': 'Paper colour',
        'pickMode': 'How you mark the fold', 'pickLine': 'Line through two points', 'pickP2P': 'Bring one point onto another',
        'pickLineHelp': 'The fold goes through the two points you choose. The side with less paper moves; “Swap side” moves the other one.',
        'pickP2PHelp': 'The first point is brought on top of the second, as in “bring the corner to the centre”.',
        'patternTitle': 'Crease pattern', 'patternHelp': 'The unfolded paper with every crease: blue dashes for valley and red dash-and-two-dots for mountain, seen from the coloured side.',
        'patternAlt': 'Crease pattern of the unfolded paper: {v} valleys and {m} mountains.',
        'replayErrors': '{n} step(s) could not be repeated and were skipped.',
        'sumFold': 'Paper with {steps} steps, {layers} layer pieces and {creases} creases.',
        'mySheet': 'My folds · diagram sheet', 'sheetWord': 'diagram sheet', 'noSteps': 'There are no steps yet: fold something first.',
        'printing': 'Opening the print dialogue: {n} sheet(s).', 'pageN': 'Sheet {i} of {n}',
        'vertexTitle': 'Flat vertex', 'vertexHelp': 'Tap around the centre point to add creases, or turn the cursor and press “Add crease”. Tap a crease to select it.',
        'presetLabel': 'Examples', 'presetChoose': 'Choose an example…', 'presetLoaded': 'Example: {name}',
        'preset_cross': 'Cross: 4 creases at 90°', 'preset_kite': 'Kite: 4 creases', 'preset_six': 'Six creases', 'preset_bad': 'A vertex that does not fold flat',
        'cursorLabel': 'Cursor angle', 'cursorAngle': 'Cursor at {a}°', 'addCrease': 'Add crease', 'deleteCrease': 'Delete crease', 'clearCreases': 'Delete all',
        'creasesCleared': 'Creases deleted', 'creasesTitle': 'Creases ({n})', 'creaseN': 'Crease {n}',
        'creaseAdded': '{type} crease at {a}°', 'creaseDeleted': 'Crease at {a}° deleted', 'creaseMoved': 'Crease moved to {a}°',
        'creaseSel': 'Crease {n}: {a}°, {type}.', 'tooManyCreases': '16 creases at most.', 'noCreaseSel': 'Select a crease first.',
        'angleLabel': 'Angle', 'angleTaken': 'There is already a crease at that angle.', 'typeLabel': 'Type',
        'turnLeft': 'Turn cursor left', 'turnRight': 'Turn cursor right',
        'checkTitle': 'Check', 'checkNeedTwo': 'Add at least two creases.',
        'flatYes': 'It folds flat.', 'flatNo': 'It does not fold flat like this.',
        'flatYesText': 'It meets every condition and the zigzag reduction finishes correctly.',
        'flatNoText': 'See which condition fails and change an angle or a crease type.',
        'okWord': 'Met', 'failWord': 'Not met',
        'chkEven': 'Even number of creases ({n}).',
        'chkMaekawa': 'Maekawa: {m} mountains and {v} valleys; they differ by {d} (it must be 2).',
        'chkKawasaki': 'Kawasaki: alternate angles {a}° and {b}° (both must be 180°).',
        'chkBlbOk': 'Small angle between two bigger ones: its creases are different.',
        'chkBlbBad': 'Small angle between two bigger ones with two matching creases: {list}.',
        'sectorTable': 'Angles between creases', 'colSector': 'Sector', 'colAngle': 'Angle',
        'theoremsNote': 'Maekawa and Kawasaki are necessary conditions. The zigzag reduction (removing two neighbouring, different creases around an angle no bigger than its neighbours) settles the whole single-vertex case.',
        'sumVertex': 'Vertex with {n} creases: {list}.',
        'craneSteps': 'Crane steps', 'sonobeSteps': 'Sonobe cube steps', 'sonUnitStep': 'Unit · step {n}', 'sonPiece': 'Assembly · piece {n}',
        'prevStep': 'Previous step', 'nextStep': 'Next step', 'firstStepBtn': 'First step', 'lastStep': 'This is already the last step.', 'firstStep': 'This is already the first step.',
        'craneTitle': 'Traditional crane · diagrams', 'sonobeTitle': 'Cube of 6 Sonobe units · diagrams',
        'craneHelp': 'Use a thin square of 15 cm or more. Crease each fold firmly with a fingernail.',
        'printCrane': 'Print the crane', 'downloadCrane': 'Download the crane (SVG)', 'printSonobe': 'Print the Sonobe', 'downloadSonobe': 'Download the Sonobe (SVG)',
        'sonColour': 'Colour {n}', 'sonobeHelp': 'Make 2 pieces of each colour: matching colours end up on opposite faces. Use 7.5 cm squares.',
        'crane1': 'Start with the coloured side up. Valley-fold along both diagonals and unfold.',
        'crane2': 'Flip the paper over. Fold it in half both ways, edge to edge, and unfold.',
        'crane3': 'Bring the left, right and top corners down to the bottom one along the creases. Flatten: this is the preliminary base, open end at the bottom.',
        'crane4': 'Fold the lower edges of the top layer to the centre line.',
        'crane5': 'Fold the top triangle down over the flaps. Crease firmly.',
        'crane6': 'Unfold the last three folds. They stay creased.',
        'crane7': 'Petal fold: lift the bottom point of the top layer along the horizontal crease. The sides tuck in towards the centre along the creases. Flatten.',
        'crane8': 'Flip it over and repeat steps 4 to 7 on the back.',
        'crane9': 'This is the bird base. Fold the lower edges of the top layer to the centre to narrow the legs. Repeat on the back.',
        'crane10': 'Inside reverse fold: push each leg up between the layers along the marked line. They become the neck and the tail.',
        'crane11': 'Make another reverse fold at the tip of the neck to form the head.',
        'crane12': 'Fold the front wing down along the horizontal line. Repeat with the back wing.',
        'crane13': 'Crane finished. Spread the wings a little and press the centre gently so the body opens.',
        'son1': 'Use a square with the white side up. Valley-fold it in half and unfold.',
        'son2': 'Fold the left and right edges to the centre line.',
        'son3': 'Fold the bottom left corner up to the right edge, and the top right corner down to the left edge.',
        'son4': 'Unfold both corners. Fold them again along the same line, but tuck each triangle under the flap on the other side.',
        'son5': 'You have a parallelogram. Flip it over.',
        'son6': 'Fold each point to the opposite corner: you get a square.',
        'son7': 'Unfold both points.',
        'son8': 'Unit finished. The square is one face of the cube, the striped points are the tabs and the thick lines are the pockets. Bend the points to 90°. Make 6 units: 2 of each colour.',
        'sonA1': 'Piece 1, at the bottom: leave it with both tabs pointing up.',
        'sonA2': 'Piece 2, on the right: slide a tab of piece 1 into its pocket.',
        'sonA3': 'Piece 3, at the front: fit its tabs with pieces 1 and 2.',
        'sonA4': 'Piece 4, on the left: like piece 2, on the other side.',
        'sonA5': 'Piece 5, at the back: close the sides.',
        'sonA6': 'Piece 6, on top: slide its two tabs into the free pockets. Cube finished: every tab sits inside a pocket.',
        'sonAssemblyPrint': 'Assembly: join the 6 pieces by sliding each tab into a neighbour’s pocket. Each colour goes on two opposite faces.',
        'exportNetSvg': 'Polyhedron net (SVG in mm)', 'exportNetPrint': 'Print the net at true scale…',
        'exportSheetSvg': 'Diagram sheet of your folds (SVG)', 'exportSheetPrint': 'Print the diagram sheet…',
        'exportCraneSvg': 'Crane diagrams (SVG)', 'exportCranePrint': 'Print the crane…',
        'exportSonobeSvg': 'Sonobe cube diagrams (SVG)', 'exportSonobePrint': 'Print the Sonobe cube…',
        'exportPng': 'Image of the 3D view (PNG)',
    },
}
assert set(STRINGS['es']) == set(STRINGS['en']), set(STRINGS['es']) ^ set(STRINGS['en'])
assert set(PAGE['es']) == set(PAGE['en'])
