"""Estudio de patrones y arte generativo (R43): simetría plana (17 grupos), rosetón, Truchet y sistemas L. Textos ES/EN.

Fuentes comprobadas:
- Schattschneider, D. (1978). The Plane Symmetry Groups: Their Recognition and Notation. The American Mathematical
  Monthly, 85(6), 439-450.
- Conway, J. H., Burgiel, H. y Goodman-Strauss, C. (2008). The Symmetries of Things. A K Peters, Wellesley (MA).
- Prusinkiewicz, P. y Lindenmayer, A. (1990). The Algorithmic Beauty of Plants. Springer-Verlag, Nueva York.
- Smith, C. S. (1987). The Tiling Patterns of Sebastien Truchet and the Topology of Structural Hierarchy.
  Leonardo, 20(4), 373-385 (con traducción de P. Boucher). doi:10.2307/1578535
Las operaciones de cada grupo siguen los representantes de las International Tables for Crystallography, vol. A.
"""

ENGINE = 'patrones'
SLUG = {'es': 'patrones', 'en': 'patterns-generative-art'}
SCRIPTS = ['ig-suite-patrones.js']
STYLES = ['ig-suite-patrones.css']
LIBRARIES = 'Ninguna biblioteca externa: geometría y SVG propios de Iris Green'
LIBRARIES_EN = 'No outside libraries: Iris Green’s own geometry and SVG'

GROUPS = {
    'p1': ('Solo traslaciones', 'Only translations',
           'El motivo se repite desplazándose en dos direcciones, sin girar ni reflejarse.',
           'The motif repeats by sliding in two directions, with no turns or reflections.'),
    'p2': ('Medios giros', 'Half turns',
           'Además de trasladarse, el motivo da medias vueltas (180°) alrededor de cuatro tipos de centros.',
           'As well as sliding, the motif makes half turns (180°) around four kinds of centre.'),
    'pm': ('Espejos paralelos', 'Parallel mirrors',
           'Espejos en una sola dirección: cada fila es el reflejo de la de al lado.',
           'Mirrors in one direction only: each row is the reflection of the next.'),
    'pg': ('Deslizamientos paralelos', 'Parallel glides',
           'Una reflexión deslizante: el motivo se refleja y avanza medio paso, como las huellas al andar.',
           'A glide reflection: the motif reflects and moves on half a step, like footprints when you walk.'),
    'cm': ('Espejos y deslizamientos', 'Mirrors and glides',
           'Espejos paralelos con deslizamientos entre ellos; la retícula es rómbica (rectangular centrada).',
           'Parallel mirrors with glides between them; the lattice is rhombic (centred rectangular).'),
    'pmm': ('Espejos en cruz', 'Crossed mirrors',
            'Espejos en dos direcciones perpendiculares; donde se cruzan hay medios giros.',
            'Mirrors in two perpendicular directions; where they cross there are half turns.'),
    'pmg': ('Espejos y deslizamientos cruzados', 'Mirrors crossed by glides',
            'Espejos en una dirección y deslizamientos en la otra, con medios giros fuera de los espejos.',
            'Mirrors in one direction and glides in the other, with half turns off the mirrors.'),
    'pgg': ('Deslizamientos cruzados', 'Crossed glides',
            'Deslizamientos en dos direcciones perpendiculares y medios giros; no hay espejos.',
            'Glides in two perpendicular directions and half turns; there are no mirrors.'),
    'cmm': ('Espejos en cruz, retícula centrada', 'Crossed mirrors, centred lattice',
            'Espejos en dos direcciones y medios giros también fuera de los espejos; retícula rómbica.',
            'Mirrors in two directions and half turns also off the mirrors; rhombic lattice.'),
    'p4': ('Cuartos de giro', 'Quarter turns',
           'El motivo gira 90° alrededor de centros de orden 4; también hay medios giros. Sin espejos.',
           'The motif turns 90° around order-4 centres; there are also half turns. No mirrors.'),
    'p4m': ('Cuadrado con todos los espejos', 'Square with every mirror',
            'Cuartos de giro con espejos que pasan por todos los centros, también en diagonal.',
            'Quarter turns with mirrors through every centre, diagonals included.'),
    'p4g': ('Cuadrado con espejos girados', 'Square with turned mirrors',
            'Cuartos de giro cuyos centros no están en los espejos; los espejos forman una red en diagonal. Muy frecuente en azulejos.',
            'Quarter turns whose centres are not on the mirrors; the mirrors form a diagonal grid. Common in tiles.'),
    'p3': ('Tercios de giro', 'Third turns',
           'Giros de 120° alrededor de tres tipos de centros, en retícula hexagonal. Sin espejos.',
           'Turns of 120° around three kinds of centre, on a hexagonal lattice. No mirrors.'),
    'p3m1': ('Tercios de giro con espejos en los centros', 'Third turns with mirrors through the centres',
             'Giros de 120° y espejos que pasan por todos los centros de giro.',
             'Turns of 120° and mirrors through every centre of turning.'),
    'p31m': ('Tercios de giro con un centro libre', 'Third turns with one free centre',
             'Giros de 120° y espejos, pero un tipo de centro queda fuera de los espejos.',
             'Turns of 120° and mirrors, but one kind of centre stays off the mirrors.'),
    'p6': ('Sextos de giro', 'Sixth turns',
           'Giros de 60°, 120° y 180° en retícula hexagonal. Sin espejos: el patrón parece girar.',
           'Turns of 60°, 120° and 180° on a hexagonal lattice. No mirrors: the pattern seems to spin.'),
    'p6m': ('Hexagonal con todos los espejos', 'Hexagonal with every mirror',
            'La simetría más rica: sextos de giro y espejos en seis direcciones, como un copo de nieve repetido.',
            'The richest symmetry: sixth turns and mirrors in six directions, like a repeated snowflake.'),
}

PAGE = {
    'es': {
        'title': 'Patrones y arte generativo',
        'description': 'Compón un motivo y repítelo con los 17 grupos de simetría plana, crea rosetones, teselas de Truchet y fractales con sistemas L. Todo vectorial, con exportación SVG, PNG, azulejo sin costuras y reglas.',
        'lede': 'Un patrón es un motivo más una regla para repetirlo. Cambia la regla y el mismo motivo da mosaicos muy distintos.',
        'make': ['Un mosaico con un solo azulejo', 'Los 17 tipos de simetría plana', 'Un rosetón de flores', 'Teselas de Truchet', 'Un fractal con tus propias reglas', 'SVG, PNG, azulejo sin costuras y reglas en JSON'],
        'steps': [
            'Elige un modo arriba: Simetría plana, Rosetón, Truchet o Fractal.',
            'En Simetría plana y Rosetón, toca una forma para elegirla; muévela con el dedo, con las flechas o con los números de Propiedades.',
            'Cambia el grupo o el número de giros en Propiedades. Activa «Ejes» para ver espejos y centros de giro.',
            'Exporta desde Archivo: SVG, PNG, azulejo repetible o las reglas.',
        ],
        'sections': [
            {'h': 'Los 17 grupos', 'p': 'Un mosaico plano que se repite en dos direcciones solo puede tener 17 tipos de simetría. El nombre corto (p4g, cmm…) es la notación internacional; el otro (4*2, 2*22…) es la notación orbifold de Conway: los números son giros, el asterisco marca espejos y la × marca deslizamientos.\n\nLa celda es el paralelogramo que se repite. Un espejo refleja el motivo; un deslizamiento lo refleja y lo avanza; un centro de giro de orden n lo gira 360°/n.'},
            {'h': 'Rosetones', 'p': 'Un rosetón no se repite a lo largo del plano: gira alrededor de un centro. Cn tiene n giros; Dn añade n espejos. Solo existen esas dos familias.'},
            {'h': 'Truchet y Smith', 'p': 'Sébastien Truchet estudió en 1704 un cuadrado partido en dos triángulos y colocado en cuatro posiciones. Cyril Stanley Smith propuso en 1987 dos arcos de cuarto de círculo: las curvas enlazan siempre de un azulejo a otro. La semilla hace que el azar se pueda repetir: la misma semilla da el mismo dibujo.'},
            {'h': 'Sistemas L', 'p': 'Un sistema L parte de un axioma y aplica reglas de sustitución una y otra vez. Luego una tortuga lo dibuja: F avanza dibujando, f avanza sin dibujar, + y − giran, [ guarda la posición y ] vuelve a ella. El estudio para al llegar a 60 000 segmentos.'},
            {'h': 'Fuentes', 'p': 'Schattschneider, D. (1978). The Plane Symmetry Groups: Their Recognition and Notation. The American Mathematical Monthly, 85(6), 439-450.\n\nConway, J. H., Burgiel, H. y Goodman-Strauss, C. (2008). The Symmetries of Things. A K Peters.\n\nPrusinkiewicz, P. y Lindenmayer, A. (1990). The Algorithmic Beauty of Plants. Springer-Verlag.\n\nSmith, C. S. (1987). The Tiling Patterns of Sebastien Truchet and the Topology of Structural Hierarchy. Leonardo, 20(4), 373-385.'},
        ],
        'links': [('Todo el taller', '/es/taller/'), ('Color', '/es/taller/color/'), ('Diseño gráfico', '/es/taller/diseno-grafico/')],
    },
    'en': {
        'title': 'Patterns and generative art',
        'description': 'Build a motif and repeat it with the 17 wallpaper groups, make rosettes, Truchet tiles and fractals with L-systems. All vector, with SVG, PNG, seamless tile and rules export.',
        'lede': 'A pattern is a motif plus a rule for repeating it. Change the rule and the same motif makes very different tilings.',
        'make': ['A mosaic using one tile', 'The 17 wallpaper symmetry groups', 'A flower rosette', 'Truchet tiles', 'A fractal with your own rules', 'SVG, PNG, seamless tile and rules as JSON'],
        'steps': [
            'Choose a mode at the top: Wallpaper symmetry, Rosette, Truchet or Fractal.',
            'In Wallpaper symmetry and Rosette, tap a shape to select it; move it with your finger, the arrow keys or the numbers in Properties.',
            'Change the group or the number of turns in Properties. Turn on “Axes” to see mirrors and centres of turning.',
            'Export from File: SVG, PNG, repeatable tile or the rules.',
        ],
        'sections': [
            {'h': 'The 17 groups', 'p': 'A flat pattern that repeats in two directions can only have 17 types of symmetry. The short name (p4g, cmm…) is the international notation; the other one (4*2, 2*22…) is Conway’s orbifold notation: numbers are turns, the asterisk marks mirrors and the × marks glides.\n\nThe cell is the parallelogram that repeats. A mirror reflects the motif; a glide reflects it and moves it on; a centre of order n turns it by 360°/n.'},
            {'h': 'Rosettes', 'p': 'A rosette does not repeat across the plane: it turns around a centre. Cn has n turns; Dn adds n mirrors. Those are the only two families.'},
            {'h': 'Truchet and Smith', 'p': 'In 1704 Sébastien Truchet studied a square split into two triangles and placed in four positions. In 1987 Cyril Stanley Smith suggested two quarter-circle arcs: the curves always join up from one tile to the next. The seed makes chance repeatable: the same seed gives the same drawing.'},
            {'h': 'L-systems', 'p': 'An L-system starts from an axiom and applies replacement rules again and again. Then a turtle draws it: F moves forward drawing, f moves without drawing, + and − turn, [ saves the position and ] goes back to it. The studio stops at 60,000 segments.'},
            {'h': 'Sources', 'p': 'Schattschneider, D. (1978). The Plane Symmetry Groups: Their Recognition and Notation. The American Mathematical Monthly, 85(6), 439-450.\n\nConway, J. H., Burgiel, H. and Goodman-Strauss, C. (2008). The Symmetries of Things. A K Peters.\n\nPrusinkiewicz, P. and Lindenmayer, A. (1990). The Algorithmic Beauty of Plants. Springer-Verlag.\n\nSmith, C. S. (1987). The Tiling Patterns of Sebastien Truchet and the Topology of Structural Hierarchy. Leonardo, 20(4), 373-385.'},
        ],
        'links': [('The whole workshop', '/en/workshop/'), ('Colour', '/en/workshop/colour/'), ('Graphic design', '/en/workshop/graphic-design/')],
    },
}

STRINGS = {
    'es': {
        'canvasLabel': 'Lienzo de patrones',
        'canvasHelp': 'En Simetría plana y Rosetón: corchetes [ y ] eligen una forma; las flechas la mueven 2 unidades (10 con Mayús); R la gira 15°; Supr la borra; Esc suelta la selección. Con una herramienta de forma, Intro añade esa forma en el centro de la celda. En Truchet, las flechas mueven un cursor de azulejo e Intro lo gira. En Fractal, arriba y abajo cambian las iteraciones y los lados, el ángulo. + y − acercan y alejan; 0 encuadra.',
        'kPatMove': 'Simetría y rosetón: [ y ] eligen forma; flechas la mueven (Mayús: paso largo); R la gira',
        'kPatShape': 'Con una herramienta de forma, Intro añade la forma en el centro de la celda',
        'kPatTile': 'Truchet: flechas mueven el cursor de azulejo; Intro lo gira; Supr lo devuelve a la regla',
        'kPatLsys': 'Fractal: flechas arriba y abajo, iteraciones; izquierda y derecha, ángulo',
        'stOneTile': 'Mosaico con un solo azulejo', 'stOneTileD': 'Reto: un azulejo girado cuatro veces llena todo el suelo (grupo p4).',
        'stSeventeen': '17 tipos de simetría plana', 'stSeventeenD': 'Reto: un motivo sin simetría propia para recorrer los 17 grupos con los ejes a la vista.',
        'stOwnFractal': 'Fractal con reglas propias', 'stOwnFractalD': 'Reto: parte de una rama sencilla y cambia sus reglas hasta que sea tuya.',
        'stFlowers': 'Rosetón de flores', 'stFlowersD': 'Pétalos, hojas y bayas repetidos seis veces con espejos (D6).',
        'stTruchet': 'Teselas de Truchet', 'stTruchetD': 'Arcos de Smith colocados al azar con semilla: cambia la semilla o gira azulejos a mano.',
        'stP4g': 'Azulejo con simetría p4g', 'stP4gD': 'Un azulejo cerámico con cuartos de giro y espejos en diagonal.',
        'stKoch': 'Copo de Koch', 'stKochD': 'El fractal clásico: cada lado se convierte en cuatro.',
        'mode_wall': 'Simetría plana', 'mode_rose': 'Rosetón', 'mode_truchet': 'Truchet', 'mode_lsys': 'Fractal (sistema L)', 'modes': 'Modos', 'modeLabel': 'Modo',
        'sh_circle': 'Círculo', 'sh_square': 'Cuadrado', 'sh_triangle': 'Triángulo', 'sh_petal': 'Pétalo', 'sh_line': 'Línea', 'sh_stroke': 'Trazo',
        'toolSelect': 'Elegir', 'toolTile': 'Girar azulejo', 'toolPan': 'Mover la vista', 'fitView': 'Encuadrar', 'axesBtn': 'Ejes', 'axesOn': 'Ejes y centros visibles', 'axesOff': 'Ejes ocultos',
        'iterMinus': 'Menos iteraciones', 'iterPlus': 'Más iteraciones', 'iterNow': 'Iteraciones: {n}',
        'motifN': 'Motivo ({n} formas)', 'motifEmpty': 'El motivo está vacío. Añade una forma.', 'handTiles': 'Azulejos girados a mano ({n})', 'handTilesEmpty': 'Toca un azulejo para girarlo.',
        'tileAt': 'Azulejo de la columna {x}, fila {y}', 'orientN': 'posición {n}', 'lsRules': 'Axioma y reglas', 'lsAxiom': 'Axioma',
        'colourHex': 'Color {hex}', 'customColour': 'Otro color', 'colourWord': 'de color', 'sizeWord': 'tamaño',
        'moved': 'Movido', 'added': 'Añadido: {what}', 'deleted': 'Borrado: {what}', 'selected': 'Elegido: {what}', 'deselected': 'Nada elegido.',
        'changed': 'Cambiado', 'rotated': 'Girado', 'colourChanged': 'Color cambiado', 'reordered': 'Orden cambiado', 'duplicated': 'Forma duplicada',
        'tooManyShapes': 'Un motivo tiene como mucho 40 formas.', 'tileRotated': 'Azulejo {x}, {y} girado', 'tileReset': 'Azulejo devuelto a la regla',
        'groupNow': 'Grupo {g} ({orb}): {name}', 'sizeLabel': 'Tamaño', 'rotLabel': 'Giro', 'swLabel': 'Grosor del trazo', 'colourLabel': 'Color',
        'toFront': 'Al frente', 'toBack': 'Al fondo', 'duplicate': 'Duplicar', 'deleteBtn': 'Borrar',
        'shapeHelp': 'Las posiciones son de la copia original del motivo. Todas las copias cambian a la vez.',
        'wallTitle': 'Mosaico', 'groupLabel': 'Grupo de simetría', 'orbWord': 'orbifold',
        'lat_oblique': 'Retícula oblicua', 'lat_rect': 'Retícula rectangular', 'lat_rhombic': 'Retícula rómbica', 'lat_square': 'Retícula cuadrada', 'lat_hex': 'Retícula hexagonal',
        'copiesN': 'Cada celda tiene {n} copias del motivo.', 'cellSize': 'Tamaño de la celda', 'ratioLabel': 'Alto de la celda (proporción)', 'skewLabel': 'Inclinación de la retícula',
        'showCell': 'Ver la celda', 'showAxes': 'Ver ejes y centros de simetría', 'lgMirror': 'Espejo', 'lgGlide': 'Deslizamiento (reflejo y avance)', 'lgRot': 'Centros de giro de orden 2, 3, 4 y 6',
        'bgLabel': 'Fondo', 'fgLabel': 'Color del dibujo', 'addShape': 'Añadir al motivo',
        'roseTitle': 'Rosetón', 'roseN': 'Número de giros (n)', 'roseKind': 'Tipo', 'roseC': 'Cn: solo giros', 'roseD': 'Dn: giros y espejos', 'roseNow': 'Rosetón {s}',
        'roseCD': 'Cn: el motivo gira {n} veces alrededor del centro, como las aspas de un molino.', 'roseDD': 'Dn: {n} giros y {n} espejos, como un copo de nieve o una flor.',
        'truchetTitle': 'Teselas', 'variantLabel': 'Tipo de azulejo', 'var_triangles': 'Triángulos (Truchet)', 'var_arcs': 'Arcos (Smith)', 'var_lines': 'Diagonales',
        'var_trianglesD': 'Un cuadrado partido en dos triángulos: cuatro posiciones.', 'var_arcsD': 'Dos cuartos de círculo que unen lados vecinos: dos posiciones, curvas que enlazan.', 'var_linesD': 'Una diagonal: dos posiciones; forma laberintos.',
        'ruleLabel': 'Regla de colocación', 'rule_random': 'Al azar (con semilla)', 'rule_checker': 'Ajedrez', 'rule_rows': 'Por filas', 'rule_diagonal': 'En diagonal',
        'seedLabel': 'Semilla', 'seedShort': 'semilla', 'newSeed': 'Nueva semilla', 'seedNow': 'Semilla «{s}»', 'clearHand': 'Quitar giros a mano', 'handCleared': 'Azulejos devueltos a la regla',
        'colsLabel': 'Columnas', 'rowsLabel': 'Filas', 'tileSize': 'Tamaño del azulejo', 'rotateTile': 'Girar este azulejo', 'resetTile': 'Devolver a la regla',
        'lsTitle': 'Sistema L', 'lsPreset': 'Ejemplo', 'lsChoose': 'Elige un ejemplo…', 'pre_koch': 'Copo de Koch', 'pre_sierpinski': 'Triángulo de Sierpinski', 'pre_dragon': 'Curva del dragón', 'pre_plant': 'Planta',
        'presetNow': 'Ejemplo: {name}', 'lsAxiomLabel': 'Axioma (punto de partida)', 'lsPredN': 'Regla {n}: símbolo', 'lsSuccN': 'Regla {n}: se cambia por', 'lsPred': 'Símbolo', 'lsSucc': 'Se cambia por',
        'lsRuleN': 'Regla {n}', 'lsDelRule': 'Borrar regla', 'lsAddRule': 'Añadir regla', 'rulesChanged': 'Reglas cambiadas',
        'lsErrTitle': 'Hay que corregir las reglas', 'lsErrAxiom': 'El axioma no puede estar vacío.', 'lsErrChar': 'El símbolo «{c}» {where} no se entiende. Usa letras y + − [ ] |.',
        'lsErrBrackets': 'Los corchetes {where} no están emparejados: cada [ necesita su ].', 'lsErrPred': 'La regla {n} necesita una sola letra como símbolo.', 'lsErrDup': 'Hay dos reglas para «{c}». Deja solo una.',
        'where_axiom': 'del axioma', 'where_rule': 'de la regla {n}',
        'lsSegs': '{n} segmentos, {it} iteraciones', 'lsCapped': ' Se ha parado en {it} iteraciones para no pasar de {max} segmentos.',
        'lsAngle': 'Ángulo de giro', 'lsIter': 'Iteraciones', 'lsHeading': 'Dirección inicial', 'lsDraw': 'Letras que dibujan',
        'lsHelp': 'F y G avanzan dibujando (puedes cambiar cuáles), f avanza sin dibujar, + gira a la izquierda, − a la derecha, [ guarda la posición, ] vuelve a ella y | da media vuelta. Las demás letras solo sirven para las reglas.',
        'challengeTitle': 'Reto', 'ch_onetile': 'Mosaico con un solo azulejo', 'ch_onetileD': 'Diseña un azulejo con varias formas. El grupo lo gira y lo refleja para llenar todo el plano sin huecos.',
        'ch_seventeen': '17 tipos de simetría plana', 'ch_seventeenD': 'Pasa por los 17 grupos con este motivo. Mira los ejes en cada uno y busca la diferencia entre espejos y deslizamientos.',
        'ch_ownfractal': 'Fractal con reglas propias', 'ch_ownfractalD': 'Cambia el axioma o las reglas, el ángulo y las iteraciones hasta que salga un fractal que no esté en los ejemplos.',
        'seenN': 'Has visto {n} de 17 grupos', 'seenAll': '¡Has visto los 17 grupos!', 'seenWord': 'visto', 'notSeenWord': 'sin ver', 'nextGroup': 'Siguiente grupo',
        'chkOwnRules': 'Tus reglas son distintas de las del punto de partida y de los ejemplos.', 'chkValid': 'Las reglas no tienen errores.', 'chkSegs': 'El dibujo tiene {n} segmentos (se piden 50 o más).',
        'chkCopies': 'Copias del azulejo en cada celda: {n} (se piden 2 o más).', 'chkShapes': 'El azulejo tiene {n} formas (se piden 3 o más).', 'okWord': 'Cumple', 'checkWord': 'Pendiente',
        'sumWall': 'Mosaico con simetría {g} (orbifold {orb}, {name}), {lat} de celda {a}. {copies} copias del motivo por celda. Fondo {bg}. Motivo de {n} formas:',
        'sumAxes': 'Se ven los espejos, los deslizamientos y los centros de giro.',
        'sumRose': 'Rosetón {s}: {n} giros y {m} espejos. Fondo {bg}. Motivo de {k} formas:',
        'sumTruchet': 'Teselas de {v}: {c} × {r} azulejos de {s}, regla {rule}, semilla «{seed}», {hand} girados a mano. Dibujo {fg} sobre {bg}.',
        'sumLsys': 'Sistema L con axioma {ax} y reglas {rules}. Ángulo {a}°, {it} iteraciones, {n} segmentos de color {fg}.',
        'exportSvg': 'Patrón (SVG)', 'exportPng': 'Patrón (PNG)', 'exportTile': 'Azulejo repetible sin costuras (PNG)', 'exportRules': 'Reglas del patrón (JSON)',
        'exportTitle': 'Patrón {what} · El taller de Iris Green', 'exportError': 'No se ha podido exportar. Inténtalo de nuevo.', 'fileWord': 'Archivo',
        'tileDone': 'Azulejo descargado: se repite sin costuras.',
    },
    'en': {
        'canvasLabel': 'Pattern canvas',
        'canvasHelp': 'In Wallpaper symmetry and Rosette: the [ and ] keys choose a shape; the arrow keys move it 2 units (10 with Shift); R turns it 15°; Delete removes it; Esc clears the selection. With a shape tool, Enter adds that shape in the middle of the cell. In Truchet, the arrow keys move a tile cursor and Enter turns the tile. In Fractal, up and down change the iterations and left and right the angle. + and − zoom in and out; 0 fits the view.',
        'kPatMove': 'Wallpaper and rosette: [ and ] choose a shape; arrow keys move it (Shift: bigger step); R turns it',
        'kPatShape': 'With a shape tool, Enter adds the shape in the middle of the cell',
        'kPatTile': 'Truchet: arrow keys move the tile cursor; Enter turns it; Delete puts it back to the rule',
        'kPatLsys': 'Fractal: up and down arrows, iterations; left and right, angle',
        'stOneTile': 'Mosaic using one tile', 'stOneTileD': 'Challenge: one tile turned four times fills the whole floor (group p4).',
        'stSeventeen': 'The 17 wallpaper symmetry groups', 'stSeventeenD': 'Challenge: a motif with no symmetry of its own, to go through all 17 groups with the axes showing.',
        'stOwnFractal': 'A fractal with your own rules', 'stOwnFractalD': 'Challenge: start from a simple branch and change its rules until it is yours.',
        'stFlowers': 'Flower rosette', 'stFlowersD': 'Petals, leaves and berries repeated six times with mirrors (D6).',
        'stTruchet': 'Truchet tiles', 'stTruchetD': 'Smith’s arcs placed at random with a seed: change the seed or turn tiles by hand.',
        'stP4g': 'Tile with p4g symmetry', 'stP4gD': 'A ceramic tile with quarter turns and diagonal mirrors.',
        'stKoch': 'Koch snowflake', 'stKochD': 'The classic fractal: every side turns into four.',
        'mode_wall': 'Wallpaper symmetry', 'mode_rose': 'Rosette', 'mode_truchet': 'Truchet', 'mode_lsys': 'Fractal (L-system)', 'modes': 'Modes', 'modeLabel': 'Mode',
        'sh_circle': 'Circle', 'sh_square': 'Square', 'sh_triangle': 'Triangle', 'sh_petal': 'Petal', 'sh_line': 'Line', 'sh_stroke': 'Stroke',
        'toolSelect': 'Select', 'toolTile': 'Turn tile', 'toolPan': 'Move the view', 'fitView': 'Fit to view', 'axesBtn': 'Axes', 'axesOn': 'Axes and centres showing', 'axesOff': 'Axes hidden',
        'iterMinus': 'Fewer iterations', 'iterPlus': 'More iterations', 'iterNow': 'Iterations: {n}',
        'motifN': 'Motif ({n} shapes)', 'motifEmpty': 'The motif is empty. Add a shape.', 'handTiles': 'Tiles turned by hand ({n})', 'handTilesEmpty': 'Tap a tile to turn it.',
        'tileAt': 'Tile in column {x}, row {y}', 'orientN': 'position {n}', 'lsRules': 'Axiom and rules', 'lsAxiom': 'Axiom',
        'colourHex': 'Colour {hex}', 'customColour': 'Another colour', 'colourWord': 'in', 'sizeWord': 'size',
        'moved': 'Moved', 'added': '{what} added', 'deleted': 'Deleted: {what}', 'selected': 'Selected: {what}', 'deselected': 'Nothing selected.',
        'changed': 'Changed', 'rotated': 'Turned', 'colourChanged': 'Colour changed', 'reordered': 'Order changed', 'duplicated': 'Shape duplicated',
        'tooManyShapes': 'A motif has 40 shapes at most.', 'tileRotated': 'Tile {x}, {y} turned', 'tileReset': 'Tile put back to the rule',
        'groupNow': 'Group {g} ({orb}): {name}', 'sizeLabel': 'Size', 'rotLabel': 'Turn', 'swLabel': 'Line thickness', 'colourLabel': 'Colour',
        'toFront': 'To front', 'toBack': 'To back', 'duplicate': 'Duplicate', 'deleteBtn': 'Delete',
        'shapeHelp': 'Positions belong to the original copy of the motif. Every copy changes at once.',
        'wallTitle': 'Tiling', 'groupLabel': 'Symmetry group', 'orbWord': 'orbifold',
        'lat_oblique': 'Oblique lattice', 'lat_rect': 'Rectangular lattice', 'lat_rhombic': 'Rhombic lattice', 'lat_square': 'Square lattice', 'lat_hex': 'Hexagonal lattice',
        'copiesN': 'Each cell holds {n} copies of the motif.', 'cellSize': 'Cell size', 'ratioLabel': 'Cell height (ratio)', 'skewLabel': 'Lattice slant',
        'showCell': 'Show the cell', 'showAxes': 'Show symmetry axes and centres', 'lgMirror': 'Mirror', 'lgGlide': 'Glide (reflect and move on)', 'lgRot': 'Centres of turning of order 2, 3, 4 and 6',
        'bgLabel': 'Background', 'fgLabel': 'Drawing colour', 'addShape': 'Add to the motif',
        'roseTitle': 'Rosette', 'roseN': 'Number of turns (n)', 'roseKind': 'Type', 'roseC': 'Cn: turns only', 'roseD': 'Dn: turns and mirrors', 'roseNow': 'Rosette {s}',
        'roseCD': 'Cn: the motif turns {n} times around the centre, like the sails of a windmill.', 'roseDD': 'Dn: {n} turns and {n} mirrors, like a snowflake or a flower.',
        'truchetTitle': 'Tiles', 'variantLabel': 'Tile type', 'var_triangles': 'Triangles (Truchet)', 'var_arcs': 'Arcs (Smith)', 'var_lines': 'Diagonals',
        'var_trianglesD': 'A square split into two triangles: four positions.', 'var_arcsD': 'Two quarter circles joining neighbouring sides: two positions, curves that link up.', 'var_linesD': 'One diagonal: two positions; it makes mazes.',
        'ruleLabel': 'Placement rule', 'rule_random': 'Random (with a seed)', 'rule_checker': 'Chequerboard', 'rule_rows': 'By rows', 'rule_diagonal': 'Diagonal',
        'seedLabel': 'Seed', 'seedShort': 'seed', 'newSeed': 'New seed', 'seedNow': 'Seed “{s}”', 'clearHand': 'Undo hand turns', 'handCleared': 'Tiles put back to the rule',
        'colsLabel': 'Columns', 'rowsLabel': 'Rows', 'tileSize': 'Tile size', 'rotateTile': 'Turn this tile', 'resetTile': 'Put back to the rule',
        'lsTitle': 'L-system', 'lsPreset': 'Example', 'lsChoose': 'Choose an example…', 'pre_koch': 'Koch snowflake', 'pre_sierpinski': 'Sierpiński triangle', 'pre_dragon': 'Dragon curve', 'pre_plant': 'Plant',
        'presetNow': 'Example: {name}', 'lsAxiomLabel': 'Axiom (starting point)', 'lsPredN': 'Rule {n}: symbol', 'lsSuccN': 'Rule {n}: replaced by', 'lsPred': 'Symbol', 'lsSucc': 'Replaced by',
        'lsRuleN': 'Rule {n}', 'lsDelRule': 'Delete rule', 'lsAddRule': 'Add rule', 'rulesChanged': 'Rules changed',
        'lsErrTitle': 'The rules need fixing', 'lsErrAxiom': 'The axiom cannot be empty.', 'lsErrChar': 'The symbol “{c}” {where} is not understood. Use letters and + − [ ] |.',
        'lsErrBrackets': 'The brackets {where} do not pair up: every [ needs its ].', 'lsErrPred': 'Rule {n} needs a single letter as its symbol.', 'lsErrDup': 'There are two rules for “{c}”. Keep only one.',
        'where_axiom': 'in the axiom', 'where_rule': 'in rule {n}',
        'lsSegs': '{n} segments, {it} iterations', 'lsCapped': ' It stopped at {it} iterations so as not to go over {max} segments.',
        'lsAngle': 'Turning angle', 'lsIter': 'Iterations', 'lsHeading': 'Starting direction', 'lsDraw': 'Letters that draw',
        'lsHelp': 'F and G move forward drawing (you can change which), f moves forward without drawing, + turns left, − turns right, [ saves the position, ] goes back to it and | turns round. Other letters are only used by the rules.',
        'challengeTitle': 'Challenge', 'ch_onetile': 'Mosaic using one tile', 'ch_onetileD': 'Design a tile with several shapes. The group turns and reflects it to fill the whole plane with no gaps.',
        'ch_seventeen': 'The 17 wallpaper symmetry groups', 'ch_seventeenD': 'Go through all 17 groups with this motif. Look at the axes in each one and find the difference between mirrors and glides.',
        'ch_ownfractal': 'A fractal with your own rules', 'ch_ownfractalD': 'Change the axiom or the rules, the angle and the iterations until you get a fractal that is not in the examples.',
        'seenN': 'You have seen {n} of the 17 groups', 'seenAll': 'You have seen all 17 groups!', 'seenWord': 'seen', 'notSeenWord': 'not seen', 'nextGroup': 'Next group',
        'chkOwnRules': 'Your rules differ from the starting point and the examples.', 'chkValid': 'The rules have no errors.', 'chkSegs': 'The drawing has {n} segments (50 or more needed).',
        'chkCopies': 'Copies of the tile in each cell: {n} (2 or more needed).', 'chkShapes': 'The tile has {n} shapes (3 or more needed).', 'okWord': 'Done', 'checkWord': 'To do',
        'sumWall': 'Tiling with {g} symmetry (orbifold {orb}, {name}), {lat} with cell size {a}. {copies} copies of the motif per cell. Background {bg}. Motif of {n} shapes:',
        'sumAxes': 'Mirrors, glides and centres of turning are showing.',
        'sumRose': 'Rosette {s}: {n} turns and {m} mirrors. Background {bg}. Motif of {k} shapes:',
        'sumTruchet': '{v} tiles: {c} × {r} tiles of size {s}, rule {rule}, seed “{seed}”, {hand} turned by hand. Drawing {fg} on {bg}.',
        'sumLsys': 'L-system with axiom {ax} and rules {rules}. Angle {a}°, {it} iterations, {n} segments in {fg}.',
        'exportSvg': 'Pattern (SVG)', 'exportPng': 'Pattern (PNG)', 'exportTile': 'Seamless repeatable tile (PNG)', 'exportRules': 'Pattern rules (JSON)',
        'exportTitle': 'Pattern {what} · Iris Green’s workshop', 'exportError': 'Could not export. Please try again.', 'fileWord': 'File',
        'tileDone': 'Tile downloaded: it repeats without seams.',
    },
}
for _g, (_es, _en, _des, _den) in GROUPS.items():
    STRINGS['es']['grp_' + _g] = _es
    STRINGS['en']['grp_' + _g] = _en
    STRINGS['es']['grpD_' + _g] = _des
    STRINGS['en']['grpD_' + _g] = _den
assert set(STRINGS['es']) == set(STRINGS['en'])
assert set(PAGE['es']) == set(PAGE['en'])
