"""Estudio de simulaciones (R43): autómatas celulares, tráfico y ecosistemas. Textos ES/EN."""

ENGINE = 'simulaciones'
SLUG = {'es': 'simulaciones', 'en': 'simulations'}
SCRIPTS = ['ig-suite-transit.js', 'ig-suite-simulaciones.js']
STYLES = ['ig-suite-simulaciones.css']
LIBRARIES = 'Canvas 2D del navegador y cálculo propio de Iris Green (sin bibliotecas externas)'
LIBRARIES_EN = 'The browser’s 2D canvas and Iris Green’s own calculations (no outside libraries)'

PAGE = {
    'es': {
        'title': 'Simulaciones',
        'description': 'Sistemas con reglas sencillas que dan comportamientos sorprendentes: el juego de la vida, autómatas de Wolfram, atascos fantasma, un cruce con semáforo y ecosistemas de conejos y zorros. Con gráficos, tabla de datos y exportación.',
        'lede': 'Una simulación repite unas pocas reglas muchas veces y enseña qué sale. Aquí puedes cambiar las reglas, avanzar paso a paso y ver en un gráfico qué pasa con las células, los coches o los animales.',
        'make': [
            'Colonias del juego de la vida con planeadores, osciladores y el cañón de Gosper',
            'Dibujos de autómatas de una fila con cualquier regla de 0 a 255',
            'Atascos fantasma en una carretera circular y un cruce con semáforo',
            'Ecosistemas de hierba, conejos y zorros, y el modelo de Lotka-Volterra con su diagrama de fases',
            'Datos en CSV, gráficos e imágenes en PNG y patrones de Life en formato RLE',
        ],
        'steps': [
            'Elige un modelo en la barra de herramientas o en Estructura. Nada se mueve hasta que pulsas Iniciar o Paso.',
            'Cambia las reglas en Propiedades: elige un elemento en Estructura (la regla, la carretera, los zorros…) para ver sus valores.',
            'En el juego de la vida, pinta células con el lápiz o coloca patrones con el cursor del teclado (flechas e Intro).',
            'Mira el gráfico junto a la simulación. El botón «Tabla de datos» da los mismos datos en una tabla.',
            'Con la misma semilla, Reiniciar repite exactamente la misma simulación. Guarda el proyecto o exporta datos e imágenes en Archivo.',
        ],
        'sections': [
            {'h': 'Tres retos', 'p': 'Juego de la vida: empieza con 12 células o menos y consigue que la colonia siga viva en la generación 100. Red de tráfico: ajusta el semáforo para que, durante 300 segundos, ninguna calle tenga más de 9 coches en cola. Ecosistema equilibrado: que conejos y zorros vivan 500 pasos. Están en «Nuevo…» y su estado se ve siempre en Propiedades.'},
            {'h': 'Autómatas celulares', 'p': 'Una rejilla de células vivas o muertas. En cada generación todas cambian a la vez según cuántas vecinas vivas tienen: nace con 3 y sobrevive con 2 o 3 se escribe B3/S23 (B de nacer, S de sobrevivir, en inglés). Cambia esos números y salen otras reglas, como HighLife (B36/S23).\n\nEl autómata elemental tiene una sola fila. Cada casilla mira a su izquierda, a sí misma y a su derecha: 8 combinaciones, y la regla dice qué sale en cada una. Esas 8 respuestas, leídas como un número binario, dan el número de la regla, de 0 a 255 (código de Wolfram).'},
            {'h': 'Atascos fantasma', 'p': 'En el modelo de Nagel y Schreckenberg cada celda mide unos 7,5 metros y cada paso dura un segundo. Los coches aceleran, frenan para no chocar y a veces frenan sin motivo. Con bastantes coches, ese frenazo se convierte en un atasco que avanza hacia atrás sin que haya ningún obstáculo: se ve como una franja roja inclinada en el diagrama espacio-tiempo.'},
            {'h': 'Conejos y zorros', 'p': 'Por agentes, cada animal es un individuo con energía: se mueve, come, puede tener crías y muere si se queda sin energía. En Lotka-Volterra no hay individuos, sino dos cantidades que cambian de forma continua; el estudio las resuelve con Runge-Kutta de cuarto orden (RK4), que calcula cuatro pendientes por paso y se equivoca muy poco. En el diagrama de fases, cada punto es un par (presas, depredadores) y la curva cerrada muestra que las dos poblaciones suben y bajan una detrás de otra.'},
            {'h': 'Sin destellos y a tu ritmo', 'p': 'Nada se mueve hasta que tú lo pides, como mucho 10 pasos por segundo, y puedes pausarlo cuando quieras. Las células son pequeñas y la pantalla nunca se invierte entera. Si tu dispositivo pide menos movimiento, el estudio empieza en modo paso a paso. Cada gráfico tiene su tabla de datos.'},
            {'h': 'Límites del modelo', 'p': 'Son modelos simplificados para aprender cómo aparecen los patrones. No sirven para predecir el tráfico real ni poblaciones reales.'},
            {'h': 'Fuentes', 'p': 'Gardner, M. (1970). «Mathematical Games: The fantastic combinations of John Conway\u2019s new solitaire game \u201clife\u201d». Scientific American, 223(4), 120-123.\n\nWolfram, S. (1983). «Statistical mechanics of cellular automata». Reviews of Modern Physics, 55(3), 601-644. doi:10.1103/RevModPhys.55.601\n\nNagel, K. y Schreckenberg, M. (1992). «A cellular automaton model for freeway traffic». Journal de Physique I, 2(12), 2221-2229. doi:10.1051/jp1:1992277\n\nLotka, A. J. (1925). Elements of Physical Biology. Baltimore: Williams & Wilkins.\n\nVolterra, V. (1926). «Fluctuations in the abundance of a species considered mathematically». Nature, 118, 558-560. doi:10.1038/118558a0\n\nButcher, J. C. (2016). Numerical Methods for Ordinary Differential Equations (3.\u00aa ed.). Chichester: Wiley.'},
        ],
        'links': [('Todo el taller', '/es/taller/'), ('Programación', '/es/taller/programacion/'), ('Estructuras y puentes', '/es/taller/estructuras/')],
    },
    'en': {
        'title': 'Simulations',
        'description': 'Systems with simple rules that behave in surprising ways: the Game of Life, Wolfram automata, phantom traffic jams, a junction with traffic lights and ecosystems of rabbits and foxes. With charts, a data table and exports.',
        'lede': 'A simulation repeats a few rules many times and shows what comes out. Here you can change the rules, move forward step by step and see on a chart what happens to the cells, the cars or the animals.',
        'make': [
            'Game of Life colonies with gliders, oscillators and the Gosper glider gun',
            'One-row automaton drawings with any rule from 0 to 255',
            'Phantom jams on a ring road and a junction with traffic lights',
            'Ecosystems of grass, rabbits and foxes, and the Lotka-Volterra model with its phase diagram',
            'CSV data, PNG charts and images, and Life patterns in RLE format',
        ],
        'steps': [
            'Choose a model in the toolbar or under Structure. Nothing moves until you press Start or Step.',
            'Change the rules under Properties: choose an item under Structure (the rule, the road, the foxes…) to see its values.',
            'In the Game of Life, paint cells with the pencil or place patterns with the keyboard cursor (arrow keys and Enter).',
            'Look at the chart next to the simulation. The “Data table” button gives the same data as a table.',
            'With the same seed, Reset repeats exactly the same simulation. Save the project or export data and images from File.',
        ],
        'sections': [
            {'h': 'Three challenges', 'p': 'Game of Life: start with 12 cells or fewer and keep the colony alive at generation 100. Traffic network: set the lights so that, for 300 seconds, no street has more than 9 cars queueing. Balanced ecosystem: keep rabbits and foxes alive for 500 steps. They are under \u201cNew\u2026\u201d and their status is always shown under Properties.'},
            {'h': 'Cellular automata', 'p': 'A grid of live or dead cells. At each generation they all change at once depending on how many live neighbours they have: born with 3 and surviving with 2 or 3 is written B3/S23 (B for born, S for survive). Change those numbers and you get other rules, such as HighLife (B36/S23).\n\nAn elementary automaton has a single row. Each square looks at its left, itself and its right: 8 combinations, and the rule says what comes out for each one. Those 8 answers, read as a binary number, give the rule number, from 0 to 255 (Wolfram code).'},
            {'h': 'Phantom traffic jams', 'p': 'In the Nagel-Schreckenberg model each cell is about 7.5 metres long and each step lasts one second. Cars speed up, slow down so they do not crash and sometimes brake for no reason. With enough cars, that braking turns into a jam that moves backwards with no obstacle at all: it shows up as a slanted red band on the space-time diagram.'},
            {'h': 'Rabbits and foxes', 'p': 'With agents, each animal is an individual with energy: it moves, eats, can have young and dies if it runs out of energy. In Lotka-Volterra there are no individuals, just two quantities that change continuously; the studio solves them with fourth-order Runge-Kutta (RK4), which works out four slopes per step and makes very small errors. On the phase diagram, each point is a pair (prey, predators) and the closed curve shows the two populations rising and falling one after the other.'},
            {'h': 'No flashing, at your own pace', 'p': 'Nothing moves until you ask, at 10 steps per second at most, and you can pause whenever you like. Cells are small and the screen never inverts as a whole. If your device asks for less motion, the studio starts in step-by-step mode. Every chart has its data table.'},
            {'h': 'Limits of the model', 'p': 'These are simplified models for learning how patterns appear. They cannot predict real traffic or real populations.'},
            {'h': 'Sources', 'p': 'Gardner, M. (1970). \u201cMathematical Games: The fantastic combinations of John Conway\u2019s new solitaire game \u2018life\u2019\u201d. Scientific American, 223(4), 120-123.\n\nWolfram, S. (1983). \u201cStatistical mechanics of cellular automata\u201d. Reviews of Modern Physics, 55(3), 601-644. doi:10.1103/RevModPhys.55.601\n\nNagel, K. and Schreckenberg, M. (1992). \u201cA cellular automaton model for freeway traffic\u201d. Journal de Physique I, 2(12), 2221-2229. doi:10.1051/jp1:1992277\n\nLotka, A. J. (1925). Elements of Physical Biology. Baltimore: Williams & Wilkins.\n\nVolterra, V. (1926). \u201cFluctuations in the abundance of a species considered mathematically\u201d. Nature, 118, 558-560. doi:10.1038/118558a0\n\nButcher, J. C. (2016). Numerical Methods for Ordinary Differential Equations (3rd ed.). Chichester: Wiley.'},
        ],
        'links': [('The whole workshop', '/en/workshop/'), ('Coding', '/en/workshop/coding/'), ('Structures and bridges', '/en/workshop/structures/')],
    },
}

_PAT = {
    'es': {
        'glider': ('Planeador', 'Planeador: 5 células que se desplazan en diagonal. Cada 4 generaciones vuelve a tener la misma forma, una casilla más allá.'),
        'lwss': ('Nave ligera', 'Nave ligera: se desplaza en horizontal y repite su forma cada 4 generaciones.'),
        'blinker': ('Parpadeador', 'Parpadeador: tres células en fila que cambian de horizontal a vertical. Es un oscilador de periodo 2.'),
        'toad': ('Sapo', 'Sapo: oscilador de periodo 2 con 6 células.'),
        'beacon': ('Faro', 'Faro: dos bloques que se tocan por una esquina. Oscilador de periodo 2.'),
        'pulsar': ('Púlsar', 'Púlsar: oscilador grande y simétrico de periodo 3, con 48 células.'),
        'pentadecathlon': ('Pentadecatlón', 'Pentadecatlón: oscilador de periodo 15.'),
        'gun': ('Cañón de Gosper', 'Cañón de planeadores de Gosper: dispara un planeador nuevo cada 30 generaciones, sin acabarse nunca.'),
        'block': ('Bloque', 'Bloque: 4 células que no cambian nunca (vida estable).'),
        'beehive': ('Colmena', 'Colmena: 6 células que no cambian nunca (vida estable).'),
        'rpent': ('R-pentominó', 'R-pentominó: solo 5 células, pero tarda más de mil generaciones en calmarse. Necesita una rejilla grande.'),
        'acorn': ('Bellota', 'Bellota: 7 células que crecen durante miles de generaciones.'),
        'diehard': ('Duradero', 'Duradero: 7 células que desaparecen del todo en la generación 130.'),
    },
    'en': {
        'glider': ('Glider', 'Glider: 5 cells that move diagonally. Every 4 generations it has the same shape again, one square further on.'),
        'lwss': ('Lightweight spaceship', 'Lightweight spaceship: moves horizontally and repeats its shape every 4 generations.'),
        'blinker': ('Blinker', 'Blinker: three cells in a row that switch between horizontal and vertical. It is an oscillator with period 2.'),
        'toad': ('Toad', 'Toad: a period-2 oscillator with 6 cells.'),
        'beacon': ('Beacon', 'Beacon: two blocks touching at a corner. A period-2 oscillator.'),
        'pulsar': ('Pulsar', 'Pulsar: a large, symmetrical period-3 oscillator with 48 cells.'),
        'pentadecathlon': ('Pentadecathlon', 'Pentadecathlon: a period-15 oscillator.'),
        'gun': ('Gosper glider gun', 'Gosper glider gun: fires a new glider every 30 generations, for ever.'),
        'block': ('Block', 'Block: 4 cells that never change (still life).'),
        'beehive': ('Beehive', 'Beehive: 6 cells that never change (still life).'),
        'rpent': ('R-pentomino', 'R-pentomino: only 5 cells, but it takes over a thousand generations to settle down. It needs a large grid.'),
        'acorn': ('Acorn', 'Acorn: 7 cells that keep growing for thousands of generations.'),
        'diehard': ('Diehard', 'Diehard: 7 cells that vanish completely at generation 130.'),
    },
}

STRINGS = {
    'es': {
        'canvasLabel': 'Simulación', 'canvasHelp': 'Con el foco aquí: las flechas mueven el cursor (cinco casillas con Mayús) y leen lo que hay; Intro o Espacio actúan con la herramienta elegida; P inicia o pausa; el punto avanza un paso. En Lotka-Volterra, las flechas cambian el punto de partida.',
        'kSimCursor': 'En la simulación: flechas para el cursor; Intro o Espacio para actuar con la herramienta',
        'kSimRun': 'P: iniciar o pausar · punto (.): avanzar un paso',
        'stGlider': 'Juego de la vida con planeador', 'stGliderD': 'Reto: con 12 células o menos, que la colonia siga viva en la generación 100.',
        'stGun': 'Cañón de planeadores', 'stGunD': 'El cañón de Gosper en una rejilla grande: un planeador nuevo cada 30 generaciones.',
        'stWolf30': 'Regla 30', 'stWolf30D': 'Autómata de una fila que parece desordenado aunque sus reglas son fijas.',
        'stWolf90': 'Triángulos de la regla 90', 'stWolf90D': 'Una sola célula dibuja triángulos dentro de triángulos.',
        'stPhantom': 'Atasco fantasma', 'stPhantomD': '30 coches en una carretera circular. Sin obstáculos, aparecen atascos que van hacia atrás.',
        'stCrossing': 'Red de tráfico con semáforo', 'stCrossingD': 'Reto: ajusta los tiempos del semáforo para que ninguna cola pase de 9 coches.',
        'stEco': 'Ecosistema equilibrado', 'stEcoD': 'Reto: hierba, conejos y zorros. Consigue que las dos especies vivan 500 pasos.',
        'stLv': 'Lotka-Volterra y diagrama de fases', 'stLvD': 'Presas y depredadores con ecuaciones resueltas por RK4, en el tiempo y en fases.',
        'model_life': 'Juego de la vida', 'model_wolf': 'Autómata elemental', 'model_traffic': 'Tráfico en anillo', 'model_net': 'Cruce con semáforo', 'model_eco': 'Ecosistema por agentes', 'model_lv': 'Lotka-Volterra',
        'famAuto': 'autómata', 'famTraffic': 'tráfico', 'famEco': 'ecosistema',
        'about_life': 'Rejilla de células vivas o muertas. En cada generación todas cambian a la vez según sus 8 vecinas.',
        'about_wolf': 'Una fila de casillas. Cada fila nueva sale de la anterior con una regla de 0 a 255 y se dibuja debajo.',
        'about_traffic': 'Modelo de Nagel-Schreckenberg: una celda mide unos 7,5 m y un paso dura 1 segundo.',
        'about_net': 'Dos calles circulares que se cruzan. Un semáforo da verde por turnos a N-S y a E-O.',
        'about_eco': 'Cada conejo y cada zorro es un individuo con energía. La hierba vuelve a crecer al cabo de un tiempo.',
        'about_lv': 'Dos poblaciones que cambian de forma continua: presas (x) y depredadores (y). Se resuelve con RK4.',
        'models': 'Modelos', 'elements': 'Elementos', 'modelLabel': 'Modelo', 'modelShort': 'Modelo', 'modelSet': 'Modelo: {m}',
        'start': 'Iniciar', 'pause': 'Pausa', 'step': 'Paso', 'reset': 'Reiniciar', 'advance10': 'Avanzar 10 pasos',
        'running': 'En marcha a {s} pasos por segundo. Pulsa Pausa para parar.', 'paused': 'En pausa en el paso {n}.', 'advanced': 'Paso {n}.', 'resetDone': 'Simulación reiniciada con la misma semilla.',
        'genN': 'generación {n}', 'stepN': 'paso {n}',
        'speed': 'Velocidad', 'stepsPerSec': 'pasos/s', 'speedOpt': '{s} por segundo', 'speedSet': 'Velocidad: {s} pasos por segundo',
        'stepModeLabel': 'Paso a paso (sin marcha continua)', 'stepModeOn': 'Modo paso a paso: avanza con Paso o «Avanzar 10 pasos».', 'stepModeOff': 'Marcha continua disponible: pulsa Iniciar.',
        'seed': 'Semilla del azar', 'newSeed': 'Otra semilla', 'seedSet': 'Semilla: {s}. Simulación reiniciada.',
        'seedNote': 'La semilla decide todo lo que ocurre al azar. Con la misma semilla y los mismos valores, la simulación sale siempre igual.',
        'chartKind': 'Gráfico', 'chartTime': 'En el tiempo', 'chartPhase': 'Fases', 'chartFund': 'Diagrama fundamental', 'chartSet': 'Gráfico cambiado',
        'flashNote': 'Como mucho 10 pasos por segundo, con células pequeñas y sin cambios de pantalla completa (WCAG 2.3.1).',
        'legend_life': 'Azul oscuro: célula viva. Blanco: muerta. El cuadro rojo es el cursor del teclado.',
        'legend_wolf': 'Cada fila es un paso; la de arriba es la fila inicial. Azul oscuro: 1. Blanco: 0.',
        'legend_traffic': 'Coches: flecha azul, rápido; flecha naranja, lento; cuadrado rojo, parado. En el diagrama espacio-tiempo el tiempo baja y las franjas rojas son atascos.',
        'legend_net': 'Coches: azul, rápido; naranja, lento; rojo, parado. Semáforo: círculo verde, pasa; cuadrado rojo, espera.',
        'legend_eco': 'Verde claro: hierba. Marrón claro: suelo comido. Círculo blanco con borde azul: conejo. Triángulo naranja: zorro.',
        'legend_lv': 'La curva azul es el recorrido; el punto violeta, el estado actual; el círculo gris, el punto de partida; el cuadrado verde, el equilibrio.',
        'nowTitle': 'Ahora mismo', 'dataTable': 'Tabla de datos', 'tableLast': 'Últimas 200 filas de {n}. El archivo CSV tiene todas.', 'tableAll': '{n} filas.',
        'challenge': 'Reto', 'chTitle_life': 'Juego de la vida', 'chTitle_net': 'Red de tráfico', 'chTitle_eco': 'Ecosistema equilibrado',
        'chGoal_life': 'Empieza con 12 células o menos y consigue que la colonia siga viva en la generación 100.',
        'chGoal_net': 'Durante 300 segundos, ninguna calle puede tener una cola de más de 9 coches.',
        'chGoal_eco': 'Conejos y zorros tienen que seguir vivos durante 500 pasos.',
        'chLifeStatus': 'Al empezar: {s} células. Generación {g}. Vivas ahora: {p}.', 'chLifeTooMany': 'Quita células hasta tener 12 o menos: al editar, la generación vuelve a 0.',
        'chLifeOk': '¡Reto conseguido! La colonia sigue viva en la generación 100.',
        'chNetStatus': 'Segundo {t} de {n}. Cola más larga: N-S {a}, E-O {b} (máximo {m}).', 'chNetOk': '¡Reto conseguido! Ninguna cola ha pasado del máximo.',
        'chNetBad': 'No lo has conseguido esta vez: colas más largas N-S {a} y E-O {b} (máximo {m}). Pista: la calle E-O tiene el doble de coches; dale más verde y prueba ciclos más cortos.',
        'chEcoStatus': 'Paso {t} de {n}: {r} conejos y {f} zorros.', 'chEcoOk': '¡Reto conseguido! Las dos especies siguen vivas tras {n} pasos.',
        'chEcoNoRabbits': 'Se han extinguido los conejos en el paso {t}.', 'chEcoNoFoxes': 'Se han extinguido los zorros en el paso {t}.',
        'chEcoHint': 'Pista: cambia la energía que da cada conejo a un zorro, las crías o la hierba, y pulsa Reiniciar.',
        'chOtherModel': 'Este reto se hace en el modelo «{m}».',
        'elGrid': 'Rejilla', 'elRule': 'Regla B/S', 'elPattern': 'Patrón para colocar', 'elWRule': 'Regla (0-255)', 'elWRow': 'Fila inicial',
        'elRoad': 'Carretera', 'elDrivers': 'Conductores', 'elLight': 'Semáforo', 'elRoadNS': 'Calle N-S', 'elRoadEW': 'Calle E-O',
        'elGrass': 'Hierba', 'elRabbits': 'Conejos', 'elFoxes': 'Zorros', 'elPrey': 'Presas (x)', 'elPred': 'Depredadores (y)', 'elSolver': 'Método de cálculo',
        'gridSize': 'Tamaño de la rejilla', 'wrapLabel': 'Bordes unidos (lo que sale por un lado entra por el otro)',
        'wrapNote': 'Con los bordes unidos, la rejilla funciona como la superficie de un donut: no hay borde.',
        'fillDensity': 'Densidad del relleno al azar', 'randomFill': 'Rellenar al azar', 'clearGrid': 'Vaciar', 'filled': 'Rejilla rellenada al azar con la semilla.', 'cleared': 'Rejilla vacía.',
        'gridResized': 'Rejilla de {w} × {h}',
        'ruleNote': 'B dice con cuántas vecinas vivas nace una célula; S, con cuántas sobrevive. Life es B3/S23.',
        'rulePreset': 'Reglas conocidas', 'ruleCustom': 'Regla propia', 'ruleText': 'Regla escrita', 'ruleHelp': 'Escribe B, los números para nacer, una barra, S y los números para sobrevivir. Ejemplo: B36/S23.',
        'ruleBad': 'Esa regla no se entiende. Usa el formato B3/S23.', 'ruleSet': 'Regla: {r}',
        'rpLife': 'Life', 'rpHigh': 'HighLife', 'rpSeeds': 'Seeds', 'rpDayNight': 'Día y noche', 'rpNoDeath': 'Vida sin muerte', 'rpMaze': 'Laberinto',
        'bornWith': 'Nace con', 'surviveWith': 'Sobrevive con',
        'patternLabel': 'Patrón', 'rotation': 'Giro', 'flipLabel': 'Reflejar', 'placeAtCursor': 'Colocar en el cursor', 'useStampTool': 'Usar la herramienta Patrón',
        'cursorX': 'Cursor: columna', 'cursorY': 'Cursor: fila',
        'patternPlaced': 'Colocado: {p}.', 'patternCut': 'Una parte quedaba fuera de la rejilla y no se ha puesto.',
        'wolfRule': 'Número de la regla', 'wolfPreset': 'Reglas conocidas', 'wolfRuleSet': 'Regla {r}',
        'wolfRuleNote': 'Cada botón es una combinación de tres casillas (izquierda, centro, derecha) y lo que sale debajo. Púlsalo para cambiar la salida: el número de la regla cambia solo.',
        'wolfTable': 'Tabla de la regla', 'wolfBitLabel': 'Si arriba hay {p}, sale {r}', 'onWord': 'uno', 'offWord': 'cero',
        'wolf_30': '30 · parece al azar', 'wolf_90': '90 · triángulos', 'wolf_110': '110 · estructuras que chocan', 'wolf_184': '184 · un tráfico muy sencillo', 'wolf_60': '60 · triángulo inclinado', 'wolf_150': '150 · triángulos con relleno', 'wolf_250': '250 · crece y se llena',
        'wolfInit': 'Cómo empieza', 'initSingle': 'Una célula en el centro', 'initRandom': 'Al azar', 'initCustom': 'Dibujada', 'wolfWidth': 'Ancho (casillas)',
        'wolfRowNote': 'Para dibujar la fila inicial, usa el lápiz en la simulación o el cursor del teclado (flechas e Intro).',
        'wolfRowEdited': 'Fila inicial cambiada', 'wolfCellOn': 'Casilla {x} de la fila inicial: 1', 'wolfCellOff': 'Casilla {x} de la fila inicial: 0',
        'roadLen': 'Largo de la carretera', 'cellsUnit': 'celdas', 'density': 'Densidad de coches', 'carsWord': 'coches',
        'initCars': 'Colocación inicial', 'initEven': 'Repartidos', 'initRandCars': 'Al azar', 'initJam': 'Todos juntos',
        'roadNote': 'Densidad: qué parte de las celdas tiene coche. Por encima del 15 % aproximadamente empiezan los atascos.',
        'vmax': 'Velocidad máxima', 'cellsPerStep': 'celdas/paso', 'vmaxNote': 'Una celda por paso son unos 27 km/h, así que la máxima equivale a unos {k} km/h.',
        'brakeP': 'Probabilidad de frenar sin motivo', 'brakeNote': 'Es la regla que crea los atascos fantasma: con 0 %, los coches repartidos nunca se paran.',
        'greenNS': 'Verde para N-S', 'greenEW': 'Verde para E-O', 'allRed': 'Todo en rojo entre turnos',
        'lightNote': 'Un ciclo completo dura {c} segundos. «Todo en rojo» deja vaciarse el cruce antes de cambiar.',
        'goalQueue': 'Reto: cola máxima', 'goalSteps': 'Reto: duración',
        'netRoadNote': 'Coches que han cruzado desde el inicio: {n}.',
        'regrow': 'Tiempo que tarda en volver a crecer', 'stepsWord': 'pasos', 'grass0': 'Hierba al empezar', 'ecoSize': 'Tamaño del terreno',
        'grassNote': 'Cuando un conejo se come la hierba, esa casilla queda sin hierba durante el tiempo indicado.',
        'initCount': 'Cantidad al empezar', 'gain': 'Energía que ganan al comer', 'energyUnit': 'puntos', 'repro': 'Probabilidad de tener una cría en cada paso',
        'rabbitNote': 'Cada paso, un conejo se mueve a una casilla vecina y gasta 1 punto de energía. Si hay hierba, se la come.',
        'foxNote': 'Cada paso, un zorro se mueve y gasta 1 punto. Si en su casilla hay un conejo, se lo come.', 'goalEco': 'Reto: pasos que deben durar',
        'lvA': 'α · crecimiento de las presas', 'lvB': 'β · caza (encuentros presa-depredador)', 'lvX0': 'Presas al empezar (x₀)',
        'lvC': 'γ · muerte de los depredadores', 'lvD': 'δ · crías de depredador por presa cazada', 'lvY0': 'Depredadores al empezar (y₀)',
        'preyNote': 'dx/dt = αx − βxy: sin depredadores, las presas crecen; cada encuentro con un depredador resta presas.',
        'predNote': 'dy/dt = δxy − γy: sin presas, los depredadores disminuyen. El equilibrio está en x = γ/δ = {x}, y = α/β = {y}.',
        'method': 'Método', 'methodRk4': 'RK4 (Runge-Kutta de orden 4)', 'methodEuler': 'Euler (más sencillo, menos preciso)',
        'stepH': 'Tamaño de cada paso (h)', 'lvT': 'Tiempo total (T)', 'solveAll': 'Resolver hasta T',
        'solverNote': 'En el modelo exacto, una cierta cantidad no cambia nunca. «Error acumulado» mide cuánto ha cambiado: con RK4 casi nada; con Euler la curva se abre en espiral.',
        'solved': 'Resuelto hasta t = {T} en {n} pasos.', 'lvDone': 'Has llegado al tiempo total T = {T}.', 'lvStartSet': 'Punto de partida cambiado', 'lvStartAt': 'Punto de partida: {x} presas, {y} depredadores.',
        'toolDraw': 'Lápiz', 'toolStamp': 'Patrón', 'toolErase': 'Goma', 'toolWolfDraw': 'Dibujar fila inicial', 'toolSelect': 'Elegir',
        'toolAddCar': 'Añadir coche', 'toolRemoveCar': 'Quitar coche', 'toolInspect': 'Mirar', 'toolAddRabbit': 'Añadir conejo', 'toolAddFox': 'Añadir zorro', 'toolStartPoint': 'Punto de partida',
        'viewLabel': 'Vista', 'viewBoth': 'Simulación y gráfico', 'viewSim': 'Solo simulación', 'viewChart': 'Solo gráfico',
        'cellsEdited': 'Células cambiadas', 'cellOn': 'Célula viva en columna {x}, fila {y}', 'cellOff': 'Célula muerta en columna {x}, fila {y}',
        'lifeAdvancedTo': 'Simulación hasta la generación {g}', 'lifeDied': 'Todas las células han muerto en la generación {g}.',
        'cursorCell': 'Cursor en columna {x}, fila {y}.', 'cursorLife': 'Columna {x}, fila {y}: {s}', 'alive': 'viva', 'dead': 'muerta',
        'cursorWolf': 'Casilla {x} de la fila inicial: {s}', 'cursorRoad': 'Celda {x} de la carretera', 'carInfo': 'coche {n} a {v} celdas por paso', 'emptyCell': 'vacía',
        'cellBusy': 'Ahí ya hay un coche.', 'noCarHere': 'No hay ningún coche en esa celda.', 'carAdded': 'Coche añadido. Hay {n} coches.', 'carRemoved': 'Coche quitado. Hay {n} coches.',
        'carN': 'Coche {n}', 'carsN': 'Coches ({n})', 'carsMore': 'Y {n} coches más.', 'carHelp': 'Este coche se ve en violeta en la carretera y en el diagrama espacio-tiempo, para seguir su recorrido.', 'removeThisCar': 'Quitar este coche',
        'ecoCell': 'Casilla {x}, {y}: {g}, {r} conejos, {f} zorros.', 'grassYes': 'con hierba', 'grassNo': 'sin hierba',
        'rabbitAdded': 'Conejo añadido. {r} conejos y {f} zorros.', 'foxAdded': 'Zorro añadido. {r} conejos y {f} zorros.', 'ecoAllGone': 'No queda ningún animal (paso {t}).',
        'paramSet': 'Cambiado: {p}. Simulación reiniciada.',
        'lifeHead': 'Regla {rule} · generación {g} · {p} vivas', 'wolfHead': 'Regla {r} · paso {n}', 'trafficHead': '{n} coches · paso {t}',
        'spaceTime': 'Diagrama espacio-tiempo', 'stAxis': 'posición → · tiempo ↓',
        'netHead': 'Segundo {t} · {s}', 'phaseNS': 'verde N-S', 'phaseEW': 'verde E-O', 'phaseRed': 'todo en rojo', 'queues': 'Colas: N-S {a}, E-O {b}', 'lightNS': 'N-S', 'lightEW': 'E-O',
        'ecoHead': 'Paso {t} · {r} conejos · {f} zorros', 'lvHead': 't = {t} · presas {x} · depredadores {y}',
        'phaseTitle': 'Diagrama de fases', 'axisPrey': 'Presas (x)', 'axisPred': 'Depredadores (y)', 'equilibrium': 'Equilibrio',
        'fdTitle': 'Diagrama fundamental: flujo según la densidad', 'axisDensity': 'Densidad de coches', 'axisFlow': 'Flujo (coches por paso y celda)', 'yourDensity': 'tu densidad',
        'chartTitle_life': 'Población por generación', 'chartTitle_wolf': 'Casillas en 1 por paso', 'chartTitle_traffic': 'Velocidad media y flujo', 'chartTitle_net': 'Velocidad media en cada calle', 'chartTitle_eco': 'Poblaciones en el tiempo', 'chartTitle_lv': 'Presas y depredadores en el tiempo',
        'chartY_life': 'Células', 'chartY_wolf': 'Casillas en 1', 'chartY_traffic': 'Celdas por paso', 'chartY_net': 'Celdas por paso', 'chartY_eco': 'Individuos', 'chartY_lv': 'Población',
        'thGen': 'Generación', 'thStep': 'Paso', 'thTime': 'Tiempo', 'thPop': 'Vivas', 'thBirths': 'Nacen', 'thDeaths': 'Mueren', 'thOnes': 'En 1',
        'thSpeed': 'Velocidad media', 'thFlow': 'Flujo', 'thSpeedNS': 'N-S', 'thSpeedEW': 'E-O', 'thRabbits': 'Conejos', 'thFoxes': 'Zorros', 'thGrassScaled': 'Hierba ÷ 10', 'thPrey': 'Presas', 'thPred': 'Depredadores',
        'col_gen': 'Generación', 'col_pop': 'Células vivas', 'col_births': 'Nacimientos', 'col_deaths': 'Muertes', 'col_step': 'Paso', 'col_ones': 'Casillas en 1', 'col_density': 'Proporción en 1',
        'col_speed': 'Velocidad media (celdas/paso)', 'col_flow': 'Flujo (coches/paso/celda)', 'col_stopped': 'Coches parados',
        'col_speedNS': 'Velocidad media N-S', 'col_speedEW': 'Velocidad media E-O', 'col_queueNS': 'Cola N-S', 'col_queueEW': 'Cola E-O', 'col_light': 'Semáforo',
        'col_grass': 'Casillas con hierba', 'col_rabbits': 'Conejos', 'col_foxes': 'Zorros', 'col_time': 'Tiempo', 'col_prey': 'Presas', 'col_pred': 'Depredadores', 'col_fdDensity': 'Densidad', 'col_fdFlow': 'Flujo',
        'liveLife': 'Generación {g}: {p} células vivas ({b} nacen y {d} mueren en el último paso).',
        'liveWolf': 'Paso {n}: {o} casillas en 1 ({d} %).',
        'liveTraffic': 'Paso {t}: velocidad media {v} celdas por paso (unos {k} km/h), flujo {f}, {s} coches parados, {j} atascos.',
        'liveNet': 'Segundo {t}: velocidad media N-S {a} y E-O {b}. Colas: N-S {qa}, E-O {qb} (máximas {ma} y {mb}). Han cruzado {pa} y {pb} coches.',
        'liveEco': 'Paso {t}: {g} casillas con hierba, {r} conejos y {f} zorros.',
        'liveLv': 't = {t}: {x} presas y {y} depredadores. Error acumulado: {e} %.',
        'sumLife': 'Rejilla de {w} × {h}, regla {rule}, {wrap}. Generación {g}, {p} células vivas.', 'wrapYes': 'bordes unidos', 'wrapNo': 'bordes cerrados',
        'sumWolf': 'Regla {r}, {w} casillas de ancho. Paso {n}, {d} % de casillas en 1.',
        'sumTraffic': 'Carretera circular de {L} celdas con {n} coches. Paso {t}, velocidad media {v} celdas por paso, {s} coches parados en {j} atascos.',
        'sumNet': 'Segundo {t}, semáforo en {s}. Colas: N-S {qa}, E-O {qb}.',
        'sumEco': 'Paso {t}: {g} casillas con hierba, {r} conejos y {f} zorros.',
        'sumLv': 't = {t}: {x} presas y {y} depredadores. Equilibrio en {xe} presas y {ye} depredadores.',
        'exportCsv': 'Exportar datos (CSV)', 'exportChart': 'Exportar gráfico (PNG)', 'exportSim': 'Exportar imagen de la simulación (PNG)', 'exportRle': 'Exportar patrón de Life (RLE)', 'importRle': 'Abrir patrón de Life (RLE)…',
        'rleBad': 'Ese archivo no tiene un patrón RLE que se pueda leer.', 'rleTooBig': 'El archivo es demasiado grande (máximo 512 KB).', 'rleTooLarge': 'El patrón no cabe en la rejilla más grande (128 × 80).', 'rleLoaded': 'Patrón abierto: {n} células.',
    },
    'en': {
        'canvasLabel': 'Simulation', 'canvasHelp': 'With focus here: the arrow keys move the cursor (five squares with Shift) and read what is there; Enter or Space act with the chosen tool; P starts or pauses; full stop advances one step. In Lotka-Volterra, the arrow keys change the starting point.',
        'kSimCursor': 'In the simulation: arrow keys for the cursor; Enter or Space to act with the tool',
        'kSimRun': 'P: start or pause · full stop (.): advance one step',
        'stGlider': 'Game of Life with a glider', 'stGliderD': 'Challenge: with 12 cells or fewer, keep the colony alive at generation 100.',
        'stGun': 'Glider gun', 'stGunD': 'The Gosper gun on a large grid: a new glider every 30 generations.',
        'stWolf30': 'Rule 30', 'stWolf30D': 'A one-row automaton that looks random even though its rules are fixed.',
        'stWolf90': 'Rule 90 triangles', 'stWolf90D': 'A single cell draws triangles inside triangles.',
        'stPhantom': 'Phantom traffic jam', 'stPhantomD': '30 cars on a ring road. With no obstacles, jams appear and move backwards.',
        'stCrossing': 'Traffic network with lights', 'stCrossingD': 'Challenge: set the traffic light timings so no queue goes over 9 cars.',
        'stEco': 'Balanced ecosystem', 'stEcoD': 'Challenge: grass, rabbits and foxes. Keep both species alive for 500 steps.',
        'stLv': 'Lotka-Volterra and phase diagram', 'stLvD': 'Prey and predators with equations solved by RK4, over time and as phases.',
        'model_life': 'Game of Life', 'model_wolf': 'Elementary automaton', 'model_traffic': 'Ring road traffic', 'model_net': 'Junction with lights', 'model_eco': 'Agent-based ecosystem', 'model_lv': 'Lotka-Volterra',
        'famAuto': 'automaton', 'famTraffic': 'traffic', 'famEco': 'ecosystem',
        'about_life': 'A grid of live or dead cells. At each generation they all change at once depending on their 8 neighbours.',
        'about_wolf': 'A row of squares. Each new row comes from the one before with a rule from 0 to 255 and is drawn underneath.',
        'about_traffic': 'The Nagel-Schreckenberg model: a cell is about 7.5 m long and a step lasts 1 second.',
        'about_net': 'Two ring roads that cross. A traffic light gives green in turns to N-S and E-W.',
        'about_eco': 'Each rabbit and each fox is an individual with energy. Grass grows back after a while.',
        'about_lv': 'Two populations that change continuously: prey (x) and predators (y). Solved with RK4.',
        'models': 'Models', 'elements': 'Items', 'modelLabel': 'Model', 'modelShort': 'Model', 'modelSet': 'Model: {m}',
        'start': 'Start', 'pause': 'Pause', 'step': 'Step', 'reset': 'Reset', 'advance10': 'Advance 10 steps',
        'running': 'Running at {s} steps per second. Press Pause to stop.', 'paused': 'Paused at step {n}.', 'advanced': 'Step {n}.', 'resetDone': 'Simulation reset with the same seed.',
        'genN': 'generation {n}', 'stepN': 'step {n}',
        'speed': 'Speed', 'stepsPerSec': 'steps/s', 'speedOpt': '{s} per second', 'speedSet': 'Speed: {s} steps per second',
        'stepModeLabel': 'Step by step (no continuous running)', 'stepModeOn': 'Step-by-step mode: move on with Step or “Advance 10 steps”.', 'stepModeOff': 'Continuous running available: press Start.',
        'seed': 'Random seed', 'newSeed': 'Another seed', 'seedSet': 'Seed: {s}. Simulation reset.',
        'seedNote': 'The seed decides everything that happens at random. With the same seed and the same values, the simulation always comes out the same.',
        'chartKind': 'Chart', 'chartTime': 'Over time', 'chartPhase': 'Phases', 'chartFund': 'Fundamental diagram', 'chartSet': 'Chart changed',
        'flashNote': 'At most 10 steps per second, with small cells and no full-screen changes (WCAG 2.3.1).',
        'legend_life': 'Dark blue: live cell. White: dead. The red square is the keyboard cursor.',
        'legend_wolf': 'Each row is a step; the top one is the starting row. Dark blue: 1. White: 0.',
        'legend_traffic': 'Cars: blue arrow, fast; orange arrow, slow; red square, stopped. On the space-time diagram time runs downwards and the red bands are jams.',
        'legend_net': 'Cars: blue, fast; orange, slow; red, stopped. Traffic light: green circle, go; red square, wait.',
        'legend_eco': 'Light green: grass. Light brown: grazed ground. White circle with a blue edge: rabbit. Orange triangle: fox.',
        'legend_lv': 'The blue curve is the path; the violet dot, the current state; the grey circle, the starting point; the green square, the equilibrium.',
        'nowTitle': 'Right now', 'dataTable': 'Data table', 'tableLast': 'Last 200 rows of {n}. The CSV file has them all.', 'tableAll': '{n} rows.',
        'challenge': 'Challenge', 'chTitle_life': 'Game of Life', 'chTitle_net': 'Traffic network', 'chTitle_eco': 'Balanced ecosystem',
        'chGoal_life': 'Start with 12 cells or fewer and keep the colony alive at generation 100.',
        'chGoal_net': 'For 300 seconds, no street may have a queue of more than 9 cars.',
        'chGoal_eco': 'Rabbits and foxes must both stay alive for 500 steps.',
        'chLifeStatus': 'At the start: {s} cells. Generation {g}. Alive now: {p}.', 'chLifeTooMany': 'Remove cells until you have 12 or fewer: when you edit, the generation goes back to 0.',
        'chLifeOk': 'Challenge complete! The colony is still alive at generation 100.',
        'chNetStatus': 'Second {t} of {n}. Longest queue: N-S {a}, E-W {b} (maximum {m}).', 'chNetOk': 'Challenge complete! No queue went over the maximum.',
        'chNetBad': 'Not this time: longest queues N-S {a} and E-W {b} (maximum {m}). Hint: the E-W street has twice as many cars; give it more green and try shorter cycles.',
        'chEcoStatus': 'Step {t} of {n}: {r} rabbits and {f} foxes.', 'chEcoOk': 'Challenge complete! Both species are still alive after {n} steps.',
        'chEcoNoRabbits': 'The rabbits died out at step {t}.', 'chEcoNoFoxes': 'The foxes died out at step {t}.',
        'chEcoHint': 'Hint: change the energy a fox gets from each rabbit, the young or the grass, then press Reset.',
        'chOtherModel': 'This challenge is done in the “{m}” model.',
        'elGrid': 'Grid', 'elRule': 'B/S rule', 'elPattern': 'Pattern to place', 'elWRule': 'Rule (0-255)', 'elWRow': 'Starting row',
        'elRoad': 'Road', 'elDrivers': 'Drivers', 'elLight': 'Traffic light', 'elRoadNS': 'N-S street', 'elRoadEW': 'E-W street',
        'elGrass': 'Grass', 'elRabbits': 'Rabbits', 'elFoxes': 'Foxes', 'elPrey': 'Prey (x)', 'elPred': 'Predators (y)', 'elSolver': 'Calculation method',
        'gridSize': 'Grid size', 'wrapLabel': 'Joined edges (what leaves one side comes in on the other)',
        'wrapNote': 'With joined edges, the grid works like the surface of a doughnut: there is no edge.',
        'fillDensity': 'Density of the random fill', 'randomFill': 'Random fill', 'clearGrid': 'Clear', 'filled': 'Grid filled at random using the seed.', 'cleared': 'Grid cleared.',
        'gridResized': 'Grid of {w} × {h}',
        'ruleNote': 'B says how many live neighbours make a cell be born; S, how many let it survive. Life is B3/S23.',
        'rulePreset': 'Known rules', 'ruleCustom': 'Your own rule', 'ruleText': 'Rule as text', 'ruleHelp': 'Type B, the numbers for being born, a slash, S and the numbers for surviving. Example: B36/S23.',
        'ruleBad': 'That rule cannot be read. Use the format B3/S23.', 'ruleSet': 'Rule: {r}',
        'rpLife': 'Life', 'rpHigh': 'HighLife', 'rpSeeds': 'Seeds', 'rpDayNight': 'Day and night', 'rpNoDeath': 'Life without death', 'rpMaze': 'Maze',
        'bornWith': 'Born with', 'surviveWith': 'Survives with',
        'patternLabel': 'Pattern', 'rotation': 'Rotation', 'flipLabel': 'Mirror', 'placeAtCursor': 'Place at the cursor', 'useStampTool': 'Use the Pattern tool',
        'cursorX': 'Cursor: column', 'cursorY': 'Cursor: row',
        'patternPlaced': 'Placed: {p}.', 'patternCut': 'Part of it fell outside the grid and was left out.',
        'wolfRule': 'Rule number', 'wolfPreset': 'Known rules', 'wolfRuleSet': 'Rule {r}',
        'wolfRuleNote': 'Each button is a combination of three squares (left, centre, right) and what comes out underneath. Press it to change the output: the rule number changes by itself.',
        'wolfTable': 'Rule table', 'wolfBitLabel': 'If above there is {p}, out comes {r}', 'onWord': 'one', 'offWord': 'zero',
        'wolf_30': '30 · looks random', 'wolf_90': '90 · triangles', 'wolf_110': '110 · colliding structures', 'wolf_184': '184 · very simple traffic', 'wolf_60': '60 · slanted triangle', 'wolf_150': '150 · filled triangles', 'wolf_250': '250 · grows and fills',
        'wolfInit': 'How it starts', 'initSingle': 'One cell in the centre', 'initRandom': 'At random', 'initCustom': 'Drawn', 'wolfWidth': 'Width (squares)',
        'wolfRowNote': 'To draw the starting row, use the pencil on the simulation or the keyboard cursor (arrow keys and Enter).',
        'wolfRowEdited': 'Starting row changed', 'wolfCellOn': 'Square {x} of the starting row: 1', 'wolfCellOff': 'Square {x} of the starting row: 0',
        'roadLen': 'Road length', 'cellsUnit': 'cells', 'density': 'Car density', 'carsWord': 'cars',
        'initCars': 'Starting positions', 'initEven': 'Spread out', 'initRandCars': 'At random', 'initJam': 'All together',
        'roadNote': 'Density: the share of cells with a car. Above roughly 15%, jams start to appear.',
        'vmax': 'Top speed', 'cellsPerStep': 'cells/step', 'vmaxNote': 'One cell per step is about 27 km/h, so the top speed is about {k} km/h.',
        'brakeP': 'Chance of braking for no reason', 'brakeNote': 'This is the rule that creates phantom jams: at 0%, cars that are spread out never stop.',
        'greenNS': 'Green for N-S', 'greenEW': 'Green for E-W', 'allRed': 'All red between turns',
        'lightNote': 'A full cycle lasts {c} seconds. “All red” lets the junction clear before the change.',
        'goalQueue': 'Challenge: maximum queue', 'goalSteps': 'Challenge: duration',
        'netRoadNote': 'Cars that have crossed since the start: {n}.',
        'regrow': 'Time it takes to grow back', 'stepsWord': 'steps', 'grass0': 'Grass at the start', 'ecoSize': 'Size of the land',
        'grassNote': 'When a rabbit eats the grass, that square has no grass for the time shown.',
        'initCount': 'Number at the start', 'gain': 'Energy gained from eating', 'energyUnit': 'points', 'repro': 'Chance of having young at each step',
        'rabbitNote': 'At each step, a rabbit moves to a neighbouring square and uses 1 point of energy. If there is grass, it eats it.',
        'foxNote': 'At each step, a fox moves and uses 1 point. If there is a rabbit on its square, it eats it.', 'goalEco': 'Challenge: steps they must last',
        'lvA': 'α · prey growth', 'lvB': 'β · hunting (prey-predator encounters)', 'lvX0': 'Prey at the start (x₀)',
        'lvC': 'γ · predator deaths', 'lvD': 'δ · predator young per prey caught', 'lvY0': 'Predators at the start (y₀)',
        'preyNote': 'dx/dt = αx − βxy: with no predators, prey increase; each encounter with a predator takes prey away.',
        'predNote': 'dy/dt = δxy − γy: with no prey, predators decrease. The equilibrium is at x = γ/δ = {x}, y = α/β = {y}.',
        'method': 'Method', 'methodRk4': 'RK4 (fourth-order Runge-Kutta)', 'methodEuler': 'Euler (simpler, less accurate)',
        'stepH': 'Size of each step (h)', 'lvT': 'Total time (T)', 'solveAll': 'Solve up to T',
        'solverNote': 'In the exact model, a certain quantity never changes. “Accumulated error” measures how much it has changed: with RK4 almost nothing; with Euler the curve opens out into a spiral.',
        'solved': 'Solved up to t = {T} in {n} steps.', 'lvDone': 'You have reached the total time T = {T}.', 'lvStartSet': 'Starting point changed', 'lvStartAt': 'Starting point: {x} prey, {y} predators.',
        'toolDraw': 'Pencil', 'toolStamp': 'Pattern', 'toolErase': 'Eraser', 'toolWolfDraw': 'Draw starting row', 'toolSelect': 'Choose',
        'toolAddCar': 'Add car', 'toolRemoveCar': 'Remove car', 'toolInspect': 'Look', 'toolAddRabbit': 'Add rabbit', 'toolAddFox': 'Add fox', 'toolStartPoint': 'Starting point',
        'viewLabel': 'View', 'viewBoth': 'Simulation and chart', 'viewSim': 'Simulation only', 'viewChart': 'Chart only',
        'cellsEdited': 'Cells changed', 'cellOn': 'Live cell at column {x}, row {y}', 'cellOff': 'Dead cell at column {x}, row {y}',
        'lifeAdvancedTo': 'Simulation up to generation {g}', 'lifeDied': 'All the cells died at generation {g}.',
        'cursorCell': 'Cursor at column {x}, row {y}.', 'cursorLife': 'Column {x}, row {y}: {s}', 'alive': 'alive', 'dead': 'dead',
        'cursorWolf': 'Square {x} of the starting row: {s}', 'cursorRoad': 'Road cell {x}', 'carInfo': 'car {n} at {v} cells per step', 'emptyCell': 'empty',
        'cellBusy': 'There is already a car there.', 'noCarHere': 'There is no car in that cell.', 'carAdded': 'Car added. There are {n} cars.', 'carRemoved': 'Car removed. There are {n} cars.',
        'carN': 'Car {n}', 'carsN': 'Cars ({n})', 'carsMore': 'And {n} more cars.', 'carHelp': 'This car is shown in violet on the road and on the space-time diagram, so you can follow its journey.', 'removeThisCar': 'Remove this car',
        'ecoCell': 'Square {x}, {y}: {g}, {r} rabbits, {f} foxes.', 'grassYes': 'with grass', 'grassNo': 'no grass',
        'rabbitAdded': 'Rabbit added. {r} rabbits and {f} foxes.', 'foxAdded': 'Fox added. {r} rabbits and {f} foxes.', 'ecoAllGone': 'There are no animals left (step {t}).',
        'paramSet': 'Changed: {p}. Simulation reset.',
        'lifeHead': 'Rule {rule} · generation {g} · {p} alive', 'wolfHead': 'Rule {r} · step {n}', 'trafficHead': '{n} cars · step {t}',
        'spaceTime': 'Space-time diagram', 'stAxis': 'position → · time ↓',
        'netHead': 'Second {t} · {s}', 'phaseNS': 'green N-S', 'phaseEW': 'green E-W', 'phaseRed': 'all red', 'queues': 'Queues: N-S {a}, E-W {b}', 'lightNS': 'N-S', 'lightEW': 'E-W',
        'ecoHead': 'Step {t} · {r} rabbits · {f} foxes', 'lvHead': 't = {t} · prey {x} · predators {y}',
        'phaseTitle': 'Phase diagram', 'axisPrey': 'Prey (x)', 'axisPred': 'Predators (y)', 'equilibrium': 'Equilibrium',
        'fdTitle': 'Fundamental diagram: flow by density', 'axisDensity': 'Car density', 'axisFlow': 'Flow (cars per step per cell)', 'yourDensity': 'your density',
        'chartTitle_life': 'Population by generation', 'chartTitle_wolf': 'Squares at 1 per step', 'chartTitle_traffic': 'Average speed and flow', 'chartTitle_net': 'Average speed on each street', 'chartTitle_eco': 'Populations over time', 'chartTitle_lv': 'Prey and predators over time',
        'chartY_life': 'Cells', 'chartY_wolf': 'Squares at 1', 'chartY_traffic': 'Cells per step', 'chartY_net': 'Cells per step', 'chartY_eco': 'Individuals', 'chartY_lv': 'Population',
        'thGen': 'Generation', 'thStep': 'Step', 'thTime': 'Time', 'thPop': 'Alive', 'thBirths': 'Born', 'thDeaths': 'Die', 'thOnes': 'At 1',
        'thSpeed': 'Average speed', 'thFlow': 'Flow', 'thSpeedNS': 'N-S', 'thSpeedEW': 'E-W', 'thRabbits': 'Rabbits', 'thFoxes': 'Foxes', 'thGrassScaled': 'Grass ÷ 10', 'thPrey': 'Prey', 'thPred': 'Predators',
        'col_gen': 'Generation', 'col_pop': 'Live cells', 'col_births': 'Births', 'col_deaths': 'Deaths', 'col_step': 'Step', 'col_ones': 'Squares at 1', 'col_density': 'Share at 1',
        'col_speed': 'Average speed (cells/step)', 'col_flow': 'Flow (cars/step/cell)', 'col_stopped': 'Stopped cars',
        'col_speedNS': 'Average speed N-S', 'col_speedEW': 'Average speed E-W', 'col_queueNS': 'Queue N-S', 'col_queueEW': 'Queue E-W', 'col_light': 'Traffic light',
        'col_grass': 'Squares with grass', 'col_rabbits': 'Rabbits', 'col_foxes': 'Foxes', 'col_time': 'Time', 'col_prey': 'Prey', 'col_pred': 'Predators', 'col_fdDensity': 'Density', 'col_fdFlow': 'Flow',
        'liveLife': 'Generation {g}: {p} live cells ({b} born and {d} die in the last step).',
        'liveWolf': 'Step {n}: {o} squares at 1 ({d}%).',
        'liveTraffic': 'Step {t}: average speed {v} cells per step (about {k} km/h), flow {f}, {s} cars stopped, {j} jams.',
        'liveNet': 'Second {t}: average speed N-S {a} and E-W {b}. Queues: N-S {qa}, E-W {qb} (longest {ma} and {mb}). {pa} and {pb} cars have crossed.',
        'liveEco': 'Step {t}: {g} squares with grass, {r} rabbits and {f} foxes.',
        'liveLv': 't = {t}: {x} prey and {y} predators. Accumulated error: {e}%.',
        'sumLife': 'Grid of {w} × {h}, rule {rule}, {wrap}. Generation {g}, {p} live cells.', 'wrapYes': 'joined edges', 'wrapNo': 'closed edges',
        'sumWolf': 'Rule {r}, {w} squares wide. Step {n}, {d}% of squares at 1.',
        'sumTraffic': 'Ring road of {L} cells with {n} cars. Step {t}, average speed {v} cells per step, {s} cars stopped in {j} jams.',
        'sumNet': 'Second {t}, traffic light at {s}. Queues: N-S {qa}, E-W {qb}.',
        'sumEco': 'Step {t}: {g} squares with grass, {r} rabbits and {f} foxes.',
        'sumLv': 't = {t}: {x} prey and {y} predators. Equilibrium at {xe} prey and {ye} predators.',
        'exportCsv': 'Export data (CSV)', 'exportChart': 'Export chart (PNG)', 'exportSim': 'Export simulation image (PNG)', 'exportRle': 'Export Life pattern (RLE)', 'importRle': 'Open Life pattern (RLE)…',
        'rleBad': 'That file does not contain an RLE pattern that can be read.', 'rleTooBig': 'The file is too large (512 KB maximum).', 'rleTooLarge': 'The pattern does not fit on the largest grid (128 × 80).', 'rleLoaded': 'Pattern opened: {n} cells.',
    },
}

for _lang in ('es', 'en'):
    for _k, (_name, _info) in _PAT[_lang].items():
        STRINGS[_lang]['pat_' + _k] = _name
        STRINGS[_lang]['patInfo_' + _k] = _info

STRINGS['es'].update({'famSpace': 'Espacio', 'stTransit': 'Diseña una misión para encontrar planetas', 'model_transit': 'Tránsitos planetarios', 'about_transit': 'Cambia la órbita y el telescopio. Observa cómo cambia la luz cuando un planeta pasa delante de su estrella.', 'observeOrbit': 'Observar una órbita', 'transitScene': 'Estrella y planeta · vista del observador', 'transitPeriod': 'Órbita: {p} horas', 'flux': 'Luz relativa', 'col_minutes': 'Tiempo (min)', 'col_expected': 'Luz calculada', 'col_measured': 'Luz con ruido simulado', 'chartTitle_transit': 'Curva de luz', 'inclination': 'Inclinación (°; 90 = de canto)', 'telescope': 'Órbita y telescopio', 'orbitRadius': 'Radio orbital (radios estelares)', 'planetRadius': 'Radio del planeta / radio estelar', 'cadence': 'Tiempo por medida (min)', 'noise': 'Ruido del detector (ppm)', 'orbitalPhase': 'Posición inicial (0–1)', 'transitLimits': 'Simulación: estrella de masa y radio solares, disco uniforme y órbita circular. No son observaciones reales. Sin oscurecimiento del borde ni actividad estelar. El punto del planeta tiene un tamaño mínimo para poder verlo.', 'liveTransit': '{n} medidas. Minuto {time}. Luz: {f} %.', 'transitSheet': 'Exportar ficha de misión (TXT)'})
STRINGS['en'].update({'famSpace': 'Space', 'stTransit': 'Design a mission to find planets', 'model_transit': 'Planetary transits', 'about_transit': 'Change the orbit and telescope. Watch the light change when a planet passes in front of its star.', 'observeOrbit': 'Observe one orbit', 'transitScene': 'Star and planet · observer view', 'transitPeriod': 'Orbit: {p} hours', 'flux': 'Relative light', 'col_minutes': 'Time (min)', 'col_expected': 'Calculated light', 'col_measured': 'Light with simulated noise', 'chartTitle_transit': 'Light curve', 'inclination': 'Inclination (°; 90 = edge-on)', 'telescope': 'Orbit and telescope', 'orbitRadius': 'Orbital radius (stellar radii)', 'planetRadius': 'Planet radius / stellar radius', 'cadence': 'Time per measurement (min)', 'noise': 'Detector noise (ppm)', 'orbitalPhase': 'Initial position (0–1)', 'transitLimits': 'Simulation: solar-mass, solar-radius star, uniform disc and circular orbit. These are not real observations. No limb darkening or stellar activity. The planet marker has a minimum visible size.', 'liveTransit': '{n} measurements. Minute {time}. Light: {f}%.', 'transitSheet': 'Export mission sheet (TXT)'})

assert set(STRINGS['es']) == set(STRINGS['en']), set(STRINGS['es']) ^ set(STRINGS['en'])
assert set(PAGE['es']) == set(PAGE['en'])

