"""Estudio de videojuegos (R43): editor de niveles que exporta un juego jugable. Textos ES/EN."""

ENGINE = 'videojuegos'
SLUG = {'es': 'videojuegos', 'en': 'video-game-design'}
SCRIPTS = ['ig-suite-juego-runtime.js', 'ig-suite-videojuegos.js']
LIBRARIES = 'PixiJS (MIT) en el editor; el juego exportado usa solo el motor propio de Iris Green, sin bibliotecas'
LIBRARIES_EN = 'PixiJS (MIT) in the editor; the exported game uses only Iris Green’s own engine, with no libraries'

PAGE = {
    'es': {
        'title': 'Diseño de videojuegos',
        'description': 'Diseña niveles de plataformas o laberintos pintando casillas: suelo, monedas, enemigos, peligros, trampolines, llaves y puertas. Pruébalos al momento y exporta un juego jugable en un solo archivo HTML.',
        'lede': 'Pinta el nivel, cambia las reglas y pulsa Jugar. Cuando te guste, expórtalo: te llevas un juego de verdad en un solo archivo que funciona en cualquier navegador, también en el móvil.',
        'make': ['Un juego de plataformas', 'Un laberinto visto desde arriba', 'Un reto contrarreloj', 'Tu juego en un archivo HTML que puedes compartir'],
        'steps': [
            'Elige una herramienta abajo (Suelo, Plataforma, Moneda, Peligro, Meta, Enemigo, Jugador) y pinta tocando o arrastrando sobre el nivel.',
            'Pulsa Jugar. Se juega con las flechas y la barra espaciadora (o los botones en pantalla). Pulsa Parar el juego para volver a editar.',
            'En Propiedades cambias el tipo de juego, el objetivo, la velocidad, el salto, la gravedad, las vidas y el tiempo.',
            'La lista Estructura cuenta lo que hay en el nivel y avisa si falta algo, como el jugador o la meta.',
            'Exporta el juego jugable (HTML) o una imagen del nivel desde Archivo.',
        ],
        'sections': [
            {'h': 'Qué es cada casilla', 'p': 'Suelo: sólido por todos lados. Plataforma: se atraviesa desde abajo y se pisa desde arriba. Hielo: resbala. Peligro: quita una vida. Moneda: se recoge. Meta: termina el nivel. Trampolín: salta muy alto. Enemigo: camina de un lado a otro; si le saltas encima, desaparece. Llave y puerta: la puerta se abre cuando tienes la llave.'},
            {'h': 'Diseñar un buen nivel', 'p': 'Enseña cada idea primero en un sitio seguro y luego pide usarla con más dificultad. Deja que se vea la meta o una moneda antes de saltar a ciegas. Prueba el nivel muchas veces: si te frustra a ti, frustrará a otras personas.'},
            {'h': 'Un juego que se puede jugar de muchas formas', 'p': 'El juego exportado se maneja con teclado o con botones en pantalla táctil, anuncia las monedas, las vidas y el final para lectores de pantalla, se pausa con P o Esc y no tiene destellos.'},
        ],
        'links': [('Todo el taller', '/es/taller/'), ('Programación', '/es/taller/programacion/'), ('Pixel art', '/es/taller/pixel-art/')],
    },
    'en': {
        'title': 'Video game design',
        'description': 'Design platform levels or mazes by painting tiles: ground, coins, enemies, hazards, springs, keys and doors. Test them straight away and export a playable game in a single HTML file.',
        'lede': 'Paint the level, change the rules and press Play. When you like it, export it: you take away a real game in a single file that works in any browser, on phones too.',
        'make': ['A platform game', 'A maze seen from above', 'A race against the clock', 'Your game in an HTML file you can share'],
        'steps': [
            'Choose a tool below (Ground, Platform, Coin, Hazard, Goal, Enemy, Player) and paint by tapping or dragging on the level.',
            'Press Play. You play with the arrow keys and the space bar (or the on-screen buttons). Press Stop the game to go back to editing.',
            'Under Properties you change the kind of game, the goal, speed, jump, gravity, lives and time.',
            'The Structure list counts what is in the level and warns you if something is missing, such as the player or the goal.',
            'Export the playable game (HTML) or an image of the level from File.',
        ],
        'sections': [
            {'h': 'What each tile does', 'p': 'Ground: solid on every side. Platform: you can pass through it from below and stand on it from above. Ice: slippery. Hazard: costs a life. Coin: you collect it. Goal: ends the level. Spring: jumps very high. Enemy: walks back and forth; if you jump on it, it disappears. Key and door: the door opens once you have the key.'},
            {'h': 'Designing a good level', 'p': 'Show each idea first somewhere safe, then ask for it again with more difficulty. Let players see the goal or a coin before a blind jump. Play your level many times: if it frustrates you, it will frustrate others.'},
            {'h': 'A game that can be played in many ways', 'p': 'The exported game works with a keyboard or with on-screen buttons on touch screens, announces coins, lives and the ending to screen readers, pauses with P or Esc and has no flashing.'},
        ],
        'links': [('The whole workshop', '/en/workshop/'), ('Coding', '/en/workshop/coding/'), ('Pixel art', '/en/workshop/pixel-art/')],
    },
}

_T = {
    'es': {
        'canvasLabel': 'Editor de niveles', 'canvasHelp': 'Con el teclado: flechas para mover el cursor por las casillas, Intro para pintar con la herramienta elegida, Supr para vaciar la casilla. Ctrl o Cmd + Intro prueba el juego.',
        'kPaint': 'En el nivel: flechas mueven el cursor; Intro o Espacio pintan; Supr vacía la casilla', 'kPlayGame': 'Ctrl/Cmd + Intro: jugar · Al jugar: flechas, Espacio para saltar, P o Esc para pausar, Intro para reiniciar',
        'stFirst': 'Mi primer nivel', 'stFirstD': 'Un nivel corto con monedas, pinchos y un enemigo. Cambia las plataformas y juega.',
        'stPlat': 'Plataformas con llave', 'stPlatD': 'Coge la llave para abrir la puerta, recoge todas las monedas y llega a la meta.',
        'stIce': 'Mundo de hielo', 'stIceD': 'El hielo resbala: ajusta la velocidad y el salto para que sea justo.',
        'stMaze': 'Laberinto con puerta', 'stMazeD': 'Vista desde arriba: busca la llave, esquiva a los guardias y recoge las monedas.',
        'stSpeed': 'Contrarreloj', 'stSpeedD': 'Una sola vida y 45 segundos. Diseña un recorrido rápido pero justo.',
        'techGame': 'motor de juego propio (Canvas 2D)', 'mode_platform': 'Plataformas', 'mode_topdown': 'Vista desde arriba', 'playingBadge': 'Jugando',
        'tool_solid': 'Suelo', 'tool_platform': 'Plataforma', 'tool_coin': 'Moneda', 'tool_hazard': 'Peligro', 'tool_goal': 'Meta', 'tool_enemy': 'Enemigo', 'tool_player': 'Jugador', 'tool_erase': 'Borrar',
        'tool_spring': 'Trampolín', 'tool_ice': 'Hielo', 'tool_key': 'Llave', 'tool_door': 'Puerta', 'tool_pan': 'Mano',
        'help_solid': 'Pinta suelo sólido.', 'help_platform': 'Se atraviesa desde abajo.', 'help_coin': 'Algo que recoger.', 'help_hazard': 'Quita una vida.', 'help_goal': 'Donde termina el nivel.',
        'help_enemy': 'Camina de un lado a otro.', 'help_player': 'Dónde empieza la partida (solo uno).', 'help_erase': 'Vacía casillas.', 'help_spring': 'Salta muy alto.',
        'help_ice': 'Suelo que resbala.', 'help_key': 'Abre las puertas.', 'help_door': 'Se abre con la llave.', 'help_pan': 'Arrastra para mover la vista.',
        'tile_solid': 'Suelo', 'tile_platform': 'Plataforma', 'tile_coin': 'Moneda', 'tile_hazard': 'Peligro', 'tile_goal': 'Meta', 'tile_enemy': 'Enemigo', 'tile_player': 'Jugador',
        'tile_spring': 'Trampolín', 'tile_ice': 'Hielo', 'tile_key': 'Llave', 'tile_door': 'Puerta', 'tile_empty': 'Vacío',
        'painted': '{name}: {n} casillas', 'cellAt': 'Columna {x}, fila {y}: {what}',
        'gCoins': 'Monedas', 'gLives': 'Vidas', 'gTime': 'Tiempo', 'gKey': 'Llave', 'gReady': 'Pulsa una tecla para empezar', 'gWon': '¡Nivel superado!', 'gLost': 'Fin de la partida',
        'gPaused': 'En pausa', 'gPausedBlur': 'En pausa: vuelve al juego para seguir.', 'gPressKey': 'Cualquier tecla o botón para seguir', 'gRestart': 'Intro o un botón para jugar otra vez',
        'gHurt': 'Pierdes una vida.', 'gAllCoins': 'Tienes todas las monedas.', 'gTimeUp': 'Se acabó el tiempo.', 'gGotKey': 'Tienes la llave: las puertas se abren.',
        'gNeedCoins': 'Faltan {n} monedas para terminar.', 'gStarted': 'Empieza la partida.',
        'pNoPlayer': 'Falta el jugador.', 'pNoGoal': 'Falta la meta.', 'pNoCoins': 'El objetivo pide monedas y no hay ninguna.', 'pDoorNoKey': 'Hay puertas pero ninguna llave.',
        'gameRole': 'juego', 'gameLabel': '{title}. Juego: usa las flechas para moverte.', 'playStarted': 'Probando el juego. Las teclas llegan al juego.', 'backToEditor': 'De vuelta al editor.',
        'touchJump': 'Saltar', 'ctlMove': 'Flechas izquierda y derecha (o A y D): moverse', 'ctlJump': 'Espacio, flecha arriba o W: saltar', 'ctlPause': 'P o Esc: pausa', 'ctlRestart': 'Intro: jugar otra vez al terminar',
        'ctlMoveTop': 'Flechas o W A S D: moverse', 'goal_flag': 'llegar a la meta', 'goal_coins': 'recoger todas las monedas', 'goal_both': 'recoger todas las monedas y llegar a la meta',
        'goalLabel': 'Objetivo', 'controlsTitle': 'Controles', 'startGameBtn': 'Ir al juego', 'credit': 'Hecho en El taller de Iris Green', 'exportError': 'No se ha podido crear el archivo del juego.',
        'levelContents': 'En el nivel', 'goToNext': 'Ir al siguiente', 'toFix': 'Antes de jugar', 'gameTitle': 'Juego', 'titleLabel': 'Título', 'renamed': 'Título cambiado.',
        'introLabel': 'Presentación (aparece en el juego exportado)', 'introSet': 'Presentación cambiada.', 'modeLabel': 'Tipo de juego', 'modeSet': 'Tipo: {m}', 'goalSet': 'Objetivo cambiado.',
        'rulesTitle': 'Reglas', 'ruleSpeed': 'Velocidad', 'ruleJump': 'Fuerza del salto', 'ruleGravity': 'Gravedad', 'ruleEnemy': 'Velocidad de los enemigos', 'ruleLives': 'Vidas', 'ruleTime': 'Tiempo límite',
        'ruleTimeHelp': '0 segundos: sin límite de tiempo.', 'lookTitle': 'Aspecto', 'bgLabel': 'Fondo', 'playerColour': 'Color del jugador', 'sizeTitle': 'Tamaño del nivel',
        'widthTiles': 'Ancho (casillas)', 'heightTiles': 'Alto (casillas)', 'resized': 'Nivel de {w} × {h} casillas.',
        'levelSummary': 'Nivel de {mode}, {w} × {h} casillas: {coins} monedas, {enemies} enemigos, {hazards} peligros. Objetivo: {goal}.',
        'stopGame': 'Parar el juego', 'playGame': 'Jugar', 'exportHtml': 'Exportar el juego jugable (HTML)', 'exportPng': 'Exportar imagen del nivel (PNG)', 'defaultTitle': 'Mi juego',
        'title_first': 'Mi primer nivel', 'title_platformer': 'La llave del castillo', 'title_ice': 'Mundo de hielo', 'title_maze': 'El laberinto de los guardias', 'title_speedrun': 'Contrarreloj',
        'intro_first': 'Recoge monedas, salta los pinchos y llega a la bandera.', 'intro_platformer': 'Encuentra la llave, abre la puerta y recoge todas las monedas antes de llegar a la bandera.',
        'intro_ice': 'Cuidado: el hielo resbala.', 'intro_maze': 'Busca la llave y las monedas sin tocar a los guardias.', 'intro_speedrun': 'Tienes una vida y 45 segundos.',
    },
    'en': {
        'canvasLabel': 'Level editor', 'canvasHelp': 'With a keyboard: arrow keys move the cursor over the tiles, Enter paints with the chosen tool, Delete empties the tile. Ctrl or Cmd + Enter tests the game.',
        'kPaint': 'On the level: arrow keys move the cursor; Enter or Space paint; Delete empties the tile', 'kPlayGame': 'Ctrl/Cmd + Enter: play · While playing: arrow keys, Space to jump, P or Esc to pause, Enter to restart',
        'stFirst': 'My first level', 'stFirstD': 'A short level with coins, spikes and one enemy. Change the platforms and play.',
        'stPlat': 'Platforms with a key', 'stPlatD': 'Get the key to open the door, collect every coin and reach the goal.',
        'stIce': 'Ice world', 'stIceD': 'Ice is slippery: tune the speed and jump so it feels fair.',
        'stMaze': 'Maze with a door', 'stMazeD': 'Seen from above: find the key, dodge the guards and collect the coins.',
        'stSpeed': 'Race against the clock', 'stSpeedD': 'One life and 45 seconds. Design a route that is fast but fair.',
        'techGame': 'our own game engine (Canvas 2D)', 'mode_platform': 'Platform', 'mode_topdown': 'Top-down', 'playingBadge': 'Playing',
        'tool_solid': 'Ground', 'tool_platform': 'Platform', 'tool_coin': 'Coin', 'tool_hazard': 'Hazard', 'tool_goal': 'Goal', 'tool_enemy': 'Enemy', 'tool_player': 'Player', 'tool_erase': 'Erase',
        'tool_spring': 'Spring', 'tool_ice': 'Ice', 'tool_key': 'Key', 'tool_door': 'Door', 'tool_pan': 'Hand',
        'help_solid': 'Paint solid ground.', 'help_platform': 'You can pass through it from below.', 'help_coin': 'Something to collect.', 'help_hazard': 'Costs a life.', 'help_goal': 'Where the level ends.',
        'help_enemy': 'Walks back and forth.', 'help_player': 'Where the game starts (only one).', 'help_erase': 'Empties tiles.', 'help_spring': 'Jumps very high.',
        'help_ice': 'Slippery ground.', 'help_key': 'Opens doors.', 'help_door': 'Opens with the key.', 'help_pan': 'Drag to move the view.',
        'tile_solid': 'Ground', 'tile_platform': 'Platform', 'tile_coin': 'Coin', 'tile_hazard': 'Hazard', 'tile_goal': 'Goal', 'tile_enemy': 'Enemy', 'tile_player': 'Player',
        'tile_spring': 'Spring', 'tile_ice': 'Ice', 'tile_key': 'Key', 'tile_door': 'Door', 'tile_empty': 'Empty',
        'painted': '{name}: {n} tiles', 'cellAt': 'Column {x}, row {y}: {what}',
        'gCoins': 'Coins', 'gLives': 'Lives', 'gTime': 'Time', 'gKey': 'Key', 'gReady': 'Press a key to start', 'gWon': 'Level complete!', 'gLost': 'Game over',
        'gPaused': 'Paused', 'gPausedBlur': 'Paused: go back to the game to carry on.', 'gPressKey': 'Any key or button to carry on', 'gRestart': 'Enter or a button to play again',
        'gHurt': 'You lose a life.', 'gAllCoins': 'You have every coin.', 'gTimeUp': 'Time is up.', 'gGotKey': 'You have the key: the doors open.',
        'gNeedCoins': '{n} coins still needed to finish.', 'gStarted': 'The game starts.',
        'pNoPlayer': 'The player is missing.', 'pNoGoal': 'The goal is missing.', 'pNoCoins': 'The objective asks for coins and there are none.', 'pDoorNoKey': 'There are doors but no key.',
        'gameRole': 'game', 'gameLabel': '{title}. Game: use the arrow keys to move.', 'playStarted': 'Testing the game. Keys now go to the game.', 'backToEditor': 'Back to the editor.',
        'touchJump': 'Jump', 'ctlMove': 'Left and right arrows (or A and D): move', 'ctlJump': 'Space, up arrow or W: jump', 'ctlPause': 'P or Esc: pause', 'ctlRestart': 'Enter: play again at the end',
        'ctlMoveTop': 'Arrow keys or W A S D: move', 'goal_flag': 'reach the goal', 'goal_coins': 'collect every coin', 'goal_both': 'collect every coin and reach the goal',
        'goalLabel': 'Objective', 'controlsTitle': 'Controls', 'startGameBtn': 'Go to the game', 'credit': 'Made in the Iris Green workshop', 'exportError': 'The game file could not be created.',
        'levelContents': 'In the level', 'goToNext': 'Go to the next one', 'toFix': 'Before playing', 'gameTitle': 'Game', 'titleLabel': 'Title', 'renamed': 'Title changed.',
        'introLabel': 'Introduction (shown in the exported game)', 'introSet': 'Introduction changed.', 'modeLabel': 'Kind of game', 'modeSet': 'Kind: {m}', 'goalSet': 'Objective changed.',
        'rulesTitle': 'Rules', 'ruleSpeed': 'Speed', 'ruleJump': 'Jump strength', 'ruleGravity': 'Gravity', 'ruleEnemy': 'Enemy speed', 'ruleLives': 'Lives', 'ruleTime': 'Time limit',
        'ruleTimeHelp': '0 seconds: no time limit.', 'lookTitle': 'Look', 'bgLabel': 'Background', 'playerColour': 'Player colour', 'sizeTitle': 'Level size',
        'widthTiles': 'Width (tiles)', 'heightTiles': 'Height (tiles)', 'resized': 'Level of {w} × {h} tiles.',
        'levelSummary': '{mode} level, {w} × {h} tiles: {coins} coins, {enemies} enemies, {hazards} hazards. Objective: {goal}.',
        'stopGame': 'Stop the game', 'playGame': 'Play', 'exportHtml': 'Export the playable game (HTML)', 'exportPng': 'Export an image of the level (PNG)', 'defaultTitle': 'My game',
        'title_first': 'My first level', 'title_platformer': 'The castle key', 'title_ice': 'Ice world', 'title_maze': 'The guards’ maze', 'title_speedrun': 'Race against the clock',
        'intro_first': 'Collect coins, jump over the spikes and reach the flag.', 'intro_platformer': 'Find the key, open the door and collect every coin before reaching the flag.',
        'intro_ice': 'Careful: the ice is slippery.', 'intro_maze': 'Find the key and the coins without touching the guards.', 'intro_speedrun': 'You have one life and 45 seconds.',
    },
}
STRINGS = _T
assert set(STRINGS['es']) == set(STRINGS['en']), set(STRINGS['es']) ^ set(STRINGS['en'])
