"""Estudio de videomapping (R43): superficies con esquinas ajustables, proyección y espectáculo HTML. Textos ES/EN."""

ENGINE = 'videomapping'
SLUG = {'es': 'videomapping', 'en': 'projection-mapping'}
SCRIPTS = ['ig-suite-mapeo-runtime.js', 'ig-suite-videomapping.js']
LIBRARIES = 'código propio de Iris Green con CSS matrix3d y Canvas 2D, sin bibliotecas externas'
LIBRARIES_EN = 'Iris Green’s own code with CSS matrix3d and Canvas 2D, no external libraries'

PAGE = {
    'es': {
        'title': 'Videomapping',
        'description': 'Proyecta imágenes que encajan en objetos reales: una caja, una pared, una maqueta o una escalera. Ajusta las cuatro esquinas de cada superficie y exporta el espectáculo en un archivo HTML.',
        'lede': 'El videomapping (o mapping) proyecta luz sobre objetos para que parezcan cambiar de color, moverse o contar una historia. Aquí creas superficies, las llenas de contenidos y ajustas sus esquinas hasta que encajan con el objeto real.',
        'make': ['Una caja de cartón que cambia de color', 'Una fachada o una maqueta con ventanas que se iluminan', 'Una escalera con escalones animados', 'Un espectáculo con tus imágenes o tus vídeos', 'Un archivo HTML para proyectarlo desde cualquier ordenador'],
        'steps': [
            'Elige un ejemplo o pulsa «Añadir superficie». Cada superficie es una forma de cuatro esquinas.',
            'Arrastra los círculos numerados para colocar las esquinas. Con el teclado: Tab hasta una esquina y flechas (Mayús para ir más rápido).',
            'En Propiedades elige el contenido: color, degradado, rayas, ondas, texto, una imagen o un vídeo de tu dispositivo.',
            'Conecta el proyector como segunda pantalla, lleva allí esta ventana y pulsa «Proyectar». Activa el «Patrón de ajuste» y mueve las esquinas hasta que encajen con el objeto.',
            'Guarda el proyecto y exporta el espectáculo en HTML para reproducirlo en otro momento.',
        ],
        'sections': [
            {'h': 'Qué es el corner pinning', 'p': 'Un proyector casi nunca está justo delante del objeto, así que la imagen llega torcida. Ajustar las cuatro esquinas deforma la imagen con una transformación de perspectiva (homografía) para que, vista desde el objeto, quede recta. Es la misma técnica de los programas profesionales de mapping.'},
            {'h': 'Cómo preparar una proyección', 'p': 'Busca una sala con poca luz. Coloca el objeto y el proyector fijos: si se mueven, hay que volver a ajustar. Las superficies claras y mates (cartón blanco, papel, paredes lisas) reflejan mejor la luz. Empieza con el patrón de ajuste: cada superficie muestra una rejilla y los números 1 a 4 en sus esquinas.'},
            {'h': 'Sin destellos', 'p': 'Las animaciones de este estudio cambian el brillo como mucho una vez cada dos segundos, muy por debajo del límite de tres destellos por segundo que marcan las pautas de accesibilidad (WCAG 2.3.1). Si prefieres menos movimiento, las animaciones empiezan en pausa. Si usas tus propios vídeos, revisa que no tengan destellos rápidos.'},
            {'h': 'Tus imágenes y vídeos', 'p': 'Las imágenes se reducen y se guardan dentro del archivo del proyecto. Los vídeos no caben en el proyecto: se reproducen desde tu dispositivo y hay que volver a elegirlos al abrir el proyecto o el espectáculo exportado. Nada se envía a internet.'},
        ],
        'links': [('Todo el taller', '/es/taller/'), ('Modelado 3D', '/es/taller/modelado-3d/'), ('Diseño gráfico', '/es/taller/diseno-grafico/')],
    },
    'en': {
        'title': 'Projection mapping',
        'description': 'Project images that fit real objects: a box, a wall, a model or a staircase. Adjust the four corners of each surface and export the show as an HTML file.',
        'lede': 'Projection mapping projects light onto objects so they seem to change colour, move or tell a story. Here you create surfaces, fill them with content and adjust their corners until they fit the real object.',
        'make': ['A cardboard box that changes colour', 'A façade or scale model with windows that light up', 'A staircase with animated steps', 'A show with your own images or videos', 'An HTML file to project it from any computer'],
        'steps': [
            'Choose an example or press “Add surface”. Each surface is a four-cornered shape.',
            'Drag the numbered circles to place the corners. With the keyboard: Tab to a corner and use the arrow keys (Shift to go faster).',
            'In Properties choose the content: colour, gradient, stripes, waves, text, an image or a video from your device.',
            'Connect the projector as a second screen, move this window there and press “Project”. Turn on the “Alignment pattern” and move the corners until they fit the object.',
            'Save the project and export the show as HTML to play it another time.',
        ],
        'sections': [
            {'h': 'What corner pinning is', 'p': 'A projector is almost never straight in front of the object, so the image arrives skewed. Adjusting the four corners warps the image with a perspective transform (homography) so that, seen on the object, it looks straight. It is the same technique that professional mapping programs use.'},
            {'h': 'How to set up a projection', 'p': 'Find a room with little light. Keep the object and the projector fixed: if they move, you have to adjust again. Light, matt surfaces (white card, paper, smooth walls) reflect light best. Start with the alignment pattern: each surface shows a grid and the numbers 1 to 4 in its corners.'},
            {'h': 'No flashing', 'p': 'The animations in this studio change brightness at most once every two seconds, far below the limit of three flashes per second set by the accessibility guidelines (WCAG 2.3.1). If you prefer less motion, animations start paused. If you use your own videos, check that they have no rapid flashes.'},
            {'h': 'Your images and videos', 'p': 'Images are reduced and stored inside the project file. Videos do not fit in the project: they play from your device and you need to choose them again when you open the project or the exported show. Nothing is sent to the internet.'},
        ],
        'links': [('The whole workshop', '/en/workshop/'), ('3D modelling', '/en/workshop/3d-modelling/'), ('Graphic design', '/en/workshop/graphic-design/')],
    },
}

STRINGS = {
    'es': {
        'canvasLabel': 'Escenario de proyección',
        'canvasHelp': 'Toca una superficie para elegirla y arrástrala para moverla. Tab lleva a sus cuatro esquinas; las flechas las mueven (Mayús para ir más rápido). Con una superficie elegida, las flechas en el escenario la mueven entera. T muestra el patrón de ajuste, P pausa o reanuda y F proyecta a pantalla completa.',
        'kMapCorner': 'En una esquina: flechas para moverla (Mayús, más rápido)',
        'kMapShow': 'En el escenario: T patrón de ajuste · P pausa · F proyectar · en pantalla completa, Tab cambia de superficie con el patrón activo',
        'stWall': 'Pared mágica', 'stWallD': 'Una superficie grande con círculos que se expanden y un saludo. Proyéctala en una pared.',
        'stBox': 'Caja de cartón', 'stBoxD': 'Las tres caras visibles de una caja, cada una con su animación.',
        'stFacade': 'Fachada', 'stFacadeD': 'Un edificio con cuatro ventanas y una puerta con texto.',
        'stStairs': 'Escalera', 'stStairsD': 'Cuatro escalones en perspectiva con rayas y degradados.',
        'addSurface': 'Añadir superficie', 'projectBtn': 'Proyectar', 'testBtn': 'Patrón de ajuste', 'playBtn': 'Animación',
        'duplicateBtn': 'Duplicar', 'resetCorners': 'Enderezar esquinas', 'deleteBtn': 'Borrar', 'forward': 'Traer adelante', 'backward': 'Llevar atrás',
        'surfaceN': 'Superficie {n}', 'copyWord': 'copia', 'surfaces': 'Superficies', 'orderHelp': 'La de arriba de la lista se ve por encima de las demás.',
        'selectedSurface': 'Elegida: {name}', 'nothingSelected': 'Ninguna superficie elegida.',
        'added': 'Añadida: {name}', 'deleted': 'Borrada: {name}', 'duplicated': 'Duplicada', 'renamed': 'Nombre cambiado',
        'cTL': 'arriba a la izquierda', 'cTR': 'arriba a la derecha', 'cBR': 'abajo a la derecha', 'cBL': 'abajo a la izquierda',
        'cornerLabel': 'Esquina {n}, {corner}, de {name}: x {x}, y {y}. Flechas para moverla.',
        'cornerAnnounce': 'Esquina {n}: x {x}, y {y}', 'cornerMoved': 'Esquina movida', 'surfaceMoved': 'Superficie movida',
        'surfaceAnnounce': '{name}: esquina 1 en x {x}, y {y}', 'cornersReset': 'Esquinas enderezadas',
        'name': 'Nombre', 'content': 'Contenido',
        'type_color': 'Color', 'type_gradient': 'Degradado', 'type_stripes': 'Rayas', 'type_checker': 'Cuadros', 'type_circles': 'Círculos',
        'type_waves': 'Ondas', 'type_text': 'Texto', 'type_image': 'Imagen', 'type_video': 'Vídeo',
        'colour1': 'Color 1', 'colour2': 'Color 2', 'bgColour': 'Color de fondo', 'textColour': 'Color del texto', 'customColour': 'Color propio',
        'count': 'Cantidad', 'direction': 'Dirección', 'dirV': 'Verticales', 'dirH': 'Horizontales', 'angle': 'Ángulo', 'textLabel': 'Texto',
        'animate': 'Animar', 'speed': 'Velocidad', 'slow': 'Lenta', 'medium': 'Media', 'opacity': 'Opacidad',
        'fit': 'Ajuste de la imagen', 'fitCover': 'Llenar', 'fitContain': 'Entera',
        'chooseImage': 'Elegir imagen…', 'chooseVideo': 'Elegir vídeo…',
        'imageSet': 'Imagen puesta', 'videoSet': 'Vídeo puesto', 'imageTooBig': 'La imagen pesa más de 20 MB.', 'imageError': 'No se ha podido abrir esa imagen.',
        'imageMissing': 'Sin imagen', 'videoMissing': 'Elige el vídeo',
        'videoNote': 'Vídeo: {name}. Se reproduce desde tu dispositivo y no se guarda en el proyecto.',
        'videoMissingNote': 'Este vídeo no está cargado. Elígelo otra vez: los vídeos no se guardan en el proyecto.',
        'contentSet': 'Contenido cambiado', 'colourSet': 'Color cambiado', 'countSet': 'Cantidad cambiada', 'opacitySet': 'Opacidad cambiada',
        'corners': 'Esquinas', 'cornersHelp': 'En porcentaje del escenario: x de izquierda a derecha, y de arriba abajo.',
        'crossedTitle': 'Esquinas cruzadas', 'crossed': 'Dos lados se cruzan y la superficie no se puede dibujar. Mueve una esquina o pulsa Enderezar esquinas.',
        'showSettings': 'Espectáculo', 'pickSurface': 'Elige una superficie en el escenario o en la lista para cambiarla.',
        'noSurfaces': 'Aún no hay superficies. Pulsa Añadir superficie.',
        'output': 'Salida', 'aspect': 'Formato de la pantalla', 'aspect_16_9': '16:9 (panorámica)', 'aspect_16_10': '16:10', 'aspect_4_3': '4:3 (clásica)',
        'aspectSet': 'Formato cambiado', 'bgStage': 'Fondo del escenario',
        'safetyNote': 'Sin destellos: las animaciones cambian el brillo como mucho una vez cada dos segundos.',
        'testOn': 'Patrón de ajuste activado', 'testOff': 'Patrón de ajuste desactivado', 'playing': 'Animación en marcha', 'paused': 'Animación en pausa',
        'noFullscreen': 'Este navegador no permite la pantalla completa aquí.',
        'fsOn': 'Proyectando a pantalla completa. Esc para salir.', 'fsOff': 'Pantalla completa cerrada.',
        'fsHint': 'Esc para salir · T patrón de ajuste · P pausa',
        'summary': '{n} superficies en formato {aspect}: {list}.',
        'exportHtml': 'Exportar espectáculo (HTML)', 'exportPng': 'Exportar imagen (PNG)', 'exportError': 'No se ha podido exportar. Inténtalo de nuevo.',
        'showTitle': 'Mi espectáculo de videomapping',
        'exportIntro': 'Conecta el proyector, lleva esta ventana a esa pantalla y pulsa Proyectar.',
        'exportKeys': 'En pantalla completa: T muestra el patrón de ajuste, P pausa la animación y Esc sale.',
        'chooseVideoFor': 'Vídeo para «{name}»:', 'credit': 'Hecho en El taller',
        'exWall': 'Pared', 'exHello': 'Saludo', 'exHelloText': '¡Hola!', 'exTop': 'Cara de arriba', 'exLeft': 'Cara izquierda', 'exRight': 'Cara derecha',
        'exFacade': 'Fachada', 'exWindow': 'Ventana {n}', 'exDoor': 'Puerta', 'exDoorText': 'Bienvenida', 'exStep': 'Escalón {n}',
    },
    'en': {
        'canvasLabel': 'Projection stage',
        'canvasHelp': 'Tap a surface to select it and drag it to move it. Tab takes you to its four corners; the arrow keys move them (Shift to go faster). With a surface selected, the arrow keys on the stage move the whole surface. T shows the alignment pattern, P pauses or resumes and F projects full screen.',
        'kMapCorner': 'On a corner: arrow keys to move it (Shift, faster)',
        'kMapShow': 'On the stage: T alignment pattern · P pause · F project · in full screen, Tab changes surface while the pattern is on',
        'stWall': 'Magic wall', 'stWallD': 'A large surface with expanding circles and a greeting. Project it on a wall.',
        'stBox': 'Cardboard box', 'stBoxD': 'The three visible faces of a box, each with its own animation.',
        'stFacade': 'Façade', 'stFacadeD': 'A building with four windows and a door with text.',
        'stStairs': 'Staircase', 'stStairsD': 'Four steps in perspective with stripes and gradients.',
        'addSurface': 'Add surface', 'projectBtn': 'Project', 'testBtn': 'Alignment pattern', 'playBtn': 'Animation',
        'duplicateBtn': 'Duplicate', 'resetCorners': 'Straighten corners', 'deleteBtn': 'Delete', 'forward': 'Bring forward', 'backward': 'Send backward',
        'surfaceN': 'Surface {n}', 'copyWord': 'copy', 'surfaces': 'Surfaces', 'orderHelp': 'The one at the top of the list is shown above the others.',
        'selectedSurface': 'Selected: {name}', 'nothingSelected': 'No surface selected.',
        'added': 'Added: {name}', 'deleted': 'Deleted: {name}', 'duplicated': 'Duplicated', 'renamed': 'Name changed',
        'cTL': 'top left', 'cTR': 'top right', 'cBR': 'bottom right', 'cBL': 'bottom left',
        'cornerLabel': 'Corner {n}, {corner}, of {name}: x {x}, y {y}. Arrow keys to move it.',
        'cornerAnnounce': 'Corner {n}: x {x}, y {y}', 'cornerMoved': 'Corner moved', 'surfaceMoved': 'Surface moved',
        'surfaceAnnounce': '{name}: corner 1 at x {x}, y {y}', 'cornersReset': 'Corners straightened',
        'name': 'Name', 'content': 'Content',
        'type_color': 'Colour', 'type_gradient': 'Gradient', 'type_stripes': 'Stripes', 'type_checker': 'Checks', 'type_circles': 'Circles',
        'type_waves': 'Waves', 'type_text': 'Text', 'type_image': 'Image', 'type_video': 'Video',
        'colour1': 'Colour 1', 'colour2': 'Colour 2', 'bgColour': 'Background colour', 'textColour': 'Text colour', 'customColour': 'Custom colour',
        'count': 'Amount', 'direction': 'Direction', 'dirV': 'Vertical', 'dirH': 'Horizontal', 'angle': 'Angle', 'textLabel': 'Text',
        'animate': 'Animate', 'speed': 'Speed', 'slow': 'Slow', 'medium': 'Medium', 'opacity': 'Opacity',
        'fit': 'Image fit', 'fitCover': 'Fill', 'fitContain': 'Whole',
        'chooseImage': 'Choose image…', 'chooseVideo': 'Choose video…',
        'imageSet': 'Image set', 'videoSet': 'Video set', 'imageTooBig': 'The image is larger than 20 MB.', 'imageError': 'That image could not be opened.',
        'imageMissing': 'No image', 'videoMissing': 'Choose the video',
        'videoNote': 'Video: {name}. It plays from your device and is not stored in the project.',
        'videoMissingNote': 'This video is not loaded. Choose it again: videos are not stored in the project.',
        'contentSet': 'Content changed', 'colourSet': 'Colour changed', 'countSet': 'Amount changed', 'opacitySet': 'Opacity changed',
        'corners': 'Corners', 'cornersHelp': 'As a percentage of the stage: x from left to right, y from top to bottom.',
        'crossedTitle': 'Crossed corners', 'crossed': 'Two sides cross and the surface cannot be drawn. Move a corner or press Straighten corners.',
        'showSettings': 'Show', 'pickSurface': 'Select a surface on the stage or in the list to change it.',
        'noSurfaces': 'There are no surfaces yet. Press Add surface.',
        'output': 'Output', 'aspect': 'Screen format', 'aspect_16_9': '16:9 (widescreen)', 'aspect_16_10': '16:10', 'aspect_4_3': '4:3 (classic)',
        'aspectSet': 'Format changed', 'bgStage': 'Stage background',
        'safetyNote': 'No flashing: animations change brightness at most once every two seconds.',
        'testOn': 'Alignment pattern on', 'testOff': 'Alignment pattern off', 'playing': 'Animation playing', 'paused': 'Animation paused',
        'noFullscreen': 'This browser does not allow full screen here.',
        'fsOn': 'Projecting full screen. Esc to exit.', 'fsOff': 'Full screen closed.',
        'fsHint': 'Esc to exit · T alignment pattern · P pause',
        'summary': '{n} surfaces in {aspect} format: {list}.',
        'exportHtml': 'Export show (HTML)', 'exportPng': 'Export image (PNG)', 'exportError': 'Could not export. Please try again.',
        'showTitle': 'My projection mapping show',
        'exportIntro': 'Connect the projector, move this window to that screen and press Project.',
        'exportKeys': 'In full screen: T shows the alignment pattern, P pauses the animation and Esc exits.',
        'chooseVideoFor': 'Video for “{name}”:', 'credit': 'Made in The workshop',
        'exWall': 'Wall', 'exHello': 'Greeting', 'exHelloText': 'Hello!', 'exTop': 'Top face', 'exLeft': 'Left face', 'exRight': 'Right face',
        'exFacade': 'Façade', 'exWindow': 'Window {n}', 'exDoor': 'Door', 'exDoorText': 'Welcome', 'exStep': 'Step {n}',
    },
}
assert set(STRINGS['es']) == set(STRINGS['en'])
