import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { checkDeliveries } from './check-delivery.mjs';
function git(repo,...args){const r=spawnSync('git',['-C',repo,...args],{encoding:'utf8'});assert.equal(r.status,0,`git ${args.join(' ')}: ${r.stderr}`);return r.stdout.trim()}
function sha(buf){return createHash('sha256').update(buf).digest('hex')}
function write(repo,path,content){const p=join(repo,path);mkdirSync(dirname(p),{recursive:true});writeFileSync(p,content)}
function initRepo(){const repo=mkdtempSync(join(tmpdir(),'sabik-delivery-'));git(repo,'init','-q');git(repo,'config','user.email','qa@example.invalid');git(repo,'config','user.name','QA');write(repo,'README.md','base\n');git(repo,'add','.');git(repo,'commit','-qm','base');return{repo,base:git(repo,'rev-parse','HEAD')}}
function commitFile(repo,path,content,msg='change'){write(repo,path,content);git(repo,'add',path);git(repo,'commit','-qm',msg);return git(repo,'rev-parse','HEAD')}
function makePackage(repo,base,head,task,owner,paths,opts={}){const dir=mkdtempSync(join(tmpdir(),`pkg-${task}-`));const files=paths.map(path=>({path,sha256:sha(spawnSync('git',['-C',repo,'show',`${head}:${path}`],{encoding:null}).stdout)}));const m={task_id:task,owner,base_sha:opts.base??base,head_sha:head,tree_sha:git(repo,'rev-parse',`${head}^{tree}`),files,sha256:Object.fromEntries(files.map(x=>[x.path,x.sha256])),commands:opts.commands??['git status --short','node --test'],results:{tests:'pass'},...(opts.codex_review?{codex_review:opts.codex_review}:{})};writeFileSync(join(dir,'DELIVERY.json'),JSON.stringify(m,null,2));writeFileSync(join(dir,'CHANGES.patch'),git(repo,'diff','--binary',base,head)+'\n');return dir}
function reservations(file,tasks){writeFileSync(file,JSON.stringify({tasks},null,2))}
function codes(report,task){return report.deliveries.find(x=>x.task_id===task).findings.map(x=>x.code)}
test('valid package',()=>{const{repo,base}=initRepo(),head=commitFile(repo,'src/a.mjs','export const a=1;\n'),pkg=makePackage(repo,base,head,'R39-A1','Agente 1',['src/a.mjs']),rf=join(repo,'reservations.json');reservations(rf,{'R39-A1':{owner:'Agente 1',files:['src/a.mjs']}});const r=checkDeliveries({repo,realBase:base,reservationsFile:rf,packages:[pkg]});assert.equal(r.status,'VALID')});
test('hash incorrect is blocked',()=>{const{repo,base}=initRepo(),head=commitFile(repo,'src/a.mjs','x\n'),pkg=makePackage(repo,base,head,'A','Agent',['src/a.mjs']),mp=join(pkg,'DELIVERY.json'),m=JSON.parse(readFileSync(mp));m.files[0].sha256='0'.repeat(64);m.sha256[m.files[0].path]='0'.repeat(64);writeFileSync(mp,JSON.stringify(m));const rf=join(repo,'r.json');reservations(rf,{A:{owner:'Agent',files:['src/a.mjs']}});assert.ok(codes(checkDeliveries({repo,realBase:base,reservationsFile:rf,packages:[pkg]}),'A').includes('HASH_MISMATCH'))});
test('file outside reservation is blocked',()=>{const{repo,base}=initRepo(),head=commitFile(repo,'src/out.mjs','x\n'),pkg=makePackage(repo,base,head,'A','Agent',['src/out.mjs']),rf=join(repo,'r.json');reservations(rf,{A:{owner:'Agent',files:['src/allowed.mjs']}});assert.ok(codes(checkDeliveries({repo,realBase:base,reservationsFile:rf,packages:[pkg]}),'A').includes('OUT_OF_SCOPE_FILE'))});
test('two agents on same file are blocked',()=>{const{repo,base}=initRepo(),h1=commitFile(repo,'src/shared.mjs','one\n','one');git(repo,'checkout','-q',base);const h2=commitFile(repo,'src/shared.mjs','two\n','two'),p1=makePackage(repo,base,h1,'A1','Agent 1',['src/shared.mjs']),p2=makePackage(repo,base,h2,'A2','Agent 2',['src/shared.mjs']),rf=join(repo,'r.json');reservations(rf,{A1:{owner:'Agent 1',files:['src/shared.mjs']},A2:{owner:'Agent 2',files:['src/shared.mjs']}});const r=checkDeliveries({repo,realBase:base,reservationsFile:rf,packages:[p1,p2]});assert.equal(r.collisions.length,1)});
test('divergent declared base is blocked',()=>{const{repo,base}=initRepo(),head=commitFile(repo,'x.txt','x\n'),pkg=makePackage(repo,base,head,'A','Agent',['x.txt'],{base:'1'.repeat(40)}),rf=join(repo,'r.json');reservations(rf,{A:{owner:'Agent',files:['x.txt']}});assert.ok(codes(checkDeliveries({repo,realBase:base,reservationsFile:rf,packages:[pkg]}),'A').includes('BASE_DIVERGENT'))});
test('secrets and audio are excluded',()=>{const{repo,base}=initRepo();write(repo,'.env','SECRET=x\n');write(repo,'private/voice.wav','not audio');git(repo,'add','.');git(repo,'commit','-qm','bad');const head=git(repo,'rev-parse','HEAD'),pkg=makePackage(repo,base,head,'A','Agent',['.env','private/voice.wav']),rf=join(repo,'r.json');reservations(rf,{A:{owner:'Agent',files:['.env','private/voice.wav']}});const c=codes(checkDeliveries({repo,realBase:base,reservationsFile:rf,packages:[pkg]}),'A');assert.ok(c.includes('SECRET_PATH_EXCLUDED'));assert.ok(c.includes('AUDIO_EXCLUDED'))});
test('read-only git commands pass and mutating git commands block',()=>{const{repo,base}=initRepo(),head=commitFile(repo,'a.txt','a\n'),rf=join(repo,'r.json');reservations(rf,{GOOD:{owner:'Agent',files:['a.txt']},BAD:{owner:'Agent',files:['a.txt']}});const good=makePackage(repo,base,head,'GOOD','Agent',['a.txt'],{commands:['git status --short','git diff --name-only HEAD^ HEAD','node --test']}),bad=makePackage(repo,base,head,'BAD','Agent',['a.txt'],{commands:['git push origin HEAD']});assert.equal(checkDeliveries({repo,realBase:base,reservationsFile:rf,packages:[good]}).status,'VALID');assert.ok(codes(checkDeliveries({repo,realBase:base,reservationsFile:rf,packages:[bad]}),'BAD').includes('GIT_MUTATION_COMMAND'))});
test('shared file requires explicit Codex review',()=>{const{repo,base}=initRepo(),head=commitFile(repo,'shared/config.mjs','x\n'),rf=join(repo,'r.json');reservations(rf,{A:{owner:'Agent',files:['shared/config.mjs'],shared:['shared/config.mjs']}});const no=makePackage(repo,base,head,'A','Agent',['shared/config.mjs']);assert.ok(codes(checkDeliveries({repo,realBase:base,reservationsFile:rf,packages:[no]}),'A').includes('CODEX_REVIEW_REQUIRED'));const yes=makePackage(repo,base,head,'A','Agent',['shared/config.mjs'],{codex_review:{approved:true,reviewer:'Codex',evidence:'issue #237 comment'}});assert.equal(checkDeliveries({repo,realBase:base,reservationsFile:rf,packages:[yes]}).status,'VALID')});
