(function(){"use strict";
const P=window.PRISMA_FOSSILS_PILOT,B=window.FOSSILS_DATA,M=window.PRISMA_FOSSIL_MODEL,$=id=>document.getElementById(id);
const cv=$("scene"),ctx=cv.getContext("2d"),dialog=$("dialog");
const T={
 es:{journal:"Cuaderno",help:"Ayuda",title:"Haz visible un detalle de la roca.",lead:"Observa el indicio, despeja exactamente donde señalas y mira qué forma aparece.",encounter:"Encuentro",explore:"Explorar",brush:"Despejar",clear:"Despejar zona señalada",observe:"Observar detalle",guide:"Guiarme al siguiente detalle",identify:"Revelar contexto",sceneHelp:"Toca un indicio para señalarlo. En Explorar puedes arrastrar la roca; en Despejar actúas sólo sobre la zona señalada.",observation:"OBSERVACIÓN",noneTitle:"Todavía no has despejado un rasgo.",noneText:"Selecciona una zona del indicio y deja aparecer una forma legible.",context:"CONTEXTO REVELADO",depth:"Observar de cerca",next:"Siguiente encuentro",prep:"Sobre esta preparación digital",simulation:"La cobertura es una simplificación interactiva para observar la representación. No reproduce un procedimiento profesional de preparación fósil.",sources:"Fuentes y límites",close:"Cerrar",modeExplore:"EXPLORAR",modeBrush:"DESPEJAR",selected:"Zona señalada. Puedes despejar exactamente aquí.",outside:"Señala primero una zona visible del fósil.",cleared:"Cobertura retirada en la zona señalada.",partial:"Ha aparecido parte de la forma. Puedes observar lo visible o seguir despejando.",observable:"Hay un rasgo visible. Obsérvalo antes de revelar el contexto.",ready:"Los rasgos necesarios están visibles. Puedes revelar el contexto.",offscreen:"El detalle ya está despejado, pero ahora está fuera de vista. Reencuadra el fósil para observarlo.",identified:"Contexto revelado. Puedes profundizar o pasar al siguiente encuentro.",cancelled:"Gesto cancelado. Lo que ya se había despejado durante el arrastre permanece visible.",guideMsg:"He señalado el siguiente detalle. Nada se ha despejado todavía.",observeNeed:"Aún no hay un rasgo suficientemente visible para describirlo.",identifyNeed:"Todavía falta hacer visible el detalle necesario.",session:"El cuaderno dura sólo durante esta sesión; recargar reinicia el piloto.",emptyJournal:"Todavía no has revelado ningún contexto.",sourcesTitle:"Fuentes y límites",helpTitle:"Cómo explorar",helpBody:["Toca directamente una zona del fósil para señalarla.","En Explorar, arrastrar desplaza la vista. En Despejar, tocar o arrastrar retira cobertura local.","Si no quieres arrastrar, señala una zona y usa «Despejar zona señalada». «Guiarme» sólo señala/reencuadra: nunca despeja por ti.","Con teclado: Tab llega a controles; con la escena enfocada, las flechas mueven la vista en Explorar y el punto de trabajo en Despejar; Enter/Espacio actúan.","Cerrar una ficha conserva encuentro, cámara, zoom y cobertura."]},
 en:{journal:"Journal",help:"Help",title:"Make one detail in the rock visible.",lead:"Notice the clue, uncover exactly where you point, and look at the form that appears.",encounter:"Encounter",explore:"Explore",brush:"Uncover",clear:"Uncover marked area",observe:"Observe detail",guide:"Guide me to the next detail",identify:"Reveal context",sceneHelp:"Tap a clue to mark it. In Explore you can drag the rock; in Uncover you act only on the marked area.",observation:"OBSERVATION",noneTitle:"No feature is visible yet.",noneText:"Select an area of the clue and let a readable form appear.",context:"CONTEXT REVEALED",depth:"Observe closely",next:"Next encounter",prep:"About this digital preparation",simulation:"The covering is an interactive simplification for observing the representation. It does not reproduce professional fossil preparation.",sources:"Sources and limits",close:"Close",modeExplore:"EXPLORE",modeBrush:"UNCOVER",selected:"Area marked. You can uncover exactly here.",outside:"First mark a visible area of the fossil.",cleared:"Cover removed at the marked area.",partial:"Part of the form has appeared. You can observe what is visible or keep uncovering.",observable:"A feature is visible. Observe it before revealing the context.",ready:"The required features are visible. You can reveal the context.",offscreen:"The detail is uncovered but is now outside the visible scene. Reframe the fossil to observe it.",identified:"Context revealed. You can go deeper or move to the next encounter.",cancelled:"Gesture cancelled. Anything already uncovered during the drag remains visible.",guideMsg:"I marked the next detail. Nothing has been uncovered yet.",observeNeed:"No feature is sufficiently visible to describe yet.",identifyNeed:"A required detail is not visible yet.",session:"The journal lasts only for this session; reloading resets the pilot.",emptyJournal:"No context has been revealed yet.",sourcesTitle:"Sources and limits",helpTitle:"How to explore",helpBody:["Tap directly on an area of the fossil to mark it.","In Explore, dragging moves the view. In Uncover, tapping or dragging removes local cover.","If you do not want to drag, mark an area and use ‘Uncover marked area’. ‘Guide me’ only marks/reframes; it never uncovers for you.","Keyboard: Tab reaches controls; with the scene focused, arrows move the view in Explore and the work point in Uncover; Enter/Space acts.","Closing a detail panel preserves encounter, camera, zoom and uncovered areas."]}
};
let lang="es",active=0,mode="explore",W=960,H=640,gesture=null,origin=null,guideZone=null,guideUntil=0;
const assets=new Map(),states=new Map(),journal=new Set();
const sediment=new Image();sediment.src="assets/arte/sedimento.webp";
function tr(k){return T[lang][k]}
function tx(v){return typeof v==="string"?v:(v?.[lang]||v?.es||"")}
function allPieces(){return B.sectors.flatMap(s=>s.pieces.map(p=>({...p,sector:s})))}
function basePiece(id){return allPieces().find(p=>p.id===id)}
function encounter(){return P.encounters[active]}
function piece(){return basePiece(encounter().id)}
function state(){
 const id=encounter().id;
 if(!states.has(id))states.set(id,{cam:{cx:.5,cy:.5,z:1},strokes:encounter().initialReveal.map(s=>({...s})),point:null,observed:new Set(),identified:false});
 return states.get(id)
}
function asset(id){
 if(!assets.has(id)){const im=new Image();im.src=basePiece(id).asset;assets.set(id,im)}
 return assets.get(id)
}
function live(msg){$("live").textContent=msg}
function say(msg,kind=""){const n=$("sceneState");n.textContent=msg;n.className="status"+(kind?" "+kind:"");live(msg)}
function fit(){state().cam={cx:.5,cy:.5,z:1};render()}
function rectForZone(z,img){const a=M.toScreen(z.rect[0],z.rect[1],img,W,H,state().cam),b=M.toScreen(z.rect[2],z.rect[3],img,W,H,state().cam);return{x:a.x,y:a.y,w:b.x-a.x,h:b.y-a.y}}
function evaluation(){const im=asset(encounter().id);if(!im.complete||!im.naturalWidth)return{zones:[],observable:false,identifiable:false,revealedCount:0,visibleCount:0,offscreenRequired:false};return M.evaluate(encounter(),state().strokes,im,W,H,state().cam)}
function statusFromEval(ev){
 if(state().identified)return tr("identified");
 if(ev.identifiable)return tr("ready");
 if(ev.offscreenRequired)return tr("offscreen");
 if(ev.observable)return tr("observable");
 if(ev.revealedCount)return tr("partial");
 return state().point?tr("selected"):tx(encounter().clue)
}
function drawCover(im,r){
 const off=document.createElement("canvas");off.width=W;off.height=H;const c=off.getContext("2d");
 c.save();c.beginPath();c.rect(r.x,r.y,r.w,r.h);c.clip();
 if(sediment.complete&&sediment.naturalWidth){const pat=c.createPattern(sediment,"repeat");c.fillStyle=pat;c.globalAlpha=.95;c.fillRect(r.x,r.y,r.w,r.h)}else{c.fillStyle="#58605d";c.globalAlpha=.96;c.fillRect(r.x,r.y,r.w,r.h)}
 c.globalCompositeOperation="destination-out";
 for(const s of state().strokes){const q=M.toScreen(s.x,s.y,im,W,H,state().cam),rad=s.r*Math.min(r.w,r.h);const g=c.createRadialGradient(q.x,q.y,rad*.58,q.x,q.y,rad);g.addColorStop(0,"rgba(0,0,0,1)");g.addColorStop(.78,"rgba(0,0,0,.9)");g.addColorStop(1,"rgba(0,0,0,0)");c.fillStyle=g;c.beginPath();c.arc(q.x,q.y,rad,0,Math.PI*2);c.fill()}
 c.restore();ctx.drawImage(off,0,0)
}
function render(){
 const im=asset(encounter().id);ctx.clearRect(0,0,W,H);const bg=ctx.createLinearGradient(0,0,0,H);bg.addColorStop(0,"#182126");bg.addColorStop(1,"#0c1216");ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);
 if(!im.complete||!im.naturalWidth){ctx.fillStyle="#EEF4F8";ctx.font="18px sans-serif";ctx.fillText(lang==="es"?"Preparando la pieza…":"Preparing the piece…",24,38);return}
 const r=M.imageRect(im,W,H,state().cam);ctx.save();ctx.globalAlpha=.98;ctx.drawImage(im,r.x,r.y,r.w,r.h);ctx.restore();drawCover(im,r);
 if(state().point){const q=M.toScreen(state().point.x,state().point.y,im,W,H,state().cam);ctx.save();ctx.strokeStyle="#C3B8FF";ctx.lineWidth=3;ctx.beginPath();ctx.arc(q.x,q.y,15,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(q.x-22,q.y);ctx.lineTo(q.x+22,q.y);ctx.moveTo(q.x,q.y-22);ctx.lineTo(q.x,q.y+22);ctx.stroke();ctx.restore()}
 if(guideZone&&Date.now()<guideUntil){const ev=evaluation(),z=ev.zones.find(x=>x.id===guideZone);if(z){const rr=rectForZone(z,im);ctx.save();ctx.setLineDash([9,6]);ctx.strokeStyle="#FFD59A";ctx.lineWidth=4;ctx.strokeRect(rr.x,rr.y,rr.w,rr.h);ctx.restore()}}
}
function resize(){const r=$("viewport").getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);W=Math.max(1,Math.round(r.width));H=Math.max(1,Math.round(r.height));cv.width=Math.round(W*d);cv.height=Math.round(H*d);cv.style.width=W+"px";cv.style.height=H+"px";ctx.setTransform(d,0,0,d,0,0);render()}
function updateObservation(){
 const ev=evaluation(),s=state();$("journalCount").textContent=journal.size;$("observedList").replaceChildren();
 const visibleObserved=ev.zones.filter(z=>s.observed.has(z.id));
 if(!visibleObserved.length){$("observationKicker").textContent=tr("observation");$("observationTitle").textContent=tr("noneTitle");$("observationText").textContent=tr("noneText")}else{
   $("observationKicker").textContent=tr("observation");$("observationTitle").textContent=visibleObserved.length===1?tx(visibleObserved[0].label):(lang==="es"?"Dos detalles conectados":"Two connected details");$("observationText").textContent=tx(visibleObserved.at(-1).observation);
   for(const z of visibleObserved){const li=document.createElement("li");li.textContent=tx(z.label);$("observedList").append(li)}
 }
 $("identityBlock").hidden=!s.identified;if(s.identified){$("identityName").textContent=tx(encounter().identity.name);$("identityText").textContent=tx(encounter().identity.text);$("identityLimit").textContent=tx(encounter().identity.limit)}
 $("observe").disabled=!ev.observable;$("identify").disabled=!ev.identifiable||s.identified;$("nextBtn").disabled=active>=P.encounters.length-1;
 say(statusFromEval(ev),ev.identifiable||s.identified?"good":ev.offscreenRequired?"warn":"")
}
function sync(){
 document.documentElement.lang=lang;$("lang").textContent=lang==="es"?"EN":"ES";$("lang").setAttribute("aria-label",lang==="es"?"Switch to English":"Cambiar a español");
 $("journalBtn").childNodes[0].nodeValue=tr("journal")+" ";$("helpBtn").textContent=tr("help");$("title").textContent=tr("title");$("lead").textContent=tr("lead");document.querySelector('label[for="encounter"]').textContent=tr("encounter");
 $("exploreMode").textContent=tr("explore");$("brushMode").textContent=tr("brush");$("clearPoint").textContent=tr("clear");$("observe").textContent=tr("observe");$("guide").textContent=tr("guide");$("identify").textContent=tr("identify");$("sceneHelp").textContent=tr("sceneHelp");$("observationKicker").textContent=tr("observation");$("depthBtn").textContent=tr("depth");$("nextBtn").textContent=tr("next");document.querySelector(".secondary-info summary").textContent=tr("prep");$("simulationCopy").textContent=tr("simulation");$("sourcesBtn").textContent=tr("sources");$("closeDialog").textContent=tr("close");
 $("modeBadge").textContent=mode==="explore"?tr("modeExplore"):tr("modeBrush");$("scene").setAttribute("aria-label",(lang==="es"?"Superficie de roca, encuentro: ":"Rock surface, encounter: ")+tx(encounter().title));
 $("encounterStep").textContent=(active+1)+" / "+P.encounters.length;$("encounterTitle").textContent=tx(encounter().title);$("encounterClue").textContent=tx(encounter().clue);$("journalCount").textContent=journal.size;
 [...$("encounter").options].forEach((o,i)=>o.textContent=(i+1)+" · "+tx(P.encounters[i].title));$("encounter").value=String(active);updateObservation();render()
}
function setMode(next){mode=next;$("exploreMode").setAttribute("aria-pressed",String(mode==="explore"));$("brushMode").setAttribute("aria-pressed",String(mode==="brush"));$("modeBadge").textContent=mode==="explore"?tr("modeExplore"):tr("modeBrush");if(mode==="brush"&&!state().point)state().point={x:.5,y:.5};updateObservation();render();cv.focus({preventScroll:true})}
function local(ev){const r=cv.getBoundingClientRect();return{x:ev.clientX-r.left,y:ev.clientY-r.top}}
function normFromLocal(p){return M.toNorm(p.x,p.y,asset(encounter().id),W,H,state().cam)}
function pointVisible(p){if(!p)return false;const im=asset(encounter().id),q=M.toScreen(p.x,p.y,im,W,H,state().cam);return M.onImage(p)&&q.x>=12&&q.x<=W-12&&q.y>=12&&q.y<=H-12}
function selectPoint(p){if(!M.onImage(p)){say(tr("outside"),"warn");return false}state().point={x:M.clamp(p.x,0,1),y:M.clamp(p.y,0,1)};say(tr("selected"));render();return true}
function clearAt(p){if(!pointVisible(p)){say(tr("outside"),"warn");return false}state().strokes.push({x:p.x,y:p.y,r:P.brushRadius});state().point={...p};updateObservation();render();return true}
function observe(){const ev=evaluation();if(!ev.observable){say(tr("observeNeed"),"warn");return}for(const z of ev.zones.filter(z=>z.visible))state().observed.add(z.id);updateObservation();live(ev.zones.filter(z=>z.visible).map(z=>tx(z.observation)).join(" "))}
function identify(){const ev=evaluation();if(!ev.identifiable){say(ev.offscreenRequired?tr("offscreen"):tr("identifyNeed"),"warn");return}state().identified=true;journal.add(encounter().id);for(const z of ev.zones.filter(z=>z.visible))state().observed.add(z.id);updateObservation();live(tx(encounter().identity.name)+". "+tx(encounter().identity.text))}
function guide(){const ev=evaluation();let z=ev.zones.find(z=>encounter().requiredZones.includes(z.id)&&!z.visible);if(!z)z=ev.zones.find(z=>encounter().requiredZones.includes(z.id));if(!z)return;state().point={x:z.center[0],y:z.center[1]};guideZone=z.id;guideUntil=Date.now()+2600;const im=asset(encounter().id),q=M.toScreen(z.center[0],z.center[1],im,W,H,state().cam);if(q.x<40||q.x>W-40||q.y<40||q.y>H-40){state().cam.cx=z.center[0];state().cam.cy=z.center[1]}say(tr("guideMsg"));render();setTimeout(()=>{if(Date.now()>=guideUntil){guideZone=null;render()}},2700)}
function openDialog(title){origin=document.activeElement;$("dialogTitle").textContent=title;$("dialogBody").replaceChildren();dialog.showModal();$("closeDialog").focus()}
function closeDialog(){dialog.close()}
dialog.addEventListener("close",()=>{if(origin&&origin.isConnected)origin.focus();else cv.focus()});$("closeDialog").onclick=closeDialog;
function depth(){if(!state().identified)return;openDialog(tx(encounter().identity.name));const wrap=document.createElement("div");wrap.className="depth-grid";const left=document.createElement("div"),im=document.createElement("img");im.src=piece().asset;im.alt=tx(piece().conserva);left.append(im);const right=document.createElement("div"),p1=document.createElement("p");p1.textContent=tx(encounter().identity.text);const p2=document.createElement("p");p2.className="muted";p2.textContent=tx(encounter().identity.limit);const dl=document.createElement("dl");for(const [a,b] of [[lang==="es"?"Se conserva":"Preserved",tx(piece().conserva)],[lang==="es"?"Edad":"Age",tx(piece().edad)],[lang==="es"?"Referencia de procedencia":"Reference context",tx(piece().ref)]]){const dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=a;dd.textContent=b;dl.append(dt,dd)}right.append(p1,p2,dl);wrap.append(left,right);$("dialogBody").append(wrap)}
function showSources(){openDialog(tr("sourcesTitle"));const p=document.createElement("p");p.textContent=tx(encounter().identity.limit);$("dialogBody").append(p);const ul=document.createElement("ul");ul.className="source-list";for(const s of encounter().sources){const li=document.createElement("li"),a=document.createElement("a");a.href=s.url;a.textContent=s.title;const small=document.createElement("div");small.className="muted";small.textContent=(lang==="es"?"Consultado: ":"Consulted: ")+s.consulted+" · "+s.supports;li.append(a,small);ul.append(li)}$("dialogBody").append(ul)}
function showHelp(){openDialog(tr("helpTitle"));const ol=document.createElement("ol");for(const x of tr("helpBody")){const li=document.createElement("li");li.textContent=x;ol.append(li)}const p=document.createElement("p");p.className="muted";p.textContent=tr("session");$("dialogBody").append(ol,p)}
function showJournal(){openDialog(tr("journal"));if(!journal.size){const p=document.createElement("p");p.textContent=tr("emptyJournal");$("dialogBody").append(p);return}const host=document.createElement("div");host.className="journal-list";for(const e of P.encounters.filter(x=>journal.has(x.id))){const c=document.createElement("div");c.className="journal-card";const h=document.createElement("h3"),p=document.createElement("p");h.textContent=tx(e.identity.name);p.textContent=tx(e.identity.text);c.append(h,p);host.append(c)}$("dialogBody").append(host)}
function enter(i){active=M.clamp(i,0,P.encounters.length-1);mode="explore";guideZone=null;asset(encounter().id).onload=()=>{fit();sync()};$("encounter").value=String(active);sync();fit()}
function movePoint(dx,dy){const im=asset(encounter().id);let p=state().point||{x:.5,y:.5},q=M.toScreen(p.x,p.y,im,W,H,state().cam);q.x=M.clamp(q.x+dx,28,W-28);q.y=M.clamp(q.y+dy,28,H-28);p=M.toNorm(q.x,q.y,im,W,H,state().cam);state().point={x:M.clamp(p.x,0,1),y:M.clamp(p.y,0,1)};updateObservation();render()}
cv.addEventListener("pointerdown",ev=>{if(ev.button!==0)return;if(gesture)return;const p=local(ev);cv.focus({preventScroll:true});cv.setPointerCapture(ev.pointerId);gesture={id:ev.pointerId,start:p,last:p,moved:false,mode,camera:{...state().cam},changes:0}});
cv.addEventListener("pointermove",ev=>{if(!gesture||gesture.id!==ev.pointerId)return;const q=local(ev),g=gesture;if(Math.hypot(q.x-g.start.x,q.y-g.start.y)>8)g.moved=true;if(!g.moved)return;if(g.mode==="explore"){M.pan(state().cam,q.x-g.last.x,q.y-g.last.y,asset(encounter().id),W,H);g.last=q;updateObservation();render()}else{const a=normFromLocal(g.last),b=normFromLocal(q),steps=Math.max(1,Math.ceil(Math.hypot(q.x-g.last.x,q.y-g.last.y)/18));for(let i=0;i<=steps;i++){const p={x:a.x+(b.x-a.x)*i/steps,y:a.y+(b.y-a.y)*i/steps};if(pointVisible(p)){state().strokes.push({x:p.x,y:p.y,r:P.brushRadius*.78});g.changes++}}g.last=q;state().point=M.onImage(b)?b:state().point;updateObservation();render()}});
function endPointer(ev,cancelled){if(!gesture||gesture.id!==ev.pointerId)return;const g=gesture;gesture=null;if(!cancelled&&!g.moved){const p=normFromLocal(local(ev));if(g.mode==="explore")selectPoint(p);else clearAt(p)}else if(cancelled){say(tr("cancelled"),"warn")}else if(g.mode==="brush"){updateObservation()}if(cv.hasPointerCapture(ev.pointerId))cv.releasePointerCapture(ev.pointerId);render()}
cv.addEventListener("pointerup",ev=>endPointer(ev,false));cv.addEventListener("pointercancel",ev=>endPointer(ev,true));
cv.addEventListener("keydown",ev=>{if(ev.ctrlKey||ev.metaKey||ev.altKey)return;const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[ev.key];if(d){ev.preventDefault();if(mode==="explore"){M.pan(state().cam,d[0]*34,d[1]*34,asset(encounter().id),W,H);updateObservation();render()}else movePoint(d[0]*34,d[1]*34);return}if(ev.key==="Enter"||ev.key===" "){ev.preventDefault();if(mode==="brush")clearAt(state().point);else if(state().point)selectPoint(state().point);else selectPoint({x:.5,y:.5})}else if(ev.key==="+"||ev.key==="="){ev.preventDefault();M.zoom(state().cam,1.15);updateObservation();render()}else if(ev.key==="-"){ev.preventDefault();M.zoom(state().cam,1/1.15);updateObservation();render()}else if(ev.key.toLowerCase()==="o"){ev.preventDefault();observe()}else if(ev.key.toLowerCase()==="i"){ev.preventDefault();identify()}else if(ev.key==="Escape"){ev.preventDefault();setMode("explore")}});
$("exploreMode").onclick=()=>setMode("explore");$("brushMode").onclick=()=>setMode("brush");$("clearPoint").onclick=()=>clearAt(state().point);$("observe").onclick=observe;$("guide").onclick=guide;$("identify").onclick=identify;$("zoomIn").onclick=()=>{M.zoom(state().cam,1.15);updateObservation();render()};$("zoomOut").onclick=()=>{M.zoom(state().cam,1/1.15);updateObservation();render()};$("fit").onclick=fit;$("depthBtn").onclick=depth;$("nextBtn").onclick=()=>enter(active+1);$("helpBtn").onclick=showHelp;$("journalBtn").onclick=showJournal;$("sourcesBtn").onclick=showSources;$("encounter").onchange=e=>enter(Number(e.target.value));$("lang").onclick=()=>{lang=lang==="es"?"en":"es";sync()};
for(let i=0;i<P.encounters.length;i++)$("encounter").append(new Option("",String(i)));
new ResizeObserver(resize).observe($("viewport"));sediment.onload=render;for(const e of P.encounters){const im=asset(e.id);im.onload=()=>{if(e.id===encounter().id){resize();sync()}}}
window.__PRISMA_FOSSILS_QA__={getState:()=>({lang,active,mode,journal:[...journal],encounter:encounter().id,state:{...state(),observed:[...state().observed]},evaluation:evaluation()}),evaluate:evaluation,screenOf:(x,y)=>M.toScreen(x,y,asset(encounter().id),W,H,state().cam)};
sync();resize();enter(0);
})();