"""Estudio 10 · Circuitos. Textos ES/EN y retos."""

KEY = 'circuitos'
NUMBER = 10
SLUG = {'es': 'circuitos', 'en': 'circuits'}
SCRIPTS = ['ig-taller-circuitos-calc.js', 'ig-taller-circuitos.js']

LEVELS = {
    1: {'es': 'Electricidad: primeras luces', 'en': 'Electricity: first lights'},
    2: {'es': 'Electricidad con cuidado', 'en': 'Electricity with care'},
    3: {'es': 'Lógica: puertas', 'en': 'Logic: gates'},
    4: {'es': 'Lógica: memoria y sumas', 'en': 'Logic: memory and sums'},
    5: {'es': 'Sin techo', 'en': 'No ceiling'},
}

CHALLENGES = [
    {'id': 'c1', 'level': 1, 'mode': 'elec', 'rules': {'minLamps': 1, 'bright': 0.5, 'noBurn': True},
     'es': {'title': 'Enciende una bombilla', 'goal': 'Una pila, una bombilla y cables: haz que la bombilla luzca por lo menos a la mitad.', 'limits': ['Sin cortocircuito', 'La bombilla al 50 % o más'], 'tip': 'La corriente necesita un camino cerrado: sale por el + de la pila, pasa por la bombilla y vuelve al −.'},
     'en': {'title': 'Light a bulb', 'goal': 'A battery, a bulb and wires: make the bulb shine at least halfway.', 'limits': ['No short circuit', 'Bulb at 50% or more'], 'tip': 'Current needs a closed path: out of the battery’s +, through the bulb and back to −.'}},
    {'id': 'c2', 'level': 1, 'mode': 'elec', 'rules': {'minLamps': 2, 'bright': 0.8, 'noBurn': True},
     'es': {'title': 'Dos bombillas bien encendidas', 'goal': 'Dos bombillas con una sola pila, y las dos al 80 % o más.', 'limits': ['Al menos 2 bombillas', 'Todas al 80 % o más'], 'tip': 'Una detrás de otra (en serie) se reparten la tensión. Una al lado de otra (en paralelo) cada una recibe la pila entera.'},
     'en': {'title': 'Two bright bulbs', 'goal': 'Two bulbs on a single battery, both at 80% or more.', 'limits': ['At least 2 bulbs', 'All at 80% or more'], 'tip': 'One after the other (in series) they share the voltage. Side by side (in parallel) each gets the whole battery.'}},
    {'id': 'c3', 'level': 1, 'mode': 'elec', 'rules': {'minLamps': 2, 'needs': ['switch'], 'bright': 0.6, 'offToo': True, 'noBurn': True},
     'es': {'title': 'Un interruptor para dos luces', 'goal': 'Un solo interruptor enciende y apaga las dos bombillas a la vez.', 'limits': ['Un interruptor', 'Dos bombillas encendidas o las dos apagadas'], 'tip': 'Pon el interruptor en la parte del camino por la que pasa toda la corriente.'},
     'en': {'title': 'One switch for two lights', 'goal': 'A single switch turns both bulbs on and off together.', 'limits': ['One switch', 'Both bulbs on or both off'], 'tip': 'Put the switch on the part of the path that all the current goes through.'}},
    {'id': 'c4', 'level': 2, 'mode': 'elec', 'lim': {'battery': 'v9'}, 'rules': {'needs': ['led'], 'led': [0.005, 0.025], 'noBurn': True},
     'es': {'title': 'Un LED sin quemarlo', 'goal': 'Enciende un LED rojo con la pila de 9 V. Sin nada más, se quema: pon una resistencia para que pasen entre 5 y 25 mA.', 'limits': ['Pila de 9 V', 'Entre 5 y 25 mA por el LED', 'Nada quemado'], 'tip': 'Ley de Ohm: la resistencia se lleva lo que sobra, 9 − 2 = 7 V. 7 V entre 0,02 A son 350 Ω.'},
     'en': {'title': 'An LED without burning it', 'goal': 'Light a red LED with the 9 V battery. On its own it burns out: add a resistor so that 5 to 25 mA flows.', 'limits': ['9 V battery', '5 to 25 mA through the LED', 'Nothing burnt'], 'tip': 'Ohm’s law: the resistor takes what is left over, 9 − 2 = 7 V. 7 V divided by 0.02 A is 350 Ω.'}},
    {'id': 'c5', 'level': 2, 'mode': 'elec', 'rules': {'minLamps': 1, 'spdt': 2, 'stair': True},
     'es': {'title': 'Luz de escalera', 'goal': 'Una bombilla que se enciende y se apaga desde abajo y desde arriba: cualquiera de los dos conmutadores la cambia.', 'limits': ['Dos conmutadores', 'Cada conmutador cambia la luz'], 'tip': 'Une las dos salidas de un conmutador con las dos del otro. Los comunes van a la pila y a la bombilla.'},
     'en': {'title': 'Staircase light', 'goal': 'A bulb that goes on and off from downstairs and upstairs: either of the two changeover switches changes it.', 'limits': ['Two changeover switches', 'Each switch changes the light'], 'tip': 'Join the two outputs of one switch to the two outputs of the other. The common terminals go to the battery and the bulb.'}},
    {'id': 'c6', 'level': 2, 'mode': 'elec', 'rules': {'needs': ['motor'], 'spdt': 2, 'reverse': True},
     'es': {'title': 'Un motor en los dos sentidos', 'goal': 'Con dos conmutadores, haz que el motor gire en un sentido o en el otro.', 'limits': ['Dos conmutadores', 'Gira en los dos sentidos'], 'tip': 'Si la corriente entra por el otro lado del motor, gira al revés. Cada conmutador elige a qué lado de la pila va cada cable del motor.'},
     'en': {'title': 'A motor both ways', 'goal': 'With two changeover switches, make the motor turn one way or the other.', 'limits': ['Two changeover switches', 'Turns both ways'], 'tip': 'If current comes in from the motor’s other side, it turns the other way. Each switch chooses which side of the battery each motor wire goes to.'}},
    {'id': 'l1', 'level': 3, 'mode': 'logic', 'target': 'andNot', 'labels': {},
     'es': {'title': 'A y no B', 'goal': 'La luz S se enciende solo cuando A está a 1 y B está a 0.', 'limits': ['Entradas A y B, salida S', 'Coincide con la tabla'], 'tip': 'Una puerta NO delante de B y luego una puerta Y.'},
     'en': {'title': 'A and not B', 'goal': 'Light S comes on only when A is 1 and B is 0.', 'limits': ['Inputs A and B, output S', 'Matches the table'], 'tip': 'A NOT gate in front of B, then an AND gate.'}},
    {'id': 'l2', 'level': 3, 'mode': 'logic', 'target': 'half', 'labels': {},
     'es': {'title': 'Semisumador', 'goal': 'Suma dos bits A y B: S es el resultado y C es lo que «me llevo».', 'limits': ['Entradas A, B; salidas S y C', 'Coincide con la tabla'], 'tip': '1 + 1 = 10 en binario: S = 0 y C = 1. Mira qué puerta da 1 solo cuando las entradas son distintas.'},
     'en': {'title': 'Half adder', 'goal': 'Add two bits A and B: S is the sum and C is the carry.', 'limits': ['Inputs A, B; outputs S and C', 'Matches the table'], 'tip': '1 + 1 = 10 in binary: S = 0 and C = 1. Find the gate that gives 1 only when the inputs differ.'}},
    {'id': 'l3', 'level': 3, 'mode': 'logic', 'target': 'majority', 'labels': {},
     'es': {'title': 'Votación de tres', 'goal': 'La luz S se enciende cuando al menos dos de las tres entradas A, B y C están a 1.', 'limits': ['Entradas A, B, C; salida S'], 'tip': 'Mira cada pareja: A y B, A y C, B y C. Si alguna pareja está entera a 1, S se enciende.'},
     'en': {'title': 'Vote of three', 'goal': 'Light S comes on when at least two of the three inputs A, B and C are 1.', 'limits': ['Inputs A, B, C; output S'], 'tip': 'Look at each pair: A and B, A and C, B and C. If any pair is all 1, S comes on.'}},
    {'id': 'l4', 'level': 4, 'mode': 'logic', 'target': 'full', 'labels': {},
     'es': {'title': 'Sumador completo', 'goal': 'Suma A + B + E (E es lo que se trae de la columna anterior). Salidas S y C.', 'limits': ['Entradas A, B, E; salidas S y C'], 'tip': 'Dos semisumadores seguidos y una puerta O para juntar lo que se lleva cada uno.'},
     'en': {'title': 'Full adder', 'goal': 'Add A + B + E (E is the carry coming in from the previous column). Outputs S and C.', 'limits': ['Inputs A, B, E; outputs S and C'], 'tip': 'Two half adders in a row and an OR gate to join their carries.'}},
    {'id': 'l5', 'level': 4, 'mode': 'logic', 'target': 'xorNand', 'labels': {}, 'lim': {'only': ['nand']},
     'es': {'title': 'Todo con NO-Y', 'goal': 'La O exclusiva (S = 1 si A y B son distintos) usando solo puertas NO-Y.', 'limits': ['Solo puertas NO-Y', 'Entradas A, B; salida S'], 'tip': 'Se puede con cuatro puertas NO-Y. Empieza por NO-Y(A, B).'},
     'en': {'title': 'Everything from NAND', 'goal': 'Exclusive OR (S = 1 if A and B differ) using only NAND gates.', 'limits': ['NAND gates only', 'Inputs A, B; output S'], 'tip': 'It can be done with four NAND gates. Start with NAND(A, B).'}},
    {'id': 'l6', 'level': 4, 'mode': 'logic', 'labels': {'ins': [], 'clock': True},
     'es': {'traffic': ['V', 'A', 'R'], 'labels': {'ins': [], 'outs': ['V', 'A', 'R'], 'clock': True}, 'title': 'Semáforo', 'goal': 'Con el reloj y dos biestables D, haz un semáforo: con cada pulso pasa de verde (V) a ámbar (A), a rojo (R) y vuelta al verde. Siempre una sola luz.', 'limits': ['Salidas V, A, R', 'Una sola luz cada vez', 'Orden verde → ámbar → rojo'], 'tip': 'Dos biestables cuentan 00, 01, 10 y vuelta a 00. Una puerta NO-O de las dos salidas vale para el verde.'},
     'en': {'traffic': ['G', 'A', 'R'], 'labels': {'ins': [], 'outs': ['G', 'A', 'R'], 'clock': True}, 'title': 'Traffic light', 'goal': 'With the clock and two D flip-flops, build a traffic light: each pulse goes from green (G) to amber (A), to red (R) and back to green. Always a single light.', 'limits': ['Outputs G, A, R', 'One light at a time', 'Order green → amber → red'], 'tip': 'Two flip-flops count 00, 01, 10 and back to 00. A NOR gate of both outputs works for green.'}},
    {'id': 'l7', 'level': 4, 'mode': 'logic', 'target': 'add2', 'labels': {},
     'es': {'title': 'Sumador de dos bits', 'goal': 'Suma dos números de dos bits: A1A0 + B1B0 = S2S1S0.', 'limits': ['Entradas A1, A0, B1, B0; salidas S2, S1, S0'], 'tip': 'Un semisumador para las unidades (A0 + B0) y un sumador completo para la columna siguiente.'},
     'en': {'title': 'Two-bit adder', 'goal': 'Add two two-bit numbers: A1A0 + B1B0 = S2S1S0.', 'limits': ['Inputs A1, A0, B1, B0; outputs S2, S1, S0'], 'tip': 'A half adder for the units (A0 + B0) and a full adder for the next column.'}},
    {'id': 'l8', 'level': 5, 'mode': 'logic', 'random': True, 'labels': {},
     'es': {'title': 'Tabla misteriosa', 'goal': 'Cada vez sale una tabla de verdad distinta con tres entradas. Construye un circuito que la cumpla. No se acaban.', 'limits': ['Entradas A, B, C; salida S', 'Coincide con la tabla'], 'tip': 'Una puerta Y por cada fila con S = 1, y una O que las junte, siempre funciona. Luego intenta usar menos puertas.'},
     'en': {'title': 'Mystery table', 'goal': 'A different three-input truth table appears each time. Build a circuit that matches it. They never run out.', 'limits': ['Inputs A, B, C; output S', 'Matches the table'], 'tip': 'One AND gate for each row where S = 1, and an OR joining them, always works. Then try using fewer gates.'}},
]

STRINGS = {
    'es': {
        'thN': 'N.º', 'kEscCancel': 'Cancela el cable o componente en curso',
        'kNewDone': 'Circuito nuevo', 'kCanvasRole': 'placa de circuitos', 'kCanvasLabel': 'Placa de {m} con {n} componentes',
        'kKeyHint': 'Con teclado: entra en la placa con el tabulador, mueve el cursor con las flechas y pulsa Intro. Para cables y componentes de dos patas, Intro en el primer punto y en el último. La tabla de componentes permite usarlo todo sin la placa.',
        'kModeLabel': 'Tipo de circuito', 'kMode_elec': 'Electricidad', 'kMode_logic': 'Lógica',
        'kTools': 'Herramientas', 'kTool_place': 'Poner', 'kTool_wire': 'Cable', 'kTool_use': 'Usar', 'kTool_edit': 'Editar', 'kTool_delete': 'Borrar',
        'kToolHelp_place': 'Elige un componente en «Componentes». Los de dos patas se ponen de un punto a otro; las puertas, en un punto.', 'kToolHelp_wire': 'Une dos puntos con un cable: arrastra, o toca el inicio y luego el final.',
        'kToolHelp_use': 'Toca un interruptor, un conmutador o una entrada para cambiarlo.', 'kToolHelp_edit': 'Toca un componente para ver y cambiar sus datos.', 'kToolHelp_delete': 'Toca un componente o un cable para quitarlo.',
        'kParts': 'Componentes', 'kPartsPanel': 'Componentes', 'kState': 'Qué pasa', 'kProps': 'Componente elegido',
        'part_battery': 'Pila', 'part_resistor': 'Resistencia', 'part_lamp': 'Bombilla', 'part_led': 'LED', 'part_switch': 'Interruptor', 'part_spdt': 'Conmutador', 'part_motor': 'Motor', 'part_wire': 'Cable',
        'part_input': 'Entrada', 'part_clock': 'Reloj', 'part_out': 'Luz de salida', 'part_and': 'Puerta Y', 'part_or': 'Puerta O', 'part_not': 'Puerta NO', 'part_xor': 'O exclusiva', 'part_nand': 'Puerta NO-Y', 'part_nor': 'Puerta NO-O', 'part_dff': 'Biestable D',
        'kPartInfo_battery': 'Pila: el lado + es el extremo final del trazo. Cada pila tiene una pequeña resistencia interna.', 'kPartInfo_resistor': 'Resistencia: frena la corriente. I = V / R.',
        'kPartInfo_lamp': 'Bombilla de 4,5 V: luce al 100 % con 1,35 W; con el doble se funde.', 'kPartInfo_led': 'LED: solo deja pasar la corriente en un sentido (del inicio al final del trazo) y se quema por encima de 30 mA.',
        'kPartInfo_switch': 'Interruptor: abierto no deja pasar la corriente; cerrado, sí. Se cambia con «Usar».', 'kPartInfo_spdt': 'Conmutador: une su borne común (izquierda) con la salida de arriba o con la de abajo.',
        'kPartInfo_motor': 'Motor: gira si pasan más de 120 mA; el sentido depende de por dónde entra la corriente.',
        'kPartInfo_input': 'Entrada: vale 0 o 1. Se cambia con «Usar».', 'kPartInfo_clock': 'Reloj: da un pulso cada vez que pulsas «Pulso de reloj».', 'kPartInfo_out': 'Luz de salida: se enciende si su punto vale 1.',
        'kPartInfo_and': 'Y: da 1 si las dos entradas son 1. Entradas a la izquierda, salida a la derecha.', 'kPartInfo_or': 'O: da 1 si alguna entrada es 1.', 'kPartInfo_not': 'NO: da lo contrario de su entrada.',
        'kPartInfo_xor': 'O exclusiva: da 1 si las entradas son distintas.', 'kPartInfo_nand': 'NO-Y: lo contrario de Y. Con ella sola se puede construir cualquier otra puerta.', 'kPartInfo_nor': 'NO-O: lo contrario de O.',
        'kPartInfo_dff': 'Biestable D: guarda un bit. En cada pulso de reloj copia en Q lo que hay en D. Arriba D y Q; abajo reloj y Q̄ (lo contrario).',
        'kBatteryKind': 'Pila', 'bat_aa': '1,5 V (una pila AA)', 'bat_pack': '4,5 V (tres pilas AA)', 'bat_v9': '9 V (pila de petaca)', 'kResValue': 'Resistencia', 'kLedColor': 'Color del LED',
        'led_rojo': 'rojo', 'led_verde': 'verde', 'led_amarillo': 'amarillo', 'led_azul': 'azul',
        'kPulse': 'Pulso de reloj', 'kResetFF': 'Biestables a 0', 'kResetDone': 'Biestables a 0', 'kPulsed': 'Pulso dado.',
        'kStartMarked': 'Primer punto marcado. Mueve el cursor y pulsa Intro en el último.', 'kTooMany': 'Demasiados componentes para la placa.', 'kNoRoom': 'No cabe ahí: acércalo al centro de la placa.',
        'kOnlyParts': 'En este reto solo se usan: {p}.', 'kPlaced': '{p} puesto. Componentes: {n}', 'kNothingToUse': 'Ese componente no se usa: se cambia con «Editar».', 'kDeleted': 'Componente quitado',
        'kNoPartHere': 'No hay ningún componente en ese punto.', 'kCancelled': 'Cancelado', 'kCursor': 'Punto {x}, {y}: {what}', 'kEmptyPoint': 'libre', 'kFrom': 'empezado en {x}, {y}',
        'kBetween': 'entre {a} y {b}', 'kAt': 'en {p}', 'kClosed': 'cerrado', 'kOpen': 'abierto', 'kPos': 'posición {n}',
        'kBurnt': 'fundido', 'kOff': 'apagado', 'kStopped': 'parado', 'kShortShort': 'cortocircuito', 'kReverse': 'al revés: no deja pasar', 'kCW': 'sentido horario', 'kCCW': 'sentido antihorario',
        'kEmptyElec': 'Pon una pila y algo que consuma: bombilla, LED o motor.', 'kNoBattery': 'Falta una pila.', 'kCantSolve': 'No se puede calcular este circuito.',
        'kLampLine': 'Bombilla {n}: {b}', 'kLedLine': 'LED {n}: {s}', 'kMotorLine': 'Motor {n}: {s}', 'kBatLine': 'Pila {n}: da {i} mA con {v} V entre sus bornes',
        'kShort': 'Cortocircuito: la corriente vuelve a la pila sin pasar por nada que la frene. En la realidad la pila se calentaría.',
        'kEmptyLogic': 'Pon entradas, puertas y luces de salida, y únelas con cables.', 'kConflict': 'Dos salidas están unidas en el mismo cable. Cada cable debe tener una sola salida.',
        'kOscillates': 'El circuito no se estabiliza: cambia sin parar.', 'kOutputsNow': 'Salidas ahora: {o}', 'kNoOutputs': 'No hay luces de salida.',
        'kTableCap': 'Componentes ({n})', 'kThPart': 'Componente', 'kThActions': 'Acciones', 'kUseN': 'Cambiar {n}', 'kEditN': 'Editar el componente {n}', 'kDelN': 'Quitar el componente {n}',
        'kTTCap': 'Tabla de verdad del circuito', 'kTTFF': '(con los biestables como están ahora)', 'kTTTooMany': 'Más de 6 entradas: la tabla sería demasiado larga.', 'kTTNeed': 'La tabla de verdad aparece cuando hay entradas y luces de salida.', 'kOutMark': '(salida)',
        'kAltTitle': 'Qué hay en la placa', 'kAltText': '{m}: {n} componentes. {parts}.', 'kAltEmpty': 'La placa está vacía.',
        'kLegendElec': 'Cable azul y grueso: pasa corriente. Gris: no pasa. Las bombillas y los LED brillan según la corriente; la tabla da los valores.',
        'kLegendLogic': 'Cable naranja, grueso y continuo: vale 1. Gris y discontinuo: vale 0. Punteado claro: sin conectar.',
        'kPropsEmpty': 'Elige un componente con «Editar» o con el botón de la tabla.', 'kLabel': 'Nombre (hasta 4 letras)', 'kLabelSet': 'Nombre: {l}', 'kFlip': 'Dar la vuelta', 'kFlipped': 'Componente girado', 'kToggle': 'Cambiar', 'kDelete': 'Quitar',
        'kPrepare': 'Poner las entradas y salidas del reto', 'kPrepared': 'Entradas y salidas puestas', 'kAnother': 'Otra tabla', 'kNewTable': 'Tabla nueva', 'kTargetCap': 'Tabla que tiene que cumplir',
        'kDone': 'Reto cumplido.', 'kNotYet': 'Así va. Cambia lo que haga falta: se comprueba solo.',
        'kChkLabels': 'Entradas y salidas con los nombres {l}', 'kChkNoConflict': 'Ningún cable con dos salidas', 'kChkNoOsc': 'El circuito se estabiliza', 'kChkTable': 'Tabla: {ok} de {n} valores bien',
        'kChkOnly': 'Solo {p}', 'kChkMaxGates': 'Puertas: {n} (máximo {m})', 'kChkOneLight': 'Una sola luz en cada paso', 'kChkOrder': 'Orden correcto durante 8 pulsos',
        'kChkLamps': 'Bombillas: {n} (mínimo {m})', 'kChkHas': 'Incluye: {p}', 'kChkNoShort': 'Sin cortocircuitos en ninguna posición', 'kChkBright': 'Todas las bombillas al {p} % o más',
        'kChkOffToo': 'Todas apagadas con el interruptor abierto', 'kChkNoBurn': 'Nada se funde ni se quema', 'kChkLed': 'Un LED encendido con entre {a} y {b} mA', 'kChkStair': 'Cada conmutador cambia la luz', 'kChkReverse': 'El motor gira en los dos sentidos',
    },
    'en': {
        'thN': 'No.', 'kEscCancel': 'Cancels the wire or part in progress',
        'kNewDone': 'New circuit', 'kCanvasRole': 'circuit board', 'kCanvasLabel': '{m} board with {n} parts',
        'kKeyHint': 'With a keyboard: tab into the board, move the cursor with the arrow keys and press Enter. For wires and two-legged parts, press Enter on the first point and on the last. The parts table lets you do everything without the board.',
        'kModeLabel': 'Type of circuit', 'kMode_elec': 'Electricity', 'kMode_logic': 'Logic',
        'kTools': 'Tools', 'kTool_place': 'Place', 'kTool_wire': 'Wire', 'kTool_use': 'Use', 'kTool_edit': 'Edit', 'kTool_delete': 'Delete',
        'kToolHelp_place': 'Choose a part under “Parts”. Two-legged parts go from one point to another; gates go on one point.', 'kToolHelp_wire': 'Join two points with a wire: drag, or tap the start and then the end.',
        'kToolHelp_use': 'Tap a switch, a changeover switch or an input to change it.', 'kToolHelp_edit': 'Tap a part to see and change its details.', 'kToolHelp_delete': 'Tap a part or a wire to remove it.',
        'kParts': 'Parts', 'kPartsPanel': 'Parts', 'kState': 'What happens', 'kProps': 'Chosen part',
        'part_battery': 'Battery', 'part_resistor': 'Resistor', 'part_lamp': 'Bulb', 'part_led': 'LED', 'part_switch': 'Switch', 'part_spdt': 'Changeover switch', 'part_motor': 'Motor', 'part_wire': 'Wire',
        'part_input': 'Input', 'part_clock': 'Clock', 'part_out': 'Output light', 'part_and': 'AND gate', 'part_or': 'OR gate', 'part_not': 'NOT gate', 'part_xor': 'XOR gate', 'part_nand': 'NAND gate', 'part_nor': 'NOR gate', 'part_dff': 'D flip-flop',
        'kPartInfo_battery': 'Battery: the + side is the end of the stroke. Each battery has a small internal resistance.', 'kPartInfo_resistor': 'Resistor: holds the current back. I = V / R.',
        'kPartInfo_lamp': '4.5 V bulb: 100% at 1.35 W; at twice that it blows.', 'kPartInfo_led': 'LED: only lets current through one way (from the start to the end of the stroke) and burns out above 30 mA.',
        'kPartInfo_switch': 'Switch: open, no current flows; closed, it does. Change it with “Use”.', 'kPartInfo_spdt': 'Changeover switch: joins its common terminal (left) to the top output or the bottom one.',
        'kPartInfo_motor': 'Motor: turns if more than 120 mA flows; the direction depends on where the current comes in.',
        'kPartInfo_input': 'Input: 0 or 1. Change it with “Use”.', 'kPartInfo_clock': 'Clock: gives a pulse each time you press “Clock pulse”.', 'kPartInfo_out': 'Output light: comes on if its point is 1.',
        'kPartInfo_and': 'AND: gives 1 if both inputs are 1. Inputs on the left, output on the right.', 'kPartInfo_or': 'OR: gives 1 if any input is 1.', 'kPartInfo_not': 'NOT: gives the opposite of its input.',
        'kPartInfo_xor': 'XOR: gives 1 if the inputs differ.', 'kPartInfo_nand': 'NAND: the opposite of AND. With it alone you can build any other gate.', 'kPartInfo_nor': 'NOR: the opposite of OR.',
        'kPartInfo_dff': 'D flip-flop: stores one bit. On each clock pulse it copies D into Q. D and Q at the top; clock and Q̄ (the opposite) at the bottom.',
        'kBatteryKind': 'Battery', 'bat_aa': '1.5 V (one AA battery)', 'bat_pack': '4.5 V (three AA batteries)', 'bat_v9': '9 V (PP3 battery)', 'kResValue': 'Resistance', 'kLedColor': 'LED colour',
        'led_rojo': 'red', 'led_verde': 'green', 'led_amarillo': 'yellow', 'led_azul': 'blue',
        'kPulse': 'Clock pulse', 'kResetFF': 'Flip-flops to 0', 'kResetDone': 'Flip-flops at 0', 'kPulsed': 'Pulse given.',
        'kStartMarked': 'First point marked. Move the cursor and press Enter on the last one.', 'kTooMany': 'Too many parts for the board.', 'kNoRoom': 'It does not fit there: move it towards the middle of the board.',
        'kOnlyParts': 'This challenge only uses: {p}.', 'kPlaced': '{p} placed. Parts: {n}', 'kNothingToUse': 'That part is not used: change it with “Edit”.', 'kDeleted': 'Part removed',
        'kNoPartHere': 'There is no part at that point.', 'kCancelled': 'Cancelled', 'kCursor': 'Point {x}, {y}: {what}', 'kEmptyPoint': 'free', 'kFrom': 'started at {x}, {y}',
        'kBetween': 'between {a} and {b}', 'kAt': 'at {p}', 'kClosed': 'closed', 'kOpen': 'open', 'kPos': 'position {n}',
        'kBurnt': 'blown', 'kOff': 'off', 'kStopped': 'stopped', 'kShortShort': 'short circuit', 'kReverse': 'backwards: lets nothing through', 'kCW': 'clockwise', 'kCCW': 'anticlockwise',
        'kEmptyElec': 'Place a battery and something that uses power: a bulb, an LED or a motor.', 'kNoBattery': 'A battery is missing.', 'kCantSolve': 'This circuit cannot be calculated.',
        'kLampLine': 'Bulb {n}: {b}', 'kLedLine': 'LED {n}: {s}', 'kMotorLine': 'Motor {n}: {s}', 'kBatLine': 'Battery {n}: gives {i} mA with {v} V across its terminals',
        'kShort': 'Short circuit: the current goes back to the battery without passing through anything to hold it back. In real life the battery would get hot.',
        'kEmptyLogic': 'Place inputs, gates and output lights, and join them with wires.', 'kConflict': 'Two outputs are joined on the same wire. Each wire must have only one output.',
        'kOscillates': 'The circuit does not settle: it keeps changing.', 'kOutputsNow': 'Outputs now: {o}', 'kNoOutputs': 'There are no output lights.',
        'kTableCap': 'Parts ({n})', 'kThPart': 'Part', 'kThActions': 'Actions', 'kUseN': 'Change {n}', 'kEditN': 'Edit part {n}', 'kDelN': 'Remove part {n}',
        'kTTCap': 'Truth table of the circuit', 'kTTFF': '(with the flip-flops as they are now)', 'kTTTooMany': 'More than 6 inputs: the table would be too long.', 'kTTNeed': 'The truth table appears once there are inputs and output lights.', 'kOutMark': '(output)',
        'kAltTitle': 'What is on the board', 'kAltText': '{m}: {n} parts. {parts}.', 'kAltEmpty': 'The board is empty.',
        'kLegendElec': 'Thick blue wire: current flows. Grey: it does not. Bulbs and LEDs shine according to the current; the table gives the values.',
        'kLegendLogic': 'Thick, solid orange wire: it is 1. Grey and dashed: it is 0. Light dotted: not connected.',
        'kPropsEmpty': 'Choose a part with “Edit” or with the button in the table.', 'kLabel': 'Name (up to 4 letters)', 'kLabelSet': 'Name: {l}', 'kFlip': 'Turn round', 'kFlipped': 'Part turned round', 'kToggle': 'Change', 'kDelete': 'Remove',
        'kPrepare': 'Place the challenge inputs and outputs', 'kPrepared': 'Inputs and outputs placed', 'kAnother': 'Another table', 'kNewTable': 'New table', 'kTargetCap': 'Table to match',
        'kDone': 'Challenge done.', 'kNotYet': 'Here is how it is going. Change what you need: it checks itself.',
        'kChkLabels': 'Inputs and outputs named {l}', 'kChkNoConflict': 'No wire with two outputs', 'kChkNoOsc': 'The circuit settles', 'kChkTable': 'Table: {ok} of {n} values right',
        'kChkOnly': 'Only {p}', 'kChkMaxGates': 'Gates: {n} (at most {m})', 'kChkOneLight': 'A single light at each step', 'kChkOrder': 'Right order for 8 pulses',
        'kChkLamps': 'Bulbs: {n} (at least {m})', 'kChkHas': 'Includes: {p}', 'kChkNoShort': 'No short circuit in any position', 'kChkBright': 'All bulbs at {p}% or more',
        'kChkOffToo': 'All off with the switch open', 'kChkNoBurn': 'Nothing blows or burns out', 'kChkLed': 'An LED lit with {a} to {b} mA', 'kChkStair': 'Each changeover switch changes the light', 'kChkReverse': 'The motor turns both ways',
    },
}
assert set(STRINGS['es']) == set(STRINGS['en'])

PAGE = {
    'es': {
        'title': 'Estudio de circuitos',
        'description': 'Circuitos eléctricos con pilas, bombillas, LED, resistencias, interruptores y motores, calculados en directo, y circuitos lógicos con puertas, biestables y tablas de verdad.',
        'lede': 'Una placa para montar circuitos de verdad. En Electricidad, la corriente se calcula al momento: bombillas que brillan, LED que se queman y motores que giran. En Lógica, puertas, memoria y sumas en binario.',
        'pills': ['Electricidad y lógica', 'Cálculo en directo', 'Tabla de verdad automática', 'Biestables y reloj', '14 retos en 5 niveles', 'Tabla de componentes accesible'],
        'steps': [
            'Elige Electricidad o Lógica, o un reto.',
            'Con «Poner», elige un componente y colócalo en la placa. Une los puntos con «Cable».',
            'Con «Usar», cambia interruptores, conmutadores y entradas. El resultado se ve al momento.',
            'En Lógica, la tabla de verdad se escribe sola. Con «Pulso de reloj» avanzan los biestables.',
            'Los retos se comprueban solos mientras montas. Guarda el circuito en un archivo para seguir otro día.',
        ],
        'sections': [
            {'h': 'Cómo calcula', 'p': 'En Electricidad se usan las leyes de Kirchhoff y la ley de Ohm: la corriente que entra en cada punto es la que sale, y en cada componente V = I × R. Los LED se tratan como una puerta que se abre a partir de cierta tensión.\n\nEn Lógica, cada cable vale 0 o 1. Las puertas se calculan hasta que todo queda quieto; los biestables D cambian solo en el pulso de reloj.',
             'li': ['Valores aproximados: pila AA de 1,5 V, grupo de tres pilas de 4,5 V y pila de 9 V, con su resistencia interna; bombilla de 4,5 V y 0,3 A; LED rojo de 2 V que se quema por encima de 30 mA; motor de 8 Ω.',
                    'Es un modelo para aprender. No sirve para montar instalaciones de la red eléctrica de casa: esas tienen tensiones peligrosas.']},
        ],
        'links': [('Estudio de robótica: sensores y motores con programa', '/es/taller/robotica/'), ('Estudio de programación', '/es/taller/programacion/'), ('Estudio de máquinas', '/es/taller/maquinas/'), ('Volver al Taller', '/es/taller/')],
        'credits': 'Estudio de circuitos de Iris Green. Cálculo propio en el navegador, sin servicios externos.',
    },
    'en': {
        'title': 'Circuits studio',
        'description': 'Electric circuits with batteries, bulbs, LEDs, resistors, switches and motors, calculated live, and logic circuits with gates, flip-flops and truth tables.',
        'lede': 'A board for building real circuits. In Electricity, the current is calculated instantly: bulbs that shine, LEDs that burn out and motors that turn. In Logic, gates, memory and binary sums.',
        'pills': ['Electricity and logic', 'Live calculation', 'Automatic truth table', 'Flip-flops and clock', '14 challenges on 5 levels', 'Accessible parts table'],
        'steps': [
            'Choose Electricity or Logic, or a challenge.',
            'With “Place”, choose a part and put it on the board. Join the points with “Wire”.',
            'With “Use”, change switches, changeover switches and inputs. You see the result straight away.',
            'In Logic, the truth table writes itself. With “Clock pulse” the flip-flops move on.',
            'Challenges check themselves while you build. Save the circuit to a file to carry on another day.',
        ],
        'sections': [
            {'h': 'How it calculates', 'p': 'Electricity uses Kirchhoff’s laws and Ohm’s law: the current flowing into each point is the current flowing out, and in each part V = I × R. LEDs are treated as a gate that opens above a certain voltage.\n\nIn Logic, each wire is 0 or 1. Gates are worked out until everything is settled; D flip-flops only change on the clock pulse.',
             'li': ['Approximate values: 1.5 V AA battery, 4.5 V pack of three and 9 V battery, with their internal resistance; 4.5 V 0.3 A bulb; 2 V red LED that burns out above 30 mA; 8 Ω motor.',
                    'It is a model for learning. It is not for wiring anything to the mains at home: mains voltages are dangerous.']},
        ],
        'links': [('Robotics studio: sensors and motors with a program', '/en/workshop/robotics/'), ('Coding studio', '/en/workshop/coding/'), ('Machines studio', '/en/workshop/machines/'), ('Back to the workshop', '/en/workshop/')],
        'credits': 'Iris Green circuits studio. Our own calculation in the browser, with no external services.',
    },
}
