"""Textos del lenguaje y del editor compartidos por Programación y Robótica."""

C = {
    'es': {
        'cView': 'Vista del programa', 'cBlocks': 'Bloques', 'cText': 'Texto', 'cBlocksView': 'Vista de bloques', 'cTextView': 'Vista de texto',
        'cTextLabel': 'Programa en texto', 'cTextHelp': 'Una orden por línea. Los bloques se abren con { y se cierran con }. Lo que va detrás de # es un comentario. Se aceptan palabras en español y en inglés.',
        'cApplyText': 'Usar este texto', 'cTextApplied': 'Texto convertido en bloques', 'cErrAt': 'Línea {line}: {m}',
        'cGroup_move': 'Moverse', 'cGroup_control': 'Control', 'cGroup_data': 'Datos', 'cGroup_func': 'Funciones',
        'cSetVar': 'guardar en variable', 'cDefFunc': 'definir función', 'cCallFunc': 'usar función', 'cHello': 'hola', 'cFuncDefault': 'figura',
        'cInserted': 'Añadido: {b}', 'cInsertHere': 'Lo siguiente se añadirá aquí', 'cCannot': 'No se puede mover más en esa dirección',
        'cOp_up': 'Subido', 'cOp_down': 'Bajado', 'cOp_out': 'Sacado del bloque', 'cOp_in': 'Metido en el bloque de arriba', 'cOp_del': 'Borrado', 'cOp_dup': 'Duplicado',
        'cOpBtn_up': 'Subir {b}', 'cOpBtn_down': 'Bajar {b}', 'cOpBtn_out': 'Sacar {b} del bloque', 'cOpBtn_in': 'Meter {b} en el bloque de arriba', 'cOpBtn_dup': 'Duplicar {b}', 'cOpBtn_del': 'Borrar {b}',
        'cBlockLabel': 'Bloque {n}: {b}. Pulsa para añadir lo siguiente después', 'cEmptyBody': 'Vacío: pulsa para añadir aquí dentro', 'cAddElse': 'Añadir «sino»',
        'cInsTopBtn': 'Añadir al principio', 'cInsTop': 'al principio del programa', 'cInsEnd': 'al final del programa', 'cInsAfter': 'después del bloque {n}', 'cInsInsideStart': 'al principio de un bloque', 'cInsAfterInside': 'dentro de un bloque, después del {n}',
        'cInsertInfo': 'Los botones «+» añaden {w}.',
        'cValue': 'valor', 'cVarName': 'nombre de la variable', 'cWhatToPrint': 'qué escribir', 'cTimes': 'veces', 'cTimesWord': 'veces', 'cCondition': 'condición',
        'cFuncName': 'nombre de la función', 'cParams': 'parámetros separados por comas', 'cArgs': 'valores separados por comas', 'cFieldError': 'Ese valor no se entiende: {m}',
        'cRunBar': 'Ejecución', 'cRun': 'Ejecutar', 'cStep': 'Paso a paso', 'cStop': 'Parar', 'cReset': 'Volver a empezar', 'cResetDone': 'Todo vuelve al inicio',
        'cSpeed': 'Velocidad', 'cSpeed_slow': 'Lenta', 'cSpeed_normal': 'Normal', 'cSpeed_fast': 'Rápida', 'cSpeed_instant': 'Al instante',
        'cRunning': 'Ejecutando', 'cStopped': 'Parado', 'cRunErr': 'Error en la línea {line}: {m}',
        'cErrNumber': 'número mal escrito', 'cErrString': 'falta cerrar las comillas', 'cErrChar': 'no se entiende el signo «{c}»', 'cErrExpected': 'falta «{x}»',
        'cErrUnexpected': 'sobra «{x}»', 'cErrNewline': 'cada orden va en su propia línea', 'cErrStmt': 'aquí debería empezar una orden', 'cErrFuncName': 'la función necesita un nombre',
        'cErrParam': 'los parámetros son nombres separados por comas', 'cErrArgs': '«{c}» necesita {n} valores', 'cErrVarName': '«{x}» no puede ser el nombre de una variable',
        'cErrUnknown': 'no conozco la orden «{x}»', 'cErrExpr': 'falta un valor o está incompleto',
        'cErrTooLong': 'el programa lleva demasiados pasos ({n}). ¿Hay un bucle que no termina?', 'cErrNoVar': 'la variable «{x}» todavía no tiene valor',
        'cErrNotNumber': 'aquí hace falta un número', 'cErrBadField': 'hay un campo con un valor que no se entiende', 'cErrSqrt': 'no hay raíz de un número negativo',
        'cErrDiv0': 'no se puede dividir entre cero', 'cErrTooMany': 'demasiadas repeticiones (más de 100.000)', 'cErrNoFunc': 'no hay ninguna función llamada «{x}»',
        'cErrCallArgs': '«{x}» necesita {n} valores', 'cErrDepth': 'la función se llama a sí misma demasiadas veces seguidas (más de {n})',
    },
    'en': {
        'cView': 'Program view', 'cBlocks': 'Blocks', 'cText': 'Text', 'cBlocksView': 'Block view', 'cTextView': 'Text view',
        'cTextLabel': 'Program as text', 'cTextHelp': 'One instruction per line. Blocks open with { and close with }. Anything after # is a comment. Words in English and in Spanish are both accepted.',
        'cApplyText': 'Use this text', 'cTextApplied': 'Text turned into blocks', 'cErrAt': 'Line {line}: {m}',
        'cGroup_move': 'Move', 'cGroup_control': 'Control', 'cGroup_data': 'Data', 'cGroup_func': 'Functions',
        'cSetVar': 'store in variable', 'cDefFunc': 'define function', 'cCallFunc': 'use function', 'cHello': 'hello', 'cFuncDefault': 'shape',
        'cInserted': 'Added: {b}', 'cInsertHere': 'The next block will be added here', 'cCannot': 'It cannot move any further that way',
        'cOp_up': 'Moved up', 'cOp_down': 'Moved down', 'cOp_out': 'Taken out of the block', 'cOp_in': 'Put into the block above', 'cOp_del': 'Deleted', 'cOp_dup': 'Duplicated',
        'cOpBtn_up': 'Move {b} up', 'cOpBtn_down': 'Move {b} down', 'cOpBtn_out': 'Take {b} out of the block', 'cOpBtn_in': 'Put {b} into the block above', 'cOpBtn_dup': 'Duplicate {b}', 'cOpBtn_del': 'Delete {b}',
        'cBlockLabel': 'Block {n}: {b}. Press to add the next one after it', 'cEmptyBody': 'Empty: press to add inside here', 'cAddElse': 'Add “else”',
        'cInsTopBtn': 'Add at the start', 'cInsTop': 'at the start of the program', 'cInsEnd': 'at the end of the program', 'cInsAfter': 'after block {n}', 'cInsInsideStart': 'at the start of a block', 'cInsAfterInside': 'inside a block, after number {n}',
        'cInsertInfo': 'The “+” buttons add {w}.',
        'cValue': 'value', 'cVarName': 'variable name', 'cWhatToPrint': 'what to print', 'cTimes': 'times', 'cTimesWord': 'times', 'cCondition': 'condition',
        'cFuncName': 'function name', 'cParams': 'parameters separated by commas', 'cArgs': 'values separated by commas', 'cFieldError': 'That value does not make sense: {m}',
        'cRunBar': 'Running', 'cRun': 'Run', 'cStep': 'Step by step', 'cStop': 'Stop', 'cReset': 'Start again', 'cResetDone': 'Everything is back at the start',
        'cSpeed': 'Speed', 'cSpeed_slow': 'Slow', 'cSpeed_normal': 'Normal', 'cSpeed_fast': 'Fast', 'cSpeed_instant': 'Instant',
        'cRunning': 'Running', 'cStopped': 'Stopped', 'cRunErr': 'Error on line {line}: {m}',
        'cErrNumber': 'badly written number', 'cErrString': 'the quotation marks are not closed', 'cErrChar': 'the sign “{c}” is not understood', 'cErrExpected': '“{x}” is missing',
        'cErrUnexpected': '“{x}” is not needed here', 'cErrNewline': 'each instruction goes on its own line', 'cErrStmt': 'an instruction should start here', 'cErrFuncName': 'the function needs a name',
        'cErrParam': 'parameters are names separated by commas', 'cErrArgs': '“{c}” needs {n} values', 'cErrVarName': '“{x}” cannot be a variable name',
        'cErrUnknown': 'I do not know the instruction “{x}”', 'cErrExpr': 'a value is missing or incomplete',
        'cErrTooLong': 'the program has taken too many steps ({n}). Is there a loop that never ends?', 'cErrNoVar': 'the variable “{x}” has no value yet',
        'cErrNotNumber': 'a number is needed here', 'cErrBadField': 'one field has a value that does not make sense', 'cErrSqrt': 'negative numbers have no square root',
        'cErrDiv0': 'you cannot divide by zero', 'cErrTooMany': 'too many repeats (over 100,000)', 'cErrNoFunc': 'there is no function called “{x}”',
        'cErrCallArgs': '“{x}” needs {n} values', 'cErrDepth': 'the function calls itself too many times in a row (over {n})',
    },
}
assert set(C['es']) == set(C['en'])

LANG_REF = {
    'es': [
        ('avanzar 100 · retroceder 50', 'moverse hacia delante o hacia atrás'),
        ('derecha 90 · izquierda 90', 'girar, en grados'),
        ('repetir 4 { … }', 'repetir lo de dentro un número de veces'),
        ('mientras x < 100 { … }', 'repetir mientras se cumpla algo'),
        ('si x > 5 { … } sino { … }', 'elegir según se cumpla algo'),
        ('x = 10 · x = x + 1', 'guardar un número o un texto en una variable'),
        ('funcion nombre(a, b) { … } · nombre(3, 50)', 'crear una orden propia y usarla'),
        ('escribir x', 'mostrar un valor en «Salida»'),
        ('y · o · no · verdadero · falso', 'combinar condiciones'),
        ('azar(1, 6) · raiz(x) · abs(x) · seno(x) · coseno(x) · redondear(x)', 'cálculos (seno y coseno en grados)'),
    ],
    'en': [
        ('forward 100 · back 50', 'move forwards or backwards'),
        ('right 90 · left 90', 'turn, in degrees'),
        ('repeat 4 { … }', 'repeat what is inside a number of times'),
        ('while x < 100 { … }', 'repeat while something is true'),
        ('if x > 5 { … } else { … }', 'choose depending on whether something is true'),
        ('x = 10 · x = x + 1', 'store a number or some text in a variable'),
        ('function name(a, b) { … } · name(3, 50)', 'make your own instruction and use it'),
        ('print x', 'show a value under “Output”'),
        ('and · or · not · true · false', 'combine conditions'),
        ('random(1, 6) · sqrt(x) · abs(x) · sin(x) · cos(x) · round(x)', 'calculations (sin and cos in degrees)'),
    ],
}
