"""Textos comunes de los estudios del Taller. Cada clave existe en los dos idiomas."""

T = {
    'es': {
        'workshop': 'El taller',
        'studioN': 'Estudio {n}',
        'whatYouGet': 'Qué tiene este estudio',
        'howTitle': 'Cómo se usa',
        'noJs': 'La herramienta necesita JavaScript. Aquí tienes todos los retos para hacerlos en papel o con otra herramienta.',
        'challengesTitle': 'Retos',
        'challengesNote': 'Elige un reto o trabaja en modo libre. Puedes cambiar de nivel cuando quieras, hacia arriba o hacia abajo. No hay tiempo límite ni puntuación.',
        'challengesNoteStatic': 'Los retos están ordenados por niveles. Puedes empezar por cualquiera.',
        'filesTitle': 'Tu trabajo y tus archivos',
        'filesText': 'Lo que haces empieza en esta pestaña. No se envía a ningún sitio. Si quieres conservarlo, puedes guardarlo explícitamente en este dispositivo o descargar tu archivo de proyecto.\n\nPara seguir otro día, pulsa «Guardar archivo»: se descarga un archivo con tu proyecto en tu dispositivo. Para retomarlo, pulsa «Abrir archivo» y elígelo. Si cierras la pestaña con cambios sin guardar, el navegador te avisa.',
        'linksTitle': 'Sigue por aquí',
        'undo': 'Deshacer', 'redo': 'Rehacer', 'new': 'Nuevo', 'open': 'Abrir archivo', 'save': 'Guardar archivo', 'print': 'Imprimir',
        'projectBar': 'Proyecto',
        'confirmNew': '¿Empezar un proyecto nuevo? Lo que no hayas guardado en un archivo se perderá.',
        'saved': 'Guardado en tu dispositivo: {name}',
        'opened': 'Proyecto abierto: {name}',
        'openBad': 'Ese archivo no es un proyecto del Taller o está dañado. No se ha cambiado nada.',
        'openOther': 'Ese archivo es de otro estudio del Taller. Ábrelo en su estudio.',
        'openTooBig': 'El archivo es demasiado grande (más de 8 MB). No se ha abierto.',
        'undone': 'Deshecho', 'redone': 'Rehecho',
        'pngSaved': 'Imagen guardada: {name}',
        'freeMode': 'Modo libre',
        'freeModeText': 'Sin reto: usa la herramienta como quieras. Puedes elegir un reto en cualquier momento sin perder lo que has hecho.',
        'free': 'Libre',
        'levelN': 'Nivel {n}',
        'limits': 'Límites del reto',
        'tip': 'Pista',
        'challengePicked': 'Reto elegido: {t}',
        'keysTitle': 'Teclado',
        'check': 'Comprobar',
        'kArrows': 'Flechas', 'kShiftArrows': 'Mayúsculas + flechas', 'kSpace': 'Espacio o Intro', 'kEsc': 'Escape', 'kUndoRedo': 'Deshacer y rehacer',
        'kTab': 'Tabulador',
        'prevChallenge': 'Reto anterior', 'nextChallenge': 'Reto siguiente', 'challengeLabel': 'Elige reto ({n} retos)',
    },
    'en': {
        'workshop': 'The workshop',
        'studioN': 'Studio {n}',
        'whatYouGet': 'What this studio has',
        'howTitle': 'How it works',
        'noJs': 'The tool needs JavaScript. Here are all the challenges so you can do them on paper or with another tool.',
        'challengesTitle': 'Challenges',
        'challengesNote': 'Pick a challenge or work in free mode. You can change level whenever you like, up or down. There is no time limit and no score.',
        'challengesNoteStatic': 'The challenges are grouped by level. You can start with any of them.',
        'filesTitle': 'Your work and your files',
        'filesText': 'What you make starts in this browser tab. It is not sent anywhere. If you want to keep it, you can explicitly save it on this device or download your project file.\n\nTo carry on another day, press “Save file”: a file with your project downloads to your device. To pick it up again, press “Open file” and choose it. If you close the tab with unsaved changes, the browser warns you.',
        'linksTitle': 'Keep going',
        'undo': 'Undo', 'redo': 'Redo', 'new': 'New', 'open': 'Open file', 'save': 'Save file', 'print': 'Print',
        'projectBar': 'Project',
        'confirmNew': 'Start a new project? Anything you have not saved to a file will be lost.',
        'saved': 'Saved to your device: {name}',
        'opened': 'Project opened: {name}',
        'openBad': 'That file is not a workshop project or it is damaged. Nothing has changed.',
        'openOther': 'That file belongs to another workshop studio. Open it in that studio.',
        'openTooBig': 'The file is too large (over 8 MB). It has not been opened.',
        'undone': 'Undone', 'redone': 'Redone',
        'pngSaved': 'Image saved: {name}',
        'freeMode': 'Free mode',
        'freeModeText': 'No challenge: use the tool however you like. You can pick a challenge at any time without losing your work.',
        'free': 'Free',
        'levelN': 'Level {n}',
        'limits': 'Challenge limits',
        'tip': 'Hint',
        'challengePicked': 'Challenge chosen: {t}',
        'keysTitle': 'Keyboard',
        'check': 'Check',
        'kArrows': 'Arrow keys', 'kShiftArrows': 'Shift + arrow keys', 'kSpace': 'Space or Enter', 'kEsc': 'Escape', 'kUndoRedo': 'Undo and redo',
        'kTab': 'Tab',
        'prevChallenge': 'Previous challenge', 'nextChallenge': 'Next challenge', 'challengeLabel': 'Choose a challenge ({n} challenges)',
    },
}

assert set(T['es']) == set(T['en'])
