"""Estudio 1 · Dibujo. Textos ES/EN y retos."""

KEY = 'dibujo'
NUMBER = 1
SLUG = {'es': 'dibujo', 'en': 'drawing'}
SCRIPTS = ['ig-taller-dibujo.js']

LEVELS = {
    1: {'es': 'Primeros trazos', 'en': 'First marks'},
    2: {'es': 'Luz y volumen', 'en': 'Light and volume'},
    3: {'es': 'Simetría y patrón', 'en': 'Symmetry and pattern'},
    4: {'es': 'Perspectiva', 'en': 'Perspective'},
    5: {'es': 'Series con reglas propias', 'en': 'Series with your own rules'},
    6: {'es': 'Sin techo', 'en': 'No ceiling'},
}

CHALLENGES = [
    {'id': 'd1', 'level': 1, 'rules': {'maxStrokes': 1, 'noErase': True},
     'es': {'title': 'Una sola línea', 'goal': 'Dibuja una cara, un animal o un objeto con un único trazo, sin levantar el lápiz.', 'limits': ['Un solo trazo', 'Sin goma'], 'tip': 'Ve despacio. Si la línea tiene que volver atrás, que vuelva por encima de sí misma.'},
     'en': {'title': 'One single line', 'goal': 'Draw a face, an animal or an object in one stroke, without lifting the pencil.', 'limits': ['One stroke only', 'No eraser'], 'tip': 'Go slowly. If the line needs to go back, let it run over itself.'}},
    {'id': 'd2', 'level': 1, 'rules': {'onlyShapes': True, 'minStrokes': 6},
     'es': {'title': 'Solo formas', 'goal': 'Dibuja un objeto de tu mesa usando solo líneas rectas, rectángulos y elipses. Al menos seis formas.', 'limits': ['Solo línea, rectángulo y elipse', 'Mínimo 6 formas'], 'tip': 'Primero la forma más grande; luego las pequeñas encima.'},
     'en': {'title': 'Shapes only', 'goal': 'Draw an object from your desk using only straight lines, rectangles and ellipses. At least six shapes.', 'limits': ['Line, rectangle and ellipse only', 'At least 6 shapes'], 'tip': 'Start with the biggest shape, then add the small ones on top.'}},
    {'id': 'd3', 'level': 1, 'rules': {'maxColors': 3, 'minStrokes': 10},
     'es': {'title': 'Tres colores', 'goal': 'Un paisaje con solo tres colores. Elige bien cuáles antes de empezar.', 'limits': ['Máximo 3 colores', 'Mínimo 10 trazos'], 'tip': 'Un color claro, uno medio y uno oscuro dan mucho juego.'},
     'en': {'title': 'Three colours', 'goal': 'A landscape using only three colours. Choose them carefully before you start.', 'limits': ['3 colours at most', 'At least 10 strokes'], 'tip': 'A light, a middle and a dark colour go a long way.'}},
    {'id': 'd4', 'level': 2, 'rules': {'exactColors': 3, 'sameHue': True, 'minStrokes': 8},
     'es': {'title': 'Luz con tres tonos', 'goal': 'Una esfera o una taza con luz: un tono claro, uno medio y uno oscuro del mismo color.', 'limits': ['Exactamente 3 colores', 'Los tres del mismo tono, de claro a oscuro'], 'tip': 'Decide de dónde viene la luz. El lado contrario va con el tono oscuro.'},
     'en': {'title': 'Light in three values', 'goal': 'A sphere or a mug with light on it: one light, one middle and one dark value of the same colour.', 'limits': ['Exactly 3 colours', 'All three the same hue, from light to dark'], 'tip': 'Decide where the light comes from. The opposite side takes the dark value.'}},
    {'id': 'd5', 'level': 2, 'rules': {'minLayers': 3, 'minStrokes': 12},
     'es': {'title': 'Tres planos', 'goal': 'Una escena con fondo, plano medio y primer plano, cada uno en su propia capa.', 'limits': ['Al menos 3 capas con dibujo'], 'tip': 'Lo lejano, más claro y con menos detalle.'},
     'en': {'title': 'Three planes', 'goal': 'A scene with background, middle ground and foreground, each on its own layer.', 'limits': ['At least 3 layers with drawing'], 'tip': 'Things far away are lighter and less detailed.'}},
    {'id': 'd6', 'level': 2, 'rules': {'minStrokes': 15, 'alt': True},
     'es': {'title': 'Sombra proyectada', 'goal': 'Un objeto y la sombra que deja en el suelo con la luz a un lado. Escribe en el texto alternativo de dónde viene la luz.', 'limits': ['Mínimo 15 trazos', 'Texto alternativo escrito'], 'tip': 'La sombra sale del objeto hacia el lado contrario a la luz.'},
     'en': {'title': 'Cast shadow', 'goal': 'An object and the shadow it casts on the floor, with the light to one side. Write in the alt text where the light comes from.', 'limits': ['At least 15 strokes', 'Alt text written'], 'tip': 'The shadow stretches away from the light.'}},
    {'id': 'd7', 'level': 3, 'rules': {'sym': ['v', 'vh'], 'symStrokes': 6}, 'setup': {'sym': 'v'},
     'es': {'title': 'Mariposa simétrica', 'goal': 'Una mariposa, una máscara o un escarabajo con simetría de espejo.', 'limits': ['Al menos 6 trazos con simetría vertical'], 'tip': 'Dibuja solo un lado: el otro sale solo.'},
     'en': {'title': 'Symmetrical butterfly', 'goal': 'A butterfly, a mask or a beetle with mirror symmetry.', 'limits': ['At least 6 strokes with vertical symmetry'], 'tip': 'Draw one side only: the other appears by itself.'}},
    {'id': 'd8', 'level': 3, 'rules': {'sym': ['radial'], 'symN': 8, 'symStrokes': 10}, 'setup': {'sym': 'radial', 'symN': 8},
     'es': {'title': 'Mandala de ocho', 'goal': 'Un mandala con simetría radial de 8 partes, de dentro hacia fuera.', 'limits': ['Simetría radial de 8', 'Al menos 10 trazos'], 'tip': 'Anillos: cada vuelta un poco más lejos del centro.'},
     'en': {'title': 'Eight-fold mandala', 'goal': 'A mandala with 8-part radial symmetry, from the centre outwards.', 'limits': ['8-part radial symmetry', 'At least 10 strokes'], 'tip': 'Rings: each round a little further from the centre.'}},
    {'id': 'd9', 'level': 3, 'rules': {'sym': ['kaleido'], 'symN': 6, 'symStrokes': 10, 'maxColors': 4}, 'setup': {'sym': 'kaleido', 'symN': 6},
     'es': {'title': 'Caleidoscopio', 'goal': 'Un caleidoscopio de 6 espejos con cuatro colores como máximo.', 'limits': ['Caleidoscopio de 6', 'Máximo 4 colores', 'Mínimo 10 trazos'], 'tip': 'Los trazos cortos cerca del centro dan estrellas.'},
     'en': {'title': 'Kaleidoscope', 'goal': 'A 6-mirror kaleidoscope with four colours at most.', 'limits': ['6-mirror kaleidoscope', '4 colours at most', 'At least 10 strokes'], 'tip': 'Short strokes near the centre make stars.'}},
    {'id': 'd10', 'level': 4, 'rules': {'snapVp': 6, 'vps': 1}, 'setup': {'guide': 'p1', 'tool': 'linea'},
     'es': {'title': 'Un punto de fuga', 'goal': 'Un pasillo, una carretera o una vía de tren que se aleja hacia un único punto.', 'limits': ['Al menos 6 líneas ajustadas al punto de fuga'], 'tip': 'Todas las líneas que se alejan van al punto rosa. Las verticales siguen verticales.'},
     'en': {'title': 'One vanishing point', 'goal': 'A corridor, a road or a railway track heading away towards a single point.', 'limits': ['At least 6 lines snapped to the vanishing point'], 'tip': 'Every line going into the distance heads for the pink point. Verticals stay vertical.'}},
    {'id': 'd11', 'level': 4, 'rules': {'snapVp': 10, 'vps': 2}, 'setup': {'guide': 'p2', 'tool': 'linea'},
     'es': {'title': 'Dos puntos de fuga', 'goal': 'Una caja o la esquina de un edificio vista de frente a la arista, con dos puntos de fuga.', 'limits': ['Al menos 10 líneas ajustadas', 'Usa los dos puntos de fuga'], 'tip': 'Empieza por la arista vertical más cercana y lleva sus extremos a cada punto.'},
     'en': {'title': 'Two vanishing points', 'goal': 'A box or the corner of a building seen edge-on, with two vanishing points.', 'limits': ['At least 10 snapped lines', 'Use both vanishing points'], 'tip': 'Start with the nearest vertical edge and take its ends to each point.'}},
    {'id': 'd12', 'level': 4, 'rules': {'snapVp': 24, 'vps': 2, 'minLayers': 2}, 'setup': {'guide': 'p2', 'tool': 'linea'},
     'es': {'title': 'Tres edificios', 'goal': 'Una calle con tres edificios en perspectiva de dos puntos y el horizonte bajo, como vista desde el suelo.', 'limits': ['Al menos 24 líneas ajustadas', 'Dos puntos de fuga', 'Al menos 2 capas'], 'tip': 'Baja el horizonte en «Altura del horizonte»: los edificios parecerán más altos.'},
     'en': {'title': 'Three buildings', 'goal': 'A street with three buildings in two-point perspective and a low horizon, as if seen from the ground.', 'limits': ['At least 24 snapped lines', 'Two vanishing points', 'At least 2 layers'], 'tip': 'Lower the horizon with “Horizon height”: the buildings will look taller.'}},
    {'id': 'd13', 'level': 5, 'rules': {'minSheets': 4},
     'es': {'title': 'La misma cosa, cuatro luces', 'goal': 'El mismo objeto en cuatro hojas: luz de la mañana, del mediodía, de la tarde y de la noche.', 'limits': ['4 hojas con dibujo'], 'tip': 'Usa «Duplicar hoja» para partir del mismo contorno.'},
     'en': {'title': 'The same thing, four lights', 'goal': 'The same object on four sheets: morning, midday, evening and night light.', 'limits': ['4 sheets with drawing'], 'tip': 'Use “Duplicate sheet” to start from the same outline.'}},
    {'id': 'd14', 'level': 5, 'rules': {'minSheets': 10, 'rules': 3},
     'es': {'title': 'Serie de diez con reglas propias', 'goal': 'Escribe tres reglas tuyas en «Mis reglas» y haz una serie de diez hojas que las cumpla.', 'limits': ['3 reglas escritas', '10 hojas con dibujo'], 'tip': 'Reglas que funcionan: un color por hoja, siempre el mismo encuadre, cada hoja un trazo más.'},
     'en': {'title': 'A series of ten with your own rules', 'goal': 'Write three rules of your own in “My rules” and make a series of ten sheets that follows them.', 'limits': ['3 rules written', '10 sheets with drawing'], 'tip': 'Rules that work: one colour per sheet, always the same framing, one more stroke on each sheet.'}},
    {'id': 'd15', 'level': 6, 'gen': True, 'rules': {},
     'es': {'title': 'Reto combinado', 'goal': 'Un tema, un límite y una técnica al azar. Pulsa «Otro reto» cuantas veces quieras: no se acaban.', 'limits': [], 'tip': 'Si una combinación no te dice nada, pide otra.'},
     'en': {'title': 'Combined challenge', 'goal': 'A random subject, limit and technique. Press “Another challenge” as often as you like: they never run out.', 'limits': [], 'tip': 'If a combination does nothing for you, ask for another.'}},
]

STRINGS = {
    'es': {
        'dLayerBg': 'Fondo', 'dLayerN': 'Capa {n}', 'dExportPng': 'Guardar PNG', 'dNewDone': 'Lienzo nuevo',
        'dCanvasRole': 'lienzo de dibujo',
        'dKeyHint': 'Con teclado: entra en el lienzo con el tabulador, mueve el cursor con las flechas y pulsa Espacio para bajar y subir la pluma.',
        'dSheets': 'Hojas', 'dKArrows': 'Mueven el cursor 12 píxeles', 'dKShiftArrows': 'Mueven el cursor 2 píxeles', 'dKSpace': 'Baja o sube la pluma; en las formas, marca el primer y el último punto',
        'dKEsc': 'Cancela el trazo en curso', 'dKTools': 'Eligen herramienta: lápiz, tinta, rotulador, pincel suave, goma, línea, rectángulo, elipse', 'dKSize': 'Tamaño más pequeño o más grande',
        'dTools': 'Herramientas',
        'dTool_lapiz': 'Lápiz', 'dTool_tinta': 'Tinta', 'dTool_rotulador': 'Rotulador', 'dTool_suave': 'Pincel suave', 'dTool_goma': 'Goma',
        'dTool_linea': 'Línea recta', 'dTool_rect': 'Rectángulo', 'dTool_elipse': 'Elipse',
        'dSize': 'Tamaño', 'dOpacity': 'Opacidad', 'dFill': 'Rellenar rectángulos y elipses',
        'dColor': 'Color', 'dPalette': 'Paleta', 'dCustomColor': 'Otro color',
        'dSym_no': 'Sin simetría', 'dSym_v': 'Espejo vertical', 'dSym_h': 'Espejo horizontal', 'dSym_vh': 'Cuatro espejos', 'dSym_radial': 'Radial', 'dSym_kaleido': 'Caleidoscopio',
        'dGuide_no': 'Sin guía', 'dGuide_grid': 'Cuadrícula', 'dGuide_p1': 'Perspectiva de un punto', 'dGuide_p2': 'Perspectiva de dos puntos',
        'dSymGuides': 'Simetría y guías', 'dSym': 'Simetría', 'dSymN': 'Número de partes (3 a 16)', 'dGuide': 'Guía', 'dGrid': 'Tamaño de la cuadrícula',
        'dHorizon': 'Altura del horizonte', 'dVp1': 'Punto de fuga 1 (izquierda o centro)', 'dVp2': 'Punto de fuga 2 (derecha)', 'dSnap': 'Ajustar líneas a la guía',
        'dGuideNote': 'Las guías no se imprimen ni se guardan en el PNG. Con «Ajustar», la línea recta va sola hacia el punto de fuga, en horizontal o en vertical.',
        'dLayers': 'Capas', 'dAddLayer': 'Añadir capa', 'dDelLayer': 'Borrar capa',
        'dProject': 'Proyecto', 'dTitle': 'Título', 'dFormat': 'Formato', 'dFormat_horizontal': 'Horizontal (3:2)', 'dFormat_vertical': 'Vertical (2:3)', 'dFormat_cuadrado': 'Cuadrado',
        'dAltLabel': 'Descripción de esta hoja (texto alternativo)', 'dAltHelp': 'Cuenta en una o dos frases qué se ve. Sirve a quien no puede ver la imagen y acompaña al dibujo al imprimir.',
        'dRulesLabel': 'Mis reglas (una por línea)',
        'dFormatConfirm': 'Al cambiar el formato, los trazos se quedan donde están y pueden quedar fuera del lienzo. ¿Cambiar?',
        'dToolPicked': 'Herramienta: {t}', 'dColorPicked': 'Color: {c}',
        'dColorNames': 'negro|gris|gris claro|blanco|granate|rojo|naranja|amarillo|verde oliva|verde|verde azulado|azul|azul marino|violeta|rosa oscuro|marrón',
        'dHueNames': 'rojo|naranja|verde amarillento|verde|turquesa|azul|violeta|rosa|blanco|negro|gris', 'dLight': 'claro', 'dDark': 'oscuro',
        'dLimShapes': 'Este reto es solo con línea recta, rectángulo y elipse.', 'dLimNoErase': 'Este reto es sin goma.',
        'dLimStrokes': 'Este reto permite {n} trazo. Deshaz el último si quieres repetirlo.', 'dLimColors': 'Este reto permite {n} colores y ya los has usado. Elige uno de los que ya están en el dibujo.',
        'dHiddenLayer': 'La capa elegida está oculta. Hazla visible o elige otra para dibujar.',
        'dPos': 'Cursor en x {x}, y {y} · {pen}', 'dPenDown': 'pluma bajada', 'dPenUp': 'pluma subida', 'dPenUpSaved': 'Pluma subida, trazo guardado',
        'dShapeStart': 'Primer punto marcado. Mueve el cursor y pulsa Espacio para terminar.', 'dShapeDone': 'Forma guardada', 'dCancelled': 'Trazo cancelado',
        'dLayerName': 'Nombre de la capa {n}', 'dVisible': 'Visible', 'dLayerOpacity': 'Opacidad de {name}', 'dLayerActive': 'En uso', 'dLayerUse': 'Usar',
        'dLayerNow': 'Dibujas en la capa {name}', 'dLayerUp': 'Subir {name}', 'dLayerDown': 'Bajar {name}', 'dStrokesN': '{n} trazos',
        'dMaxLayers': 'Máximo {n} capas por hoja', 'dLayerAdded': 'Capa añadida', 'dLastLayer': 'Cada hoja necesita al menos una capa',
        'dDelLayerConfirm': '¿Borrar la capa «{name}» y todo lo que tiene? Puedes deshacerlo.', 'dLayerDeleted': 'Capa borrada', 'dLayerMoved': 'Capa movida',
        'dSheetOf': 'Hoja {n} de {m}', 'dPrevSheet': 'Hoja anterior', 'dNextSheet': 'Hoja siguiente', 'dAddSheet': 'Hoja nueva', 'dDupSheet': 'Duplicar hoja', 'dDelSheet': 'Borrar hoja',
        'dMaxSheets': 'Máximo {n} hojas por proyecto', 'dDelSheetConfirm': '¿Borrar la hoja {n}? Puedes deshacerlo.',
        'dAltTitle': 'Qué hay en el lienzo', 'dAltEmpty': 'Todavía no has escrito una descripción de esta hoja.',
        'dAltAuto': 'Hoja {sheet} de {sheets}. {strokes} trazos en {layers} de {total} capas. Colores: {colors}. Herramientas: {tools}. Simetría: {sym}.',
        'dUntitled': 'Sin título', 'dColorsUsed': 'Colores usados en esta hoja: {n}',
        'dChkMinStrokes': 'Trazos: {n} (mínimo {m})', 'dChkMaxStrokes': 'Trazos: {n} (máximo {m})', 'dChkColors': 'Colores: {n} (máximo {m})', 'dChkExactColors': 'Colores: {n} (hacen falta {m})',
        'dChkHue': 'Los colores son del mismo tono y van de claro a oscuro (diferencia de luz: {spread} %; hace falta 25 % o más)',
        'dChkShapes': 'Solo líneas rectas, rectángulos y elipses', 'dChkLayers': 'Capas con dibujo: {n} (mínimo {m})',
        'dChkSym': 'Trazos con {sym}: {n} (mínimo {m})', 'dChkVp': 'Líneas ajustadas a los puntos de fuga: {n} (mínimo {m})', 'dChkVps': 'Puntos de fuga usados: {n} de {m}',
        'dChkSheets': 'Hojas con dibujo: {n} (mínimo {m})', 'dChkRules': 'Reglas escritas: {n} (mínimo {m})', 'dChkAlt': 'Descripción escrita',
        'dGenPools': 'un faro|tu calle de noche|una planta de interior|un tren que llega|una ciudad bajo el agua|tu mochila por dentro|un mercado|un robot jardinero|una tormenta vista desde la ventana|el esqueleto de un pez|una estación espacial|un árbol en cuatro estaciones||solo con tres colores|con una sola línea|sin goma|con simetría radial|en tres capas|solo con formas|con el horizonte muy bajo|con dos puntos de fuga|con la mano que no usas (con ratón o dedo)|sin usar el negro||con luz de un solo lado|con mucho detalle en un rincón y nada en el resto|como un plano visto desde arriba|como un cartel|en una tira de cuatro hojas|como si fuera de noche|con trazos muy cortos|en tamaño enorme, que se salga del lienzo',
        'dGenOut': 'Dibuja {a}, {b}, {c}.', 'dGenBtn': 'Otro reto',
        'dCheckAllOk': 'Reto cumplido. Puedes seguir, guardar el PNG o pasar a otro.', 'dCheckSome': 'Así va el reto. Sigue cuando quieras: no hay prisa.',
        'dSetup': 'Preparar la herramienta', 'dSetupDone': 'Herramienta preparada para el reto', 'dMadeIn': 'hecho en el Taller',
    },
    'en': {
        'dLayerBg': 'Background', 'dLayerN': 'Layer {n}', 'dExportPng': 'Save PNG', 'dNewDone': 'New canvas',
        'dCanvasRole': 'drawing canvas',
        'dKeyHint': 'With a keyboard: tab into the canvas, move the cursor with the arrow keys and press Space to put the pen down and lift it.',
        'dSheets': 'Sheets', 'dKArrows': 'Move the cursor 12 pixels', 'dKShiftArrows': 'Move the cursor 2 pixels', 'dKSpace': 'Puts the pen down or lifts it; with shapes, marks the first and last point',
        'dKEsc': 'Cancels the stroke in progress', 'dKTools': 'Choose a tool: pencil, ink, marker, soft brush, eraser, line, rectangle, ellipse', 'dKSize': 'Smaller or bigger size',
        'dTools': 'Tools',
        'dTool_lapiz': 'Pencil', 'dTool_tinta': 'Ink', 'dTool_rotulador': 'Marker', 'dTool_suave': 'Soft brush', 'dTool_goma': 'Eraser',
        'dTool_linea': 'Straight line', 'dTool_rect': 'Rectangle', 'dTool_elipse': 'Ellipse',
        'dSize': 'Size', 'dOpacity': 'Opacity', 'dFill': 'Fill rectangles and ellipses',
        'dColor': 'Colour', 'dPalette': 'Palette', 'dCustomColor': 'Another colour',
        'dSym_no': 'No symmetry', 'dSym_v': 'Vertical mirror', 'dSym_h': 'Horizontal mirror', 'dSym_vh': 'Four mirrors', 'dSym_radial': 'Radial', 'dSym_kaleido': 'Kaleidoscope',
        'dGuide_no': 'No guide', 'dGuide_grid': 'Grid', 'dGuide_p1': 'One-point perspective', 'dGuide_p2': 'Two-point perspective',
        'dSymGuides': 'Symmetry and guides', 'dSym': 'Symmetry', 'dSymN': 'Number of parts (3 to 16)', 'dGuide': 'Guide', 'dGrid': 'Grid size',
        'dHorizon': 'Horizon height', 'dVp1': 'Vanishing point 1 (left or centre)', 'dVp2': 'Vanishing point 2 (right)', 'dSnap': 'Snap lines to the guide',
        'dGuideNote': 'Guides are not printed or saved in the PNG. With “Snap”, the straight line heads for the vanishing point, or runs horizontally or vertically, on its own.',
        'dLayers': 'Layers', 'dAddLayer': 'Add layer', 'dDelLayer': 'Delete layer',
        'dProject': 'Project', 'dTitle': 'Title', 'dFormat': 'Format', 'dFormat_horizontal': 'Landscape (3:2)', 'dFormat_vertical': 'Portrait (2:3)', 'dFormat_cuadrado': 'Square',
        'dAltLabel': 'Description of this sheet (alt text)', 'dAltHelp': 'Say in one or two sentences what can be seen. It helps anyone who cannot see the image and goes with the drawing when you print.',
        'dRulesLabel': 'My rules (one per line)',
        'dFormatConfirm': 'If you change the format, strokes stay where they are and may end up outside the canvas. Change it?',
        'dToolPicked': 'Tool: {t}', 'dColorPicked': 'Colour: {c}',
        'dColorNames': 'black|grey|light grey|white|maroon|red|orange|yellow|olive green|green|teal|blue|navy|violet|dark pink|brown',
        'dHueNames': 'red|orange|yellow-green|green|turquoise|blue|violet|pink|white|black|grey', 'dLight': 'light', 'dDark': 'dark',
        'dLimShapes': 'This challenge uses the straight line, rectangle and ellipse only.', 'dLimNoErase': 'This challenge has no eraser.',
        'dLimStrokes': 'This challenge allows {n} stroke. Undo the last one if you want another go.', 'dLimColors': 'This challenge allows {n} colours and you have used them all. Pick one that is already in the drawing.',
        'dHiddenLayer': 'The chosen layer is hidden. Make it visible or pick another one to draw on.',
        'dPos': 'Cursor at x {x}, y {y} · {pen}', 'dPenDown': 'pen down', 'dPenUp': 'pen up', 'dPenUpSaved': 'Pen up, stroke saved',
        'dShapeStart': 'First point marked. Move the cursor and press Space to finish.', 'dShapeDone': 'Shape saved', 'dCancelled': 'Stroke cancelled',
        'dLayerName': 'Name of layer {n}', 'dVisible': 'Visible', 'dLayerOpacity': 'Opacity of {name}', 'dLayerActive': 'In use', 'dLayerUse': 'Use',
        'dLayerNow': 'You are drawing on layer {name}', 'dLayerUp': 'Move {name} up', 'dLayerDown': 'Move {name} down', 'dStrokesN': '{n} strokes',
        'dMaxLayers': '{n} layers per sheet at most', 'dLayerAdded': 'Layer added', 'dLastLayer': 'Each sheet needs at least one layer',
        'dDelLayerConfirm': 'Delete the layer “{name}” and everything on it? You can undo this.', 'dLayerDeleted': 'Layer deleted', 'dLayerMoved': 'Layer moved',
        'dSheetOf': 'Sheet {n} of {m}', 'dPrevSheet': 'Previous sheet', 'dNextSheet': 'Next sheet', 'dAddSheet': 'New sheet', 'dDupSheet': 'Duplicate sheet', 'dDelSheet': 'Delete sheet',
        'dMaxSheets': '{n} sheets per project at most', 'dDelSheetConfirm': 'Delete sheet {n}? You can undo this.',
        'dAltTitle': 'What is on the canvas', 'dAltEmpty': 'You have not written a description of this sheet yet.',
        'dAltAuto': 'Sheet {sheet} of {sheets}. {strokes} strokes on {layers} of {total} layers. Colours: {colors}. Tools: {tools}. Symmetry: {sym}.',
        'dUntitled': 'Untitled', 'dColorsUsed': 'Colours used on this sheet: {n}',
        'dChkMinStrokes': 'Strokes: {n} (at least {m})', 'dChkMaxStrokes': 'Strokes: {n} (at most {m})', 'dChkColors': 'Colours: {n} (at most {m})', 'dChkExactColors': 'Colours: {n} ({m} needed)',
        'dChkHue': 'The colours share one hue and go from light to dark (difference in lightness: {spread}%; 25% or more needed)',
        'dChkShapes': 'Straight lines, rectangles and ellipses only', 'dChkLayers': 'Layers with drawing: {n} (at least {m})',
        'dChkSym': 'Strokes with {sym}: {n} (at least {m})', 'dChkVp': 'Lines snapped to vanishing points: {n} (at least {m})', 'dChkVps': 'Vanishing points used: {n} of {m}',
        'dChkSheets': 'Sheets with drawing: {n} (at least {m})', 'dChkRules': 'Rules written: {n} (at least {m})', 'dChkAlt': 'Description written',
        'dGenPools': 'a lighthouse|your street at night|a house plant|a train pulling in|a city under water|the inside of your bag|a market|a gardening robot|a storm seen from the window|a fish skeleton|a space station|a tree in four seasons||with only three colours|with one single line|with no eraser|with radial symmetry|on three layers|with shapes only|with a very low horizon|with two vanishing points|with your other hand (mouse or finger)|without using black||with light from one side only|with lots of detail in one corner and none elsewhere|as a plan seen from above|as a poster|as a strip of four sheets|as if it were night|with very short strokes|huge, spilling off the canvas',
        'dGenOut': 'Draw {a}, {b}, {c}.', 'dGenBtn': 'Another challenge',
        'dCheckAllOk': 'Challenge done. You can carry on, save the PNG or move to another one.', 'dCheckSome': 'Here is how the challenge is going. Carry on whenever you like: there is no rush.',
        'dSetup': 'Set up the tool', 'dSetupDone': 'Tool set up for the challenge', 'dMadeIn': 'made in the Workshop',
    },
}
assert set(STRINGS['es']) == set(STRINGS['en'])

PAGE = {
    'es': {
        'title': 'Estudio de dibujo',
        'description': 'Lienzo con capas, pinceles, goma, simetría y guías de perspectiva. Retos por niveles sin techo, modo libre, deshacer sin límite y proyectos en tu propio archivo.',
        'lede': 'Un lienzo de verdad: capas, pinceles, goma, simetría y guías de perspectiva. Dibuja libre o sigue retos que suben de nivel sin techo.',
        'pills': ['8 herramientas', 'Capas', 'Simetría y caleidoscopio', 'Perspectiva de 1 y 2 puntos', 'Series de hojas', '15 retos en 6 niveles', 'Ratón, dedo, lápiz o teclado'],
        'steps': [
            'Elige un reto o quédate en modo libre.',
            'Dibuja con el ratón, el dedo, un lápiz digital o el teclado.',
            'Usa capas para separar partes: fondo, figura, detalles. Puedes ocultarlas, moverlas y cambiar su opacidad.',
            'Activa la simetría o una guía de perspectiva cuando la necesites.',
            'Pulsa «Comprobar» para ver cómo va el reto. Guarda el PNG, imprime o guarda el proyecto para seguir otro día.',
        ],
        'sections': [
            {'h': 'Para qué sirve cada cosa', 'p': 'Las capas son hojas transparentes una encima de otra: lo que borras en una no toca las demás. La simetría repite cada trazo en espejo o alrededor del centro. La perspectiva hace que las líneas que se alejan vayan a un punto del horizonte, como en una foto de una calle.\n\nLas hojas sirven para series: el mismo dibujo con otra luz, una historia en viñetas o diez variaciones de una idea.'},
        ],
        'links': [('Tus intereses: Cielo nocturno, para dibujar tu constelación', '/es/intereses/cielo/'), ('Estudio de ideas e inventos', '/es/taller/ideas/'), ('Las hojas para imprimir del Taller', '/es/taller/hojas/'), ('Volver al Taller', '/es/taller/')],
        'credits': 'Estudio de dibujo de Iris Green. Lo que dibujas es tuyo. Las imágenes exportadas llevan una franja con IRIS GREEN · irisgreen.eu fuera del dibujo.',
    },
    'en': {
        'title': 'Drawing studio',
        'description': 'A canvas with layers, brushes, eraser, symmetry and perspective guides. Levelled challenges with no ceiling, free mode, unlimited undo and projects in your own file.',
        'lede': 'A real canvas: layers, brushes, eraser, symmetry and perspective guides. Draw freely or follow challenges that go up in level with no ceiling.',
        'pills': ['8 tools', 'Layers', 'Symmetry and kaleidoscope', '1- and 2-point perspective', 'Series of sheets', '15 challenges on 6 levels', 'Mouse, finger, stylus or keyboard'],
        'steps': [
            'Pick a challenge or stay in free mode.',
            'Draw with a mouse, your finger, a stylus or the keyboard.',
            'Use layers to keep parts apart: background, figure, details. You can hide them, move them and change their opacity.',
            'Turn on symmetry or a perspective guide when you need it.',
            'Press “Check” to see how the challenge is going. Save a PNG, print, or save the project to carry on another day.',
        ],
        'sections': [
            {'h': 'What each thing is for', 'p': 'Layers are transparent sheets stacked on top of each other: what you erase on one does not touch the others. Symmetry repeats every stroke as a mirror image or around the centre. Perspective makes lines that go into the distance meet at a point on the horizon, like in a photo of a street.\n\nSheets are for series: the same drawing in different light, a story in panels or ten variations on one idea.'},
        ],
        'links': [('Your interests: Night sky, to draw your constellation', '/en/interests/night-sky/'), ('Ideas and inventions studio', '/en/workshop/ideas/'), ('The workshop printable sheets', '/en/workshop/sheets/'), ('Back to the workshop', '/en/workshop/')],
        'credits': 'Iris Green drawing studio. What you draw is yours. Exported images carry a strip with IRIS GREEN · irisgreen.eu outside the drawing.',
    },
}
