"""Estudio 2 · Diseño gráfico y tipografía. Textos ES/EN y retos."""

KEY = 'diseno'
NUMBER = 2
SLUG = {'es': 'diseno-grafico', 'en': 'graphic-design'}
SCRIPTS = ['ig-taller-diseno-calc.js', 'ig-taller-diseno.js']

LEVELS = {
    1: {'es': 'Formas y letras', 'en': 'Shapes and letters'},
    2: {'es': 'Que se lea bien', 'en': 'Easy to read'},
    3: {'es': 'Composición', 'en': 'Layout'},
    4: {'es': 'Sistemas y señales', 'en': 'Systems and signs'},
    5: {'es': 'Sin techo', 'en': 'No ceiling'},
}


def _preset(title, date, info):
    return {'format': 'cartel', 'bg': '#ffffff', 'els': [
        {'type': 'rect', 'x': 0, 'y': 0, 'w': 420, 'h': 200, 'fill': '#f2c230', 'r': 0},
        {'type': 'text', 'x': 30, 'y': 76, 'w': 0, 'h': 0, 'text': title, 'size': 40, 'font': 'atkinson', 'weight': 700, 'align': 'left', 'fill': '#ffffff'},
        {'type': 'text', 'x': 30, 'y': 240, 'w': 0, 'h': 0, 'text': date, 'size': 22, 'font': 'atkinson', 'weight': 400, 'align': 'left', 'fill': '#c8ccd2'},
        {'type': 'rect', 'x': 0, 'y': 440, 'w': 420, 'h': 154, 'fill': '#1b1f24', 'r': 0},
        {'type': 'text', 'x': 30, 'y': 500, 'w': 0, 'h': 0, 'text': info, 'size': 18, 'font': 'atkinson', 'weight': 400, 'align': 'left', 'fill': '#17395c'},
    ]}


CHALLENGES = [
    {'id': 'd1', 'level': 1, 'rules': {'format': 'logo', 'maxShapes': 1, 'minTexts': 1, 'contrast': 'AA'},
     'es': {'title': 'Un logo con una sola forma', 'goal': 'Diseña un logo en formato cuadrado con una sola forma y un nombre. Que el nombre se lea bien.', 'limits': ['Formato logo', 'Una sola forma', 'Al menos un texto', 'Contraste AA en los textos'], 'tip': 'Una forma sencilla se recuerda mejor. Prueba un círculo o una estrella y el nombre dentro o debajo.'},
     'en': {'title': 'A logo with one shape', 'goal': 'Design a square logo with a single shape and a name. The name must be easy to read.', 'limits': ['Logo format', 'Only one shape', 'At least one text', 'AA contrast on texts'], 'tip': 'A simple shape is easier to remember. Try a circle or a star, with the name inside or below.'}},
    {'id': 'd2', 'level': 1, 'rules': {'format': 'cartel', 'maxColours': 2, 'minTexts': 1, 'bigText': 48, 'contrast': 'AA'},
     'es': {'title': 'Cartel de dos colores', 'goal': 'Un cartel con solo dos colores (el fondo cuenta) y un título grande.', 'limits': ['Formato cartel', 'Dos colores como mucho', 'Un texto de 48 o más', 'Contraste AA'], 'tip': 'Con dos colores, uno oscuro y otro claro funcionan casi siempre.'},
     'en': {'title': 'Two-colour poster', 'goal': 'A poster with only two colours (the background counts) and a big title.', 'limits': ['Poster format', 'Two colours at most', 'A text of size 48 or more', 'AA contrast'], 'tip': 'With two colours, one dark and one light almost always work.'}},
    {'id': 'd3', 'level': 2, 'rules': {'minTexts': 3, 'contrast': 'AA'},
     'es': {'title': 'Arregla el contraste', 'goal': 'Este cartel no se lee bien. Cambia colores hasta que los tres textos pasen el nivel AA de contraste.', 'limits': ['Los tres textos siguen ahí', 'Contraste AA en todos'], 'tip': 'Mira la tabla de capas: dice el contraste de cada texto. Puedes cambiar el color del texto o el de la forma que tiene detrás.',
            'preset': _preset('Taller de verano', 'Del 1 al 15 de julio', 'Inscripción gratis en la biblioteca')},
     'en': {'title': 'Fix the contrast', 'goal': 'This poster is hard to read. Change colours until all three texts pass AA contrast.', 'limits': ['The three texts are still there', 'AA contrast on all of them'], 'tip': 'Look at the layers table: it shows the contrast of each text. You can change the text colour or the colour of the shape behind it.',
            'preset': _preset('Summer workshop', '1 to 15 July', 'Free sign-up at the library')}},
    {'id': 'd4', 'level': 2, 'rules': {'minTexts': 3, 'hierarchy': 2, 'minSize': 14, 'contrast': 'AA'},
     'es': {'title': 'Lo importante, primero', 'goal': 'Tres textos con jerarquía: el más grande mide al menos el doble que el más pequeño, y ninguno baja de 14.', 'limits': ['3 textos', 'El mayor, el doble del menor', 'Ninguno por debajo de 14', 'Contraste AA'], 'tip': 'Título, subtítulo y detalle. El tamaño y el peso (normal o negrita) dicen qué se lee antes.'},
     'en': {'title': 'Important things first', 'goal': 'Three texts with hierarchy: the biggest is at least twice the smallest, and none is below 14.', 'limits': ['3 texts', 'Biggest twice the smallest', 'None below 14', 'AA contrast'], 'tip': 'Title, subtitle and detail. Size and weight (regular or bold) tell people what to read first.'}},
    {'id': 'd5', 'level': 3, 'rules': {'minTexts': 3, 'aligned': True, 'minShapes': 1, 'contrast': 'AA'},
     'es': {'title': 'Todo en línea', 'goal': 'Tres textos o más alineados por el mismo borde (izquierdo, centro o derecho) y al menos una forma.', 'limits': ['3 textos alineados', 'Al menos una forma', 'Contraste AA'], 'tip': 'Elige un texto y usa «Alinear»; o escribe la misma X en todos. Los textos centrados se alinean por su centro.'},
     'en': {'title': 'All in line', 'goal': 'Three or more texts aligned on the same edge (left, centre or right) and at least one shape.', 'limits': ['3 aligned texts', 'At least one shape', 'AA contrast'], 'tip': 'Select a text and use “Align”; or type the same X for all of them. Centred texts line up by their centre.'}},
    {'id': 'd6', 'level': 3, 'rules': {'format': 'tarjeta', 'minTexts': 3, 'minSize': 10, 'maxColours': 3, 'contrast': 'AA'},
     'es': {'title': 'Tarjeta de visita', 'goal': 'Una tarjeta con nombre, oficio y una forma de contacto, con tres colores como mucho.', 'limits': ['Formato tarjeta', '3 textos', 'Ninguno por debajo de 10', '3 colores como mucho', 'Contraste AA'], 'tip': 'En poco espacio, deja aire alrededor. Mejor pocas cosas y grandes.'},
     'en': {'title': 'Business card', 'goal': 'A card with a name, a job and a way to get in touch, with three colours at most.', 'limits': ['Card format', '3 texts', 'None below 10', '3 colours at most', 'AA contrast'], 'tip': 'In a small space, leave room around things. Better a few big things.'}},
    {'id': 'd7', 'level': 4, 'rules': {'format': 'senal', 'needArrow': True, 'bigText': 60, 'contrast': 'AAA'},
     'es': {'title': 'Señal de edificio', 'goal': 'Una señal que indica un sitio (por ejemplo, la biblioteca) con una flecha y un texto grande que se lea de lejos.', 'limits': ['Formato señal', 'Una flecha', 'Un texto de 60 o más', 'Contraste AAA'], 'tip': 'Las señales se leen de lejos y deprisa: letra sin adornos, mucho contraste y pocas palabras.'},
     'en': {'title': 'Building sign', 'goal': 'A sign that points to a place (the library, for example) with an arrow and a big text that can be read from far away.', 'limits': ['Sign format', 'An arrow', 'A text of size 60 or more', 'AAA contrast'], 'tip': 'Signs are read from far away and quickly: a plain typeface, strong contrast and few words.'}},
    {'id': 'd8', 'level': 4, 'rules': {'minColours': 4, 'minTexts': 2, 'contrast': 'AA'},
     'es': {'title': 'Paleta de cuatro', 'goal': 'Un diseño con cuatro colores o más en el que todos los textos pasan el nivel AA.', 'limits': ['4 colores o más', '2 textos', 'Contraste AA en todos'], 'tip': 'Usa el comprobador de contraste para probar parejas antes de colorear.'},
     'en': {'title': 'Palette of four', 'goal': 'A design with four or more colours where every text passes AA.', 'limits': ['4 colours or more', '2 texts', 'AA contrast on all'], 'tip': 'Use the contrast checker to try pairs before you colour things in.'}},
    {'id': 'd9', 'level': 4, 'rules': {'format': 'pantalla', 'minTexts': 2, 'minSize': 24, 'contrast': 'AAA'},
     'es': {'title': 'Pantalla de bienvenida', 'goal': 'Una pantalla de bienvenida para un evento, con textos grandes y el contraste más alto.', 'limits': ['Formato pantalla', '2 textos', 'Ninguno por debajo de 24', 'Contraste AAA'], 'tip': 'Las pantallas se ven desde lejos y a veces con reflejos: más contraste ayuda a todo el mundo.'},
     'en': {'title': 'Welcome screen', 'goal': 'A welcome screen for an event, with big texts and the highest contrast.', 'limits': ['Screen format', '2 texts', 'None below 24', 'AAA contrast'], 'tip': 'Screens are seen from far away and sometimes with glare: more contrast helps everyone.'}},
    {'id': 'd10', 'level': 5, 'random': True, 'rules': {},
     'es': {'title': 'Encargo sorpresa', 'goal': 'Cada vez sale un encargo distinto: formato, tema, colores y textos. Con «Otro encargo» sale otro, sin fin.', 'limits': ['Lo que pida el encargo'], 'tip': 'Antes de dibujar, escribe los textos. Luego elige dos colores que contrasten y añade el tercero.'},
     'en': {'title': 'Surprise brief', 'goal': 'A different brief comes up each time: format, theme, colours and texts. “Another brief” gives you a new one, endlessly.', 'limits': ['Whatever the brief asks for'], 'tip': 'Before drawing, write the texts. Then choose two colours that contrast and add the third.'}},
]

STRINGS = {
    'es': {
        'thN': 'N.º', 'dsNewDone': 'Diseño nuevo', 'dsPng': 'Guardar imagen PNG', 'dsSvg': 'Guardar SVG', 'dsSvgSaved': 'SVG guardado: {name}', 'dsUntitled': 'Diseño sin título', 'dsMadeIn': 'hecho en el Taller',
        'dsAdd': 'Añadir', 'dsAdd_rect': 'Rectángulo', 'dsAdd_ellipse': 'Elipse', 'dsAdd_poly': 'Polígono', 'dsAdd_star': 'Estrella', 'dsAdd_line': 'Línea', 'dsAdd_arrow': 'Flecha', 'dsAdd_text': 'Texto',
        'dsType_rect': 'Rectángulo', 'dsType_ellipse': 'Elipse', 'dsType_poly': 'Polígono', 'dsType_star': 'Estrella', 'dsType_line': 'Línea', 'dsType_arrow': 'Flecha', 'dsType_text': 'Texto',
        'dsFormat': 'Formato', 'dsFormat_cartel': 'Cartel (420 × 594)', 'dsFormat_tarjeta': 'Tarjeta (340 × 220)', 'dsFormat_logo': 'Logo (400 × 400)', 'dsFormat_senal': 'Señal (800 × 400)', 'dsFormat_pantalla': 'Pantalla (960 × 540)',
        'dsBg': 'Fondo', 'dsGrid': 'Cuadrícula', 'dsSnap': 'Ajustar de 5 en 5', 'dsSnapOn': 'Ajuste activado', 'dsSnapOff': 'Ajuste desactivado',
        'dsKeyHint': 'Con teclado: entra en la mesa de trabajo con el tabulador y usa [ y ] para elegir elemento; las flechas lo mueven. Todo se puede cambiar también en «Propiedades» y en la tabla de capas.',
        'dsKShiftArrows': 'Mayúsculas + flechas', 'dsKMove': 'Mover el elemento elegido 1 punto', 'dsKMove10': 'Mover 10 puntos', 'dsKPlusMinus': '+ y −', 'dsKScale': 'Hacer más grande o más pequeño', 'dsKBrackets': '[ y ]', 'dsKCycle': 'Elegir el elemento anterior o el siguiente',
        'dsKPage': 'Re Pág y Av Pág', 'dsKOrder': 'Subir o bajar de capa', 'dsKDup': 'Control + D', 'dsKDupT': 'Duplicar', 'dsKDel': 'Supr', 'dsKDelT': 'Quitar el elemento', 'dsKEsc': 'Dejar de elegir', 'dsKUndo': 'Deshacer y rehacer',
        'dsResult': 'Resultado', 'dsProps': 'Propiedades', 'dsPalette': 'Colores', 'dsAlign': 'Alinear en la mesa', 'dsChecker': 'Comprobador de contraste', 'dsDocPanel': 'Proyecto', 'dsTitle': 'Título del diseño',
        'dsTarget': 'Aplicar a', 'dsTarget_fill': 'Relleno o color del texto', 'dsTarget_stroke': 'Borde o línea', 'dsTarget_bg': 'Fondo de la mesa', 'dsCustom': 'Otro color', 'dsApplyCustom': 'Aplicar este color',
        'dsPaletteNote': 'Elige primero un elemento. El color se aplica a lo que marques en «Aplicar a».', 'dsColourSet': '{c} aplicado a: {w}', 'dsSelectFirst': 'Primero elige un elemento.',
        'dsCol_negro': 'Negro', 'dsCol_blanco': 'Blanco', 'dsCol_marino': 'Azul marino', 'dsCol_azul': 'Azul', 'dsCol_turquesa': 'Turquesa', 'dsCol_verde': 'Verde', 'dsCol_amarillo': 'Amarillo', 'dsCol_naranja': 'Naranja', 'dsCol_rojo': 'Rojo', 'dsCol_magenta': 'Magenta', 'dsCol_violeta': 'Violeta', 'dsCol_gris': 'Gris', 'dsCol_grisclaro': 'Gris claro', 'dsCol_crema': 'Crema',
        'dsAl_left': 'Izquierda', 'dsAl_hcenter': 'Centro horizontal', 'dsAl_right': 'Derecha', 'dsAl_top': 'Arriba', 'dsAl_vcenter': 'Centro vertical', 'dsAl_bottom': 'Abajo', 'dsAlignNote': 'Coloca el elemento elegido respecto a la mesa, con un margen.',
        'dsFg': 'Texto', 'dsBgPair': 'Fondo', 'dsSwap': 'Intercambiar', 'dsSample': 'Así se lee este texto', 'dsRatio': 'Contraste: {r}:1',
        'dsAANormal': 'AA para texto normal (4,5:1)', 'dsAALarge': 'AA para texto grande (3:1)', 'dsAAANormal': 'AAA para texto normal (7:1)', 'dsNonText': 'Formas e iconos que hay que distinguir (3:1)',
        'dsCheckerNote': 'Texto grande: 24 o más, o 18,66 o más en negrita. Son los niveles de las pautas WCAG 2.2.',
        'dsNoSel': 'Elige un elemento en la mesa o en la tabla de capas, o añade uno nuevo.', 'dsText': 'Texto (Intro para otra línea)', 'dsFont': 'Letra', 'dsFont_atkinson': 'Atkinson Hyperlegible', 'dsFont_newsreader': 'Newsreader', 'dsFont_sans': 'Sin remates (Arial)', 'dsFont_serif': 'Con remates (Georgia)', 'dsFont_mono': 'Monoespaciada (Courier)',
        'dsSize': 'Tamaño', 'dsWeight': 'Grosor', 'dsW400': 'Normal', 'dsW700': 'Negrita', 'dsAlignText': 'Alineación de las líneas', 'dsTA_left': 'A la izquierda', 'dsTA_center': 'Centradas', 'dsTA_right': 'A la derecha',
        'dsLs': 'Espacio entre letras', 'dsLh': 'Altura de línea', 'dsItalic': 'Cursiva', 'dsW': 'Ancho', 'dsH': 'Alto', 'dsDx': 'Avance horizontal', 'dsDy': 'Avance vertical', 'dsRot': 'Giro (grados)', 'dsOp': 'Opacidad (%)', 'dsRadius': 'Esquinas redondeadas',
        'dsSides': 'Lados', 'dsPoints': 'Puntas', 'dsInner': 'Hueco de la estrella (%)', 'dsFill': 'Relleno', 'dsTextColour': 'Color del texto', 'dsStroke': 'Borde', 'dsLineColour': 'Color de la línea', 'dsSw': 'Grosor del borde o la línea', 'dsHex': 'código', 'dsBadHex': 'Escribe un color como #17395c.',
        'dsDup': 'Duplicar', 'dsDel': 'Quitar', 'dsDuplicated': 'Duplicado: {n}', 'dsDeleted': 'Quitado: {n}', 'dsRaised': 'Subido una capa', 'dsLowered': 'Bajado una capa', 'dsTooMany': 'Has llegado al máximo de elementos.',
        'dsNewText': 'Escribe aquí', 'dsNameText': 'Texto {n} «{s}»', 'dsAdded': 'Añadido: {n}', 'dsSelected': 'Elegido: {n}', 'dsNone': 'ninguno',
        'dsNoEls': 'La mesa está vacía. Añade una forma o un texto.', 'dsLayersCap': 'Capas ({n}); la primera está encima', 'dsThEl': 'Elemento', 'dsThContrast': 'Contraste del texto', 'dsThOrder': 'Orden', 'dsUp': 'Subir de capa: {n}', 'dsDown': 'Bajar de capa: {n}', 'dsLow': 'bajo',
        'dsAltTitle': 'Descripción en texto', 'dsAltBoard': '{f}, fondo {c}, {n} elementos, de abajo arriba:', 'dsAltText': 'Texto {n}: «{s}», tamaño {z}, letra {f}, color {c}, en X {x}, Y {y}.', 'dsAltShape': '{k} {n}, color {c}, en X {x}, Y {y}, de {w} × {h}.',
        'dsCanvasLabel': 'Mesa de trabajo, {f}, con {n} elementos. Elegido: {s}.',
        'dsCountLine': '{n} elementos y {c} colores (con el fondo).', 'dsTextLine': '{n}: {r}:1, texto {l}, {a}', 'dsLarge': 'grande', 'dsNormal': 'normal', 'dsNoTexts': 'Todavía no hay textos: el contraste se mide en cuanto pongas uno.',
        'dsDone': 'Reto cumplido', 'dsNotYet': 'Todavía no: mira la lista.', 'dsAnother': 'Otro encargo', 'dsUseFormat': 'Usar el formato del reto',
        'dsBrief': 'Encargo: {th}. Formato {f}. Colores: {c} como máximo. Textos: {n} como mínimo, uno de tamaño {b} o más. Contraste {a}.',
        'dsThemes': ['cartel de un concierto en el parque', 'tarjeta de una tienda de bicicletas', 'logo de un club de ajedrez', 'señal de la sala de música', 'pantalla de una feria de ciencia', 'cartel de una recogida de libros', 'logo de una huerta del barrio', 'señal de la salida hacia el jardín', 'pantalla de un torneo de juegos de mesa', 'cartel de un taller de cocina', 'tarjeta de una persona que arregla relojes', 'logo de un grupo de senderismo'],
        'dsChk_format': 'Formato: {f}', 'dsChk_minTexts': 'Textos: {n} (mínimo {m})', 'dsChk_maxShapes': 'Formas: {n} (entre 1 y {m})', 'dsChk_minShapes': 'Formas: {n} (mínimo {m})',
        'dsChk_maxColours': 'Colores: {n} (máximo {m})', 'dsChk_minColours': 'Colores: {n} (mínimo {m})', 'dsChk_bigText': 'Un texto de tamaño {m} o más', 'dsChk_minSize': 'Ningún texto por debajo de {m}',
        'dsChk_hierarchy': 'El texto mayor mide al menos {m} veces el menor', 'dsChk_aligned': 'Los textos comparten borde izquierdo, centro o borde derecho', 'dsChk_needArrow': 'Hay una flecha', 'dsChk_inside': 'Todo cabe dentro de la mesa',
        'dsChk_contrastAA': 'Contraste AA en todos los textos ({n} por debajo)', 'dsChk_contrastAAA': 'Contraste AAA en todos los textos ({n} por debajo)',
    },
    'en': {
        'thN': 'No.', 'dsNewDone': 'New design', 'dsPng': 'Save PNG image', 'dsSvg': 'Save SVG', 'dsSvgSaved': 'SVG saved: {name}', 'dsUntitled': 'Untitled design', 'dsMadeIn': 'made in the Workshop',
        'dsAdd': 'Add', 'dsAdd_rect': 'Rectangle', 'dsAdd_ellipse': 'Ellipse', 'dsAdd_poly': 'Polygon', 'dsAdd_star': 'Star', 'dsAdd_line': 'Line', 'dsAdd_arrow': 'Arrow', 'dsAdd_text': 'Text',
        'dsType_rect': 'Rectangle', 'dsType_ellipse': 'Ellipse', 'dsType_poly': 'Polygon', 'dsType_star': 'Star', 'dsType_line': 'Line', 'dsType_arrow': 'Arrow', 'dsType_text': 'Text',
        'dsFormat': 'Format', 'dsFormat_cartel': 'Poster (420 × 594)', 'dsFormat_tarjeta': 'Card (340 × 220)', 'dsFormat_logo': 'Logo (400 × 400)', 'dsFormat_senal': 'Sign (800 × 400)', 'dsFormat_pantalla': 'Screen (960 × 540)',
        'dsBg': 'Background', 'dsGrid': 'Grid', 'dsSnap': 'Snap to 5', 'dsSnapOn': 'Snap on', 'dsSnapOff': 'Snap off',
        'dsKeyHint': 'With a keyboard: tab into the artboard and use [ and ] to choose an element; the arrow keys move it. You can also change everything in “Properties” and in the layers table.',
        'dsKShiftArrows': 'Shift + arrows', 'dsKMove': 'Move the chosen element 1 point', 'dsKMove10': 'Move 10 points', 'dsKPlusMinus': '+ and −', 'dsKScale': 'Make it bigger or smaller', 'dsKBrackets': '[ and ]', 'dsKCycle': 'Choose the previous or next element',
        'dsKPage': 'Page Up and Page Down', 'dsKOrder': 'Move up or down a layer', 'dsKDup': 'Control + D', 'dsKDupT': 'Duplicate', 'dsKDel': 'Delete', 'dsKDelT': 'Remove the element', 'dsKEsc': 'Stop choosing', 'dsKUndo': 'Undo and redo',
        'dsResult': 'Result', 'dsProps': 'Properties', 'dsPalette': 'Colours', 'dsAlign': 'Align on the artboard', 'dsChecker': 'Contrast checker', 'dsDocPanel': 'Project', 'dsTitle': 'Design title',
        'dsTarget': 'Apply to', 'dsTarget_fill': 'Fill or text colour', 'dsTarget_stroke': 'Border or line', 'dsTarget_bg': 'Artboard background', 'dsCustom': 'Another colour', 'dsApplyCustom': 'Apply this colour',
        'dsPaletteNote': 'Choose an element first. The colour goes to whatever you pick in “Apply to”.', 'dsColourSet': '{c} applied to: {w}', 'dsSelectFirst': 'Choose an element first.',
        'dsCol_negro': 'Black', 'dsCol_blanco': 'White', 'dsCol_marino': 'Navy blue', 'dsCol_azul': 'Blue', 'dsCol_turquesa': 'Teal', 'dsCol_verde': 'Green', 'dsCol_amarillo': 'Yellow', 'dsCol_naranja': 'Orange', 'dsCol_rojo': 'Red', 'dsCol_magenta': 'Magenta', 'dsCol_violeta': 'Violet', 'dsCol_gris': 'Grey', 'dsCol_grisclaro': 'Light grey', 'dsCol_crema': 'Cream',
        'dsAl_left': 'Left', 'dsAl_hcenter': 'Centre across', 'dsAl_right': 'Right', 'dsAl_top': 'Top', 'dsAl_vcenter': 'Centre down', 'dsAl_bottom': 'Bottom', 'dsAlignNote': 'Places the chosen element on the artboard, with a margin.',
        'dsFg': 'Text', 'dsBgPair': 'Background', 'dsSwap': 'Swap', 'dsSample': 'This is how this text reads', 'dsRatio': 'Contrast: {r}:1',
        'dsAANormal': 'AA for normal text (4.5:1)', 'dsAALarge': 'AA for large text (3:1)', 'dsAAANormal': 'AAA for normal text (7:1)', 'dsNonText': 'Shapes and icons people need to tell apart (3:1)',
        'dsCheckerNote': 'Large text: size 24 or more, or 18.66 or more in bold. These are the WCAG 2.2 levels.',
        'dsNoSel': 'Choose an element on the artboard or in the layers table, or add a new one.', 'dsText': 'Text (Enter for a new line)', 'dsFont': 'Typeface', 'dsFont_atkinson': 'Atkinson Hyperlegible', 'dsFont_newsreader': 'Newsreader', 'dsFont_sans': 'Sans serif (Arial)', 'dsFont_serif': 'Serif (Georgia)', 'dsFont_mono': 'Monospaced (Courier)',
        'dsSize': 'Size', 'dsWeight': 'Weight', 'dsW400': 'Regular', 'dsW700': 'Bold', 'dsAlignText': 'Line alignment', 'dsTA_left': 'Left', 'dsTA_center': 'Centred', 'dsTA_right': 'Right',
        'dsLs': 'Letter spacing', 'dsLh': 'Line height', 'dsItalic': 'Italic', 'dsW': 'Width', 'dsH': 'Height', 'dsDx': 'Horizontal run', 'dsDy': 'Vertical run', 'dsRot': 'Rotation (degrees)', 'dsOp': 'Opacity (%)', 'dsRadius': 'Rounded corners',
        'dsSides': 'Sides', 'dsPoints': 'Points', 'dsInner': 'Star depth (%)', 'dsFill': 'Fill', 'dsTextColour': 'Text colour', 'dsStroke': 'Border', 'dsLineColour': 'Line colour', 'dsSw': 'Border or line width', 'dsHex': 'code', 'dsBadHex': 'Type a colour such as #17395c.',
        'dsDup': 'Duplicate', 'dsDel': 'Remove', 'dsDuplicated': 'Duplicated: {n}', 'dsDeleted': 'Removed: {n}', 'dsRaised': 'Moved up a layer', 'dsLowered': 'Moved down a layer', 'dsTooMany': 'You have reached the maximum number of elements.',
        'dsNewText': 'Type here', 'dsNameText': 'Text {n} “{s}”', 'dsAdded': 'Added: {n}', 'dsSelected': 'Chosen: {n}', 'dsNone': 'none',
        'dsNoEls': 'The artboard is empty. Add a shape or a text.', 'dsLayersCap': 'Layers ({n}); the first one is on top', 'dsThEl': 'Element', 'dsThContrast': 'Text contrast', 'dsThOrder': 'Order', 'dsUp': 'Move up a layer: {n}', 'dsDown': 'Move down a layer: {n}', 'dsLow': 'low',
        'dsAltTitle': 'Text description', 'dsAltBoard': '{f}, background {c}, {n} elements, from bottom to top:', 'dsAltText': 'Text {n}: “{s}”, size {z}, typeface {f}, colour {c}, at X {x}, Y {y}.', 'dsAltShape': '{k} {n}, colour {c}, at X {x}, Y {y}, {w} × {h}.',
        'dsCanvasLabel': 'Artboard, {f}, with {n} elements. Chosen: {s}.',
        'dsCountLine': '{n} elements and {c} colours (including the background).', 'dsTextLine': '{n}: {r}:1, {l} text, {a}', 'dsLarge': 'large', 'dsNormal': 'normal', 'dsNoTexts': 'No texts yet: contrast is measured as soon as you add one.',
        'dsDone': 'Challenge complete', 'dsNotYet': 'Not yet: check the list.', 'dsAnother': 'Another brief', 'dsUseFormat': 'Use the challenge format',
        'dsBrief': 'Brief: {th}. Format: {f}. Colours: {c} at most. Texts: {n} at least, one of size {b} or more. {a} contrast.',
        'dsThemes': ['poster for a concert in the park', 'card for a bicycle shop', 'logo for a chess club', 'sign for the music room', 'screen for a science fair', 'poster for a book collection', 'logo for a community garden', 'sign for the way out to the garden', 'screen for a board-game tournament', 'poster for a cooking workshop', 'card for someone who repairs clocks', 'logo for a walking group'],
        'dsChk_format': 'Format: {f}', 'dsChk_minTexts': 'Texts: {n} (minimum {m})', 'dsChk_maxShapes': 'Shapes: {n} (between 1 and {m})', 'dsChk_minShapes': 'Shapes: {n} (minimum {m})',
        'dsChk_maxColours': 'Colours: {n} (maximum {m})', 'dsChk_minColours': 'Colours: {n} (minimum {m})', 'dsChk_bigText': 'A text of size {m} or more', 'dsChk_minSize': 'No text below size {m}',
        'dsChk_hierarchy': 'The biggest text is at least {m} times the smallest', 'dsChk_aligned': 'The texts share a left edge, centre or right edge', 'dsChk_needArrow': 'There is an arrow', 'dsChk_inside': 'Everything fits on the artboard',
        'dsChk_contrastAA': 'AA contrast on all texts ({n} below)', 'dsChk_contrastAAA': 'AAA contrast on all texts ({n} below)',
    },
}
assert set(STRINGS['es']) == set(STRINGS['en'])

PAGE = {
    'es': {
        'title': 'Estudio de diseño gráfico',
        'description': 'Carteles, logos, tarjetas y señales con formas, textos y colores; comprobador de contraste WCAG 2.2 y exportación en PNG y SVG.',
        'lede': 'Una mesa de trabajo para diseñar de verdad: formas, textos con varias letras, paleta de color y capas. El estudio mide el contraste de cada texto con lo que tiene detrás y te dice si se lee bien.',
        'pills': ['Formas, textos y capas', 'Contraste WCAG 2.2 en directo', 'Cinco formatos', 'PNG y SVG', '10 retos en 5 niveles', 'Todo con teclado'],
        'steps': [
            'Elige un formato: cartel, tarjeta, logo, señal o pantalla. O elige un reto.',
            'Añade formas y textos con los botones de encima de la mesa.',
            'Cambia tamaño, color, letra y posición en «Propiedades», o arrastra sobre la mesa.',
            'Mira «Resultado» y la tabla de capas: dicen el contraste de cada texto.',
            'Guarda el proyecto en un archivo, o descárgalo en PNG o SVG.',
        ],
        'sections': [
            {'h': 'Cómo mide el contraste', 'p': 'Para cada texto, el estudio mira nueve puntos de su recuadro y calcula el color que hay detrás: el fondo más las formas que tiene debajo, con su opacidad. Se queda con el peor de los nueve.\n\nLa fórmula es la de las pautas WCAG 2.2: nivel AA pide 4,5:1 en texto normal y 3:1 en texto grande; nivel AAA pide 7:1 y 4,5:1. Texto grande es de tamaño 24 o más, o de 18,66 o más en negrita.',
             'li': ['Las letras Atkinson Hyperlegible y Newsreader se cargan con la página. Las otras son las del sistema.',
                    'El SVG guarda los textos como texto: se puede abrir y seguir editando en otros programas de dibujo.',
                    'Las imágenes descargadas llevan una franja con la marca de composición «IRIS GREEN · irisgreen.eu», fuera del diseño.']},
        ],
        'links': [('Estudio de dibujo', '/es/taller/dibujo/'), ('Estudio de ideas y proyectos', '/es/taller/ideas/'), ('Volver al Taller', '/es/taller/')],
        'credits': 'Estudio de diseño gráfico de Iris Green. Cálculo propio del contraste según la fórmula de WCAG 2.2, sin servicios externos.',
    },
    'en': {
        'title': 'Graphic design studio',
        'description': 'Posters, logos, cards and signs with shapes, texts and colours; a WCAG 2.2 contrast checker and PNG and SVG export.',
        'lede': 'An artboard for real design work: shapes, texts in several typefaces, a colour palette and layers. The studio measures the contrast of each text against what is behind it and tells you whether it is easy to read.',
        'pills': ['Shapes, texts and layers', 'Live WCAG 2.2 contrast', 'Five formats', 'PNG and SVG', '10 challenges on 5 levels', 'Everything by keyboard'],
        'steps': [
            'Choose a format: poster, card, logo, sign or screen. Or choose a challenge.',
            'Add shapes and texts with the buttons above the artboard.',
            'Change size, colour, typeface and position in “Properties”, or drag on the artboard.',
            'Look at “Result” and the layers table: they show the contrast of each text.',
            'Save the project to a file, or download it as PNG or SVG.',
        ],
        'sections': [
            {'h': 'How contrast is measured', 'p': 'For each text, the studio looks at nine points in its box and works out the colour behind it: the background plus the shapes underneath, with their opacity. It keeps the worst of the nine.\n\nThe formula is the one in the WCAG 2.2 guidelines: level AA asks for 4.5:1 for normal text and 3:1 for large text; level AAA asks for 7:1 and 4.5:1. Large text is size 24 or more, or 18.66 or more in bold.',
             'li': ['The Atkinson Hyperlegible and Newsreader typefaces load with the page. The others are the system ones.',
                    'The SVG keeps texts as text: you can open it and keep editing in other drawing programs.',
                    'Downloaded images carry a strip with the “IRIS GREEN · irisgreen.eu” credit, outside the design.']},
        ],
        'links': [('Drawing studio', '/en/workshop/drawing/'), ('Ideas and projects studio', '/en/workshop/ideas/'), ('Back to the Workshop', '/en/workshop/')],
        'credits': 'Iris Green graphic design studio. Own contrast calculation using the WCAG 2.2 formula, with no external services.',
    },
}
