"""Estudio 7 · Estructuras y puentes. Textos ES/EN, escenas y retos."""

KEY = 'estructuras'
NUMBER = 7
SLUG = {'es': 'estructuras', 'en': 'structures'}
SCRIPTS = ['ig-taller-estructuras-calc.js', 'ig-taller-estructuras.js']

LEVELS = {
    1: {'es': 'Triángulos (maqueta de mesa)', 'en': 'Triangles (table-top model)'},
    2: {'es': 'Cargas (maqueta de mesa)', 'en': 'Loads (table-top model)'},
    3: {'es': 'Carretera (tamaño real)', 'en': 'Road (full size)'},
    4: {'es': 'Tren (tamaño real)', 'en': 'Train (full size)'},
    5: {'es': 'Sin techo', 'en': 'No ceiling'},
}


def sc(scale, span, load, mats, pieces=0, k=1, walls=False, anchors=0, cliffs='both', mass=0):
    return {'scale': scale, 'span': span, 'load': load, 'mats': mats, 'maxPieces': pieces, 'maxK': k,
            'anchorsOnWalls': walls, 'maxAnchors': anchors, 'cliffs': cliffs, 'maxMass': mass}


CHALLENGES = [
    {'id': 'e1', 'level': 1, 'scene': sc('maqueta', 0.3, {'type': 'peso', 'kg': 1, 'at': [0, 0]}, ['palito'], pieces=5),
     'es': {'title': 'El triángulo', 'goal': 'Cruza un hueco de 30 cm y aguanta 1 kg colgado en el centro con cinco palitos como máximo.', 'limits': ['Máximo 5 piezas', 'Solo palitos'], 'tip': 'Dos piezas rectas en línea se doblan por el nudo del medio. Un triángulo no.'},
     'en': {'title': 'The triangle', 'goal': 'Cross a 30 cm gap and hold 1 kg hanging in the middle with five craft sticks at most.', 'limits': ['5 pieces at most', 'Craft sticks only'], 'tip': 'Two straight pieces in a line fold at the middle joint. A triangle does not.'}},
    {'id': 'e2', 'level': 1, 'scene': sc('maqueta', 0.5, {'type': 'peso', 'kg': 2, 'at': [0, 0]}, ['palito'], pieces=13),
     'es': {'title': 'Puente de palitos', 'goal': 'Un puente de 50 cm que aguante 2 kg en el centro, con 13 palitos como máximo.', 'limits': ['Máximo 13 piezas', 'Solo palitos'], 'tip': 'Palitos cortos: un palito largo comprimido se dobla (pandeo) mucho antes.'},
     'en': {'title': 'Craft-stick bridge', 'goal': 'A 50 cm bridge that holds 2 kg in the middle, with 13 craft sticks at most.', 'limits': ['13 pieces at most', 'Craft sticks only'], 'tip': 'Keep sticks short: a long stick being squeezed bends (buckles) much sooner.'}},
    {'id': 'e3', 'level': 2, 'scene': sc('maqueta', 0.5, {'type': 'peso', 'kg': 5, 'at': [0, 0]}, ['palito', 'hilo'], pieces=21),
     'es': {'title': 'Cinco kilos', 'goal': 'El mismo hueco de 50 cm, ahora con 5 kg. Palitos e hilo, 21 piezas como máximo.', 'limits': ['Máximo 21 piezas', 'Palitos e hilo'], 'tip': 'El hilo solo sirve donde la pieza tira (tracción). Donde empuja, se afloja.'},
     'en': {'title': 'Five kilos', 'goal': 'The same 50 cm gap, now with 5 kg. Craft sticks and string, 21 pieces at most.', 'limits': ['21 pieces at most', 'Craft sticks and string'], 'tip': 'String only works where a piece is pulled (tension). Where it is pushed, it goes slack.'}},
    {'id': 'e4', 'level': 2, 'scene': sc('maqueta', 0.5, {'type': 'peso', 'kg': 1, 'at': [0.15, 0]}, ['palito', 'liston', 'hilo'], pieces=16, walls=True, anchors=2, cliffs='left'),
     'es': {'title': 'Voladizo', 'goal': 'Solo hay pared a la izquierda. Sujeta 1 kg a 40 cm de la pared, como una grúa o un balcón.', 'limits': ['Máximo 16 piezas', 'Hasta 2 apoyos más en la pared'], 'tip': 'Arriba las piezas tiran; abajo empujan contra la pared.'},
     'en': {'title': 'Cantilever', 'goal': 'There is only a wall on the left. Hold 1 kg 40 cm away from the wall, like a crane or a balcony.', 'limits': ['16 pieces at most', 'Up to 2 more supports on the wall'], 'tip': 'At the top the pieces pull; at the bottom they push against the wall.'}},
    {'id': 'e5', 'level': 3, 'scene': sc('real', 12, {'type': 'coche'}, ['madera', 'acero'], pieces=7),
     'es': {'title': 'Un coche sobre el río', 'goal': 'Un puente de 12 m para que pase un coche. Siete piezas como máximo.', 'limits': ['Máximo 7 piezas', 'Madera o acero', 'La carretera va por la línea discontinua, de borde a borde'], 'tip': 'Con pocas piezas, piensa en un solo triángulo grande con la carretera abajo.'},
     'en': {'title': 'A car over the river', 'goal': 'A 12 m bridge for a car to cross. Seven pieces at most.', 'limits': ['7 pieces at most', 'Timber or steel', 'The road runs along the dashed line, edge to edge'], 'tip': 'With few pieces, think of one big triangle with the road at the bottom.'}},
    {'id': 'e6', 'level': 3, 'scene': sc('real', 20, {'type': 'camion'}, ['madera', 'acero', 'cable'], pieces=13),
     'es': {'title': 'Pasa un camión', 'goal': 'Un puente de 20 m para un camión de 26 toneladas. Trece piezas como máximo.', 'limits': ['Máximo 13 piezas'], 'tip': 'La prueba mueve el camión de un lado a otro: la pieza más cargada cambia según dónde esté.'},
     'en': {'title': 'A lorry crosses', 'goal': 'A 20 m bridge for a 26-tonne lorry. Thirteen pieces at most.', 'limits': ['13 pieces at most'], 'tip': 'The test drives the lorry from one side to the other: the most loaded piece changes as it moves.'}},
    {'id': 'e7', 'level': 4, 'scene': sc('real', 24, {'type': 'tren'}, ['madera', 'acero', 'cable']),
     'es': {'title': 'Que pase el tren', 'goal': 'Un puente de 24 m por el que pase una locomotora con un vagón: 140 toneladas.', 'limits': ['Sin límite de piezas', 'Sección sencilla'], 'tip': 'Las piezas inclinadas de los extremos son las que más empujan. Hazlas cortas.'},
     'en': {'title': 'Let the train through', 'goal': 'A 24 m bridge for a locomotive and one wagon to cross: 140 tonnes.', 'limits': ['No limit on pieces', 'Single section'], 'tip': 'The sloping pieces at the ends push hardest. Keep them short.'}},
    {'id': 'e8', 'level': 4, 'scene': sc('real', 24, {'type': 'tren'}, ['madera', 'acero', 'cable'], mass=2500),
     'es': {'title': 'El más ligero que aguante un tren', 'goal': 'El mismo tren y el mismo hueco, con menos de 2,5 toneladas de estructura. Cada prueba te dice tu mejor marca de esta sesión.', 'limits': ['Estructura de menos de 2.500 kg', 'Sección sencilla'], 'tip': 'Los cables pesan poco, pero solo tiran. Cruzados en X, uno de los dos siempre trabaja.'},
     'en': {'title': 'The lightest one that holds a train', 'goal': 'The same train and the same gap, with under 2.5 tonnes of structure. Each test shows your best result this session.', 'limits': ['Structure under 2,500 kg', 'Single section'], 'tip': 'Cables weigh little, but they only pull. Crossed in an X, one of the two is always working.'}},
    {'id': 'e9', 'level': 5, 'scene': sc('real', 36, {'type': 'tren'}, ['madera', 'acero', 'cable'], k=3),
     'es': {'title': 'Treinta y seis metros', 'goal': 'Un vano de 36 m con el tren. Puedes usar secciones dobles o triples: aguantan más y pesan más.', 'limits': ['Secciones de hasta ×3'], 'tip': 'Refuerza solo las piezas que la tabla marca cerca del límite.'},
     'en': {'title': 'Thirty-six metres', 'goal': 'A 36 m span with the train. You can use double or triple sections: stronger and heavier.', 'limits': ['Sections up to ×3'], 'tip': 'Strengthen only the pieces the table shows close to their limit.'}},
    {'id': 'e10', 'level': 5, 'scene': sc('real', 30, {'type': 'camion'}, ['madera'], walls=True),
     'es': {'title': 'Arco', 'goal': 'Un puente de 30 m solo de madera para el camión. Puedes apoyar piezas en las paredes del barranco.', 'limits': ['Solo madera', 'Apoyos en las paredes permitidos'], 'tip': 'Un arco empuja contra las paredes: todas sus piezas trabajan a compresión.'},
     'en': {'title': 'Arch', 'goal': 'A 30 m timber-only bridge for the lorry. You can rest pieces on the canyon walls.', 'limits': ['Timber only', 'Supports on the walls allowed'], 'tip': 'An arch pushes against the walls: all its pieces work in compression.'}},
    {'id': 'e11', 'level': 5, 'random': True, 'scene': sc('real', 20, {'type': 'coche'}, ['madera', 'acero', 'cable']),
     'es': {'title': 'Encargo al azar', 'goal': 'Un hueco, una carga y unos materiales al azar. Pide otro encargo cuando quieras: no se acaban.', 'limits': ['Cambian en cada encargo'], 'tip': 'Lee la escena en «Escena» antes de empezar.'},
     'en': {'title': 'Random commission', 'goal': 'A random gap, load and set of materials. Ask for another commission whenever you like: they never run out.', 'limits': ['They change with each commission'], 'tip': 'Read the setup under “Scene” before you start.'}},
]

STRINGS = {
    'es': {
        'yes': 'sí', 'no': 'no', 'kEscCancel': 'Cancela la pieza en curso',
        'eCanvasRole': 'editor de estructuras', 'eCanvasLabel': 'Estructura con {n} piezas sobre un hueco de {span}',
        'eKeyHint': 'Con teclado: entra en el dibujo con el tabulador, mueve el cursor por la rejilla con las flechas y pulsa Intro en el punto de inicio y en el final de cada pieza. Todo lo que ves está también en la tabla de piezas.',
        'eKArrows': 'Mueven el cursor un punto de la rejilla', 'eKEnter': 'Marca el inicio y el final de una pieza (o actúa según la herramienta)', 'eKDelete': 'Borra el nudo del cursor y sus piezas',
        'eKModes': 'Herramientas: pieza, mover, borrar, apoyo, cambiar material', 'eKTest': 'Probar la carga',
        'eTools': 'Herramientas', 'mode_pieza': 'Pieza', 'mode_pintar': 'Cambiar material', 'mode_mover': 'Mover nudo', 'mode_borrar': 'Borrar', 'mode_apoyo': 'Apoyo',
        'modeHelp_pieza': 'Arrastra de un punto a otro, o toca el inicio y luego el final.', 'modeHelp_pintar': 'Toca una pieza para ponerle el material y la sección elegidos.',
        'modeHelp_mover': 'Arrastra un nudo a otro punto de la rejilla.', 'modeHelp_borrar': 'Toca una pieza o un nudo para quitarlo.', 'modeHelp_apoyo': 'Toca un punto del borde del terreno para poner o quitar un apoyo.',
        'eMaterial': 'Material', 'eSection': 'Sección', 'section_1': 'Sencilla', 'section_2': 'Doble (×2)', 'section_3': 'Triple (×3)',
        'mat_palito': 'Palito', 'mat_liston': 'Listón', 'mat_hilo': 'Hilo', 'mat_madera': 'Madera', 'mat_acero': 'Acero', 'mat_cable': 'Cable',
        'matInfo_palito': 'Palito de manualidades de 10 × 2 mm. Ligero; comprimido y largo, se dobla pronto.', 'matInfo_liston': 'Listón de pino de 5 × 5 mm. Más rígido que el palito.',
        'matInfo_hilo': 'Cordel de algodón. Solo aguanta tirando (tracción); montado tenso.', 'matInfo_madera': 'Viga de madera laminada de 20 × 20 cm.',
        'matInfo_acero': 'Perfil de acero IPE 300.', 'matInfo_cable': 'Cable de acero de 50 mm. Solo aguanta tirando; montado tenso.',
        'eCapInfo': 'Con {len} de largo aguanta {t} tirando y {c} empujando. Pesa {w}.', 'eNoCompression': 'nada',
        'eMatPicked': 'Material: {m}',
        'eScene': 'Escena', 'eScale': 'Tamaño', 'scale_real': 'Tamaño real', 'scale_maqueta': 'Maqueta de mesa', 'eSpanM': 'Hueco (metros, de 4 a 60)', 'eSpanCm': 'Hueco (centímetros, de 10 a 100)',
        'eLoad': 'Carga', 'eKg': 'Peso colgado (kg)', 'eWalls': 'Permitir apoyos en el terreno', 'eApplyScene': 'Usar esta escena',
        'eSceneInfo': '{scale}. Hueco de {span}. Carga: {load}. Piezas máximas: {pieces}. Materiales: {mats}. Apoyos en el terreno: {walls}.',
        'eMaxMassInfo': 'Peso máximo de la estructura: {m}.', 'eNoLimit': 'sin límite',
        'eSceneConfirm': 'Cambiar la escena empieza una estructura nueva. Lo que no hayas guardado en un archivo se pierde (puedes deshacerlo). ¿Seguir?',
        'eSceneApplied': 'Escena nueva lista', 'eAnother': 'Otro encargo',
        'loadWeight': '{kg} kg colgados', 'loadWeightShort': 'Peso colgado', 'veh_persona': 'una persona', 'veh_grupo': 'un grupo de personas (960 kg)', 'veh_coche': 'un coche (1,5 t)',
        'veh_camion': 'un camión (26 t)', 'veh_tren': 'un tren (140 t)',
        'eTest': 'Probar la carga', 'eTesting': 'Probando…', 'eResult': 'Resultado', 'eNoTestYet': 'Construye y pulsa «Probar la carga». La prueba incluye el peso de las piezas.',
        'eEmpty': 'Todavía no hay piezas.', 'eRoadGap': 'Falta carretera entre {gaps}. Pon piezas por la línea discontinua de borde a borde.',
        'eLoadPoint': 'Falta un nudo en el punto de carga (flecha rosa, a {x} del borde izquierdo).',
        'eHolds': 'Aguanta. La pieza más exigida llega al {peak} % de lo que resiste.',
        'eBreaks': 'Se rompe la pieza {n}: {why}{pos}.', 'eWhen': ' cuando la carga está a {x}',
        'eWhyTension': 'se parte de tanto tirar', 'eWhyBuckle': 'se dobla de lado al empujar (pandeo)', 'eWhyCrush': 'se aplasta al empujar',
        'eThenFalls': 'Sin ella, la estructura se viene abajo.', 'eStandsDamaged': 'Se rompen {n} piezas, pero lo demás sigue en pie.',
        'eMechanism': 'La estructura se mueve sin romperse: le falta algún triángulo. El nudo marcado con un círculo rojo no está sujeto.',
        'eMass': 'Peso de la estructura: {m}', 'ePieces': 'Piezas: {n}',
        'eGoalPieces': 'Piezas: {n} (máximo {m})', 'eGoalMass': 'Peso: {m} (máximo {max})', 'eChallengeDone': 'Reto cumplido.', 'eChallengeAlmost': 'Aguanta, pero falta cumplir un límite del reto.',
        'eBetter': 'Mejoras tu marca de esta sesión (antes: {m}).', 'eBestSoFar': 'Tu mejor marca en esta sesión: {m}.',
        'ePos': 'Frente de la carga a {x} del borde izquierdo (paso {n} de {m})', 'eDeform': 'Ver la deformación (exagerada)', 'eDeformX': 'deformación ×{n}',
        'eMaxShort': 'máx. {u} %',
        'eOutside': 'Ese punto está fuera de la zona de trabajo.', 'eInGround': 'Ese punto está dentro del terreno.', 'eNoAnchorHere': 'En esta escena no se puede apoyar en ese punto del terreno.',
        'eMaxAnchors': 'Esta escena permite {n} apoyos más como máximo.', 'eMaxPieces': 'Este reto permite {n} piezas como máximo.', 'eTooMany': 'Demasiadas piezas para el editor.',
        'eExists': 'Ya hay una pieza entre esos dos nudos.', 'eAdded': 'Pieza {n}: {mat}, {len}', 'eDeleted': 'Pieza borrada', 'eNodeDeleted': 'Nudo y sus piezas borrados',
        'eFixedAnchor': 'Los apoyos de los bordes son parte del terreno y no se quitan.', 'eAnchorNoMove': 'Los apoyos no se mueven.', 'eOccupied': 'Ya hay un nudo ahí.',
        'eMoved': 'Nudo movido a {x}, {y}', 'eAnchorOnlyGround': 'Los apoyos van en el borde del terreno: arriba de los lados o en las paredes.', 'eAnchorAdded': 'Apoyo añadido',
        'ePainted': 'Pieza {n}: {mat}', 'eNewDone': 'Estructura nueva',
        'eCursor': 'Cursor en {x} del borde izquierdo, altura {y}: {what}', 'eAtAnchor': 'apoyo', 'eAtNode': 'nudo con {n} piezas', 'eAtGround': 'dentro del terreno', 'eAtEdge': 'borde del terreno',
        'eAtEmpty': 'punto libre', 'eFrom': 'pieza empezada en {x}, {y}',
        'eStartMarked': 'Inicio marcado. Mueve el cursor y pulsa Intro en el final.', 'eNodePicked': 'Nudo elegido. Mueve el cursor y pulsa Intro donde quieras dejarlo.',
        'eNoNodeHere': 'No hay un nudo en el cursor.', 'eNoMemberHere': 'No hay una pieza junto al cursor.', 'eCancelled': 'Cancelado',
        'eAltTitle': 'Qué hay en el dibujo', 'eAltText': '{scale}, hueco de {span}, carga: {load}. {pieces} piezas, {nodes} nudos y {anchors} apoyos.',
        'eByMaterial': 'Por material:',
        'eLegend': 'Tras la prueba: azul, la pieza tira (tracción); naranja con raya blanca, empuja (compresión). Cuanto más oscura y gruesa, más cerca de su límite. Discontinua roja con aspa, rota; punteada gris, cable flojo.',
        'eLegendShort': 'Azul: tira. Naranja con raya blanca: empuja. Roja discontinua con aspa: rota. La tabla da los valores exactos.',
        'eTableCap': 'Piezas de la estructura ({n})', 'eTableEmpty': 'Todavía no hay piezas.',
        'thN': 'N.º', 'thFromTo': 'De → a (desde el borde izquierdo, altura)', 'thLen': 'Largo', 'thMat': 'Material y sección', 'thForce': 'Fuerza', 'thKind': 'Trabaja', 'thUse': 'Uso', 'thState': 'Estado', 'thDel': 'Quitar',
        'kTension': 'tirando', 'kNone': 'casi nada', 'kCompression': 'empujando', 'stNotTested': 'sin probar', 'stBroken': 'rota', 'stSlack': 'floja', 'stLimit': 'cerca del límite', 'stOk': 'bien', 'stBuckle': 'puede pandear', 'stUnstable': 'estructura inestable',
        'eRowMat': 'Material de la pieza {n}', 'eRowSection': 'Sección de la pieza {n}', 'eRowDelete': 'Quitar la pieza {n}',
    },
    'en': {
        'yes': 'yes', 'no': 'no', 'kEscCancel': 'Cancels the piece in progress',
        'eCanvasRole': 'structure editor', 'eCanvasLabel': 'Structure with {n} pieces over a {span} gap',
        'eKeyHint': 'With a keyboard: tab into the drawing, move the cursor around the grid with the arrow keys and press Enter at the start and at the end of each piece. Everything you see is also in the table of pieces.',
        'eKArrows': 'Move the cursor one grid point', 'eKEnter': 'Marks the start and end of a piece (or acts with the current tool)', 'eKDelete': 'Deletes the joint under the cursor and its pieces',
        'eKModes': 'Tools: piece, move, delete, support, change material', 'eKTest': 'Test the load',
        'eTools': 'Tools', 'mode_pieza': 'Piece', 'mode_pintar': 'Change material', 'mode_mover': 'Move joint', 'mode_borrar': 'Delete', 'mode_apoyo': 'Support',
        'modeHelp_pieza': 'Drag from one point to another, or tap the start and then the end.', 'modeHelp_pintar': 'Tap a piece to give it the chosen material and section.',
        'modeHelp_mover': 'Drag a joint to another grid point.', 'modeHelp_borrar': 'Tap a piece or a joint to remove it.', 'modeHelp_apoyo': 'Tap a point on the edge of the ground to add or remove a support.',
        'eMaterial': 'Material', 'eSection': 'Section', 'section_1': 'Single', 'section_2': 'Double (×2)', 'section_3': 'Triple (×3)',
        'mat_palito': 'Craft stick', 'mat_liston': 'Batten', 'mat_hilo': 'String', 'mat_madera': 'Timber', 'mat_acero': 'Steel', 'mat_cable': 'Cable',
        'matInfo_palito': 'A 10 × 2 mm craft stick. Light; when long and squeezed it bends early.', 'matInfo_liston': 'A 5 × 5 mm pine batten. Stiffer than a craft stick.',
        'matInfo_hilo': 'Cotton string. It only holds when pulled (tension); fitted taut.', 'matInfo_madera': 'A 20 × 20 cm glued-laminated timber beam.',
        'matInfo_acero': 'An IPE 300 steel section.', 'matInfo_cable': 'A 50 mm steel cable. It only holds when pulled; fitted taut.',
        'eCapInfo': 'At {len} long it holds {t} pulling and {c} pushing. It weighs {w}.', 'eNoCompression': 'nothing',
        'eMatPicked': 'Material: {m}',
        'eScene': 'Scene', 'eScale': 'Size', 'scale_real': 'Full size', 'scale_maqueta': 'Table-top model', 'eSpanM': 'Gap (metres, 4 to 60)', 'eSpanCm': 'Gap (centimetres, 10 to 100)',
        'eLoad': 'Load', 'eKg': 'Hanging weight (kg)', 'eWalls': 'Allow supports on the ground', 'eApplyScene': 'Use this scene',
        'eSceneInfo': '{scale}. Gap of {span}. Load: {load}. Maximum pieces: {pieces}. Materials: {mats}. Supports on the ground: {walls}.',
        'eMaxMassInfo': 'Maximum structure weight: {m}.', 'eNoLimit': 'no limit',
        'eSceneConfirm': 'Changing the scene starts a new structure. Anything you have not saved to a file is lost (you can undo this). Carry on?',
        'eSceneApplied': 'New scene ready', 'eAnother': 'Another commission',
        'loadWeight': '{kg} kg hanging', 'loadWeightShort': 'Hanging weight', 'veh_persona': 'one person', 'veh_grupo': 'a group of people (960 kg)', 'veh_coche': 'a car (1.5 t)',
        'veh_camion': 'a lorry (26 t)', 'veh_tren': 'a train (140 t)',
        'eTest': 'Test the load', 'eTesting': 'Testing…', 'eResult': 'Result', 'eNoTestYet': 'Build, then press “Test the load”. The test includes the weight of the pieces.',
        'eEmpty': 'There are no pieces yet.', 'eRoadGap': 'Road missing between {gaps}. Put pieces along the dashed line from edge to edge.',
        'eLoadPoint': 'A joint is needed at the load point (pink arrow, {x} from the left edge).',
        'eHolds': 'It holds. The hardest-working piece reaches {peak}% of what it can take.',
        'eBreaks': 'Piece {n} breaks: {why}{pos}.', 'eWhen': ' when the load is at {x}',
        'eWhyTension': 'it snaps from being pulled too hard', 'eWhyBuckle': 'it bends sideways when pushed (buckling)', 'eWhyCrush': 'it is crushed when pushed',
        'eThenFalls': 'Without it, the structure comes down.', 'eStandsDamaged': '{n} pieces break, but the rest stays up.',
        'eMechanism': 'The structure moves without breaking: a triangle is missing somewhere. The joint circled in red is not held in place.',
        'eMass': 'Structure weight: {m}', 'ePieces': 'Pieces: {n}',
        'eGoalPieces': 'Pieces: {n} (at most {m})', 'eGoalMass': 'Weight: {m} (at most {max})', 'eChallengeDone': 'Challenge done.', 'eChallengeAlmost': 'It holds, but one of the challenge limits is not met yet.',
        'eBetter': 'You beat your best result this session (before: {m}).', 'eBestSoFar': 'Your best result this session: {m}.',
        'ePos': 'Front of the load {x} from the left edge (step {n} of {m})', 'eDeform': 'Show the deformation (exaggerated)', 'eDeformX': 'deformation ×{n}',
        'eMaxShort': 'max. {u}%',
        'eOutside': 'That point is outside the work area.', 'eInGround': 'That point is inside the ground.', 'eNoAnchorHere': 'In this scene you cannot rest on that point of the ground.',
        'eMaxAnchors': 'This scene allows {n} more supports at most.', 'eMaxPieces': 'This challenge allows {n} pieces at most.', 'eTooMany': 'Too many pieces for the editor.',
        'eExists': 'There is already a piece between those two joints.', 'eAdded': 'Piece {n}: {mat}, {len}', 'eDeleted': 'Piece deleted', 'eNodeDeleted': 'Joint and its pieces deleted',
        'eFixedAnchor': 'The supports at the edges are part of the ground and cannot be removed.', 'eAnchorNoMove': 'Supports do not move.', 'eOccupied': 'There is already a joint there.',
        'eMoved': 'Joint moved to {x}, {y}', 'eAnchorOnlyGround': 'Supports go on the edge of the ground: on top of either side or on the walls.', 'eAnchorAdded': 'Support added',
        'ePainted': 'Piece {n}: {mat}', 'eNewDone': 'New structure',
        'eCursor': 'Cursor {x} from the left edge, height {y}: {what}', 'eAtAnchor': 'support', 'eAtNode': 'joint with {n} pieces', 'eAtGround': 'inside the ground', 'eAtEdge': 'edge of the ground',
        'eAtEmpty': 'free point', 'eFrom': 'piece started at {x}, {y}',
        'eStartMarked': 'Start marked. Move the cursor and press Enter at the end.', 'eNodePicked': 'Joint picked. Move the cursor and press Enter where you want to drop it.',
        'eNoNodeHere': 'There is no joint under the cursor.', 'eNoMemberHere': 'There is no piece next to the cursor.', 'eCancelled': 'Cancelled',
        'eAltTitle': 'What is in the drawing', 'eAltText': '{scale}, gap of {span}, load: {load}. {pieces} pieces, {nodes} joints and {anchors} supports.',
        'eByMaterial': 'By material:',
        'eLegend': 'After the test: blue, the piece is pulled (tension); orange with a white stripe, it is pushed (compression). The darker and thicker, the closer to its limit. Red dashed with a cross, broken; grey dotted, slack cable.',
        'eLegendShort': 'Blue: pulled. Orange with a white stripe: pushed. Red dashed with a cross: broken. The table gives the exact values.',
        'eTableCap': 'Pieces in the structure ({n})', 'eTableEmpty': 'There are no pieces yet.',
        'thN': 'No.', 'thFromTo': 'From → to (distance from left edge, height)', 'thLen': 'Length', 'thMat': 'Material and section', 'thForce': 'Force', 'thKind': 'Working', 'thUse': 'Use', 'thState': 'State', 'thDel': 'Remove',
        'kTension': 'pulled', 'kNone': 'almost nothing', 'kCompression': 'pushed', 'stNotTested': 'not tested', 'stBroken': 'broken', 'stSlack': 'slack', 'stLimit': 'near its limit', 'stOk': 'fine', 'stBuckle': 'may buckle', 'stUnstable': 'unstable structure',
        'eRowMat': 'Material of piece {n}', 'eRowSection': 'Section of piece {n}', 'eRowDelete': 'Remove piece {n}',
    },
}
assert set(STRINGS['es']) == set(STRINGS['en'])

PAGE = {
    'es': {
        'title': 'Estudio de estructuras y puentes',
        'description': 'Construye puentes con palitos, madera, acero y cables y pruébalos con pesos, coches, camiones y un tren. Cálculo real de fuerzas, pandeo y roturas.',
        'lede': 'Construye puentes y estructuras pieza a pieza y pruébalos: un peso colgado, un coche, un camión o un tren. El cálculo dice qué pieza tira, cuál empuja y cuál se rompe.',
        'pills': ['Maqueta de mesa y tamaño real', '6 materiales', 'Cálculo de fuerzas y pandeo', 'Cargas que se mueven', 'Tabla con todos los valores', '11 retos en 5 niveles', 'Ratón, dedo o teclado'],
        'steps': [
            'Elige un reto o prepara tu escena en «Escena».',
            'Con «Pieza», une dos puntos de la rejilla. Empieza en los apoyos de los bordes.',
            'Elige el material antes de poner cada pieza, o cámbialo luego con «Cambiar material» o en la tabla.',
            'Pulsa «Probar la carga». La carga cruza el puente y el dibujo muestra qué pieza tira, cuál empuja y cuál se rompe.',
            'Corrige y vuelve a probar. Guarda el proyecto para seguir otro día.',
        ],
        'sections': [
            {'h': 'Cómo calcula', 'p': 'Cada pieza une dos nudos que giran libremente, como en una celosía. Con esas uniones, una pieza solo puede tirar (tracción) o empujar (compresión). El programa resuelve el equilibrio de todos los nudos a la vez, con el peso de las piezas, el de la calzada y la carga.\n\nUna pieza se rompe si tira más de lo que resiste o si empuja más de lo que aguanta. Las piezas largas que empujan se doblan de lado antes de aplastarse: es el pandeo, y crece con el cuadrado del largo. Los hilos y cables solo tiran y se montan tensos. Si una pieza se rompe, el cálculo la quita y mira si lo demás aguanta.',
             'li': ['Es un modelo para aprender: uniones ideales, sin viento, sin vibraciones y sin coeficientes de seguridad. No sirve para diseñar nada que se vaya a construir.',
                    'Materiales (valores aproximados): palito de manualidades de 10 × 2 mm y listón de pino de 5 × 5 mm (módulo 10 GPa, resistencia 30 MPa); cordel que rompe con unos 60 N; madera laminada de 20 × 20 cm (11 GPa, 24 MPa); perfil de acero IPE 300 (210 GPa, 275 MPa); cable de acero de 50 mm (rotura de cálculo 1.500 kN).',
                    'Cargas (aproximadas): coche de 1,5 t en 2 ejes; camión de 26 t en 3 ejes; locomotora de 80 t y vagón de 60 t en 8 ejes; calzada de 400 kg por metro en tamaño real.']},
        ],
        'links': [('Estudio de programación', '/es/taller/programacion/'), ('Estudio de robótica', '/es/taller/robotica/'), ('Tus intereses', '/es/intereses/'), ('Volver al Taller', '/es/taller/')],
        'credits': 'Estudio de estructuras de Iris Green. Cálculo propio por el método de rigidez, sin servicios externos.',
    },
    'en': {
        'title': 'Structures and bridges studio',
        'description': 'Build bridges from craft sticks, timber, steel and cables and test them with weights, cars, lorries and a train. Real calculation of forces, buckling and failures.',
        'lede': 'Build bridges and structures piece by piece and test them: a hanging weight, a car, a lorry or a train. The calculation shows which piece is pulled, which is pushed and which breaks.',
        'pills': ['Table-top model and full size', '6 materials', 'Forces and buckling', 'Moving loads', 'Table with every value', '11 challenges on 5 levels', 'Mouse, finger or keyboard'],
        'steps': [
            'Pick a challenge or set up your own scene under “Scene”.',
            'With “Piece”, join two grid points. Start from the supports at the edges.',
            'Choose the material before placing each piece, or change it later with “Change material” or in the table.',
            'Press “Test the load”. The load crosses the bridge and the drawing shows which piece is pulled, which is pushed and which breaks.',
            'Fix it and test again. Save the project to carry on another day.',
        ],
        'sections': [
            {'h': 'How it calculates', 'p': 'Each piece joins two joints that turn freely, as in a truss. With joints like that, a piece can only pull (tension) or push (compression). The program solves the balance of every joint at once, with the weight of the pieces, the road deck and the load.\n\nA piece breaks if it is pulled harder than it can take, or pushed harder than it can hold. Long pieces that are pushed bend sideways before they are crushed: this is buckling, and it grows with the square of the length. Strings and cables only pull and are fitted taut. If a piece breaks, the calculation removes it and checks whether the rest still holds.',
             'li': ['It is a model for learning: ideal joints, no wind, no vibration and no safety factors. It is not for designing anything that will be built.',
                    'Materials (approximate values): 10 × 2 mm craft stick and 5 × 5 mm pine batten (modulus 10 GPa, strength 30 MPa); string that snaps at about 60 N; 20 × 20 cm glued-laminated timber (11 GPa, 24 MPa); IPE 300 steel section (210 GPa, 275 MPa); 50 mm steel cable (design breaking load 1,500 kN).',
                    'Loads (approximate): 1.5 t car on 2 axles; 26 t lorry on 3 axles; 80 t locomotive and 60 t wagon on 8 axles; road deck of 400 kg per metre at full size.']},
        ],
        'links': [('Coding studio', '/en/workshop/coding/'), ('Robotics studio', '/en/workshop/robotics/'), ('Your interests', '/en/interests/'), ('Back to the workshop', '/en/workshop/')],
        'credits': 'Iris Green structures studio. Our own stiffness-method calculation, with no external services.',
    },
}
