"""Estudio 9 · Máquinas. Textos ES/EN y retos."""

KEY = 'maquinas'
NUMBER = 9
SLUG = {'es': 'maquinas', 'en': 'machines'}
SCRIPTS = ['ig-taller-maquinas-calc.js', 'ig-taller-maquinas.js']

LEVELS = {
    1: {'es': 'Primeros mecanismos', 'en': 'First mechanisms'},
    2: {'es': 'Fuerza y sentido', 'en': 'Force and direction'},
    3: {'es': 'Trenes compuestos', 'en': 'Compound trains'},
    4: {'es': 'Cargas grandes', 'en': 'Heavy loads'},
    5: {'es': 'Sin techo', 'en': 'No ceiling'},
}

CHALLENGES = [
    {'id': 'g1', 'level': 1, 'tab': 'gears', 'rules': {'ratio': 1 / 3},
     'es': {'title': 'Tres veces más lento', 'goal': 'Monta dos engranajes para que la salida gire tres veces más despacio que el motor.', 'limits': ['Marca un engranaje como salida', 'Relación 1:3'], 'tip': 'Si el motor tiene 20 dientes, busca uno con el triple de dientes.'},
     'en': {'title': 'Three times slower', 'goal': 'Build two gears so the output turns three times slower than the motor.', 'limits': ['Mark one gear as the output', 'Ratio 1:3'], 'tip': 'If the motor has 20 teeth, look for one with three times as many.'}},
    {'id': 'g2', 'level': 1, 'tab': 'gears', 'rules': {'ratio': 1, 'sameDir': True},
     'es': {'title': 'Mismo sentido, misma velocidad', 'goal': 'Haz que la salida gire igual de rápido que el motor y en el mismo sentido.', 'limits': ['Relación 1:1', 'Mismo sentido que el motor'], 'tip': 'Dos engranajes que se tocan giran en sentidos contrarios. Un tercero en medio devuelve el sentido.'},
     'en': {'title': 'Same direction, same speed', 'goal': 'Make the output turn as fast as the motor and in the same direction.', 'limits': ['Ratio 1:1', 'Same direction as the motor'], 'tip': 'Two gears that touch turn in opposite directions. A third one in the middle turns it back.'}},
    {'id': 'g3', 'level': 2, 'tab': 'gears', 'rules': {'minTorque': 4},
     'es': {'title': 'Cuatro veces más fuerza', 'goal': 'Consigue que la salida tenga por lo menos cuatro veces el par (la fuerza de giro) del motor.', 'limits': ['Par ×4 o más en la salida'], 'tip': 'Lo que se gana en fuerza se pierde en velocidad: un engranaje pequeño que mueve uno grande.'},
     'en': {'title': 'Four times the force', 'goal': 'Make the output have at least four times the motor’s torque (turning force).', 'limits': ['Torque ×4 or more at the output'], 'tip': 'What you gain in force you lose in speed: a small gear driving a big one.'}},
    {'id': 'g4', 'level': 2, 'tab': 'gears', 'rules': {'ratio': 3, 'sameDir': True},
     'es': {'title': 'Triple de rápido', 'goal': 'La salida tiene que girar tres veces más rápido que el motor y en el mismo sentido.', 'limits': ['Relación 3:1', 'Mismo sentido que el motor'], 'tip': 'Ahora el grande mueve al pequeño. Para el sentido, recuerda el engranaje del medio.'},
     'en': {'title': 'Three times faster', 'goal': 'The output must turn three times faster than the motor and in the same direction.', 'limits': ['Ratio 3:1', 'Same direction as the motor'], 'tip': 'Now the big one drives the small one. For the direction, remember the gear in the middle.'}},
    {'id': 'g5', 'level': 3, 'tab': 'gears', 'rules': {'ratio': 1 / 12, 'sameDir': True},
     'es': {'title': 'La aguja de las horas', 'goal': 'En un reloj, la aguja de los minutos da 12 vueltas mientras la de las horas da una. Monta ese tren: 12 veces más lento y en el mismo sentido.', 'limits': ['Relación 1:12', 'Mismo sentido que el motor'], 'tip': 'Con un solo par no llegas. Pon dos engranajes en el mismo eje («delante» o «detrás»): 1:3 y luego 1:4.'},
     'en': {'title': 'The hour hand', 'goal': 'On a clock, the minute hand goes round 12 times while the hour hand goes round once. Build that train: 12 times slower and in the same direction.', 'limits': ['Ratio 1:12', 'Same direction as the motor'], 'tip': 'One pair is not enough. Put two gears on the same axle (“in front” or “behind”): 1:3 and then 1:4.'}},
    {'id': 'g6', 'level': 3, 'tab': 'gears', 'rules': {'ratio': 1 / 60, 'maxTeeth': 60},
     'es': {'title': 'Sesenta a uno', 'goal': 'De segundos a minutos: la salida da una vuelta por cada 60 del motor, sin usar engranajes de más de 60 dientes.', 'limits': ['Relación 1:60', 'Ningún engranaje de más de 60 dientes'], 'tip': '60 = 3 × 4 × 5. Tres etapas en ejes compartidos.'},
     'en': {'title': 'Sixty to one', 'goal': 'From seconds to minutes: the output goes round once for every 60 turns of the motor, with no gear over 60 teeth.', 'limits': ['Ratio 1:60', 'No gear over 60 teeth'], 'tip': '60 = 3 × 4 × 5. Three stages on shared axles.'}},
    {'id': 'p1', 'level': 1, 'tab': 'lever', 'setup': {'load': 60}, 'rules': {'load': 60, 'maxEffort': 20},
     'es': {'title': 'Levanta 60 kg con 20 kg', 'goal': 'Mueve el punto de apoyo, la carga y el sitio donde empujas hasta levantar 60 kg haciendo como mucho 20 kg de fuerza.', 'limits': ['Carga de 60 kg', 'Fuerza de 20 kg o menos'], 'tip': 'Cuanto más lejos del apoyo empujas y más cerca está la carga, menos fuerza hace falta.'},
     'en': {'title': 'Lift 60 kg with 20 kg', 'goal': 'Move the pivot, the load and the place where you push until you lift 60 kg with a force of 20 kg at most.', 'limits': ['Load of 60 kg', 'Force of 20 kg or less'], 'tip': 'The further from the pivot you push and the closer the load is, the less force you need.'}},
    {'id': 'p2', 'level': 2, 'tab': 'lever', 'setup': {'load': 60}, 'rules': {'load': 60, 'kind': 2, 'maxEffort': 30},
     'es': {'title': 'Como una carretilla', 'goal': 'Monta una palanca de segundo tipo: el apoyo en un extremo, la carga en medio y la fuerza en el otro extremo. 60 kg con 30 kg o menos.', 'limits': ['Palanca de segundo tipo', 'Fuerza de 30 kg o menos'], 'tip': 'En la carretilla, la rueda es el apoyo y tú levantas por los mangos.'},
     'en': {'title': 'Like a wheelbarrow', 'goal': 'Build a second-class lever: pivot at one end, load in the middle and force at the other end. 60 kg with 30 kg or less.', 'limits': ['Second-class lever', 'Force of 30 kg or less'], 'tip': 'In a wheelbarrow, the wheel is the pivot and you lift the handles.'}},
    {'id': 'p3', 'level': 2, 'tab': 'lever', 'setup': {'load': 10}, 'rules': {'load': 10, 'kind': 3, 'maxEffort': 25},
     'es': {'title': 'Como unas pinzas', 'goal': 'Palanca de tercer tipo: la fuerza va entre el apoyo y la carga. Mueve 10 kg sin pasar de 25 kg de fuerza.', 'limits': ['Palanca de tercer tipo', 'Fuerza de 25 kg o menos'], 'tip': 'Este tipo pide más fuerza que la carga, pero la punta se mueve más y más rápido. Así funcionan tu brazo y unas pinzas.'},
     'en': {'title': 'Like tweezers', 'goal': 'Third-class lever: the force goes between the pivot and the load. Move 10 kg with no more than 25 kg of force.', 'limits': ['Third-class lever', 'Force of 25 kg or less'], 'tip': 'This kind needs more force than the load, but the tip moves further and faster. Your arm and tweezers work like this.'}},
    {'id': 'p4', 'level': 4, 'tab': 'lever', 'setup': {'load': 500}, 'rules': {'load': 500, 'maxEffort': 50},
     'es': {'title': 'Media tonelada', 'goal': 'Con una tabla de 3 m, levanta 500 kg haciendo como mucho 50 kg de fuerza.', 'limits': ['Carga de 500 kg', 'Fuerza de 50 kg o menos'], 'tip': 'Necesitas una ventaja de 10: el brazo de la fuerza, diez veces el de la carga.'},
     'en': {'title': 'Half a tonne', 'goal': 'With a 3 m plank, lift 500 kg with a force of 50 kg at most.', 'limits': ['Load of 500 kg', 'Force of 50 kg or less'], 'tip': 'You need an advantage of 10: the force arm ten times the load arm.'}},
    {'id': 'q1', 'level': 1, 'tab': 'pulley', 'setup': {'load': 40, 'h': 2}, 'rules': {'load': 40, 'maxEffort': 22},
     'es': {'title': 'La mitad de esfuerzo', 'goal': 'Sube 40 kg haciendo como mucho 22 kg de fuerza.', 'limits': ['Carga de 40 kg', 'Fuerza de 22 kg o menos'], 'tip': 'La polea fija solo cambia la dirección. La polea móvil reparte el peso entre dos tramos de cuerda.'},
     'en': {'title': 'Half the effort', 'goal': 'Raise 40 kg with a force of 22 kg at most.', 'limits': ['Load of 40 kg', 'Force of 22 kg or less'], 'tip': 'A fixed pulley only changes the direction. A movable pulley shares the weight between two lengths of rope.'}},
    {'id': 'q2', 'level': 2, 'tab': 'pulley', 'setup': {'load': 100, 'h': 2}, 'rules': {'load': 100, 'maxEffort': 30},
     'es': {'title': '100 kg con menos de 30', 'goal': 'Sube 100 kg haciendo menos de 30 kg de fuerza.', 'limits': ['Carga de 100 kg', 'Fuerza de 30 kg o menos'], 'tip': 'Cada polea pierde un poco por el rozamiento. Mira la diferencia entre la fuerza ideal y la real.'},
     'en': {'title': '100 kg with under 30', 'goal': 'Raise 100 kg with a force under 30 kg.', 'limits': ['Load of 100 kg', 'Force of 30 kg or less'], 'tip': 'Each pulley loses a little to friction. Look at the difference between the ideal and the real force.'}},
    {'id': 'q3', 'level': 3, 'tab': 'pulley', 'setup': {'load': 50, 'h': 2}, 'rules': {'load': 50, 'height': 2, 'maxEffort': 20, 'maxRope': 8},
     'es': {'title': 'Poca fuerza y poca cuerda', 'goal': 'Sube 50 kg a 2 m de altura con menos de 20 kg de fuerza y sin tirar de más de 8 m de cuerda.', 'limits': ['50 kg a 2 m', 'Fuerza de 20 kg o menos', 'Cuerda de 8 m o menos'], 'tip': 'Más tramos de cuerda: menos fuerza, pero más cuerda. Busca el equilibrio.'},
     'en': {'title': 'Little force and little rope', 'goal': 'Raise 50 kg to a height of 2 m with under 20 kg of force and pulling no more than 8 m of rope.', 'limits': ['50 kg to 2 m', 'Force of 20 kg or less', 'Rope of 8 m or less'], 'tip': 'More lengths of rope: less force, but more rope. Find the balance.'}},
    {'id': 'q4', 'level': 4, 'tab': 'pulley', 'setup': {'load': 1000, 'h': 3}, 'rules': {'load': 1000, 'height': 3, 'maxEffort': 250, 'maxRope': 20},
     'es': {'title': 'Una tonelada', 'goal': 'Sube 1000 kg a 3 m con 250 kg de fuerza o menos (por ejemplo, entre cuatro personas) y 20 m de cuerda como mucho.', 'limits': ['1000 kg a 3 m', 'Fuerza de 250 kg o menos', 'Cuerda de 20 m o menos'], 'tip': 'Las grúas de obra usan polipastos con muchos tramos de cuerda.'},
     'en': {'title': 'One tonne', 'goal': 'Raise 1000 kg to 3 m with 250 kg of force or less (for example, four people) and 20 m of rope at most.', 'limits': ['1000 kg to 3 m', 'Force of 250 kg or less', 'Rope of 20 m or less'], 'tip': 'Building-site cranes use pulley blocks with many lengths of rope.'}},
    {'id': 'k1', 'level': 1, 'tab': 'chain', 'rules': {'steps': 3},
     'es': {'title': 'Una cadena de tres', 'goal': 'Planea una máquina de tres pasos en la que cada paso empieza con el movimiento con el que acaba el anterior. Escribe qué hace cada uno.', 'limits': ['3 pasos', 'Todos encajan', 'Cada paso con su texto'], 'tip': 'Por ejemplo: una canica rueda por una rampa, cae sobre una palanca y la palanca empuja un dominó.'},
     'en': {'title': 'A chain of three', 'goal': 'Plan a three-step machine where each step starts with the movement the one before ends with. Write what each one does.', 'limits': ['3 steps', 'All fit together', 'Each step with its text'], 'tip': 'For example: a marble rolls down a ramp, drops onto a lever and the lever pushes a domino.'}},
    {'id': 'k2', 'level': 3, 'tab': 'chain', 'rules': {'steps': 6, 'kinds': 4},
     'es': {'title': 'Seis pasos, cuatro piezas', 'goal': 'Una máquina de seis pasos que encajan, con cuatro tipos de pieza distintos como mínimo.', 'limits': ['6 pasos', '4 tipos de pieza', 'Todos encajan', 'Cada paso con su texto'], 'tip': 'Los engranajes y las ruedas convierten un tirón en giro y un giro en rodar.'},
     'en': {'title': 'Six steps, four parts', 'goal': 'A machine of six steps that fit together, with at least four different kinds of part.', 'limits': ['6 steps', '4 kinds of part', 'All fit together', 'Each step with its text'], 'tip': 'Gears and wheels turn a pull into a turn and a turn into rolling.'}},
    {'id': 'g7', 'level': 5, 'tab': 'gears', 'random': True, 'rules': {},
     'es': {'title': 'Relación sorpresa', 'goal': 'Cada vez sale una relación distinta. Monta un tren de engranajes que la cumpla exactamente. Con «Otra relación» sale otra, sin fin.', 'limits': ['La relación y el sentido que pida'], 'tip': 'Descompón la fracción: 5/16 es 1/2 × 5/8, o 10 dientes contra 32.'},
     'en': {'title': 'Surprise ratio', 'goal': 'A different ratio comes up each time. Build a gear train that matches it exactly. “Another ratio” gives you a new one, endlessly.', 'limits': ['The ratio and direction it asks for'], 'tip': 'Split the fraction: 5/16 is 1/2 × 5/8, or 10 teeth against 32.'}},
    {'id': 'k3', 'level': 5, 'tab': 'chain', 'rules': {'steps': 10, 'kinds': 6},
     'es': {'title': 'La gran máquina', 'goal': 'Diez pasos o más que encajan, con seis tipos de pieza como mínimo. Después, si quieres, constrúyela de verdad con lo que tengas en casa.', 'limits': ['10 pasos o más', '6 tipos de pieza', 'Todos encajan', 'Cada paso con su texto'], 'tip': 'Imprime la lista: te sirve de guion para montarla.'},
     'en': {'title': 'The great machine', 'goal': 'Ten or more steps that fit together, with at least six kinds of part. Then, if you like, build it for real with what you have at home.', 'limits': ['10 steps or more', '6 kinds of part', 'All fit together', 'Each step with its text'], 'tip': 'Print the list: it works as a script for building it.'}},
]

STRINGS = {
    'es': {
        'thN': 'N.º', 'mPng': 'Guardar imagen PNG', 'mMadeIn': 'hecho en el Taller', 'mNewDone': 'Máquinas nuevas', 'mTabs': 'Máquina', 'mTab_gears': 'Engranajes', 'mTab_lever': 'Palanca', 'mTab_pulley': 'Poleas', 'mTab_chain': 'Máquina en cadena',
        'mTeeth': 'Dientes', 'mTeethN': '{n} dientes', 'mGearN': 'Engranaje {n} ({z} dientes)', 'mHow': 'Cómo se une', 'mHow_mesh': 'Engrana al lado de…', 'mHow_front': 'En el mismo eje, delante de…', 'mHow_back': 'En el mismo eje, detrás de…',
        'mNextTo': 'Engranaje de referencia', 'mDirection': 'Hacia dónde', 'mDir_0': 'Derecha', 'mDir_45': 'Abajo a la derecha', 'mDir_90': 'Abajo', 'mDir_135': 'Abajo a la izquierda', 'mDir_180': 'Izquierda', 'mDir_225': 'Arriba a la izquierda', 'mDir_270': 'Arriba', 'mDir_315': 'Arriba a la derecha',
        'mAddGear': 'Añadir engranaje', 'mAddPanel': 'Añadir engranaje', 'mAddNote': 'Los engranajes del mismo eje giran juntos y están en capas distintas: no se tocan con los de otra capa.',
        'mLayerLimit': 'Solo hay cuatro capas: no cabe más delante o detrás.', 'mOccupied': 'Ese eje ya tiene un engranaje en esa capa.', 'mTooMany': 'Has llegado al máximo de piezas.', 'mAdded': 'Engranaje {n} añadido, con {z} dientes',
        'mMotorPanel': 'Motor', 'mRpm': 'Velocidad del motor (vueltas por minuto)', 'mMotorDir': 'Sentido del motor', 'mCW': 'sentido horario', 'mCCW': 'sentido antihorario',
        'mMotor': 'Motor', 'mOutput': 'Salida', 'mMakeMotor': 'Motor: engranaje {n}', 'mMakeOut': 'Salida: engranaje {n}', 'mRemove': 'Quitar engranaje {n}', 'mRemoved': 'Quitado',
        'mLoose': 'suelto, no gira', 'mLayerN': 'capa {n}', 'mGearsCap': 'Engranajes ({n})', 'mThTeeth': 'Dientes', 'mThLayer': 'Capa', 'mThSpeed': 'Velocidad', 'mThDir': 'Sentido', 'mThTorque': 'Par', 'mThRole': 'Papel', 'mThActions': 'Acciones',
        'mTurnEvery': 'una vuelta cada {s} s', 'mSpin': 'Girar', 'mStop': 'Parar', 'mTime': 'Tiempo (segundos)', 'mSpinReduced': 'Movimiento reducido: avanzan 5 segundos de golpe.', 'mSpinning': 'Girando', 'mStopped': 'Parado',
        'mLeverPanel': 'Palanca de 3 m', 'mFulcrum': 'Punto de apoyo', 'mLoadPos': 'Carga', 'mEffortPos': 'Donde empujas', 'mLoadKg': 'Carga (kg)', 'mLeverNote': 'Las posiciones se miden desde el extremo izquierdo de la tabla. El peso de la tabla no se cuenta.',
        'mPulleyPanel': 'Poleas', 'mPulleyKind': 'Montaje', 'mPulley_fija': 'Polea fija', 'mPulley_movil': 'Polea móvil', 'mPulley_pol2': 'Polipasto de 2 tramos', 'mPulley_pol3': 'Polipasto de 3 tramos', 'mPulley_pol4': 'Polipasto de 4 tramos', 'mPulley_pol6': 'Polipasto de 6 tramos',
        'mHeight': 'Altura a subir (m)', 'mPulleyNote': 'Cada polea móvil pesa 0,4 kg y cada polea pierde un 5 % por rozamiento.', 'mRopesN': '{n} tramos sostienen la carga', 'mRopes1': 'Un tramo sostiene la carga',
        'mChainPanel': 'Añadir paso', 'mPart': 'Pieza', 'mAddStep': 'Añadir paso', 'mStepAdded': 'Paso {n} añadido. Escribe qué hace.', 'mChainNote': 'Un paso encaja si empieza con el movimiento con el que acaba el anterior. La salida de cada pieza se puede cambiar en la tabla.',
        'mPart_rampa': 'Rampa', 'mPart_palanca': 'Palanca', 'mPart_polea': 'Polea', 'mPart_engranaje': 'Engranaje', 'mPart_domino': 'Dominó', 'mPart_pendulo': 'Péndulo', 'mPart_muelle': 'Muelle', 'mPart_balanza': 'Balanza', 'mPart_embudo': 'Embudo', 'mPart_rueda': 'Rueda', 'mPart_cuerda': 'Cuerda', 'mPart_canica': 'Canica',
        'mMove_caida': 'caída', 'mMove_rodar': 'rodar', 'mMove_empujon': 'empujón', 'mMove_giro': 'giro', 'mMove_tiron': 'tirón', 'mMove_balanceo': 'balanceo', 'mMove_agua': 'agua',
        'mChainEmpty': 'Todavía no hay pasos. Elige una pieza y pulsa «Añadir paso».', 'mChainCap': 'Pasos de la máquina ({n})', 'mWhat': 'Qué hace', 'mInp': 'Empieza con', 'mOut': 'Acaba con',
        'mInpN': 'Paso {n}: empieza con', 'mOutN': 'Paso {n}: acaba con', 'mPartN': 'Paso {n}: pieza', 'mTextN': 'Paso {n}: qué hace', 'mUpN': 'Subir el paso {n}', 'mDownN': 'Bajar el paso {n}', 'mDelN': 'Quitar el paso {n}', 'mMoved': 'Ahora es el paso {n}', 'mNoFit': 'no encaja con el anterior',
        'mResult': 'Resultado', 'mJam': 'Bloqueado: hay engranajes que tendrían que girar a dos velocidades a la vez.', 'mCollide': 'Hay {n} choques: engranajes que se pisan sin engranar (línea roja discontinua).',
        'mMotorLine': 'Motor (engranaje {n}): {s}, {d}.', 'mOutLine': 'Salida (engranaje {n}): {s}, {d}. Relación {p}:{q}. Par ×{tq}.', 'mNoOut': 'Marca un engranaje como salida en la tabla para ver la relación.', 'mLooseLine': 'Sueltos, sin girar: {l}.',
        'mEffortOnFulcrum': 'Estás empujando justo en el punto de apoyo: así no se mueve.', 'mLeverLine': 'Hace falta una fuerza de {e} kg para levantar {l} kg. Ventaja: ×{a}.',
        'mKind_1': 'Palanca de primer tipo: el apoyo está entre la carga y la fuerza (como un balancín).', 'mKind_2': 'Palanca de segundo tipo: la carga está entre el apoyo y la fuerza (como una carretilla).', 'mKind_3': 'Palanca de tercer tipo: la fuerza está entre el apoyo y la carga (como unas pinzas).',
        'mPulleyLine': 'Fuerza real: {e} kg (ideal, sin rozamiento: {i} kg). Tramos de cuerda que sostienen la carga: {n}. Para subir {h} m hay que tirar de {r} m de cuerda.', 'mWork': 'Trabajo para subir la carga: {j} julios. Las poleas no lo reducen: reparten el esfuerzo en más cuerda.',
        'mChainLine': '{n} pasos, {b} sin encajar, {k} tipos de pieza.',
        'mCanvas_gears': 'Dibujo del tren de engranajes. Los datos están en la tabla y en el texto de debajo.', 'mCanvas_lever': 'Dibujo de la palanca con el apoyo, la carga y la fuerza.', 'mCanvas_pulley': 'Dibujo del montaje de poleas con la carga y la cuerda.', 'mCanvas_chain': 'Dibujo de los pasos de la máquina en cadena.',
        'mAltTitle': 'Descripción en texto', 'mAltGear': 'Engranaje {n}: {z} dientes, capa {l}, {s}.', 'mAlt_lever': 'La tabla mide 3 m. El resultado de arriba dice dónde están el apoyo, la carga y la fuerza, y cuánta fuerza hace falta.', 'mAlt_pulley': 'El resultado de arriba dice cuántos tramos de cuerda sostienen la carga, la fuerza y la cuerda necesarias.',
        'mAnother': 'Otra relación', 'mRandomGoal': 'Objetivo: relación {p}:{q}, {d}.', 'mSameDir': 'en el mismo sentido que el motor', 'mOppDir': 'en sentido contrario al motor',
        'mChkFree': 'Sin bloqueos ni choques', 'mChkOut': 'Hay un engranaje de salida que gira', 'mChkRatio': 'Relación {p}:{q} (ahora {g})', 'mChkSameDir': 'Salida en el mismo sentido que el motor', 'mChkOppDir': 'Salida en sentido contrario al motor',
        'mChkTorque': 'Par ×{m} o más (ahora ×{g})', 'mChkMaxTeeth': 'Ningún engranaje de más de {m} dientes', 'mChkMaxGears': 'Como mucho {m} engranajes (ahora {n})',
        'mChkEffort': 'Fuerza de {m} kg o menos (ahora {g} kg)', 'mChkKind': 'Palanca de tipo {k}', 'mChkAdv': 'Ventaja de ×{m} o más', 'mChkAdvMax': 'Ventaja de ×{m} o menos', 'mChkLoad': 'Carga de {m} kg o más', 'mChkHeight': 'Subir {m} m o más', 'mChkRope': 'Cuerda de {m} m o menos (ahora {g} m)',
        'mChkSteps': 'Al menos {m} pasos (ahora {n})', 'mChkFit': 'Todos los pasos encajan ({b} sin encajar)', 'mChkKinds': 'Al menos {m} tipos de pieza (ahora {n})', 'mChkTexts': 'Cada paso dice qué hace',
        'mDone': 'Reto cumplido', 'mNotYet': 'Todavía no: mira la lista.',
    },
    'en': {
        'thN': 'No.', 'mPng': 'Save PNG image', 'mMadeIn': 'made in the Workshop', 'mNewDone': 'New machines', 'mTabs': 'Machine', 'mTab_gears': 'Gears', 'mTab_lever': 'Lever', 'mTab_pulley': 'Pulleys', 'mTab_chain': 'Chain machine',
        'mTeeth': 'Teeth', 'mTeethN': '{n} teeth', 'mGearN': 'Gear {n} ({z} teeth)', 'mHow': 'How it joins', 'mHow_mesh': 'Meshes beside…', 'mHow_front': 'On the same axle, in front of…', 'mHow_back': 'On the same axle, behind…',
        'mNextTo': 'Reference gear', 'mDirection': 'Which way', 'mDir_0': 'Right', 'mDir_45': 'Down and right', 'mDir_90': 'Down', 'mDir_135': 'Down and left', 'mDir_180': 'Left', 'mDir_225': 'Up and left', 'mDir_270': 'Up', 'mDir_315': 'Up and right',
        'mAddGear': 'Add gear', 'mAddPanel': 'Add gear', 'mAddNote': 'Gears on the same axle turn together and sit on different layers: they do not touch gears on another layer.',
        'mLayerLimit': 'There are only four layers: nothing more fits in front or behind.', 'mOccupied': 'That axle already has a gear on that layer.', 'mTooMany': 'You have reached the maximum number of parts.', 'mAdded': 'Gear {n} added, with {z} teeth',
        'mMotorPanel': 'Motor', 'mRpm': 'Motor speed (turns per minute)', 'mMotorDir': 'Motor direction', 'mCW': 'clockwise', 'mCCW': 'anticlockwise',
        'mMotor': 'Motor', 'mOutput': 'Output', 'mMakeMotor': 'Motor: gear {n}', 'mMakeOut': 'Output: gear {n}', 'mRemove': 'Remove gear {n}', 'mRemoved': 'Removed',
        'mLoose': 'loose, not turning', 'mLayerN': 'layer {n}', 'mGearsCap': 'Gears ({n})', 'mThTeeth': 'Teeth', 'mThLayer': 'Layer', 'mThSpeed': 'Speed', 'mThDir': 'Direction', 'mThTorque': 'Torque', 'mThRole': 'Role', 'mThActions': 'Actions',
        'mTurnEvery': 'one turn every {s} s', 'mSpin': 'Turn', 'mStop': 'Stop', 'mTime': 'Time (seconds)', 'mSpinReduced': 'Reduced motion: they jump forward 5 seconds at once.', 'mSpinning': 'Turning', 'mStopped': 'Stopped',
        'mLeverPanel': '3 m lever', 'mFulcrum': 'Pivot', 'mLoadPos': 'Load', 'mEffortPos': 'Where you push', 'mLoadKg': 'Load (kg)', 'mLeverNote': 'Positions are measured from the left end of the plank. The weight of the plank is not counted.',
        'mPulleyPanel': 'Pulleys', 'mPulleyKind': 'Set-up', 'mPulley_fija': 'Fixed pulley', 'mPulley_movil': 'Movable pulley', 'mPulley_pol2': 'Pulley block, 2 ropes', 'mPulley_pol3': 'Pulley block, 3 ropes', 'mPulley_pol4': 'Pulley block, 4 ropes', 'mPulley_pol6': 'Pulley block, 6 ropes',
        'mHeight': 'Height to raise (m)', 'mPulleyNote': 'Each movable pulley weighs 0.4 kg and each pulley loses 5% to friction.', 'mRopesN': '{n} lengths of rope hold the load', 'mRopes1': 'One length of rope holds the load',
        'mChainPanel': 'Add step', 'mPart': 'Part', 'mAddStep': 'Add step', 'mStepAdded': 'Step {n} added. Write what it does.', 'mChainNote': 'A step fits if it starts with the movement the one before ends with. You can change what each part ends with in the table.',
        'mPart_rampa': 'Ramp', 'mPart_palanca': 'Lever', 'mPart_polea': 'Pulley', 'mPart_engranaje': 'Gear', 'mPart_domino': 'Domino', 'mPart_pendulo': 'Pendulum', 'mPart_muelle': 'Spring', 'mPart_balanza': 'Balance', 'mPart_embudo': 'Funnel', 'mPart_rueda': 'Wheel', 'mPart_cuerda': 'String', 'mPart_canica': 'Marble',
        'mMove_caida': 'fall', 'mMove_rodar': 'roll', 'mMove_empujon': 'push', 'mMove_giro': 'turn', 'mMove_tiron': 'pull', 'mMove_balanceo': 'swing', 'mMove_agua': 'water',
        'mChainEmpty': 'No steps yet. Choose a part and press “Add step”.', 'mChainCap': 'Machine steps ({n})', 'mWhat': 'What it does', 'mInp': 'Starts with', 'mOut': 'Ends with',
        'mInpN': 'Step {n}: starts with', 'mOutN': 'Step {n}: ends with', 'mPartN': 'Step {n}: part', 'mTextN': 'Step {n}: what it does', 'mUpN': 'Move step {n} up', 'mDownN': 'Move step {n} down', 'mDelN': 'Remove step {n}', 'mMoved': 'Now it is step {n}', 'mNoFit': 'does not fit the one before',
        'mResult': 'Result', 'mJam': 'Jammed: some gears would have to turn at two speeds at once.', 'mCollide': 'There are {n} clashes: gears that overlap without meshing (dashed red line).',
        'mMotorLine': 'Motor (gear {n}): {s}, {d}.', 'mOutLine': 'Output (gear {n}): {s}, {d}. Ratio {p}:{q}. Torque ×{tq}.', 'mNoOut': 'Mark a gear as the output in the table to see the ratio.', 'mLooseLine': 'Loose, not turning: {l}.',
        'mEffortOnFulcrum': 'You are pushing right on the pivot: that way nothing moves.', 'mLeverLine': 'You need a force of {e} kg to lift {l} kg. Advantage: ×{a}.',
        'mKind_1': 'First-class lever: the pivot is between the load and the force (like a seesaw).', 'mKind_2': 'Second-class lever: the load is between the pivot and the force (like a wheelbarrow).', 'mKind_3': 'Third-class lever: the force is between the pivot and the load (like tweezers).',
        'mPulleyLine': 'Real force: {e} kg (ideal, without friction: {i} kg). Lengths of rope holding the load: {n}. To raise it {h} m you pull {r} m of rope.', 'mWork': 'Work to raise the load: {j} joules. Pulleys do not reduce it: they spread the effort over more rope.',
        'mChainLine': '{n} steps, {b} not fitting, {k} kinds of part.',
        'mCanvas_gears': 'Drawing of the gear train. The data is in the table and in the text below.', 'mCanvas_lever': 'Drawing of the lever with the pivot, the load and the force.', 'mCanvas_pulley': 'Drawing of the pulley set-up with the load and the rope.', 'mCanvas_chain': 'Drawing of the steps of the chain machine.',
        'mAltTitle': 'Text description', 'mAltGear': 'Gear {n}: {z} teeth, layer {l}, {s}.', 'mAlt_lever': 'The plank is 3 m long. The result above says where the pivot, the load and the force are, and how much force you need.', 'mAlt_pulley': 'The result above says how many lengths of rope hold the load, and the force and rope you need.',
        'mAnother': 'Another ratio', 'mRandomGoal': 'Goal: ratio {p}:{q}, {d}.', 'mSameDir': 'in the same direction as the motor', 'mOppDir': 'in the opposite direction to the motor',
        'mChkFree': 'No jams or clashes', 'mChkOut': 'There is an output gear that turns', 'mChkRatio': 'Ratio {p}:{q} (now {g})', 'mChkSameDir': 'Output in the same direction as the motor', 'mChkOppDir': 'Output in the opposite direction to the motor',
        'mChkTorque': 'Torque ×{m} or more (now ×{g})', 'mChkMaxTeeth': 'No gear over {m} teeth', 'mChkMaxGears': 'At most {m} gears (now {n})',
        'mChkEffort': 'Force of {m} kg or less (now {g} kg)', 'mChkKind': 'Class {k} lever', 'mChkAdv': 'Advantage of ×{m} or more', 'mChkAdvMax': 'Advantage of ×{m} or less', 'mChkLoad': 'Load of {m} kg or more', 'mChkHeight': 'Raise it {m} m or more', 'mChkRope': 'Rope of {m} m or less (now {g} m)',
        'mChkSteps': 'At least {m} steps (now {n})', 'mChkFit': 'All steps fit together ({b} not fitting)', 'mChkKinds': 'At least {m} kinds of part (now {n})', 'mChkTexts': 'Each step says what it does',
        'mDone': 'Challenge complete', 'mNotYet': 'Not yet: check the list.',
    },
}
assert set(STRINGS['es']) == set(STRINGS['en'])

PAGE = {
    'es': {
        'title': 'Estudio de máquinas',
        'description': 'Engranajes, palancas, poleas y máquinas en cadena calculados en directo: velocidad, sentido, fuerza y cuerda, con retos por niveles.',
        'lede': 'Máquinas simples de verdad. Monta trenes de engranajes y mira a qué velocidad y en qué sentido gira cada uno; mueve el apoyo de una palanca; elige poleas para subir una tonelada; planea una máquina en cadena paso a paso.',
        'pills': ['Engranajes, palanca y poleas', 'Cálculo en directo', 'Tabla y texto de cada pieza', 'Máquina en cadena para imprimir', '18 retos en 5 niveles', 'Movimiento solo si lo pides'],
        'steps': [
            'Elige una máquina arriba del dibujo, o un reto.',
            'En Engranajes, añade piezas desde el panel: al lado de otra, o en el mismo eje. Marca en la tabla cuál es el motor y cuál la salida.',
            'En Palanca y Poleas, mueve los valores del panel y mira cuánta fuerza hace falta.',
            'En Máquina en cadena, añade pasos y escribe qué hace cada uno. El estudio avisa si un paso no encaja con el anterior.',
            'Los retos se comprueban solos. Guarda el proyecto en un archivo o imprime la lista de pasos.',
        ],
        'sections': [
            {'h': 'Cómo calcula', 'p': 'Engranajes: todos tienen dientes del mismo tamaño (módulo 2 mm), así que el tamaño depende del número de dientes. Dos engranajes que se tocan giran en sentidos contrarios, y la velocidad cambia en proporción inversa a los dientes: 20 contra 60 gira tres veces más despacio y con tres veces más par. Los del mismo eje giran juntos.\n\nPalanca: la fuerza por su distancia al apoyo es igual a la carga por su distancia al apoyo.\n\nPoleas: la carga se reparte entre los tramos de cuerda que la sostienen, pero hay que tirar de más cuerda. Se cuenta un 5 % de pérdida por rozamiento en cada polea y 0,4 kg por cada polea móvil.',
             'li': ['Es un modelo para aprender: no sustituye al cálculo de una máquina real ni a las normas de seguridad para levantar cargas.',
                    'Las velocidades se dan en vueltas por minuto (rpm). El par se da como múltiplo del par del motor.']},
        ],
        'links': [('Estudio de circuitos: motores e interruptores', '/es/taller/circuitos/'), ('Estudio de estructuras: puentes y torres', '/es/taller/estructuras/'), ('Estudio de robótica', '/es/taller/robotica/'), ('Volver al Taller', '/es/taller/')],
        'credits': 'Estudio de máquinas de Iris Green. Cálculo propio en el navegador, sin servicios externos.',
    },
    'en': {
        'title': 'Machines studio',
        'description': 'Gears, levers, pulleys and chain machines calculated live: speed, direction, force and rope, with levelled challenges.',
        'lede': 'Real simple machines. Build gear trains and see how fast and which way each one turns; move the pivot of a lever; choose pulleys to raise a tonne; plan a chain machine step by step.',
        'pills': ['Gears, lever and pulleys', 'Live calculation', 'Table and text for each part', 'Printable chain machine', '18 challenges on 5 levels', 'Motion only when you ask'],
        'steps': [
            'Choose a machine above the drawing, or a challenge.',
            'In Gears, add parts from the panel: beside another one, or on the same axle. Mark in the table which one is the motor and which one the output.',
            'In Lever and Pulleys, change the values in the panel and see how much force you need.',
            'In Chain machine, add steps and write what each one does. The studio tells you if a step does not fit the one before.',
            'Challenges check themselves. Save the project to a file or print the list of steps.',
        ],
        'sections': [
            {'h': 'How it calculates', 'p': 'Gears: all of them have teeth of the same size (module 2 mm), so their size depends on the number of teeth. Two gears that touch turn in opposite directions, and the speed changes in inverse proportion to the teeth: 20 against 60 turns three times slower with three times the torque. Gears on the same axle turn together.\n\nLever: the force times its distance to the pivot equals the load times its distance to the pivot.\n\nPulleys: the load is shared between the lengths of rope that hold it, but you have to pull more rope. A 5% friction loss is counted for each pulley and 0.4 kg for each movable pulley.',
             'li': ['It is a model for learning: it does not replace the calculation of a real machine or the safety rules for lifting loads.',
                    'Speeds are given in turns per minute (rpm). Torque is given as a multiple of the motor’s torque.']},
        ],
        'links': [('Circuits studio: motors and switches', '/en/workshop/circuits/'), ('Structures studio: bridges and towers', '/en/workshop/structures/'), ('Robotics studio', '/en/workshop/robotics/'), ('Back to the Workshop', '/en/workshop/')],
        'credits': 'Iris Green machines studio. Own calculation in the browser, with no external services.',
    },
}
